<blockquote class="prechapter">
  “The most lively thought is still inferior to the dullest sensation.”
  <div class="attrib">
    &mdash; David Hume (1711-1776)
  </div>
</blockquote>

<div class="chapsection">
<p>
<span class="caplead">Peanut shells crunched under the soles</span> of Eugene’s designer sneakers. He leaned against the carving-pocked bar, careful to avoid dipping the elbow of his custom-fit leather jacket into something sticky and unnameable. Around him, tattooed men with large bellies and larger beards swigged Jack Daniels and bragged about the horsepower of their “hogs” beneath the blare of the jukebox.
</p>
<p>
“I didn’t mean to make trouble, Eugene,” a young, thin man said with a gulp.
</p>
<p>
Eugene clapped a hand firmly on his shoulder. It could have been a gesture of friendship, but it wasn’t. “You cheat us, and think this wouldn’t make trouble?” Eugene said sweetly. He spoke fluidly, but his hard consonants and throaty vowels betrayed his Russian origins. 
</p>
<p>
“It’s not just me!” the fellow said shakily. “Jimmy jumped last week, and Martinez…”
</p>
<p>
Eugene slid his hand up toward the man’s neck. “Do you think Sergey and I aren’t <em>painfully</em> aware of that, Francisco? How much is the street price for loyalty?”
</p>
<p>
“I… like selling for you, Eugene,” Francisco stammered. “You and Sergey, you always treat me good. It’s just…”
</p>
<p>
“This new supplier’s product is <em>so</em> much better, right?”
</p>
<p>
Francisco’s lips trembled. “Her staple is better than your samplers, chief,” he said almost apologetically. “But that’s not the point.”
</p>
<p>
Eugene’s eyes narrowed. “What <em>is</em> the point, Francisco?”
</p>
<p>
Through a dry mouth, he murmured, “She charges a fifth of your prices.”</p>
<p>
Eugene leaned in, pulling Francisco’s face to his ear. “I’m sorry. I don’t think I heard you right. You said she’s undercutting us by a <em>fifth</em>?”</p>
<p>
“Undercutting you <em>to</em> a fifth. What you sell for a grand, she sells for two hundred. They say she makes it locally, chief. She can, like, grow it in a tub of saltwater or something. Like with pot. Some kind of hy-<em>dro</em>-ponic…”</p>
<p>
Eugene rolled his eyes. “Francisco, how did you get to be a salesman without knowing shit about your product? Coca is not like hemp. Each bush has very little usable material. A kilogram of coca leaves will only yield five grams of blow. Farms need to harvest acres of crop just to break even. You would know this if you were not an idiot.”
</p>
<p>
“Look, I don’t know how it works, chief,” Francisco pleaded. “I’m just saying what I heard. Look at her prices, though. It checks out, right? She’s got no import costs. No cartel dues. No <em>Federales</em> bribes. Maybe she knows something you don’t.”
</p>
<p>
Eugene’s fingers closed around Francisco’s throat. He looked into his reddening eyes and hissed, “You betray us for this utter bullshit…?”
</p>
<p>
Gasping, Francisco honked out through his squeezed larynx, “See for yourself, chief!” He reached out with one thin arm and pointed toward the back of the bar.
</p>
<p>
Eugene’s gaze followed his trembling finger past silhouettes of gruff drunks. Near the pool table in the back, the crowd simply stopped, like a sea held back by an invisible dam. There, on a tall bar stool, sat a young Asian woman drinking a fluorescent cocktail. Eugene couldn’t make out details, but, amid all the denim vests and grease-stained jeans, her sleek white dress and gladiator stilettos stuck out like a Viagra in a bag of molly.
</p>
<p>
“She’s <em>here</em>?” Eugene grunted. He released his hold on Francisco, who coughed and wheezed as he reclaimed his breath. “<em>That’s</em> who’s muscling in on our area?”
</p>
<p>
“She showed up about two weeks ago,” said Francisco, his voice still raspy. “She’s been using this joint for a recruiting ground. Been here about half a dozen times. Each time she comes, she gets more people signing up to sell for her.”
</p>
<p>
Eugene squinted. A pink Hello Kitty purse rested on the girl’s lap. “She doesn’t even look old enough to be drinking.”
</p>
<p>
“She’s been growing a network real damn fast,” Francisco explained. “I figured, the way she’s going, pretty soon I’d be working for her anyway. And eventually, so would you.”
</p>
<p>
Eugene smacked him hard upside the head. “Get the fuck out of here, Francisco. Go. Leave town. If Sergey or I ever see you again, you’re a dead man.”
</p>
<p>
Sparing not a moment, the youth pushed himself away from the bar and scuttled hastily to the door.
</p>
<p>
Eugene stayed put, watching the girl keenly. Three muscular men shared the empty area with her &mdash; one by her side, the other two absorbed in a game of pool. He pulled out his cellphone. “<span class="computer">Sergey</span>,” he typed. “<span class="computer">Get down here. You have to see this.</span>”
</p>
<p>
A reply came almost immediately. “<span class="computer">Busy. Picking the music with Rosie for dance recital. Are you having something more important than evening with daughter?</span>”
</p>
<p>
Eugene carefully slipped his way through the crowd toward the back of the bar. He angled the phone’s camera at the Asian girl, waited for some biker to move his enormous head, and snapped a photo. “<span class="computer">In Renton</span>,” he typed beneath the image attachment. “<span class="computer">Just take the Tesla, drive is less than 10 minutes.</span>”
</p>
<p>
He waited for a reply. None came.
</p>
<p>
Before him, the girl sat and drank, texting furiously on her cell, saying nothing to her three large companions. Her foot wagged cheerfully like a dog’s tail. Occasionally she would reach a hand into her Hello Kitty purse and withdraw it carefully, one manicured fingernail held upturned like a spoon, carrying a small scoop of fine white powder that promptly disappeared up her nose.
</p>
<p>
Eugene glanced at his phone. Still no word from Sergey. With a grimace, he rolled his shoulders, cracked his knuckles, and strode forward.
</p>
<p>
The bodyguard’s arm immediately barred his approach.
</p>
<p>
“I want a word with the lady,” Eugene said.
</p>
<p>
“Lady doesn’t want to talk to you,” the guard replied. 
</p>
<p>
Eugene talked past him, directly to the girl. “Have you heard of Sergey Mukhayev?”
</p>
<p>
She cocked an eyebrow and put away her cellphone. “Let him through,” she said. The guard promptly stepped back to resume his post at her side. She spent several silent seconds scrutinizing Eugene, her fingers fiddling against her cocktail glass. Her pupils were the size of dimes. “So,” she finally said. “I figured I’d run into you sooner or later. Eugene, right? I've heard stories.”
</p>
<p>
“Do you have a name?” he asked.
</p>
<p>
The girl sipped her drink. “Julie,” she replied. “Julie Yen. Get to know it. It’ll be a household word.”
</p>
<p>
From this distance, Eugene confirmed his initial impression: the girl was still mostly a child. He shook his head. “What the hell is this? Did your daddy get you a My Little Druglord playset for your birthday?”
</p>
<p>
The guard beside her snarled, “Respect the lady!”
</p>
<p>
Eugene replied, “Your lady is stepping on some very big toes.”
</p>
<p>
The girl chuckled. “Yeah. I bet I am. Thomas Edison stepped on the toes of the candle industry too. And Henry Ford pissed off a lot of horse breeders.”
</p>
<p>
“I don’t know what the fuck you’re talking about, little girl,” said Eugene. “What I do know is that you are in Sergey’s territory. And that means you better start answering a lot of questions if you know what’s good for you.”
</p>
<p>
The stoic bodyguard advanced. “You’re threatening my boss, buddy. Your conversation’s over.”
</p>
<p>
“Where is your source?” Eugene barked over the guard’s shoulder. “Who is your cartel contact? How are you evading Coast Guard patrols?”
</p>
<p>
Julie Yen laughed raucously. “Oh, Eugene! Dear obsolete, useless Eugene! What would be the point of explaining anything? You wouldn’t understand a word I told you.”
</p>
<p>
Eugene noticed that the occasional click of colliding billiard balls behind him had ceased. The two pool players were no longer engrossed in their game. He realized that could mean only one thing: they must be standing right…
</p>
<p>
He ducked down into a squat, spinning and kicking out as he dropped. His leg made contact with an ankle. He crooked his knee, sweeping the foot of one of the men behind him. The would-be assailant fell backward, knocking his head against the pool table as he tumbled. Eugene rose from his squat to deliver his fallen opponent a swift stomp on the chest. Ribs cracked beneath his heel.
</p>
<p>
He turned to the other pool player just in time to see a cue swinging at his face. He leaned into the arc of the swing, grabbed the stick, and spun with its momentum, turning his back toward its wielder. An elbow jab made contact with the attacker’s gut hard enough to sink him to his knees, but the man’s grip on the stick remained firm. Eugene wrestled the cue downward against the floor and pushed until it cracked in two. He grabbed the thicker end and rammed the butt against his attacker’s temple. The kneeling man reeled and collapsed.
</p>
<p>
The bodyguard at Julie’s side approached the melee, reaching out to grapple Eugene with elephant-trunk arms. Eugene quickly scanned the large man’s posture for weaknesses.
</p>
<p>
A pair of hairy, thick-fingered hands appeared beneath the bodyguard’s armpits. They snaked up over his shoulders and joined behind the man’s head, locking his arms in a full nelson. The guard, taken by surprise, struggled to break free from the large unseen figure behind him.
</p>
<p>
Eugene wasted no time. With the broken pool cue still in his hands, he thrust the cracked end into a patch of vulnerable flesh just below the guard’s ribs. The splintered wood tore through cloth, skin, and muscle, and when Eugene released the stick it remained lodged in his torso. The bodyguard emitted a long, powerless grunt and sank to the floor, his blood running down the pool cue. The bartender and patrons looked away furtively as the wounded man crawled toward an exit; they were savvy enough to see and hear nothing.
</p>
<p>
With the bodyguard fallen, Eugene saw the round, rugged face and the massive, middle-aged form of the man who had come to his aid.
</p>
<p>
“Sergey!” Eugene said in his native tongue. “What did you do that for? I could’ve handled him on my own!”
</p>
<p>
Sergey smirked warmly at him. “Where’s this princess that’s causing so much fuss?”
</p>
<p>
The two of them spotted Julie cowering by the back wall, crouching in her couture footwear. She held her barstool in both hands, jabbing it at them like a lion-tamer. There was no place for her to run.
</p>
<p>
Sergey regarded her with a frown. “She’s very young.” 
</p>
<p>
“And high as the moon,” Eugene added. “Apparently she manufactures it herself.” Her Hello Kitty purse lay near his feet &mdash; the girl had tossed it during the scuffle. Eugene squatted down and casually walked his fingers into the purse’s open top to spread it wide enough to peek inside. Amidst mascara and lipstick and a sandwich bag full of powdered cocaine, there was a plain white keycard. It bore a stylized letter <em>W</em> and the inscription, <em>Tungsten Medical Technologies</em>.
</p>
<p>
Sergey nodded. “I’ve heard these rumors. Think they have any truth?”
</p>
<p>
Eugene stood back up and looked at the cowering young woman. “She says we wouldn’t understand the truth,” he said as he and Sergey slowly closed in on her. “But she’ll have plenty of time to explain it to us.”
</p>
</div>
