<div class="chapsection">
<p>
<span class="caplead">Mercury was adorned with grinning gargoyles</span> and occult symbols. Mannequins stood in corners, as though the Medusa sculpture by the door had turned patrons to plastic. Young people with bits of metal in their skin sipped colorful drinks to the buzzing, beeping background music.
</p>
<p>
Danny walked in carrying a Claymore tote bag full of electronic junk. Wires and tubes protruded from the top. He spotted Jason Tuttle alone at a table.
</p>
<p>
“I take it you haven’t been home?” Jason said, eyeing the suit Danny was still wearing from the afternoon’s presentation.
</p>
<p>
“I hung out in the office after our chat.” Danny sat down to join him. “Figured I’d soak in the vibe one last time. Play with the Foosball table. Kick the vending machine.”
</p>
<p>
Jason gestured at Danny’s bag. “But you didn’t walk away empty-handed, I see.”
</p>
<p>
“This? Just a souvenir. Something I made during the Naval Base Kitsap contract. Nothing that anyone but me would miss.”
</p>
<p>
“Is it Claymore property?”
</p>
<p>
“Does it seriously matter anymore?” Danny asked.
</p>
<p>
“Yes, actually. We’re auctioning off Claymore’s assets. Everything’s up for appraisal. The software, the hardware, the furniture, the company van. It’s all for sale. Including whatever <em>that</em> is.”
</p>
<p>
Danny gazed into the bag’s metal-strewn depths. “For <em>sale</em>? You… No. It’s not yours. <em>I</em> designed and built it…”
</p>
<p>
“<em>For</em> Claymore,” Jason insisted.
</p>
<p>
Danny reached inside and fished out a foot-long, six-inch-wide flared metal tube. Attached was a rubber-coated handle with a plastic trigger near the top. Metal blocks protruded from its back, connected to cables that dangled down into the bag. Danny held the assembly delicately by the pistol grip. His eyes traced the device’s contours like fingertips across a lover’s body.
</p>
<p>
“What is it?” asked Jason.
</p>
<p>
“A 3-megawatt S-band magnetron fitted to a 24 dB gain extended horn antenna, driven by an LC oscillator that delivers 50-nanosecond pulses at a 5% duty cycle. Its power train is a high-voltage ultracapacitor bank fed by a parallel-wired lithium ion battery pile, with a built-in wall-power converter &mdash; which makes the whole machine self-contained, man-portable, and field-rechargeable.”
</p>
<p>
Jason shook his head. “None of that means anything to me.”
</p>
<p>
Danny broke his eyes away from the contraption to shoot Jason a cold glare. “Exactly.”
</p>
<p>
Jason’s face crinkled into a smile. “I see you take pride in your work. Tell you what. Hear me out on this little project. If you decide to accept it, consider your gizmo there as a starting bonus. Sound good?”
</p>
<p>
Danny put the device back in the bag and gave Jason his attention.
</p>
<p>
“Tell me, Danny. How much do you know about me?”
</p>
<p>
“Nothing. I didn’t even know your name until this afternoon. I Googled you, of course. Got a bunch of hits on a company called Tungsten Medical Technologies. Some kind of medical supply retailer?”
</p>
<p>
Jason nodded. “Yes, Tungsten. That’s what I was hoping to talk about.”
</p>
<p>
“You were their head accountant or something, right?”
</p>
<p>
“I was their COO. Chief Operations Officer. I was with Tungsten for a long, long time &mdash; almost since they started, back in the seventies. We sold high-end surgical equipment and medical tools. We supplied a lot of research labs. It was a good company to work for. Privately owned, friendly, very customer-focused. Good times.”
</p>
<p>
“I’ve never heard of it before. Is it big?” Danny asked.
</p>
<p>
“At its height, maybe three hundred people. Mostly sales teams. We had guys who bought equipment from manufacturers, and other guys who’d turn around and sell it to schools and hospitals.”
</p>
<p>
“So this Tungsten company doesn’t actually <em>make</em> anything, then?”
</p>
<p>
Jason shook his head. “Back then, no. We were just re-sellers.”
</p>
<p>
“Sounds simple, but I feel like I’m missing something,” said Danny. “Why would a customer bother going through a middleman? I mean, if I were a surgeon looking for a shiny new scalpel or something, I’d just go to the manufacturer’s website.”
</p>
<p>
“And how exactly would you have done that in the late seventies?”
</p>
<p>
Danny laughed inwardly. It was easy to forget just how recent the dot-com revolution was. Something as simple and ubiquitous as online shopping was not yet even two decades old.
</p>
<p>
“You hit the nail on the head, though,” Jason continued. “The Internet hasn’t been kind to Tungsten. It made our core business model obsolete. Tungsten spent the last ten years in a death spiral. When the recession hit, the company finally fell apart. We laid off almost everybody. I took severance. It was a hard decision, but I could tell we were finished. The company got ready to sell off its stockroom and close its doors.”
</p>
<p>
“But it managed to survive?” asked Danny.
</p>
<p>
“Yes, but… it’s <em>changed</em>. Two years ago, some nameless overseas consortium swooped in and bought the company. These guys &mdash; Russian, Estonian, something like that &mdash; they were able to get it for a steal. They installed this old scientist to run the whole shop. Dr. Pyotr Passinsky. The investment consortium wires him money, and he pays the bills and keeps the staff in line.”
</p>
<p>
“So there’s still a staff around.”
</p>
<p>
“Yeah,” said Jason. “Dr. Passinsky kept some of the technical salesmen who knew their way around the old equipment. Then he went and hired about a dozen new people. Very pricey people &mdash; geneticists, chemical engineers, neurobiologists. The consortium apparently has this vision to revamp Tungsten into a cutting-edge research shop for pharmaceutical biotechnology.”
</p>
<p>
Danny nodded wistfully. “Heh. Biotech…”
</p>
<p>
“Yes,” said Jason. “Are you familiar with that technology space at all?”
</p>
<p>
Danny shook his head, smiling distantly. The very word “biotechnology” conjured images he’d long forgotten. There was a time before the Internet boom when a young computer enthusiast wasn’t seen as a potential millionaire, but a pimple-pocked pariah suited solely for locker-stuffing and atomic wedgies. It was a time when his fellow Generation X nerds were all reading William Gibson’s <em>Neuromancer</em> and playing <em>Shadowrun</em> and dressing like <em>The Matrix</em>; when they said to each other with heady excitement, “The future is <em>digital</em>!” Growing up, they had made that future real &mdash; configuring ISDN lines, building websites, creating dot-coms. They were homesteaders and gold prospectors taming the West.
</p>
<p>
Yet now, <em>because</em> they had made it real, by definition it wasn’t futuristic anymore.
</p>
<p>
But <em>biotechnology</em> was still an uncharted frontier. Biotech still held unscaled vistas and unseen horizons &mdash; the next “virtual reality”, the next “information superhighway”, the next “cyberspace”. The future <em>used</em> to be digital. Now the <em>present</em> was digital. The future was squishy.
</p>
<p>
“Not at all,” Danny answered. “But I have friends who work at the Fred Hutchinson Cancer Research Center. And ZymoGenetics. And the Allen Institute for Brain Science. I’ve been hearing for decades that biotech is just around the corner. I guess it’s finally happening.”
</p>
<p>
Jason nodded. “Exactly. Biotechnology is getting big. But Tungsten isn’t.”
</p>
<p>
“You don’t think so?” asked Danny.
</p>
<p>
“They’re playing a very strange game over there right now. In the entire two years under Dr. Passinsky, they haven’t filed a single patent. They haven’t published any papers or presented at any conferences.”
</p>
<p>
Danny felt a little stupid. “And that’s unusual?”
</p>
<p>
“Very. See, if Tungsten <em>really</em> wanted to join the pharmaceuticals race, they’d be building a reputation and soliciting a buyout,” Jason explained. “FDA approval is a long and painful process, and a tiny player like Tungsten should be trying to join some ‘mega-corporation’ to leverage their clinical trial pipeline. Take ICOS Biologics for example, over in Bothell. They used to be the biggest private biotechnology firm in the Pacific Northwest. They developed Cialis, the drug for erectile dysfunction. What did they do? Sold to Eli Lilly. Or take ID Biomedical &mdash; they created a flu vaccine mist that you spray up your nose. They sold to GlaxoSmithKline. That’s how this game goes. But Tungsten isn’t playing.”
</p>
<p>
“Have you talked to them?” asked Danny. “You were their COO. You had a long history with them. Can’t you just call them?”
</p>
<p>
“No way,” said Jason. “My time with them was before this new consortium took over, so I have no more access than anybody else. They have no public relations arm. The only person you can reach on the phone is their receptionist, and she doesn’t know anything.”
</p>
<p>
“And what about the scientists? Those lab workers? I mean, Jason, you’re a rich guy. You could just bribe them to tell you what’s going on.”
</p>
<p>
“I tried that, actually,” Jason confessed. “See, the company’s only about twenty heads, so talking to the workers without setting off alarm bells is tricky. I figured I’d go for someone low on the totem pole. They have a college intern, this twenty-year-old Asian-American girl named Julie Yen. I hired a private eye to check her out. She’d been acting really strangely for several weeks, so we figured she must be having personal problems. Drug problems, maybe. My guy approached her and offered her cold hard cash to tell us what she’s working on. She just got this big grin and said, ‘Wouldn’t <em>you</em> like to know!’ She started hanging out with some really shady characters after that. We didn’t follow her.”
</p>
<p>
“I see. What about their computers? Have you tried hacking in?” asked Danny.
</p>
<p>
Jason didn’t reply. He just looked at Danny and grinned.
</p>
<p>
“Oh God, you’re shitting me!” Danny said. 
</p>
<p>
“I’m serious,” Jason answered. 
</p>
<p>
“You want <em>me</em> to hack into Tungsten.”
</p>
<p>
“Yes. Hack in and find out what they’re up to. This Eastern European consortium took over my old medical supply company and turned it into some kind of top-secret research facility, and I want to know what they’re making in there.”
</p>
<p>
“<em>That’s</em> your job offer?”
</p>
<p>
Jason nodded. “I presume you’ve got expertise in the matter. I mean, you’re a talented engineer, so I figured…”
</p>
<p>
Danny flashed him a nervous grin. “Actually, I… well, kinda…”
</p>
<p>
Danny thought back to his career as a hacker, long ago. It consisted of him finding a newsletter on his freshman homeroom teacher’s desk. In a section listing faculty phone numbers, they’d given the extension for a dial-in connection to a system that the teachers used for inputting grades. Danny had an 8086 IBM PC with a 1200-baud Hayes modem. After fiddling with the modem’s settings, he got it to connect to the school’s computer. He saw that he needed to enter a teacher’s username and password to change any grades, and was about to give up. 
</p>
<p>
But then he noticed that the main screen displayed, “<span class="computer">NUMBER OF CURRENT USERS</span>,” and the number wasn’t going down. Danny discovered, through sheer luck, that the grades system’s connection-handling software had a flaw: if he simply hung up without logging out, the system would think his connection was still open. Danny guessed that the system could only handle so many connections at a time, so he started calling and disconnecting over and over again. He was right – it would accept no more than 255 simultaneous users, at which point it simply stopped answering incoming calls. Victory! The school’s teachers couldn’t enter their grades anymore! The school fixed it by rebooting the machine, but Danny jammed it again the next day. He kept this up for a few weeks until his parents got the phone bill.
</p>
<p>
“Uh, Jason, I’ll be honest,” said Danny. “My skills might be a little rusty.”
</p>
<p>
“Don’t worry. I’ve already assembled a team,” said Jason. “I’ll introduce you tomorrow. Very skilled guys. I want you to lead them.”
</p>
<p>
“<em>Me</em>? But… I don’t think I’m… Look, Jason, the skills for <em>building</em> data systems aren’t the same as the skills for <em>breaking</em> them. It’s a different mindset.”
</p>
<p>
“So you don’t think you’d be able to do the job?” Jason asked.
</p>
<p>
“I can <em>absolutely</em> do the job!” Danny replied. “I… I’ll have to think about it.”
</p>
<p>
Jason gave a crisp nod. “You think. I’ll go get a beer.”
</p>
<p>
He left the table. For several moments Danny sat limply, listening to the atonal electronic background music, watching the space where Jason had been.
</p>
<p>
There would be no Claymore the following day. No 9:30 standup meeting, no bug triage, no competitive analysis reports. None of the ritual or rigmarole that had defined his life for the last six years. And in its place was… nothing. Nothing.
</p>
<p>
He pulled out his cellphone and launched the LinkedIn app. He typically used it to keep in touch with contacts he made at conferences. For the first time ever, the profile he loaded was his own.
</p>
<p>
Six years at Claymore Communications, developing a new cellular multiplexing protocol. And before that, three years at a company that built network appliances. And before that, three years building custom FPGA-based digital radio systems. And before that… 
</p>
<p>
Not a single company in his entire employment history still existed. He’d gotten in on the ground floor of each one, when they were still under a dozen employees, hoping to ride the wave to prominence. Instead, they all fizzled in the wake of new technologies. The relentless pace of the industry rendered every one of his projects obsolete and useless by the time it could be brought to market.
</p>
<p>
Jason returned to the table. “So…?”
</p>
<p>
Danny said nothing.
</p>
<p>
Jason prodded, “With Claymore dead, what else will you do?”
</p>
<p>
Danny shrugged. “I’ll find some way to spend my time. I’ll hang out at Ada’s Technical Books on Broadway. I’ll tap some local connections in the Maker community and engineering Meetup groups. I’ll…”
</p>
<p>
His gaze drifted downward at his cellphone screen. His own face, with slightly smoother skin and brighter eyes, looked up at him from the LinkedIn headshot. The objective statement beside it read, “Creative, optimistic computer engineer eager to make history in the digital revolution.” It hadn’t been modified in over six years.
</p>
<p>
“I’m in, Jason,” he said. “Let’s make it happen.”
</p>
</div>