<div class="chapsection">
<p>
<span class="caplead">Mercury was adorned with grinning gargoyles</span> and occult symbols. Twisted mannequins stood in corners, as though the Medusa sculpture by the door had turned mutant patrons to plastic. Young men and women with assorted bits of metal in their skin sipped colorful drinks to the buzzing, beeping background music.
</p>
<p>
Danny walked in carrying a Claymore tote bag full of electronic junk. Wires and tubes poked out from the top. He spotted Jason Tuttle alone at a table.
</p>
<p>
“I take it you haven’t been home?” Jason teased, eyeing the suit Danny was still wearing from the afternoon’s presentation.
</p>
<p>
“I hung out in the office after our chat,” Danny said as he sat down to join him. “Figured I’d soak in the vibe one last time. Play with the Foosball table. Kick the vending machine.”
</p>
<p>
“But I see you didn’t walk away empty-handed,” said Jason, eyeing Danny’s bag.
</p>
<p>
“This? Just a souvenir,” Danny said. “Nothing that anyone but me would miss.”
</p>
<p>
“Is it Claymore property?” asked Jason.
</p>
<p>
“Does it seriously matter anymore?” Danny replied morosely.
</p>
<p>
“Yes, actually, it does,” Jason said. “Remember, we’re auctioning off Claymore’s assets. Everything’s up for appraisal. The software, the hardware, the furniture, the company van. Everything. If whatever’s in that bag has monetary value, then you’re committing theft against the investors. That includes me.”
</p>
<p>
Danny gazed into the bag’s metal-strewn depths. “Monetary value?”
</p>
<p>
Jason shrugged. “Everything has <em>some</em> monetary value, Danny.”
</p>
<p>
Danny reached inside and carefully fished out a foot-long, six-inch-wide flared metal tube. Attached to the tube was a rubber-coated cylindrical handle with a plastic trigger near the top. Metal blocks protruded from its back, connected to red and black cables that dangled down into the recesses of the bag. Danny held the assembly delicately by the pistol grip, his finger near the trigger. His eyes traced the device’s joints and contours like fingertips across a lover’s body.
</p>
<p>
“What is it?” asked Jason.
</p>
<p>
“Something I designed and built during Claymore’s contract at Naval Base Kitsap.,” Danny said, still looking at the machine. His voice was quiet, almost tender. 
</p>
<p>
“It looks like some kind of homemade megaphone on steroids…”
</p>
<p>
Danny replied, “It’s a 3-megawatt S-band magnetron fitted to a 24 dB gain extended horn antenna, driven by an LC oscillator that delivers 50-nanosecond pulses at a 5% duty cycle. Its power train is a high-voltage ultracapacitor bank fed by a parallel-wired lithium ion battery pile, with a built-in wall-power converter &mdash; which makes the whole machine self-contained, man-portable, and field-rechargeable.”
</p>
<p>
Jason shook his head. “None of that means anything to me.”
</p>
<p>
Danny broke his eyes away from the contraption to look at Jason. His gaze was cold. “Exactly,” he said.
</p>
<p>
Jason’s face crinkled into a smile. “I see you take pride in your work.”
</p>
<p>
Danny looked down and shrugged. He murmured quietly, “It keeps me going.”
</p>
<p>
“Tell you what,” said Jason. “Hear me out on this little project. If you decide to accept it, consider your gizmo there as a starting bonus. Sound good?”
</p>
<p>
Danny put the device back in the bag and gave Jason his attention.
</p>
<p>
“Tell me, Danny. How much do you know about me?”
</p>
<p>
“Nothing,” Danny answered with a shrug. “I didn’t know your name until this afternoon. I tried to Google you after our chat. Got a bunch of hits on some company called Tungsten Medical Technologies. Some kind of medical supply retailer?”
</p>
<p>
Jason nodded. “Yes, Tungsten. That’s exactly what I was hoping to talk about.”
</p>
<p>
“You were, like, their head accountant or something, right?” Danny asked. “That’s what my search turned up, anyway.”
</p>
<p>
“I was their COO. Chief Operations Officer,” Jason clarified. “I was with Tungsten for a long, long time &mdash; almost since they started, back in the seventies. We sold high-end surgical equipment and medical tools. We supplied a lot of research labs. It was a good company to work for. Privately owned, friendly, very customer-focused. Good times.”
</p>
<p>
“I’ve never heard of it before. Is it big?” Danny asked.
</p>
<p>
“At its height it was maybe three hundred people,” Jason explained. “Mostly sales teams. We had guys who bought equipment from manufacturers, and other guys who’d turn around and sell it to schools and hospitals.”
</p>
<p>
“So this Tungsten company doesn’t actually make anything, then?”
</p>
<p>
“Back then, no. We were just re-sellers.”
</p>
<p>
“Sounds simple, but I feel like I’m missing something,” said Danny. “Why would a customer bother going through a middleman? I mean, if I’m a surgeon looking for a shiny new scalpel or something, I’d just go to the manufacturer’s website.”
</p>
<p>
Jason answered, “And how exactly would you do that in the late seventies?”
</p>
<p>
Danny laughed at himself. It was easy for him to forget just how recent the dot-com revolution was. Something as simple and ubiquitous as online shopping was not yet even two decades old.
</p>
<p>
“You hit the nail on the head, though,” Jason continued. “The Internet hasn’t been kind to Tungsten. It made our core business model obsolete. Tungsten spent the last ten years in a death spiral. When the recession hit, the company finally fell apart. We laid off almost everybody. I took severance. It was a hard decision, but I could tell we were finished. The company got ready to sell off its stockroom and close its doors.”
</p>
<p>
“But it managed to survive?” asked Danny.
</p>
<p>
“Yes, but… it’s changed,” said Jason. “Two years ago, some nameless overseas consortium swooped in and bought the company. These foreign guys &mdash; Russian, Estonian, something like that &mdash; they were able to get it for a steal. They installed this old scientist to run the whole shop. Dr. Pyotr Passinsky’s his name. The investment consortium wires him money, and he pays the bills and keeps the staff in line.”
</p>
<p>
“So there’s still a staff around.”
</p>
<p>
“Yeah,” said Jason. “Dr. Passinsky kept some of the technical salesmen who knew their way around the old equipment. Then he went and hired about a dozen new people. Very pricey people. Geneticists, chemical engineers, neurobiologists. The consortium apparently has this vision to re-vamp Tungsten into a cutting-edge research shop for pharmaceutical biotechnology.”
</p>
<p>
Danny nodded. “Heh. Biotech,” he said wistfully.
</p>
<p>
“Yes,” said Jason. “Are you familiar with that technology space at all?”
</p>
<p>
Danny shook his head with a distant smile. The very word “biotechnology” conjured images he had long forgotten. There was a time before the Internet boom when a young computer enthusiast wasn’t seen as a potential millionaire, but a pimple-pocked social outcast suitable solely for locker-stuffing and atomic wedgies. It was a time when his fellow Generation X tech nerds were all reading William Gibson’s <em>Neuromancer</em> and playing <em>Shadowrun</em> and dressing like <em>The Matrix</em>; when they said to each other with heady excitement, “The future is <em>digital</em>!” Growing up, they had made that future real &mdash; configuring ISDN lines, building websites, creating dot-coms. They were homesteaders and gold prospectors taming the West.
</p>
<p>
Yet now, <em>because</em> they had made it real, by definition it wasn’t futuristic anymore. Danny’s first few jobs made him feel like a pioneer in a vast uncharted wilderness. Now he felt like a soulless office drone.
</p>
<p>
But <em>biotechnology</em>, Danny mused. Biotech still held unscaled vistas and unseen horizons &mdash; the next “virtual reality,” the next “information superhighway,” the next “cyberspace.” The future <em>used</em> to be digital. Now the <em>present</em> was digital. The future was squishy.
</p>
<p>
“Not even a little,” Danny answered. “But I have friends who work at the Fred Hutchinson Cancer Research Center. I see the smokestacks of the ZymoGenetics building twice a day on my commute. I’ve driven through the construction zone in South Lake Union, where Paul Allen is building that gigantic Institute for Brain Science. I know Seattle’s quickly becoming a nexus of biotech, like it was once a nexus of the Information Age. I’ve always heard biotech’s right around the corner for decades. I guess it’s finally happening.”
</p>
<p>
Jason nodded. “Exactly. Biotechnology is getting big. But Tungsten isn’t.”
</p>
<p>
“You don’t think so?” asked Danny.
</p>
<p>
“They’re playing a very strange game over there right now,” said Jason. “In the entire two years under Dr. Passinsky, they haven’t filed a single patent. They haven’t published any papers or presented at any conferences.”
</p>
<p>
“And that’s unusual?” Danny said naively.
</p>
<p>
“Very. See, if Tungsten was really trying to join the pharmaceuticals race, they’d be building a reputation for themselves and negotiating with someone like Johnson & Johnson for a buyout,” Jason explained. “FDA approval is a long and painful process, and a tiny player like Tungsten should be trying to join some so-called ‘mega-corporation’ to leverage their clinical trial pipeline. Look at ICOS Biologics, over in Bothell. They used to be the biggest biotechnology firm in Seattle. They developed Cialis, the drug for erectile dysfunction. What did they do? Sold to Eli Lilly. Or take ID Biomedical &mdash; they created a flu vaccine mist that you spray up your nose. They sold to GlaxoSmithKline. That’s how this game goes. But Tungsten isn’t playing.”
</p>
<p>
“Have you talked to them?” asked Danny. “You were their COO. You had a long history with them. Can’t you just call them?”
</p>
<p>
“No way,” said Jason. “My time with them was before this new consortium took over, so I have no more access than anybody else. They have no public relations arm. The only person you can reach on the phone is their receptionist, and she doesn’t know anything.”
</p>
<p>
“And what about the scientists? Those lab workers? I mean, Jason, you’re a rich guy. You could just bribe them to tell you what’s going on.”
</p>
<p>
“I tried that, actually,” Jason confessed. “See, the company’s only about twenty heads, so talking to the workers without setting off alarm bells is tricky. I figured I’d go for someone low on the totem pole. They have a college intern, this twenty-year-old Asian-American girl named Julie Yen. I hired a private eye to check her out. She’d been acting really strangely for several weeks, so we figured she must be having personal problems. Drug problems, maybe. My guy approached her and offered her cold hard cash to tell us what she’s working on. She just got this big grin and said, ‘Wouldn’t <em>you</em> like to know!’ She started hanging out with some really shady characters after that. We didn’t follow her.”
</p>
<p>
“I see. What about their computers? Have you tried hacking in?” asked Danny.
</p>
<p>
Jason didn’t reply. He just looked at Danny and grinned.
</p>
<p>
“Oh God, you’re shitting me!” Danny said. 
</p>
<p>
“I’m serious,” Jason answered. 
</p>
<p>
“You want <em>me</em> to hack into Tungsten.”
</p>
<p>
“Yes. Hack in and find out what they’re up to. This Eastern European consortium took over my old medical supply company and turned it into some kind of top-secret research facility, and I want to know what they’re making in there.”
</p>
<p>
“<em>That’s</em> your job offer?”
</p>
<p>
Jason nodded. “I presume you’ve got expertise in the matter. I mean, you’re a talented engineer, so I figured…”
</p>
<p>
Danny flashed him a nervous grin. “Actually, I… well, kinda…”
</p>
<p>
Danny thought back to his career as a hacker, long ago. It consisted of him finding a newsletter on his freshman homeroom teacher’s desk. In a section listing important faculty phone numbers, they’d given the extension for a dial-in connection to a system that the teachers used for inputting grades. Danny had an 8086 IBM PC with a 1200-baud Hayes modem. After fiddling with the modem’s settings, he got it to connect to the school’s computer. He saw that he needed to enter a teacher’s username and password to change any grades, and was about to give up. 
</p>
<p>
But then he noticed that the main screen displayed, “<span class="computer">NUMBER OF CURRENT USERS</span>,” and the number wasn’t going down. Danny discovered, through sheer luck, that the grades system’s connection-handling software had a flaw: if he simply hung up without logging out, the system would think his connection was still open. Danny guessed that the system could only handle so many connections at a time, so he started calling and disconnecting over and over again to max it out. He was right – the system would accept no more than 255 simultaneous users, at which point it simply wouldn’t answer any more incoming phone calls. Victory! The school’s teachers couldn’t enter their grades anymore! The school fixed it by rebooting their computer, but Danny simply jammed it again the next day. He kept this up for a few weeks until his parents got the phone bill.
</p>
<p>
“Uh, Jason, I’ll be honest,” said Danny. “My skills might be a little rusty.”
</p>
<p>
“Don’t worry. I’ve already assembled a team,” said Jason. “I’ll introduce you tomorrow. Three other guys. Very skilled. I want you to lead them. What do you say?”
</p>
<p>
Danny looked away. “I don’t know.”
</p>
<p>
“What’s not to know?” Jason asked. “I can plainly see you practically beaming at the idea.”
</p>
<p>
He said hesitantly, “What you’re asking for is illegal.”
</p>
<p>
“Which is exactly why I need someone I can work closely with,” said Jason. “Someone I can trust. Danny, I know there are professional hacker organizations out there &mdash; there are entire companies that do information security operations. But the legitimate ones won’t take on a project like this, and the illegitimate ones are, um, not the kind of people I want to do business with. I need someone I already have an established working relationship with &mdash; and technically you’ve been on my payroll for the last six years. I need <em>you</em>, Danny.”
</p>
<p>
“<em>Me</em>? But… I don’t think I’m…” he stammered. “Look, Jason, the skills for <em>building</em> data systems aren’t the same as the skills for <em>breaking</em> them. It’s a different mindset.”
</p>
<p>
“So you don’t think you’d be able to do the job?” Jason asked.
</p>
<p>
“I can <em>absolutely</em> do the job!” Danny replied quickly. “I… I’ll have to think about it.”
</p>
<p>
Jason gave a crisp nod. “You think. I’ll go get a beer.”
</p>
<p>
He left the table quickly. For several moments Danny sat limply, listening to the atonal electronic background music, watching the empty space where Jason had been.
</p>
<p>
There would be no Claymore the following day. No 9:30 standup meeting, no bug triage, no competitive analysis reports. None of the ritual or rigmarole that had defined his life for the last six years. And in its place was… nothing. Nothing.
</p>
<p>
He pulled his cellphone out of his pocket and launched the LinkedIn app. He typically used it to keep in touch with contacts he made at conferences. For the first time ever, the profile he loaded was his own.
</p>
<p>
Six years at Claymore Communications, developing a new cellular multiplexing protocol. And before that, three years at a company that built network appliances. And before that, three years building custom FPGA-based digital radio systems. And before that… 
</p>
<p>
Not a single company in his entire employment history still existed. He’d gotten in on the ground floor of each one, when they were still a dozen employees or less, with the hope of riding the wave to prominence. Instead, they all fizzled in the wake of new technologies. The relentless pace of the industry invariably rendered every one of his projects obsolete and useless by the time it could be brought to market.
</p>
<p>
Jason returned to the table. “So…?”
</p>
<p>
Danny said nothing.
</p>
<p>
Jason prodded, “With Claymore dead, what else will you do?”
</p>
<p>
Danny shrugged. “I’ll find some way to spend my time. I’ll hang out at Ada’s Technical Books on Broadway. I’ll tap some local connections in the Maker community and engineering Meetup groups. I’ll…”
</p>
<p>
His gaze drifted downward at his cellphone screen. His own face, with slightly smoother skin and brighter eyes, looked up at him from the LinkedIn headshot. The objective statement beside it read, “Creative, optimistic computer engineer eager to make history in the digital revolution.” It hadn’t been modified in over six years.
</p>
<p>
“I’m in, Jason,” he said. “Let’s make it happen.”
</p>
</div>