<div class="chapsection">
<p>
<span class="caplead">Krongor’s battleaxe split the orc’s skull</span> in half, spraying the cavern wall with black ichor as the creature fell lifeless at the barbarian’s feet. 
</p>
<p>
Several paces ahead, Zhan quickly chanted arcane syllables. With a hand that suddenly glowed white, the wizard grabbed a nearby orc. Arcs of lightning surged through its body as its vibrato screams echoed through the cavern. The air filled with the stench of ozone and burning hair. The monster fell, twitching but lifeless.
</p>
<p>
A veritable army of the beasts surrounded Krongor. The warrior’s axe cleaved through another orc’s torso. Yet no sooner had the foe fallen than the next one filled its place.
</p>
<p>
Zhan pointed toward the barbarian and shouted another incantation &mdash; and in an instant, Krongor was engulfed in an inferno. All he could see was flame. The very air around him set alight, singeing his hair, blistering his skin.
</p>
<p>
And just as quickly as the fire had appeared, it vanished. The cavern was silent, save for the sizzling orc remains. Amidst a circle of ashen bodies, Krongor collapsed to his knees in agony. “You idiot!” he growled.
</p>
<p>
“I’m sorry!” cried Zhan. “They were all around you! It <em>did</em> kill them all, at least…”
</p>
<p>
Smoke still rose from the barbarian’s flesh. He gritted his teeth, keeping himself conscious solely through strength of will. “Stupid wizards! Just use your damn hocus-pocus to patch me up, will you?”
</p>
<p>
Zhan nodded apologetically. He sat beside Krongor in a meditative pose and began whispering prayers to Eir, Goddess of Healing. The deity’s love reached even down into these dark pits. As he prayed, Krongor’s wounds closed, vanishing before his eyes.
</p>
<p>
Some dispute remained over whether that actually happened.
</p>

<hr/>

<p>
“I don’t care what you think I said before!” insisted Moshen. “He has <em>no</em> healing spells!”
</p>
<p>
Moshen, a scrawny Asian kid with thick glasses, sat at the head of a lacquered table, on a leather bench that wrapped along the walls of a yacht’s wood-paneled cabin. His face was mostly obscured by a laminated cardboard screen bearing pictures of knights and dragons. The table held a disorganized pile of books, dice, and Cheetos. At the center, atop a plastic sheet with a hexagonal grid, stood two-inch painted pewter figurines &mdash; one axe-wielding barbarian, one wizard, and several orc figures lying face-down.
</p>
<p>
“This is bullshit!” Mike fired back, waving a handful of papers. He was dark-haired and tall, well-muscled but too fat and scruffy to show definition. “When we were in Salavina, I remember Zhan going to the Temple of Eir and learning a healing spell from the High Priestess.” He turned to his side. “Didn’t you?”
</p>
<p>
Jason Tuttle sat next to Mike, chugging a soda and adding up experience points on a worn character sheet. “She taught me a prayer for good health, Mike. She didn’t grant me the authority to channel the power of her god.”
</p>
<p>
“You talked me into helping you fight through these orc-infested caverns, and you can’t even cast any healing spells!?”
</p>
<p>
“Mike, quit being such a munchkin!” Moshen insisted. “Wizards throw lightning bolts and fireballs. Priests manipulate life energies. They operate on completely incompatible principles.”
</p>
<p>
Jason shrugged. “Wizards can’t cast healing spells, dude. Everybody knows that.”
</p>
<p>
“Give me Zhan’s character sheet, Jason,” Mike demanded.
</p>
<p>
Jason put a hand over the paper. “Why…?”
</p>
<p>
Wielding an eraser with menace, Mike declared, “I’m going to change him into a barbarian.”
</p>
<p>
Jason’s face was a mask of horror. “Don’t even think about it!”
</p>
<p>
“Try and stop me!” Mike snatched at Zhan’s character sheet. Jason yanked it away and held it at arm’s length. Mike tried to reach around Jason, but he wouldn’t yield. The two grown men slapped at each other and wrestled on the cabin bench for control of the paper.
</p>
<p>
Footsteps from above pressed them to a truce. Through the portholes, they could see jeans and hiking boots. The visitor knelt down to peer inside. Danny’s face appeared in the round window. Jason pointed to the entrance.
</p>
<p>
“Hey,” Danny said as he descended the steep stairs into the cabin. “Oh good, I got the right boat.”
</p>
<p>
Jason waved hello. “Come on in, Danny. Meet the gang.”
</p>
<p>
Danny looked around. On one end of the cabin was a large flat-screen TV. On the other end, he saw the table covered with rulebooks, figurines, and soda cans. He instantly recognized the scene. He’d walked into a <em>Dungeons & Dragons</em> campaign. 
</p>
<p>
“Aww Christ,” he muttered. He felt the revulsion and regret of a recovered heroin addict entering an opium den. Danny’s days of chasing these particular dragons were long behind him. “Jason, can I talk to you?”
</p>
<p>
Jason wiggled his way from the table and crossed the compartment.
</p>
<p>
“<em>This</em> is your hacker team?” Danny whispered. “Where did you find these guys?”
</p>
<p>
“They’re from my gaming group,” Jason said innocently. “We play every Thursday at the Wizards of the Coast store in Crossroads Mall.”
</p>
<p>
“You play <em>Dungeons & Dragons</em>? Aren’t you like sixty? Don’t you have a wife and kids and a life and stuff?”
</p>
<p>
Jason replied coldly, “My ex-wife is none of your business.”
</p>
<p>
“Sorry, didn’t mean to hit a sore spot. But, I mean, look at these guys. Do they have any skills? Do they even have <em>jobs</em>?”
</p>
<p>
“They have my complete trust,” said Jason. “They’re smart and capable. You should see the kind of shit we pull off together. Just last month, we destroyed the stronghold of a Dark Elven necromancer.”
</p>
<p>
“Your <em>characters</em> did that. In your <em>head</em>. <em>You</em> sat around rolling dice and scarfing Cheetos.”
</p>
<p>
“Look, I know personnel management, alright?” Jason said. “What counts is whether you can work as a team. These guys are my comrades in arms. They’re in. Are you?”
</p>
<p>
Danny sighed and approached the table. Mike and Moshen paused poking through rulebooks and scribbling on papers long enough to mumble greetings. “Guys. Good to meet you. My name’s Danny. I’m the lead engineer at… um… Let’s just say I’ve overseen the demise of many small companies.”
</p>
<p>
He shook hands with both of them.
</p>
<p>
“Moshen Chen. Web designer and developer. ASP.NET, Ruby on Rails, HTML 5, Angular, Closure, I do it all. You want a kick-ass website, I’m your man.”
</p>
<p>
“Mike Braun. I work at the Safeway on Queen Anne.” Danny stopped in mid-handshake. “And I’m taking Cisco certification classes at Bellevue College. Network administration &mdash; router setup, mail servers, domain name registrars, packet monitoring, that kind of stuff.”
</p>
<p>
“And thinks wizards can cast <em>Cure Light Wounds</em>,” Moshen interjected.
</p>
<p>
“Oh shut up already!” Mike wailed.
</p>
<p>
“Isn’t <em>Cure Light Wounds</em> a priest spell?” Danny said before he could stop himself.
</p>
<p>
“See!” said Moshen, sticking his finger in Mike’s face.
</p>
<p>
“You play?” Jason asked Danny eagerly.
</p>
<p>
Danny shook his head. “Not since Second Edition.” That was a lie.
</p>
<p>
“You want to hop in?” offered Jason. “We have plenty of extra character sheets.”
</p>
<p>
Danny closed his eyes and sighed slowly. “Is there anything else I should know about you guys before we get started? Additional skills? Um… Attributes? Proficiencies? ”
</p>
<p>
“I play hockey!” Mike peacocked. “I can be your muscle if things get physical!”
</p>
<p>
“Yeah!” Moshen chimed in. “And I know kung fu!”
</p>
<p>
Danny eyed the men with a cocked eyebrow. “Hockey… and… kung fu…? Guys, this is just a network penetration mission. The only way things can possibly ‘get physical’ is if we’re, like, unspeakably bad at our jobs. We’re <em>not</em> bad at our jobs, are we?” The faces in front of him may as well have been blobs of cold Play-Doh. “<em>Are we?</em>”
</p>
<p>
Meekly, Mike offered, “Nnn… <em>no?</em>”
</p>
<p>
From the hexagonal grid on the table, Danny picked up the barbarian figurine. It was painted with loving detail. “Clear off this table. Keep the pencils and notebooks. We’ve got work to do.” 
</p>
</div>
