<div class="chapsection">
<p>
<span class="caplead">Krongor’s battleaxe split the orc’s skull</span> in half, spraying the cavern wall with black ichor as the creature fell lifeless at the barbarian’s feet. 
</p>
<p>
Several paces ahead, Zhan quickly chanted arcane syllables. With a hand that suddenly glowed white, the wizard grabbed a nearby orc by the arm. Arcs of lightning surged through its body as its vibrato screams echoed through the cavern. The air filled with the stench of ozone and burning hair. The monster fell backward, twitching but lifeless.
</p>
<p>
A veritable army of the foul beasts surrounded Krongor, stabbing with their serrated swords. The muscular warrior’s axe cleaved through an orc’s torso in a single blow. Yet no sooner had the foe fallen than one of its comrades advanced to fill its place.
</p>
<p>
Zhan pointed toward the barbarian with splayed fingers and shouted another incantation &mdash; and in an instant, Krongor found himself engulfed in an inferno. In all directions, all Krongor could see was orange tongues of flame. The very air around him set alight, searing his lungs and singeing his hair. His skin blistered and charred.
</p>
<p>
And just as quickly as the fire had appeared, it vanished. The cavern was silent, save for the sizzling from the burnt remains of the orcs. Amidst a circle of ashen bodies, Krongor collapsed to his knees in agony. “You idiot!” he growled.
</p>
<p>
“I’m sorry!” cried Zhan. “They were all around you! It <em>did</em> kill them all, at least…”
</p>
<p>
Thin trails of smoke still rose from the barbarian’s skin. He gritted his teeth, keeping himself conscious solely through strength of will. “Stupid blasphemous wizards! Just use your damn hocus-pocus powers to patch me up, will you?”
</p>
<p>
Zhan nodded apologetically. He sat beside Krongor in a meditative pose and began whispering prayers to Eir, Goddess of Healing. The deity’s warm love reached even down into these dark pits. As he prayed, Krongor’s wounds closed and healed before his eyes.
</p>
<p>
There was some dispute over whether or not that actually happened.
</p>

<hr/>

<p>
“I don’t care what you think I said before!” insisted Satish, a short, stout Indian man. “I’m telling you now, he has no healing spells.”
</p>
<p>
Satish sat at the head of a highly lacquered table, on a leather bench that wrapped along the walls of a yacht’s cabin. The table consumed half of the space in the wood-paneled room. Through round portholes, the water of Lake Washington glistened in the midday sun.
</p>
<p>
The shiny table held a disorganized pile of books, dice, and Cheetos. At the center, atop a plastic sheet with a hexagonal grid and dry-erase marker lines, stood two-inch painted pewter figurines – one mighty axe-wielding barbarian, one wizard, and several orc figures lying face-down.
</p>
<p>
“This is bullshit!” Mike fired back, waving a handful of papers. He was dark-haired and tall, well-muscled but too fat and scruffy to show definition. “When we were in Salavina, I remember Zhan going to the Temple of Eir and learning a healing spell from the High Priestess.” He turned to his side. “Didn’t you?”
</p>
<p>
Jason Tuttle sat next to Mike, chugging a soda and adding up experience points on a worn character sheet. “She taught me a prayer for good health, Mike,” he said. “She didn’t grant me the authority to channel the power of her god.”
</p>
<p>
“She did! She totally did! Ask Moshen!”
</p>
<p>
Moshen, a scrawny Asian kid with thick glasses, sat near Mike at the table, his nose deep in a rulebook. “Leave me out of this, man. I’m not even here,” he said without looking up. “I’m still waiting for the two of you back in town, getting drunk and hitting on wenches.”
</p>
<p>
Mike turned back to Jason. “Are you telling me that you talked me into helping you fight through these orc-infested caverns, and you can’t even cast any healing spells!?”
</p>
<p>
Jason shrugged. “Wizards can’t cast healing spells, dude. Everybody knows that.”
</p>
<p>
“Mike, quit being such a munchkin!” Satish railed. “It doesn’t make any sense for wizards to heal! Wizard and priest spells operate on completely incompatible principles. Wizards throw lightning bolts and fireballs. Priests manipulate life energies. It’s a big difference!”
</p>
<p>
A low, frustrated noise came out of Mike’s throat. “Stupid freaking wizards…”
</p>
<p>
“Really sorry about the fireball,” said Jason. “My bad.”
</p>
<p>
“Give me Zhan’s character sheet, Jason,” Mike demanded.
</p>
<p>
Jason put a protective hand over the paper. “Why…?”
</p>
<p>
Wielding an eraser with menace, Mike declared, “I’m going to change him into a fellow barbarian.”
</p>
<p>
Jason’s face was a mask of horror. “Don’t even think about it!”
</p>
<p>
“Try and stop me!” Mike snatched at Zhan’s character sheet. Jason yanked it away and held it at arm’s length. Mike tried to reach around Jason, but he wouldn’t yield. The two overweight grown men slapped at each other and wrestled for control of the pencil-marked sheet on the narrow cabin bench.
</p>
<p>
Their bickering was interrupted by footsteps above. Through the portholes they could see jeans and hiking boots. The visitor knelt down to peer inside. Danny’s face appeared in a porthole. Jason pointed to the entrance.
</p>
<p>
“Hey,” Danny said as he descended the steep stairs into the cabin. “Oh good, I got the right boat.”
</p>
<p>
Jason waved hello. “Hey Danny, glad you could make it. Come on in, meet the gang.”
</p>
<p>
Danny looked around. All the furniture was cleverly arranged to make the best possible use of the cabin’s limited space. On one end of the room was a plasma TV and a desk with a laptop docking station. On the other end, he saw the table covered with rulebooks, figurines, and soda cans. 
</p>
<p>
He instantly recognized the scene. He’d walked into a <em>Dungeons & Dragons</em> campaign. 
</p>
<p>
“Aww Christ,” he moaned under his breath. He felt the revulsion and regret of a recovered heroin addict entering an opium den. This game, as far as Danny was concerned, was an equally egregious waste of life &mdash; a slightly more literal way to chase a dragon. “Jason,” he said, “can I talk to you?”
</p>
<p>
Jason wiggled his way from the table and crossed the compartment in a few steps. He and Danny turned away from the group and spoke in whispers.
</p>
<p>
“<em>This</em> is your hacker team?” asked Danny. “Where did you find these guys?”
</p>
<p>
“They’re my gaming group,” Jason said innocently. “We play every Thursday at the Wizards of the Coast store in Crossroads Mall.”
</p>
<p>
“You play <em>Dungeons & Dragons</em>? Aren’t you like sixty? Don’t you have a wife and kids and a life and stuff?”
</p>
<p>
Jason replied coldly, “My ex-wife is none of your business.”
</p>
<p>
“Sorry, didn’t mean to hit a sore spot. But, I mean, look at these guys. Do they have any skills? Do they even have real jobs?”
</p>
<p>
“They have my complete trust,” said Jason. “They’re smart, and they’re fully capable of getting the job done. You should see the kind of shit we’ve been able to pull off together. Just last month, we destroyed the stronghold of a Dark Elven necromancer.”
</p>
<p>
“Your <em>characters</em> did that. In your <em>head</em>. <em>You</em> sat around a table rolling dice and scarfing Cheetos.”
</p>
<p>
“Look, I know personnel management, alright?” Jason said. “What counts is whether or not you can work as a team. These guys are my comrades in arms. They’re in. Are you?”
</p>
<p>
Danny sighed. “Yeah.” He turned to face the group. The other three men were quietly poking through rulebooks or scribbling on papers. They looked up as he approached the table. “Guys. Good to meet you all.” They waved and murmured greetings in response. “My name’s Danny. I’m the lead engineer at… um… Let’s just say I’ve overseen the demise of plenty of small companies.”
</p>
<p>
He shook hands with each of them in turn.
</p>
<p>
“Satish Srinivasan. I do whitebox testing and assembly optimization in Microsoft’s Xbox division.”
</p>
<p>
“Moshen Chen. Web designer and developer. ASP.NET, Ruby on Rails, HTML 5, Angular, Closure, I do it all. You want a kick-ass website, I’m your man.”
</p>
<p>
“Mike Braun. I work at the Safeway on Queen Anne.” Danny stopped in mid-handshake. Mike added, “And I’m taking Cisco certification classes at Bellevue College. You know, network administration – router setup, mail servers, domain name registrars, packet monitoring, that kind of stuff.”
</p>
<p>
“And thinks wizards can cast <em>Cure Light Wounds</em>,” Satish interjected.
</p>
<p>
“Oh shut up already!” Mike insisted.
</p>
<p>
“Isn’t <em>Cure Light Wounds</em> a priest spell?” said Danny before he could stop himself.
</p>
<p>
“See!” said Satish, sticking his finger in Mike’s face.
</p>
<p>
“You play?” Jason asked Danny eagerly.
</p>
<p>
Danny shook his head. “Not since Second Edition.” That was a lie.
</p>
<p>
“You want to hop in?” offered Jason. “We have plenty of extra character sheets.”
</p>
<p>
Danny closed his eyes and sighed slowly. “Is there anything else I should know about you guys before we get started? Additional skills? Um… Attributes? Proficiencies? ”
</p>
<p>
“I play hockey!” Mike said proudly. “I can be your muscle if things get physical!”
</p>
<p>
“Yeah!” Moshen chimed in. “And I know kung fu!”
</p>
<p>
Danny eyed the men with a cocked eyebrow. “Hockey… and… kung fu…?” 
</p>
<p>
From the hexagonal grid on the table, he picked up the two-inch pewter figurine of the barbarian. He stared at it for a few moments. It was painted with loving detail. He chuckled and shook his head. 
</p>
<p>
“Guys, let me give you all a reality check. This is a network penetration mission. In an ideal world this’ll be done from some Internet café and take less than ten minutes. If they have a poorly maintained firewall that crumbles under a script-kiddie attack, this whole thing will be completely anticlimactic. Now clear off this table, gentlemen. Keep the pencils and notebooks. We’ve got work to do.” 
</p>
<p>
</div>
