<div class="chapsection">

<div class="computer cyberchat">

<div class="message messagein">
  <div class="speaker">witchdoctor82</div> 
  hey lady!
</div>  

<div class="message messageout">
  <div class="speaker">tinacious_g</div> 
  O HAI!
</div>

<div class="message messagein">
  HI2U2! Whatchya up to?
</div>  

<div class="message messageout">
  IM IN MY LOBBY HATING MY LIFE
</div>

<div class="message messagein">
  why are u still at work? Its almost 10
</div>  

<div class="message messageout">
  Drippy gave me a bunch of shit tasks just to make my life suck.
</div>

<div class="message messagein">
  sorry t. you gonna be done soon?
</div>  

<div class="message messageout">
  No. Haven’t really focused. I made a big mistake called icanhascheezburger. 
</div>
<div class="message messageout">
  And cuteoverload. 
</div>
<div class="message messageout">
  And stuffonmycat.
</div>

<div class="message messagein">
  haha did lolcats steal your brain?
</div>  

<div class="message messageout">
  Yeah. 
</div>
<div class="message messageout">
  I was like, I don’t waaaaaaaant to print any more forms tonight. I know, I’ll cheer myself up by looking at funny pictures of cats on the internets. OMG KITTIES! 
</div>
<div class="message messageout">
  KITTIES KITTIES EVERYWHERE!
</div>
<div class="message messageout">
  Hours later... ZOMGZ MOAR KITTIES!
</div>

<div class="message messagein">
  did you know you get a dopamine rush just from looking at a picture of a smiling baby or a cute animal? There was a uk study about 2yrs ago that proved lolcats are actually a drug.
</div>  

<div class="message messageout">
  AW GEEZ NOT THIS SHIT AGAIN! 
</div>
<div class="message messageout">
  Drippy dragged me into his office this afternoon to lecture me about neurotransmitters. 
</div>
<div class="message messageout">
  He called me hormonal 
</div>
<div class="message messageout">
  and kindly offered to implant electrodes into my cerebral cortex.
</div>

<div class="message messagein">
  aww what a sweet man! 
</div>  

<div class="message messageout">
  It was really more a lecture about me behaving myself with Roger. Drippy disapproved of me giving Roger a close look at my iPhone earlier today.
</div>
<div class="message messageout">
  At high velocity.
</div>

<div class="message messagein">
  hmm. t, you know ur never supposed to succumb to anger. Remember all energy u put out comes back to u threefold. Which is why ur stuck at work late tonight. 
</div>  
<div class="message messagein">
  the Rule Of Three is a core wiccan tenet. u shudnt trifle with stuff like that.
</div>
<div class="message messagein">
  but just between u and me... 
</div>
<div class="message messagein">
  nice!
</div>

<div class="message messageout">
  I’m pretty sure I’m stuck here late not because of mystical energy but because of the security cameras...
</div>
<div class="message messageout">
  ohshit! Shitshitshit!
</div>
<div class="message messageout">
  I swear I just heard one move. 
</div>
<div class="message messageout">
  I think it’s pointed at me. It’s in a black glass dome on the ceiling but you can kinda see the lens if you look real hard.
</div>
<div class="message messageout">
  I think it’s checking out my boobs.
</div>
<div class="message messageout">
  Am I losing it?
</div>

<div class="message messagein">
  yes. :)
</div>
<div class="message messagein">
  anyway, im serious about the Rule of Three, t. I know u dont believe in it, but you really are shaped by the energy you put out. I see it work all the time.
</div>
<div class="message messagein">
  for example. i have this one patient whos seeing me for ptsd. 
</div>
<div class="message messagein">
  his last doc had him on luvox, but it made him nauseous and dizzy. so he switched to lexapro, which he didnt respond to. then they tried klonopin, but he got suicidally depressed.
</div>
<div class="message messagein">
  so when i got him, you know what i gave him?
</div>
<div class="message messagein">
  mullein!
</div>

<div class="message messageout">
  Is that a new anti-anxiety med? 
</div>

<div class="message messagein">
  its a flower!
</div>
<div class="message messagein">
  little yellow fuzzy flower.
</div>
<div class="message messagein">
  i made him a bracelet out of them. :)
</div>

<div class="message messageout">
  Let me guess. It’s a charm, right? 
</div>

<div class="message messagein">
  yes! a protection charm. for courage when confronted by evil spirits.
</div>
<div class="message messagein">
  i told him to wear the bracelet all day, and i taught him a spell to recite whenever he feels his anxiety coming back.
</div>

<div class="message messageout">
  You prescribed him a Wiccan ritual?
</div>
<div class="message messageout">
  Nat, are you actually allowed to do that? :P
</div>

<div class="message messagein">
   not really :)
</div>
<div class="message messagein">
  but it helped him a lot.
</div>

<div class="message messageout">
  ”Dear Swedish Medical Center Ethics Committee. My treatment methodology involved a magic bracelet...” ;)
</div>

<div class="message messagein">
  you think THATs the strangest thing theyve heard? :)
</div>
<div class="message messagein">
  anyway, the magick comes not from the bracelet, but from the mind of the wearer. the mullein merely acts as a focal point for the wearer to channel their own innate capacity for self-healing.
</div>
<div class="message messagein">
  part of the healing ritual involves making sure that the beneficiary KNOWS its a healing ritual.
</div>
<div class="message messagein">
  if it helps to understand it, you can think of it as the placebo effect. but the very fact that the placebo effect even works at all, ever, is sort of my entire point.
</div>

<div class="message messageout">
  Better living through self-deception? :)
</div>

<div class="message messagein">
  or self-fulfilling prophecy. call it what you will. either way, it really works.
</div>
<div class="message messagein">
  its the process of taking something in your mind, that you imagine, and using the power of your mind to manifest your imagination in the real world.
</div>
<div class="message messagein">
  and THAT, dear t, is magick. ;)
</div>

<div class="message messageout">
  :)
</div>
<div class="message messageout">
  So then, O Wizened Witch-Woman.
</div>
<div class="message messageout">
  What kind of magick can I use to improve this total shit-show of a situation I’ve got here?
</div>
<div class="message messageout">
  I mean, right now, here’s the potion for my life: take one part romantic failure, two parts professional failure, stir them in a crucible made of tungsten, and choke it down when it’s cold and bitter.
</div>

<div class="message messagein">
  *hugs*
</div>
<div class="message messagein">
  sorry things suck for you so much right now, t
</div>
<div class="message messagein">
  for what its worth, u should know that you are fortunate in that your trap is of your own creation. i say that not to assign you guilt or blame but to remind you that you have the power to dismantle it.
</div>
<div class="message messagein">
  for example, when it comes to dating, you can learn to recognize loser manchild jerks and stop wasting time on them. you need to find someone a little more mature 
</div>

<div class="message messageout">
  Got anyone in mind? 
</div>

<div class="message messagein">
  how about one of the scientists? 
</div>

<div class="message messageout">
  How about no more dating guys from the office? 
</div>
<div class="message messageout">
  Besides, they’re all dipshits. Everybody here sucks. I get zero respect here. ZERO. 
</div>
<div class="message messageout">
  I try to talk shop with the scientists sometimes, and they just humor me. Like, “Aww how cute! The Xerox girl is trying to use big words!”
</div>
<div class="message messageout">
  Fuck, they don’t know me! They don’t know that I know this shit. They don't know I was on track to be one of them back in college, before by dad got sick and I had to go help my mom take care of him.
</div>
<div class="message messageout">
  They never even fucking ask.
</div>

<div class="message messagein">
  why don’t u do something about it t?
</div>
<div class="message messagein">
  get yourself onto a research project maybe?
</div>

<div class="message messageout">
  You mean like the one where Drippy saws my head open and sticks probes in my brain? 
</div>
<div class="message messageout">
  They don’t take me seriously enough here to even consider the possibility of me doing real research.
</div>

<div class="message messagein">
  well, t, from their point of view, why should they?
</div>
<div class="message messagein">
  you are their office admin. that’s your role. you play it willingly. they have no reason to think of you as anything else.
</div>
<div class="message messagein">
  they don’t see inside you. they don’t know what your capable of. all they see is a receptionist. 
</div>
<div class="message messagein">
  they won’t give you a chance because you haven’t shown what you can do, and you haven’t shown what you can do because they haven’t given you a chance to.
</div>

<div class="message messageout">
  Yep. FML.
</div>

<div class="message messagein">
  dont you see? it's a spell.
</div>

<div class="message messageout">
  It’s a freakin curse.
</div>

<div class="message messagein">
  you have to break it, t.
</div>

<div class="message messageout">
  Yeah I know. I just wish I could prove myself to them.
</div>

<div class="message messagein">
  start by proving yourself to yourself.
</div>

<div class="message messageout">
  You say that like it’s so easy. Like my life is just full of opportunities to
</div>
<div class="message messageout">
  actually
</div>
<div class="message messageout">
  heh...
</div>

<div class="message messagein">
  ?
</div>

<div class="message messageout">
  You remember that slutty intern I’ve complained about? 
</div>
<div class="message messageout">
  She disappeared a few days ago.
</div>
<div class="message messageout">
  I spent all afternoon trying to track her down. Nobody’s heard anything from her.
</div>
<div class="message messageout">
  She totally fubarred some super-important assignment, and Drippy’s freaking out about it.
</div>
<div class="message messageout">
  It’s kindasorta why I’m stuck here tonight in the first place. To handle her firing paperwork.
</div>
<div class="message messageout">
  But...
</div>
<div class="message messageout">
  Wouldn’t it be awesome if I single-handedly retraced her steps and set everything right? 
</div>
<div class="message messageout">
  It’d be like, whoa! Christina Giordano! By day: abused office admin. By night: Molecular biologist slash superhero!
</div>
<div class="message messageout">
  Tun tata tuuuuuun!
</div>

<div class="message messagein">
  what kind of assignment is it?
</div>

<div class="message messageout">
  Don’t know. Drippy didn’t say. But I bet I can find out. I’m sure her desk is full of all sorts of interesting info.
</div>

<div class="message messagein">
  her desk? do u have access to it?
</div>
<div class="message messagein">
  would anyone notice if you poked thru it?
</div>

<div class="message messageout">
  I can get to her desk no problem. It’s in the big open office bullpen area.
</div>
<div class="message messageout">
  Nobody would notice. I’m alone here tonight.
</div>
<div class="message messageout">
  There’s cameras everywhere, but Drippy told me to track her down at all costs, so I have a perfectly good reason to dig through her desk. 
</div>

<div class="message messagein">
  so i don’t get why you haven’t already gone and done it.
</div>

<div class="message messageout">
  Oh shit.
</div>
<div class="message messageout">
  You think I should? Really?
</div>

<div class="message messagein">
  t, for fucks sake stop talking to me and go show them what you’re made of! :)
</div>

<div class="message messageout">
  Right now? For real?
</div>

<div class="message messagein">
  YES
</div>
<div class="message messagein">
  t?
</div>
<div class="message messagein">
  hello? u there?
</div>
<div class="message messagein">
  guess not.
</div>
<div class="message messagein">
  atta girl.
</div>

</div>
</div>