<div class="chapsection">
<p>
<span class="caplead">In the periphery of her vision</span>, something moved. Tina swore she saw a shadow glide across the adjoining hallway. If Tina hadn’t looked down from the last camera at that exact moment, she would have missed it entirely. 
</p>
<p>
Yet the corridor was dark. A split second later, she saw nothing.
</p>
<p>
She left the bullpen and peeked down the hallway. Faint noises came from around a corner.
</p>
<p>
Tina continued to the bend in the hallway. She saw light pouring from the doorway to the cold-storage room, where Tungsten kept samples of <em>E. coli</em> bacteria in suspended animation. She heard someone in there, rummaging through glassware.
</p>
<p>
She walked uncertainly toward the lit room. The hum of whirring HVAC machinery and the sound of clinking glassware grew louder as she approached. The door was open, and a chilly breeze poured from it.
</p>
<p>
She peeked inside. The door to the deep-freeze unit was open. Amidst the cold fog pouring out onto the floor, Tina could see a pair of black sneakers under the door, and could hear someone rifling through test tubes.
</p>
<p>
She watched for just a moment too long.
</p>
<p>
A man’s gloved fingers wrapped around the edge of the steel door and pushed it shut. The room got slightly quieter as the massive door’s rubber gasket muffled the hum of the deep-freezer’s cooling pumps.
</p>
<p>
She saw the man standing there, breathing into his gloves to recover from the cold. He wasn’t one of the scientists. He was muscular and athletic, in jeans and a dark jacket. He was in his late twenties or early thirties, and sported dark crew-cut hair. A Bluetooth earpiece sat in his ear. His expression was hard and resolute, and something about his face and posture hinted to her that he was no stranger to violence.
</p>
<p>
He saw her.
</p>
<p>
They looked at each other tensely.
</p>
<p>
Tina had left her iPhone charging at her desk. Her first instinct told her to sprint back to her lobby, call the police, and get the hell out of the building. Except she couldn’t, because he was staring at her. The only thing she could think to do was to run her receptionist program. “Hi. Can I help you?”
</p>
<p>
He replied in a foreign accent. The same accent, albeit much lighter, as Dr. Passinsky’s. Russian. “I’m from the courier service. I’m here to pick up a delivery for urgent shipment tomorrow. Has to arrive first thing in the morning. Sorry to bother you.”
</p>
<p>
As he spoke, he gazed at her like a wolf at a rabbit. Tina felt an intense tightness in her chest. “I’m supposed to sign visitors in at the front desk,” she said tentatively.
</p>
<p>
“Not necessary,” said the man, his eyes boring a hole through her. “I belong here. I have a keycard.” 
</p>
<p>
She stood immobile in the doorway, forcing herself to remain calm. “Well. Then. Good luck with the delivery. I’ll just go back to my desk now and finish my work. Okay?”
</p>
<p>
He stared at her silently. He said nothing in response.
</p>
<p>
“Okay?” she repeated, trying not to sound like she was pleading.
</p>
<p>
Finally, he said, “Okay.”
</p>
<p>
She resisted the urge to breathe a sigh of relief. She’d pretend to believe him about his deliveryman story, he’d pretend to believe her about believing it, and they’d both let the night proceed under this pleasant little fiction. “Okay,” she repeated with a nod, and slowly started backing out from the doorway. 
</p>
<p>
“You know what?” the man said suddenly. “I change my mind.”
</p>
<p>
With a quick, soundless motion, the man reached into his jacket, pulled out a gun, and pointed it at Tina. The stubby silver revolver was barely larger than his hand, but its barrel looked wide enough to stick a finger into. 
</p>
<p>
“Get in here, young lady,” he commanded. With a practiced flick of his thumb, managing to keep the squat barrel perfectly still, he cocked the revolver’s hammer back. It made a faint click, a tiny sound that somehow managed to ring louder than all of the machinery in the room.
</p>
<p>
She stepped through the doorway.
</p>
<p>
“Good girl,” he said as he carefully uncocked the hammer. “Now come over here.” 
</p>
<p>
He backed away several feet, keeping the gun trained on her as she walked toward the deep-freezer.
</p>
<p>
“That refrigerator,” he said to her, bobbing his head at the deep-freezer. “That’s long-term storage for microbe samples, yes?”
</p>
<p>
Tina nodded.
</p>
<p>
“Open it.”
</p>
<p>
She reluctantly grabbed the handle of the deep-freezer’s massive metal door and yanked. The door’s rubber gasket released its airtight seal, letting the cryogenic air spill into the room. Standing in front of the open door felt like being stabbed with thousands of tiny needle-sharp shards of ice.
</p>
<p>
“You know, I really am here for pickup,” the man said casually. “Your friend Julie &mdash; you know Julie, yes? &mdash; She left something here, that is really better left with someone else. Now, about you, I’m thinking maybe you could be useful. You want to be useful, yes?”
</p>
<p>
“What do you want?” Tina croaked out, shivering.
</p>
<p>
“Tell me,” said the crew-cut man with the Russian accent and the small revolver, “what the fuck is an Eppendorf tube?”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Satish smacked the cellphone</span> out of Mike’s hand with “<span class="computer">91</span>” on the dialer. “No cops!” he commanded.
</p>
<p>
“We have to, Satish!” said Mike. “Look at this crazy shit. We <em>have</em> to call the police!”
</p>
<p>
“Yeah, right,” Satish mocked. “And tell them what, exactly? ‘Oh, hi, me and my Dungeons and Dragons buddies were just casually hacking into this company, when we saw some scary stuff going on through their video feeds that we happened to hijack.’ Have you forgotten that what we’re doing here is illegal too?”
</p>
<p>
“You’re being paranoid,” said Mike.
</p>
<p>
“No, I’m erring on the side of caution,” Satish insisted. “Let’s just mind our own fucking business. There’s no point in risking our own necks.”
</p>
<p>
“So, we just sit here watching on our laptops like a bunch of useless dumbasses?” Mike shot back.
</p>
<p>
“Maybe you haven’t noticed, but this team <em>is</em> a bunch of useless dumbasses!” said Satish. “And, you know, with an idiot like Danny in charge, it’s not even really a surprise. The guy made it very clear back at the coffee shop that he has no idea what he’s doing! He hand-holds you through a bunch of script kiddie attacks, and then kisses your butts and tells you that you’re all awesome brilliant hackers. That’s fine, up to the point at which a stupid mistake can get you in real trouble &mdash; fines and jail for you, deportation for me. And we’re at that point now. So let’s just let this… this whatever-is-going-on-here, let’s just sit here, let it blow over, and resume the operation when everything’s nice and quiet again.”
</p>
<p>
Mike shook his head. “Let it ‘blow over’? But that girl in there is&mdash;!” 
</p>
<p>
“She’s not our fucking problem!” Satish insisted. 
</p>
<p>
Outside the car, Jason and Danny were staring at Danny’s laptop, watching the events in the cold-storage room unfold. The strained voices of the two men arguing reached them through the open car window. With his gaze fixed on the image of the dark-haired young woman held at gunpoint, Danny said to them in a low, grave voice, “She <em>is</em>. She <em>is</em> our problem. This is all our fault.”
</p>
<p>
“What are you going on about, Danny?” Satish said as he rolled his eyes. 
</p>
<p>
“We tricked her into leaving her desk,” Danny said slowly. His eyes were wide, his face pale in the light of his laptop screen. “We separated her from her computer and her phone. We created the window of opportunity for those guys to enter the building, and we deprived her of the means to call for help. <em>We</em> did this. This is on <em>us</em>.”
</p>
<p>
“On <em>us</em>?” said Satish. “No, Danny. On <em>you</em>! Don’t get <em>me</em> into this. That camera trick was <em>your</em> idea.”
</p>
<p>
Mike angrily barked at Satish, “Hey man, it was <em>you</em> who said we can’t proceed if she’s at her desk!” 
</p>
<p>
“And you agreed!” Satish retorted. “So if anything, you’re just&mdash;”
</p>
<p>
“Guys, stop…!” Danny said, not so much as a command but as a plea. He looked back and forth between them and the screen. The girl in the video feed stood before the giant refrigerator, shivering. “God. Satish is right. Jason put <em>me</em> in charge…”
</p>
<p>
Jason interjected, “Whoa, Danny! I hired you to extract <em>data</em>. This project wasn’t supposed to involve…” He pointed at the man on the screen, who kept his small silver revolver trained unwaveringly on the receptionist. “…<em>that</em>.”
</p>
<p>
Danny handed Jason the laptop and leaned back against the car, his hands at his temples. “But everything Satish said is true,” he muttered, his throat suddenly dry and hoarse. “I <em>don’t</em> know what I’m doing. I’m way out of my league. Sure, I can put on a <em>show</em> of competence, right? I can play at being a ’Leet Hacker Dude, as long as I’m around people who don’t know any better. I can act important. Make myself feel significant. Pretend that I’m not past my prime, that I’m not steadily getting more and more irrelevant year after year, with one failed dot-com project after another. I can fake it pretty darn well, can’t I? And that’s perfectly good enough if there’s no actual shit hitting the fan. But when there’s the real possibility of someone getting hurt because of me… The real possibility of that girl getting…” He covered his face with his hands. “My God, what have I done?”
</p>
<p>
Satish nodded smugly and said, “So you agree we should lay low, right?”
</p>
<p>
Danny shook his head vigorously, as though the motion could clear away his current reality like an Etch A Sketch doodle. “I have to <em>undo</em> this! I have to Control-Z. I have to reload a previous save…” He turned to look at the building across the dark street. The gunman still stood loitering by the front door. Danny gulped hard, and said, “I have to go in there.”
</p>
<p>
Eyebrows cocked all around him. 
</p>
<p>
“Guys, we’re still here to do a job,” he said to the four men staring at him askance. His voice was pensive. His eyes gazed out into the middle distance, focused on nothing. “I think maybe… Instead of bailing, we might be able to use this situation to our advantage.”
</p>
<p>
Jason asked cautiously, “What do you mean, Danny?”
</p>
<p>
“That guy in the building is making Christina dig through the freezer. They’re looking for something. What we’re watching isn’t a kidnapping. They’re pulling off a robbery.”
</p>
<p>
Jason shrugged. “And…?”
</p>
<p>
“And so are we,” said Danny. “The difference is, <em>they</em> seem to know what they’re looking for. We’re here to steal Tungsten’s secrets, right? Well, <em>something</em> is in that freezer. Something valuable. I say we take it. We’re hackers, right? Let’s hack their theft in progress and make it our own.”
</p>
<p>
Jason looked at him in aghast silence for a moment. “Jesus. You’re serious. Danny, have you lost your mind? They’ll <em>kill you</em>.”
</p>
<p>
Danny looked down, his brow furrowed in thought. “Not necessarily. I think can out-maneuver them in there.”
</p>
<p>
“How?” the middle-aged financier asked. “Look at those guys! They’re obviously not new at this. They have guns, they have training, they have experience…”
</p>
<p>
“We’ve got a massive tactical advantage,” Danny said slowly. With a pointed finger, he tapped loudly on the screen of his laptop.
</p>
<p>
Mike nodded his big furry head. “The cameras. You’re talking about going all Splinter Cell on them, right? Covert ops?”
</p>
<p>
“Right,” said Danny. “We can see everything going on in there. They can’t. And that information asymmetry means that <em>we</em> have the upper hand. At Claymore, I built Navy communication grids. Modern battlefields are digital. During both Iraq wars, what’s the first thing the US Army did? Knocked out the enemy computer networks. During the riots in Iran and Libya and Syria, the rulers disabled civilian access to cellphones. Information, you see, is what the military refers to as a ‘force multiplier’. Those guys in there have the guns. But the information? That’s <em>our</em> game.”
</p>
<p>
“I want in,” said Mike. He hopped out of the car and went to stand by Danny. “I said at the beginning that I’d be your muscle if things got physical. I keep my word.” With a deep and somber nod, Danny proffered his gratitude.
</p>
<p>
“Do you have a plan, Danny?” asked Jason.
</p>
<p>
“Not yet,” he said. “First thing we need to do is find a way into the building…”
</p>
<p>
Satish said grudgingly, “I can get you in.”
</p>
<p>
“You can?” said Danny.
</p>
<p>
“Yeah,” Satish answered. He was still standing with his back against the Navigator, sulking. “I think you’re completely insane, but if you’ve decided to go get yourself killed then I guess I can help.” He fiddled with his laptop. “Here, Danny. Look at the outside camera. Zoom in on the keycard reader.”
</p>
<p>
Danny pulled up the feed on his laptop. As he watched, the green light popped on to indicate the door was unlocked. It stayed lit for several seconds.
</p>
<p>
“A simple replay attack,” Satish explained. “When that guy opened the door, the keycard reader sent a UDP packet to an authentication database, which replied with a datagram to unlock the door. I saw the whole thing on my packet sniff. I just sent the keycard reader an exact copy of the authorization message.”
</p>
<p>
“Great,” Danny said with forced confidence. “Now all we need is a way to get that guy away from the front door. Let me think…” He stood staring at the ground. His body remained frozen, but his eyes darted rapidly in spastic patterns. His lips writhed with soundless mumbling. His fingers twitched as though drawing diagrams in an ethereal notebook. After a minute of fidgety silence, he looked up abruptly. “Jason. You’re part of this little Dungeons and Dragons group, right? How are your role-playing abilities?”
</p>
<p>
“Uhh… pretty good, I guess…” Jason said apprehensively.
</p>
<p>
Mike cleared his throat and interjected, “He’s being extremely humble.”
</p>
<p>
“Thanks, Mike…” Jason replied with a dubious smile. “When I was a young sales associate I did a lot of improv theater. I found that it helped build cold-calling skills.”
</p>
<p>
“We’ll your participation,” said Danny. “And your car. Do you have anything we can use as a weapon? A flare gun, maybe? Or a lug wrench?”
</p>
<p>
“That’s a big metal tool for changing tires, right? Looks like a plus sign?” Jason asked. “It’s under the spare tire in the back.”
</p>
<p>
Danny turned his head to Mike. “You said you play hockey, right? Think you can handle beating someone into submission with a metal stick?”
</p>
<p>
Mike grinned enthusiastically.
</p>
<p>
“Moshen,” said Danny. “Get out of the car. You and Satish will stay right here.” 
</p>
<p>
“What about you, Danny?” asked Jason.
</p>
<p>
“Me? I’ll be going in with <em>this</em>.” 
</p>
<p>
He opened the passenger door and grabbed his Claymore tote bag. He began pulling out bits of metal and plastic one by one, starting with the piece that looked like a narrow homemade bullhorn with the pistol grip and the large rubber-coated blocks on the back.
</p>
<p>
After the bullhorn came a row of plastic blocks, each as big as a Rubik’s Cube, joined into a line with duct tape. Next came a group of eight heavy blue cylinders, each one the size and shape of a tallboy beer can, arranged like an eight-pack and bracketed together with stiff wire. Each component was strung on thick black and red cables, the junction points buried under a slather of caulk and epoxy. 
</p>
<p>
A two-foot-long white hollow plastic tube, about four inches wide with slots and grooves all along its length, stuck out from the top of the bag. Danny grabbed it and began screwing it onto the back of the horn.
</p>
<p>
“The hell’s that thing?” asked Moshen.
</p>
<p>
“Well,” said Danny as he worked, “this part in front is a magnetron that I ‘borrowed’ from a battleship radar system at Naval Base Kitsap.” He took the eight-pack of heavy blue cylinders and clipped it to the back of the white tube. “<em>This</em> is a bank of high-voltage ultracapacitors from a hybrid car powertrain. They can pump out almost a megajoule per second. <em>This</em>…” He Velcro’ed the plastic cubes along the length of the tube like the spine of some ancient reptilian creature. “…is a set of relays for switching between serial charge and parallel discharge…”
</p>
<p>
He pulled out a slotted metal box with air vents and a three-prong power socket. “This is the power conversion module,” Danny said as he attached it to the tube. “And <em>this</em>…” He pulled out a stack of laptop batteries. “…is a stack of laptop batteries.” The stack was about a dozen batteries high, all duct-taped together with their metal contacts tethered to one another with coils of cable.
</p>
<p>
He stood up and held the device in both hands. Fully assembled, it was about four feet long. With the flick of a few switches, tiny lights lit up near the capacitor bank. Small fans whirred to life inside the power supply box. The device emitted a faint high-pitched whine that rose until it passed above the range of human hearing.
</p>
<p>
He held the pistol grip of the magnetron horn with his right hand, and slung the end of the PVC tube over his arm. His right shoulder bore the weight of the assorted duct-taped and snapped-in components on the back of the device.
</p>
<p>
The men gawked. “Seriously, Danny, what is that thing?” demanded Jason.
</p>
<p>
Danny gave a faint chuckle, “It’s just a… A flashlight.” 
</p>
<p>
“That’s one seriously elaborate flashlight,” said Jason.
</p>
<p>
“It’s very, very bright,” said Danny, and inhaled sharply through his nose. “Alright, friends. Here’s what’s going to happen…” 
</p>
</div>