<div class="chapsection">
<p>
<span class="caplead">In the periphery of her vision</span>, something moved. Tina swore she saw a shadow glide across the adjoining hallway. If she hadn’t looked down from the camera at that exact moment, she would have missed it entirely. Light spilled out from the far end of the dim corridor. It had been completely dark just a minute before.
</p>
<p>
She edged uncertainly toward the illumination. On rounding a bend, she saw that the light shone from the cold-storage room, where Tungsten kept samples of <em>E. coli</em> bacteria in suspended animation. The hum of whirring HVAC machinery and the sound of clinking glassware grew as she approached.
</p>
<p>
She peeked inside. The door to the deep-freeze unit hung open. Amidst the cold fog pouring out onto the floor, Tina could see a pair of black sneakers under the door, and could hear someone rifling through test tubes.
</p>
<p>
A man’s gloved fingers wrapped around the edge of the steel door and pushed it shut. 
</p>
<p>
The man wasn’t one of the scientists. Indeed, everything about his clothes and demeanor made it obvious that he didn’t belong anywhere near a laboratory.
</p>
<p>
He saw her.
</p>
<p>
Tina had left her iPhone charging at her desk. Instinct pressed her to sprint back to the lobby, call the police, and get the hell out of the building. Except she couldn’t, because his eyes locked onto hers, freezing her body and mind as solidly as the specimens in the fridge.
</p>
<p>
“Hi. Can I help you?” The words hung in the air for a moment before she realized that the receptionist automaton voice that had uttered them was her own.
</p>
<p>
He replied in a foreign accent &mdash; the same accent as Dr. Passinsky’s: Russian. “I’m from the courier service. I’m here to pick up delivery for urgent shipment tomorrow. Has to arrive first thing in the morning.”
</p>
<p>
He gazed at her like a wolf at a rabbit. Tina felt a crushing tightness in her chest. “I’m supposed to sign visitors in at the front desk…”
</p>
<p>
“Not necessary,” said the man, his eyes boring a hole through her. “I belong here. See? I have a keycard.” 
</p>
<p>
She stood immobile in the doorway, forcing herself to remain calm. “Good luck with the delivery. I’ll just go back to my desk now and finish my work. Okay?”
</p>
<p>
He stared at her silently.
</p>
<p>
“Okay?” she repeated, trying not to sound like she was pleading.
</p>
<p>
Finally, he said, “Okay.”
</p>
<p>
She resisted sighing in relief. She’d pretend to believe his deliveryman story, he’d pretend to believe her about believing it, and they’d both let the night proceed under this pleasant little fiction. “Okay,” she repeated with a nod, and slowly started backing out from the doorway. 
</p>
<p>
“You know what?” the man said suddenly. “I change my mind.”
</p>
<p>
With a quick, soundless motion, the man reached into his jacket, pulled out a gun, and pointed it at Tina. The revolver was barely larger than his palm, but its barrel looked wide enough to stick a finger into. 
</p>
<p>
“Get in here, young lady.” With a practiced flick of his thumb, managing to keep the barrel perfectly still, he cocked the revolver’s hammer back. It made a click, a tiny sound that somehow managed to ring louder than all of the machinery in the room.
</p>
<p>
She stepped through the doorway.
</p>
<p>
“Good girl. Now come here.” He backed away several feet, keeping the gun trained on her. “That refrigerator…” He bobbed his head at the deep-freezer. “That’s long-term storage for microbe samples, yes?”
</p>
<p>
Tina nodded.
</p>
<p>
“Open it.”
</p>
<p>
She grabbed the handle of the deep-freezer’s massive metal door and yanked. The door’s rubber gasket released its seal, letting the cryogenic air spill into the room. Standing in front of it felt like being stabbed with thousands of needle-sharp shards of ice.
</p>
<p>
“You know, I really am here for pickup,” the man said. “Your friend Julie &mdash; you know Julie, yes? &mdash; She left something here, that is really better left with someone else. Now, about you, I’m thinking maybe you could be useful. You want to be useful, yes?”
</p>
<p>
“What do you want?” Tina croaked.
</p>
<p>
“Tell me,” he said, “what the fuck is an Eppendorf tube?”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Jason smacked the cellphone</span> out of Mike’s hand with “<span class="computer">91</span>” on the dialer. “No cops!”
</p>
<p>
“Look at this shit, Jason!” said Mike. “We <em>have</em> to call the police!”
</p>
<p>
“And tell them what, exactly?” Jason replied. He stood outside the car at the open window beside Mike, his arm still stretched inside. “‘Oh, hi, me and my Dungeons and Dragons buddies were just hacking into this company, when we saw some scary stuff going on through their video feeds that we happened to hijack.’ Have you forgotten that what we’re doing here is illegal too?”
</p>
<p>
“You’re being paranoid,” said Mike.
</p>
<p>
“With damn good reason!” Jason insisted. “Think about how much we each have to lose if any of this gets back to us &mdash; me especially. Now look, I know you’re a bunch of talented guys, and you <em>think</em> that maybe you can cover your tracks. But what if you’re wrong? Think about the kind of computer forensics experts that the cops can bring in on a case like this. They’ll zero in on the tiniest little mistake you could possibly make. So let’s just let this… this whatever-is-going-on-here, let’s let it blow over, and resume the operation when everything’s nice and quiet again.”
</p>
<p>
Mike shook his head. “Let it ‘blow over’? But that girl in there is&mdash;!” 
</p>
<p>
“She’s not our problem,” Jason said, avoiding eye contact. “I hate to say it that bluntly, but we didn’t cause her situation, so it’s not our responsibility to get her out of it.”
</p>
<p>
Danny stared at the live video of the dark-haired young woman held at gunpoint. “We <em>did</em>, though. We <em>did</em> cause this. This is all our fault.”
</p>
<p>
“<em>Our</em> fault, Danny?” said Jason, incredulous. 
</p>
<p>
Moshen, from behind them, murmured, “Our camera-spinning trick.”
</p>
<p>
Danny nodded gravely. “We lured her away from her desk. We separated her from her computer and her phone. We created the window of opportunity for those guys to enter the building, and we deprived her of the means to call for help. <em>We</em> did this. This is on <em>us</em>.” He looked back and forth between them and his screen. The girl in the video feed stood before the giant refrigerator, shivering. “God. Jason, you put <em>me</em> in charge, and I…” He shook his head vigorously, as though the motion could clear away his current reality like an Etch A Sketch doodle. “I have to Control-Z. I have to reload an earlier save… I have to <em>undo</em> this!”
</p>
<p>
“Don’t be silly, Danny,” Jason insisted. “Let’s just lay low and…”
</p>
<p>
“<em>No!</em>” The sudden strength of Danny’s voice startled them all &mdash; particularly Danny himself. He took a deep breath. “Listen, we’re still here to do a job. I think maybe… Instead of bailing, we might be able to use this situation to our advantage. ”
</p>
<p>
Eyebrows cocked around him.
</p>
<p>
“That guy is making Christina dig through the freezer. They’re looking for something. What we’re watching isn’t a kidnapping. They’re pulling off a robbery.”
</p>
<p>
Jason shrugged. “And…?”
</p>
<p>
“And so are we,” said Danny. “The difference is, <em>they</em> seem to know what they’re looking for. We’re here to steal Tungsten’s secrets, right? <em>Something</em> is in that freezer. Something valuable. I say we take it. We’re hackers, right? Let’s hack their theft and make it our own.”
</p>
<p>
Jason regarded him, aghast. “Jesus. You’re serious. Danny, have you lost your mind? They’ll <em>kill you</em>.”
</p>
<p>
Danny looked down, his brow furrowed. “Not necessarily. I think can outmaneuver them in there.”
</p>
<p>
“How?” the financier asked. “<em>Look</em> at those guys! They’re not new at this. They have guns, training, experience&mdash;”
</p>
<p>
“<em>We’ve</em> got a massive tactical advantage,” Danny tapped his laptop screen.
</p>
<p>
Mike nodded. “The cameras. You’re talking about going all Splinter Cell on them, right? Covert ops?”
</p>
<p>
“Right,” said Danny. “We can see everything in there. They can’t. And that information asymmetry means that <em>we</em> have the upper hand. At Claymore, I built Navy communication grids. Modern battlefields are digital. During both Iraq wars, what’s the first thing the US Army did? Knocked out the enemy computer networks. During the riots in Iran and Libya and Syria, the rulers disabled civilian access to cellphones. Information is what the military refers to as a ‘force multiplier’. Those guys in there have guns. But information? That’s <em>our</em> game.”
</p>
<p>
“I want in,” said Mike, hopping out of the car. “I said I’d be your muscle if things got physical. I keep my word.”
</p>
<p>
“Do you have a plan, Danny?” asked Jason.
</p>
<p>
“Not yet. First, we need to find a way into the building…”
</p>
<p>
“I think I can arrange that,” offered Mike. “Look at the outside camera. Zoom in on the keycard reader.”
</p>
<p>
Danny pulled up the feed. As he watched, the green light popped on to indicate the door was unlocked. It stayed lit for several seconds.
</p>
<p>
“A simple replay attack,” Mike explained. “When that guy opened the door, the keycard reader sent a UDP packet to an authentication database, which replied with a datagram to unlock the door. I saw it on my packet sniff, and noticed that there’s no crypto handshake. I just sent the keycard reader a copy of the authorization message.”
</p>
<p>
“Can you teach Moshen to do that?” asked Danny.
</p>
<p>
Mike shrugged. “I can write a script for him to run. Should be pretty straightforward.”
</p>
<p>
“Great,” Danny said, forcing a veneer of confidence. “Now all we need is a way to get that guy away from the front door. Let me think…” He stood staring at the ground. His body remained still, but his eyes darted spastically. His fingers twitched as though drawing diagrams in an ethereal notebook. After a minute of fidgety silence, he looked up abruptly. “Jason. You’re part of this little Dungeons and Dragons group. How are your role-playing abilities?”
</p>
<p>
“Uhh… pretty good, I guess…” Jason said apprehensively.
</p>
<p>
Mike cleared his throat and interjected, “He’s being extremely humble.”
</p>
<p>
“Thanks, Mike…” Jason replied through a dubious smile. “When I was a young sales associate, I did a lot of improv theater. It helped me build cold-calling skills.”
</p>
<p>
“We’ll need your help,” said Danny. “And your car. Do you have anything we can use as a weapon? A flare gun, maybe?”
</p>
<p>
“There’s a lug wrench in the trunk, under the spare tire,” Jason replied.
</p>
<p>
Danny turned to Mike. “You said you play hockey, right? Think you can handle beating someone with a stick?”
</p>
<p>
Mike grinned.
</p>
<p>
“Moshen,” said Danny. “Get out of the car. You’ll stay over here.” 
</p>
<p>
“What about you, Danny?” asked Jason.
</p>
<p>
“Me? I’ll be going in with <em>this</em>.” 
</p>
<p>
He opened the passenger door and grabbed his Claymore tote bag. He began pulling out bits of metal and plastic, and clipping and twisting them together.
</p>
<p>
First came the narrow bullhorn-looking device, with its pistol-like handle. It was followed by a row of plastic blocks, each as big as a Rubik’s Cube. Next emerged a group of heavy blue cylinders, each one the size and shape of a beer can, arranged like an eight-pack. Each component was strung on cables, the junction points buried under slathers of caulk and epoxy. 
</p>
<p>
A two-foot-long white hollow plastic tube, about four inches wide with slots and grooves all along its length, protruded from the bag. Danny screwed it onto the back of the horn.
</p>
<p>
“The hell’s that thing?” asked Moshen.
</p>
<p>
“Well,” said Danny as he worked, “this part in front is a magnetron I ‘borrowed’ from a battleship radar system at Naval Base Kitsap.” He took the eight-pack of cylinders and affixed it to the back of the white tube. “<em>This</em> is a bank of high-voltage ultracapacitors from a hybrid car powertrain. <em>This</em>…” He Velcro’ed the plastic cubes along the length of the tube. “…is a set of relays for switching between serial charge and parallel discharge…” He pulled out a slotted metal box with vents and a socket. “This is the power conversion module,” Danny declared while attaching it to the tube. “And <em>this</em>…” He pulled out a stack of laptop batteries. “…is a stack of laptop batteries.” The stack was about a dozen batteries high, all duct-taped together with their metal contacts tethered to one another with coils of cable.
</p>
<p>
He stood up and held the device in both hands. Fully assembled, it was about four feet long. With the flick of a few switches, tiny lights sparked alive near the capacitor bank. Fans whirred inside the power supply box. The device emitted a faint high-pitched whine that rose until it passed above the range of human hearing, like a high-end camera flashbulb charging up for a photograph.
</p>
<p>
He held the pistol grip of the magnetron horn with his right hand, and slung the end of the PVC tube over his arm. His right shoulder bore the weight of the assorted duct-taped and snapped-in components on the back of the device.
</p>
<p>
The men gawked. “Seriously, Danny, what is that thing?” demanded Jason.
</p>
<p>
Danny gave a faint chuckle. “It’s just a… A flashlight.” 
</p>
<p>
“That’s one elaborate flashlight,” said Jason.
</p>
<p>
“It’s very bright,” said Danny, and inhaled sharply. “Alright, guys. Here’s the plan…” 
</p>
</div>