<div class="chapsection">
<p>
<span class="caplead">The black Lincoln Navigator</span> wound awkwardly around Tungsten’s parking lot towards the building’s entrance, driving slowly and weaving back and forth. The man standing by the door studied the oddly-moving SUV apprehensively as it approached.
</p>
<p>
The car came to a stop far from the entrance. The driver-side window rolled down, revealing a middle-aged man with gelled gray hair, illuminated by the light pouring through the glass doors of Tungsten’s brightly-lit lobby.
</p>
<p>
Jason’s head drooped weakly. His mouth hung open and his eyes didn’t focus. He tried to speak, but all that came out was a raspy whisper.
</p>
<p>
The man at the entrance said something into his Bluetooth headset and then barked at him, “What do you want?”
</p>
<p>
Jason made an effort to speak louder. “Is this the Weisenbaum Clinic?” he asked slowly in a hoarse, nasal voice.
</p>
<p>
The man made a brushing motion with his free hand. “No. Go away.”
</p>
<p>
“It’s supposed to be right here,” Jason whined. “I see the big ‘W’ on the door.”
</p>
<p>
“This isn’t a clinic,” the man barked.
</p>
<p>
“Please, it’s very important,” Jason said, drawing out and enunciating each word. “I have an urgent medical condition. I need to go see…” His speech degenerated into a series of wheezes and coughs. “Please, I just need the address. Can you…” He coughed and wheezed again. “Can you come closer please? It hurts for me to talk so loud.”
</p>
<p>
With an exasperated sigh, the man took a few steps toward the SUV.
</p>
<p>
“I know the phone number to the clinic,” Jason whispered slowly and breathily, “but my telephone is broken. Maybe you can make a call for me?”
</p>
<p>
The man glared at him. “If I do, will you go away?”
</p>
<p>
“Yes.”
</p>
<p>
The man said something in Russian into his headset, his tone of annoyance crossing the language barrier. He reached into his pocket and pulled out his cellphone. “Okay, give me the number,” he grumbled.
</p>
<p>
“Four two five,” Jason said slowly, “Eight six five… Eight six five two? No, wait, eight six five three…”
</p>
<p>
“Eight six five eight six five two?” said the man as he punched in the sequence.
</p>
<p>
“No, sorry, eight six five is just the first part. I was just repeating it to make sure you got it. Four two five, eight six five…”
</p>
<p>
“Four two five, eight six five…” repeated the man as he dialed.
</p>
<p>
“Right. Four two… Oh, you know what? I’m sorry. That’s my daughter’s number. The one to the clinic is four two five, eight five three… Wait, eight five or eight six…?”
</p>
<p>
The man growled in frustration. 
</p>
<p>
He was spending so much concentration trying to dial Jason’s number that he didn’t notice the green light pop on above the keycard reader on the big glass doors behind him.
</p>
<p>
Nor did he notice Mike tiptoeing his way along the wall, making his way silently toward the entrance.
</p>
<p>
Until Mike finally ducked through the door.
</p>
<p>
The whole area in front of the entrance was illuminated by the light coming from the lobby. Mike had to step into the light in order to pass through the large glass doors. His shadow swept across the man and the black SUV.
</p>
<p>
Danny cursed silently. He should’ve anticipated that. He hadn’t.
</p>
<p>
“What the fuck!” the man said. He turned his head just in time to see Mike heading into the hallway on the other side of the lobby.
</p>
<p>
That’s when the man’s cellphone exploded.
</p>
<p>
The phone jumped in his hand with a loud “<em>crack!</em>” A shower of white sparks burst somewhere within, spilling out from the sides and from the seams around the buttons. Arcs of electricity flashed across its face. The man yelped and dropped it to the ground.
</p>
<p>
Jason slammed on the gas. The SUV’s tires squealed in place before hurling the car forward. Jason steered a twisting, zigzagging pattern back out to the street.
</p>
<p>
The man’s head swiveled rapidly between the car and the building entrance. Turning his face toward the car, he let his jacket fall to the ground and drew the long barrel of the silenced semiautomatic handgun up to shoulder height. He held the gun with both hands and took aim. 
</p>
<p>
He pulled the trigger several times. The gun didn’t make a “<em>bang!</em>” It did, however, make a popping noise, together with the clacking sound of interlocking spring-loaded metal parts snapping into place, like a very large stapler. Even with the silencer, the report from the firearm was quite loud.
</p>
<p>
“Fuck!” screamed Jason into the hands-free conference call in progress on his cellphone. A bullet glanced off of the rear driver’s side window, leaving a deep scar in the glass, just as Jason cleared the parking lot. The car lurched as he made a sharp turn onto the street, bolting away from the building.
</p>
<p>
Having lost Jason’s SUV, the man turned toward the Tungsten entrance. He thrust his hip toward the card-reader. The little green light popped on.
</p>
<p>
“He’s heading in,” said Moshen on the conference call.
</p>
<p>
Danny crouched behind the corner of the Tungsten building, out of sight from the main entrance. Beside him, his contraption whined faintly with a rising high-pitched tone, its tiny lights glowing red. “Mike, he’s coming for you,” Danny said into his cellphone. “Make sure he follows you to the stockroom. Moshen, keep him safe.”
</p>
<p>
“Aye aye,” said Moshen. “Mike, Satish has you on camera, and I’ve got the guy after you. He’s in a hallway about fifty feet behind you.”
</p>
<p>
Mike’s voice asked, “How do I get to the stockroom from here?”
</p>
<p>
“End of the hall,” Moshen directed. “Make a left…”
</p>
<p>
On the conference call, Danny heard Mike running through Tungsten’s hallways. Moshen guided him, always keeping him one turn ahead of his pursuer. A distant <em>pop-clack!</em> occasionally punctuated the dialog.
</p>
<p>
“Now Mike, remember,” said Danny. “There’s a keycard scanner on the outside of the door to the stockroom. So once you get into the stockroom, you can’t get back into the Tungsten offices without a keycard. The only way out of that stockroom is through the fire door near the loading dock.”
</p>
<p>
Moshen added, “He’s walking slowly down the hall toward you with his gun drawn. Stay out of sight, Mike.”
</p>
<p>
The conference call carried the sound of a door opening. “I’m in the stockroom,” said Mike. 
</p>
<p>
Danny caught himself nibbling on his fingernails. “Jason. Where are you?”
</p>
<p>
“Down the street,” said Jason’s voice. “There’s bullet holes in my car. The repairs are coming out of your pay.”
</p>
<p>
“Come back here,” said Danny. “Quickly. Get to the loading dock.”
</p>
<p>
Danny saw headlights on the road beyond the parking lot. Jason’s SUV came back into view and proceeded back towards the Tungsten building.
</p>
<p>
“Mike!” said Moshen. “I see the guy coming up to the stockroom door!”
</p>
<p>
Danny watched Jason’s SUV roll past the parking lot toward the back of the building. “Jason’s not in position yet,” Danny said into the cellphone. “Mike, can you keep him busy in the stockroom for a few seconds?”
</p>
<p>
Danny heard Mike grunting and straining. The sound was followed by a few popping, clacking shots from the silenced handgun.
</p>
<p>
“Holy shit!” yelled Danny. “Mike! Mike, are you alright? What’s happening?”
</p>
<p>
Satish’s voice came across the call. “He looks fine. He tried to push over one of the shelves of inventory. The guy busted in on him and opened fire, but he managed to duck behind some old junk. He’s hiding behind an X-ray machine or something.”
</p>
<p>
“What’s the guy doing?” Danny asked.
</p>
<p>
Moshen answered, “He’s crouched and ready, both hands on his gun, about thirty feet away from Mike. It looks like he doesn’t know where Mike is.”
</p>
<p>
“Mike, did you hear that?” asked Danny.
</p>
<p>
Moshen replied, “He’s nodding Yes, Danny. He’s holding the lug wrench in one hand and his cellphone in the other. He’s putting them down on the floor and picking up something from a shelf near him… It looks like a weird old computer… He’s slowly sticking it out from the machine he’s hiding behind… oh shit!”
</p>
<p>
“What?” Danny demanded.
</p>
<p>
“He shot it out of his hand!”
</p>
<p>
Danny cursed under his breath. “Guys, I’m going in,” he said as he walked to the entrance. “Satish, the front door, please.”
</p>
<p>
The green light popped on above the card reader. Danny entered the building and hustled down the corridors toward the stockroom, keeping his cellphone pressed to his ear while carrying his contraption. Moshen’s voice guided him through the dark, unfamiliar office hallways, past rooms of strange apparatuses and doors marked with ominous warnings and hazard symbols.
</p>
<p>
Jason’s voice came across the air. “I’m in position, Danny.”
</p>
<p>
Satish said, “Mike’s pinned down. If he moves, he’ll get shot.”
</p>
<p>
Danny arrived at the hallway outside the stockroom. Before him was a large metal door. Embedded in the door was a small glass window, no bigger than a person’s face, positioned just barely high enough to see through. The stockroom’s low fluorescent emergency lights made the small square of glass emit a faint sickly yellow shine at the end of the dim hallway. On the wall, a foot away from the door, was a glowing green button attached to a thin electrical cable conduit that ran up to the ceiling. The cable split off and connected to a large block that pressed up against a silvery rectangle at the top of the door &mdash; the electromagnet and armature plate of a magnetic lock system.
</p>
<p>
Mike whispered into the call, “Moshen. You said he’s about thirty feet away from me toward the entrance, right?”
</p>
<p>
“Yeah,” said Moshen.
</p>
<p>
“Mike, I’m right outside,” Danny said into the cellphone. “What are you doing?”
</p>
<p>
“I’m gonna throw this thing at him,” Mike said very quietly.
</p>
<p>
“What thing?” asked Danny.
</p>
<p>
“I’m not sure,” said Mike. “It looks kind of like an old computer, but it’s all round and purple and it says ‘SGI O2+’ on the front.”
</p>
<p>
“Dude!” said Danny. “In the late ‘90s, that thing used to be the most popular 3D rendering workstation on the consumer market!”
</p>
<p>
“Yeah well,” said Mike, “let’s see if it makes a good projectile weapon.”
</p>
<p>
Both through the cellphone and through the door in front of him, Danny heard Mike give a mighty grunt, followed by a crashing noise and the “<em>pop-clack!</em>” of the silenced semiautomatic. On the far side of the stockroom, the metal bar on the fire door released its latch as Mike body-checked his way through the exit. 
</p>
<p>
Jason’s voice announced, “Mike, you’re okay!” It sounded distant and slightly echoing. Jason’s voice was being picked up both by his own cellphone and by Mike’s.
</p>
<p>
“Punch it!” yelled Mike.
</p>
<p>
 Danny heard a crunching thud as Jason backed his SUV up against the fire exit. Jason had positioned his car about three feet away from the door, and had been waiting to see Mike run out. The moment Mike cleared the door, Jason slammed the back of his car against it and engaged the parking brake. The fire door opened outward, so the SUV served as a very large, very expensive, very effective doorstop.
</p>
<p>
“Good job, Mike,” said Danny. “Now make your way around the outside of the building, get back in through the front doors, and come on back here.”
</p>
<p>
“On my way,” said Mike. 
</p>
<p>
From inside the stockroom, Danny could hear the man throwing himself against the fire exit in a useless attempt to push away the SUV. The “<em>pop-clack!</em>” of the gun sounded a few times, then silence.
</p>
<p>
Danny waited tensely in the dim hallway outside the stockroom door. “Is he coming back this way yet?” he asked.
</p>
<p>
“Not yet,” said Moshen. “Good news is you have an extra second or two. Bad news is, that’s because he’s reloading. Get ready.”
</p>
<p>
Danny took a deep breath and put the end of his device up against the wall, just under the button that would open the large metal stockroom door. The machine’s small red and green indicator LEDs looked like Christmas-tree lights in the unlit hallway.
</p>
<p>
“He’s coming up to the door…” said Moshen.
</p>
<p>
Danny heard a bit of movement on the other side. The wall, he reckoned, was made of six inches’ worth of drywall, wood, and foam insulation &mdash; all of which was almost completely transparent to microwaves.
</p>
<p>
 “Now!” yelled Moshen.
</p>
<p>
Danny pulled the trigger. 
</p>
<p>
The mechanical arms of the high-power relays all clicked simultaneously against their contacts inside the spine of plastic cubes. The pulsed discharge of current from the capacitor bank to the magnetron sent a soft low-pitched “<em>bonk!</em>” through the air around it. Lights along the capacitor bank flipped from green to red.
</p>
<p>
On the other side of the wall, Danny heard a snapping, cracking sound, followed by a man screaming in shocked frustration and unleashing a long stream of Russian curse words. The man pulled in vain at the door handle on the other side. The door shook slightly but refused to yield. 
</p>
<p>
Danny held his device triumphantly over his shoulder. Its fans whirred to cool it from its recent shot. The capacitor bank began to recharge, emitting its characteristic rising whine.
</p>
<p>
A round shadow eclipsed the sickly yellow glow of the small window embedded in the door. In the dim light, Danny could just barely make out the man’s face, looking at him through the glass with eyes of fury. The man’s cursing fell silent. He simply stared at Danny in impotent rage.
</p>
<p>
Danny gave the man a smug shrug, waved goodbye, and turned around to saunter away.
</p>
<p>
He had barely made it two steps when he heard a “<em>pop-clack!</em>”, coupled with the sound of shattering glass.
</p>
<p>
Danny turned to look.
</p>
<p>
All that remained of the small square window was a few jagged shards. The man drew his gun up to the shot-out window. The end of the silencer came to rest upon a crag of broken glass. The man looked down the sights and took aim.
</p>
<p>
Danny felt the world recede in slow motion. The accelerating thumping of his own pulse drowned out all other sound in his ears.
</p>
<p>
He propelled himself away from the door, holding onto his unwieldy weapon over his shoulder and letting its mass swing down along his back. He only needed to take seven or eight sprinting steps to make it to an intersection in the hallway, but in those steps he felt like he was frozen in mid-air. A bullet zinged past him &mdash; Danny saw nothing, but felt the air crack against his skin in the projectile’s wake. He twisted his torso to expose only his side, rather than his back, to the gunfire. Another bullet zoomed by, so close he could feel its heat against his back, across his left shoulder blade.
</p>
<p>
The adjoining corridor drew nearer. He leaped and rolled into the hallway, his weapon smacking against the floor as he pushed his body away from the line of fire. A bullet hit the floor near his feet. He took several crouching, stumbling steps deeper into the hallway as another bullet hit the wall near him, leaving a dusty crater. 
</p>
<p>
He looked around. He was out of the line of fire. From around the bend, he could hear the man trapped in the stockroom banging against the door and cursing in Russian. The bullets had stopped. 
</p>
<p>
But he was still in danger.
</p>
<p>
On the other end of the dark hallway into which he had just fled, Danny saw the shape of a large man. The shape was coming toward him.
</p>
<p>
He pushed himself back up from the floor. His left shoulder stung under the strain. 
</p>
<p>
He grabbed his weapon. Most of the machine’s mass was at its back end, where its eight-pack of blue ultracapacitors was attached. Danny held it in both hands and raised it like a sledgehammer, ready to smash the capacitor bank across the face of his approaching attacker. He let out a mighty yell, and threw himself at the figure in the dark.
</p>
<p>
Somewhere underneath the din of his heartbeat and his own battle-cry, he heard Mike’s voice yell, “Danny!” The voice didn’t come through a cellphone, but from the figure in front of him. 
</p>
<p>
Danny stopped in mid-lunge as recognition came to him through his combat panic.
</p>
<p>
“Mike!” Danny said with a relieved smile. He exhaled deeply. “Holy shit, I am so fucking happy to see you right now.” His head swirled as the adrenaline rush faded away. He was safe. 
</p>
<p>
 Danny retrieved his cellphone from the hallway floor. His gun was a little banged up &mdash; the power converter had gotten slightly dented and the row of relays had come loose from their Velcro moorings &mdash; but there didn’t seem to be any functional damage.
</p>
<p>
On the conference call, Jason asked, “Are you guys okay?”
</p>
<p>
“Yeah,” Danny said, dizzy. “I think I landed wrong on my shoulder. Stings a little.” He rolled his left arm around. “Seems to be okay though. No time to rest; we’ve got to get to that freezer room. This next part’s going to be tricky…”
</p>
<p>
“I was thinking about that, Danny,” said Jason. “You might want to grab a lab coat, if you see one around. And a facemask. That way, you’ll &mdash;” 
</p>
<p>
His words were muffled by a low, thundering boom that resounded through the building. The echoes of a distant explosion rumbled down Tungsten’s corridors, permeating the walls and flooding the rooms like a thick clear syrup of long, wide sound waves.
</p>
<p>
“Camera crew!” Danny gasped. “What the hell was that?”
</p>
<p>
Moshen replied slowly, “That was the other guy’s gun.”
</p>
<p>
“The one that’s pointed at the girl?” Danny asked with renewed panic.
</p>
<p>
“She tried to fight back,” Moshen replied.
</p>
<p>
Danny gasped. “Is she…”
</p>
<p>
“Get your butts over there fast,” Moshen directed.
</p>
<p>
Danny gulped, and exchanged a nod of affirmation with Mike. The two men set off down the hallway.
</p>
<p>
The fingers of Danny’s left hand very subtly twitched, subconsciously reaching for Control-S on a nonexistent keyboard. As Danny proceeded with Mike through the dim corridors, he caught himself glancing into rooms craving the sight of a prominently placed typewriter like in <em>Resident Evil</em>, or a pink audiocassette like in <em>Grand Theft Auto: Vice City</em>, or perhaps just a glowing red square like in <em>Silent Hill 2</em>. But he knew that, on this level, he would find no save-points.
</p>
<p>
</div>