<div class="chapsection">
<p>
<span class="caplead">The black Lincoln Navigator</span> wound languidly around Tungsten’s parking lot in an awkward, snaking path. The man standing by the door studied it apprehensively, and said something into his Bluetooth headset.
</p>
<p>
The car came to a stop near the entrance. The driver-side window rolled down, revealing a middle-aged man with gelled gray hair.
</p>
<p>
Jason’s head drooped, his mouth hanging open and eyes unfocused. He inquired in a slow, raspy whisper, “Is this the Weisenbaum Clinic? I see the big ‘W’ on the door…”
</p>
<p>
“No,” the man barked. “Go away.”
</p>
<p>
“Please, it’s very important,” Jason said, drawing out and enunciating each word. “I have an urgent medical condition. I need to go see…” His speech degenerated into a series of wheezes and coughs. “Can… Can you come closer please? It hurts for me to talk so loud.”
</p>
<p>
With an exasperated sigh, the man took a few steps toward the SUV.
</p>
<p>
“I know the phone number to the clinic,” Jason whispered breathily, “but my telephone is broken. Maybe you can make a call for me?”
</p>
<p>
The man glared at him. “If I do, will you go away?”
</p>
<p>
“Yes.”
</p>
<p>
The man said something in Russian into his headset, his tone of annoyance crossing the language barrier. He pulled out his cellphone. “Okay, give me the number.”
</p>
<p>
“Four two five,” Jason said slowly, “Eight six five… Eight six five two? No, wait, eight six five three…”
</p>
<p>
“Eight six five eight six five two?” said the man, dialing the sequence.
</p>
<p>
“No, eight six five is just the first part. I was just repeating it to make sure you got it. Four two five, eight six five… Four two… Oh, you know what? I’m sorry. That’s my daughter’s number. The one to the clinic is four two five, eight five three… Wait, eight five or eight six…?”
</p>
<p>
The man growled. 
</p>
<p>
Focused on trying to dial Jason’s number, he couldn’t notice the green light pop on above the keycard reader behind him. Nor could he notice Mike tiptoe along the wall, spidering toward the entrance.
</p>
<p>
Until Mike finally ducked through the big glass door. As Mike’s body slid into the light pouring from the lobby, his shadow swept across the parking lot.
</p>
<p>
Danny cursed silently. He should’ve anticipated that. He hadn’t.
</p>
<p>
“What the fuck!” the man said. He turned his head just in time to see Mike heading into the hallway.
</p>
<p>
That’s when the man’s cellphone exploded.
</p>
<p>
The phone jumped in his hand with a loud “<em>crack!</em>” A shower of white sparks burst somewhere within, spilling out from the sides and from the seams around the buttons. Arcs of electricity flashed across its face. The man yelped, dropping it to the ground.
</p>
<p>
Jason slammed on the gas. The SUV’s tires squealed on the pavement. He steered a zigzagging pattern back out to the street.
</p>
<p>
The man’s head swiveled from the building to the car. He let his jacket fall to the ground and drew the silenced semiautomatic up to shoulder height. He held the gun with both hands, took aim, and pulled the trigger several times. The gun didn’t make a “<em>bang!</em>” It did, however, make a distinct popping noise, together with the loud “<em>clack!</em>” of spring-loaded metal parts snapping into place.
</p>
<p>
“<em>Fuck!</em>” screamed Jason into the hands-free conference call in progress on his cellphone. A bullet glanced off of the rear driver’s side window, leaving a scar in the glass, just as Jason cleared the parking lot. The car lurched as he made a sharp turn onto the street, bolting away from the building.
</p>
<p>
Having lost Jason’s SUV, the man turned toward the Tungsten entrance. He thrust his hip toward the card-reader. The green light popped on.
</p>
<p>
“He’s heading in,” warned Moshen on the conference call.
</p>
<p>
Danny crouched behind the corner of the Tungsten building, out of sight from the entrance. Beside him, his contraption whined faintly with a rising high-pitched tone, its tiny lights glowing red. His phone was pressed to his face. “Mike, he’s coming for you. Make sure he follows you to the stockroom. Moshen, keep him safe.”
</p>
<p>
“Aye aye,” said Moshen. “Mike, I’ve got the guy on camera. He’s in a hallway about fifty feet behind you.”
</p>
<p>
Mike’s voice asked, “How do I get to the stockroom from here?”
</p>
<p>
“End of the hall,” Moshen directed. “Make a left…”
</p>
<p>
On the conference call, Danny heard Mike running through Tungsten’s hallways. Moshen guided him, always keeping him one turn ahead of his pursuer. A distant <em>pop-clack!</em> occasionally punctuated the dialog.
</p>
<p>
“Now, Mike, remember,” said Danny. “There’s a keycard scanner on the outside of the door to the stockroom. So once you get into the stockroom, you can’t get back into the Tungsten offices without a keycard. The only way out of that stockroom is through the fire door near the loading dock.”
</p>
<p>
Moshen added, “He’s walking slowly down the hall toward you with his gun drawn. Stay out of sight, Mike.”
</p>
<p>
The conference call carried the sound of a door opening. “I’m in the stockroom,” said Mike. 
</p>
<p>
Danny caught himself biting his fingernails. “Jason. Come back here and get to the loading dock. Quickly. Where are you?”
</p>
<p>
“Down the street,” Jason’s voice tinned. “There’s bullet holes in my car. The repairs are coming out of your pay.” 
</p>
<p>
“Mike!” Moshen announced. “He’s at the stockroom door!”
</p>
<p>
Danny saw headlights on the road beyond the parking lot. Jason’s SUV proceeded back towards the Tungsten building. “Jason’s not in position yet,” he said into the cellphone. “Mike, can you keep the guy busy?”
</p>
<p>
Danny heard Mike grunting and straining. The sound was followed by a few popping, clacking shots from the handgun.
</p>
<p>
“Mike! <em>Mike!</em>” yelled Danny. “Are you alright? What’s happening?”
</p>
<p>
Moshen’s voice came across the call. “He looks fine. He tried to push over one of the shelves of inventory. The guy busted in on him and opened fire, but he managed to duck behind some old junk. He’s hiding behind an X-ray machine or something.”
</p>
<p>
“What’s the guy doing?” Danny asked.
</p>
<p>
Moshen answered, “He’s crouched and ready, both hands on his gun, about thirty feet from Mike &mdash; it looks like he doesn’t know where he is. But he’s searching.”
</p>
<p>
Danny cursed under his breath. “Guys, I’m going in. Moshen, the front door, please.”
</p>
<p>
The green light popped on above the card reader. Danny entered the building and hustled down the corridors, keeping his cellphone to his ear while carrying his contraption. Moshen’s voice guided him through the dark, unfamiliar office hallways, past strange apparatuses and doors marked with ominous warnings and hazard symbols.
</p>
<p>
Jason’s voice came across the air. “I’m in position, Danny.”
</p>
<p>
Moshen said, “Mike’s pinned down. If he moves, he’ll get shot.”
</p>
<p>
Danny arrived at the hallway outside the stockroom. Before him was a metal door. It bore a small glass window, no bigger than a person’s face. The stockroom’s emergency lights made the square of glass emit a faint sickly yellow shine at the end of the dim hallway. The wall beside the door held a glowing green button attached to a thin electrical conduit that ran up to the ceiling. The conduit split off and connected to a block that pressed up against a silvery rectangle &mdash; the armature plate of a standard magnetic lock system.
</p>
<p>
Mike whispered into the call, “Moshen. You said he’s about thirty feet away from me toward the entrance, right?”
</p>
<p>
“Yeah,” said Moshen.
</p>
<p>
“Mike, I’m right outside,” Danny said into the cellphone. “What are you doing?”
</p>
<p>
“I’m gonna throw this thing at him,” Mike said quietly.
</p>
<p>
“What thing?” asked Danny.
</p>
<p>
“I’m not sure,” said Mike. “It looks kind of like an old computer, but it’s all round and purple and says ‘SGI O2+’ on the front.”
</p>
<p>
“Dude!” said Danny. “In the late ‘90s, that thing used to be the most popular 3D rendering workstation on the consumer market!”
</p>
<p>
“Yeah well,” said Mike, “let’s see if it makes a good projectile weapon.”
</p>
<p>
Danny heard Mike give a mighty grunt, followed by a crashing noise and the “<em>pop-clack!</em>” of the semiautomatic. On the far side of the stockroom, Mike body-checked his way through the emergency exit. 
</p>
<p>
Jason’s voice announced, “Mike, you’re okay!”
</p>
<p>
“<em>Punch it!</em>” yelled Mike.
</p>
<p>
A thud sounded through the cellphone as Jason backed his SUV up against the fire exit. Jason had positioned his car about three feet from the door, waiting to see Mike run out. The moment Mike cleared the exit, Jason slammed the back of his car against it. The fire door opened outward, so the SUV served as an enormous doorstop.
</p>
<p>
“Good job, Mike,” said Danny. “Now go around the outside of the building, get back in through the front doors, and come back here.”
</p>
<p>
From inside the stockroom, Danny could hear the man throwing himself against the fire exit in a useless attempt to push away the SUV. The “<em>pop-clack!</em>” of the gun sounded a few times, then silence.
</p>
<p>
Danny waited in the dim hallway outside the stockroom door. “Is he coming back this way yet, Moshen? As soon as he realizes the fire exit’s blocked, he’s going to try to get out the way he came. But he’ll need to use his keycard to open the door from that side.”
</p>
<p>
“Not yet,” Moshen assured. “Good news is you have an extra second or two. Bad news is, that’s because he’s reloading.”
</p>
<p>
Danny took a deep breath. He put the end of his device up against the wall, just under the button that would unlock the hefty metal stockroom door. The wall, he reckoned, was made of six inches’ worth of drywall, wood, and foam insulation &mdash; all of which was essentially transparent to microwaves. “Moshen, watch him close. Tell me the exact moment he’s about to swipe that keycard.” He listened for movement on the other side.
</p>
<p>
“<em>Now!</em>” yelled Moshen.
</p>
<p>
Danny pulled the trigger. Current discharged from the capacitor bank to the magnetron, sending a soft, low-pitched “<em>bonk!</em>” through the air around it. Lights flipped from green to red.
</p>
<p>
On the other side of the wall, Danny heard a snapping sound, followed by a man screaming in shocked frustration and unleashing a long stream of Russian curse words. The man pulled in vain at the door handle on the other side. The door shook slightly but refused to yield. 
</p>
<p>
Danny held his device triumphantly over his shoulder. Its fans whirred to cool it from its recent shot. The capacitor bank began to recharge, emitting its characteristic rising whine.
</p>
<p>
A round shadow eclipsed the jaundiced glow of the small window embedded in the door. In the dim light, Danny could just make out the man’s face, looking murderously at him through the glass. The man’s cursing fell silent. He simply stared at Danny in impotent rage.
</p>
<p>
Danny gave him a smug shrug, waved goodbye, and turned around to saunter away.
</p>
<p>
He had barely made it two steps when he heard a “<em>pop-clack!</em>”, coupled with the sound of shattering glass.
</p>
<p>
Danny turned to look.
</p>
<p>
All that remained of the small square window was a few jagged shards. The man drew his gun up. The end of the silencer came to rest upon a crag of broken glass. He looked down the sights and took aim.
</p>
<p>
Danny’s world began receding in slow motion. His ears heard nothing but the deafening thunder of his own accelerating pulse.
</p>
<p>
He propelled himself away from the door with all the power his legs could offer. He only needed to take seven or eight sprinting steps to make it to an intersection in the hallway, but in those steps he felt like he was frozen in mid-air. A bullet zinged past him &mdash; Danny saw nothing, but felt the air crack against his skin in the projectile’s wake. He twisted his torso to expose only his side to the gunfire. Another bullet zoomed by, so close he could feel its heat against his back, across his left shoulder blade.
</p>
<p>
The adjoining corridor drew nearer. He leaped and rolled into the hallway, his weapon smacking against the floor as he pushed himself away from the line of fire. A bullet smacked the floor near his feet. He took several crouching, stumbling steps deeper into the hallway as another bullet hit the wall near him, leaving a dusty crater. 
</p>
<p>
He looked around. He was out of the line of fire. From around the bend, he could hear the man trapped in the stockroom banging against the door and cursing in Russian. The bullets had stopped. 
</p>
<p>
But he was still in danger.
</p>
<p>
On the other end of the dark hall, Danny saw the shape of a large man. It was approaching quickly.
</p>
<p>
He pushed himself back up from the floor. His left shoulder stung under the strain. 
</p>
<p>
He grabbed his weapon. Most of the machine’s mass was at its back end, where its eight-pack of blue ultracapacitors was attached. Danny held it in both hands and raised it like a sledgehammer, ready to smash the capacitor bank across the face of his attacker. Roaring, he threw himself at the figure in the dark.
</p>
<p>
Somewhere underneath the din of his heartbeat and his own battle-cry, he heard Mike’s voice yell, “Danny!” The voice didn’t come through a cellphone, but from the figure in front of him. 
</p>
<p>
Danny stopped in mid-lunge as shards of recognition jangled through his combat panic.
</p>
<p>
“Mike!” Danny said, so relieved he almost started laughing. “I am so fucking happy to see you right now.” His head swirled as the adrenaline subsided. He was safe. 
</p>
<p>
Danny retrieved his cellphone from the hallway floor. His gun was a little banged up &mdash; the power converter had gotten dented, and the row of relays had come loose from their Velcro moorings &mdash; but there didn’t seem to be any functional damage.
</p>
<p>
On the conference call, Jason asked, “Are you guys okay?”
</p>
<p>
“Yeah,” Danny said, dizzy. “I think I landed wrong on my shoulder. Stings a little.” He rolled his left arm around. “Seems to be okay, though. No time to rest &mdash; we’ve got to get to that freezer room. This next part’s going to be tricky…”
</p>
<p>
“I was thinking about that, Danny,” said Jason. “You might want to grab a lab coat, if you see one. And a facemask. That way, you’ll&mdash;” 
</p>
<p>
His words were muffled by a low, thundering boom that resounded through the building. The echoes of a distant explosion rumbled down Tungsten’s corridors, permeating the walls and flooding the rooms like a thick clear syrup of sound.
</p>
<p>
“What the hell was that?” asked Danny.
</p>
<p>
Moshen replied, “That was the other guy’s gun.”
</p>
<p>
“The one that’s pointed at the girl?” Danny pressed with renewed panic.
</p>
<p>
“She tried to fight back,” Moshen replied.
</p>
<p>
Danny gasped. “Is she…”
</p>
<p>
“Get your butts over there,” Moshen directed.
</p>
<p>
Danny gulped, and exchanged a nod with Mike.
</p>
<p>
As the pair began negotiating the dim corridors, Danny’s fingers twitched, subconsciously reaching for Control-S on a nonexistent keyboard. He caught himself glancing into rooms, craving the sight of a prominently placed typewriter like in <em>Resident Evil</em>, or a pink audiocassette like in <em>Grand Theft Auto: Vice City</em>, or perhaps just a glowing red square like in <em>Silent Hill 2</em>.
</p>
<p>
But he knew that, on this level, he would find no save-points.
</p>
</div>