<div class="chapsection">
<p>
<span class="caplead">“I n-need you b-be more s-piffic,”</span> Tina said through a shivering jaw as she closed the massive metal door yet again. Inside the ultra low freezer were half a dozen rack shelves. On each shelf were a dozen long, deep cases made of metal and Styrofoam, built to slide out like drawers. Inside each case were two dozen vials, each no bigger than a finger. And one of these vials was the one that the man with the gun wanted.
</p>
<p>
He sat on a desk between her and the exit. “I already told you. It’s a small clear plastic snap-top tube with cone-shaped bottom.” He kept his revolver pointed at her absentmindedly, his attention divided between her and his cellphone.
</p>
<p>
“You just described <em>every</em> vial in there,” she said. She breathed into the thick black acrylic gloves that protected her fingers from frostbite.
</p>
<p>
Ignoring her, the man tapped his Bluetooth headset. “<em>Allyo? Allyo, Leonya? Gdye ti, durak?</em>”
</p>
<p>
“Is everything okay?” she asked.
</p>
<p>
“My partner isn’t…” he started, then cut himself off. “Isn’t your business. Where is that fucking tube?”
</p>
<p>
“I have no idea,” Tina said. “Look, all these vials look exactly the same. How did you expect to know which one’s the right one?”
</p>
<p>
While still poking at his phone, he replied, “There is sticker on the side.”
</p>
<p>
“They <em>all</em> have a sticker on the side,” she insisted. “That’s how they’re labeled.”
</p>
<p>
“Is your problem now,” the man said as he fiddled with his cellphone. “Figure it out.”
</p>
<p>
On a metal table in the center of the room stood a case from the deep-freezer. Its hinged top gaped open, revealing a grid of empty circular holes in a Styrofoam interior. Beside the case lay a series of snap-top test tubes, their caps rimmed with frost. Within their translucent walls was a pasty yellowish-brown goop in varying states of thaw. Each tube bore a rectangular white label along its side, with handwritten letters and numbers to indicate sample identifiers.
</p>
<p>
“I don’t know what you want me to do!” Tina pleaded. “Look, I’m just the receptionist, okay? Tungsten does <em>not</em> pay me enough for this. How about I just walk out of here, I’ll get my purse from the front, I’ll drive away, go home, and we’ll both say none of this ever happened? I’m not going to call the cops, I’m not going to remember your face, I’m not going to have any idea about you or Julie or about anything. Okay? Please, I swear to God, I want nothing to do with this.” 
</p>
<p>
Suddenly, the man looked up from his phone with a furious glare. “Be useful!” he growled. “You know what happens if you are not useful?”
</p>
<p>
Tina shivered, but not from the cold.
</p>
<p>
She turned to the table with resignation. One by one, she picked the tiny vials up in her acrylic-gloved hands and put them back into the case, taking care to slide each one into the exact little round Styrofoam hole from whence it came. When the last of the two dozen vials had been returned, she sealed the case’s metal lid and picked it up in one hand by a carrying strap. With her other hand, she grabbed the lever-like handle of the cryogenic storage unit. The freezer was attached to a monitoring terminal, a small ancient dirty beige computer with a thick clunky keyboard, which kept track of the environment inside the freezer. “<span class="computer">TEMPERATURE: 200.7K -72.4oC -98.3oF</span>”, its screen reported in blocky green letters. Tina winced.
</p>
<p>
“Can I at least borrow your jacket?” she asked.
</p>
<p>
“My jacket? Lady, this is Italian custom-made lambskin leather.”
</p>
<p>
Her body began preemptively shivering. A yank of the handle released the cryogenic storage unit’s seal, and she again found herself standing in a pale cloud of stabbing cold mist. The freezer’s loud pumps whirred to keep the interior frigid in spite of the open door, and the monitoring terminal’s readout fluctuated. Working as quickly as her shaking body would allow, Tina slid the case in her hands back into its place upon the freezer’s rime-coated racks. She then grabbed the strap of the next identical case on the shelf, pulled it out, and slammed the freezer door shut.
</p>
<p>
Back at the metal table, she popped open the lid of the new case and began pulling out vials, struggling to catch the lip of each snap-top tube with the fingertips of the acrylic glove. She examined each label carefully before laying the vial on the table in a neat row matching its position in the case. The labels all bore some researcher’s initials, a date, a batch number, and similar identifiers. She could find no pattern among them, and nothing distinct about any particular one.
</p>
<p>
The man watched her stack the tubes into precise organized lines on the table. With a squint, he asked, “This will help you find the one I want?”
</p>
<p>
“What? No, it’s…” Tina stammered as she tried to multitask between arranging the tubes and talking to her captor. “Everything in the fridge is organized by location. If I put these back out of order, I’ll ruin all the scientists’ projects.”
</p>
<p>
The man shrugged dismissively. “Who cares about putting back?”
</p>
<p>
“What do you mean?” Tina asked, bewildered, as she worked. I have to put them back or else they’ll die. The brown stuff in the vials is bacteria frozen in glycerol. They’re living things. They can’t live in the suspension. The glycerol protects them from ice when they get frozen, but they need water and food. If they come out of suspended animation in the glycerol, they’ll…”
</p>
<p>
She glanced up at him for a moment. She looked back and forth between the freezer, her precise little row of test tubes, and his gun.
</p>
<p>
“You know what?” she said. “Fuck it.”
</p>
<p>
She stepped toward the cryogenic storage unit, but didn’t touch the door. Instead, she slid her body against the side of the machine’s massive bulk, toward the wall. Behind the freezer, where chill gave way to heat as the compressor pushed thermal energy uphill against its natural gradient, a thick black cable ran to a heavy power plug. Tina reached down behind the machine, welcoming the warm air from the condenser fans blasting up her arm, and grabbed the plug. It took a hard yank to dislodge it from its wall socket. The moment it came loose, the refrigeration machinery fell silent.
</p>
<p>
Back near the door, the screen of the monitoring terminal lit up in a panicking flurry of bright green all-caps warning messages. Tina grabbed the freezer’s door handle one last time and pulled it wide open, letting the unit’s cold air spill freely out into the room. She stood back far enough to avoid the draft, and silently watched the terminal as its temperature readout climbed.
</p>
<p>
It wasn’t long before the cases could be comfortably touched with bare hands. She grabbed them two at a time, pulled them from their slippery racks, and set them on the table. Melting frost dripped down their sides to form small puddles on the tabletop. She opened their lids and pulled out vial after vial, giving each label a quick examination before tossing it down into a discard pile.
</p>
<p>
There was one vial that bore visibly less frost on its cap than the others &mdash; it had clearly been withdrawn from its box often. When Tina drew it out, she knew immediately that it was the one that the Russian had come for. Like all the others, it was less than two inches long with a conical bottom, filled with a pale brown substance that looked frozen solid. But in place of a label, it bore a tattered yellow smiley face sticker affixed on its translucent round surface.
</p>
<p>
The Russian perked up as he saw her place the tube down on the table.
</p>
<p>
“Here. Take it,” she said.
</p>
<p>
The Russian eagerly stepped forward. He slid his cellphone into his jacket pocket and picked up the tube with the tips of his fingers. 
</p>
<p>
“Are we done here?” Tina asked.
</p>
<p>
The man held the vial up in front of his face, examining it with delight. His grin echoed the smile on the round yellow sticker. “Yes. I think we are.”
</p>
<p>
“Good,” she said. “Goodbye.” And she made a bee-line for the door.
</p>
<p>
She didn’t make. A cold leather-gloved hand clamped firmly around her wrist and jerked her back. 
</p>
<p>
“No!” she shouted.
</p>
<p>
“Not so fast, young lady.”
</p>
<p>
“What!” she protested. “What do you want! Let me go!”
</p>
<p>
“You’re really quite useful, you know,” he said.
</p>
<p>
“You said we’re done here!” She tried to pull her hand back, to no avail. He held her wrist firmly with his left hand, with both his gun and the vial in his right.
</p>
<p>
“We are done <em>here</em>,” repeated the man. “But… I have more use for you…”
</p>
<p>
Tina felt her stomach lurch. “Fuck you, <em>no</em>!” she screamed, and fought against his grip with all her might. But he was far too strong. 
</p>
<p>
He yanked her back into the room and released her, letting her momentum carry her a few stumbling steps away from him. He once again stood between her and the door.
</p>
<p>
“Relax,” he said in a commanding tone. “Do not assume things. I’ve done this before &mdash; I know what you are worrying about. But lady, I am a professional. I don’t mix business with pleasure. Besides, I get hotter pieces of ass than you any time I want. Your body is of no interest to me.”
</p>
<p>
Tina stared at him silently. She felt both slightly relieved and incredibly insulted at the same time.
</p>
<p>
“You are proving handy to have around,” he said. “Besides…” He gestured with the vial. “I need to make sure you did not pull any funny business with this tube. I need the stuff in here to come out alive. And that means you need to give me… insurance.”
</p>
<p>
Tina gulped quietly.
</p>
<p>
“So, here is a plan,” he continued. “We take you back to our factory. Your little friend is there &mdash; she will be happy to see you. We will keep you until we finish a good batch and see that everything works. It should only take a few days. You will be treated well. Nobody will hurt you. And when you get success, we will let you go.”
</p>
<p>
“You have got to be kidding me,” Tina said.
</p>
<p>
“Stop arguing already! Cooperate and things will go well for you. We are businessmen, not animals. Now come on!” He waved the gun at her. “This is happening. Let’s go.”
</p>
<p>
Tina stood frozen in place. She could feel her pulse in her neck.
</p>
<p>
“Get moving! Go go go!” he ordered.
</p>
<p>
The sound of his voice began to recede, like she was hearing it underwater. She felt her skin crawl as goosebumps rose. She looked furtively around the room.
</p>
<p>
A few feet away from her was the old dirty beige freezer monitoring terminal with the green screen and the big heavy keyboard. It was still flashing silent distress about the freezer’s temperature.
</p>
<p>
“Okay. I’ll do it,” she said, her own voice sounding oddly distant and flat. 
</p>
<p>
“Good girl,” he said. “Now let’s go already.”
</p>
<p>
“I need to check the environmental settings for the cold storage unit here,” she said, nodding her head toward the terminal. “When we get the tube back to your factory, I’ll need to store it somewhere with the exact same temperature, pressure, and humidity levels.”
</p>
<p>
He grinned again. “See! You’re being useful already!”
</p>
<p>
She stepped slowly toward the terminal, laid her hands upon the keyboard, and made a few meaningless keystrokes. The large, clunky keys made loud <em>ka-chunk!</em> sounds beneath her fingers.
</p>
<p>
“My colleagues and I will show our appreciation of you being so helpful,” the man said to her. “If you continue to be so diligent, you will be rewarded.”
</p>
<p>
She squinted at the screen and leaned her face very close to the monitor. “Damn it,” she said slowly.
</p>
<p>
“Is everything alright?” he asked her.
</p>
<p>
“This isn’t making any sense,” she said. “Come here, can you take a look at this?”
</p>
<p>
He stepped toward the terminal and stood right behind her.
</p>
<p>
She glanced over her shoulder. He was still holding both the vial and the revolver in the same hand. That meant his grip on both was probably weak.
</p>
<p>
She put her hands on either side of the keyboard and leaned her head to the left, encouraging him to look over her right shoulder. She curled her fingers underneath the keyboard’s edges.
</p>
<p>
“See where it says ‘Temperature’?” she asked.
</p>
<p>
“Yes…” he said, leaning his face forward toward the screen.
</p>
<p>
In a swift upward jerking motion, Tina swung the keyboard over her shoulder and smashed it against his face.
</p>
<p>
She let go of the keyboard, which fell away with a clatter, and reached for his hand. Her palm made contact with the butt of the revolver. She grabbed it and pushed the barrel upward and away from her. She worked her fingers in between his hand and the gun. 
</p>
<p>
The vial fell out of his hand. She could hear it rolling in a small circle on the linoleum.
</p>
<p>
The revolver twisted in his grasp but wouldn’t yield. Her index finger landed inside the trigger guard.
</p>
<p>
She realized that, even if she couldn’t take the gun from him, she could at least empty it. Guns only hold so many bullets. And without the threat of being shot, she might be able to make a run for it. She pulled the trigger.
</p>
<p>
The sound was not just deafening. It was so loud it was blinding.
</p>
<p>
Tina felt a hot shock wave blast across her face and jostle her hair. Her nostrils filled with the sharp, earthy odor of gunpowder. For a nearly imperceptible moment her vision registered a foot-long arc of black and orange flame erupt from the barrel.
</p>
<p>
The revolver kicked outward and upward. The man’s arm, retaining the gun, flew back and up above his shoulder, pulling away from Tina’s grasp. Grainy white dust sprinkled from the wall that the gun had been pointed at. There was a hole in the drywall, near the ceiling. It was the size of a man’s fist.
</p>
<p>
For a split second, she was too disoriented to move. The shock of the explosion left her paralyzed with bewilderment, seeing nothing but the hole in the wall and hearing nothing but the ringing in her own ears. On an instinctive level, she felt like she had to make sure she could at least still breathe before doing anything else.
</p>
<p>
And suddenly she couldn’t.
</p>
<p>
While she had been dazed by the blast, the Russian had regained control of the weapon. He hadn’t shot her with it. Instead, he slammed the butt of the revolver high into her abdomen, just below her sternum.
</p>
<p>
She grabbed her chest with both hands, gasping desperately for air, writhing and twisting her body, trying hopelessly to get her breathing to work again. She heaved her shoulders up and down to get a shallow current of oxygen into her quickly acidifying bloodstream. Her clenching throat emitted an unnatural, high-pitched wheezing sound with every inhale.
</p>
<p>
After several terrifying seconds, she felt her breath gradually return.
</p>
<p>
“Stupid fucking bitch,” grumbled the Russian, angry but collected. He touched two gloved fingers to his mouth and examined them. His lower lip was bleeding where Tina had busted it open with the keyboard. He slowly knelt down and retrieved the vial from the floor, keeping the gun trained on her with renewed mindfulness. “You try something like that again, I hurt you in ways that take longer to heal. Understand?”
</p>
<p>
Tina’s mind spun with anger, fear, and self-pity. Under the command of the man with the gun, with nausea welling up in her throat, she began to march toward the door.
</p>
<p>
It was then that the Russian, with a startled expression, suddenly turned his head toward the hallway. He quickly and quietly motioned with his hand for her to stop moving.
</p>
<p>
Tina halted in her tracks. “What now?” she demanded.
</p>
<p>
“Shhhhh!” said the Russian.
</p>
<p>
Tina could just barely make out a man’s voice from far down the hallway. Both Tina and the Russian stood frozen. The man’s voice drew closer.
</p>
<p>
“Negative, Dispatch,” said the man’s voice. “No signs of engagement. Breach signals are rising. Proceeding further into Sector G.”
</p>
<p>
The Russian stared at the doorway with a look of fear and disgust. “What the fuck is this shit?” he mumbled slowly.
</p>
<p>
“Dispatch, I’m seeing illumination from the cryogenic storage facility room area,” the unseen man said loudly. “Radiometric breach waves are continuing to increase. I’ll head toward the cryogenic area. Approaching now.”
</p>
<p>
The Russian turned to Tina with eyes wide, his expression angrily demanding answers. Tina, just as confused, shrugged with upturned palms.
</p>
<p>
The Russian closed his fist around the tube in his left hand, hiding it in his black leather glove. He tucked his revolver into his jacket pocket. “Don’t move,” he said to her.
</p>
<p>
He then stepped out into the hallway, and as he closed the door, he said, “Who the fuck are you?”
</p>
</div>