<div class="chapsection">
<p>
<span class="caplead">“I n-need you b-be more s-piffic,”</span> Tina stammered through her shivering jaw as she closed the massive metal door yet again. Inside the ultra-low freezer were half a dozen rack shelves. Each shelf held a dozen lunchbox-shaped cases made of metal and Styrofoam. Inside each case were two dozen vials, each no bigger than a finger. And one of these vials was the one that the man with the gun wanted.
</p>
<p>
He sat on a desk between her and the exit. “I already told you: small, clear plastic snap-top tube with cone-shaped bottom.” He absentmindedly kept his revolver pointed at her, his attention divided between her and his phone.
</p>
<p>
“You just described <em>every</em> vial in there.” She blew into the thick black acrylic gloves that protected her fingers from frostbite.
</p>
<p>
Ignoring her, the man tapped his Bluetooth headset. “<em>Allyo? Allyo, Leonya? Gdye ti, durak?</em>”
</p>
<p>
“Is everything okay?” she asked.
</p>
<p>
“My partner isn’t…” he started, then cut himself off. “Isn’t your business. Where is that fucking tube?”
</p>
<p>
“I have no idea,” Tina said. “All these vials look exactly the same. How did you expect to know which one’s the right one?”
</p>
<p>
Still jabbing at his phone, he replied, “There is sticker on the side.”
</p>
<p>
“They <em>all</em> have a sticker on the side,” she insisted. “That’s how they’re labeled.”
</p>
<p>
“Is your problem now. Figure it out.”
</p>
<p>
On a metal table in the center of the room stood a case from the deep-freezer. Its hinged top gaped open, revealing a grid of empty circular holes in a Styrofoam interior. Beside the case lay a series of snap-top test tubes, their caps rimmed with frost. Their translucent walls revealed a pasty yellowish-brown goop. Each tube bore a rectangular white label along its side, with handwritten identifiers.
</p>
<p>
“I don’t know what you want me to do!” Tina pleaded. “Look, I’m just the receptionist, okay? Tungsten does <em>not</em> pay me enough for this. How about I just walk out of here, get my purse from my desk, drive off, and we’ll both say none of this ever happened? I won’t call the cops, or remember your face. Okay? Please, I swear to God, I want nothing to do with this.” 
</p>
<p>
The man looked up from his phone, glaring. “Be useful!” he growled. “You know what happens if you are not useful?”
</p>
<p>
Tina shivered, but not from the cold.
</p>
<p>
She turned to the table with resignation. One by one, she picked up the tiny vials and put them back into the case, taking care to slide each one into the exact little round Styrofoam hole from whence it came. When the last of the two dozen vials had been returned, she sealed the case’s metal lid and lifted it in one hand by a carrying strap. With her other, she grabbed the lever-like handle of the cryogenic storage unit. The freezer was attached to a monitoring terminal, an ancient dirty beige computer with a thick clunky keyboard, which kept track of the environment inside the freezer. “<span class="computer">TEMPERATURE: 200.7K -72.4oC -98.3oF</span>”, its screen reported in blocky green letters. Tina winced.
</p>
<p>
“Can I at least borrow your jacket?” she asked.
</p>
<p>
“My jacket? Lady, this is Italian custom-made lambskin leather.”
</p>
<p>
Her body shivered preemptively. A yank of the handle released the cryogenic storage unit’s seal, and she again found herself standing in a pale cloud of stabbing cold mist. The freezer’s loud pumps whirred to keep the interior frigid in spite of the open door, and the monitoring terminal’s readout fluctuated. Working as quickly as her shaking body would allow, Tina slid the case back into its place upon the freezer’s rime-coated racks. She then grabbed the strap of the next identical case on the shelf, pulled it out, and slammed the freezer door shut.
</p>
<p>
Back at the metal table, she popped open the lid of the new case and began pulling out vials, struggling to catch the lip of each snap-top tube with the fingertips of the glove. She examined each label carefully before laying the vials on the table in a neat row matching its position in the case. The labels all bore some researcher’s initials, a date, a batch number, and similar figures. She could find no pattern among them, and nothing distinct about any of them.
</p>
<p>
The man watched her stack the tubes into precise organized lines on the table. With a squint, he asked, “This will help you find what I want?”
</p>
<p>
“What? No, it’s…” Tina stammered as she tried to multitask between arranging the tubes and talking to her captor. “Everything in the fridge is organized by location. If I put these back out of order, I’ll ruin all the scientists’ projects.”
</p>
<p>
The man shrugged dismissively. “Why put back at all?”
</p>
<p>
“What? I <em>have</em> to put them back or else they’ll die,” Tina insisted. “The brown stuff in the vials is bacteria frozen in glycerol. They’re living things. They can’t live in the suspension. The glycerol protects them from ice when they’re frozen, but they need water and food. If they come out of suspended animation in the glycerol, they’ll…”
</p>
<p>
She looked back and forth between the freezer, her precise little row of test tubes, and his gun.
</p>
<p>
“You know what?” she said. “Fuck it.”
</p>
<p>
She stepped toward the cryogenic storage unit, but didn’t touch the door. Instead, she slid her body against the side of the machine’s massive bulk, toward the wall. Behind the freezer, beneath the thrumming compressor pumps and condenser coils, a thick black cable snaked to a heavy power plug. Tina reached down behind the machine, welcoming the warm air blowing from the condenser fans, and grabbed it. With a yank, she dislodged the plug from its wall socket. The refrigeration machinery fell silent.
</p>
<p>
The monitoring terminal lit up in a panicking flurry of bright green all-caps alert messages. Tina grabbed the freezer’s door handle one last time and pulled it wide open, letting the unit’s cold air spill freely out into the room. She stood back far enough to avoid the draft, and watched the terminal as its temperature readout climbed.
</p>
<p>
It wasn’t long before the cases could be comfortably touched with bare hands. She grabbed them two at a time, pulled them from their slippery racks, and set them on the table. Melting frost dripped down their sides, pooling on the tabletop. She opened their lids and pulled out vial after vial, giving each label a quick examination before tossing it down into a discard pile.
</p>
<p>
There was one vial that bore visibly less frost on its cap &mdash; it had clearly been withdrawn from its box often. Tina drew it out, and knew immediately that it was the one the Russian had come for. In place of a label, this vial had a tattered yellow smiley face sticker affixed on its translucent surface.
</p>
<p>
The Russian perked up as he saw her lay it on the table. He slid his cellphone into his pocket, stepped forward eagerly, and picked up the tube with the tips of his gloved fingers. 
</p>
<p>
“Are we done here?” Tina asked.
</p>
<p>
The man held the vial to his face. His grin echoed the smile on the round yellow sticker. “Yes. I think we are.”
</p>
<p>
“Good,” she said, already halfway to the door.
</p>
<p>
She didn’t make it. A leather-gloved hand clamped around her wrist and jerked her back. “Not so fast, young lady.”
</p>
<p>
“No! Let me go!” she demanded.
</p>
<p>
“You’re quite useful, you know,” he said.
</p>
<p>
“You said we’re <em>done</em> here!” She struggled, but to no avail. He held her wrist with his left hand, balancing his gun and the vial in his right.
</p>
<p>
“We are done <em>here</em>,” repeated the man. “But… I have more use for you…”
</p>
<p>
Tina felt her stomach lurch. “<em>No</em>!” she screamed, fighting against his grip with all her might.
</p>
<p>
He yanked her back into the room and released her, letting her momentum carry her a few stumbling steps.
</p>
<p>
“Relax,” he said in a commanding tone. “Do not assume things, lady. I am a professional. I don’t mix business with pleasure. Besides, I get hotter pieces of ass than you any time I want. Your body is of no interest to me.”
</p>
<p>
Tina stared at him silently. She found herself feeling relieved and offended at the same time.
</p>
<p>
“You are proving handy to have around,” he said. “Besides…” He gestured with the vial. “I need to make sure you did not pull any funny business with this tube. I need the stuff in here to come out alive. And that means you need to give me… insurance.”
</p>
<p>
Tina gulped quietly.
</p>
<p>
“So, here is a plan,” he continued. “We take you back to our factory. Your little friend is there &mdash; she will be happy to see you. We keep you until we finish a good batch and see that everything works. It should only take a few days. Nobody will hurt you. And when you get success, we let you go.”
</p>
<p>
“You have got to be kidding me,” Tina said.
</p>
<p>
“Stop arguing already! Cooperate and things go well for you. We are businessmen, not animals. Now come on!” He waved the gun at her.
</p>
<p>
The sound of his voice began to recede, like she was hearing it underwater. She felt her skin crawl as goosebumps rose. She looked furtively around the room.
</p>
<p>
A few feet away from her, the old beige terminal still flashed silent distress about the freezer’s temperature.
</p>
<p>
“Okay. I’ll do it,” she said. 
</p>
<p>
“Good girl,” he said. “Let’s go.”
</p>
<p>
“I need to check the environmental settings for the cold storage unit,” she said, nodding her head toward the terminal. “When we get the tube back to your factory, I’ll need to store it somewhere with the exact same temperature, pressure, and humidity levels.”
</p>
<p>
He grinned again. “See! You’re being useful already!”
</p>
<p>
She stepped slowly toward the terminal, laid her hands upon the keyboard, and made a few meaningless keystrokes. The clunky keys made loud <em>ka-chunk!</em> sounds beneath her fingers.
</p>
<p>
“My colleagues and I will show our appreciation of you being so helpful,” the man said.
</p>
<p>
She squinted at the screen. “Hmm… Damn it,” she said slowly.
</p>
<p>
“Is everything alright?” he asked her.
</p>
<p>
“This isn’t making any sense,” she said. “Come here, can you take a look at this?” She glanced at him as she beckoned him over. He was still holding both the vial and the revolver in the same hand. That meant his grip on both was probably weak.
</p>
<p>
He stepped toward the terminal and stood right behind her, looking over her shoulder. 
</p>
<p>
“See where it says ‘Temperature’?” she asked, quietly curling her fingers underneath the keyboard’s edges.
</p>
<p>
“Yes…” he said, leaning forward.
</p>
<p>
With a swift upward jerk, Tina swung the keyboard over her shoulder and smashed it against his face.
</p>
<p>
As he smarted from the blow, she grabbed for the revolver, working her fingers between his hand and the gun. The vial fell, rolling in a small circle on the linoleum. The revolver twisted in his grasp but wouldn’t yield. Her index finger landed inside the trigger guard.
</p>
<p>
She realized that, even if she couldn’t take the gun, maybe she could empty it. Guns only hold so many bullets. And without the threat of being shot, she might be able to make a run for it. She pushed the barrel upward and away from her, and pulled the trigger.
</p>
<p>
The sound wasn’t just deafening. It was so loud it was blinding.
</p>
<p>
A foot-long arc of black and orange flame flashed from the barrel. A hot shock wave blasted across Tina’s face, jostling her hair. Her nostrils filled with the sharp, earthy odor of gunpowder.
</p>
<p>
The gun’s recoil hit her palm like a baseball bat in full swing. Her hand was knocked back as the revolver flew upward, escaping her grasp. The Russian, his arms longer and his grip stronger, was just barely able to keep hold of the weapon. Grainy white dust sprinkled from the wall nearby. There was a hole in the drywall, the size of a man’s fist.
</p>
<p>
For a split second, she was too disoriented to move. The shock of the explosion left her momentarily paralyzed. In that instant, her world was reduced to nothing but the hole in the wall and the ringing in her ears. She needed to make sure she could at least still breathe before doing anything else.
</p>
<p>
And suddenly she couldn’t.
</p>
<p>
While she had been dazed by the blast, the Russian had regained control of the weapon. He hadn’t shot her with it. Instead, he slammed the butt high into her abdomen, just below her sternum.
</p>
<p>
She clutched her chest with both hands, gasping for air, writhing and twisting her body, unable to understand why her lungs suddenly refused the simple autonomic instruction to just <em>inhale</em>. She heaved her shoulders, trying to get a shallow current of oxygen into her quickly acidifying bloodstream. Her clenching throat emitted an unnatural, high-pitched wheeze.
</p>
<p>
After several terrifying seconds, her breath gradually returned.
</p>
<p>
“Stupid fucking bitch,” grumbled the Russian, angry but collected. He touched two gloved fingers to his mouth and examined them. His lower lip was bleeding where Tina had busted it open with the keyboard. He slowly knelt down and retrieved the vial from the floor, keeping the gun trained on her with renewed mindfulness. “You try something like that again, I hurt you in ways that take longer to heal. Understand?”
</p>
<p>
Tina’s mind spun with anger, fear, and self-pity. With nausea welling up in her throat, she began to march toward the door.
</p>
<p>
It was then that the Russian, with a startled expression, suddenly turned his head toward the hallway. He quickly and quietly motioned with his hand for her to stop moving.
</p>
<p>
Tina halted in her tracks. “What now?”
</p>
<p>
“Shhhhh!” hissed the Russian.
</p>
<p>
Tina could just barely make out a man’s voice from down the hallway, steadily drawing closer.
</p>
<p>
“Negative, Dispatch,” said the man’s voice. “No signs of engagement. Breach signals are rising. Proceeding further into Sector G.”
</p>
<p>
The Russian stared at the doorway. “What is this shit?” he mumbled slowly.
</p>
<p>
“Dispatch, I’m seeing illumination from the cryogenic storage area,” the unseen man said loudly. “Radiometric breach waves are increasing. Approaching now.”
</p>
<p>
The Russian turned to Tina with eyes wide, his expression angrily demanding answers. Tina, just as confused, shrugged with upturned palms. He closed his gloved fist around the tube, and tucked his revolver into his jacket pocket. “Don’t move,” he ordered.
</p>
<p>
He then stepped out into the hallway, and, as he closed the door, he said, “Who the fuck are you?”
</p>
</div>