<div class="chapsection">
<p>
<span class="caplead">The Russian looked a lot scarier in person</span> than on a laptop screen. He wasn’t any taller than Danny, but his raw strength and physical training were clearly evident in his posture and movements. His busted lip only added to his air of ferocity. 
</p>
<p>
Danny felt ill. His own body was the logical result of slouching over a keyboard since the age of seven. His idea of exercise was <em>Dance Dance Revolution</em>, which did nothing for upper body strength. This man could end him without breaking a sweat.
</p>
<p>
“Sir, you need to accompany me to decontamination immediately,” Danny said authoritatively through a surgical mask that covered his mouth and nose &mdash; and also saved him from having to improvise facial expressions. “This facility has been exposed to ectopic levels of radiological contaminatives far in excess of federal safety obligations.”
</p>
<p>
“What the fuck are you talking about?” the Russian grumbled.
</p>
<p>
Danny held his microwave gun pointed at the Russian with one hand and his cellphone up to his ear with the other. Despite the fact that the former was technically a weapon, Danny recognized that it was the latter that was actually keeping him at bay.
</p>
<p>
“I’m with the Federal Emergency Management Agency’s biological alert response team. This building is a registered Class Seven research facility, with instant alarms wired directly to Bellevue regional FEMA headquarters.” Danny knew he was a terrible actor. Jason and Moshen were feeding him lines through his cellphone. He was doing his best to deliver them as believably as he could.
</p>
<p>
The Russian eyed Danny warily. “You are some kind of cop? Do you have a badge?”
</p>
<p>
“I’m a FEMA contractor,” said Danny. “We’re not cops, but I’m patched in to the Bellevue Police Department on the radio right now.”
</p>
<p>
“You talking to cops outside?”
</p>
<p>
“That’s correct. We have patrol units stationed around the building. There’s a decontamination van out front and ambulances on standby.”
</p>
<p>
The Russian stared at Danny incredulously. 
</p>
<p>
“There’s a window in the conference room behind you,” Danny said suggestively. “Go ahead. Take a look.”
</p>
<p>
The man cautiously backed up several feet until he could see outside. In the dark of night, through the needles of the pine trees that lined the building, flashed the distinct red and blue strobe of a police light.
</p>
<p>
“Fucking shit!” the man spat. “What the fuck is going on?”
</p>
<p>
“Several minutes ago we received an alarm indicating a breach of containment of potentially infectious pathogenic microbiations. According to the readings on this interferometric biocontamination detector kit, you’ve been exposed to dangerous levels of organic couplings. Biohazard containment protocol requires that I get you to a decontamination facility immediately.” 
</p>
<p>
“You got some kind of call?” the Russian asked tensely.
</p>
<p>
“The signal was an automatic response to an unscheduled access to the cryogenic containment machinery,” Danny said. “Do you know of any recent activity involving the freezer equipment?”
</p>
<p>
“I know of nothing,” said the man. “I am just nighttime delivery man.”
</p>
<p>
“Are you alone here inside this facility?”
</p>
<p>
“Yes,” said the Russian. “Yes, I am.”
</p>
<p>
He immediately looked past Danny with an angry glare as a beam of light swept the hallway. A click from the freezer room’s door handle was followed by the humming of the cooling equipment inside. Danny looked over his shoulder.
</p>
<p>
“No. No, he’s not,” said Tina. 
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">“I’m sorry. The, um, alarm is my fault.</span> I forgot to deactivate the nightly security.” 
</p>
<p>
Tina saw the man who was spewing the incoherent technical jargon. He was slender and moderately tall, with jeans and hiking boots poking out from beneath an ill-fitting white lab coat. His floppy, curly brown hair was long overdue for a cut. He moved and spoke with youthful energy, but the slight cracking of the skin near his eyes and the subtle gray streaks near his temples betrayed the march of slowly advancing years.
</p>
<p>
She couldn’t see the man’s mouth through the surgical mask, but his eyes radiated gratitude and relief.
</p>
<p>
She could also see something that the Russian apparently couldn’t: a large dark red blot on the back of the white lab coat. The man’s left shoulder blade was matted with blood. 
</p>
<p>
“Can you tell us anything about the nature of the contaminants?” he asked her.
</p>
<p>
She went to stand by his side, so that he wouldn’t be at risk of revealing his injured shoulder. “They’re an <em>E. coli</em> strain with plasmid enhancements of indeterminate nature. They’re being transported in an Eppendorf vial.” That part, at least, was true.
</p>
<p>
The man stared at her blankly. Tina could hear a faint voice squawking over his cellphone. Finally, he asked, “What is the location of this vial?”
</p>
<p>
“It’s enclosed in the port-side extremity,” she answered.
</p>
<p>
She stood close enough to hear several tinny voices in the man’s cellphone. “Oh! It’s in the Russian dude’s hand!” “Which one?” “Port side. Which side is port?” “Left if you’re facing stern.” “Are you sure?” “I own a yacht. I know which way is port.” “So is it the Russian’s left or Danny’s left?” “It’s the left side if you’re facing the front of the building.” “What?” “That’s how it works on a boat…” 
</p>
<p>
While the voices chattered, Tina spotted movement behind the Russian, around the bend in the hallway. A large scruffy man, overweight but agile, moved slowly through the darkness. He appeared to be holding a weapon of some kind. He saw her looking at him, and brought a finger up to his lips.
</p>
<p>
“Listen,” Tina said to the geeky guy in the lab coat. “I am aware of the present need for complex communication protocols, owing to the proximity of non-native personnel. And while I’m uncertain about the exact cause of your organization’s presence in this facility, it’s clear to me that your relationship to law enforcement suffers from a complete lack of existence. Now, are you aware of the presence of clandestine personnel to the posterior of the non-native agent?”
</p>
<p>
“Affirmative,” the man responded. “That would be Agent Bravo. He’s on standby pending physical altercation. However, that would be a scenario best avoided.”
</p>
<p>
“Agreed,” Tina said. “Immediate departure would be advisable.”
</p>
<p>
“You go ahead,” said the man. “For me, retrieval of contaminant is imperative.”
</p>
<p>
Tina’s jaw dropped. “Have you lost all function in your cerebral cortex?”
</p>
<p>
The Russian watched them talk with narrowed eyes.
</p>
<p>
The geeky guy turned to the Russian and said, “Sir, are you currently carrying a vial of potentially infectious agents on your person?”
</p>
<p>
The Russian shot Tina a murderous glare. “Did she tell you that?”
</p>
<p>
“No, sir,” said the geek. “It’s simply the only way to explain the amplitude of these readings.” He waved his instrument back and forth in the direction of the Russian. Tina had no idea what to make of the device he held. It looked like some kind of high-tech art project made of parts scavenged from Radio Shack. One thing that she could clearly see, though, was that he wasn’t getting any “readings” from the machine. It had no display.
</p>
<p>
“The fuck are you doing with that thing?” asked the Russian.
</p>
<p>
“Sir, please show me what’s in your hands,” ordered the man.
</p>
<p>
“There is nothing in my hands,” the Russian asserted.
</p>
<p>
“These readings say otherwise,” the geek said emphatically.
</p>
<p>
“I doubt that,” replied the Russian.
</p>
<p>
“What do you mean?” said the man.
</p>
<p>
The Russian slowly said, “Let me see these readings.”
</p>
<p>
The man nervously replied, “It takes a great deal of training to interpret the status of the indicator lamps on this interferometric biodetector.”
</p>
<p>
All signs of tension and apprehension left the Russian’s face. He stared at the geek with a look of contemptuous incredulity. “As much training as it takes to engage in complex communication practices to fool non-native personnel in proximity?”
</p>
<p>
The geek gulped.
</p>
<p>
“You are both assholes,” the Russian said slowly. “You think because I have accent that I don’t understand things? Fuck you both, you insulting pieces of shit. Let me tell you something. Trying to get in on my action, keep me from doing my job? I understand. It’s nothing personal. But insulting my intelligence? That is something I do not forgive.” 
</p>
<p>
The geek gulped. “Agent Bravo, prepare for engagement.” He pulled off his surgical mask and let it drop to the floor. His face was focused, calculating.
</p>
<p>
Tina saw the burly man in the hallway crouch down, ready to pounce.
</p>
<p>
“Cut the crap already,” the Russian ordered. “You do not intimidate me. You could not intimidate anyone. I don’t know who you are talking to, and I don’t know why there is a cop car outside that window. But one thing I know is that you are completely full of shit.” The Russian held out his left hand and, from his gloved fist, he produced the small plastic vial. An evil, condescending grin overtook his face. “I will not waste bullet on you. You want this? Come get it.”
</p>
<p>
The geeky man remained resolute. He put his cellphone in his pocket, flexed, and backed up several paces. He raised his machine with both hands like a giant club.
</p>
<p>
The Russian laughed, turned his torso sideways, and drew his fist up near his hip in a ready posture. He placed his feet shoulder-width apart with slightly bent knees, and beckoned for his opponent to attack.
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">With a mighty battle cry,</span> Danny rushed headlong at the Russian.
</p>
<p>
The Russian kept his eye on him, evaluating his trajectory, judging his center of mass.
</p>
<p>
So he was caught completely off-guard when the lug wrench smashed against the back of his skull with the full force of Mike’s silent charge from behind.
</p>
<p>
“Yes!” Tina squealed.
</p>
<p>
As the Russian reeled in pain, Danny swung his machine like a baseball bat at the man’s torso. The heavy pack of blue ultracapacitors hit the Russian in the chest with a hollow thud, knocking the air out of his lungs and sending him stumbling sideways. The Eppendorf tube fell to the carpeted floor.
</p>
<p>
Danny tried to scramble for the vial, but to his surprise he found himself hopelessly winded from the attack. He took a few panting, breathless steps.
</p>
<p>
Tina dashed for it. She plucked the tube from the floor and put it in her pocket.
</p>
<p>
Danny then half-saw, half-felt her run up beside him. Oddly, she seemed taller than him. She put his arm over her shoulders, his back stinging with the motion. She helped him stand back up. He had fallen to one knee without even realizing it.
</p>
<p>
“You’ve got to get out of here,” she told him. The feel of her body, firm and feminine, felt reassuring and supportive.
</p>
<p>
He shook his head and looked gravely at Mike and the Russian.
</p>
<p>
The Russian, dizzy from the blows, swung blindly outward as he turned to face his rear attacker.
</p>
<p>
Mike, taller and larger than the man, attempted to bring the lug wrench crashing down on his head again.
</p>
<p>
Regaining his senses, the Russian parried Mike’s downward blow with an overhead block, the lug wrench hitting his forearm rather than his head. He fluidly parlayed the motion of the block into a side kick; his rearward leg struck upward in a powerful snap against the bottom of Mike’s ribcage. Mike grunted in pain and curled his torso down around the point of impact, clutching his arms defensively near his chest. As the Russian brought his leg down from the kick, he stomped his heel squarely down onto Mike’s foot. Mike staggered backward. 
</p>
<p>
The Russian shifted his weight to deliver another kick. Mike saw him and quickly took another step back to avoid the attack. He found himself with his back to a wall.
</p>
<p>
The Russian’s planned second kick was a feint. Mike, still protecting his aching rib, was unwittingly leaving his face open.
</p>
<p>
The delivery of the side kick had brought the Russian’s hand down near his hip. From there, with a turn of his waist and a cough-like shout of, “Kyuh!”, he lunged forward and fired his fist up and center. The strike drove straight into Mike’s nose.
</p>
<p>
Mike’s head flew back and slammed into the wall behind him, with enough force to knock a hole in the drywall. Flakes of gypsum flew from the point of impact. White dust lodged in Mike’s hair.
</p>
<p>
The Russian paused for a moment to read his opponent.
</p>
<p>
Mike withdrew his head from the drywall, revealing a shallow crater. Along the dent, outlined in gypsum dust, was the unmistakable vertical rectangular shape of a wooden stud. The broken drywall bore a smear of blood.
</p>
<p>
Mike swayed sideways and stood uneasily, looking blankly off to the side.
</p>
<p>
“Mike!” Danny shouted.
</p>
<p>
Slowly, Mike pulled himself up to his full height and looked down at the Russian with a completely uncomprehending face. His eyes were glazed and empty. 
</p>
<p>
Mike absentmindedly let go of the lug wrench. It dropped to the floor. Slowly, very slowly, he took a step toward the Russian and began an uncontrolled lurch forward.
</p>
<p>
The Russian was poised to take advantage of Mike’s momentum. He reached up with both hands, grabbed Mike’s head, and prepared to pull down. He drew up his leg, ready to drive his knee into Mike’s face.
</p>
<p>
His Bluetooth headset exploded.
</p>
<p>
Tina’s wide-eyed gaze turned from the combatants to Danny. Too weak to join the melee, Danny had pulled away from Tina and aimed his machine at the two men. Nothing seemed to happen when he had pulled the trigger except for a soft “<em>bonk!</em>” and a change in color of some small lights.
</p>
<p>
The man yelped in pain and surprise. The burst in his ear threw him off-balance. His hands around Mike’s head, he stumbled in mid-kick, holding onto Mike to remain upright.
</p>
<p>
With a wide, sloppy sweep, Mike kicked the man’s legs out from under him. As the man fell, Mike let himself fall with him. They hit the ground together. Large, overweight, muscular Mike used the man’s body to break his fall. 
</p>
<p>
The man grunted, wriggled, and tried to push Mike off of him.
</p>
<p>
Mike lay on top of the Russian like a bag of cement, refusing to yield. His broken face lay pressed against the ground next to the Russian’s. Mike slid his hands blindly toward the squirming man’s head, keeping his foe’s arms pinned with his bulk.
</p>
<p>
As the man punched and struggled beneath him, Mike wrapped his fingers around his neck. He placed his thumbs across the Russian’s throat, stared down at him with eyes blank and empty, and squeezed.
</p>
<p>
The Russian gasped and gulped for air, trying in vain to heave Mike away. He tried kicking him, punching him, pushing, twisting, writhing, but nothing would make Mike move. Mike simply looked down at the Russian senselessly, as though he was looking through him into some kind of empty space below the floor.
</p>
<p>
The Russian’s eyes turned bloodshot and began to moisten and bulge out of his face. His tongue swelled and stuck out of his mouth, spittle foaming at the corners of his lips. His skin began to turn a disturbing shade of purple. He tried to say something, but his voice came out as a wet guttural honk, barely discernible as human. His struggling degenerated into aimless twitches. After making a series of disgusting gurgling noises, he stopped moving.
</p>
<p>
“Mike…” said Danny.
</p>
<p>
Mike looked up vaguely at Danny, his nose crushed, his hair caked with gypsum powder, his beard moist with blood. He lifted himself up off the Russian slowly and awkwardly and stood there, dazed, his imploded nose bleeding.
</p>
<p>
Then he took a few stumbling steps toward the wall, leaned himself against it, and vomited.
</p>
<p>
Danny’s cellphone squawked from his pocket, “Are you guys okay?”
</p>
<p>
“Mike’s hurt,” said Danny toward his own pocket.
</p>
<p>
“So are you,” said Tina.
</p>
<p>
“Nah, I’m fine,” said Danny. “Just winded.”
</p>
<p>
“You’ve lost a lot of blood,” she said.
</p>
<p>
“How do you figure?” he asked.
</p>
<p>
She turned around to show him her cardigan. The parts of it that had been in contact with the back of his left shoulder were soaked in blood. His blood.
</p>
<p>
“What the fuck?” He put down his machine, took off his lab coat, and stared at the large red stain.
</p>
<p>
A high-pitched wheezing sound emerged from the floor near them. The Russian stirred, the veins in his neck bulging and throbbing.
</p>
<p>
Tina quickly left Danny’s side and ran towards the Russian. He was beginning to turn and lift his head, his still-unconscious body driven by reflexes to restore the flow of air.
</p>
<p>
She darted a hand into the man’s pocket and grabbed his revolver.
</p>
<p>
Danny said, “His cellphone. Get his cellphone.”
</p>
<p>
Tina nodded. With two or three quick pats, she felt the rectangular bulge in his jacket pocket. She grabbed it and sprung away.
</p>
<p>
She headed straight for Mike. He stood leaning against the wall, staring down emptily at his own vomit, a trickle of blood and drool dripping slowly from his face.
</p>
<p>
She put her hand on his shoulder. “Hello. What’s your name?” she asked in a slow, clinical tone.
</p>
<p>
Mike turned his broken face toward her, and with a slow, slightly slurred voice, he said, “I am called Krongor, Barbarian of the Lowland Plains.”
</p>
<p>
In the dim hallway, Tina turned on the Russian’s cellphone and shined the light of its screen into Mike’s eyes.
</p>
<p>
“We need to get him to a hospital right now,” she said to Danny.
</p>
<p>
“Broken nose?” asked Danny.
</p>
<p>
“Concussion.”
</p>
<p>
From off to the side, Mike droned, “Are you a priestess of Eir? I need healing.”
</p>
<p>
“Come on, big guy,” she said, slipping herself between him and the wall. “I’ll help you walk. Let’s get… <em>Ghuh</em>! Holy <em>shit</em> you’re heavy!” 
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">The escape back to the lobby</span> felt like a jostling, jerking montage, a miasmic swirl of the sound of wheezing and the smell of vomit and blood. The scruffy injured man took long, lumbering steps, too slow and sometimes in the wrong direction, and often stopping to yawn and trying to sit down in place. 
</p>
<p>
The geek, despite being injured himself, handled most of the task of shepherding his scruffy friend. He yelled into his cellphone, “Rendezvous at the front! Jason, extract us!”
</p>
<p>
Tina, in the meantime, divided her attention between them and the Russian, whom she watched with horror as he regained consciousness. With a series of fitful coughs he propped himself up on his elbows. His watery eyes opened. As she and the two men hurried down the hallway, the Russian turned to them with primal fury in his face. Tina flinchingly waved the small silver gun at him. The sight of his own gun pointed at him only enraged him further, and he hoisted himself to his feet and began to stumble toward them.
</p>
<p>
He still wasn’t quite able to breathe. He tripped, fell to his hands and knees and rasped loudly as he tried to inhale. 
</p>
<p>
Tina and the two men rounded a bend in the hallway and tried to rush down the straight corridor past the bullpen towards the brightly lit lobby.
</p>
<p>
But with the scruffy injured man’s disoriented ambling, the straight hallway felt like a twisting labyrinth. The bright spot of light at the end of the corridor seemed to draw nightmarishly farther into the distance with every step forward.
</p>
<p>
And behind them, with a half-crawling gait, the Russian, wheezing and rasping and coughing, dragged himself around the corner. His eyes burned with a lust for revenge. 
</p>
<p>
They crashed through the interior door into the lobby with the Russian gaining rapidly, his breath and strength quickly returning. The geek wordlessly dropped his contraption to the floor and started pulling on Tina’s reception desk a few short feet from the door. Tina understood, and rushed to the other side to lift and push. Everything on the desk &mdash; her computer, her purse, her paperwork &mdash; tumbled to the floor as they slid and jostled it into position. They wedged the desk sideways against the wide glass door just as the Russian’s fast-moving form appeared on the other side. He pushed and kicked at the door, making the barricade slide with every impact. The two of them kept the desk braced against the door with their own strength, but without their active defense it wouldn’t hold for long.
</p>
<p>
“Jason!” the geek shouted into his cellphone. “Car! Now!” Holding himself against the desk, he turned to Tina. “I’ll hold this guy off. There’s friends coming with a car. Get Mike out of here. I’ll be right behind you.”
</p>
<p>
Tina looked out the glass front doors with the large frosted “W”. 
</p>
<p>
Outside, in the darkness of the parking lot, Tina could see the distinct red and blue strobe pattern of a police car light.
</p>
<p>
A wave of relief washed over her. “Hey! Hey… you…” she said to the geek.
</p>
<p>
“My name’s Danny,” he said. 
</p>
<p>
“Look!” she said, nodding at the lights outside. “The cops are here! It’s all okay!”
</p>
<p>
“That’s not the cops,” he replied. “That’s Satish.”
</p>
<p>
Through the glass doors, Tina saw a large black SUV screeching to a halt just in front of Tungsten’s front door. In the SUV’s headlights, she could see two men standing in the parking lot. One looked small and scrawny with thick glasses, the other stocky and dark-skinned. They both carried open laptops on their arms.
</p>
<p>
She saw that the police car lights weren’t real. They were simply a full-screen video being played on the stocky man’s laptop.
</p>
<p>
Danny turned to Tina and yelled, “Go!” 
</p>
<p>
Hesitant and suspicious, Tina looked at the aging nerd holding the desk against the door, and at his lumbering friend. They were both injured, the latter critically so. They’d saved her from a kidnapping; they’d probably even saved her life. Whoever they were, they weren’t bad men. And whatever they were doing here, they clearly weren’t very good at it.
</p>
<p>
The SUV let out a long honk.
</p>
<p>
She grabbed her purse and hurried over to the scruffy guy. He was staring at the Russian and mumbling incoherently. She hustled him out through the front door. The side door to the black Lincoln Navigator was open.
</p>
<p>
The dark-skinned man helped them into the middle row of seats. “Mike! Mike, you big idiot, are you okay?” he said in an Indian accent.
</p>
<p>
“Satish!” the injured man said. His furry, bloody face lit up with childlike glee. “Satish! I need to tell you something!”
</p>
<p>
“What is it, Mike?” the Indian said with worry as they entered the car.
</p>
<p>
Mike slumped down into the far seat, resting his head against the window. “I rolled a natural twenty!”
</p>
<p>
Satish answered, “What?”
</p>
<p>
“On the grapple attack,” said Mike. “Against the fighter-thief with the leather armor. You saw, right?” He let out a long yawn.
</p>
<p>
The driver was a late middle-aged man with a large belly and gelled gray hair. “Danny, we’re all in,” he said into his cellphone. “Get over here fast! The guy in the stockroom jumped out the door as soon as I pulled away. He can’t be far behind.”
</p>
<p>
“Copy that,” said the geek’s voice from the cellphone.
</p>
<p>
A moment later, he came leaping into the SUV with gadget in hand, shaking the entire car on its suspension system. He slammed the car door shut behind him and clambered past Tina into the back seat. 
</p>
<p>
“Danny! You’re okay!” said the driver.
</p>
<p>
The geek replied, “Drive!”
</p>
<p>
Through the windshield, the SUV’s headlights illuminated the figure of a man rounding the corner of the building, carrying a handgun with an attached silencer. Jason hit the gas and cranked the wheel as the man raised his firearm. The SUV lurched heavily and pulled away in a sharp turn. 
</p>
<p>
A series of pops rang out across the parking lot.
</p>
<p>
The middle passenger-side window shattered, sprinkling shards of automobile safety glass into the interior of the car.
</p>
<p>
Mike’s head bounced between the window and the headrest as Jason dodged and weaved across the parking lot. “Owwwwwwwww,” Mike droned.
</p>
<p>
The gunfire stopped, but was replaced by the sound of car doors opening and slamming shut. The tires of the white Tesla Roadster squealed against the pavement.
</p>
<p>
The SUV had barely made it a block down the street before the Roadster caught up, pulling up next to them on the driver’s side. The hum of the Roadster’s electric motor rose and dropped in pitch as its driver kept pace. With six occupants, Jason’s SUV was no match for the all-electric sports car’s speed and maneuverability.
</p>
<p>
Jason saw the long silenced handgun pointing at him out of the passenger side of the Roadster.
</p>
<p>
Everybody in the car flew forward in their seats as Jason slammed on the brake. The throbbing of the SUV’s anti-lock system pulsed through the cabin as the Navigator came to a screeching halt. Jason fought with the wheel to keep the car from pitching into a roll.
</p>
<p>
The Roadster slowed down and pulled into a tight U-turn.
</p>
<p>
The SUV’s passengers were thrown about as Jason rapidly reared the car up, maneuvering halfway through a three-point turn, pausing briefly with the car positioned perpendicularly across the road. The Roadster began to zip back towards them, ready to give chase in the opposite direction on the street, back toward Tungsten.
</p>
<p>
Instead of completing the three-point turn, Jason turned the SUV in the same direction they had already been driving, opposite to the way the Roadster was now heading. The electric sports car whooshed past them. A series of “<em>pop-clack!</em>” sounds burst out as the SUV pulled away and the Roadster turned around again.
</p>
<p>
The small Asian guy in the passenger seat screamed at Tina, “Shoot back already!”
</p>
<p>
Tina realized she was still holding onto the Russian’s revolver. The mere existence of this small gun made her stomach lurch. It felt like an abomination, an obscenity cast in metal. “No,” she said flatly.
</p>
<p>
“Why the fuck not?” Moshen demanded.
</p>
<p>
“Have you ever shot at a person before?” she countered.
</p>
<p>
The rear window of the SUV collapsed in a shower of glass slivers. Danny screamed and ducked.
</p>
<p>
“Quit being such a girl and shoot back!” insisted Moshen.
</p>
<p>
“Fuck you,” replied Tina. “Whoever you are.”
</p>
<p>
A low “ploink!” sounded from the back of the car as a bullet chipped out a chunk of the rear bumper. 
</p>
<p>
“Moshen,” he answered. “Nice to meet you. Now give me the gun.” He stretched out his hand.
</p>
<p>
“Do you know how to use it?” she asked skeptically.
</p>
<p>
“It’s a gun. How hard can it be? It’s a point-and-click interface.”
</p>
<p>
Tina shoved the revolver into his hand, happy to get the evil little thing away from her. “Careful with it. It’s got a hell of a kick.”
</p>
<p>
A bullet shattered the SUV’s right taillight.
</p>
<p>
The Asian kid leaned out the passenger side window, trying to point the gun at the Roadster behind them. Jason helped him by turning sharply to the right, onto another dark side street. 
</p>
<p>
Moshen pulled the trigger.
</p>
<p>
Everybody in the car reflexively ducked down at the overwhelming boom.
</p>
<p>
The thundering sound was immediately followed by the clatter of an object skidding across the cracked windshield and falling away onto the road.
</p>
<p>
Danny asked from the back, “What the fuck was that?”
</p>
<p>
“Nothing!” said Moshen defensively. “That was nothing!”
</p>
<p>
Jason answered, “That… was the gun.” 
</p>
<p>
The SUV bobbed sideways as Jason swerved around a car that had the misfortune of being on the same suburban road. The innocent bystander’s horn Dopplered behind them as Jason desperately sped his way down the street, the Roadster in pursuit drawing ever closer.
</p>
<p>
“I can’t out-drive them,” said Jason.
</p>
<p>
“Any more bright ideas?” Satish asked Danny with a sneer.
</p>
<p>
All eyes fell on Danny. The SUV fell into tense silence amid the rush of air through broken windows.
</p>
<p>
“Hey, wait a minute,” said Danny. “Guys. Do you hear that?”
</p>
<p>
“Hear what?” asked Moshen.
</p>
<p>
“The sound of their engine.”
</p>
<p>
They listened. 
</p>
<p>
“…No,” said Moshen.
</p>
<p>
Satish said, “It’s an all-electric drive train, you idiot. They don’t <em>have</em> an engine.”
</p>
<p>
“Exactly,” Danny said. “Jason. Get us closer.”
</p>
<p>
Jason asked, “Closer?”
</p>
<p>
“Yeah,” said Danny. He peeked carefully over the SUV’s rear door, through the blown-out window. The Tesla Roadster was barely a hundred feet away. The handgun protruded from its passenger window. “Their car is about two square meters in frontal cross-section. What’s the radius of a sphere for which a 24-decibel gain covers two square meters of surface area?”
</p>
<p>
“How the hell should I know?” Jason yelled back.
</p>
<p>
“Sorry, just thinking out loud,” said Danny. He checked the lights on his machine. 
</p>
<p>
“Seriously, Danny, what the hell is that thing?” yelled Jason.
</p>
<p>
“It’s a HERF gun,” Danny answered.
</p>
<p>
“A Nerf gun?” yelled Jason.
</p>
<p>
“No, HERF,” said Danny. “It stands for High-Energy Radio Frequency. Well, technically a directional HPM &mdash; that’s a High Power Microwave emitter &mdash; but HERF more generally. It’s a DEW &mdash; a directed-energy weapon. Basically an electromagnetic pulse rifle. It produces 3-megawatt bursts of S-band electromagnetic radiation in 50-nanosecond…”
</p>
<p>
Satish barked, “Dude! Some other time!”
</p>
<p>
“Right. Sorry,” said Danny. “Now let me think. One over ten to the two point four times four pi r squared equals two. That’s about… one-twentieth r squared. So r equals square root of forty. That’s about six poiiiint… Six point three meters.”
</p>
<p>
“What do you need me to do, Danny?” Jason shouted back.
</p>
<p>
“Let them get within about 20 feet without exposing me to their passenger side.”
</p>
<p>
“You got it. Hold on tight!”
</p>
<p>
Jason spun the wheel to the left, veering the car across the street’s divider into the oncoming traffic lane. He snapped the wheel straight again and slammed on the brakes.
</p>
<p>
Danny, grabbing onto the seat with one hand and his energy gun with the other, aimed its nozzle out the back of the SUV through the broken rear window, and waited for exactly the right moment.
</p>
<p>
As Jason braked, the Roadster pulled up to within a few scant feet of the SUV. Danny could see the face of the driver, the Russian whom Mike had nearly killed, illuminated by the sports car’s dashboard.
</p>
<p>
Danny pulled the trigger. 
</p>
<p>
The dashboard lights of the gleaming white Tesla Roadster went dead. So did the headlights. So did the motor.
</p>
<p>
Danny yelled back to Jason, “Floor it!”
</p>
<p>
The suddenly unpowered Roadster, rolling along by sheer momentum, quickly began to recede into the distance as the SUV sped away down the street. Screaming Russian curse words followed them briefly before fading into the night.
</p>
<p>
Once the Roadster disappeared in the rearview mirror, Jason finally released the gas pedal down to street-legal speeds. They drove calmly in silence for a few minutes, heading toward downtown Bellevue. 
</p>
<p>
“Damn dude,” Moshen said to Jason. “Where did you learn to drive like that?”
</p>
<p>
“Here. Tonight,” Jason answered, and forced himself to laugh.
</p>
<p>
“Satish!” Mike drawled.  “Can we tally up our experience points now?”
</p>
<p>
Tina said, “This man needs to get to a hospital. Go to Overlake. It’s close.”
</p>
<p>
“No hospitals,” said Satish. 
</p>
<p>
“What?” said Tina.
</p>
<p>
“Hospitals will ask questions,” Satish said.
</p>
<p>
“He’s right,” said the driver. “I have a lot to lose if any of this gets back to me.”
</p>
<p>
“Are you people serious?” screamed Tina. “This guy could go into a coma and die!”
</p>
<p>
Mike asked warily, “Satish…? How many hit points am I down to…?”
</p>
<p>
“I think you’re in the negatives, man,” said Satish.
</p>
<p>
Mike looked horrified. “I’m <em>what</em>? Oh, no! I need Cure Light Wounds! Does anybody here know Cure Light Wounds?”
</p>
<p>
Jason asked, “Christina… It’s Christina, right?”
</p>
<p>
“Tina,” she corrected.
</p>
<p>
“Do you know anywhere we can take him without leaving any records? Someone that can treat him without a paper trail?”
</p>
<p>
Mike said, “Of course she does. She’s a priestess. She knows Cure Light Wounds. None of you guys do. You’re all wizards. Wizards throw lightning bolts and fireballs. Priests handle life energies and heal people.”
</p>
<p>
The man’s senseless words gave Tina an idea. “I know a priestess, actually.”
</p>
<p>
“He doesn’t really mean…” said Jason.
</p>
<p>
“Head towards Swedish Medical Center, on First Hill,” Tina ordered.
</p>
<p>
“I said no hospitals!” said Satish.
</p>
<p>
“Stop spazzing,” Tina said. “I have a friend that lives there. She’s a doctor. She’ll know what to do. …She always knows what to do.”
</p>
<p>
They drove on in silence. The Navigator passed through Bellevue and made it onto the highway. Across the long straight floating bridge of State Route 520, over the moonlit waters of Lake Washington, the speckled lights and skyscraper silhouettes of Seattle’s nighttime skyline loomed before them as they headed into the city.
</p>
<p>
“Guys, listen,” Tina said. “I just want to say, whatever this is all about… Guys, thank you. Thank you for getting me out of there. Really.”
</p>
<p>
“Hey, anytime! No problem!” said Danny awkwardly, adjusting his shoulder. “I mean, my pleasure! Well, not really, but… uh… I, uh…” He smiled shyly. “I like your hair.” 
</p>
</div>