<div class="chapsection">
<p>
<span class="caplead">The Russian looked a lot scarier in person</span> than on a laptop screen. He wasn’t any taller than Danny, but his raw strength was clearly evident in his posture. His busted lip only added to his ferocity. 
</p>
<p>
Danny felt ill. His own body was the logical result of slouching over a keyboard since the age of seven. His idea of exercise was <em>Dance Dance Revolution</em>. This man could end him without breaking a sweat.
</p>
<p>
“Sir, you need to accompany me to decontamination immediately,” Danny said authoritatively through a surgical mask that covered his mouth and nose &mdash; and also saved him from having to improvise facial expressions. “This facility has been exposed to ectopic levels of radiological contaminatives far in excess of federal safety obligations.”
</p>
<p>
“What the fuck are you talking about?” the Russian grumbled.
</p>
<p>
Danny held his microwave gun pointed at him with one hand and his cellphone up to his ear with the other. Despite the fact that the former was technically a weapon, Danny recognized that it was the latter that was actually keeping him at bay.
</p>
<p>
“I’m with the Federal Emergency Management Agency’s biological alert response team. This building is a registered Class Seven research facility, with instant alarms wired directly to Bellevue regional headquarters.” Danny knew he was a terrible actor. Jason and Moshen were feeding him lines through his cellphone. He was doing his best to deliver them as believably as he could.
</p>
<p>
The Russian eyed Danny warily. “You are some kind of cop? Do you have a badge?”
</p>
<p>
“I’m a FEMA contractor,” said Danny. “I’m patched in to the Bellevue Police Department on the radio right now. We have patrol units stationed around the building.” Noting the Russian’s look of incredulity, he added, “There’s a window in the conference room behind you. Go ahead. Take a look.”
</p>
<p>
The man cautiously backed up several feet until he could see outside. In the dark of night, through the needles of the pine trees that lined the building, flashed the distinct red and blue strobe of a police light. “Fucking shit!” he spat.
</p>
<p>
“Several minutes ago we received an alarm indicating a breach of containment of potentially infectious pathogenic microbiations. According to the readings on this interferometric biocontamination detector kit, you’ve been exposed to dangerous levels of organic couplings. Biohazard containment protocol requires that I get you to a decontamination facility immediately.” 
</p>
<p>
“You got some kind of alarm?” the Russian asked tensely.
</p>
<p>
“The signal was an automatic response to an unscheduled access to the cryogenic containment machinery,” Danny said. “Do you know of any recent activity involving the freezer equipment?”
</p>
<p>
“I know nothing,” said the man. “I am just nighttime delivery man.”
</p>
<p>
“Are you alone here inside this facility?”
</p>
<p>
“Yes,” said the Russian. “Yes, I am.”
</p>
<p>
He immediately looked past Danny with an angry glare as a beam of light swept the hallway. Danny looked over his shoulder.
</p>
<p>
“No, he’s not,” said the girl.
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">“I’m sorry. The, um, alarm is my fault.</span> I forgot to deactivate the nightly security.” 
</p>
<p>
Tina saw the man who was spewing technobabble. He was slender and moderately tall, with jeans and hiking boots poking out beneath an ill-fitting white lab coat. His floppy, curly brown hair was overdue for a cut. He moved and spoke with youthful energy, but the cracking of the skin near his eyes and subtle gray streaks on his temples betrayed the march of advancing years.
</p>
<p>
She couldn’t see his mouth through the surgical mask, but his eyes radiated gratitude.
</p>
<p>
She also saw something that the Russian apparently couldn’t: a large dark red blot on the back of the white lab coat. The man’s left shoulder was matted with blood.
</p>
<p>
“Can you tell us about the nature of the contaminants?” he asked her.
</p>
<p>
She went to stand by his side, so that he wouldn’t be at risk of revealing his injured shoulder. “They’re an <em>E. coli</em> strain with plasmid enhancements of indeterminate nature. They’re being transported in an Eppendorf vial.” That part, at least, was true.
</p>
<p>
The man listened to his cellphone. Finally, he asked, “What is the location of this vial?”
</p>
<p>
She thought for a second, and answered, “It’s enclosed in the port-side extremity.”
</p>
<p>
She stood close enough to hear several tinny voices in the man’s phone. “Oh! It’s in the Russian dude’s hand!” “Which one?” “Port side. Which side is port?” “Left if you’re facing stern.” “Are you sure?” “I own a yacht. I know which way is port.” “So is it the Russian’s left or Danny’s left?” “It’s the left side if you’re facing the front of the building.” “What?” “That’s how it works on a boat…” 
</p>
<p>
While the voices chattered, Tina spotted movement behind the Russian. A large scruffy man, overweight but agile, moved slowly through the darkness. He appeared to be holding a weapon of some kind. He saw her looking at him, and brought a finger to his lips.
</p>
<p>
“Listen,” Tina said to the geeky guy in the lab coat. “I am aware of the present need for complex communication protocols, owing to the proximity of non-native personnel. And while I’m uncertain about the exact cause of your arrival at this facility, it’s clear to me that your relationship to law enforcement suffers from a complete lack of existence. Now, are you aware of the presence of clandestine personnel to the posterior of the non-native agent?”
</p>
<p>
“Affirmative,” the man responded. “That would be Agent Bravo. He’s on standby pending physical altercation. However, that would be a scenario best avoided.”
</p>
<p>
“Agreed,” Tina said. “Immediate departure would be advisable.”
</p>
<p>
“You go ahead. For me, retrieval of contaminant is imperative.”
</p>
<p>
Tina’s jaw dropped. “Have you lost all function in your cerebral cortex?”
</p>
<p>
The Russian watched them talk with narrowing eyes.
</p>
<p>
The geeky guy turned to the Russian and said, “Sir, are you currently carrying a vial of potentially infectious agents on your person?”
</p>
<p>
The Russian shot Tina a murderous glare. “Did she tell you that?”
</p>
<p>
“No, sir. It’s simply the only way to explain the amplitude of these readings.” He waved his instrument at the Russian. Tina thought the strange device looked like a mad combination of high-tech art and parts scavenged from Radio Shack. She could clearly see, though, that he wasn’t getting any “readings” from the machine. It had no display.
</p>
<p>
“The fuck are you doing with that thing?” asked the Russian.
</p>
<p>
“Sir, please show me what’s in your hands,” ordered the man.
</p>
<p>
“There is nothing in my hands,” the Russian asserted.
</p>
<p>
“These readings say otherwise,” the geek said emphatically.
</p>
<p>
“I doubt that,” replied the Russian.
</p>
<p>
“What do you mean?” said the man.
</p>
<p>
The Russian slowly said, “Let me see these readings.”
</p>
<p>
The man nervously replied, “It takes a great deal of training to interpret the status of the indicator lamps on this interferometric biodetector.”
</p>
<p>
All signs of tension and apprehension left the Russian’s face. He stared at the geek with smoldering contempt. “As much training as it takes to engage in complex communication protocols to fool non-native personnel?”
</p>
<p>
The geek gulped.
</p>
<p>
“You are both assholes,” the Russian said slowly. “You think because I have accent that I don’t understand things? Fuck you both, you smart-ass pieces of shit. Let me tell you something. Trying to get in on my action, keep me from doing my job? I understand. It’s nothing personal. But insulting my intelligence? That is something I do not forgive.” 
</p>
<p>
“Agent Bravo!” the geek shouted. “Prepare for engagement!” He pulled off his surgical mask. His face was focused, calculating.
</p>
<p>
Tina saw the burly man in the hallway crouch, ready to pounce.
</p>
<p>
“Cut the crap already,” the Russian ordered. “I don’t know who you are talking to, and I don’t know why there is cop car outside that window. But I <em>do</em> know you are completely full of shit.” The Russian held out his left hand and, from his gloved fist, produced the vial. “I will not waste bullet on you. You want this? Come get it.”
</p>
<p>
The geeky man remained resolute. He put his cellphone in his pocket, flexed, and backed up several paces. He raised his machine with both hands like a giant club.
</p>
<p>
The Russian laughed, turned his torso sideways, and drew his fist up near his hip in a ready posture. He placed his feet shoulder-width apart with slightly bent knees, and beckoned for his opponent to attack.
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">With a mighty battle cry,</span> Danny rushed headlong at the Russian.
</p>
<p>
The Russian kept his eye on him, evaluating his trajectory, judging his center of mass.
</p>
<p>
So he was caught completely off-guard when the lug wrench smashed against the back of his skull with the full force of Mike’s charge from behind.
</p>
<p>
“Yes!” Tina squealed.
</p>
<p>
As the Russian reeled in pain, Danny swung his machine like a baseball bat at the man’s torso. The heavy pack of ultracapacitors hit the Russian in the chest, knocking the air out of his lungs and sending him stumbling sideways. The Eppendorf tube fell to the carpeted floor.
</p>
<p>
Danny tried to scramble for the vial, but to his surprise he found himself hopelessly winded from the attack. He took a few breathless steps.
</p>
<p>
Tina dashed for it. She plucked the tube from the floor and put it in her pocket.
</p>
<p>
Danny then half-saw, half-felt her run up beside him. Oddly, she seemed taller than him. She put his arm over her shoulders and helped him stand back up. He had fallen to one knee without even realizing it.
</p>
<p>
“You’ve got to get out of here,” she told him. The pressure of her body felt reassuring.
</p>
<p>
He shook his head and looked gravely at Mike and the Russian.
</p>
<p>
The Russian, dizzy from the blows, swung blindly outward as he turned to face his attacker.
</p>
<p>
Mike attempted to crash the lug wrench down on his head again.
</p>
<p>
The Russian parried Mike’s downward blow with an overhead block, the lug wrench hitting his forearm rather than his skull. He fluidly parlayed the block into a side kick; his rearward leg struck upward in a powerful snap against the bottom of Mike’s ribcage. Mike grunted in pain and curled his torso down around the point of impact, clutching his arms defensively near his chest. As the Russian brought his leg down from the kick, he stomped his heel squarely down onto Mike’s foot. Mike staggered backward. 
</p>
<p>
The Russian shifted his weight to deliver another kick. Mike saw him and quickly took another step back to avoid the attack. He found himself with his back to a wall.
</p>
<p>
The Russian’s planned second kick was a feint. Mike, still protecting his aching rib, was unwittingly leaving his face open.
</p>
<p>
The delivery of the side kick had brought the Russian’s hand down near his hip. From there, with a turn of his waist and a cough-like shout, he lunged forward and fired his fist up and center. The strike drove straight into Mike’s nose.
</p>
<p>
Mike’s head flew back and slammed into the wall behind him, with enough force to knock a hole in the drywall. Flakes of gypsum flew from the point of impact. Dust lodged in Mike’s hair.
</p>
<p>
The Russian paused for a moment to read his opponent.
</p>
<p>
Mike withdrew his head from the drywall, revealing a crater. He swayed sideways and stood uneasily.
</p>
<p>
“Mike!” Danny shouted.
</p>
<p>
Mike pulled himself up to his full height and looked down at the Russian with a completely uncomprehending face. His eyes were glazed and empty. 
</p>
<p>
Mike absentmindedly let go of the wrench. It dropped to the floor. He took a step toward the Russian and began an uncontrolled lurch forward.
</p>
<p>
The Russian took advantage of Mike’s momentum. He reached up with both hands, grabbed Mike’s head, and prepared to pull down. He drew up his leg, ready to drive his knee into Mike’s face.
</p>
<p>
His Bluetooth headset exploded.
</p>
<p>
Tina’s wide-eyed gaze turned from the combatants to Danny. Too weak to join the melee, Danny had aimed his machine at the men. Nothing seemed to happen when he had pulled the trigger except for a soft “<em>bonk!</em>” and a change in color of some lights.
</p>
<p>
The man yelped in pain and surprise. The burst in his ear threw him off-balance. His hands still around Mike’s head, he stumbled in mid-kick, holding onto Mike to remain upright.
</p>
<p>
With a wide, sloppy sweep, Mike kicked the man’s legs out from under him. As he fell, Mike let himself fall with him. They hit the ground together. Mike, weighing easily a hundred pounds more than his opponent, used the man’s body to break his fall. 
</p>
<p>
The man grunted, wriggled, and tried to push Mike off of him.
</p>
<p>
Mike lay on top of the Russian like a bag of cement, refusing to yield. His broken face lay pressed against the ground next to the Russian’s. Mike slid his hands blindly toward the squirming man’s head, keeping his foe’s arms pinned with his bulk.
</p>
<p>
As the man punched and struggled beneath him, Mike wrapped his fingers around his neck. He placed his thumbs across the Russian’s throat, stared down at him with eyes blank and empty, and squeezed.
</p>
<p>
The Russian gasped and gulped for air, trying in vain to heave Mike away. He tried kicking, punching, pushing, twisting,  but nothing would make Mike move. Mike stared downward, as though he was looking through the Russian into some kind of empty space below the floor.
</p>
<p>
The Russian’s eyes turned bloodshot and began to moisten and bulge out of his face. His tongue swelled and stuck out of his mouth, with spittle foaming at the corners. His skin turned a disturbing shade of purple. He tried to say something, but his voice came out as a wet guttural honk, barely discernible as human. His struggling degenerated into aimless twitches. After making a series of disgusting gurgling noises, he stopped moving.
</p>
<p>
“Mike…” said Danny.
</p>
<p>
Mike looked up vaguely at Danny, his nose crushed, his hair caked with gypsum powder, his beard moist with blood. He lifted himself off of the Russian slowly and awkwardly and stood there, dazed, his imploded nose bleeding.
</p>
<p>
Then he took a few stumbling steps toward the wall, leaned against it, and vomited.
</p>
<p>
Danny’s cellphone squawked from his pocket, “Are you guys okay?”
</p>
<p>
“Mike’s hurt,” Danny replied.
</p>
<p>
“So are you,” said Tina.
</p>
<p>
“Nah, I’m fine,” said Danny. “Just winded.”
</p>
<p>
“You’ve lost a lot of blood,” she said.
</p>
<p>
He raised a perplexed eyebrow.
</p>
<p>
She turned around to show him her cardigan. The parts of it that had been in contact with the back of his left shoulder were soaked in blood. His blood.
</p>
<p>
“What the fuck?” He put down his machine, took off his lab coat, and stared at the red stain.
</p>
<p>
A high-pitched wheezing sound emerged from the floor near them. The Russian stirred, the veins in his neck bulging.
</p>
<p>
Tina quickly left Danny’s side and ran towards the Russian. He was beginning to turn and lift his head, his still-unconscious body driven by reflexes to restore the flow of air.
</p>
<p>
She darted a hand into his pocket and grabbed his revolver.
</p>
<p>
Danny said, “Get his phone.”
</p>
<p>
Tina nodded. With a few quick pats, she felt the rectangular bulge. She grabbed it and sprung away.
</p>
<p>
She headed straight for Mike. He stood leaning against the wall, staring down emptily as bodily fluids trickled out of his face and onto the carpet.
</p>
<p>
She laid her hand on his shoulder. “Hello. What’s your name?” she asked in a clear, clinical tone.
</p>
<p>
Mike turned his broken face toward her, and with a slurred voice, he answered, “I am called Krongor, Barbarian of the Lowland Plains.”
</p>
<p>
Tina turned on the cellphone and shined its light into Mike’s eyes.
</p>
<p>
“We need to get him to a hospital right now,” she said.
</p>
<p>
“Broken nose?” asked Danny.
</p>
<p>
“Concussion.”
</p>
<p>
From off to the side, Mike droned, “Are you a priestess of Eir? I need healing.”
</p>
<p>
“Come on, big guy,” she said, slipping herself between him and the wall. “I’ll help you walk. Let’s get… <em>Ghuh</em>! Holy <em>shit</em> you’re heavy!” 
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">The escape back to the lobby</span> felt like a jerking montage, a miasmic swirl of wheezing and vomit and blood. The large concussed man took long, lumbering steps, too slow and sometimes in the wrong direction, and often stopping to yawn and trying to sit down in place. 
</p>
<p>
The geek, despite being wounded himself, handled most of the task of shepherding his scruffy friend. He yelled into his cellphone, “Rendezvous at the front! Jason, extract us!”
</p>
<p>
Tina divided her attention between them and the Russian, whom she watched with horror as he regained consciousness. With a fit of coughs he propped himself up on his elbows. As she and the two men hurried down the hallway, the Russian turned to them with primal fury in his watery eyes. Tina flinchingly waved the small silver revolver. The sight of his own gun pointed at him only enraged him further.
</p>
<p>
He still wasn’t quite able to breathe. He tripped, fell to his hands and knees and rasped loudly. 
</p>
<p>
They rounded a bend in the hallway and tried to rush down the corridor towards the brightly lit lobby. But with the injured man’s disoriented ambling, the straight hallway felt like a twisting labyrinth. The bright spot of light at the end seemed to draw nightmarishly farther with every step forward. And behind them, with a half-crawling gait, the Russian, rasping and coughing, dragged himself around the corner. His eyes burned with a lust for revenge. 
</p>
<p>
They crashed into the lobby with the Russian gaining rapidly, his breath and strength quickly returning. The geek wordlessly dropped his contraption to the floor and started pulling on Tina’s reception desk a few short feet from the lobby’s interior door. Tina understood, and rushed to the other side to lift and push. Everything on the desk &mdash; her computer, her purse, her paperwork &mdash; tumbled. They wedged it sideways against the wide glass door just as the Russian’s fast-moving form appeared on the other side. He shoved and kicked at the door, making the barricade slide with every impact. The two of them kept the desk braced against the door with their own strength, but without their active defense it wouldn’t hold for long.
</p>
<p>
“Jason!” the geek shouted into his cellphone. “Car! Now!” Pushing against the desk, he turned to Tina. “I’ll hold this guy off. There’s friends coming with a car. Get Mike out of here. I’ll be right behind you.”
</p>
<p>
Tina looked out the glass front doors with the large frosted “W”. Outside, in the darkness of the parking lot, there flashed the distinct red and blue strobe pattern of a police car. A wave of relief washed over her. “Hey! Hey… you…”
</p>
<p>
“My name’s Danny,” he said.
</p>
<p>
“Look!” she said. “The cops are here! It’s all okay!”
</p>
<p>
“That’s not the cops,” he replied. “That’s Moshen.”
</p>
<p>
A black SUV screeched to a halt in front of the entrance. In the SUV’s headlights, she could see a young man standing in the parking lot. He looked small and scrawny with thick glasses, and carried an open laptop on his arm.
</p>
<p>
The police car lights weren’t real. They were simply a video being played on the scrawny kid’s laptop.
</p>
<p>
The SUV let out a honk.
</p>
<p>
She grabbed her purse and hurried over to the scruffy guy. He was staring at the Russian and mumbling incoherently. She hustled him outside. The side door to the Navigator was open.
</p>
<p>
The scrawny kid helped them into the middle row of seats. “Mike! Mike, you big idiot, are you okay?”
</p>
<p>
“Moshen!” the injured man said. His furry, bloody face lit up with childlike glee. “I need to tell you something!”
</p>
<p>
“What is it, Mike?” Moshen said, his face sunken with worry.
</p>
<p>
Mike slumped down into the far seat, resting his head against the window. “I rolled a natural twenty!”
</p>
<p>
Moshen answered, “What?”
</p>
<p>
“On the grapple attack,” said Mike. “Against the fighter-thief with the leather armor. You saw, right?”
</p>
<p>
Danny came leaping into the SUV with his bulky gadget in hand. He slammed the car door shut behind him, clambered past Tina into the back seat, and yelled, “Drive!”
</p>
<p>
Through the windshield, the SUV’s headlights illuminated a man rounding the corner of the building, carrying a handgun with a silencer. Jason hit the gas and cranked the wheel as the man raised his firearm. The SUV lurched heavily and pulled away in a sharp turn. A series of pops rang out across the parking lot.
</p>
<p>
The middle passenger-side window shattered, sprinkling glass into the interior of the car.
</p>
<p>
Mike’s head bounced between the window and the headrest as Jason dodged and weaved. “Owwwwwwwww,” Mike droned.
</p>
<p>
The gunfire stopped, but was replaced by the sound of car doors opening and slamming shut. The tires of the Tesla Roadster squealed against the pavement.
</p>
<p>
The Navigator had barely made it a block down the street before the Roadster caught up, pulling up next to them on the driver’s side. The hum of the Roadster’s electric motor rose and dropped in pitch as its driver kept pace. Jason’s SUV was no match for the all-electric sports car’s speed and maneuverability.
</p>
<p>
Jason saw the long silenced handgun pointing at him out of the passenger side of the Roadster.
</p>
<p>
Everybody in the car flew forward in their seats as Jason slammed on the brake. The throbbing of the SUV’s anti-lock system pulsed through the cabin as the Navigator came to a screeching halt. Jason fought with the wheel to keep the car from pitching into a roll.
</p>
<p>
The Roadster slowed down and pulled into a tight U-turn.
</p>
<p>
The SUV’s passengers were thrown about as Jason rapidly reared the car up, maneuvering halfway through a three-point turn, pausing briefly in a position perpendicular across the road. The Roadster began to zip back towards them, ready to give chase in the opposite direction, back toward Tungsten.
</p>
<p>
Instead of completing the three-point turn, Jason turned the SUV in the same direction they had already been driving. The electric sports car whooshed past them. A series of “<em>pop-clack!</em>” sounds burst out as the SUV pulled away and the Roadster turned around again.
</p>
<p>
The small Asian guy in the passenger seat screamed at Tina, “Shoot back already!”
</p>
<p>
Tina realized she still had the Russian’s revolver. The mere existence of this small gun made her stomach lurch. It felt like an abomination, an obscenity cast in metal. “No,” she said flatly.
</p>
<p>
“Why the fuck not?” Moshen demanded.
</p>
<p>
“Have you ever shot a person before?” she countered.
</p>
<p>
The rear window of the SUV collapsed in a shower of glass. Danny screamed and ducked.
</p>
<p>
“Give me the gun,” Moshen insisted, stretching his hand. “I’ll do it.”
</p>
<p>
“Do you know how to use it?” she asked skeptically.
</p>
<p>
“It’s a gun. How hard can it be? It’s a point-and-click interface.”
</p>
<p>
A low “ploink!” sounded from the back of the car as a bullet chipped out a chunk of the rear bumper. 
</p>
<p>
Tina shoved the revolver into his hand, happy to get the evil little thing away from her. “Careful with it. It’s got a hell of a kick.”
</p>
<p>
The Asian kid leaned out the passenger window, trying to point the gun at the Roadster behind them. Jason helped him by turning sharply to the right, onto another dark side street. Moshen pulled the trigger.
</p>
<p>
Everybody in the car reflexively ducked at the overwhelming boom.
</p>
<p>
The thundering sound was immediately followed by the clatter of an object skidding across the cracked windshield and falling away onto the road.
</p>
<p>
Danny asked from the back, “What the fuck was that?”
</p>
<p>
“Nothing!” said Moshen defensively. “That was nothing!”
</p>
<p>
Jason answered, “That… was the gun.” 
</p>
<p>
The SUV tilted as Jason swerved around a car that had the misfortune of being on the same suburban road. The innocent bystander’s horn Dopplered behind them as Jason desperately sped down the street, the Russians in pursuit.
</p>
<p>
Jason shook his head. “I can’t out-drive them!” he said hoarsely. They watched helplessly as the Roadster drew closer. The SUV fell into tense silence amid the rush of air through broken windows.
</p>
<p>
“Hey. Wait a minute,” said Danny. “Guys. Do you hear that?”
</p>
<p>
“Hear what?” asked Moshen.
</p>
<p>
“The sound of their engine.”
</p>
<p>
They listened. 
</p>
<p>
“…No,” said Moshen. “It’s an all-electric drive train. They don’t <em>have</em> an engine.”
</p>
<p>
“Exactly,” Danny said. “Jason. Get us closer.”
</p>
<p>
Jason asked, “Closer?”
</p>
<p>
“Yeah,” said Danny. He peeked carefully over the SUV’s rear door, through the blown-out window. The Tesla Roadster was barely a hundred feet away. “Their car is about two square meters in frontal cross-section. What’s the radius of a sphere for which a 24-decibel gain covers two square meters of surface area?”
</p>
<p>
“How should I know?” Jason yelled back.
</p>
<p>
“Sorry, just thinking out loud,” said Danny. He checked the lights on his machine. 
</p>
<p>
“Seriously, Danny, what <em>is</em> that thing?” yelled Jason.
</p>
<p>
“It’s a HERF gun,” Danny answered.
</p>
<p>
“A Nerf gun?”
</p>
<p>
“High-Energy Radio Frequency,” said Danny. “Specifically, a directional High Power Microwave emitter, but HERF more generally. It produces 3-megawatt bursts of S-band radiation in 50-nanosecond…”
</p>
<p>
Jason barked, “Dude! Some other time!”
</p>
<p>
“Right. Sorry. Now let me think. One over ten to the two point four times four pi r squared…” Danny mumbled. His mouth kept moving even after words stopped coming out. Finally he said, “…About six poiiiint… Six point three meters.”
</p>
<p>
“What do you need me to do, Danny?” Jason shouted back.
</p>
<p>
“Let them get within about 20 feet without exposing me to their passenger side.”
</p>
<p>
“You got it. Hold on tight!”
</p>
<p>
Jason spun the wheel to the left, veering the car across the street’s divider into the oncoming traffic lane. He snapped the wheel straight again and slammed the brakes.
</p>
<p>
Danny, bracing himself against a seat, aimed his energy gun’s nozzle out through the broken rear window.
</p>
<p>
As Jason braked, the Roadster pulled up to within a few scant feet. Danny could see the face of the driver, the Russian whom Mike had nearly killed, illuminated by the SUV’s taillights.
</p>
<p>
Danny pulled the trigger. 
</p>
<p>
The Roadster’s headlights went dead. So did the motor.
</p>
<p>
Danny yelled over his shoulder, “Floor it!”
</p>
<p>
The suddenly unpowered Roadster, rolling along by sheer momentum, quickly receded into the distance as the SUV sped away. Screaming Russian curse words followed them briefly before fading into the night.
</p>
<p>
Once the Roadster disappeared in the rearview mirror, Jason finally released the gas pedal, dropping the SUV down to street-legal speeds. They drove calmly, heading toward downtown Bellevue. 
</p>
<p>
“Moshen!” Mike drawled. “Can we tally up our experience points now?”
</p>
<p>
Tina said, “This man needs to get to a hospital. Go to Overlake. It’s close.”
</p>
<p>
“No hospitals,” said Jason. 
</p>
<p>
“What?” said Tina.
</p>
<p>
“Hospitals will ask questions,” Jason said.
</p>
<p>
“Are you people serious?” screamed Tina. “He could slip into a coma!”
</p>
<p>
Mike asked warily, “Moshen…? How many hit points am I down to…?”
</p>
<p>
“I think you’re in the negatives, man,” Moshen replied.
</p>
<p>
Mike looked horrified. “I need Cure Light Wounds! Does anybody here know Cure Light Wounds?”
</p>
<p>
Jason asked, “Christina… It’s Christina, right?”
</p>
<p>
“Tina,” she corrected.
</p>
<p>
“Do you know anywhere we can take him without leaving any records?”
</p>
<p>
Mike said, “Of course she does. She’s a priestess. She knows Cure Light Wounds. None of you guys do. You’re all wizards. Wizards throw lightning bolts and fireballs. Priests handle life energies and heal people.”
</p>
<p>
His senseless words gave Tina an idea. “I <em>do</em> know a priestess, actually.”
</p>
<p>
“He doesn’t really mean…” said Jason.
</p>
<p>
“Head towards Swedish Medical Center, on First Hill,” Tina ordered.
</p>
<p>
“I said no hospitals!” said Jason.
</p>
<p>
“Stop spazzing,” Tina said. “I have a friend that lives there. She’ll know what to do.”
</p>
<p>
The Navigator drove in silence. Across the long straight bridge of State Route 520, over the moonlit waters of Lake Washington, the speckled lights and skyscraper silhouettes of Seattle’s nighttime skyline loomed before them.
</p>
<p>
“Guys, listen,” Tina said. “I just want to say, whatever this is all about… Thank you for getting me out of there. Really.”
</p>
<p>
“Hey, anytime! No problem!” said Danny, adjusting his shoulder. “I mean, my pleasure! Well, not really, but… uh…” He smiled shyly. “I like your hair.” 
</p>
</div>