<div class="chapsection">
<p>
<span class="caplead">The locals called it “Pill Hill”.</span> Home to four sprawling hospitals and the state blood bank, First Hill squeezed an entire city’s worth of medical care into one square mile of steeply sloped one-way streets. Beneath jumbled overpasses sat crumbling condominiums and tiny turn-of-the-century houses, with bars on the windows and multiple deadbolts on the front doors. Within many resided the kinds of people who took comfort in living near a state-subsidized methadone dispensary or trauma ward.
</p>
<p>
A bullet-riddled Lincoln Navigator parked in an unenforced tow-away zone did not look out of place.
</p>
<p>
“Has the bleeding stopped?” Natalie Rosenbaum asked upon opening her door. She was slightly taller than Tina, but considerably more girthy. She wore a purple UW School of Medicine sweatshirt, drawstring pants, and the demeanor of a battlefield commander.
</p>
<p>
“Mostly,” said Tina. “We couldn’t keep his nose pinched because of the swelling.” Mike’s nose looked like a red bulbous prosthetic glued onto his face.
</p>
<p>
Natalie’s apartment was an unholy catastrophe. It was strewn with medical books and pizza cartons and candles, and smelled of cat litter and dirty socks. Notebooks and crusty paper plates littered her coffee table next to her MacBook Pro. Above her TV, on an unpainted wooden shelf nailed into the wall, sat an authentic human skull, between psychiatry textbooks on one side and racks of herbs and jewelry on the other. A small stuffed-and-mounted snake crawled out of the skull’s eye socket, its forked tongue sticking out inquisitively.
</p>
<p>
“Come here. Sit down,” Natalie ordered Mike. 
</p>
<p>
With an annoyed meow, a small furry gray blur scurried away as the crew of strangers entered the living room.
</p>
<p>
Natalie cleared some space on her couch, sweeping aside a Pepsi bottle, a stuffed doll, and a bundle of twine. Mike sat down in a daze, the couch shifting under his weight. Natalie took a look at the back of his head.
</p>
<p>
Back by the doorway, Moshen started sniffling and sneezing furiously. “Oh God damn it, you have a cat, don’t you?”
</p>
<p>
“There’s Benadryl in the bathroom,” Natalie called over her shoulder.
</p>
<p>
Moshen eyed the piles of laundry and beaded jewelry he’d have to cross to reach the bathroom. He didn’t dare peek inside the bathroom itself.
</p>
<p>
Jason suggested, “Why don’t you head back down to the car, Moshen? All your laptops and things are still in there.”
</p>
<p>
“And my HERF gun,” said Danny.
</p>
<p>
“Yeah, and his Nerf gun,” repeated Jason. “Go make sure someone doesn’t just reach through the busted windows and take them.”
</p>
<p>
“No way, man!” said Moshen. “This hood’s all gangbangers and drug dealers. I ain’t sitting out there by myself!”
</p>
<p>
“I thought you said you know kung fu,” Jason teased, tossing him the keys to the SUV. Moshen hurried out the door, his sneezes receding down the hallway outside.
</p>
<p>
Natalie gave Mike some Tylenol and a glass of water. “Here, swallow these if you can.” She lifted the glass up to his mouth. Mike managed to comply.
</p>
<p>
She sat next to him and examined his eyes, then dropped her hand down to his wrist and felt his pulse. “Has he been having seizures?” she asked Tina.
</p>
<p>
“No,” Tina replied. “But he threw up once.”
</p>
<p>
Holding his fingers, Natalie asked, “Have his hands and lips been shaking like this the whole time?”
</p>
<p>
“I… I don’t know. I didn’t notice,” replied Tina.
</p>
<p>
The doctor looked into Mike’s eyes, puffy above his swollen furry cheeks, and asked, “Do you feel cold?”
</p>
<p>
“No,” answered Mike in a stuffy nasal drawl. “I feel warm. And my face hurts.”
</p>
<p>
“Tina,” said Natalie. “You said on the phone that he was in some kind of fight, right? How bad was it? Emotionally, I mean. Is this just someone shoving him in line at a bar somewhere and it got out of hand, or was he fighting for his life?”
</p>
<p>
Tina said quietly, “It was… bad.”
</p>
<p>
Natalie said to the large man, “What’s your name? Do you know where you are?”
</p>
<p>
Mike replied, “My name is Krongor. I’m a Level 5 Barbarian Warrior. We’re in the Blade Coast city of Salavina, near the Temple of Eir.”
</p>
<p>
Natalie’s jaw dropped. She turned to Tina with a bewildered expression. “Okay, I was not expecting <em>that</em>.”
</p>
<p>
“He’s delirious,” Tina said.
</p>
<p>
Natalie shook her head ponderously and looked back at Mike. “We’re near the Temple of <em>what</em>?”
</p>
<p>
“Eir,” said Mike. “Handmaiden of Frigga.”
</p>
<p>
Natalie’s eyes lit up and a wide smile overtook her face. She threw her head back and let out a loud, raucous laugh.
</p>
<p>
Jason asked with worry, “What’s going on? What’s so funny?”
</p>
<p>
Natalie kept laughing. “That’s brilliant!”
</p>
<p>
“Is he alright?” asked Jason. “Is he brain-damaged?”
</p>
<p>
“Eir! The Norse goddess of healing!” she said with delight. “And we’re down the street from Swedish Medical Center!”
</p>
<p>
Mike smiled.
</p>
<p>
She squeezed his arm and said, “Listen. My name is Doctor Natalie Rosenbaum. This is my apartment. You’re safe here. I know you’re hurt, you’re scared, but you’re going to be okay.”
</p>
<p>
He nodded slowly.
</p>
<p>
“I want you to close your eyes,” she said methodically, “and inhale slowly through your mouth. Hold your breath in… Good… And then slowly let it out. Focus on relaxing. Breathe in… This is a safe place. Nothing bad will happen to you here. And out…”
</p>
<p>
After a few repetitions, Mike opened his eyes. They were wet.
</p>
<p>
“What’s your name?” asked Natalie.
</p>
<p>
“Mike,” he answered. “Michael Braun.”
</p>
<p>
“Can you tell me where you are, Mike?” she asked softly.
</p>
<p>
“Yes. We’re on Pill Hill by Swedish Medical,” he said quietly. “In your apartment.”
</p>
<p>
“Very good, Mike,” she said.
</p>
<p>
“It’s a mess,” he added.
</p>
<p>
Natalie smiled bashfully.
</p>
<p>
Mike looked blankly over Natalie’s shoulder and said, “I haven’t forgotten.”
</p>
<p>
“Forgotten what, Mike?” she asked.
</p>
<p>
“That I’m going to die.”
</p>
<p>
“You’re not going to die, Mike,” Natalie said reassuringly.
</p>
<p>
“Yes I am,” he said. “We all do. ‘Remember to keep death daily before one’s eyes. <em>Memento mori.</em>’”
</p>
<p>
Natalie turned her head and followed Mike’s gaze. He was staring at the shelf above her TV, studying the grinning human skull with the taxidermic snake emerging from its eye socket.
</p>
<p>
“Mike…” Natalie asked with piqued curiosity, “What do you do for a living?”
</p>
<p>
“I protect the People of the Lowland Plains from the armies of the Orc King.”
</p>
<p>
“And when you’re not busy doing that?”
</p>
<p>
“I stock groceries at the Safeway in Queen Anne.”
</p>
<p>
“They teach you the Rules of Saint Benedict at the Safeway?” she asked with a wry smile. “Are your coworkers monks?”
</p>
<p>
“No,” he answered. “They’re fellow peasants.”
</p>
<p>
“That quote you just recited. That’s by Saint Benedict. Where do you know it from?”
</p>
<p>
“From the Wizard’s Compendium rulebook, in the chapter on Necromancy,” he answered. “It’s the caption under an illustration of a skull with a snake in its eye.”
</p>
<p>
“Do you know anything about Saint Benedict?” she asked.
</p>
<p>
“He was a Level 20 Priest?” said Mike.
</p>
<p>
Natalie hoisted her body back up to standing and navigated across the room. “Benedict is the patron saint of students and scholars. He’s the one who codified the rules that all monks live by. You’ve heard that monks take vows of celibacy, silence, and poverty, right? Do you know why?”
</p>
<p>
“To avoid sin through temptation,” answered Mike.
</p>
<p>
Natalie smiled. She took the skull from the shelf and headed back to the couch. “It’s actually deeper than that. The main purpose of the Rules of Saint Benedict is to remove the ego from the study of the divine. They get a monk’s mind out of its own way.” She sat down beside him. “See, Benedict knew that a curious mind is prone to self-sabotage. It learns something incompletely, and then moves on too quickly, trying to build more knowledge on top of an incomplete foundation. It thinks, ‘Yeah yeah, I get it. I know how this works,’ when it really doesn’t. The purpose of the Rules of Saint Benedict is to make sure that the monk is examining himself at every moment of his life, always checking his own assumptions, always seeking knowledge, never presuming to have any. Makes sense, right?”
</p>
<p>
“True knowledge begins in knowing that you know nothing,” Mike recited. “An unexamined life is not worthy of being lived by a human being.”
</p>
<p>
“You know Socrates!” Natalie said gleefully.
</p>
<p>
“Yeah,” said Mike. “I read tons of him and Plato and Aristotle when The Titans expansion pack came out for Age of Mythology.”
</p>
<p>
Natalie giggled.
</p>
<p>
There was no joy in Mike’s face or tone. Slowly, he reached toward Natalie and took the skull from her hands. He held it before his face and gazed into its eye sockets.
</p>
<p>
“I tried to kill a man tonight,” he said emptily.
</p>
<p>
The room fell silent.
</p>
<p>
“I almost succeeded.”
</p>
<p>
Danny said softly, “You saved our lives back there, man.”
</p>
<p>
Jason added, “Yeah, Mike. You did the right thing.”
</p>
<p>
Mike said nothing. In the quiet tension, Natalie scooted closer and put an arm around him. He leaned into the hug, welcoming the contact.
</p>
<p>
“Did I?” Mike finally replied. “Did I really? Because it doesn’t feel like it. I don’t feel righteous. I don’t feel like I won. Where’s my gold pieces? Where’s my experience points? Where’s that sense of accomplishment? You know… You know that feeling you get when you beat a big boss in a video game? It’s like this little burst of stuff that your brain squirts out, telling you, ‘Yay! You win! Good job! Whatever you just did, keep doing it!’ You know what I’m talking about?”
</p>
<p>
Natalie answered, “Heh, yes. That stuff is called dopamine.”
</p>
<p>
“Well, I’m not getting it,” said Mike. “I’m trying to make myself feel it, but it’s just not working. You know, I wish I could honest-to-God convince myself that this is all just some D&amp;D campaign. Because if it’s all just fantasy, then I can handle it. It’s all fun and exciting, and what I just did was epic and I should be proud of myself. But if it’s not, then…”
</p>
<p>
Natalie clapped her hand on Mike’s thigh. “Okay, big guy, listen up,” she said brightly. “I’ll take you to Swedish. They’ll fix your nose and give you a CT scan. I’m going to help you through this. I’ll personally make sure you’re okay. I need to go change, and then we’ll head out.”
</p>
<p>
She stood up from the couch and glided cheerfully toward her bedroom.
</p>
<p>
As she passed by, Tina heard her humming.
</p>
<p>
“Glad to see you’re happy,” Tina said with a trace of resentment.
</p>
<p>
Natalie responded in a sing-song whisper, “You failed to mention over the phone that this guy is <em>fucking awesooooome</em>!” She proceeded into the bedroom and rummaged through her closet. 
</p>
<p>
Tina followed and closed the door behind her. From the pile of blankets on the bed, a pair of feline eyes watched her. “Did I mention that I was almost kidnapped by the Russian mob tonight?”
</p>
<p>
Natalie giggled, “Sorry, T, I know I’ve been ignoring you. I…” She saw Tina’s eyes. Her face turned ashen. “Oh my god. You’re serious.”
</p>
<p>
“It’s been a busy night,” said Tina.
</p>
<p>
Natalie wrapped her ample arms around her friend. “What happened?”
</p>
<p>
“I’m still processing, honestly. One moment I’m was at work, bored shitless as usual. Next thing I know, some goon is waving a gun at me… Nat, if these guys hadn’t shown up, I’d be in a dungeon somewhere right now. Or dead.”
</p>
<p>
Natalie shook her head sagely. “First chance we get, T, we’re performing a rite of gratitude. No arguing! You owe it. Your guides brought you protection tonight &mdash; the least you can do is light a candle to acknowledge your good fortune. Besides… <em>I</em>, for one, am incredibly thankful that there was something or someone out there, looking out for my friend.” She turned her attention to the clothes littering her floor, and fished out a pair of black Spanx. “Is <em>that</em> who this Mike guy fought today?” Natalie’s voice was strained as she pulled the girdle over her hips. “A Russian hitman? And he <em>won</em>?”
</p>
<p>
“Damn it, Nat!”
</p>
<p>
“Sorry! It’s just… that’s… pretty cool.” She hoisted herself into a gray dress. “You’re telling me those doughy dweebs in my living room are actually an undercover ninja squad?”
</p>
<p>
That got a chuckle out of Tina. “Not exactly. They were total ass-clowns. It was like watching The Bourne Identity starring The Three Stooges. The other guy, the tall geeky one? He’s injured too. He’s lost blood &mdash; I think a bullet grazed his shoulder.”
</p>
<p>
“He looked a little pale, but I figured it’s just nerd-skin. I’ll check him out. He fought?”
</p>
<p>
“He was mostly a distraction,” said Tina. “He had this machine… It was like something out of a really low-budget sci-fi movie, all held together with Velcro and duct tape, like he built it himself.”
</p>
<p>
“Technogeeky. Sounds like your type.” Natalie examined her face in the mirror of an obscenely cluttered vanity and dabbed her face with foundation.
</p>
<p>
“Please. I don’t do old men,” said Tina.
</p>
<p>
“No, you don’t do <em>men</em> at all,” Natalie retorted. “You do boys. Besides, I know you. If you don’t find yourself a rebound, you’ll be giving Roger a drunken bootie call before you can say, ‘Walk of shame.’”
</p>
<p>
“Hey, I have more willpower than that!” Tina insisted.
</p>
<p>
Natalie shot her a look.
</p>
<p>
“Oh my god, shut up!” Tina suddenly got very interested in the sleeve of her cardigan, which was stained with Danny’s blood. She took it off and threw it into Natalie’s closet. “Nat, if I didn’t know better, I’d say you were pressuring me into hooking up with the first do-able guy to come along just so you can hear me tell dirty stories about someone besides Roger for a change. Maybe what you should be focusing on is creating some dirty stories of your own.”
</p>
<p>
Natalie crossed her arms. “Oh, we will have <em>none</em> of that, you hear? I’m the only clinical psychiatrist in the room, so I’ll be the only one doing any clinical psychiatrizing.”
</p>
<p>
“Oh, bam! I got a little truthy there, didn’t I?” Tina teased.
</p>
<p>
Natalie finished adjusting her dress and makeup. “How do I look?”
</p>
<p>
“Smashing. But your new crush is potentially brain-damaged, so he probably won’t notice.”
</p>
<p>
“You’ve still got keys, right?” asked Natalie. “Do you want to come with me to Swedish, or should I leave you here with your new boyfriend? There’s Jack Daniels in the pantry.”
</p>
<p>
“Subtle, Nat. Real subtle. I think I’ll stick around, but only because I want to see what’s all the fuss about this vial.”
</p>
<p>
Natalie reached into a drawer and pulled out a blood pressure cuff, a stethoscope, and a stopwatch. “You still remember how to use these?”
</p>
<p>
Tina nodded.
</p>
<p>
Natalie tossed the tools into Tina’s hands and shoved her out to the living room.
</p>
<p>
Jason had taken Natalie’s place beside Mike on the couch, keeping him engaged in light conversation. Danny waited quietly on a stool near the kitchen.
</p>
<p>
“Danny!” barked Natalie. “Take your clothes off.”
</p>
<p>
Danny jumped uneasily.
</p>
<p>
The girls approached him. Natalie circled him, carrying clothes and first aid, and pulled on a pair of plastic gloves. Tina stood by with the sphygmomanometer.
</p>
<p>
Hesitantly, Danny pulled off his flannel and t-shirt. They were caked with crusted blood. A three-inch-long gouge stretched across his left shoulder.
</p>
<p>
Natalie expertly cleaned the wound and dressed it in gauze and adhesive bandages.
</p>
<p>
Tina took Danny’s wrist and held his arm out so she could slide on the blood pressure cuff. Her fingertips traced the inside of his wrist. The rhythmic throb of his ulnar artery conveniently grew visible to her naked eye. She breathed on the end of the stethoscope to warm it, and carefully laid it against the inside of his elbow. “Hey,” she said to him. “You okay?”
</p>
<p>
“Me?” he answered with an overconfident smile. “Yeah, of course. Doing great! Why?” 
</p>
<p>
“Your pulse is racing.”
</p>
<p>
Natalie checked Tina’s numbers. “He’ll be fine,” said Natalie. “Drink some orange juice, eat some protein bars, and rest for a while.” She ruffled his floppy brown hair and said to him, “Think you can handle that?” 
</p>
<p>
Danny replied, “Mind if I raid your fridge?”
</p>
<p>
Natalie looked sheepish. “All I have is liquor and frozen pot pies. But there’s a Rite Aid on Madison and Summit. Walking distance. Tina will help you get there. Right, Tina?”
</p>
<p>
Tina scrunched her face at her. “Sure. No problem.”
</p>
<p>
Natalie took away his bloodied flannel. “Here. Wear this,” she said, shoving a wad of fresh clothes into his hands.
</p>
<p>
Danny held up a shapeless flower-print sweatshirt. “Thanks, Doc,” he said with equal parts sincerity and sarcasm.
</p>
<p>
Natalie sashayed back to the couch. “And now, as for <em>you</em>…” She reached out with both arms, took Mike by the hands, and helped him rise from the couch. “Ready to get your head examined?”
</p>
<p>
He didn’t answer.
</p>
<p>
“You’ll be okay, Mike,” she said quietly.
</p>
<p>
He nodded.
</p>
<p>
“Here, this will help.” She opened a closet near the front door, and rummaged inside. “Normally I’d give someone sedatives to reduce anxiety, but I don’t want to take chances with your head right now. What I <em>can</em> give you, though, is this.” 
</p>
<p>
She pulled out a large homemade woven bracelet of small yellow flowers, and wrapped it around his wrist.
</p>
<p>
With a fascinated expression, Mike said, “Mullein!”
</p>
<p>
Natalie’s jaw dropped. “You know what this is?”
</p>
<p>
Mike said, “I’ve never seen it in real life before.”
</p>
<p>
“Do you know what it does?”
</p>
<p>
“It grants the wearer a plus-four bonus on saving throws versus fear.”
</p>
<p>
Natalie hopped in place just a little bit.
</p>
<p>
Mike raised his wrist to his face and examined the charm. His eyes began welling up with tears. “Natalie…” he said in a cracking voice. “I really don’t feel very brave right now. I don’t feel like a winner. I just feel like… I just…”
</p>
<p>
Natalie regarded him sympathetically, gently reached her arms around him, and pressed her head against his chest. “It’s okay, Mike,” she whispered. 
</p>
<p>
He returned her embrace and bowed his head to rest atop hers. His chest shook several times silently. A series of coughing sobs rumbled forth, each one longer than the last, until they joined in a long wail. Loud, wet, gasping inhalations punctuated his bawling.
</p>
<p>
“It’s okay, Mike. It’s okay,” Natalie repeated, holding him tight. “Don’t be afraid to cry.”
</p>
</div>