<div class="chapsection">
<p>
<span class="caplead">Tina watched the entire carton of Tropicana</span> Orange Juice disappear down Danny’s gullet. He grabbed it off the shelf and nursed it right there in the dairy section, taking multi-gulp swigs and pausing only to come up for air. 
</p>
<p>
“You did not just chug that whole thing, did you?” she said.
</p>
<p>
“Oh man, that hit the spot,” Danny said with a contented sigh. He wiped his mouth with the sleeve of Natalie’s oversized floral-print sweatshirt. He scanned the brightly-lit aisles of the Rite Aid, absent-mindedly handed the empty carton to Tina, and made a bee-line for a promotional display of Clif Bars near the checkout counters.
</p>
<p>
“This thing is sixty ounces!” said Tina, reading the carton’s labeling as she followed.
</p>
<p>
“Mm-hmm,” said Danny dismissively as he tore into a Clif Crunchy Peanut Butter.
</p>
<p>
“A normal human bladder can only hold like twenty.”
</p>
<p>
Danny shrugged.
</p>
<p>
“You do realize,” she pointed out, “that you’re going to piss your pants in five… four… three…”
</p>
<p>
“Can’t pee right now,” he said with his mouth full. “Too busy eating.” He finished his snack in a matter of seconds and grabbed two more bars from the display. He held them up in each hand in front of Tina. “Hey, which one do you think is better for me right now? The Cool Mint Chocolate, or another Crunchy Peanut Butter?”
</p>
<p>
“How the hell should I know?” said Tina.
</p>
<p>
Danny shrugged. “I don’t know. You seem to know what you’re doing when it comes to, like, medical…, you know, biological, organic… doohickeys. I know they just have you working at this biotech company as an office admin, but you seem good at this stuff.” 
</p>
<p>
Tina was momentarily stunned into delighted silence. “Well,” she said with a smile, “I personally happen to be a fan of Cool Mint Chocolate…”
</p>
<p>
With exaggerated graciousness, he extended the package to her. “Join me for dinner?”
</p>
<p>
“Sure.” She half-sat against a closed checkout counter and peeled open the wrapper.
</p>
<p>
Danny ripped the Peanut Butter Crunch package open with his teeth and immediately bit off a chunk of the chewy protein bar inside. 
</p>
<p>
“You really love that Peanut Butter there, don’t you?” she mused.
</p>
<p>
“Mmmm…” he said while chewing. “It’s good, but… I could really use something to wash it down with. Maybe some OJ?”
</p>
<p>
She watched him scarf down his second Peanut Butter Crunch bar while she took her time with her Cool Mint Chocolate.
</p>
<p>
“So. Danny…” she said between slow bites.
</p>
<p>
“Hrmm?”
</p>
<p>
“Who the hell are you?” 
</p>
<p>
The question made him suddenly appear a bit sullen. He slowed down his chewing and stared at the floor. “I’m just a guy.”
</p>
<p>
“A tech wizard guy?”
</p>
<p>
“A failed one, maybe.”
</p>
<p>
“Aww. A genius computer hacker guy, then?”
</p>
<p>
“Heh, right. In some alternate reality.”
</p>
<p>
“So what kind of guy do you consider yourself to be?” she asked.
</p>
<p>
Danny thought for a moment. “I’m not really sure. I don’t really think about it much. I think I spend so much time thinking about who I’d <em>like</em> to be, or who I believe I’m <em>supposed</em> to be, that I never really think much about who I <em>am</em>.”
</p>
<p>
“And who do you believe you’re supposed to be?”
</p>
<p>
“Heh. I’m supposed to be an astounding technologist,” he said with an odd mix of confidence and bitterness. “I’m supposed to be Thomas Edison or Nikola Tesla. Or Bill Gates or Steve Jobs or Larry Page or Mark Zuckerberg. I’m supposed to be young and brilliant and everybody’s supposed to be in awe of my genius.”
</p>
<p>
Tina nibbled on her Clif Bar. “Hmm. So you’re saying you believe the world should revolve around you, then. Noted…”
</p>
<p>
“It’s not that I believe it <em>should</em>,” he said with a self-deprecating smile, “It’s just that I certainly wouldn’t complain if it did.”
</p>
<p>
Tina smiled back at him through another bite of her Clif Bar, her eyes twinkling. 
</p>
<p>
“All I mean,” Danny continued, “is that I want to be responsible for shaping the world I live in. Take something that’s inside me, in my mind, and use it to help define our reality. I feel like I was supposed to have done so a long time ago. I mean, I was in the right field at the right time. I had the right skills and the right talents. And now here I am, pushing forty, and I’m like, ‘What the fuck happened?’ Did I miss my exit on the highway or something? It’s like I’m off course. Like there’s this whole other life that I’m supposed to be living, right now, right this very minute, in some alternate reality… And instead I’m… here. Does that make any sense?”
</p>
<p>
Tina nodded slowly. “Yeah, it does. More than you know,” she said quietly. 
</p>
<p>
“So, what about you?” Danny asked. 
</p>
<p>
“What about me?” she returned, with a slight wiggle.
</p>
<p>
“How did you learn all about biotechnology? Did you, like, absorb it through osmosis at Tungsten or something? Um, no pun intended.”
</p>
<p>
Tina beamed. “I might have picked up a thing or two…” Her cheeks turned slightly rosy from the praise. “The truth is, the only reason I went to work at Tungsten was because it’s such a small company that I figured there’d actually be a chance they’d let the office admin migrate into a research position. It was a long shot, but it was worth taking.”
</p>
<p>
“So you’d intended to go into research from the start?” Danny asked.
</p>
<p>
Tina nodded. “I studied microbiology in college. I wanted to work on cures for infectious diseases. You know, like MRSA or antibiotic-resistant tuberculosis.”
</p>
<p>
Danny blinked. “They have you working as a receptionist with a degree in microbiology?”
</p>
<p>
Tina looked away as her face saddened. “I never finished. My junior year, my dad got really sick…”
</p>
<p>
Danny ventured, “Tuberculosis?”
</p>
<p>
Tina shook her head. “That would be one hell of a poetic twist, wouldn’t it? But no. Early-onset Parkinson’s. Very rapid progression. I moved back here to Seattle to help take care of him. And my mom had a really hard time coping, especially after he passed away… So, yeah, when you talk about life veering you down a track you hadn’t intended…”
</p>
<p>
“Especially when that track involves Russian hitmen,” Danny added.
</p>
<p>
Tina shuddered. “Yeah. God. The less of those I have to see from now on, the better. You know, it’s bad enough that the guy held me at gunpoint and tried to drag me off to his hideout or whatever… but you know what <em>really</em> upset me? The guy was texting on his cellphone the whole time!”
</p>
<p>
Danny laughed. “<em>That’s</em> what upset you? Him texting while he was supposed to be giving you his undivided attention?”
</p>
<p>
“Well, no, not really; I was, in fact, just a <em>little</em> more upset about the gun,” Tina said with a smile. “But still. How <em>rude</em>! Right?”
</p>
<p>
Danny suddenly lit up. “Oh! Speaking of that phone! Do you still have it?”
</p>
<p>
“What, the Russian’s cellphone?” Tina said. “Yeah, but it’s locked.”
</p>
<p>
Danny smirked. “Oh really?”
</p>
<p>
“Yeah. I checked it on our way to Nat’s place. You need a password to get into it.”
</p>
<p>
Danny laughed. “We’ll see about that.”
</p>
<p>
Tina reached into her purse and fished out the Russian’s phone, a slim device with a squat screen and a full QWERTY keyboard. 
</p>
<p>
Danny took it with an evil gleam in his eye, and examined it carefully. “I bet you think this is a BlackBerry, right?”
</p>
<p>
Tina shrugged.
</p>
<p>
“Well it’s not. This is a Pantech. AT&amp;T sells them as part of a GoPhone package &mdash;where you can pay cash up front and your name never shows up on any phone records. In other words, this is a disposable phone. And it’s a good one for the price, really. Supports MMS, BlueTooth, email, web browsing, GPS…”
</p>
<p>
“So what can you do with it?” Tina said, skeptical but eager.
</p>
<p>
Danny pressed the phone’s Power key. The screen greeted him with a picture of a tall rectangle with one clipped corner, with a gold square in the middle. A prompt read, “PIN Code”, with an empty box awaiting a number.
</p>
<p>
“Plenty,” he said with a sinister grin. “See, there’s basically two different ways to lock a SmartPhone like this. The lock can apply either to the phone itself, or to the removable SIM card inside it. Locking the phone protects all of the data stored on it &mdash; emails, photos, contact lists, that kind of thing. Locking the SIM prevents charges to the phone number &mdash; like voice minutes, text messages, and data usage. Now, our Russian friend here chose to lock the SIM, which means we can’t use this phone for placing calls pretending to be him. What we <em>can</em> do, though, is this…”
</p>
<p>
He flipped the phone over, unlatched the rear cover, and pried out the battery. Behind the hollow space sat a small plastic card about the size of a thumbnail, rectangular with one clipped corner. The card was white with blue and orange markings reading, “AT&amp;T Go”. “Yeah, thought so,” Danny said. He pulled the small card out of its slot, revealing a gold square embedded in its underside. “He won’t be needing this anymore…”
</p>
<p>
“That’s the SIM card, right?” Tina asked.
</p>
<p>
“Yeah,” said Danny as he slid the small piece of plastic into his pocket. “It tells your phone who you are. It holds the Subscriber Identity Module &mdash; basically a tiny little computer built right into the card. The microchip stores a secret code called your IMSI &mdash; your International Mobile Subscriber Identity. Your cellular service provider, like AT&amp;T, links your IMSI to your account information &mdash; what your balance is, how many minutes you have left this month, that kind of thing. It’s a clever little system that lets customers upgrade their phones while still keeping the same phone number &mdash; you just pop your SIM card out of one phone and into another, and your phone number and account info go where the SIM goes.”
</p>
<p>
“So, all cellphones have one?” Tina asked.
</p>
<p>
“Well, no,” Danny answered. “It depends on the kind of cellular technology they use. SIM cards are currently specific to GSM. My own phone is on Verizon, which uses CDMA, so it doesn’t have SIM capabilities yet. But yours… You’ve got an iPhone, right?”
</p>
<p>
“Yeah…” she said hesitantly.
</p>
<p>
“On AT&amp;T?”
</p>
<p>
“Maybe…”
</p>
<p>
“Sweet.” He reached his hand out and made grabbing motions. “Gimme.”
</p>
<p>
“What are you going to do to it?” she asked with a trace of dread.
</p>
<p>
“Nothing too terrible, I promise,” he said unconvincingly.
</p>
<p>
She reluctantly handed him her iPhone. “I really hope you know what you’re doing.”
</p>
<p>
Danny scanned the aisles of the Rite Aid. “Now, I just need…” Suddenly, still holding on to both cellphones, he jumped away from the checkout counter and made a quick dash for an aisle of stationery and school supplies.
</p>
<p>
“Hey! Where are you going with my phone!” Tina demanded.
</p>
<p>
Danny hopped back to the counter. “…this!” he said, and triumphantly held up a partially unbent paper clip.
</p>
<p>
“I don’t think I like where this is going,” Tina said.
</p>
<p>
“It’s okay,” Danny said smoothly, turning Tina’s phone around in his hand. “Everything will be juuuuust…” 
</p>
<p>
He found a tiny, almost invisible hole along the edge of the iPhone. Tina watched in fascinated horror as he took the unwound end of the paper clip, brought the tip to the small round opening, and thrust it deep inside. The paper clip hit a latch mechanism. With a click, a thin plastic cartridge slid out from a nearly invisible seam. 
</p>
<p>
“…fine!” Danny said triumphantly.
</p>
<p>
Tina felt violated by proxy.
</p>
<p>
Danny withdrew the cartridge from Tina’s iPhone. Clipped onto it was a SIM card, almost identical to the one that came from the Russian’s Pantech.
</p>
<p>
Tina eyed him warily. “You’re going to put everything back together again when you’re done, right?”
</p>
<p>
Danny smirked, and inserted Tina’s SIM card into the Russian’s Pantech. He put the Pantech’s battery and rear cover back into place, and powered on the device.
</p>
<p>
“Booyah! Victory!” he announced.
</p>
<p>
“Holy shit! You got it?”
</p>
<p>
Danny waved the phone in the air triumphantly. Its screen showed a menu of application icons, overlaid with a status message indicating seven missed calls.
</p>
<p>
Tina nodded approvingly. “Not too bad,” she said with a coy grin.
</p>
<p>
“Oh, I’m just getting started,” said Danny. “Now comes the <em>really</em> fun part: figuring out as much about this Russian guy as humanly possible. Let’s start with all these calls he missed… Hmm. They’re all from some guy who’s just listed as ‘Sergey’ in this dude’s address book. We have his number. Want to prank-call him?”
</p>
<p>
Tina giggled. “Let’s, um, not.”
</p>
<p>
“Agreed,” said Danny. “Okay, let’s see what else we’ve got. Who else is in his address book? Hmmm… we have a Natasha… an Olga… a Tonya… a Malia… a Yulia… I’m beginning to see a pattern here. Oh hey! They’ve got photos!” His jaw almost hit the floor. “…Whoah! Not safe for work!”
</p>
<p>
Tina couldn’t see the screen. “You want to share?” she asked suggestively.
</p>
<p>
“Uh, maybe some other time?” Danny replied with a blush of adolescent nervousness.
</p>
<p>
“What else can you find on there?” Tina asked.
</p>
<p>
“Oh, tons,” he said. “This thing’s a damn goldmine. He’s got his email on here. Most of the messages are in Russian. We can run them through Babelfish later. In the meantime, here’s some Groupon deals… A newsletter from Key Arena… An Evite to a bachelor party… A gym membership renewal notice… A Facebook alert message for friends with birthdays coming up…”
</p>
<p>
Tina shook her head in bewilderment. “This is so fucking unreal. The guy who held me at gunpoint has a Facebook account? And friends with birthdays and weddings?”
</p>
<p>
“Seems like it. Oh hey, this could be good. Check this out. ‘To: Eugene Mukhayev. From: Wells Fargo Online. Wells Fargo Online Statement Ready to View.’”
</p>
<p>
Tina laughed incredulously. “No way! You can see his bank statements?”
</p>
<p>
“Naw. The Wells Fargo website is making me sign in with a username and password. I don’t have either one. But… How much you want to bet this guy uses a life password?”
</p>
<p>
“A ‘life password’? What’s that?” Tina asked.
</p>
<p>
“It’s the password that unlocks your entire life. People have a thousand online accounts, right? And they always use the same damn password for everything they do. All it takes is for one website to mis-handle your password, and your whole life is wide open. Everybody does it. Take you, for example. I’m willing to bet you do it too. Your Facebook password, your bank password, your password for your corporate email at work. Admit it. They’re all the same, aren’t they?”
</p>
<p>
Tina stared at him in horror. “Not… necessarily…!” she squeaked. She suddenly felt as though she were standing completely naked in front of him.
</p>
<p>
Danny chuckled, and began rapidly thumbing the Pantech’s keyboard. “All I have to do is go through these websites that he gets these emails from, and request a password reset. They make it easy &mdash; a link to the website is usually the first thing in the email, and on most websites the ‘Forgot Password’ button is right under the login prompt. Evite… Bam… Meetup… Bam… Groupon… Bam…” 
</p>
<p>
As he continued digging through the email, the Pantech started emitting small blipping noises. “Ah, here we go,” said Danny. “The password reset emails are coming in… See, proper password handling protocols demand that a website never, ever send a password in plaintext. In fact, a website shouldn’t even store your password on their servers… But every now and then… you get a website that… Ah, here we go! …That does shit like this…” He turned the phone’s screen toward Tina. 
</p>

<pre class="computer">
From: customerservice@efitnessgym.com
An e-mail with your password 
has been sent to: eugene@pash.ly

Dear Eugene Mukhayev (zhenkamu78),
You have requested your user name/password for your 
eFITNESS Power Gym account. Please find this information 
below.

<strong>
Username: zhenkamu78
Password: pizdets69!
</strong>

Thank you for using our services,
The eFITNESS Power Gym Team 
</pre>

<p>
“See that?” Danny said. “All it takes is one. Now, think those credentials will work on his Wells Fargo account? Copy… paste… and…” Danny again turned the screen toward Tina. 
</p>
<p>
The screen showed a Wells Fargo account management web page. Below the title banner and greeting text was a list of several bank account numbers with summaries, each one showing a six-figure balance. Buttons on the page offered the ability to view transaction histories, pay bills, perform wire transfers, request loans, and generally wreak havoc.
</p>
<p>
“Mmmmmmwhah! Goodnight, folks!” said Danny.
</p>
<p>
“Dude,” Tina said slowly. “You did not!”
</p>
<p>
“I did!” he said with an enormous, cocky smirk.
</p>
<p>
“You just hacked the Russian mob,” she said, grinning in incredulity.
</p>
<p>
“Uhhhhh, kinda sorta, yeah.”
</p>
<p>
“Using nothing but the dude’s cellphone!”
</p>
<p>
“Yup.”
</p>
<p>
“…Hot,” she said slyly, slightly lowering her head. She self-consciously ran her fingers through her hair, fully aware that it was a total mess. Her eyes stayed trained on him, looking upward, meeting his gaze. She smiled flirtatiously, nibbling ever so slightly on her lower lip.
</p>
<p>
Danny stepped toward her. He placed the Pantech into her hand, the skin of their fingers brushing against one another. “Tina. I want to ask you something.” His breathing palpitated with tension and urgency.
</p>
<p>
“Go ahead,” she said eagerly.
</p>
<p>
“Does this Rite Aid have a bathroom? ‘Cuz I have to take one massive leak.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Danny came back to find</span> Tina still at the register, with the empty OJ and the pile of Clif Bar wrappers in the basket beside her. She was holding the Eppendorf tube up to her eyes, scrutinizing it very closely.
</p>
<p>
“I know what you’re thinking,” said Danny, “and the answer is: Yes, I <em>can</em> use that to make a teeny tiny little lava lamp.”
</p>
<p>
“Danny, look at this…” she said, fascinated.
</p>
<p>
He moved his face next to hers. Together, they stared intently at the vial of translucent brown slime. The smiley face sticker on the side of the vial stared back at them.
</p>
<p>
“What am I supposed to be seeing?” he asked.
</p>
<p>
 “It’s not goopy inside,” she said, shaking it. “I think it’s crusty.”
</p>
<p>
“So?”
</p>
<p>
“Danny, do you still have that paper clip?”
</p>
<p>
He handed it to her. She straightened the clip into a long metal wire. “We need to sterilize this,” she said. With vial and unbent paper clip in hand, she marched back into the store, retrieving another shopping basket on the way.
</p>
<p>
Danny followed her to the Emergency and First Aid aisle. Her first move was to find a box of latex gloves. She tore the box open and pulled one powdery white glove onto her hand. 
</p>
<p>
She then grabbed a small bottle of rubbing alcohol and set it down on an empty shelf nearby. She dipped the unbent paper clip into the sharp-smelling liquid and held it there, letting it soak. Danny heard her counting time under her breath. She repeated the process with each finger of her latex-gloved hand, drying them off with a few brisk shakes through the air. “Good enough,” she mumbled.
</p>
<p>
With her tools and her fingers adequately cleaned, she popped open the top of the Eppendorf tube and dipped the tip of the paper clip into the vial. It made a hard scratching sound. When she was done, she pulled the paperclip out of the tube and examined it closely. 
</p>
<p>
The pale brown goo had congealed into a hard resin that clung to the paper clip in large crusty yellow flakes. Looking at it, Danny was reminded of something a dentist might scrape off of the back of someone’s teeth.
</p>
<p>
“Is it supposed to do that?” Danny asked.
</p>
<p>
“Only when they’re scared shitless,” Tina replied, closing the tube.
</p>
<p>
“Who’s ‘they’?” Danny felt clueless.
</p>
<p>
“The <em>E. coli</em> bacteria,” Tina answered, staring at the yellow-white crust on the tip of the paperclip. She gently transferred the flake to her latex-gloved index finger, and held it inches from her eye, holding her breath as she studied the substance.  
</p>
<p>
“You can tell what mood they’re in?”
</p>
<p>
Tina pinched the grain between the thumb and forefinger of her gloved hand. She used her other hand to roll off the glove, turning it inside out, holding the pinch the whole time. When it was finally off she gave the latex several twists and knotted it off near the base of the digits. The yellowish flake remained sealed in the glove’s inverted surface.
</p>
<p>
“They’ve locked themselves into a biofilm,” Tina said. 
</p>
<p>
Danny shrugged dumbly.
</p>
<p>
“It’s like they’re circling their wagons,” she said. “It’s a cooperative emergency defense mechanism. A lot of strains of bacteria, when they feel like they’re in danger, they start to exude this thick mix of starches and proteins. A bacterium starts cranking this stuff out when it senses it’s dying. When nearby bacteria feel their neighbors spewing this stuff, they start to spew it too, so the entire colony hides inside a massive layer of sticky crust. It’s like they make a little fort. And once they’re inside, they go into a natural suspended animation. They basically shut down all their life processes except for the barest essentials, and sit there and wait for the threat to pass.”
</p>
<p>
“That crusty stuff is a panic room for germs?” said Danny.
</p>
<p>
“Exactly,” said Tina. “They must’ve started forming it when they came out of the freezer and woke up to find themselves in glycerol solution.”
</p>
<p>
“So what’s it mean for us?”
</p>
<p>
“It means,” said Tina, looking closely at the vial, “that they’re still alive. They’re terrified out of their little wits, but they’re still kicking.”
</p>
<p>
“How long can they stay like that?” Danny asked.
</p>
<p>
“Oh, once they lock themselves inside a plaque like this, they can stay there for pretty damn long. The trick is waking them up and convincing them it’s safe to come out.”
</p>
<p>
“Can that be done?”
</p>
<p>
Tina looked around, taking stock of the drugstore. With a gleam in her eye, she said, “Let’s see what I can do!” She put the tied-off latex glove and the rubbing alcohol into the shopping basket, and scanned the shelves of the First Aid aisle. She found a cheap digital oral thermometer and added it to her cache. “We’re going to make us some lysogeny broth. See if you can find a Pyrex bowl. At least a quart. With a lid. And grab a measuring cup. And an oven mitt. If we’re lucky, Nat might find us an autoclave at the hospital. If not, we’ll just take our chances with her stove. Lord knows it’s never been used for cooking.”
</p>
<p>
“Uh… Sure! Yes! Okay!” Danny replied. He sensed that something technical was happening, but it was so far outside of his domain of expertise that he felt like a total layman. He hadn’t felt like that in a very, very long time. He found himself liking it. Or more specifically, liking being made to feel this way. Or more specifically still, being made to feel this way by her. He set out toward the kitchenware section and gathered Tina’s spell components.
</p>
<p>
When he finished, he found her in a nearby aisle. He dropped his materials into her basket. “What else do we need for this soup recipe?”
</p>
<p>
“Lysogeny broth,” she corrected. “We’ll need salt, tryptone, and yeast extract.”
</p>
<p>
“You’ve done this before, haven’t you?” he asked.
</p>
<p>
Tina blushed. “It’s easier than it looks. The trick with biology is that these things <em>want</em> to work by themselves. Living things are self-correcting. It’s called homeostasis. If you have a biological process and something goes wrong, it usually breaks in a way that compensates for the damage.”
</p>
<p>
“Yeah, in engineering we call that a robust failure mode,” said Danny. “It’s a form of fault tolerance. If a component fails, the other components of the system not only compensate for the failure but actually help get the failed component working again.”
</p>
<p>
“Yeah. In nature, everything’s built that way,” said Tina. “Left to its own devices, biological systems always find a way to make things work. Life’s a lot less fragile than most people think. Humans have been building machines for about five thousand years. Cellular life has been self-replicating for about three and a half billion. It’s probably doing something right.”
</p>
<p>
Danny felt both inspired and intimidated. “So, those other ingredients…” he said, deflecting his attention to the task at hand. “I know what table salt is. The other two… Um, is there a Lab Chemicals aisle here?”
</p>
<p>
“They’re just fancy names for bacteria food,” said Tina. “Lysogeny broth is a mixture of fairly common stuff that happens to be super nutritious for a growing young bacterial colony. Yeast extract is rich in glutamates for building new proteins, and nucleotides to give the bacteria raw materials for replicating their DNA. And the other stuff, tryptone, that’s just a big pile of amino acids that come from the breakdown of dairy proteins… Whaaat?” she suddenly asked him self-consciously.
</p>
<p>
“What what?” Danny asked, bewildered.
</p>
<p>
“You’re looking at me like you want to say something,” she said.
</p>
<p>
“Heh, it’s nothing. I’m just… impressed.” She met his gaze again with a look that cut his breath short &mdash; her unkempt black hair falling around her face, her dark eyes looking mischievously at him. Her tiny nose stud glinted in the bright fluorescent light. “So. Amino acids, right?” he said abruptly. 
</p>
<p>
“Yeah…” she said.
</p>
<p>
“I have an idea. Follow me.” He led Tina to the Diet Supplements aisle. There, amidst white bottles filled with pills of calcium and zinc and vitamins, were tubs of powdered bodybuilding formulas, with names like “Cyto Gainer”, “Muscle Milk”, and “Amino Fuel”.
</p>
<p>
Tina nodded gleefully. “Danny, you’re a freakin’ genius!” She picked up a tub labeled “Complete Casein”. “Ohhhhhhhh man, they are going to love this shit!” she said as she read the nutritional information on the back. She took the vial in one hand and wiggled it toward the tub, saying, “Right, little guys? You want some casein? Some nice tasty casein? Yes you do! Oh yes you do! And maybe some B-complex gel-caps? Yeah? Good little <em>E. coli</em>!”
</p>
<p>
Danny smiled warmly at her antics.
</p>
<p>
“Sterilization is going to be really tricky, though,” Tina mentioned pensively. “There’s all different kinds of bacteria around us all the time &mdash; in the air, in the water, everywhere. If any random bacterium gets into the lysogeny broth, it’ll multiply in there along with our <em>E. coli</em> strain, and it’ll compete for the broth’s nutrients. Normally, when people do this in a lab, the <em>E. coli</em> is intentionally given resistance to some specific antibiotic, and the lysogeny broth is infused with that antibiotic, so only our strain can survive in there. We can’t do that here because we don’t know what antibiotic these guys were bred to be resistant against, if any. But if we’re lucky…”
</p>
<p>
He listened to her talk, reeling with admiration. She stood in the aisle, shopping basket in one hand, purse in the other. Hair dark and haphazard. A small, unassuming stud glinting on the side of her nose. And a gleam of competent determination in her eyes.
</p>
<p>
She paused for a moment. “Hey Danny.”
</p>
<p>
“What?”
</p>
<p>
“You’re looking at me like that again,” she said with a tone that made it clear that she rather liked it.
</p>
<p>
His mind filled with a thousand possible responses. 
</p>
<p>
He mustered up his deepest reserves of confidence, leaned toward her, and said suavely, “Yeah, I am. What are you gonna do about it?”
</p>
<p>
“I was actually wondering,” she said as she took a step toward him and looked up into his eyes, “if <em>you’re</em> going to do something about it.”
</p>
<p>
He reached his hand out and placed it on the smooth curve of her waist to pull her closer. She eagerly pressed her body against his. The feel of her toned midsection hit his veins like a shot of opium, sending his head spinning in blissful delirium. He drew his lips down toward hers. She reciprocated, reaching up to slide her hand across the back of his neck, and guided his face down to meet hers.
</p>
<p>
He watched himself kissing her in an out-of-body experience, the camera of his eye circling around them. The Rite Aid’s muzak became a punk-pop love ballad. Bystanders started applauding. The credits rolled, and they lived happily ever after.
</p>
<p>
None of that happened.
</p>
<p>
She had said, “You’re looking at me like that again,” with an inviting smile, her bright eyes looking expectantly at him. He knew he should act. He told himself to act. But he found himself merely standing idly like a dunce, feeling the moment slip away.
</p>
<p>
The awkward tension was broken by an explosion of noise from Tina’s purse. 
</p>
<p>
They both looked in surprise at the bag. From the purse flowed music &mdash; a tinny pop song sung in a foreign language.
</p>
<p>
Perplexed, Tina quickly rummaged through her purse.
</p>
<p>
“Oh. Heh. It’s that Eugene guy’s cellphone,” she said. “That’s his ring tone. Check it out.” She held the phone so Danny could see the screen lighting up with, “<span class="computer">Sergey</span>”.
</p>
<p>
Danny’s eyebrows furrowed in confusion. “Uh, no… That can’t be right…”
</p>
<p>
“Why?” she asked innocently. “What’s wrong?”
</p>
<p>
“I get that the phone would recognize the incoming number and display the contact’s name…” Danny said, mostly to himself. “But how would it… Tina, you didn’t put the… thing in the thing… did you?”
</p>
<p>
“The what?”
</p>
<p>
Danny reached his hand into his pocket. He felt the small SIM card he had pulled from the Russian’s cellphone. His face went ashen.
</p>
<p>
“Jesus, Danny, what is it?” 
</p>
<p>
“Your SIM card’s still in that phone,” he said in horror.
</p>
<p>
The music stopped.
</p>
<p>
“So?” she asked.
</p>
<p>
“The SIM determines the phone’s subscriber account,” said Danny. “Your phone number goes where your SIM goes.”
</p>
<p>
Tina stared at the phone. “Wait. Wait a minute. So what you’re saying…”
</p>
<p>
The music started again.
</p>
<p>
“This Sergey guy isn’t calling Eugene,” said Danny. “He’s calling <em>you</em>.”
</p>
<p>
The blood left Tina’s face. As the phone continued ringing, she just stood there looking at it with wide eyes, not moving, not breathing.
</p>
<p>
Finally, she decided to press a button. The music stopped.
</p>
<p>
Slowly, she brought the phone up to her ear and trembled out, “Hello?”
</p>
<p>
Danny could only barely hear the other side of the conversation. He could make out a male voice with a foreign accent.
</p>
<p>
Tina said into the phone, “I’m… I’m sorry.”
</p>
<p>
The voice said something in response.
</p>
<p>
“No,” Tina replied meekly. “I haven’t gone to the police yet.”
</p>
<p>
The voice spoke again.
</p>
<p>
 “Yes, I still have it,” she said. “But it’s thawed out, and…”
</p>
<p>
The voice cut her off. 
</p>
<p>
“Look, you can <em>have</em> it for all I care,” said Tina. “I have zero interest in…”
</p>
<p>
The voice interrupted her.
</p>
<p>
“No, I didn’t swap it!” Tina protested. “Or contaminate it, or damage it, or…”
</p>
<p>
The voice barked something at her.
</p>
<p>
“Proof? Um, I promise?” Tina offered. “What kind of proof do you want? I don’t…”
</p>
<p>
The voice grumbled.
</p>
<p>
“What? No! I can’t…” Tina insisted. The voice responded. As it talked, Tina gasped and began to cry. “No! Please, you don’t have to…”
</p>
<p>
The voice said something.
</p>
<p>
Tina choked on a scream. “…I understand,” she whimpered.
</p>
<p>
The voice made a few statements.
</p>
<p>
“I…” She paused for a long time. Finally, emptily, she said, “Okay.” 
</p>
<p>
The voice issued a gruff response. Then, after a pause, it said something else.
</p>
<p>
Tina looked up at Danny. She slowly pulled the phone away from her ear and extended it out to him. “He wants to talk to you,” she whispered.
</p>
<p>
Danny blinked. “To <em>me</em>?”
</p>
<p>
Tina nodded slowly, her eyes blank.
</p>
<p>
“How the hell…?” Danny protested.
</p>
<p>
“He said he wants to speak to the man with the electric gun.”
</p>
<p>
Danny took the phone from her. “…Hello?”
</p>
<p>
The voice, deep and resonant, said, “I understand you are responsible for interrupting our operation and damaging my men’s equipment.”
</p>
<p>
Danny took in a sharp, aggressive breath. “What do you want?” he said tensely.
</p>
<p>
“For start,” said the voice, “you owe me new Tesla Roadster.”
</p>
</div>