<div class="chapsection">
<p>
<span class="caplead">Pain enveloped Mike like a cocoon,</span> robbing him of all sense of time or direction. He felt like he was floating in the dark womb of some alien beast. He sat propped up in his hospital bed, covered in gauze, with Moshen and Natalie at his bedside keeping him awake. The pain sent his mind reeling, almost like a drug. The agony was borderline euphoric.
</p>
<p>
“It’s your endorphins kicking in,” Natalie said. “They work on your brain like morphine. That’s where the word ‘endorphin’ comes from, you know &mdash; ‘endogenous morphine.’ It’s basically natural heroin. Your body’s protecting itself. Making the damage easier to bear.”
</p>
<p>
“Natalie…,” he asked. “Why are you being so nice to me? We just met.”
</p>
<p>
“Yeah, but I… Uh… You seem pretty cool,” she said, blushing.
</p>
<p>
A shadow on the other side of the privacy curtain stole Natalie’s attention. A few distressed voices approached. Mike recognized one of them as the girl from the Tungsten building: Tina. She was sobbing.
</p>
<p>
“They know everything about me, Nat,” she was saying, her voice froggy. “They busted into my car. It was still sitting in the Tungsten parking lot. They got the registration and insurance papers and whatever else was in there. They know my address, my phone number, my Social Security Number…”
</p>
<p>
Danny materialized beside her, carrying plastic bags. “Jason… I… I’m gonna need hazard pay.”
</p>
<p>
“What the hell is going on?” Jason said.
</p>
<p>
“The Russians called Tina,” Danny answered.
</p>
<p>
Tina said meekly, “They want me to help them incubate the stuff in the Eppendorf tube. They told me to meet them at my apartment in one hour, ‘or else.’”
</p>
<p>
“They think you can incubate it for them?” Jason asked.
</p>
<p>
“Yes. Geez. It’s just <em>E. coli</em>. The incubation part is easy,” Tina said. “It’s figuring out what to <em>do</em> with them once they’re grown that’s the hard part. You incubate it, you get a warm tub of goo. Great. What do you do with <em>that</em>? The only person who knows that, is Julie.”
</p>
<p>
“Julie Yen?” Jason asked.
</p>
<p>
Tina eyed him suspiciously. “How do you know Julie?”
</p>
<p>
“Christina, is Julie working for these Russians?” Jason asked.
</p>
<p>
“I don’t know. When that guy was holding me at gunpoint, he implied that she’s not exactly with them willingly.”
</p>
<p>
“And they’re trying to threaten you into ending up like her?” Jason asked.
</p>
<p>
Tina nodded weakly.
</p>
<p>
Jason rolled his eyes. “Pffft. Amateurs.”
</p>
<p>
“Come again?” Tina squeaked.
</p>
<p>
“Listen,” said Jason. “You hold more cards than you think. A party only resorts to threats if they have nothing of value. If the first instinct of these Russians is to go straight for your jugular, then they’re approaching the negotiation from a position of weakness.”
</p>
<p>
Tina stared at him incredulously. “You’re saying the mob is in a ‘position of weakness’?”
</p>
<p>
“Oh, absolutely,” said Jason. “Think about it. They’re a criminal organization that’s at constant risk from both rivals and law enforcement. They have a lot to lose. Believe me, this stuff I know. I may be out of my league when it comes to tech, but they do teach us something in business school.”
</p>
<p>
“We’re not dealing with a business here!” Tina cried. “We’re dealing with the mob!”
</p>
<p>
Jason smiled. “What do you think the mob is? Whatever else may be true about them, they’re rational players. They have to watch their bottom line. I didn’t get rich by playing the lottery, you know. I made my money by understanding what people want. So let’s try and understand these guys. What do we know about them? What can we deduce about their needs, their risks, their motivations? Anything?”
</p>
<p>
Danny handed a cellphone to Jason. “I know a thing or two about them.”
</p>
<p>
Jason looked at the small screen, perplexed at first, then excited. Moshen looked over enthusiastically. Mike craned his neck. Hoots and high-fives were exchanged.
</p>
<p>
“A lot of the emails are in Russian,” said Danny. “Could you guys run them through an online translator?”
</p>
<p>
Moshen took the phone. “No problem, Danny,” he said, and twirled back to his laptop.
</p>
<p>
Jason nodded. “We’ve got them by the balls and they don’t even know it. Christina, I can get you out of this. Do you trust me?”
</p>
<p>
“I don’t have much choice, do I?” she replied.
</p>
<p>
Jason extended a hand, palm up. “The vial, please.”
</p>
<p>
She shot him a look of suspicion so hot it could’ve ignited his gelled hair.
</p>
<p>
“It’s either me or the Russians.”
</p>
<p>
She grudgingly pulled the vial out of her purse and put it in his palm. Jason’s fingers curled around it like the fronds of a carnivorous plant. 
</p>
<p>
Jason turned to his team. “Moshen. What have you been able to learn so far from that phone?”
</p>
<p>
“Not a ton,” Moshen replied. “There’s as much English and Spanish as there is Russian in these emails. And my Spanish sucks, and the English is really, really bad English. It’s all ghetto slang and innuendoes.”
</p>
<p>
Jason nodded knowingly. “Spanish, and gangbanger English… Let me guess. All the Russian-language emails are among a small group of people, and it’s mostly talking about high-level strategy and probably a bunch of family matters, right? And then everything else is in Spanish and English, and it’s all very short and specific, mostly giving orders and demanding status reports.”
</p>
<p>
Moshen nodded. “…Yeah, I’d say that sums it up.”
</p>
<p>
Danny chimed in. “Wait, I get it. Their inner circle is all the same Russian family. But their foot soldiers are just random thugs that they hire from around the neighborhood, and it’s these low-level employees that do the day-to-day work.”
</p>
<p>
Jason nodded. “Exactly. Moshen, do they say where they’re keeping her?”
</p>
<p>
“Not quite,” Moshen said. “They mentioned something about making her set up a factory in a rented warehouse space. Or set up a warehouse in a rented factory space.”
</p>
<p>
Danny suggested, “You know, that phone has GPS…” He took the Pantech from Moshen and gave it a few quick pokes. “AT&amp;T Navigator… Recent Places… Done.” He passed the phone around for the team to examine.
</p>
<p>
Jason studied it. “Promising, but there’s over three dozen addresses in that history list. Can we narrow it down?”
</p>
<p>
“Moshen,” said Danny. “Hop on Google Maps. They said they’re going to make her work at a factory or warehouse. Use Satellite View to check which of these addresses are in industrial zones.” As Moshen got to work, Danny turned to Jason. “Assuming you do find this Julie girl, what’s your plan?”
</p>
<p>
“Bribery,” Jason answered. “Find some low-ranking worker and pay him off.”
</p>
<p>
Danny shook his head. “It’d have to be one hell of a bribe, Jason. A guy like that could end up at the bottom of Puget Sound.”
</p>
<p>
“I admit it isn’t the best of stratgies,” Jason said sourly. “After all, if the mob thought one of their own was on the take, all hell would break loose. I don’t know exactly what’s the Russian mafia’s disaster plan for internal espionage, but I’ve seen what happens at corporations when management thinks some employees might be secretly working for a competitor. It isn’t pretty.”
</p>
<p>
Danny looked away pensively. “What if…”
</p>
<p>
“What if what?” asked Jason.
</p>
<p>
“What if that was the point?” Danny offered.
</p>
<p>
Jason cocked his head. “Not following…”
</p>
<p>
Danny turned to his fellow computer geeks. “Guys. Do any of you happen to have admin privileges on an SMTP server?”
</p>
<p>
Mike slowly raised one feeble hand.
</p>
<p>
Danny smiled. “Of course. From your Cisco certification classes.”
</p>
<p>
Mike nodded. “The teacher gives us a couple of servers to play with.”
</p>
<p>
Danny replied, “Can you configure it to bypass all authentication mechanisms and function as an open mail relay?”
</p>
<p>
Mike’s large brow furrowed. “Yeah, but we’re not supposed to do that. The very first thing we learn is how to <em>prevent</em> them from running as open mail relays.”
</p>
<p>
Danny grinned. “And why exactly is that?” 
</p>
<p>
“Because open mail relays make the whole Internet a worse place,” Mike answered. “Spammers from all over the world constantly look for them. Open mail relays are where all those spam messages for penis enlargement pills and herbal Viagra and discount mortgages come from.”
</p>
<p>
“Yep. And <em>why</em> do spammers need open mail relays for that?” Danny asked.
</p>
<p>
“Because open relays are completely anonymous,” Mike answered. “An open relay doesn’t verify the source of the message. It just forwards everything stupidly along.”
</p>
<p>
“Exactly. So, if we wanted to forge a bunch of emails from the Russian mob guys to their foot-soldiers…”
</p>
<p>
Mike’s eyes expanded. “…We’d need an open mail relay!” He grabbed a laptop hungrily. The computer seesawed on his lap as he punched on the keyboard.
</p>

<pre class="computer">
<strong>telnet localhost 25</strong>
</pre>

<p>
The terminal window replied:
</p>

<pre class="computer">
220-mail46.cisco.bellevuecollege.edu ESMTP Exim 4.69 #1
220-This computer system is solely for use by Bellevue 
220 College staff and students. 
220-We do not authorize the use of this system to 
220 transport unsolicited, and/or bulk e-mail.
</pre>

<p>
The empty cursor blinked alone on the blank line below the message. Mike knew that it was waiting for a few words of SMTP, the primitive language spoken by mailservers.
</p>

<pre class="computer">
<strong>MAIL FROM:sergey@pash.ly</strong>

250 OK

<strong>RCPT TO:eugene@pash.ly</strong>

250 Accepted

<strong>DATA</strong>

354 Enter message, ending with "." on a line by itself

<strong>
To: "Eugene &lt;eugene@pash.ly&gt;"
From: "Sergey &lt;sergey@pash.ly&gt;"
Subject: This is a test
Mary had a little lamb, whose fleece was white as snow.
.
</strong>

250 OK id=1Kervv-0002Di-VE
</pre>

<p>
“What happens now?” asked Jason.
</p>
<p>
In reply, the Pantech chirped. Mike glanced at the screen and proudly held it up for all to see. 
</p>
<p>
Jason eyed Danny reproachfully. “What kind of plan is this, Danny? So, you can forge their emails. So what?”
</p>
<p>
Danny replied, “Two words: Byzantine General.” 
</p>
<p>
All eyes in the room stared at Danny quizzically.
</p>
<p>
“Oh, come on!” he said, returning their gazes. “<em>None</em> of you knows how to break a Byzantine army?” He gave an exasperated sigh. “Ah well. Moshen, do you have a street address for us?”
</p>
<p>
Moshen pivoted his laptop. A satellite image showed an overhead view of Seattle’s southward stretch of shipping yards lining the silty gray Duwamish River. “That looks like an industrial zone, right?”
</p>
<p>
“Danny,” Jason asked, “what the hell is this Byzantine General thing?”
</p>
<p>
“Grab your car keys,” said Danny. “I’ll explain on the way.”
</p>
</div>