<div class="chapsection">
<p>
<span class="caplead">Pain enveloped Mike like a cocoon.</span> It robbed him of all sense of time, space, or direction. He felt like he was floating in the dark womb of some alien beast. He sat propped up in his hospital bed with his wounds dressed in gauze, talking with friends, enduring the exhaustion and the delirium, counting the hours until Natalie and the nurses would tell him it’s okay to sleep. The pain diffused from his face to the rest of his body, until he felt it everywhere, inside and out. It sent his mind reeling, almost like a drug high. The agony was borderline euphoric.
</p>
<p>
“It’s your endorphins kicking in,” Natalie said. “They work on your brain like morphine. That’s where the word ‘endorphin’ comes from, you know &mdash; ‘endogenous morphine.’ It’s basically heroin that your body makes naturally. Your body’s protecting itself. Making the damage a little easier to bear.”
</p>
<p>
“Natalie…,” he asked. “Why are you being so nice to me? We just met.”
</p>
<p>
“Yeah, but I… Uh… You seem pretty cool,” she said, blushing.
</p>
<p>
Natalie’s attention was drawn away by a shadow on the other side of the privacy curtain. A few people approached, talking in distressed tones. As they got closer, he recognized one of the voices as the girl from the Tungsten building. 
</p>
<p>
It was Tina. She was sobbing.
</p>
<p>
“They know everything about me, Nat,” she was saying, her voice froggy. “They busted into my car. It was still sitting in the Tungsten parking lot. They got the registration and insurance papers and whatever else was in there. They know my address, my phone number, my Social Security Number…”
</p>
<p>
Danny materialized beside her, carrying plastic bags from Rite Aid. “Jason…” he said tensely. “I… I’m gonna need hazard pay.”
</p>
<p>
“What the hell is going on?” Jason said.
</p>
<p>
“The Russians called Tina,” Danny answered.
</p>
<p>
“Called <em>her</em>?” Jason repeated.
</p>
<p>
Tina said meekly, “They want me to help them incubate the stuff in the Eppendorf tube. They told me to meet them at my apartment in one hour, ‘or else.’”
</p>
<p>
“They think you can incubate it for them?” Jason asked.
</p>
<p>
“Yes. Geez. It’s just <em>E. coli</em>. The incubation part is easy,” Tina said. “It’s figuring out what the hell to do with them once they’re grown that’s the hard part. You incubate them, you get a warm tub of goo. Great. What do you do with <em>that</em>? I don’t know how the hell they expect me to figure that out. The only person who knows that, is Julie.”
</p>
<p>
“Julie Yen?” Jason asked.
</p>
<p>
Tina eyed him suspiciously. “How do you know Julie?”
</p>
<p>
Jason ignored the question. “Christina, is Julie working for these Russians?”
</p>
<p>
“I don’t know,” said Tina. “When that guy was holding me at gunpoint, he said stuff that made me think she’s not exactly with them willingly.”
</p>
<p>
“And they’re trying to threaten you into ending up like her?” Jason asked.
</p>
<p>
Tina nodded meekly.
</p>
<p>
Jason rolled his eyes. “Pffft. Amateurs.”
</p>
<p>
“Come again?” Tina squeaked.
</p>
<p>
“Listen,” said Jason. “You hold more cards than you think. A party only resorts to threats if they have nothing of value. If the first instinct of these Russians is to go straight for your jugular, then they’re approaching the negotiation from a position of weakness.”
</p>
<p>
Tina stared at him incredulously. “You’re saying the mob is in a ‘position of weakness’?”
</p>
<p>
“Oh, absolutely,” said Jason. “Think about it. They’re a criminal organization that’s at constant risk from both rivals and law enforcement. They have a lot to lose. I promise you, they give off the impression of being big and tough, but they’re a lot more scared of you than you are of them.”
</p>
<p>
“I highly doubt that,” said Tina.
</p>
<p>
“They’re issuing threats just to get you to the bargaining table. Their BATNA must be absolutely terrible.”
</p>
<p>
“What the hell is a BATNA?”
</p>
<p>
“A Best Alternative To a Negotiated Agreement,” Jason answered. “It’s your fallback strategy. Believe me, this stuff I know. I may be out of my league when it comes to tech, but they do teach us something in business school.”
</p>
<p>
“We’re not dealing with a business here!” Tina cried. “We’re dealing with the mob!”
</p>
<p>
Jason smiled. “What do you think the mob is?” 
</p>
<p>
Tina stared at him in silence.
</p>
<p>
“Trust me,” said Jason, his tone steady. “Whatever else may be true about them, they’re rational players. They have to watch their bottom line. I didn’t get rich by playing the lottery; I got rich by understanding what people want. So let’s try and understand these guys. What do we know about them? What can we deduce about their needs, their risks, their motivations? Anything?”
</p>
<p>
Danny, standing nearby, smiled wickedly. “I know a thing or two about them.” He handed a cellphone to Jason.
</p>
<p>
Jason looked at the small screen, perplexed. Slowly, his eyes went wide as understanding dawned. Satish and Moshen looked over excitedly. Mike craned his neck to look at the phone. Jason showed the screen to the men. Hoots and high-fives were exchanged. Danny let out a peal of maniacal laughter.
</p>
<p>
“A lot of the emails are in Russian,” said Danny. “Could you guys run them through an online translator?”
</p>
<p>
Moshen took the phone. “No problem, Danny,” he said, and twirled back to his laptop.
</p>
<p>
Jason nodded approvingly. “We’ve got them by the balls and they don’t even know it. Christina, I can get you out of this. Do you trust me?”
</p>
<p>
“I don’t have much choice, do I?” she replied.
</p>
<p>
Jason extended a hand out to her with his palm up. “The vial, please.”
</p>
<p>
She shot him a look of suspicion so hot it could’ve ignited his gelled hair.
</p>
<p>
“It’s either me or the Russians.”
</p>
<p>
She grudgingly pulled the vial out of her purse and put it in his palm. Jason’s fingers curled around it like the fronds of a carnivorous plant. 
</p>
<p>
With determination, Jason turned to his team. “Moshen. What do the emails say about this Julie Yen girl?”
</p>
<p>
“They don’t say anything about any Julie Yen by name,” Moshen answered. “But I’ve learned about six different ways in Russian to say, ‘Oriental whore.’”
</p>
<p>
“What have you been able to learn so far?” Jason asked.
</p>
<p>
“Not a ton,” Moshen replied. “There’s as much English and Spanish as there is Russian in these emails. And my Spanish sucks, and the English is really, really bad English. It’s all ghetto slang and, like, innuendoes and shit.”
</p>
<p>
“Hmm.” Jason nodded knowingly. “Spanish, and gangbanger English… Let me take a guess. All the Russian-language emails are among a small tight group of people, and it’s mostly talking about high-level strategy and probably a bunch of family matters, right? And then everything else is in Spanish and English, and it’s all very short and specific, mostly giving orders and demanding status reports.”
</p>
<p>
Moshen nodded. “…Yeah. Yeah, I’d say that actually sums it up.”
</p>
<p>
Danny, from the side, chimed in. “So, wait, I get it. Their inner circle is all the same Russian family. But their foot soldiers are just random thugs that they hire from around the neighborhood, and it’s these, sort of, low-level employees, I guess, that do most of the day-to-day work. Right?”
</p>
<p>
Jason nodded. “Exactly. Moshen, do they say where they’re keeping her?”
</p>
<p>
“Not quite,” Moshen said. “They mentioned something about making her set up a factory in a rented warehouse space. Or set up a warehouse in a rented factory space.”
</p>
<p>
Danny suggested, “You know, that phone has GPS…” He took the Pantech from Moshen and gave it a few quick pokes. “AT&amp;T Navigator… Recent Places… Done.” He passed the phone around for the team to examine.
</p>
<p>
Jason looked at it. “Promising, but there’s over three dozen addresses in that history list. Can we narrow it down?”
</p>
<p>
“Moshen,” said Danny. “Hop on Google Maps and start looking up these addresses, ok? They said they’re going to make her work at a factory or warehouse, right? Use Satellite View to check which of these are in industrial zones.”
</p>
<p>
Moshen got to work.
</p>
<p>
Danny turned to Jason. “Assuming you do find this Julie girl, what’s your plan?”
</p>
<p>
Jason smiled. “To convince her to work for me, obviously.”
</p>
<p>
Danny blinked a few times. “I’m guessing it isn’t <em>her</em> agreement you need to secure. If it’s true that she’s being held in some mob warehouse somewhere, then she won’t be there alone. We can’t exactly just drive over there and ring the doorbell and be like, ‘Hi! We’re here to pick up the girl!’ Do warehouses even <em>have</em> doorbells?”
</p>
<p>
Jason nodded. “It’ll be tricky. My plan is to find some low-ranking worker and bribe him.”
</p>
<p>
Danny shook his head. “It’d have to be one hell of a bribe, Jason. A guy like that could end up at the bottom of Puget Sound.”
</p>
<p>
“Yeah, I’d have to make the payout big enough to be worth the risk,” Jason said sourly. “And besides, if they thought one of their own was on the take, all hell would break loose. I don’t know exactly what the Russian mafia’s disaster plan is for internal espionage, but I’ve seen what happens at companies when management thinks some employees might be secretly working for a competitor. It isn’t pretty.”
</p>
<p>
Danny looked away pensively. “What if…”
</p>
<p>
“What if what?” asked Jason.
</p>
<p>
“What if that was the point?” Danny offered.
</p>
<p>
Jason cocked his head. “Not following…”
</p>
<p>
Danny turned to his fellow computer geeks. “Guys. Do any of you happen to have admin privileges on an SMTP server?”
</p>
<p>
Mike stirred. Slowly, feebly, he raised one hand.
</p>
<p>
Danny smiled. “Of course. From your Cisco certification classes.”
</p>
<p>
Mike nodded. “The teacher gives us a couple of servers to play with.”
</p>
<p>
Danny replied, “Can you configure it to bypass all authentication mechanisms and function as an open mail relay?”
</p>
<p>
Mike furrowed his large brow. “Yeah, but we’re not supposed to do that. The very first thing we learn is how to <em>prevent</em> them from running as open mail relays.”
</p>
<p>
Danny grinned. “And why exactly is that?” 
</p>
<p>
“Because open mail relays make the whole Internet a worse place,” Mike answered. “Spammers from all over the world constantly look for them. Open mail relays are where all those spam messages for penis enlargement pills and herbal Viagra and discount mortgages and shit come from.”
</p>
<p>
“Yep. And why do spammers need open mail relays for that?” Danny asked.
</p>
<p>
“Because open relays are completely anonymous,” Mike answered. “An open relay doesn’t verify the source of the message. It just forwards everything stupidly along.”
</p>
<p>
“Exactly. So, if we wanted to forge a bunch of emails from the Russian mob guys to their foot-soldiers…”
</p>
<p>
Mike widened his eyes. “…We’d need an open mail relay!”
</p>
<p>
Eagerly, the large scruffy man grabbed a laptop. The computer seesawed on his lap as he punched his fingers against the keyboard.
</p>

<pre class="computer">
<strong>telnet localhost 25</strong>
</pre>

<p>
The terminal window replied:
</p>

<pre class="computer">
220-mail46.cisco.bellevuecollege.edu ESMTP Exim 4.69 #1
220-This computer system is solely for use by Bellevue 
220 College staff and students enrolled in classes for 
220 Cisco Certified Network Administration certification 
220 exams. 
220-We do not authorize the use of this system to 
220 transport unsolicited, and/or bulk e-mail.
</pre>

<p>
The empty cursor blinked alone on the blank line below the message. Mike knew that it was waiting for a few words of SMTP, the primitive language spoken by mailservers since the dawn of the Internet. He answered it in kind.
</p>

<pre class="computer">
<strong>MAIL FROM:sergey@pash.ly</strong>

250 OK

<strong>RCPT TO:eugene@pash.ly</strong>

250 Accepted

<strong>DATA</strong>

354 Enter message, ending with "." on a line by itself

<strong>
To: "Eugene &lt;eugene@pash.ly&gt;"
From: "Sergey &lt;sergey@pash.ly&gt;"
Subject: This is a test
Mary had a little lamb, whose fleece was white as snow.
.
</strong>

250 OK id=1Kervv-0002Di-VE
</pre>

<p>
“What happens now?” asked Jason.
</p>
<p>
“The message has to bounce around the intertubes for a bit,” said Mike. 
</p>
<p>
“Does that take long?”
</p>
<p>
In reply, the Pantech chirped. Mike glanced at the screen and proudly held it up to Danny. Danny took the phone with a look of exquisite approval. 
</p>
<p>
Satish eyed Danny reproachfully. “What kind of plan is this, Danny? So, you can forge their emails. So what? How do you think that helps you?”
</p>
<p>
Danny replied, “Two words for you, Satish.”
</p>
<p>
“And those would be…?” 
</p>
<p>
“Byzantine General.” 
</p>
<p>
Everyone except for Danny and Satish exchanged quizzical glances.
</p>
<p>
“What about it?” Satish asked defiantly.
</p>
<p>
“You know how to break a Byzantine army, right?” Danny goaded.
</p>
<p>
“Sure. Yeah,” Satish countered. “What’s your point?”
</p>
<p>
“Now that we can forge their emails, we can induce a Byzantine failure mode,” Danny replied.
</p>
<p>
“In what?” said Satish. “In their mailserver?”
</p>
<p>
“No,” Danny said. “In their foot-soldiers.”
</p>
<p>
Satish shook his head, aghast. “You’re insane.”
</p>
<p>
“Yep!” Danny said proudly. Turning, he asked, “Moshen, do you have a street address for us?”
</p>
<p>
“I think so, Danny.” Moshen turned his laptop around. A satellite image showed an overhead view of Seattle’s long southward stretch of shipping yards lining the silty gray Duwamish River. “I’d say that looks like an industrial zone, right?”
</p>
<p>
“Danny,” Jason asked, “what the hell is this Byzantine General thing?”
</p>
<p>
“So glad you asked!” said Danny. “Grab your car keys. I’ll explain on the way.”
</p>
</div>