<div class="chapsection">
<p>
<span class="caplead">
“Asperger’s?” Danny muttered
</span>
as they stepped down the interior stairs. “You told the guy I had Asperger’s?”
</p>
<p>
Jason shrugged. “The best lies are based on truth.” The two of them kicked away bits of cardboard and styrofoam litter as they walked across the space. They passed fluid-filled vats, racks of glassware, and a row of 55-gallon drums marked “Kerosene” and “Acetone” and covered with hazard warnings.
</p>
<p>
Julie Yen stood beside a naked mattress strewn with ragged blankets. She greeted them with a scowl.
</p>
<p>
“Julie,” said Jason quietly as he approached. “Relax. We’re friends. Everything will be okay.”
</p>
<p>
“Right,” she scoffed.
</p>
<p>
Danny paid less attention to the girl than to the supplies and equipment surrounding him. On a metal table sat an unmarked glass bottle of clear liquid, sealed with a stopper. Eye goggles and black rubber gloves lay beside it. He reached toward it.
</p>
<p>
“I wouldn’t touch that if I were you,” Julie called out.
</p>
<p>
“What is it?” Danny asked.
</p>
<p>
“Hydrochloric acid, eleven molar concentration. I told you idiots you only need three molar to stabilize the base. I’ll have to dilute the shit out of it.” She sighed. “Don’t know why I’m even stopping you. Go ahead, open it.”
</p>
<p>
Jason whispered, “We’re not with the Russians, Julie. We’re here to bust you out.”
</p>
<p>
She gave Jason no response, remaining as unreactive as a noble gas. Not a muscle on her face moved.
</p>
<p>
“Don’t you want to get out of here?” he pressed.
</p>
<p>
Julie’s lip trembled. “I want…” she looked up at the windows of the overhead office and screamed, “…my <em>fucking blow</em>!” She grabbed a nearby piece of cardboard and threw it weakly upwards. “They fucking stole it! It’s mine, God damn it! Fuck…!” She threw herself down onto her mattress, sobbing.
</p>
<p>
Jason squatted beside her. “Julie… Are you alright?”
</p>
<p>
“This is all my fault,” she said, her voice croaky. “I should have just done my job like a good little girl. I can’t do anything right.” She sniffled, wiped her nose with her sleeve, and added, “Your friend is gonna burn his hands off.”
</p>
<p>
Danny was jabbing at the bottle with his HERF gun, watching the liquid jiggle back and forth. It looked like ordinary water, except for the fine white haze suspended above its surface.
</p>
<p>
Julie shuffled toward him. Without a word, she donned the gloves, strapped the goggles over her face, and gently pulled out the stopper. A translucent trail of pale vapor wafted upward. She grabbed a scrap of cardboard from the floor and waved it over the bottle, passing it through the finger of fog. Along the line of exposure, the cardboard blackened and charred. She gave the sheet a slight shake, and chunks crumbled to ash. She used the remains of the cardboard to wipe the stopper. Where it touched, the cardboard simply vanished. She re-sealed the bottle and removed her safety gear. “That’s why you don’t fuck with this stuff.”
</p>
<p>
Jason reached into his pocket. “Julie, listen. We brought you something…” He drew out the Eppendorf vial and extended it toward her.
</p>
<p>
Her head lifted high at the sight of it. “The mother strain!” She grabbed it quickly from his grasp and held it up to her face. “It’s biofilming. That’s good. It’s supposed to. This is…!” Her eyes darted up toward the office. Her expression, momentarily eager, quickly soured again. “You shouldn’t have brought it here.”
</p>
<p>
“Can you incubate it?” asked Jason.
</p>
<p>
“The second I finish a batch, the Russians will put a bullet through my head.”
</p>
<p>
“I might be able to talk them into letting you go.”
</p>
<p>
“Fat chance.”
</p>
<p>
“It’s worth a try,” said Jason. “But tell me more about it first.”
</p>
<p>
Julie frowned. “Can you get me some blow?”
</p>
<p>
“Tell me what’s in the vial,” said Jason, “and I’ll see what I can do.”
</p>
<p>
“It’s a cocaine factory,” she said simply.
</p>
<p>
Jason looked around. “Yeah, I gathered that.”
</p>
<p>
Julie held up the vial. “No, this. <em>This</em> is a cocaine factory.” She pointed across the room, toward a pyramidal stack of large plastic jars labeled “L-Glutamine”. “You feed that stuff to these bacteria, and they poop out benzoylmethylecgonine.”
</p>
<p>
“Benzowhat?” said Jason.
</p>
<p>
“Benzoylmethylecgonine. Cocaine. The world’s best targeted dopamine reuptake inhibitor.”
</p>
<p>
Jason eyed the purple labels on the jars. “That L-Glutamine stuff… Is it hard to get?”
</p>
<p>
Julie looked at Jason with a face usually directed at the kid in class who eats paste. “It’s <em>glutamine</em>. It’s forty bucks a pound at any GNC store.”
</p>
<p>
“So, you incubate the germs in that vial, then you pour in that glutamine stuff, and then suddenly you have cocaine?”
</p>
<p>
“More or less,” said Julie. “You have to give it time to let the enzymes act, but after that you can process it just like leaves from a coca plant. Mix it with kerosene, grind it into a paste, separate with acetone, blah blah blah. The process kills the bacteria, so you need to keep a pure mother broth around. But basically, yeah.”
</p>
<p>
Danny interrupted, “Wait, let me get this straight. This whole night, I’ve been chasing after some kind of germ that’s been injected with the gene for cocaine?”
</p>
<p>
Julie rolled her eyes. “There is no ‘gene for cocaine’. Cocaine isn’t a protein. It’s a crystalline tropane alkaloid. Do you have any idea how complicated its biosynthesis process is?”
</p>
<p>
“Umm… no?” Danny replied.
</p>
<p>
“Look, cellular machinery can’t create cocaine directly through gene expression,” said Julie. “But it <em>can</em> create enzymes to catalyze precursors. That’s what happens in <em>Erythroxylon coca</em> &mdash; the coca plant. Unlike cocaine, enzymes <em>are</em> proteins. Enzymes <em>do</em> have genetic encodings. Which meeeeeans…” She paused, hoping that the implication would be obvious. The two men stared at her blankly. “…Which <em>means</em> that we can sequence those genes in the coca plant, and then splice them into <em>E. coli</em>. So the <em>E. coli</em> thinks they’re part of its own genome, and translates them into proteins. Got it?”
</p>
<p>
Danny nodded brightly. “Yeah!”
</p>
<p>
Julie cocked an eyebrow. “Really?”
</p>
<p>
“Yes!” Danny declared. “It’s just like a DLL hijacking attack! How a lot of computer viruses work.”
</p>
<p>
Jason stared at her quizzically. “You gene-spliced a coca plant into a laboratory germ to create a cocaine-producing bio-machine? That sounds like one hell of an engineering accomplishment.”
</p>
<p>
“Recombinant genetics isn’t for sissies,” she replied proudly.
</p>
<p>
“So,” Jason asked, “how much of this genetic engineering did you perform on your own?”
</p>
<p>
“What do you mean?” Julie replied.
</p>
<p>
“How did <em>you</em> get that vial?” Jason prodded.
</p>
<p>
“I told you!” Julie said defiantly. “By sequencing the <em>Erythroxylon coca</em> genome…”
</p>
<p>
“That answers how <em>Tungsten</em> created it,” said Jason. “It doesn’t answer how <em>you</em> ended up with it. Look, I don’t know much about science, but I do know about personnel management. The kind of engineering effort you’re describing would take years, even for a team of world-class researchers. You did <em>not</em> create it on your own as some intern summer project.”
</p>
<p>
“They couldn’t have finished it without me!” she protested.
</p>
<p>
“Right. They needed <em>you</em> to sequence the coca plant genome. They needed <em>you</em> to splice the genes into the <em>E. coli</em> strain…”
</p>
<p>
Julie glared at him. “I’m a key member of the research staff!”
</p>
<p>
“You’re a college sophomore.”
</p>
<p>
“God, shut the fuck up!” She stormed back to her mattress in a huff.
</p>
<p>
Jason sat down beside her. After giving her a few moments to cool off, he asked her gently, “Tell me how it went down.”
</p>
<p>
She picked idly at a loose thread. “Creating cocaine-producing <em>E. coli</em> wasn’t just some side-project. It’s the whole point of Tungsten. This vial is everything they’ve been working for.”
</p>
<p>
“And they entrusted it to their intern?”
</p>
<p>
“Well… Genetic engineering isn’t an exact science. It’s not like we can reach inside a cell’s nucleus with little tweezers, you know? We use special chemicals called restriction enzymes to chop out the genes we want from the source organism. But a lot of other unwanted chunks of DNA also float out along with it. You then have to fool a bacterium into absorbing these chunks into its own genome. It’s tricky because bacteria have evolved restriction modification systems to protect themselves from foreign DNA…”
</p>
<p>
“Ooh!” Danny interrupted. “Like Intrusion Prevention Systems on computer networks! I just learned about those today.”
</p>
<p>
Julie blinked at him and shrugged. “Anyway. To fool a bacterium into adopting foreign DNA, you have to wrap the new gene into a plasmid, or load it into a bacteriophage virus, and so on. Oh, <em>and</em> you have to create some way to separate the <em>E. coli</em> that <em>do</em> absorb your new gene from the ones that don’t. Like with something called a ‘screenable marker’, which is where we add a gene for bioluminescence to make organisms glow in the dark. Because, don’t forget, we don’t actually <em>see</em> what we’re working with &mdash; all we’re doing is mixing liquids and keeping our fingers crossed.”
</p>
<p>
“So, what you’re saying,” said Jason, “is that you can do everything right, and in the end your germs don’t absorb any new DNA. Or they do, but it wasn’t the specific gene you were hoping for. Which means you have to mix up another batch and try again?”
</p>
<p>
“Over and over,” said Julie. “And that’s just for <em>one</em> gene. The metabolic pathway for cocaine synthesis has about forty. It’s mostly done by robots. But you have to do follow-up tests by hand.”
</p>
<p>
Jason smiled. “Which is exactly the kind of task that they’d give an intern.”
</p>
<p>
Julie nodded. “Exactly. It was my job to check on the batches. So when one of them finally produced an <em>E. coli</em> strain that was expressing <em>all</em> the cocaine biosynthesis genes, I was the first to see it.”
</p>
<p>
“And you were supposed to call in the senior researchers. But instead, you…”
</p>
<p>
“Yeah. I just… you know…”
</p>
<p>
“Took it.”
</p>
<p>
Julie nodded. “They eventually realized that something was up. Damned if I know how. Sensor data from the robots, maybe? They were starting to suspect me after a couple weeks. But by then I’d already started making my own batches and dealing… And… And then…” She curled up on her side in a fetal position, the Eppendorf tube between her palms.
</p>
<p>
“Are you okay?” Jason asked.
</p>
<p>
“No, I’m not fucking okay!” she sobbed. “God, I don’t understand why everything has to be so fucking hard! Nothing I do ever fucking works! Nothing is ever good enough! I get a full scholarship to the University of Washington and my parents are like, ‘Why not Berkeley or MIT?’ I score 97% on my organic chemistry final, and they go, ‘Why not a hundred?’ I work so fucking hard… All I want is to know that I did <em>something</em> right. <em>Anything</em>. I just wanted one big score, just to be able to say to the world, ‘Look at me, fuckers! I win!’… I… I’m such a fuckup…”
</p>
<p>
Gently, Jason asked, “Julie… There’s one more thing I need you to explain.”
</p>
<p>
She bolted back up furiously. “Oh fuck, come on!”
</p>
<p>
“You’ve told me the <em>how</em>, but not the <em>why</em>. Tungsten was working full-time to develop this living cocaine dispenser. But from a business perspective, that doesn’t make any sense. The end product is illegal to sell. What was Tungsten’s market strategy?”
</p>
<p>
“You mean like how to make money off of it?” asked Julie. “Fuck if I know. I was just on the science end of things. All I know are rumors. The scientists talked about medical applications. They believe the future of psychopharmacology is dopamine.”
</p>
<p>
“Dopamine?”
</p>
<p>
“It’s a neurotransmitter,” said Julie. “It runs the nucleus accumbens, the ‘pleasure center’ of the brain. It controls motivation, excitement, attention, that kind of thing. There’s this class of drugs called DRIs &mdash; dopamine reuptake inhibitors. Wellbutrin, Ritalin, Adderall &mdash; they’re all DRIs. They jam the brain’s dopamine-draining machinery &mdash; they make dopaminergic pathways flood themselves, like running a sink with a clogged drain.”
</p>
<p>
“And what effect does that have?” Jason asked.
</p>
<p>
“Well, it’s a rush. A thrill of victory, sort of. Like, if you ace a test at school, it’s how you feel at seeing that A+. Or you’re playing piano and nail an arpeggio you’ve been struggling with. Or you beat someone at a game, or win a bet…”
</p>
<p>
Jason gave a slow, knowing nod. “A cocaine high.”
</p>
<p>
“Exactly,” Julie replied. “Cocaine is the <em>original</em> DRI. What we’re now figuring out how to do with synthetic drugs, the coca plant has been doing naturally for millions of years.”
</p>
<p>
Danny stood near the center of the room, beside a cylindrical glass vat as tall as him, covered with hoses and pipes and gauges. He looked up from the dials and buttons he had been idly fiddling with, his mouth agape. “Jason! <em>You’ve</em> tried cocaine?”
</p>
<p>
Jason rolled his eyes. “I made my first million in my mid-twenties in 1981, Danny. You do the math.” He turned his gaze back to the sullen, unwashed girl. “And I know what she’s going through right now. The withdrawal. The feeling that all your pride, all your joy, all your potential, has been drained out of your very soul, and nothing will ever make it come back. The feeling that you’re a worthless piece of human garbage who will live out the rest of your days accomplishing nothing.”
</p>
<p>
Julie curled into her pajamas and turned away from him, remaining silent.
</p>
<p>
“That’s what cocaine does, you know,” Jason continued. “Gives you a feeling of accomplishment. Just straight-up <em>gives</em> it to you &mdash; without you having to do anything to earn it. It’s great stuff, in a way. Who needs to actually pursue dreams or achieve goals, when you can just get the resulting pride and satisfaction directly in powder form?” He leaned into her and said quietly, “But you eventually learn it’s a fake feeling. You can’t outsmart your own mind. You yourself know perfectly well whether or not you’ve achieved your own goals, because you’re the one that defines those goals in the first place. And when that happens… When you reach that realization… After that point, no matter how much coke you do, it’s never, ever going to be enough. Julie… Isn’t that right?”
</p>
<p>
Julie jerked her head toward him and glared. “We had a deal…!”
</p>
<p>
Jason stood up with a grunt. “I’ll go talk to that Rex guy upstairs. Thank you, Julie. You’ve been… helpful.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Jason descended the stairs.</span> Rex closely followed with gun in hand. Julie kept her eyes fixed on them. “Well?”
</p>
<p>
Rex sat down on the folding chair and laid the gun across his lap. From his pocket he produced a small white package, which he laid on the table. With a rhythmic tapping of a razor blade against the metal tabletop, he chopped its contents into ever finer grains, and drew out thin parallel lines of powder.
</p>
<p>
Julie’s face lit up in an ecstatic grin. With her small body and oversized t-shirt, she looked like a child beaming at the sight of presents under the tree on a wintry white Christmas morning. But for her, the greatest present of all was the snow. 
</p>
<p>
“You got any idea how much trouble I’d be in if the boss-man found out?” Rex grumbled as he worked. “We’re in lockdown. I was supposed to flush this.”
</p>
<p>
Julie stared transfixed at the rails of coke with an expression not unlike Pavlov’s dogs upon hearing a bell.
</p>
<p>
Rex rolled up a dollar bill into a tight tube. He sat up straight, tossed his long stringy blond hair behind his head, and exhaled fully. Then, in one continious motion, he brought the rolled-up bill to his nostril, bowed his head, and traced the end of the green tube along the bottom-most line. When all the granules had disappeared up his nose, he pitched his head back, closed his eyes, and emitted a satisfied sigh.
</p>
<p>
Julie tried to body-check him off of the chair. “My turn!”
</p>
<p>
Rex pushed her away and raised his gun. “Mind your manners, little lady! Guests first. Gentlemen?”
</p>
<p>
Danny stood petrified. Jason shook his head.
</p>
<p>
Rex eyed Jason dubiously. “Numbers? You don’t want any?”
</p>
<p>
“No thanks, Rex,” said Jason. “Umm… Diggitty’s on all sorts of medication, so he can’t have any. And me, I’m too old to get much out of it anymore.”
</p>
<p>
“You sure?” Rex persisted. “It’s top-notch stuff.”
</p>
<p>
“I don’t get a high from coke,” said Jason. “I just get a headache.”
</p>
<p>
“Well shit. I hope I never get <em>that</em> old,” Rex grunted, rising from his chair.
</p>
<p>
He had barely lifted his rear from of the seat before Julie slid in and grabbed the rolled-up bill. She dove straight into the next line on the table, snorting it up as quickly as her nose would allow. She held her breath for several seconds, looking like she was about to sneeze. Tears built up in her eyes. Her accelerating pulse was visible in her ears. 
</p>
<p>
After several seconds of sitting motionless, she finally made a sound: a euphoric, delighted, childlike laugh.
</p>
<p>
“I can’t feel my face!” she giggled, and traced her fingers sensuously across her mouth and cheeks.
</p>
<p>
Jason watched her indulge. “Listen, Julie. You still have the vial, right?”
</p>
<p>
Julie sat in unresponsive bliss.
</p>
<p>
“Julie, the vial…” he persisted.
</p>
<p>
She abruptly turned. “Dude I can hear you just fine, shut the fuck up,” she snapped, her voice rapid and energetic. “Can’t a girl enjoy a freakin’ high? It’s my first hit in like a week, so let me fucking roll with it, okay? Christ. Buzzkill.”
</p>
<p>
“Part of the deal I struck with Rex,” said Jason, “is that you’d start the incubation.”
</p>
<p>
“Well fuck that! He’s going to shoot me the minute I finish a batch.”
</p>
<p>
Rex rolled his wide-pupilled eyes. “I keep telling you, bitch. If you behave, nobody’s going to hurt you. Fuck, I’ll shoot you if you <em>don’t</em> make a batch.”
</p>
<p>
“Fine, fine,” said the girl. “Let me do the rest of these lines and I’ll go pop it in the tank.” Her head swooped down. Another white rail disappeared.
</p>
<p>
Her eyes began darting back and forth, looking at the objects on the tabletop. She fidgeted with her hands, and occasionally glanced over her shoulder towards Rex.
</p>
<p>
“Are you okay?” asked Danny.
</p>
<p>
“I’m fine,” she said quickly.
</p>
<p>
“You look agitated,” he said.
</p>
<p>
“I’m just thinking…” she replied.
</p>
<p>
From outside, past the large double doors on the opposite side of the factory, came the sound of an engine, followed by car doors opening and closing.
</p>
<p>
The dreadlocked guard said something beyond the wall. His words weren’t clear, but he sounded surprised.
</p>
<p>
Someone answered in a Russian accent. “…Tonight is complete cluster of fucks!…”
</p>
<p>
Danny recognized the voice. He had heard it on the stolen cellphone. It was the voice of Sergey Mukhayev.
</p>
<p>
Rex froze in place. “Oh… shit…”
</p>
<p>
A third person outside spoke. Danny recognized the voice of the man from the Tungsten hallway: Eugene Mukhayev. “That’s the car! That’s their fucking car!”
</p>
<p>
Jason gulped, and backed toward the rear wall, behind the steel drums.
</p>
<p>
Rex sprang to life. “We’ve got to get rid of the coke! I wasn’t supposed to give you any! I’m not even supposed to have any. Fuck…”
</p>
<p>
Julie, still fidgeting, grabbed clumsily at the open packet of white powder. While handing it to Rex, she carefully enunciated, “Whoops!”, and let its contents spill onto the floor in a conspicuous pile.
</p>
<p>
“Oh fuck me!” Rex bent down next to Julie and tried to sweep the powder out of sight.
</p>
<p>
“What I was thinking about,” said Julie, speaking rapidly, “was that dopamine is active in more than just the nucleus accumbens. You know where else it’s found?”
</p>
<p>
Jason, his voice dry with fear, said, “Julie, I don’t think we have time for…”
</p>
<p>
“The substantia nigra,” said the girl. “It’s a part of your brain that controls movement. It’s the part that deteriorates in people with Parkinson’s disease. The pleasure centers might shape your desires, but the substantia nigra affects what you actually <em>do</em> about those desires.”
</p>
<p>
Outside, the voices argued. “Nothing? What do you mean, nothing?” shouted Sergey. The guard replied, “They scrubbed the car, boss. They even pulled off their VIN tags.”
</p>
<p>
“Now, what’s interesting about the substantia nigra,” Julie continued, “is that it functions by lateral inhibition. It takes all the possible different things you can do at any given moment, and chooses one based on learned reward expectation. See, your cerebral cortex comes up with dozens of different courses of action, all the time, every second you’re awake. Blink now or blink later? Left foot forward or right foot forward? Say ‘hello’ or say ‘goodbye’?…”
</p>
<p>
Rex, his face pale, kept sweeping desperately at the floor. “Fuck fuck fuck! He’s gonna know…”
</p>
<p>
Danny watched the Asian girl’s hands as she talked. He noticed a pattern to her movements. She wasn’t fidgeting. She was rehearsing.
</p>
<p>
“…But of all those actions you’re thinking of taking all the time,” Julie resumed, “only one ever wins out. And it’s the substantia nigra that makes the selection. Of all the hypothetical bodily movements you can possibly take, the substantia nigra chooses which one will get to activate the muscles. And the substantia nigra runs on dopamine.”
</p>
<p>
“Julie!” Jason barked. “Either help or shut up!”
</p>
<p>
From the alley, Sergey commanded, “You stay here! Guard door like you were supposed to! Eugene and I go take care of this ourselves.” 
</p>
<p>
Footsteps ascended the stairs outside.
</p>
<p>
Danny, his head spinning from fear, gasped, “Julie, what’s your point?”
</p>
<p>
Suddenly she stopped moving and locked eyes with Danny. “My point,” she said slowly, “is that dopamine is the substance that converts thought into action.”
</p>
<p>
She turned to look down at Rex on the floor hiding the mess of cocaine. She gave him an innocent smile. “And do you know what I’m thinking right now?” she asked him sweetly.
</p>
<p>
“What?” the pock-skinned  man growled, looking up from his crouched position next to her chair.
</p>
<p>
And she reached across the table, grabbed the clear unlabeled bottle, pulled out the stopper, and poured half a liter of hydrochloric acid onto his face. 
</p>
</div>
