<div class="chapsection">
<p>
<span class="caplead">Nothing in the world had any right</span> to look like what Danny saw before him. It belonged on a movie screen, tempered by the knowledge that it was nothing more than CGI and latex. It could not &mdash; must not &mdash; be real.
</p>
<p>
The man tore at his face, frantically trying to wipe away the hissing, steaming froth that was forming on his flesh. His gun clattered to the concrete floor as he rose. He ran blindly a few stumbling steps before collapsing to his knees. His screams crescendoed so loud and high-pitched that they scarcely seemed human. Strands of blond hair fell from his head, curling and writhing on their own upon the floor. Within his eye sockets were two deformed cauldrons of bubbling white foam. Greenish-yellow cauliflower-like globules of fat spilled out from areas that had once been cheeks and chin.
</p>
<p>
The stench was like vomit after a meal of putrescent meat.
</p>
<p>
And then there was an explosion of mechanical sound &mdash; a <em>rat-tat-tat-tat-tat</em>, like someone shoving a metal rod into the spokes of a spinning bicycle wheel. Several smoky black blurs streaked through the air, toward the shrieking faceless thing that had been Rex. He collapsed lifeless on the factory floor. The cardboard and packing peanuts on the floor around the body turned crimson. The screams mercifully ended.
</p>
<p>
Julie exhaled a satisfied, “Ahhhhh!” She stood where Rex’s gun had fallen, holding the blocky weapon awkwardly in both of her small hands. Smoke wafted from its barrel.
</p>
<p>
At the top of the stairs stood Eugene Mukhayev, and an immense middle-aged man that must have been Sergey. They stared with jaws slack, their eyes wide with horror and disgust.
</p>
<p>
Julie swung the gun upward, pointed it at them, and opened fire without warning or hesitation.
</p>
<p>
The two men ducked and took cover in the office directly behind them. Eugene returned fire from a small revolver, making sporadic half-blind shots from around the door jamb.
</p>
<p>
Julie shot in wild bursts, struggling against the recoil. Flakes of brick knocked loose from the walls around the stairs. The windows shattered, raining glass shards. The pale blue door’s plywood splintered into sand-colored streaks. Spent shell casings leapt from her gun, pinging upon the concrete floor.
</p>
<p>
One brass cylinder dinged the back of Danny’s hand, still scorching hot. At that moment, it dawned on Danny that he wasn’t a passive observer. The bullets from the office above were meant for him just as much as for the coke-addled girl.
</p>
<p>
He looked for somewhere to hide. Jason had already bunkered himself under the metal table.
</p>
<p>
Clenching his HERF gun, Danny dove to shield himself from the firefight. He ducked behind the largest, most solid-looking object nearby. 
</p>
<p>
Unfortunately that object was a blue 55-gallon drum filled with kerosene. 
</p>
<p>
An errant bullet from Eugene’s pistol plunked into the barrel, puncturing it. 
</p>
<p>
Danny had seen enough action movies and played enough first-person shooter games to know what happens when a barrel of flammable liquid gets shot. <span class="think">So this is it</span>, he thought quickly, more in impressions than words. <span class="think">A pretty awesome way to die, actually.</span> And the kerosene barrel exploded, ripping Danny to shreds in a blast of steel and flame.
</p>
<p>
But that didn’t actually happen.
</p>
<p>
The barrel did, however, begin leaking its clear, pungent contents all over Danny’s sweatshirt. Kerosene poured like a demon’s urine stream, forming an iridescent puddle on the concrete floor.
</p>
<p>
The <em>rat-tat-tat</em> of Julie’s firearm abated, and she bounded up the stairs. Eugene had stopped shooting. From the office room came the spinning clicks of a revolver cylinder and the ding of empty rounds upon the floor.
</p>
<p>
Julie suddenly yelled, “Oh, you’re in trouble now!” She squeezed the trigger, and through the open doorway she sprayed the office wildly with aimless gunfire. Bullets tore into the floor, the walls, the desk, leaving gouges like clawmarks from a wild beast.
</p>
<p>
The office’s front door swung open. The two gangsters fled outside, crouching low to dodge the girl’s gunfire, and slammed the heavy outer door shut behind them.
</p>
<p>
Julie continued firing, until finally the weapon’s bolt made an idle click and ceased moving. An abrupt silence closed around its wake.
</p>
<p>
Realizing that she was out of ammunition, Julie wasted no time. She sprinted to the other side of the small office and twisted the front door’s deadbolts shut.
</p>
<p>
Outside, the men pounded against the front door and struggled with the locks, but they were seconds too late. They tried kicking it, bashing it, even shooting it, but the outer door wouldn’t yield. 
</p>
<p>
“Don’t bother, man,” the guard outside insisted. “We made sure <em>nobody</em> could bust in. Your orders, remember?”
</p>
<p>
Eugene yelled, “God fucking damn it, Deshaun! You standing in alley the whole time? You don’t hear the shooting? You don’t think to come up here and help us maybe?”
</p>
<p>
“You guys told me to stay out here. I thought Rex had you covered. I heard screaming. I figured you were, you know, working them over.”
</p>
<p>
Sergey answered, “That screaming <em>was</em> Rex.”
</p>
<p>
“Holy fuck. Guys, are you alright?”
</p>
<p>
“No, I’m not alright,” Eugene grumbled. “Look what that girl did to my jacket! This is Italian custom-made lambskin! See here? Bullet graze. Here? Torn on glass. I swear to fucking God, that bitch is not making it out of there alive! I’ll tear that little whore’s throat out! I’ll kick her teeth in with my bare hands!”
</p>
<p>
Sergey said, “You kick with your hands, Zhenka?”
</p>
<p>
Eugene sputtered, “I… with my… Shut up!”
</p>
<p>
Inside, Julie leaned against the metal door, breathing heavily. A huge grin consumed her face. “Woooooohoooooo!”
</p>
<p>
The rows of 55-gallon drums had served as a backstop for Eugene’s bullets. Most of them were leaking profusely, coating the floor of the factory in a mixture of kerosene and acetone. Styrofoam dissolved into thick bubbling puddles, filling the room with a soft hiss. Soaked in kerosene, Danny’s sweatshirt felt damp and heavy. The mixed stench of jet fuel and nail polish remover assaulted his nose and burned his lungs. It was growing progressively harder to breathe. His eyes stung.
</p>
<p>
Julie struggled with some piece of furniture in the office. Rattling sounds echoed from upstairs. “Hey, you!” she called out.
</p>
<p>
“Me?” asked Danny.
</p>
<p>
She poked her head out through the broken interior door. “Do me a favor. There’s this desk up here with a couple drawers that I want to get into. It’s locked.”
</p>
<p>
“And?” asked Danny.
</p>
<p>
“Get the key,” she answered.
</p>
<p>
“From where?”
</p>
<p>
 Julie pointed toward the center of the room. Danny followed her finger.
</p>
<p>
She was pointing at Rex’s body.
</p>
<p>
Danny’s stomach lurched. He felt his pulse in his throat. His vision began to dim &mdash; the world became oddly flat as though projected on a screen. He gulped for air, but the searing mix of chemicals served only to make him feel even sicker.
</p>
<p>
“Oh for God’s sake,” Julie said. “Grow some fucking balls!”
</p>
<p>
Danny shook his head just to stay conscious. <span class="think">This isn’t real</span>, he told himself. <span class="think">This is just a video game. I’m at home right now, sitting on my nice comfy leather couch, in the middle of my 7.1 surround sound setup, in front of my 60” HDTV, playing a really awesome new game on my PlayStation. It’s very, very immersive.</span>
</p>
<p>
He maneuvered toward the body, feeling like he was detached and floating. Up close, he could tell by parallax that the acid-burned face model was rendered as a genuine triangle mesh with Bezier edge-smoothing rather than a more conventional programmatic shader, and he was deeply impressed by the PlayStation’s ability to handle such a high polygon count. He watched his hand before his eyes as it prodded blood-soaked pockets. Danny found a keychain with several keys, a Ford car remote, and a tiny plush Kurt Cobain doll. He added the keychain to his inventory. He then hurried to the stairs, eager to get up to the office and away from the noxious fumes that were depleting his health bar.
</p>
<p>
Up in the office, Julie and Jason were both waiting for him. Julie stood by the desk, impatiently wrestling with the locked drawer. Jason sat on the floor, looking green and pale &mdash; the irritant gases were hitting his middle-aged cardiopulmonary system hardest of all.
</p>
<p>
Danny fiddled with the keychain until he found a small brass key, suited for a desk. He unlocked the drawer and rifled through it.
</p>
<p>
“So, anything good in there?” asked Julie.
</p>
<p>
“Well,” answered Danny, “there’s this…” He withdrew a narrow metal box &mdash; an extra magazine for Julie’s gun. Slits in the magazine allowed Danny to see about fifty bullet cartridges stacked neatly inside.
</p>
<p>
Julie nodded approvingly and took the ammunition. She began pulling and pressing on random parts of the gun, trying to figure out how to eject the empty magazine and replace it with the full one.
</p>
<p>
“…And this,” Danny said, slapping a large, heavy key onto the desk.
</p>
<p>
“Oh, I’ve seen that before,” said Julie. “When they bring new equipment in. It’s for those big loading doors downstairs.” 
</p>
<p>
Danny checked on Jason, who seemed to be improving now that he was away from the spill of kerosene and acetone. The smell of the chemicals was less intense in the small office. From the bathroom came the whirring of an overhead ventilator.
</p>
<p>
Danny turned to the computer on the desk and began searching for something they might be able to use to escape. An initial click-through of the desktop folders suggested that this computer probably contained nothing but pirated movies and amateur porn. 
</p>
<p>
As he searched, he heard the conversation in the alley below.
</p>
<p>
“Guys, we can get in just fine,” said the guard. “I have keys to that door up there.”
</p>
<p>
Eugene replied, “And what? Waltz right in? Do we know how much iron they have?”
</p>
<p>
“No,” answered the guard guiltily.
</p>
<p>
“Fuck, Deshaun, you did not search them before they go in?” Sergey scolded. “Okay, I’m not sending anyone in there without head-to-toe armor. Is not worth losing another man.”
</p>
<p>
The guard suggested, “We could just crack the door open and lob a few grenades in.”
</p>
<p>
Sergey grumbled, “That would break the vial.”
</p>
<p>
“Riot grenades, then,” said the guard. “Fill the place up with tear gas, choke ‘em out. Or flash-bangs &mdash; stun them, then blow them away before they know what the fuck’s going on.”
</p>
<p>
Eugene scoffed, “You think we have giant stash of grenades in our trunk, Deshaun? Oh sure! Welcome to Grenade Buffet! Twelve ninety-nine, all you can throw!”
</p>
<p>
Deshaun replied, “Guys, you want grenades? I can get you grenades. Just one call to my boys. Deliver in twenty minutes or less. My phone’s right here.”
</p>
<p>
Back in the office, that last line piqued Danny’s interest. He abandoned the computer and, with HERF gun in hand, walked to the exterior wall, listening intently to try to triangulate exactly where the voices were coming from.
</p>
<p>
“Put your phone away!” Eugene ordered.
</p>
<p>
“It ain’t a big deal, man” the guard said. “A dude owes me a favor.”
</p>
<p>
Danny flipped a switch. Small fans whirred to life.
</p>
<p>
“That’s not the point!” Eugene insisted. “Put it away now!”
</p>
<p>
“I… okay…” said Deshaun. “But I don’t…”
</p>
<p>
Inside the office, there was a soft “<em>bonk!</em>”
</p>
<p>
“Ow!” yelled Deshaun. “What the <em>fuck</em>?”
</p>
<p>
A broken cellphone clattered to the ground.
</p>
<p>
Eugene groaned, “Fucking great. Told you so!”
</p>
<p>
The HERF gun emitted a quiet, high-pitched whine as its capacitors recharged.
</p>
<p>
Below, Sergey started coughing and rumbling.
</p>
<p>
“Seryozha! Are you alright?” asked Eugene.
</p>
<p>
Sergey cleared his throat forcefully, sounding like a whinnying horse. “I’m fine. Shut up.” 
</p>
<p>
Deshaun barked, “The fuck happened to my phone, man?”
</p>
<p>
“The nerdy guy has some kind of electronics gun,” said Eugene. “It kills phones.”
</p>
<p>
Sergey added, “And cars. That asshole destroyed my Roadster.” 
</p>
<p>
“That’s just because it was electric, I think,” Eugene said. “It won’t work on all cars. My Beamer should be okay.”
</p>
<p>
“Even with all its little extras?” said Sergey, his voice still hoarse.
</p>
<p>
“What little extras?” Eugene asked defensively.
</p>
<p>
<span class="think">Yes, what little extras?</span> thought Danny.
</p>
<p>
“All the options you always brag about,” Sergey said. “When you buy that thing, you come to me saying, ‘Oh, uncle, look at fancy new toy! She is with the remote ignition, she is with the satellite radio, she is with the GPS, she is with the BMW Assist plan…’ ”
</p>
<p>
<span class="think">She is with the spectrum profile of a symphony orchestra</span>, Danny thought. He checked the HERF gun’s lamps. They were green again.
</p>
<p>
Eugene mumbled, “Shit, you think it…”
</p>
<p>
There was a low “<em>bonk!</em>”, and a sharp crack from the alley below.
</p>
<p>
Eugene screamed, “Fuck, no no <em>no</em>!” A car door was flung open. “My Beamer! My beautiful brand new 650i Beamer!” Footsteps ran to the side of the alley with Jason’s Lincoln Navigator. You…” A shot rang out. “…God&mdash;” <em>Bang!</em> “&mdash;damned…” <em>Bang!</em> “…dick!” <em>Bang!</em> <em>Bang!</em> <em>Bang!</em>  
</p>
<p>
Danny giggled.
</p>
<p>
Sergey made several loud, pained grunting noises.
</p>
<p>
Deshaun nervously said, “Hey… Hey, Sergey. You okay, boss-man? You don’t look so good…”
</p>
<p>
The large Russian snapped back gruffly, “Mind your own fucking business!”
</p>
<p>
Eugene abandoned his tantrum and spoke a few words of Russian, his voice heavy with concern.
</p>
<p>
“I said I’m fine, God damn it,” Sergey rumbled defiantly. “Now let’s think of way to… to… How you would say?”
</p>
<p>
Deshaun offered, “Fuck these shitheads up?”
</p>
<p>
“Exactly.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">The <em>rat-tat-tat</em> of Julie’s gun</span> burst out suddenly. She fired a few bullets through the broken office windows, announcing that she had successfully reloaded. Danny couldn’t find anything helpful on the bullet-scarred computer, but Julie had put it to use to figure out how to operate her firearm. Between Wikipedia, YouTube, and some gun enthusiast websites, she was able to identify it as a MAC-10 and determine how to swap the magazine and load a round into the chamber. 
</p>
<p>
“Jason. Can’t you, like, talk us out of here?” Danny pleaded.
</p>
<p>
“And how do you propose I do that?”
</p>
<p>
“I don’t know. Negotiate or something?”
</p>
<p>
“We’re in no position,” Jason scoffed. “Negotiation isn’t some magic spell where I open my mouth and suddenly everyone becomes lovey-dovey. Negotiation takes leverage. Which we don’t.”
</p>
<p>
“We still have our phones. Is there anyone you can call?”
</p>
<p>
“The cops?” Jason offered. “But, um…” He gestured out to the room &mdash; to the cocaine on the desk, to the bullet holes in the wall, to the mangled corpse below. “I can make shit up, Danny, but I can’t think of any innocent way to explain what we’re doing here.”
</p>
<p>
Danny sighed. “So. Death or jail. That’s our options?”
</p>
<p>
Jason looked down somberly and shrugged.
</p>
<p>
Julie, for her part, admired herself in the bathroom mirror. She postured and posed with the gun, pouting her lips and giving sultry looks, pressing it up against her body like an action movie femme fatale &mdash; the visual impression of erotic danger greatly diminished by her pajamas and bunny slippers. “God, you guys are a bunch of whiners.”
</p>
<p>
Jason asked, “Got any ideas, Julie?”
</p>
<p>
“Yeah, I do,” she said, trying out a <em>Charlie’s Angels</em> pose and finding that it was best done in heels and a side-slit skirt rather than borrowed sweatpants. “But you guys are too chickenshit for it.”
</p>
<p>
“Try us,” Jason insisted.
</p>
<p>
“No,” she said. “I’m sick of explaining shit to you guys. Ever since you got here, you’re all talk talk talk. Fuck that. You want to get something done, just fucking do it.”
</p>
<p>
“Tell us what you have in mind, Julie,” Jason coaxed.
</p>
<p>
In response, Julie marched to the desk and grabbed the large, heavy key. “You.” She jabbed a finger at Danny’s chest. “When I give a signal, start banging on this door. Pound on it. You know, create a distraction. Think you can handle that?” She then skipped down the stairs, her slipper-clad feet making soft syncopated landings. Down in the factory, she bounded toward the large metal double doors at the front of the room. 
</p>
<p>
From the inside, the loading doors were held closed by a complex mechanical arrangement of steel crossbars, operated by a large lever. A heavy padlock kept the lever in place. Slowly and quietly, struggling against the cocaine to keep her fingers from shaking, Julie slid the key into the padlock and discreetly freed the lever. With the lock undone, she began a series of practice pantomimes on the latch mechanism. After a dozen or so rehearsals, the girl closed her eyes, concentrated, and took several breaths. Finally, she looked up at Danny and shook her fist in the air.
</p>
<p>
Danny slapped his hand hard against the locked door, sending out metallic reverberations. He was answered with a gunshot from outside, accompanied by the “<em>plink!</em>” of a bullet. 
</p>
<p>
Danny awkwardly called, “Hey, uh, Eugene! Eugene, are you there?”
</p>
<p>
From the other side, Eugene said, “Did you hear that? Did this fucker just call my name like he’s my buddy? You got something to say to me, dickwad?”
</p>
<p>
“I want to, uh, negotiate?” Danny shouted.
</p>
<p>
Sergey’s deep voice responded, “You want to talk, you talk with me.”
</p>
<p>
Danny replied, “I.. Uh… I was just thinking, that, uh, you know, we have the vial in here… You know, the vial you want… Or at least, I assume you want… So, like, maybe if you wanted to, uh, like…”
</p>
<p>
He was interrupted by a loud metallic groan from below.
</p>
<p>
With as much strength as her small arms could muster, Julie yanked the lever that drove the mechanical latches holding the loading doors shut. The large metal double doors came unmoored from their sockets, and Julie shoved one of them narrowly open.
</p>
<p>
“Surprise, motherfuckers!” she screamed, and let loose a hail of gunfire.
</p>
<p>
The men in the alley shouted and dove for cover, Deshaun behind the exterior stairwell and the two Russians behind their BMW. Julie crouched in the doorway, using the large metal doors as a shield, steering the MAC-10 with both hands. The rattle of her gun was answered by the matching report of the black man’s identical firearm and the sporadic bangs of Eugene’s revolver.
</p>
<p>
The gap in the doors put the exterior stairwell directly in Julie’s line of fire. Her bullets made high-pitched plinks as they grazed off of the iron railing, zinging through wide gaps in the struts between the steps. The African-American guard aimed around the side of the railing and fired back.
</p>
<p>
Julie dropped to the ground just in time. The spray of hollow-point bullets from Deshaun’s gun had been meant for Julie’s head, but instead hit the narrowly opened door behind her. They squashed against the inside of the metal door, pushing against it and bouncing idly away as flat little mushrooms of lead that ricocheted into the factory. The door behind Julie began to swing wide open from the kinetic energy of the deadly projectiles.
</p>
<p>
On the ground, Julie kept firing. The stairwell, she noticed, didn’t quite reach all the way down to the ground. There was a gap of approximately three inches between the asphalt and the bottom-most stair, and in that gap she could see Deshaun’s shoes. She turned the MAC-10 horizontally, rested her hand on the ground, and seized the opportunity.
</p>
<p>
The burst of bullets ripped through the guard’s foot and ankle. He let out a sustained, choking grunt, and fell sideways onto the stairwell, landing on his knees. He tried using his arms to push himself off the stairs and back into an upright position, grunting through gritted teeth. When his leg collapsed under him a second time, he looked down at his foot, and that’s when he started screaming.
</p>
<p>
Laying prone on the stairs made him a much easier target for Julie. There were gaps in the ironwork to permit a bullet to pass. She stood up, lifted her firearm, and prepared to spray several more bullets at him, counting on at least one to score a killing shot.
</p>
<p>
Instead, she flew backward into the factory.
</p>
<p>
The echoes of the last bang from Eugene’s pistol resounded through the alley. The ricochet of Deshaun’s bullets had pushed the door open wide enough to afford the crew-cut Russian a clear shot at the small Asian girl.
</p>
<p>
Julie fell on her tailbone and landed face-up just inside the large loading doors. Her MAC-10 was still in her hand.
</p>
<p>
Lying on her back, she stared upward at the ceiling’s gymnasium lights through a blank, confused look. She tried to rise, but her abdominal muscles wouldn’t obey. 
</p>
<p>
On one side of her abdomen, her sweatshirt bore a small moist circular stain of blood, barely the size of a penny.
</p>
<p>
The stain quickly grew much bigger.
</p>
<p>
She managed to turn over and lift herself up on an elbow. 
</p>
<p>
She coughed wetly. A thick stream of blood flowed out from her mouth.
</p>
<p>
There she remained frozen, propped on one elbow. Her breathing became short, shallow. Her skin paled, fading to a washed-out greenish hue. Her dark, wide-pupiled eyes glazed over. She began to shiver.
</p>
<p>
Hearing the sound of movement just outside the loading doors, she slowly turned her head to look outward. A man’s shadow darkened the doorway. Julie lifted the MAC-10 in one hand and waved it at the entrance, straining against the gun’s weight. The weapon shook in her weakening hand. She squeezed the trigger. The recoil knocked the firearm out of her grasp.
</p>
<p>
The muscular, leather-clad figure of Eugene wheeled into the doorway. He fired two quick shots squarely into Julie’s ribs and spun back out of sight.
</p>
<p>
Julie collapsed. A final wet, rasping breath escaped her throat, carrying with it a red, bubbling froth. Her entire body twitched once, and fell still. 
</p>
<p>
The room was silent. Blood pooled around her.
</p>
<p>
Eugene again appeared in the doorway, crouching low and glancing around cautiously. He reached through the entrance just far enough to grab a bunny-slipper-clad ankle, and dragged her lifeless body out into the alley. A streak of blood on the floor marked her exit, and she was gone.
</p>
<p>
There was the sound of rustling clothing. 
</p>
<p>
“<em>Oppah!</em>” said Eugene. “Seryozha, look what the good little girl has for us!”
</p>
<p>
“She had the vial on her?” asked Sergey.
</p>
<p>
“Yes!” Eugene said happily. He walked toward Sergey. “Here you go, Seryozha. Is present from your favorite nephew!”
</p>
<p>
Sergey responded in Russian.
</p>
<p>
“Now we go in and teach those fuckers a lesson?” asked Eugene.
</p>
<p>
“No,” said Sergey. “Now we save our soldier.”
</p>
<p>
Deshaun grunted between shallow breaths.
</p>
<p>
“Keep your feet up, Deshaun,” Sergey commanded. “You lose a lot of blood already. Foot is a bad place to get shot. Blood gushes out like from faucet. Now hold on, I tie my belt around the leg, make less blood flow, okay?”
</p>
<p>
Deshaun said through gritted teeth, “Am I gonna walk, boss?”
</p>
<p>
Sergey responded, “Let’s make sure you not to go into shock, then we worry about you dancing ballet with Rosie someday in a future. We need get you to doctor, but we can’t start Eugene’s car. We take yours. You have keys? Is it close?”
</p>
<p>
“Yeah. It’s around the corner,” said Deshaun. Keys jingled.
</p>
<p>
Sergey instructed, “Zhenya, stay here with him, keep his feet up. I drive over.”
</p>
<p>
“Bad idea, Seryozha,” said Eugene tensely. “You bring that ride here, it’ll get zapped by that fucking electric gun.”
</p>
<p>
“Alright, then help me carry him,” Sergey directed.
</p>
<p>
“What? And let those two guys get away?” Eugene protested. “They’re in there right now! How about just we go in, take care of them, <em>then</em> we go fix Deshaun.”
</p>
<p>
“We <em>not</em> rushing in there, Zhenka!” Sergey insisted. “They could be armed, plotting ambush. Or they set up traps with bottles of chemicals. Zhenya … God forbid anything happen to you like what happen to Rex…”
</p>
<p>
The two men talked briefly in Russian. The discussion ended with a few grunts as Sergey helped the injured black man balance on his remaining foot. The two of them coordinated a hurried three-legged walk down the alley. Deshaun groaned out words of gratitude through gritted teeth.
</p>
<p>
As for Eugene, the silhouette of his leather-jacket-clad body, crouching with gun in hand, reappeared in the doorway downstairs. He carefully scanned the reeking slosh-covered factory room, eyeing potential hiding places amongst the packing materials and bullet-riddled equipment, and said tauntingly, “Come out, come out, wherever you are!” 
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">There was barely enough room under the desk</span> for both Danny and Jason to huddle together, terrified. They could hear the Russian stalking the room below. His cautious exploration would lead him to the office in due time. If they could just buy a few seconds to make it to the car… 
</p>
<p>
Danny eyed the front door with bitter frustration. It was only a few feet away, but there was no way to open it and get down the stairs without being seen. The athletic mobster would gun them down in the alley before they could reach the SUV. Alone and in peak condition, Danny might have been able to make a dash for it, but Jason would stand no chance. And between the blood loss, the sleep deprivation, and the noxious fumes, Danny could barely blink without passing out from exertion.
</p>
<p>
Downstairs, the Russian’s footsteps squished against a sheet of cardboard soaked in the reeking slurry.
</p>
<p>
Danny’s eyes went wide. He suddenly gasped.
</p>
<p>
“Are you alright?” Jason asked in hushed tones.
</p>
<p>
“Jason! What are the formulas for kerosene and acetone?” Danny whispered.
</p>
<p>
Jason blinked at him.
</p>
<p>
“I need a bond energy table…”
</p>
<p>
“What are you talking about?” Jason asked.
</p>
<p>
“I’m thinking,” Danny replied, “that the floor down there is soaked with organic chemicals. And I don’t know jack about chemistry, but I do know there’s one thing those substances have in common.”
</p>
<p>
“What’s that?” asked Jason.
</p>
<p>
“They’re flammable.” Danny reached over the top of the desk and groped around blindly. “See, ever since I saw those barrels get shot, I’ve been thinking… The barrels were <em>full</em>, right? No oxygen to react with. Ergo, no combustion… But out <em>here</em>, in the open air, with those big doors downstairs open…” He drew his hand back. “Damn it. These guys sell cocaine for a living but apparently they’re too straight-edge to smoke.”
</p>
<p>
Jason looked at him hesitantly. “It’s okay, Danny. It was a good idea. Nobody can ever say you weren’t resourceful until the end.”
</p>
<p>
“Fuck the end,” said Danny. “I’m not done yet.”
</p>
<p>
He looked around. There was nothing within reach but shards of broken glass. And his HERF gun.
</p>
<p>
His HERF gun, with its 3-megawatt S-band magnetron powered by pulsed electrical discharge from a 600-farad ultracapacitor bank.
</p>
<p>
Danny silently unscrewed the magnetron horn. Cables protruded from the back of the megaphone-shaped component. He picked up a sharp piece of broken glass and used it to pry the epoxy insulation away. The shard sliced his palm. He found himself leaving crimson fingerprints all over the magnetron horn.
</p>
<p>
From the factory below, rustling steadily drew closer.
</p>
<p>
He cut one pair of cables free, and put them in his mouth one at a time to strip away the insulation with his teeth. He took each exposed, frayed metal tip between his fingers and twisted it into a fine point. When he was done, he tied the two wires to the end of the PVC pipe, leaving a quarter-inch gap between the exposed silvery ends.
</p>
<p>
Danny frowned at the contraption. “What do you think?” he asked Jason.
</p>
<p>
“What’d you do?” Jason returned.
</p>
<p>
“Made the world’s most overpowered barbecue lighter,” Danny replied. “Assuming it works. We don’t have time to test it. It takes about thirty seconds to recharge. I don’t want to risk it. Now, help me find something to ignite…”
</p>
<p>
Jason found a loose sheet of paper, careful to keep it from making too much rustling noise.
</p>
<p>
Danny shook his head. “I need something with more heat capacity. Something that will stay burning long enough to raise the temperature to its flash point. There’s got to be something here that will hold a decent flame…”
</p>
<p>
“Your shirt,” Jason said. “It’s soaking.”
</p>
<p>
“Yeah, it’s pretty uncomfortable, but that’s the least of my… Oh!”
</p>
<p>
Danny wriggled awkwardly in the cramped space. The wrestling match with the kerosene-soaked fabric seemed interminable, but Danny ultimately prevailed. He pulled the damp floral-print away from his head, and laid it down as a wad on the linoleum floor.
</p>
<p>
He lifted the modified HERF gun and placed its tip, with the two exposed ends of wire, against the cotton heap. After giving the circuitry one last visual inspection, he pulled the trigger.
</p>
<p>
The gap between the exposed wires flashed with a bright blue spark &mdash; accompanied by a cracking, zapping buzz. Danny cursed himself for forgetting one key characteristic of pulsed-current open-air spark gaps: they’re <em>loud</em>. 
</p>
<p>
Eugene responded to the noise by firing his handgun. It was much louder. 
</p>
<p>
Bullets whizzed in through the shot-out windows, slamming into the opposite wall of the office. A few plinked against the exterior of the office itself, forming fresh dimples in the metal wall. Running footsteps filled the gaps between the shots.
</p>
<p>
The sweatshirt ignited in a bright orange flame, burning ferociously in the fume-laden air.
</p>
<p>
Danny spun out from under the desk and, keeping his head down, extended an arm to help hoist Jason out behind him. The overweight man grunted and rose to his feet, crouching as low as his aging knees and spine would allow.
</p>
<p>
“Go!” Danny hissed, pushing him toward the front door. 
</p>
<p>
Still crouching, Jason quickly made his way to the door and reached up to click the locks open. 
</p>
<p>
Bullets zoomed through the broken windows. Jason flung the door open, sending a rush of air inward. The sweatshirt’s flames pranced with added vigor, sending specks of burning thread wafting upward. Jason’s heavy footsteps pounded down the iron stairs outside.
</p>
<p>
Eugene sprinted toward the loading doors. Equipment crashed around him as he shoved pieces aside. His feet splashed in chemical puddles.
</p>
<p>
Danny reached down. With one hand he grabbed his HERF gun. With the other, heedless of the pain, he grabbed the fiery sweatshirt. He hurled the fireball through the broken window down into the factory, and dove for the door. 
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">
The factory was ablaze before</span> 
the burning sweatshirt even touched the floor. The volatile vapors of acetone flashed first, sending an ignition wave racing out to the corners of the room. The Styrofoam and cardboard followed, lifting dirty, noxious residue into the air as they combusted. In a blink, the small factory transformed into a roaring inferno.
</p>
<p>
Danny had just barely cleared the landing when the wave of heat blasted out behind him, carrying glowing embers and ash amidst arcs of flame. 
</p>
<p>
Below, the loading doors swung open on their hinges and slammed against the side of the building, an enormous spout of fire shoving them apart in one thrust like a great demonic hand. 
</p>
<p>
And within that glowing spout of red fire was the black silhouette of Eugene.
</p>
<p>
The Russian had been mere steps from the doors when the room erupted. The wave of overpressure hit him in the back like a charging bull. He fell halfway out of the doorway, landing hard against the street. 
</p>
<p>
Eugene maintained enough presence of mind to keep his face down as gusts of flame billowed above. The Russian crawled toward his BMW for cover.
</p>
<p>
An alarm wailed inside the building. Water gushed from sprinklers in the factory’s high ceiling. White mist poured out into the alley alongside the red flames and black smoke. Streams trickled to the street from the factory floor, drawing streaked wet lines through the trail of blood that ran to Julie’s pale, lifeless body on the asphalt outside.
</p>
<p>
Danny raced down the stairs with his butchered HERF gun. The moment he cleared the last stair and hit the pavement, he bounded toward the SUV. He hoped to see Jason in the driver’s seat, starting the engine.
</p>
<p>
Instead, Jason stood despondently next to the Navigator, looking down. All four tires had been shot out. Jason turned to Danny with an expression combining panic and nausea.
</p>
<p>
On the ground outside the factory, on the opposite side of the BMW, Eugene rolled frantically to extinguish himself. The Italian lambskin material of his jacket melted off in rivulets from his sides and sleeves.
</p>
<p>
Danny scanned the alley. Here and there, amid dumpsters and discarded pallets, a handful of other cars had parked there overnight. One was a red Ford F-150. Its rear bumper and window were covered with stickers of Seattle grunge and metal bands &mdash; logos of Nirvana, Pearl Jam, Soundgarden, Queensrÿche, and Alice in Chains. 
</p>
<p>
Danny felt in his pocket, and pulled out the keychain he had lifted from Rex’s body &mdash; the one with the Ford remote and the Kurt Cobain plushie. He tried a button on the remote. The taillights of the red Ford blinked a greeting.
</p>
<p>
Jason and Danny wasted no time getting to the late Rex’s pickup truck. The two men scrambled into the Ford. Force of habit drove Danny to the passenger’s side, and he passed the keys to Jason. The moment the key turned, the ignition was drowned out by the distorted chords of a grunge guitar riff that blasted out at jarring volumes. Danny switched off the stereo while Jason hit the gas.
</p>
<p>
Eugene climbed to his feet, covered in black soot. His jeans were charred, his hair and eyebrows were singed, and his jacket was unrecognizable. In the distance, at the end of the alley, he could see the car turning to the lanes of busy fulfillment houses, the two men inside escaping to populated safety. Eugene’s roars of anger echoed behind them.
</p>
</div>