<div class="chapsection">
<p>
<span class="caplead">
Clanging and clattering came from the cookware cabinet</span> as Danny dug around. With an accompaniment of metallic percussion, he produced a two-gallon stainless steel pot, complete with lid.
</p>
<p>
“That’ll be perfect,” said Tina. “Here, wipe down the inside.” She tossed him some alcohol wipes. 
</p>
<p>
Danny watched her as she worked at his kitchen counter. She had arranged a row of bottles and containers. The sleeves of her simple white button-down shirt were rolled up to her elbows, and her hands were wrapped in a fresh pair of rubber gloves. She carefully measured and poured powders into the Pyrex mixing bowl.
</p>
<p>
“Hey, Danny,” she said. “Could I borrow a paper and pencil?”
</p>
<p>
“Sure,” he said, scrubbing the pot with the alcohol wipes. “What for?”
</p>
<p>
“I want to sanity-check some of my ratio estimates,” she said, tapping at the Pyrex bowl. “That pot is, what, two gallons? You don’t happen to know what that is in liters off the top of your head, do you?”
</p>
<p>
“7.6,” he replied almost instantly.
</p>
<p>
Tina stared at him slackjawed. “I… was joking…”
</p>
<p>
Danny simply shrugged. “Actually, more like 7.57,” he added after a moment.
</p>
<p>
She blinked. “Right. So, about that pencil and paper…”
</p>
<p>
“In the bedroom,” Danny said, pointing. “On the desk, next to the computer.” 
</p>
<p>
Tina walked away toward his bedroom. Danny’s gaze followed her. Those black slacks moved with a wonderfully mesmerizing sway. He felt himself drawn to her by a force he could only describe as electromagnetic. Through the doorway he could see her standing by his computer desk. He could so easily just come up behind her, put his hand on her waist, feel her tight body through the fabric of her shirt, pull her toward him. Hear her gasp in surprise and delight and press herself against him. Run his fingers through her hair, sweep it aside from the back of her head, expose her neck. Put his lips on her ear and tug gently at her earlobe, nibble lightly, trace his mouth down along the nape of her…
</p>
<p>
He dropped the two-gallon pot.
</p>
<p>
He managed to duck down and catch it before it crashed on his kitchen tile. When he stood back up, Tina was returning. 
</p>
<p>
“Fill the pot with hot water,” she instructed, “and pre-heat the oven to 450.” She put the paper on the counter and began writing, her mind sharply focused.
</p>
<p>
Danny did as told. When he went to prepare the oven, he saw the clock above the stove. The time was 2:17am.
</p>
<p>
His exhaustion returned to him like a lead shawl suddenly draped upon his shoulders. For a few moments, he barely felt strong enough to stand. He put the pot into the sink and began filling it, leaning heavily against the counter with both hands. With unfocused vision, he watched the hot water rise against the stainless steel, swirling and sloshing and effervescing. 
</p>
<p>
Tina’s voice came from behind him. “Pssst! Incoming!” He turned around and saw her standing with the Pyrex bowl in both gloved hands, filled with an off-white powder of flour-like consistency. She stepped to the sink beside him and poured the powder into the pot, stirring vigorously with a metal spatula as the water level rose.
</p>
<p>
She stood literally within arm’s reach of him. From here, he could see the smudges on her face from hastily applied makeup. He could smell the traces of her floral perfume.
</p>
<p>
He caught himself subtly leaning into her. He wasn’t sure whether or not she caught him doing it; she simply kept standing there, stirring the pot as it filled, her eyes fixed downward to her task. He did notice, though, that her cheeks were blushing, and her lips were drawn up in a coquettish smile. 
</p>
<p>
The water neared the brim of the pot. Tina shut off the tap, and silence abruptly filled the house. She stood motionless for a moment, her hand frozen on the water knob.
</p>
<p>
Danny looked down nervously at the pot.
</p>
<p>
Tina broke the stillness with a sharp inhale. “Alright then,” she said. “So, let’s get this stuff semi-sterilized, I guess.”
</p>
<p>
Inside the pot, the broth simply looked like saltwater &mdash; slightly cloudy and silty, like ocean brine. She closed its lid, carried it to the stove, and loaded it into the pre-heated oven.
</p>
<p>
With the water busy heating, Danny wandered back around to the opposite side of the counter and grabbed a seat. “So, what happens now?” he asked, resting his head limply on his hands.
</p>
<p>
“In about ten minutes,” said Tina, “the water will hit a rolling boil. When that happens, I’ll turn down the heat and let it simmer for a while.”
</p>
<p>
Danny let out a big yawn and said, “Cooooool.”
</p>
<p>
Tina came around to sit next to him. “A real autoclave would suck out all the air and then blast it with pressurized steam for twenty minutes. What we’re doing here is less thorough, but hopefully it’ll get the job done. We’ll lose some water in the boiling, so the broth will be a little thicker than it’s supposed to be. But hopefully the <em>E. coli</em> will like that.”
</p>
<p>
Danny folded his arms lazily on the granite countertop. He groggily said, “Yay, happy germs,” before laying his head down and closing his eyes.
</p>
<p>
Tina chuckled. “Tired?”
</p>
<p>
Danny snorted. “So tired…”
</p>
<p>
“Aww.” She reached out to touch his head. Her fingernails scratched lightly at his scalp. Barely able to stay conscious as he already was, the sensation sent his mind floating off into a happy place. A contented hum, almost a purr, escaped beneath his breath.
</p>
<p>
A clanking, rattling noise emanated from the oven.
</p>
<p>
Danny rose quickly and looked at it with fear, mustering whatever alertness he could.
</p>
<p>
Tina pulled her hand back and giggled at him. “It’s just the lid. The water’s starting to boil. We’ll give it another few minutes.”
</p>
<p>
“And then it’ll be sterile?” asked Danny.
</p>
<p>
Tina shook her head. “Not by a long shot. ‘Sterile’ literally means that there’s nothing alive. There’s no way we’ll achieve that without a real autoclave. The air, the water, the inside of the pot, it’s all teeming with life.”
</p>
<p>
“No, the water’s clean,” Danny murmured. “It just came out of the sink.”
</p>
<p>
“Heh. Try looking at tap water under a microscope sometime,” Tina replied.
</p>
<p>
“But we’re boiling it,” Danny said quizzically. “And we scrubbed it with alcohol.”
</p>
<p>
“All of that helps, yes,” said Tina. “But there are bacteria that can survive alcohol, boiling, fire, pressure, acid… You name it, they can live through it. They harden their cell walls and form endospores, and they’re basically indestructible.”
</p>
<p>
“So what’s the point?”
</p>
<p>
“Well, just because we can’t get it perfect doesn’t mean we can’t get it good enough to work,” said Tina. “See, in a lab we’d want the <em>E. coli</em> to be the only living things in the entire broth. But in practice, we just need them to be the dominant lifeform in there, not necessarily the exclusive one. Different strains of bacteria will usually try to kill and eat each other anyway, so really all we have to do is give our <em>E. coli</em> a leg up on the competition. We kill as much stuff as we can, and trust the <em>E. coli</em> to handle the rest on their own.”
</p>
<p>
Danny grunted and nodded, and put his head back down.
</p>
<p>
“The real trick,” Tina continued, “will come afterwards. See, when we take the broth out of the oven, we’ll need to cool it down just the right amount. If we put the bacteria in when the water’s still boiling, it’ll kill them. But if we let it cool all the way down to room temperature, they won’t grow. We need to find a way to keep the broth just warm enough for incubation.”
</p>
<p>
Danny nodded. “And how warm is that?” he asked.
</p>
<p>
Tina walked over to the bags and pulled out the digital thermometer. “Body temperature,” she said. “Ninety-eight point six degrees Fahrenheit.”
</p>
<p>
Danny made an affirmative zombie-like noise.
</p>
<p>
“But keeping it there will be tricky,” Tina said. “An electric stove’s lowest setting is around 200. We’d have to keep the pot on your range, and take shifts checking the thermometer, turning the heat on and off every few minutes. Unless you’ve got any other suggestions.”
</p>
<p>
Danny shrugged and groaned uncertainly. “Put it in a nest and sit on it?”
</p>
<p>
Tina giggled. “That would get the job done.”
</p>
<p>
“I’ll bring you worms, and distract predators with my colorful feathers. You’ll be safe and comfy.”
</p>
<p>
“Any better ideas?” Tina said with a chuckle.
</p>
<p>
Danny yawned hard. After a moment of thought, he reached out toward her and made grabby motions with his bandaged hand. “Here, let me see that thermometer…”
</p>
<p>
He carefully examined the small device. Through its translucent white plastic shell, he could see a narrow green circuitboard behind the temperature readout screen. Wordlessly, Danny hopped down from his stool and staggered toward his foyer.
</p>
<p>
“Ooh! You have a plan, don’t you?” Tina asked eagerly. Behind her, the lid on the pan inside the oven clattered loudly. She hopped over to the stove to reduce it to a simmer.
</p>
<p>
Danny walked mechanically to the door leading out to his garage. Circuit schematics materialized in his head. In his mind’s eye appeared fine gray rectilinear diagrams of transistors, power supplies, crossovers… It was child’s play.
</p>
<p>
By the time Tina followed him to the garage, he was already seated at his workbench. The thermometer was clamped into a vise beneath a large table-mounted magnifying glass with a bright built-in lamp. He was slicing its translucent plastic shell with a scalpel-like X-ACTO knife.
</p>
<p>
“Can I watch?” she asked, and leaned closely over his shoulder.
</p>
<p>
He gently tapped the metal bulb at the tip of the thermometer with his blade. “See that?” he said. “That’s the casing for a little thing called a ‘thermistor…’”
</p>
<p>
With a few more strokes of the knife, the thermometer’s shell split in half. While the wide end with the digital display stayed clamped in the vise, the narrow end fell away. It dangled by two thin orange wires, barely as thick as a hair. Working carefully under the magnifying glass, he severed the two wires and brought the newly freed tip down to the surface of the table.
</p>
<p>
“Is that the temperature sensor?” asked Tina.
</p>
<p>
“Basically, yeah,” said Danny. “It’s made of a special temperature-sensitive ceramic material. The warmer it gets, the more it impedes the flow of electricity. Thermal resistor, see?” He reached beside his workbench toward his own large collection of wires, spun onto plastic spools and carefully arranged by thickness and color. He cut away several lengths and stripped their ends. He then set down his knife, drew a hot soldering iron out of its holster in the corner of his table, and delicately applied tiny drops of solder to their tips. 
</p>
<p>
“I thought thermometers use mercury,” she said. “And that you’re not supposed to open them like that.”
</p>
<p>
Danny shook his head. “Mercury thermometers have been getting phased out for years. These digital ones are better anyway. They’re all solid-state. Here, hold this, okay?” 
</p>
<p>
He passed her the severed bottom of the thermometer. Thanks to his soldering work, the two wires that dangled from it were now several feet long.
</p>
<p>
When she took it delicately in her fingers, he pressed it into her palm. “No, like this…” He put his hands around hers and folded it around the sensor. “Warm it up…” 
</p>
<p>
He noticed himself lingering on her touch. Their eyes met. There was a long pause.
</p>
<p>
Tina said softly with a hint of a smile, “You know, it won’t reach body temperature in my hand.”
</p>
<p>
“It won’t?” Danny asked quietly.
</p>
<p>
“No chance,” she said. “It’s an oral thermometer.”
</p>
<p>
“Oh…” he murmured.
</p>
<p>
Their eyes still locked, she drew her hand away from his and turned the thermometer around in her fingers. Her lips parted gently. She slid it into her mouth, nestling the tip in the space beneath her tongue.
</p>
<p>
Danny found himself forgetting to breathe.
</p>
<p>
He abruptly stood up from the workbench and turned away. He stepped briskly to a case of narrow shelves, each bearing translucent plastic bins filled with assorted electronic components. “So anyway… It won’t need much…” he mumbled. “One transistor… A switching power supply… Power MOSFET… Relay… A rheostat for calibration…”
</p>
<p>
He returned to the workbench with a handful of black and silver objects, which he spilled onto the table like jacks as he sat back down. He selected a breadboard, an index-card-sized rectangle of white plastic dotted with a grid of hundreds of tiny holes. Into two of the countless sockets, he inserted the loose ends of the long wires soldered to the thermistor, still hanging from Tina’s mouth as she stood there blinking. Into two others, he slid wires from a regulated variable power supply at the back of the table. He then began drawing pieces from his pile of components and adding them to the breadboard. After barely a few minutes of silent labor, he announced, “There!”
</p>
<p>
Tina looked on. “Sho, umm… What’sh shish shing shupposhed to do?”
</p>
<p>
“It’s a thermostat,” Danny answered. “Watch. See this LED?” He pointed to a small glass gumdrop-like object on the breadboard, about the size and shape of a pencil eraser. 
</p>
<p>
“Mm-hmm,” Tina replied.
</p>
<p>
“Pretend that’s a burner on my stove,” Danny continued. “Now, I’ve tuned the thermostat to your body heat. When the thermometer is at your body temperature or higher, it’s turned off. But if it cools down…”
</p>
<p>
He reached up toward her face. She puckered her lips. He pulled the dismantled thermometer from her mouth, possibly more slowly than necessary. He shook the warm, moist tip of the thermometer through the air. After a few seconds, the small glass bubble on the breadboard popped aglow with a bright green light.
</p>
<p>
Tina understood and grinned. “So if you put the thermometer tip inside the pot, then it can turn the burner on and off automatically, which will keep the broth at a nice, steady, warm temperature without us having to keep a vigil on it.”
</p>
<p>
“Bingo,” said Danny. “Of course, I’ll seal the whole thing in epoxy resin to make it watertight, so the electronics won’t short out.”
</p>
<p>
Tina raised an eyebrow. “How’ll you connect this to your stove?”
</p>
<p>
 “With this…!” Danny replied excitedly. He held up a translucent blue plastic cube the size of his palm. It looked similar to the ones on the back of the HERF gun that sat sipping power in the corner. Complex mechanical components wound and bent under its skin. Thick, stubby metal prongs projected from its underside. “This is a power relay,” he explained as he attached wires between the breadboard and the cube. “It can switch ten amps of 220VAC on a two-amp 12VDC control current.”
</p>
<p>
Tina shrugged uncomprehendingly.
</p>
<p>
Danny couldn’t help shooting her a slightly devious smile. “You’ll see.” He proceeded to attach two thick red wires to the underside of the cube. The wires were capped with yellow cone-shaped connectors the size of a pinkie knuckle.
</p>
<p>
Tina stared at the jerry-rigged contraption, her eyes gleaming. “I have to go check on the broth. Meet you in the kitchen?” He nodded, and she skipped away out of the garage.
</p>
<p>
By the time Danny finished his makeshift thermostat, Tina had already taken the pot out of the oven. The kitchen sink was plugged and filled with a watery slurry of ice from his freezer. Tina held the hot vessel with oven mitts and gently rocked and rotated it in the ice bath. She mindfully held the lid down, careful to prevent it from sliding off and exposing the broth to the open air.
</p>
<p>
Danny entered the kitchen wearing thick gray electrical gloves, carrying his medley of connected electronic components. He laid his thermostat down on the counter &mdash; the breadboard sprouting silver and black growths, the severed thermometer tip on the end of two long lines, the translucent blue power relay with protruding red wires with yellow-capped tips. “Are you done with the stove?” he asked.
</p>
<p>
“All yours,” said Tina.
</p>
<p>
He walked up to the stove, grabbed it with both hands, and pulled. The stove slid hesitantly from its space along the wall, scraping against the floor tiles. The lanky engineer was able to shimmy it out of its home, just far enough to expose the black cord that plugged the stove into the house’s 220VAC circuit. He pulled the large round plug out of the wall, causing the stove’s clock to go dead.
</p>
<p>
He then produced his X-ACTO knife and slashed open the stove’s power cable. He slid the blade slowly down the rubber insulation until he had formed a slit almost a foot long. Multicolored wires and metallic coating protruded from the gash.
</p>
<p>
“Is that safe?” Tina asked.
</p>
<p>
“Not in the slightest,” said Danny. He severed and stripped one of the multicolored wires, and spliced its ends with the power relay. He sealed his work with generous helpings of duct tape, the sticky gray ribbon making stretchy noises as it came off the roll. When he was finished, the breadboard and power supply lay on the floor beside the displaced stove, electrically implanted into its power cord. Gingerly, he plugged the appliance back into the wall. Much to his relief, nothing caught fire. The stove came back to life, its clock blinking 00:00.
</p>
<p>
“Not bad,” Tina said with a smirk. She lifted the two-gallon pot, carried it to the stove, and set it on the largest burner.
</p>
<p>
Danny took off his electrical gloves and offered her the thermometer. “Shall we?”
</p>
<p>
Tina looked at the transparent bag in his hand with utter disgust on her lips and a glint of humor in her eye. “Ugh! I think not! That thing hasn’t been cleaned! You want to stick that bacteria-covered monstrosity of yours into my nice, warm, nutritious broth? I’ll have you know that I am a <em>lady</em>, good sir…!”
</p>
<p>
She strutted past him in a mock huff toward the row of Rite Aid supplies on the counter. She grabbed the bottle of rubbing alcohol and found a large bowl to pour it into. The liquid’s sharp scent stung their noses. She took the thermometer from him and immersed it in the rubbing alcohol, sloshing it around and making sure that every last bit of its exterior received a thorough soaking.
</p>
<p>
“There!” she said. “<em>Now</em> you may plunge your thermostat into my pot.” 
</p>
<p>
With a deft, quick motion, she slid the lid aside just barely widely enough to accommodate Danny’s device. A warm, salty, sweet scent rose from the pot, organic yet pure. The thermometer made a soft plop as it entered the broth. With a metallic scraping sound, Tina quickly replaced the cover. The wires from the thermostat protruded from the rim, preventing the lid from closing completely. Tina applied a generous coat of Saran Wrap to form an approximately airtight seal, and the pot was safe from airborne bacteria.
</p>
<p>
The two of them watched it for a few moments. 
</p>
<p>
From beside the stove, the power relay emitted a loud “<em>Click!</em>”, and the stove’s power died. Its clock showed a dead black face.
</p>
<p>
“Is it supposed to do that?” asked Tina.
</p>
<p>
“I think so,” said Danny. “The burner was on, right? So it was heating this whole time. Which means it’s supposed to turn off now to cool down a little. And then when it’s cool enough it’ll turn back on again.”
</p>
<p>
“So it’s working?” she asked.
</p>
<p>
Danny nodded.
</p>
<p>
 “So all that’s left,” said Tina, “is the…” 
</p>
<p>
“Yeah, the…,” Danny repeated.  
</p>
<p>
They both turned their heads and stared at the white latex glove on the granite counter, inside-out, twisted and tied off near the base of the digits.
</p>
<p>
Tina approached the counter and picked up the glove. She held one of the fingers pinched shut, and with a pair of scissors she cut the finger away from the rest of the glove. She held it up before her eyes and examined it carefully.
</p>
<p>
“Is the crusty stuff in there?” Danny asked.
</p>
<p>
“Yeah,” Tina said, and slowly walked back to the stove. The footsteps of her black shoes on his white kitchen tile punctuated the tense stillness of the air. Keeping a pinch on the open top of the severed latex finger, she held it near the pot. “You ready?”
</p>
<p>
Danny whispered thickly, “Let’s do it.”
</p>
<p>
Tina inhaled sharply and held her breath, her rib cage expanding, her breasts stretching her white button-down shirt. 
</p>
<p>
She quickly peeled back the plastic wrap and pushed the lid aside barely an inch, leaving a narrow crescent of broth momentarily exposed. With both gloved hands, she gently tapped the latex finger. The lone yellowish-white grain tumbled out. It alighted on the water’s surface like a flake of fish food, buoyant in the salty broth.
</p>
<p>
Tina rapidly closed the cover and re-wrapped the plastic. She peeled off her gloves, and finally let herself exhale.
</p>
<p>
Danny stood beside her, both of them looking down at the two-gallon stainless steel pot. “What happens now?”
</p>
<p>
“Nothing,” Tina answered. 
</p>
<p>
“Nothing?”
</p>
<p>
“Now we just wait for them to multiply,” Tina replied. She flexed her fingers, her black nail polish giving off a hint of iridescence as it caught the light. “They’ll fill the whole pot eventually.”
</p>
<p>
“How long will that take?” asked Danny.
</p>
<p>
Tina shrugged. “Depends on how well I prepped that broth. Maybe hours. Maybe a couple of days. Maybe weeks. It’s a big pot.” She swept a lock of her hair over her ear.
</p>
<p>
“Hrmm. This thing could be on my stove for a couple of weeks?” said Danny.
</p>
<p>
“Yep,” she said, turning to face him with mischievous eyes. Her full, pink lips were stretched in an elfish smile. “Sucks to be you, doesn’t it?”
</p>
<p>
“Oh, in so many ways,” Danny said with a chuckle. If he wasn’t ready to pass out from exhaustion, it wouldn’t have been funny; he’d have begun mentally enumerating them all. He found, however, that being nervous or anxious required effort &mdash; the effort of visualizing failure. As the two of them stood beside the pot, Tina’s face inches from his own, he found that he could no longer expend the time and energy required to sabotage himself. Not at 00:00 in the morning.
</p>
<p>
“So…” said Tina.
</p>
<p>
“So,” said Danny, his eyes fixed on hers. “What’s left for us to do here?”
</p>
<p>
“I don’t know,” Tina said. “You tell me.”
</p>
<p>
Beside the stove, the power relay brought the burner back to life with a loud, “<em>Click!</em>”
</p>
<p>
His hand shot toward her waist. He pulled her toward him and slid his other hand under her ear around the back of her neck, his fingers running through that dark unkempt hair that he had wanted to touch since first seeing her on that hacked video feed earlier that night. His lips crashed upon hers like waves against a primordial shore.
</p>
<p>
He didn’t think about brushing his tongue lightly against hers. He didn’t think about leading into a nibble of the lower lip. He didn’t think; he didn’t calculate or analyze or hypothesize. He simply did.
</p>
<p>
She squeezed her body against his, her breasts pressing against his ribs and her hips pushing against his pelvis. She could undoubtedly feel his desire for her. Her arms reached around him and her fingers splayed against his back, drawing him tightly to her.
</p>
<p>
The pressure of her hand hit his injured shoulder. A flash of searing pain jolted him out of the kiss. He pulled back and hissed harshly, his eyes wide and his senses suddenly heightened. The wound throbbed with his quickening pulse.
</p>
<p>
She drew her hands away and looked up at him with an apologetic expression.
</p>
<p>
His eyes gazed into hers with raw animal hunger. He grinned.
</p>
<p>
With a shove, he thrust her away from the stove with carefully guided force. Her back hit the refrigerator. 
</p>
<p>
He grabbed her dark hair and pulled her head to one side, exposing her neckline, and pressed his mouth vigorously against the side of her neck. His other hand cupped over her shirt and bra and massaged her breast.
</p>
<p>
She moaned deliciously into his ear. Her hand was in his hair, pulling his head down to increase the pressure on her neck, craving more. She raised one knee, her shoe against the refrigerator door, her thigh rubbing against his waist. Her hips ground against his.
</p>
<p>
As his mouth worked its way down from her ear to her collar, his hand began unbuttoning her white shirt. 
</p>
<p>
She ran her hand under his pajama shirt, her fingers tracing the contours of the muscles of his torso.
</p>
<p>
Her last button undone, Danny stepped back to admire the sight of this lithe young lady against his fridge, her white shirt hanging open and exposing her tan bra and toned midsection. He took a moment to consume her curving feminine form with his eyes as she remained pressed with her back against the fridge. Tina smirked libidinously for a moment, wiggling teasingly against the fridge, happy to let him enjoy the view.
</p>
<p>
She then kicked herself away from the fridge and reached out to grab him and yank him back to her by his blue linen pajama shirt, which she promptly pulled off of him. She flung it to the kitchen floor.
</p>
<p>
With both hands, he pulled her shirt down and off behind her, leaving the sleeves bunched at her wrists. She began to wriggle her hands to slide entirely free… but he didn’t want her to. Instead, he twisted the shirt tightly, trapping her hands behind her in its white fabric. Putting his other hand on her shoulder, he spun her around and pushed her against the fridge once more, pinning her face and chest against its door. While his one hand maintained the squeeze on the shirt bunched around her wrists to keep her hands immobile, his other deftly unhooked her bra, his agile fingers making quick work of the clasps. 
</p>
<p>
At last he released her wrists, tossing her white shirt mindlessly aside and dropping her tan bra to the floor. With his body he kept her pinned against the refrigerator door, his naked torso pressing hungrily against the warm, supple skin of her back. She pressed one of her newly freed arms against the refrigerator, the palm flat against the door. The other reached up and back, her black-painted fingers clutching his head.  
</p>
<p>
His arms wrapped around to her front. One hand climbed upward to massage and caress her naked breast, molding around its soft round form. He gently pinched her nipple between two fingers, eliciting moans of delight from her parted lips.
</p>
<p>
His other hand reached around the curve of her hip and climbed downward, past her abdomen, past her navel. He unthreaded her belt from its loops. Pulled it away from the buckle. Slid it open, letting its leather ends dangle aside. Nimbly unbuttoned her black slacks. Drew down the zipper.
</p>
<p>
He took his time, savoring every moment, enjoying hearing her gasp. 
</p>
<p>
His fingers first stroked teasingly outside her panties, indulging in the slickness of her hot, moist passion. He kept his ministrations on the outside of the thin fabric until her face contorted in agony; then he finally granted her the relief of feeling him touch her with his bare fingers. He rubbed and stroked with a steady, pulse-like rhythm, matching his motions to the pace of her breathing. He keenly watched her face, relishing her pleasure.
</p>
<p>
The subtle rocking of her hips progressively accelerated. Her panting breaths rose to gasps. Her moans began to crescendo into cries.
</p>
<p>
Finally, when she seemed to approach the threshold of exploding, she suddenly pushed him violently away with both hands. She turned to face him, topless in her black slacks and low-heel pumps, and tilted her head slightly downward to look up at him with voracious eyes. Her face was flush, glowing with carnal cravings. She leaped to him like an untamed beast, a wildcat ready to devour a helpless prey. 
</p>
<p>
Her hand, capped with nails like black talons, ran claw-like down his front, leaving a long trail in his skin from his chest down past his abdomen. 
</p>
<p>
She then dropped to her knees before him, yanking down his pajama pants in a single stroke.
</p>
<p>
She pleasured him with her mouth deftly and skillfully. She looked up at him frequently with big, bright, naughty eyes. Her face, framed by her dark hair, radiated mischievous enjoyment. He caught his own hips gently thrusting to match the rhythm of her efforts, and his fingers ran through her hair as he groaned ecstatically.
</p>
<p>
He pulled away long before his excitement could go supercritical. While she took her shoes and socks off, he gave the kitchen a quick, determined scan. The counter looked like it was about the right height…
</p>
<p>
With a sweep of his arm, groceries tumbled from the granite countertop and crashed onto the floor. Amino acid powder spilled across Danny’s kitchen tile. He could hardly give less of a damn.
</p>
<p>
Tina ran over to him on bare feet. She gave him an eager kiss, then excitedly hopped up onto the counter. 
</p>
<p>
Danny pulled her slacks and panties down to her ankles, relishing the sight and sensation of her long, smooth thighs, and the wet womanhood between them. 
</p>
<p>
With her butt on the granite countertop, in a flurry of leggy motion, she kicked the black slacks and panties away.
</p>
<p>
They landed on the kitchen floor, beside the bunched-up button-down white shirt, beside the bra, beside the blue pajamas and the slippers and the shoes and socks that lay strewn across the tile. Beside the pile of Rite Aid groceries and improvised biotechnology equipment that now littered the floor. Beside the breadboard and the power relay and the multicolored wires that ran behind the stove and up to the stainless steel pot.
</p>
<p>
Within the broth, the microscopic <em>E. coli</em> felt the warmth and moisture around them, and slowly awoke from their slumber. Mindless and hungry, they eagerly began partaking of the bountiful feast, ready to explore the vast new frontiers of this nutrient-filled vessel. 
</p>
<p>
And on the granite countertop, the two lovers partook just as eagerly of one another. There was no boundary between the joys of their mutual intellectual achievement and their mutual physical pleasure. There was no separation between ecstasy of the mind, ecstasy of the body, and ecstasy of the soul. Their worlds &mdash; his of electronics and hers of biology, his of the mechanical and hers of the organic, his of the wizardly material and hers of the mystic divine &mdash; their passions, like their bodies, were made to be united. 
</p>
</div>