<div class="chapsection">
<p>
<span class="caplead">Pike Place Market on a sunny afternoon</span> bustled with the cacophonous crowd. Tourists, locals, and seagulls alike swarmed the multi-level pavilion, where the smell of fish and the music of street performers filled the air. Built on a steep slope overlooking Elliott Bay, the countless shops and cafés were constructed atop one another, connected by chaotic networks of stairs and ramps. Farmers set up carts filled with fruits and honey on the comb. Artists hocked watercolor paintings. Fishmongers threw salmon over the heads of cheering customers. 
</p>
<p>
Sergey Mukhayev sat in a wicker patio chair at a small round table at an outdoor café, sipping tea and waiting. 
</p>
<p>
The tea was hot, black, and strong. He wasn’t supposed to indulge, but this one cup of tea wouldn’t kill him. It was simply a nod to the truth &mdash; and the truth, like the tea, was bitter. It would be ten years before Rosie would graduate college. His chances of seeing that happen were fifty-fifty at best. In however many years remained for him, his sole purpose was to secure her future, to at least partially rectify the tragedy he had made of her innocent young life. His business, with its secrecy and violence, unfortunately happened to be incredibly lucrative. Through it he had caused his own damnation. And through it, he sought to earn some small glimmer of redemption.
</p>
<p>
He felt the caffeinated drink begin to take its effect. His heart quickened. Ironic stuff, tea was &mdash; so soothing to the mind, yet so stressing to the body.
</p>
<p>
And with the quickening came the pain. A sharp pinch stabbed his chest, like heartburn after a meal of needles. He pressed his hand to his sternum and winced. His head felt as though he had stood up too quickly. He made himself cough several times; the dry hacking motion helped get the blood flowing back to his head.
</p>
<p>
His fingers felt around in his pocket for his pills, searching for the small smooth beads of chewable aspirin mixed in among the hard round beta-blockers and the long oval statin tablets. He preferred to keep them jumbled in his pocket, outside their bottles. Bottles of pills made distinct rattling noises, and he’d be damned if he was going to walk around the city jingling with medication like a goddamned geriatric. He was only forty-seven years old and still strong as an ox &mdash; his muscles lacked the definition they’d once had in his youth, but he was still as mighty and powerful as ever. And if any lousy cretin dared to look at him like some kind of poor frail invalid, he’d sooner stab the son of a bitch’s eyes out than suffer a moment of his pity. 
</p>
<p>
The aspirin worked quickly. The pain subsided, and Sergey resumed sipping his tea.
</p>
<p>
From behind him came a man’s voice. It was dry and aged. “Sergey Mukhayev,” it said flatly. Its pronunciation of his name was clear and crisp. Rather than the lisping Anglicized bastardization to which he had grown accustomed over the last decade, the voice intoned his name with the true, rich, heavy consonants of a native Russian speaker. He turned and looked up. A gaunt, elderly face looked back at him through inscrutable blue eyes. 
</p>
<p>
The old man carried a manila envelope. He sat down across the table. “You’re a difficult man to contact, Sergey,” he said in Russian. “Are you hiding, or just taking a little break?”
</p>
<p>
Sergey stared at him suspiciously. “I’ve had a few issues with my communication channels lately.”
</p>
<p>
“Indeed,” said the man. “You know, you certainly don’t make my life easy. You don’t reply to email, your telephone goes straight to voicemail… Why, if that Leo boy hadn’t answered for you, I was about ready to send a courier over to your house.”
</p>
<p>
“Am I supposed to know you?” Sergey replied.
</p>
<p>
“No,” said the old man. “But it’s part of my job to know you.”
</p>
<p>
“The pleasure’s all yours, then,” said Sergey.
</p>
<p>
“I am called Pyotr Passinsky. <em>Doctor</em> Pyotr Passinsky.” He spoke impeccable Russian with a highbrow Muscovite dialect. The accent fell upon the Russian ear similarly to the sound of High British to a native English speaker. The affectation connoted either great intelligence and fine breeding, or extreme arrogance and unadulterated pomposity.
</p>
<p>
The old man extended a handshake. Sergey did not accept. “Am I supposed to be impressed?”
</p>
<p>
“You should respect your elders.”
</p>
<p>
“Maybe I’d respect you,” said Sergey, “if I knew who the hell you are and what you want with me.”
</p>
<p>
“Who I am is a victim of your aggression, and what I want is restitution,” Passinsky said. “Your men broke into my company last night, Sergey. Tungsten Medical Technologies. Well, it’s not <em>my</em> company, of course, but I’m responsible for it. Your barbaric little adventure makes me look very bad, especially considering that part of my duties is to make sure you aren’t misbehaving. And your timing could not be worse. My boss, as it so happens, is flying into town as we speak, to discuss corporate financial matters. I’m now, in addition to our scheduled affairs, forced to explain your uncouth actions.”
</p>
<p>
“<em>My</em> men? <em>My</em> actions? That’s quite some accusations you’re leveling there, <em>Doctor</em>. I have no idea what you’re talking about.” Sergey’s voice was slow, shrewd, and somewhat snide. He had spent his youth in Saint Petersburg, on the humid shores of the Baltic Sea. It was a city of art and theatre, of literature and music, and of crime and corruption so brazen that it would have made Prohibition-era Chicago look like the Smurfs’ Village. Sergey’s subtle accent conveyed cleverness, ruggedness, and an attitude toward authority that could not be properly described in polite company.
</p>
<p>
The old man’s face showed profound irritation. He reached into the manila envelope and withdrew a sheet of paper to lay on the table. Upon the paper was a screenshot of a security camera recording. It showed Eugene, clad in his now-destroyed Italian leather jacket, standing in a brightly lit room filled with glassware and scientific equipment. He was holding a young woman at gunpoint with one of those tiny snubnose .44 Magnum hand-cannons of which he was so fond.
</p>
<p>
“Are you going to deny that this is your nephew Eugene?” asked Passinsky.
</p>
<p>
“What if I do?” Sergey shot back.
</p>
<p>
Passinsky’s cold eyes narrowed. “Kindly spare me the trouble of proving what we both already know. I’m a scientist, not a judicial magistrate. I refuse to waste my time playing pointless mind-games with you.”
</p>
<p>
Sergey smirked. “Then you shouldn’t have sat down here.”
</p>
<p>
Passinsky exhaled sharply through his nose. “Fine. In that case, let’s see if <em>this</em> one rings a bell…”
</p>
<p>
He produced another paper, bearing an image of a man in his late thirties, wearing a lab coat and holding an odd contraption. Sergey recognized him from the factory: it was the technical savant who seemed to be plaguing Sergey at every turn. Sergey’s fists clenched at the sight of him.
</p>
<p>
Passinsky gave a nod. “So, I take it he is familiar?”
</p>
<p>
Sergey growled, “I have… encountered him.”
</p>
<p>
“Just as I thought, then,” said Passinsky. “It appears this fellow has been a thorn in both our sides. It may interest you to know that, from what I can tell, this is not his usual line of work. He’s a computer engineer. Highly skilled, but otherwise rather unremarkable. Aside from having worked on a few civilian contracts for the United States Navy, he doesn’t even appear to have any military affiliation.”
</p>
<p>
“How is he called?” Sergey hissed.
</p>
<p>
Passinsky held up his manila envelope. “It is all here. His name, his address, his social groups, and so on.” He waved the envelope, but made no move to pass it across the table.
</p>
<p>
Sergey kept a poker face. “Supposing I was interested…”
</p>
<p>
Passinsky rolled his eyes. “Sergey, you <em>are</em> interested. I will not play silly games with you, you punk! Do you understand?”
</p>
<p>
“What do you want for it?”
</p>
<p>
“You know perfectly well what I want, Sergey,” said the old man.
</p>
<p>
“Suppose I didn’t bring it,” Sergey said standoffishly. “Suppose I came here only to find out who you are and what you have to offer. And now that I know, suppose I simply reach over this table, grab that envelope from your weak old hands, and walk away?” 
</p>
<p>
Passinsky grimaced. “Even an overgrown Leningrad street urchin should at least feel some shame&mdash;”
</p>
<p>
“It’s called Saint Petersburg, you vegetable-brained geriatric,” Sergey interrupted. “It hasn’t been called Leningrad in over twenty years.”
</p>
<p>
“Consider it in practical terms,” Passinsky chided. “Why do you think I agreed to meet you here, in this venue?” He leaned back and gestured to the throngs of people milling about the shops and stands of Pike Place Market. “Do you really think you’d be able to get away with attacking an old man in public?”
</p>
<p>
“Fine. But then, even someone as obviously senile as you should at least feel some shame in making me such a pathetic offer. A tube filled with priceless microbes, in exchange for some papers about some random man whom I only care about as an afterthought?”
</p>
<p>
“The vial is worthless to you,” Passinsky pressed. “You do not know how to use its contents.” 
</p>
<p>
“Ah, but I know <em>you</em> want it very badly, and I’m quite certain you’d be willing to give me much more for it than…” Sergey waved at the envelope. “…<em>that</em>. No, good Doctor. I think I’ll keep what’s mine.”
</p>
<p>
“It’s <em>not</em> yours,” said Passinsky.
</p>
<p>
“It is now,” Sergey smirked. 
</p>
<p>
The elderly man sighed and leaned forward, clasping his hands. “Sergey, let me make something perfectly clear. This exchange that I propose is strictly a professional courtesy. I sincerely hope that you brought the vial here, and that you are willing to hand it over amicably. Because if you do not, then I’ll have to have my boss’s men extract it from you by force &mdash; and if you are indeed having ‘communication problems’, then you are hardly in a position to put up much of a fight. I would really prefer that the matter does not escalate to such a level &mdash; not because I give a damn about you, but because it would greatly displease my boss. And my boss is not a man I wish to displease further. So that is why I extend to you the invitation of handling this matter by way of exchange &mdash; it is the closest I can come to a win-win solution. Do you understand?” 
</p>
<p>
Sergey stared at the old scientist contemptuously.
</p>
<p>
Passinsky stared back. “Need I remind you, I’ve already demonstrated that I know how to reach you, where you live, and who your family is.”
</p>
<p>
Sergey looked away with a snarl. Bitterly, he reached into his pocket, withdrew the small smiley-faced vial, and laid it on the table. 
</p>
<p>
Passinsky gave him the envelope, and took the vial in his liver-spotted fingers. “I’m glad we could come to an agreement.”
</p>
<p>
Sergey opened the envelope and examined the papers inside. “So… Are we done here?”
</p>
<p>
“Well,” said the old scientist, “there is perhaps another matter, more personal in nature.”
</p>
<p>
Sergey folded the papers and put them in his pocket. “What is it now?”
</p>
<p>
“This ‘Daniel’ fellow… He’s built a most remarkable machine. A rifle that shoots a pulse of electromagnetic energy…”
</p>
<p>
“Yes, yes.” Sergey groaned. “It kills electronics, I know.”
</p>
<p>
“From a technical perspective, I’m quite curious about this invention. If there’s any chance you could procure it for me, I could reward you.”
</p>
<p>
Sergey snorted. “That accursed piece of garbage? I’d sooner shove it into a trash compactor.”
</p>
<p>
“You know, a young man at my office helped me identify it. You’ll never believe where he recognized the device from. An old computer game! Delightful, isn’t it? And do you know what its function was in this computer game? Deactivating robots and… Another kind of monster… My young colleague used an amusing word for it: ‘cyborg’. Do you know what a cyborg is, Sergey?”
</p>
<p>
Sergey stared at the old scientist with a bored expression.
</p>
<p>
“Oh Sergey, you of all people really should learn this word. A ‘cyborg’, you see, is a creature that is part man, part machine. A man who’s had parts of his body replaced with electronic components. Parts of his body that no longer function properly because of injury or illness. Do you understand my meaning, my friend?”
</p>
<p>
Slowly, Sergey’s bored demeanor faded to a combination of humiliation and indignant rage. He folded one arm across his chest, and leaned menacingly toward the old man. “The state of my body is absolutely none of your concern, you parasite-infested swine!”
</p>
<p>
“It is nothing to be ashamed about,” Passinsky said. “In fact, I would consider it a source of pride! A testimony to the fact that we truly do live in future times. A living embodiment of the power of technology over the weaknesses of the flesh.”
</p>
<p>
“How dare you!” Sergey spat. “Whose flesh are you calling ‘weak’, you decrepit cur? I could break you in half with a flick of my wrist!”
</p>
<p>
Passinsky shook his bald head. “Such hostility, over something so inspirational.”
</p>
<p>
“How the hell do you know these things about me?” he snarled at the old man. “Why have you been watching me!? Who the hell do you think you are?”
</p>
<p>
Passinsky shrugged innocently. “You were simply a part of my assignment, Sergey. It’s nothing personal. My boss knew you’d moved your operation to Seattle after your little falling-out in Leningrad&mdash; sorry, Saint Petersburg. And, because of both the location of Tungsten’s offices and the nature of our research objectives, he thought it would make sense to keep track of you. Maybe even hire you for some distribution work later. Which, of course, is no longer a possibility…”
</p>
<p>
Sergey’s fists clutched the sides of the table. “Why me? Why does your boss give a damn about me? How does he even know who I am?”
</p>
<p>
“Well, I don’t know the details,” Passinsky said nonchalantly. “but from what I understand, you two have a history. I hear you worked for him back in Saint Petersburg? Arranged some sales, apparently…”
</p>
<p>
Sergey’s throat seized. His pulse throbbed on the sides of his neck. “No…”
</p>
<p>
“I got the impression that something went sour between the two of you back then,” Passinsky continued. “He seemed extremely unhappy about something you’d done about ten years ago…”
</p>
<p>
The crowded pavilion spun around Sergey’s head, the shifting forms of shoppers and tourists suddenly making him feel nauseous. His breathing grew shaky.
</p>
<p>
“Something about… What was it?” Passinsky went on. “You kept too large a commission for yourself? Something along those lines? You lied about the size of a sale so you could keep the difference? He never really told me exactly what it was, and I never bothered to ask…”
</p>
<p>
His hearing began to fade. In the periphery of his vision, Sergey could see intricate patterns of capillaries, surging with blood.
</p>
<p>
Passinsky added, “He’s called Ivan…”
</p>
<p>
Sergey shot up from his chair. Standing, he lifted the metal patio table a few inches and slammed it back down. The delicate cup of tea, along with its saucer, tumbled and shattered against the patio deck. 
</p>
<p>
“He murdered my family!” Sergey screamed. 
</p>
<p>
Passersby gasped at the outburst and stared in shock. Patrons seated nearby backed away. Café staff turned their heads and watched nervously, glancing back and forth to decide who, if anyone, should say something.
</p>
<p>
Passinsky flinched but remained seated. His face displayed nothing more than simple annoyance.
</p>
<p>
“He killed Sveta! And Vadik!” Sergey leaned on the table, his hands still curled around its edges, his knuckles turning white. “His men broke into my home! They gassed me and electrocuted me with cattle prods! They tied me down and forced me to watch! Do you know what he did to them? Do you know!?”
</p>
<p>
Passinsky avoided eye contact. “I know what kind of man my boss is.”
</p>
<p>
Sergey suddenly looked away and gasped, “Your boss…! Ivan is your boss…!”
</p>
<p>
Passinsky nodded affirmatively. “He’s the man that wires my paychecks. He created a fictitious investment consortium to move funds into the United States, but he’s the consortium’s sole member. Tungsten is his company.”
</p>
<p>
“Tungsten is his company…” Sergey repeated, his eyes wide with panic. 
</p>
<p>
Passinsky shrugged. “Of course. Surely you didn’t think that a company whose sole project is a new source of cocaine would have an entirely scrupulous investment provider.”
</p>
<p>
“Tungsten is Ivan’s company…,” Sergey stuttered. “It’s Ivan’s company… And I… Last night, I… Oh dear God…! And he’s coming? Ivan’s coming? Here? Today?”
</p>
<p>
“He was already on his jet when I talked to him earlier this morning,” said Passinsky. “He’s landed by now.”
</p>
<p>
“But he doesn’t know, right?” Sergey said, his voice a combination of fury and pleading. “He doesn’t know that I… That my men… That we…”
</p>
<p>
Passinsky grunted. “Don’t be silly, Sergey. Of course he knows. I told him. And let me tell you, that was not a phone call that I enjoyed having to&mdash;”
</p>
<p>
The small table flew aside with a single swipe of Sergey’s hand. 
</p>
<p>
He grabbed the scientist by the collar, and hoisted him to his face. “You son of a bitch!” Sergey screamed, along with a litany of colorful invectives whose rich meanings would be lost in translation. He shook the frail gray form while the old man stammered and demanded that the brute unhand him.
</p>
<p>
The crowd erupted in protest. The commotion had put bystanders at alert, and many had already been preparing to intervene. Men rushed in &mdash; café staff, passersby, fellow patrons &mdash; to pull the large man off of the thin elderly scientist. Women shielded the aged victim, shouted for help, called out for anyone who might speak Russian to come and translate. 
</p>
<p>
Sergey fought back against the pull of many arms around him, grabbing at him, restraining him, forcing him down…
</p>
<p>
Just like he’d done so many years ago… When the men broke into his house on a frigid Saint Petersburg morning… When they’d knocked the gun from his hand, he grabbed a lamp, and bashed it against their skulls… And when the lamp broke, he continued with his fists… His large, powerful muscles burning with adrenaline… His wife, Sveta, running to the nursery… Rosie in her crib, crying, screaming… Vadik, his son, six years old, biting, kicking, trying to fend them off with a plastic toy sword… His head reeled from the ether they’d tried to knock him out with… But he would not be subdued, not by these men, not when his family was at stake… And suddenly his entire skeleton rattled within his flesh as cattle prods stabbed his ribs… And his chest felt like it was being crushed in a vise, and there was an arrhythmic fluttering from behind his sternum, and everything tilted and went black…
</p>
<p>
He picked one hand at random from the many that held him. He grabbed its wrist and gave a twisting yank. There was a crunching noise, and a man shrieked. The injured foe retreated, several people coming to his aid.
</p>
<p>
The sea of hands released him, and the crowd of vigilant citizens backed away in terror. A vacant ring surrounded him, none daring to come within his reach.
</p>
<p>
His eyes darted around the outdoor pavilion, looking for an escape. The narrow crisscrossing walkways, the rolling street carts, the convoluted networks of stairs and ramps throughout Pike Place Market would serve him well. But he had to move fast. Not only because the police were surely on their way, but because…
</p>
<p>
“Rosie,” he gasped. “My Rosie…!” He reached for the pocket where he typically kept his cellphone. It wasn’t there. He had destroyed it the previous night. “They’ll… Oh God…!”
</p>
<p>
He bolted from the pavilion. A few brave people tried to stop him. He swept them aside like curtains.
</p>
<p>
Passinsky, straightening his shirt and gesturing graciously to the intervening bystanders to let them know he was alright, called out to him, “Sergey, don’t bother! I’m sure that he already has her.”
</p>
<p>
The old scientist’s choice of words was deliberate. In Russian, the verb “to have” is never used in reference to a woman or girl unless it is intended to convey a very specific implication.
</p>
</div>
