<div class="chapsection">
<p>
<span class="caplead">Beneath a star-filled sky, Jason’s yacht</span> rocked gently on the soft wind-driven waves. On its deck, Danny carefully aimed his pulse rifle out across the black water.
</p>
<p>
“Can you make it hold still?” Danny insisted.
</p>
<p>
On the flying bridge above, Jason manned the helm. “Can I make what hold still?”
</p>
<p>
“The boat.”
</p>
<p>
“It’s on water, Danny,” Jason responded testily. “It’s as still as it’s going to get.”
</p>
<p>
Danny’s HERF gun rested on a large tripod. The gun bore a large attachment on its muzzle: a domed dish a yard wide, made from chicken wire and aluminum foil. In front of the dish, a copper plate sat on a collapsible plastic rod several inches long, with wires running to a circuitboard in Danny's hands. Lights and gauges flashed patterns that only Danny could decipher.
</p>
<p>
“Well, this boat has to stop bobbing if I’m going to get a decent shot,” said Danny.
</p>
<p>
“Can you even hit anything from all the way out here?” Jason asked.
</p>
<p>
“Oh yeah,” Danny replied, eyeing the indicator lamps on the circuitboard. “This parabolic field antenna boosts the HERF gun’s output gain by about thirty decibels. Those Coast Guard radar stations along the shore? I can knock them out from half a mile away. But it narrows the beam, so I need to line it up just right…”
</p>
<p>
Out past the HERF gun’s parabolic antenna, past the bow of the yacht and the silvery ripples of moonlit water, there spread the steep, dark, tree-lined banks of the Medina waterfront. And over that waterfront, dwarfing the personal mansions of tech tycoons beside it, rose the twelve-storied edifice of the Medina Gallante. Its floor-to-ceiling windows formed checkerboard patterns of glowing white and dark iridescent green. Gray cobblestone pillars buttressed its walls. Sloped brown beams of cedar supported its staggered multi-leveled roofs. The luxury hotel followed the contours of the sloping hillside shore upon which it was built, giving it an air of natural belonging, like a living growth of wood, stone, and crystal rising up from the forested waterline.
</p>
<p>
At the base of the hotel, a private wharf jutted out into the water. A handful of small yachts swayed gently in the waves, moored to a few short piers.
</p>
<p>
“Do they have anyone patrolling the wharf?” asked Jason.
</p>
<p>
“Negative,” said Danny. “Satish and I read through some documents from the RockBox server that discuss the Gallante’s security protocols. They have one guy that handles yacht rentals during the day, but nobody’s watching the water at night…” He made more bare-handed adjustments to the curved shape of the wire mesh. Suddenly, he smiled at the readings on the circuitboard and announced, “Ah, here we go!”
</p>
<p>
He flipped a few switches on the energy cannon. Lights blinked on. Fans whirred.
</p>
<p>
“Now, keep in mind,” Danny said slowly while checking the device’s indicator lamps, “this is exactly what this device is built for. I made this little guy during Claymore’s contract with Naval Base Kitsap. The Navy wanted us to find and fix flaws in their communication system up there. I told them they needed to harden their electronics against directed electromagnetic pulses. They laughed and said that EMPs would never happen &mdash; that they’re, um, ‘sci-fi hootenanny’, were their exact words. Well, I told them, ‘Give me a high-powered radar magnetron, and I’ll show you hootenanny.’ So they did, just to humor me. And when I came back and demonstrated this device to them and proved I was right, they were surprisingly displeased…”
</p>
<p>
“Oh!” Jason said accusatorially. “So that’s what happened to the Kitsap contract! You know, the rest of the investors and I, we never got a straight answer from you guys about it…”
</p>
<p>
“Yeah, well. My point is, the Coast Guard’s radar systems are exactly the same kind as Naval Base Kitsap’s. Somewhere along that shoreline, there’s an automated radar station watching this stretch of water. It’s just a small plastic dome, about the size of a beach ball, probably painted to look like a rock. Inside, there’s an S-band magnetron, just like in this gun here. Except theirs is a twenty-kilowatt emitter built for continuous low-power scanning, while mine is a three megawatt monster optimized for one single high-impact burst.”
</p>
<p>
He held up the circuitboard, aglow with multicolored lights and gauges. 
</p>
<p>
“I’ve got a bead on them right now,” he explained. “According to this, their radar pod is currently sweeping the area with a 5-degree beam at 2.8 gigahertz…”
</p>
<p>
Danny crouched to fit his shoulder underneath the tripod-mounted HERF gun, and gingerly pulled the trigger. 
</p>
<p>
“…And now it’s not.”
</p>
<p>
After a moment of silence, Jason asked, “That’s it?”
</p>
<p>
Danny flashed him a satisfied grin.
</p>
<p>
“The Coast Guard’s radar is down?”
</p>
<p>
Danny nodded vigorously. “If by ‘down,’ you mean fried to a spark-singed crisp.”
</p>
<p>
“Will they notice?”
</p>
<p>
“They’ll no doubt send a repair crew in the morning,” said Danny. “But tonight, the sea is ours.”
</p>
<p>
Jason nodded. “Alright then. I’ll take her in. Slowly. You should go update the team.”
</p>
<p>
Danny saluted. “Aye aye, skipper!”
</p>
<p>
Jason looked out at the flat expanse of water ahead, and tapped the controls of the sleek cherrywood console that comprised the helm. A vibration quaked across the body of the yacht. Water burbled behind the vessel as the motor rumbled to life.
</p>
<p>
Danny made his way across the topside, holding onto random yacht-parts to keep his balance. He reached the stairs to take him below deck, to the cozy wood-paneled compartment where he had first met Mike and Moshen and Satish playing <em>Dungeons &amp; Dragons</em> just the previous day.
</p>
<p>
Upon the lacquered table sat several laptops, their screens showing floor plans, emails, and code. Freshly purchased cellphones and Bluetooth headsets lay on the leather benches surrounding the table, beside their recently opened packaging.
</p>
<p>
A large television screen on the room’s rear wall displayed the faces of Danny’s teammates in neatly tiled teleconferencing windows. In one corner, he could see Tina tending to glassware in his kitchen. In another, Satish, still in his office, examined source code. Mike and Natalie shared a video feed from the hospital room, the two of them bantering in obnoxiously cute tones. A small icon represented Moshen, available only by voice.
</p>
<p>
“Guys,” Danny announced. The faces of his teammates turned toward their respective monitors. “It’s happening.”
</p>
<p>
Mike was the first to respond. “I’m ready to start poking through their network as soon as Satish gives me a back door. I’ve taught Nat-Nat how to work the camera feeds, so we’ll be your eyes and ears.”
</p>
<p>
“Thank you, Mike,” Danny said. “Are you sure you’re feeling up for this?”
</p>
<p>
Mike nodded his large furry head. “What else am I going to do, just lie here? They want to hold me for two more days for monitoring. Do you have any idea how boring it is to be stuck in a hospital bed?”
</p>
<p>
Moshen’s voice chimed in over the conference call. “ ‘Nat-Nat’? You call her ‘Nat-Nat’? What does she call you? ‘Snugglewumpus’?”
</p>
<p>
Natalie giggled. “Oooh! Snugglewumpus! I like that one! My Snugglewumpus…”
</p>
<p>
Mike cooed back, “I could see myself as your Snugglewumpus!” The two of them started making out on camera.
</p>
<p>
Danny grabbed a mouse on the lacquered table and hid their window. “Satish. Speaking of that back door, how’s our trojan coming?”
</p>
<p>
Satish’s head swiveled. “Good to go, Danny. I’ve sent you the executable. I found a weakness in the integration of their billing system. It was built by a different contractor than the security system. Both billing and security by themselves are pretty solid, but the connection between them is sloppy, like the two contractors weren’t really working together to make sure their systems talked to one another correctly. The bottom line is, I’ve got a rootkit ready. As soon as this program runs on a computer that accesses the Gallante’s billing system, I take complete control.”
</p>
<p>
Danny checked his DropBox account on one of the laptops on the table. A new executable file awaited him. “Good work, Satish. Thank you.”
</p>
<p>
“It still needs to be delivered by hand, Danny,” Satish warned. “Physically. You know what that means.”
</p>
<p>
Danny nodded, and plugged his data stick into the USB port of the laptop. “It means,” he said while copying files, “that I’m going to be checking out the Gallante’s fine dining establishments.” With the files transferred to his data stick, Danny turned his attention to the small motionless icon. “Moshen, what about you? What's your status?”
</p>
<p>
Moshen’s disembodied voice replied, “I’m parked on some random side-street about five miles away.”
</p>
<p>
“Great,” Danny said. “How are you feeling? Confident? Pumped?”
</p>
<p>
Moshen said, “Um…”
</p>
<p>
On a tree-lined residential road somewhere in Seattle’s eastern suburbs, a boxy gray van marked “Claymore Communications” stood on the curb. Moshen sat in the driver’s seat, his scrawny arms hanging loosely from the steering wheel. To his right, Sergey Mukhayev stared brooding out the windshield, his hulking form breathing tensely as he gazed into the night. Behind them, Leo adjusted the suppressor on his handgun while Eugene idly twirled a razor-sharp butterfly knife with deadly dexterity.
</p>
<p>
“I… can’t complain…” Moshen said carefully.
</p>
<p>
Danny switched his focus to Tina. Her dark hair framed her face as she looked downward, tinkering with objects offscreen. Her small nose stud glinted in the light of his kitchen. “Tina. Status?”
</p>
<p>
She replied with a tired half-smile, “I’ve been Betty Crockering all day. FYI, I’d never eat in this house ever again if I were you.”
</p>
<p>
“I have a job for you during this operation,” Danny said. “It’s a job you’re best prepared for out of all of us, and it’s critical to the mission’s success.”
</p>
<p>
“As long as it gets me out of the kitchen,” she replied. “What do you need?”
</p>
<p>
“You’re not going to like it.” He hesitated for a few moments.
</p>
<p>
“Well?” she pressed.
</p>
<p>
Danny replied, “Communications officer.”
</p>
<p>
“What does that mean?” she asked suspiciously.
</p>
<p>
“You know, like Uhura from Star Trek,” said Danny.
</p>
<p>
“Which means…?” she repeated.
</p>
<p>
“Well, see,” Danny explained, “the Gallante’s phone switch plugs into a Cisco VOIP telephony system, which Mike should be able to get command of. And their security guards have walkie-talkies that use a trunked P25 digital radio system with an RTP cross-bridge, which Satish will probably be able to take over. What this means is that we can route all voice traffic &mdash; incoming, outgoing, and internal &mdash; to a SIP user agent on your terminal. And your professional experience coordinating Skype teleconferences gives you the best mastery of Skype meeting controls out of all of us…”
</p>
<p>
“<em>Which means…?</em>”
</p>
<p>
“…You’ll be answering phones,” Danny said.
</p>
<p>
She glared at him with a gaze so cold that her image almost began frosting the screen.
</p>
<p>
“…You know, because… Your day job…” Danny stammered.
</p>
<p>
“I hate you so much right now,” she said.
</p>
<p>
He looked away sheepishly. “I… I know…”
</p>
<p>
Without warning, the low rumble of the yacht’s engines cut out. Footsteps sounded from above. Through the portholes, Danny could see Jason walking along the deck, dragging ropes to secure the yacht to the dock.
</p>
<p>
“It’s almost go-time,” Danny told his teammates.
</p>
<p>
Mike said to him, “Be careful, Danny. Stay out of sight.”
</p>
<p>
“Don’t worry, Mike,” Danny replied. “I’ve got that covered. Watch this. Now you see me…”
</p>
<p>
He stepped out of the view of the webcam and dug through the piles of equipment and supplies on the benches around the table. After a few moments, he stepped back into frame. He was wearing blue coveralls, a toolbelt, and a plastic ID holder with a plain white card inside. In one gray-gloved hand he held his HERF gun, while in the other he carried a large red toolbox.
</p>
<p>
“…Now you don’t!”
</p>
<p>
The footsteps on the deck came around to the aft of the vessel. Jason descended into the cabin. He waved hello to the faces on the screen. “The ship’s secure, Danny.”
</p>
<p>
Danny took a deep breath to steel himself.
</p>
<p>
“Try not get killed, okay?” said Jason. “Come back here when you’re ready for extraction. I’ll be waiting.”
</p>
<p>
“Actually, Jason,” Danny said, “there’s a very important task that I need you to handle.”
</p>
<p>
“What’s that?”
</p>
<p>
“The same thing I did for you forty-eight hours ago. I need you to prepare a PowerPoint presentation.” 
</p>
<p>
</div>