<div class="chapsection">
<p>
<span class="caplead">Beneath a star-filled sky, Jason’s yacht</span> rocked gently on soft wind-driven waves.
</p>
<p>
“Can you make it hold still?” Danny insisted.
</p>
<p>
On the bridge above, Jason manned the helm. “Can I make what hold still?”
</p>
<p>
“The boat.”
</p>
<p>
“It’s on water, Danny. It’s as still as it’s going to get.”
</p>
<p>
He braced his HERF gun against the yacht’s handrail. Lights and gauges on the device flashed patterns that only Danny could decipher.
</p>
<p>
“Well, this boat has to stop bobbing if I’m going to get a decent shot,” said Danny.
</p>
<p>
“Can you even hit anything from all the way out here?” Jason asked.
</p>
<p>
“Oh yeah,” Danny replied, eyeing the indicator lamps. “I can boost the gain up to thirty decibels. Those Coast Guard radar stations along the shore? I can knock them out from half a mile away. But boosting tightens the beam, so I need to line it up just right…”
</p>
<p>
Out past the HERF gun’s nozzle, past the bow of the yacht and the moonlit water, there spread the steep tree-lined banks of the Medina waterfront. And over that waterfront, dwarfing the personal mansions of tech tycoons, rose the twelve-story edifice of the Medina Gallante. Its floor-to-ceiling windows formed checkerboard patterns of iridescent green. Cobblestone pillars buttressed its walls. Sloped brown beams of cedar supported multi-leveled roofs. The hotel’s architecture invoked a sense of natural belonging, like a living growth of wood, stone, and crystal rising up from the forested waterline.
</p>
<p>
At the base of the hotel, a private wharf jutted out into the lake. A few moored yachts swayed in the waves.
</p>
<p>
“This is exactly what this device is designed for,” Danny explained as he made adjustments. “I built this guy during Claymore’s contract with Naval Base Kitsap. The Navy wanted us to find and fix flaws in their communication system. I told them they needed to harden their electronics against directed electromagnetic pulses. They laughed and said that EMPs are, um, ‘sci-fi hootenanny’, were their exact words. Well, I told them, ‘Give me a high-power magnetron, and I’ll show you hootenanny.’ They did, just to humor me. And when I came back and demonstrated this device to prove my point, they were surprisingly displeased…”
</p>
<p>
“Oh!” Jason said. “So <em>that’s</em> what happened to the Kitsap contract! You know, the rest of the investors and I, we never got a straight answer from you about it…”
</p>
<p>
“Yeah, well. My point is, the Coast Guard’s radar systems are exactly the same kind as Naval Base Kitsap’s. Somewhere along that shoreline, there’s an automated radar station watching this stretch of water. It’s a plastic dome, about the size of a beach ball, painted to look like a rock.” He studied the device’s multicolored lights. “I’ve got a bead on them right now. Their radar pod is sweeping the area with a 5-degree beam at 2.8 gigahertz…”
</p>
<p>
Danny pulled the trigger. 
</p>
<p>
“…And now it’s not.”
</p>
<p>
Jason asked, “That’s it?”
</p>
<p>
Danny flashed him a satisfied grin.
</p>
<p>
“Just like that? The Coast Guard’s radar is down?”
</p>
<p>
Danny nodded. “If by ‘down,’ you mean fried to a crisp. They’ll no doubt send a repair crew in the morning. But tonight, the sea is ours.”
</p>
<p>
Jason nodded. “Alright then. I’ll take her in. Slowly. You go update the team.” He tapped the controls of the cherrywood console. A vibration quaked across the yacht. Water burbled behind the vessel.
</p>
<p>
Danny made his way across topside, and descended the stairs to the wood-paneled compartment where he had first met Mike and Moshen and Satish playing <em>Dungeons &amp; Dragons</em> the previous day.
</p>
<p>
Upon the lacquered table sat several laptops, their screens showing floor plans, emails, and code. Freshly purchased cellphones and Bluetooth headsets lay on the leather bench seats.
</p>
<p>
A television on the room’s rear wall displayed the faces of Danny’s teammates in neatly tiled teleconference windows. In one corner, he could see Tina tending to glassware in his kitchen. In another, Satish, still in his office, examined source code. Mike and Natalie shared a feed from the hospital room, and bantered in obnoxiously cute tones. A small icon represented Moshen, available only by voice.
</p>
<p>
“Guys,” Danny announced. “It’s happening.”
</p>
<p>
Mike responded, “I’m ready to poke through their network as soon as Satish gives me a back door. I’ve taught Nat-Nat how to work the camera feeds, so we’ll be your eyes and ears.”
</p>
<p>
Danny asked, “Mike, are you sure you’re feeling up for this?”
</p>
<p>
Mike nodded. “What else am I going to do? They want to hold me for two more days. Do you know how boring it is to be stuck in a hospital bed?”
</p>
<p>
Moshen’s voice chimed in. “‘Nat-Nat’? You call her ‘Nat-Nat’? What does she call you? ‘Snugglewumpus’?”
</p>
<p>
Natalie giggled. “Oooh, I like that one! My Snugglewumpus…”
</p>
<p>
Mike cooed back, “I could see myself as your Snugglewumpus!” They started making out on camera.
</p>
<p>
Danny grabbed a mouse and hid their window. “Satish. Speaking of that back door, how’s our trojan coming?”
</p>
<p>
“I found a weakness in the integration of their billing system,” Satish replied. “It was built by a different contractor than the security system. By themselves, both billing and security are pretty solid. But their connection is sloppy. I’ve sent you a rootkit. As soon as this program runs on a computer that accesses the Gallante’s billing system, I take complete control.”
</p>
<p>
Danny checked his DropBox account. A new file awaited him.
</p>
<p>
“It needs to be delivered by hand, Danny,” Satish warned. “Physically. You know what that means.”
</p>
<p>
Danny nodded, and plugged his data stick into a USB port. “It means,” he said while copying files, “that I’ll be checking out the Gallante’s fine dining establishments.” Danny turned his attention to the small motionless icon. “Moshen, what’s your status?”
</p>
<p>
Moshen’s disembodied voice replied, “I’m parked on some side-street five miles away.”
</p>
<p>
“Great,” Danny said. “How are you feeling? Confident? Pumped?”
</p>
<p>
Moshen said, “Um…”
</p>
<p>
On a tree-lined residential road somewhere in Seattle’s eastern suburbs, a boxy gray van marked “Claymore Communications” stood on the curb. Moshen sat in the driver’s seat, his thin arms hanging loosely from the steering wheel. To his right, Sergey Mukhayev stared brooding, his hulking form breathing tensely as he gazed into the night. Behind them, Leo adjusted the suppressor on his handgun while Eugene deftly twirled a butterfly knife.
</p>
<p>
“I… can’t complain…” Moshen said.
</p>
<p>
Danny switched focus to Tina. Her dark hair framed her face as she looked downward, tinkering with objects offscreen. “Tina. Status?”
</p>
<p>
She replied with a tired half-smile, “I’ve been Betty Crockering all day. FYI, I’d never eat in this house again if I were you.”
</p>
<p>
“I have a job for you,” Danny said. “It’s a job you’re best prepared for out of all of us, and it’s mission-critical.”
</p>
<p>
“As long as it gets me out of the kitchen,” she replied. “What do you need?”
</p>
<p>
“You’re not going to like it.” He hesitated for a few moments, and finally said, “Communications officer.”
</p>
<p>
“What does that mean?” she asked.
</p>
<p>
“You know, like Uhura from Star Trek,” said Danny.
</p>
<p>
“Which means…?” she repeated.
</p>
<p>
“The Gallante’s phone switch plugs into a Cisco VoIP system,” Danny explained, “which Mike will control. And their security guards have walkie-talkies that use a trunked P25 digital radio system with an RTP cross-bridge, which Satish will take over. We can route all voice traffic to a SIP user agent on your terminal. And your professional experience coordinating Skype meetings gives you mastery of teleconferences controls…”
</p>
<p>
“<em>Which means…?</em>”
</p>
<p>
“…You’ll be answering phones,” Danny said.
</p>
<p>
She glared at him with a gaze so cold that her image almost began frosting the screen.
</p>
<p>
“…You know, because… Your day job…” Danny stammered.
</p>
<p>
“I hate you so much right now,” she said.
</p>
<p>
He looked away meekly. “I know…”
</p>
<p>
The rumble of the yacht’s engines cut out. On the deck above, Jason slung ropes to moor the yacht to the dock.
</p>
<p>
“It’s go-time,” Danny told his teammates.
</p>
<p>
Mike said, “Be careful, Danny. Stay out of sight.”
</p>
<p>
“Don’t worry,” Danny replied. “I’ve got that covered. Watch this. Now you see me…”
</p>
<p>
He stepped away from the webcam and rummaged through supplies. When he returned, he had changed clothes. He wore blue coveralls, a toolbelt, and a plastic ID holder with a plain white card. One gray-gloved hand held his HERF gun, while the other carried a large red toolbox.
</p>
<p>
“…Now you don’t!”
</p>
<p>
Behind him, Jason descended into the cabin. “The ship’s secure, Danny.”
</p>
<p>
Danny took a deep breath to steel himself.
</p>
<p>
“Try not get killed,” said Jason. “Come back here when you’re ready for extraction. I’ll be waiting.”
</p>
<p>
“Actually, Jason,” Danny said, “there’s a very important task that I need you to handle.”
</p>
<p>
“What’s that?”
</p>
<p>
“The same thing I did for you forty-eight hours ago. I need you to prepare a PowerPoint presentation.” 
</p>
</div>