<div class="chapsection">
<p>
<span class="caplead">The mercenaries stared at the screen</span>, murmuring. Ivan barked at them.
</p>
<p>
Danny interrupted, “He’s finished! As of right now, he has no money and no power. He’s nothing but a penniless old man.”
</p>
<p>
Ivan stared at him through narrowed, wrinkly eyes. “You are such idiot. You think <em>that</em> is all my money?” He pointed at the bank balance on the screen. “That is <em>pocket change</em>! That is one weekend gambling in Monaco! You think you stealing this one account making me ‘penniless’?”
</p>
<p>
“No,” Danny said slowly. “I’m not talking about the account. What I’m talking about, Ivan, is your business ventures.”
</p>
<p>
The television flashed. The image cut to a pie chart overlaid on a map of Eastern Europe. One small pink wedge was marked with a pin-up silhouette; a steel-gray section showed a handgun; a brown slice bore a hypodermic needle. But by far the largest wedge, taking up over half the pie, was colored white, flanked by a line of cocaine.
</p>
<p>
“We’ve examined your finances, Ivan,” Danny boasted. “This is the breakdown of your revenue. There’s the usual: sex trafficking, arms trading. But most of your income is from drugs &mdash; specifically, cocaine. And so it appears, Ivan, that you have made&mdash;” The screen cut to a photograph of the Tungsten Medical Technologies building. “&mdash;a very poor investment decision.”
</p>
<p>
Ivan laughed dryly. “You know so little!” He reached into his chest pocket and produced the small translucent smiley-faced Eppendorf vial. “Tungsten is best investment I ever make!”
</p>
<p>
“There’s something I’d like to show you,” said Danny. “It’s inside my toolbox.”
</p>
<p>
Ivan spoke a few gruff words to a nearby bodyguard. The man yanked the box from Danny, set it down on the coffee table, and cautiously unbuckled the lid. Slowly, he drew from the box a small translucent Eppendorf vial filled with pale brown goo.
</p>
<p>
The other men crowded in to take a closer look. Their eyes shifted between the vial in Ivan’s hand and the one pulled from the box.
</p>
<p>
“Pass them around,” Danny said pleasantly. “I brought enough for everybody.”
</p>
<p>
The bodyguard pulled out another Eppendorf vial, identical to the first. Then another. And another.
</p>
<p>
“Each one is cloned directly from that batch you’re holding in your hand,” Danny explained. “You’re a businessman, Ivan. You saw this genetic engineering project as a chance to control your entire supply chain, without having to depend on manufacturers in South America. That’s why you had Tungsten create this bacterium &mdash; to produce a source of cocaine that’s portable, durable, and easily replaced. Well, guess what, Ivan? You wanted ‘easily replaced’? You got it.
</p>
<p>
“See, we in the technology industry have a name for what you’ve done: ‘disruptive innovation’. It’s a creation whose very existence completely changes the marketplace forever.”
</p>
<p>
The screen filled with a collage of images: a printing press, a flint-lock firearm, a light bulb, a Model T Ford, an airplane, a nuclear explosion, an IBM mainframe computer, an iPhone. The photograph of the Eppendorf vial with the Tungsten logo floated in a corner.
</p>
<p>
“Here’s the bittersweet secret about the tech world,” Danny continued. “Those of us who help overturn outdated methods and old paradigms render ourselves obsolete by our own innovations. We find ourselves at a competitive disadvantage against younger, fresher minds &mdash; minds that are uncluttered by knowledge of derelict systems that we had to learn in order to replace. The youth that follow will only know the world we have made for them; they will never know the world we came from. The pinnacle of our achievements, the greatest heights to which we can climb, will for them be merely their starting point. They will take for granted our lifetimes of work and claim it as their birthright. They’ll use our own accomplishments to leave us in the dust. The world moves on &mdash; and it does so because we <em>make</em> it move on. Because, as a technologist, that’s the whole point.
</p>
<p>
“And now, Ivan… Take a look at what the youth of today are doing with <em>your</em> accomplishments right this minute.”
</p>
<p>
On the television screen appeared a YouTube video page. The frame showed a T-shirted young man sitting in a dark room. His face was hidden behind a pale mask bearing the smug countenance of Guy Fawkes, the subversive mascot of the Anonymous hacker collective.
</p>
<p>
“So, check this crazy shit,” he said from behind the mustachioed mask. His energetic voice sounded in its mid-twenties. “There’s this dude I know from the Maker meetup group. Older dude. He DMed me this afternoon. He goes, ‘Let’s meet in private. There’s a message I need to get out.’ And at first I’m like, ‘Man, we’re not friends. We just see each other around. Stop being weird.’ But then he says, ‘I know you’re with Anonymous. This is relevant.’ So I’m like, alright, I’ll take a chance. I invite him down to my lair. Well, he and a girl show up like ten minutes later. And they bring <em>this</em>…”
</p>
<p>
The Fawkes-faced young man held up a goo-filled vial.
</p>
<p>
“So, obviously I’m like, ‘What’s that?’ He says, ‘It’s the next logical step for hackers. Computers are overdone. This is hacking DNA.’ The girl walks me through how to grow it &mdash; like sea monkeys, kinda. So we whip up a batch, and he gives me a bunch of empty test tubes and says, ‘Spread this out to as many people as you can, and do it <em>fast</em>.’ And I’m like, ‘Why? What <em>is</em> this stuff?’ He says nothing. He reaches into his bag, and he pulls out…”
</p>
<p>
The young man held up a cellophane-wrapped brick of white powder.
</p>
<p>
“Now, that, kids, is exactly what it looks like. I tried a bit. It’s a hundred percent the real deal. And this dude had like a dozen of them. That’s right, folks. This little tube of snot literally makes coke by the kilo. This is a straight-up game-changer, folks. You’re witnessing history in the making. This goop here turns the entire cocaine industry into a do-it-yourself project.
</p>
<p>
“So, I’m calling all my bros and sisters in the 206. Get your butts over here. This dude gave it to me, now I’m gonna give it to you. And then tomorrow you guys give it to others. This shit’s about to &mdash; heh &mdash; go viral.”
</p>
<p>
Underneath the video, the comment section’s count was already into quadruple digits.
</p>

<div class="computer email">
me gusta!<br/>
<strong>youcancallmegoddess 2 minutes ago</strong><br/>
<br/>
HOLY SHIT NEAT!<br/>
<strong>wilcobox 3 minutes ago</strong><br/>
<br/>
Yo bro bring that shit to Philly stat!<br/>
<strong>linkopteryx47 5 minutes ago</strong><br/>
<br/>
Guys, I'm a bioengineering PhD student @UCDavis and to everyone saying this is bullshit, it's absolutely possible with the right resources. Send me a sample, my advisor will bust a nut over this.<br/>
<strong>monicapetrelli 6 minutes ago</strong><br/>
</div>

<p>
“And it’s not just on YouTube,” said Danny. “It’s on Twitter, Craigslist, reddit, SMS. There’s a hundred cloned vials floating around the city by now. In two days, there’ll be a thousand. In a week, there’ll be hundreds of thousands across the country. You’ve created a living thing here, Ivan. And do you know what a living thing does, by definition? It multiplies.
</p>
<p>
“Isn’t this what you wanted, Ivan? You set out to create a technology that you could use to liberate yourself from Colombian drug cartels. Well, guess what? Now that you’ve created it, that exact same technology can be used just as easily by anyone else to liberate themselves from <em>you</em>.
</p>
<p>
“So, Ivan, the question is: What will this do to the market value of cocaine? Your single most profitable product? The only product that keeps your entire empire in the black? Well, you’re a businessman. You do the math. 
</p>
<p>
“The truth is, Ivan, you should be proud of yourself. I truly mean that. Oh sure, financially, this might be an unmitigated disaster. But as a <em>technologist</em>, what you’ve done is what people like me <em>dream</em> of doing. You’ve changed the world. In fact, you’ve changed it so thoroughly that you no longer even have a place in it. You’ve pushed the world so far forward that it’s left you behind. You stand here now completely spent, having given to the world everything you have to offer. And now, all your talents, all your efforts, everything that has enabled you to achieve this triumph &mdash; all of it, specifically <em>because</em> you’ve achieved it, is now obsolete and useless.
</p>
<p>
“And you know what the real irony is? Finding yourself obsolete and useless? That’s <em>not</em> defeat. It’s the exact opposite: it’s how you know your mission’s been accomplished. It’s how you know you’ve achieved your goals. It isn’t a hallmark of failure; it’s the pinnacle of victory. When you’ve used yourself up… When you’ve rendered yourself pointless by your own hand… When you feel your knees buckle from fatigue and you collapse, exhausted and weak and old, onto the dusty path along which you’ve been pushing the world, and it rolls away from you, propelled forward by the momentum you had spent your life imparting to it, and you watch the world recede toward the horizon carrying the next generation onward to a future you’ve made possible and yet you will never see… …Then! <em>Then</em> is when you can finally let your head drop down into the dirt with a smile on your lips, when you can finally rest; because <em>then</em> is when you know that you’ve succeeded.
</p>
<p>
“And, Ivan? You’ve succeeded.”
</p>
<p>
On the television, a map of Seattle’s metropolis appeared. It was sprinkled with dozens of tiny pictures of the Eppendorf vial. The icons were packed into clusters in the University District, on Capitol Hill, in Belltown, in Pioneer Square &mdash; all high-density neighborhoods of young, technologically savvy urban professionals. A new vial icon popped onto the display in Fremont, then another on Beacon Hill. The map gradually zoomed out. Slowly, the icons began peppering West Seattle, then Lynnwood, then Burien, then Bellevue, then Redmond &mdash; and as everyone watched, the little Eppendorf vials spread ever outward.
</p>
<p>
The suite’s overhead lights flicked back to life.
</p>
<p>
Ivan glared at Danny. “You will regret what you have done! If you thinking I would letting this… this crime against me…”
</p>
<p>
“Ivan, this presentation you just saw… Do you think <em>you</em> were the target audience? None of this was for you.” Danny slowly swept his arm around the room to Ivan’s entourage. “It was for them.”
</p>
<p>
The mercenaries and prostitutes all looked back at Danny with expressions that spread across a wide spectrum, from contempt to curiosity to simply being impressed by his gall.
</p>
<p>
“What do you all think?” Danny prompted. “Do you think this guy is going to be a stable employer for much longer? Do you think he’ll still be able to take you on private jets to luxury hotels around the world a month from now? Hook you up with corporate perks? Pay for your health insurance and a nice pension plan? If you ask me, your prospects with this guy don’t look promising.”
</p>
<p>
The television flipped back to Ivan’s bank account.
</p>
<p>
“I have an alternate proposal for all of you,” Danny continued. “You see the balance shown on that screen? You guys bring Sergey’s daughter to me, unharmed. As soon as she and I are away from this hotel, my colleagues and I will take the money in this account and divide it up between each of you equally. We’ll transfer it to your own personal bank accounts directly, the moment she and I are at a safe distance. Count how many of you are in this room. Look at the numbers on the screen. Do the math.
</p>
<p>
“And as you consider my offer, bear something in mind. Each of you will <em>only</em> receive this money if both the girl and I walk out of here alive. If any one of you chooses to shoot me, you will not only be losing the cash for yourself; you will also be losing the cash for every one of your colleagues. Look around you. Decide whether or not that seems like a good idea.” Danny chose a soldier at random, looked him in the eye, and asked “What do you think?” He pivoted toward another and repeated, “What do <em>you</em> think?” He turned to face the lithe man holding the gun to him. “What about you?”
</p>
<p>
The man’s thin brows twitched into a furrow. He looked quizzically at Ivan.
</p>
<p>
Ivan yelled at him in Russian.
</p>
<p>
One of the other mercenaries in the room reluctantly spoke up.
</p>
<p>
Ivan erupted in a torrent of sharp words. He railed at the speaker and all the other men in the room. His nostrils flared; spittle flew from his lips.
</p>
<p>
In an instant, by an order from Ivan, a few of the men turned their guns away from Danny. They pointed them instead at the mercenary who had spoken out. Taken by surprise, the man raised his arms and said something quick and apologetic.
</p>
<p>
Another man came to the speaker’s defense. He said something to one of the bodyguards still loyal to Ivan. The two began to argue. They pointed their guns at one another.
</p>
<p>
There was more bickering, more tense discussion and hasty negotiation. More guns pivoted away from Danny and turned to bear down on each others’ wielders.
</p>
<p>
Ivan screamed hoarsely. He was ignored.
</p>
<p>
Outside, beyond the scuffle, the doors to the suite’s balcony hung open. There, in the moonlit darkness, a hint of motion caught Danny’s attention. A thin black nylon cord dropped onto the balcony floor from somewhere above, so silent and discreet that the arguing mercenaries failed to notice. The outline of a man’s helmeted head, suspended upside down, peeked surreptitiously from the top of the doorway.
</p>
<p>
The figure hanging inverted above the balcony stretched an arm out toward the room. In its hand was a small silver snub-nose revolver.
</p>
<p>
A low boom thundered through the suite, as though the room had been suddenly plunged into a thick ocean of liquid air.
</p>
<p>
One of the men on the periphery of the standoff crumpled to the floor. A dark, viscous slurry of organic matter poured from his side. A corner of his rib cage was missing.
</p>
<p>
Eugene, hanging upside down, swung his gun toward a second target.
</p>
<p>
Men and women dove for cover in all directions.
</p>
<p>
Three of the mercenaries opened fire toward the balcony, shaking the room with syncopated gunshots. Eugene pulled himself upward, out of the reach of their bullets. They rushed outside. With their guns pointed upward, they burst through the balcony doors &mdash; and there, they hesitated as their eyes adjusted to the darkness.
</p>
<p>
That moment was all Eugene needed.
</p>
<p>
He swung his feet down and kicked a man in the head, then dropped in behind him while he was still reeling. Eugene’s hand made a quick jabbing motion at the mercenary’s neck. When the hand came away, Eugene’s butterfly knife protruded from the man’s throat. The mercenary gurgled and fell to his knees, pink foam frothing from his lips.
</p>
<p>
Before the other two soldiers could bring their guns to bear, two more shots rang out from Eugene’s revolver. One man collapsed to the balcony floor.
</p>
<p>
The remaining bodyguard managed to get a handful of rounds off from his handgun, striking Eugene in the abdomen and chest. Eugene stumbled backwards from the impacts. The hammer of the man’s gun clicked against an empty chamber. He took a step toward Eugene, expecting to see him fall limp.
</p>
<p>
Instead, he heard the bullets, flattened and deformed into squashed mushroom-like shapes, dinging like coins against the balcony floor.
</p>
<p>
Eugene glanced down for a moment at his body armor, taking stock of the dimples where the bullets had hit. Then his eyes rose back up to zero in on the remaining mercenary with a look of extreme displeasure.
</p>
<p>
There was a blur of motion. It ended with the man’s body careening over the edge of the railing, his screams falling away toward the ground far below.
</p>
<p>
With the balcony cleared, Eugene tilted his head to the side to crack his neck, and came over to his stabbed victim to retrieve his knife.
</p>
<p>
The cedarwood doors of the Presidential Suite crashed open. Sergey stood in the doorway, MAC-10 in hand, crouched behind his ballistic shield. Behind him, in the antechamber, Leo took aim with his M4.
</p>
<p>
The mercenaries scrambled. Some began shooting; their bullets deflected and bounced at unpredictable angles off of Sergey’s shield with high-pitched “<em>ploinks!</em>”
</p>
<p>
The wiry man who had held Danny at gunpoint was crouched near the glass coffee table. Upon Sergey’s entrance, he looked around frantically for someplace to hide. At the exact moment he turned to face the front doorway, a low boom burst from Leo’s rifle.
</p>
<p>
Danny vaguely registered a black form zip through the air, a ghost’s shadow. The projectile slammed the shark-faced man in the chest, sledgehammering him backward, down into the sunken living room. The man hurtled against the coffee table, upending it, sending the toolbox and the towel-covered crystal bowl clattering to the floor.
</p>
<p>
But Danny didn’t actually see or hear them land. The thing that had struck the man’s chest exploded.
</p>
<p>
It had come from the underslung M203 projectile launcher of Leo’s rifle. It was black with a rubbery surface, about the size of a pill bottle. Its pyrotechnic formula was designed to throw no shrapnel and spout no flame. Instead, for one infinitessimal instant, it burned twice as bright as the sun and boomed louder than a jet engine.
</p>
<p>
It was a 40-millimeter spin-stabilized flash grenade. And when it went off, Danny was looking at it.
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">There was a crushing sensation</span> as his body was slammed against a wall of solid sound. The very air around him tried to squeeze the life out of him.
</p>
<p>
Suddenly, there was no gunfire. There were no men shouting, no bullets slicing through the air. There was no gravity, no up or down or sideways. There was only the pale void &mdash; directionless, infinite.
</p>
<p>
Danny couldn’t tell how long he spent floating in that emptiness, blind and deaf and without bearing. The flash grenade was a nonlethal munition, but it was unmistakably a weapon &mdash; an energy weapon. It was a perfectly crafted attack against the human body’s sensory systems, exploiting overflow vulnerabilities in its acoustic and electromagnetic transduction machinery. And in that moment, Danny knew exactly what it was like to be an electronic device getting hit by a pulse from his HERF gun.
</p>
<p>
Formless ripples eventually danced in the milky emptiness. Shimmering ghosts coalesced into shapes. Colors and hues, pale and washed-out at first, slowly re-saturated.
</p>
<p>
He saw a large, dark shape rushing at him out of the snowy void.
</p>
<p>
Danny tried to dodge the oncoming blur, but he was too unbalanced. Before he could even move, the shadow was upon him.
</p>
<p>
He felt his body suddenly pressed against a bulky torso clad in plate-reinforced bulletproof padding, like the chest of a charging bull dressed for battle. A meaty arm grabbed him under his armpit. The dark figure pulled him off of his unsteady feet and dragged him across the unseen room. 
</p>
<p>
Beneath the ringing din, he heard the faint tinny chatter of many voices. “Danny! Are you okay?” “Talk to us!” “Danny, what's going on?” He felt their vibrations directly on the skin of his ear, and realized that they were coming from his Bluetooth headset.
</p>
<p>
From the other side of the dark figure, bullets ricocheted off of reinforced polymer, zinging and plinking in random directions. Somewhere off to his flank, the periodic <em>rat-tat-tat!</em> of fully-automatic gunfire cracked through the air, low and muffled as though heard from underwater. Danny’s nostrils filled with the acrid, metallic smell of burnt gunpowder.
</p>
<p>
The texture of the light and shadows around him shifted. He recognized the rectangular shape and rich brown color of the cedar door as it passed by. Danny blinked hard. His eyes hurt with a dull burning ache, like fatigued muscles. The antechamber just outside the Presidential Suite came into focus. He found himself near the elevator.
</p>
<p>
The dark figure set Danny on his feet. Danny steadied himself and looked up.
</p>
<p>
He saw, looking back into his eyes, the helmet-covered face of Sergey Mukhayev. The armor-clad man pushed Danny toward the door to the emergency stairwell, underneath a glowing red “Exit” sign.
</p>
<p>
And he heard Sergey’s voice &mdash; through the helmet, the gunfire, the ringing &mdash; yell, “<em>Go!</em>”
</p>
<p>
At the cedarwood doorway, Leo shouted something in Russian and began backing away from the entrance. Sergey spun back toward the door and swung his MAC-10 toward the entryway. He charged away from Danny, bounding forward behind his shield; the floor seemed to shake with his wide, heavy footfalls. He rushed into the room, fighting against the force of the bullets slamming into his shield.
</p>
<p>
For the first time in what felt like minutes, Danny took a breath.
</p>
<p>
He suddenly realized that Sergey’s command to him was probably a very good idea.
</p>
<p>
Danny took one look at the emergency exit door and pushed both palms against its crash bar. The heavy metal barrier whooshed open into the dim, echoing stairwell. He stepped quickly onto the concrete landing and pressed the door shut behind him. The sounds of combat continued outside.
</p>
<p>
The buzzing chatter in his ear had never abated. But after a few seconds in the stairwell, with the fire door muffling the din of battle, the noises coming out of his Bluetooth headset finally began to form coherent speech.
</p>
<p>
“Danny!” Tina said. “Danny, come in! Please, <em>please</em> come in!”
</p>
<p>
“I’m here,” he replied. He had to take several seconds just to clear his throat.
</p>
<p>
“Are you alright?” Tina asked.
</p>
<p>
Yellow spots still danced before his eyes. His ears still overlaid the world with a high-pitched whine. “I’m honestly not sure.”
</p>
<p>
Jason spoke on the channel. “Danny, for God’s sake, get your ass out of there. It’s up to Sergey and his guys now. Our part is over.”
</p>
<p>
He took a moment to shake the tension out of his muscles, to clear himself of the fear and bravado. He closed his eyes and watched the blobs of color slowly fade from his sight, and took a few wobbly steps down the stairs. “I’m on my way, Jason. I’ll swing down to the security office to grab my HERF gun, then come meet you aboard your yacht. Be there in a few minutes.”
</p>
<p>
He was barely one flight down when the door crashed open above him.
</p>
<p>
The stairwell suddenly filled with the <em>rat-tat-tat!</em> of automatic rifle blasts and the dings of casings on concrete. The smooth, unadorned walls conducted the sound down the full height of the building.
</p>
<p>
Footsteps rushed toward him. Combat boots descended the steps, leaving bloody prints. The helmeted head of Leo the gunman peered down. “What in the hell are you still doing here?” he said. He limped as he walked.
</p>
<p>
A gunshot boomed through the stairwell. A bullet struck Leo’s armor with a sharp smack. He swung his rifle toward the door and fired a few rounds. 
</p>
<p>
Danny screamed and fled. Gravity did most of the work for him as he jostled down the stairs. The flights melted into a whizzing blur before his eyes &mdash; a kaleidoscope of gray stairs, black railing, water pipes and fire alarms.
</p>
<p>
Natalie’s voice appeared on the channel. “Danny, there’s two people with guns running to the stairwell.”
</p>
<p>
“More of Ivan’s men?”
</p>
<p>
“No, just random hotel guests,” said Natalie. “At least, I <em>thought</em> they are. All over the building, everybody’s running away from the stairwell. But these two &mdash; one guy and one woman &mdash; they whipped out guns and started rushing <em>toward</em> the emergency exit. They’re both standing outside the stairwell right now &mdash; they’re on either side holding their guns out.”
</p>
<p>
“What the fuck?” Danny screeched.
</p>
<p>
“One’s pulling out something from her pocket,” Natalie added. “It’s black with something shiny attached. The other’s talking on his cellphone in one hand with his gun in the other… Danny, the woman looks like she’s getting ready to body-check the door. The dude’s holding back a few feet, like he’s giving her cover.”
</p>
<p>
“Jesus. Sounds like they’re pros,” Danny said. “Who the hell <em>are</em> they?”
</p>
<p>
A fire door a few levels above burst open. A woman’s voice rang out, “Freeze! Police!”
</p>
<p>
Danny held his breath.
</p>
<p>
“Put your weapons on the ground,” she commanded slowly, “and raise your arms! Both of you!”
</p>
<p>
A few seconds of stillness followed. Danny gripped the railing tightly, holding every muscle taut, careful to avoid making a sound. He was a few landings below where the police had entered. <em>Both of you</em>, the woman had said, apparently referring to Leo and his attacker &mdash; meaning that they didn’t know Danny was below them. He willed himself to stay statue-like.
</p>
<p>
The man above said, “Buddy, I don’t care how big your gun is or how much armor you got on. How far you think you’ll make it on that bum leg?”
</p>
<p>
A gentle tap indicated a gun being placed on the floor, followed by the ratcheting clicks of handcuffs. Then came the distinct static of a two-way radio. The device that Natalie had seen wasn’t a cellphone &mdash; it was a walkie-talkie.
</p>
<p>
“Dispatch, come in,” said the man. “This is Detective Macintyre, with Detective Santello, on plainclothes investigation at Medina Gallante. We spotted a company van marked ‘Claymore Communications’ on the Medina municipal camera system, and gave it a routine tail. Dispatch, we’ve got a situation here…”
</p>
<p>
Leo interrupted. “I… need a bandage.”
</p>
<p>
“You need a surgeon, pal,” the cop replied. “But first… You have the right to remain silent. Anything you say can and will be used against you in a court of law…”
</p>
<p>
Below, Danny resumed descending the stairs, praying that the policeman’s voice would mask the sound of his movements.
</p>
<p>
Danny soon found himself on the wide ground-floor landing. To his side, the stairs continued downward to the parking garage. Ahead, a fire door stood between him and the maintenance corridor. He opened it gently, and stepped out of the dim stairwell into the fluorescent-lit “HOTEL STAFF ONLY” hallway.
</p>
<p>
“Cops,” he gasped into the Bluetooth. “Jesus. Tina, this whole building is going to be crawling with law enforcement soon. Tell Sergey and Eugene. They’ll need to be ready for extraction before the cavalry arrives.”
</p>
<p>
“I lost them.” Tina said. “Sergey’s connection went dead. Eugene’s still on the channel but he isn’t responding.”
</p>
<p>
Danny stared at the door to the stairwell from which he’d just emerged. “We can’t just leave them up there. They have to know about Leo and the cops…”
</p>
<p>
Jason chimed in. “Danny, you can check on them later. Right now you need to get to safety.”
</p>
<p>
Danny frowned. “You’re right.” He looked down the drab hallway. “I’ll go grab my HERF gun from the security office and join you on the yacht.”
</p>
<p>
The corridor was silent, save for the faint hum of fluorescent tubes. When he came to the security office, he was greeted by the blissfully familiar sight of his energy weapon charging against the wall.
</p>
<p>
Inside the room, an odd odor hung in the air: the acrid stink of burnt plastic. It came from the far end of the room, where Eugene had tied up the captives.
</p>
<p>
The trio of towel-clad mercenaries had broken free of Eugene’s knotwork. On the floor, near the stout Latina security guard, lay a cigarette lighter. The three underdressed Russians turned toward Danny and growled.
</p>
<p>
“Oh, God damn it,” Danny mumbled, and bolted.
</p>
<p>
The mercenaries gave chase, each self-consciously keeping one hand on the white towel around his waist. Danny sprinted toward the end of the corridor. Like a nightmare, the exit seemed to recede farther with each step. He knew he’d never make it.
</p>
<p>
A nondescript gray door passed on his side. With the men only a few feet behind him, he grabbed the handle and pushed it open, revealing a small, cramped janitor’s closet. He hurled himself inside and slammed the door behind him. Digging his heels into the floor, he pressed his back against the door as the naked Russians beat and kicked against the outside.
</p>
<p>
“Guys…” he said, gulping. “I might have made a slight miscalculation…”
</p>
<p>
Moshen answered him. “Danny! I see you on camera! Sit tight!” There was the sound of metallic clattering.
</p>
<p>
“I’ve got nowhere to go, Moshen,” Danny said. His muscles were beginning to give out. “Hey, Tina? Can you put us in a private channel? Just you and me?”
</p>
<p>
“Yeah…,” she said. Background static disappeared.
</p>
<p>
“Listen… It really doesn’t look good for me here…”
</p>
<p>
“Danny, come on! You’ll think of a way out of this!”
</p>
<p>
His boots slipped along the floor as the strength in his legs faltered. “Look… I know you and I met literally yesterday… But I just… I want you to know…”
</p>
<p>
He was interrupted by a loud wailing from the hallway outside. A young male voice screamed, “<em>Kyuuuuuaaaaaaaaah!</em>”
</p>
<p>
A series of hard impacts, of grunts and smacks, of kicks in stomachs and fists in faces followed. Hands and heads crashed against the walls beside the closet door. It lasted for barely half a minute, and came to an abrupt stop.
</p>
<p>
Danny stood back, letting the door swing open.
</p>
<p>
Moshen stood in the bright hallway, both hands clutching long, sturdy metal rods that Danny recognized as mounting brackets from the back of the Claymore Communications van. He looked unhurt. At his feet, the three towel-clad men lay unconscious and bleeding. “Come on, Danny,” he said. “Grab your zappy-gun, and let’s go see what happened to Sergey.”
</p>
<p>
“Moshen?” Danny gasped. “How… How did you… How did <em>you</em>…?”
</p>
<p>
Moshen shrugged. “I told you when we first met, Danny: I know kung fu.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">The penthouse antechamber was silent</span>. The gilded walls were pocked and dented with bullet holes. Spent bullet casings glinted yellow on the red carpet. A gentle breeze flowed in through the shattered windows. The large cedar doors hung slightly ajar.
</p>
<p>
Approaching the suite, Danny heard soft groaning, coughing, rattling breath. He used his HERF gun to prod the door open. The motion wasn’t met with gunfire.
</p>
<p>
Inside, casualties littered the room, slumped over furniture and crumpled on the floor. Most of the mercenaries weren’t dead &mdash; at least, not yet. They twitched and coughed and pressed their hands against their wounds. The women seemed to have mostly avoided the gunfire. One stood alone in a corner with her arms crossed, glaring contemptuously at Ivan’s men as they lay dying. Another held a mercenary in her arms as he struggled to breathe through a sucking chest wound.
</p>
<p>
Danny squared his shoulders and entered. Gunpowder and blood, both stenches acrid and metallic, tangled in the air. He and Moshen proceeded cautiously toward the wide, elegant spiral stairs. Ivan’s mercenaries and concubines tracked them silently with their eyes. The pair slowly ascended.
</p>
<p>
The stairs opened out to a wide carpeted floor, with a conference room on one side and a hallway of bedrooms on the other. The glass walls of the conference room were shattered. Bodies lay sprawled across a bullet-chipped table.
</p>
<p>
From the bedrooms came a child’s sobbing.
</p>
<p>
The sound led Danny to an open doorway. The door itself lay flat on the floor, torn chunks of wood hanging from its hinges. Inside, Sergey knelt beside a bed. His helmet and shield lay on the floor nearby. In his arms, he cradled a twelve-year-old girl.
</p>
<p>
Quizzically, she watched Danny enter the bedroom.
</p>
<p>
Sergey noticed her staring at the doorway, and instantly swung his MAC-10.
</p>
<p>
Danny dove. “Sergey, it’s <em>me</em>!”
</p>
<p>
Sergey’s eyebrows curled. “Daniel?” His face was expressionless, but tears streaked the sides of his nose. Speechless, he walked towards Danny, then grabbed him with both arms and pulled him in for a nearly-ribcage-crushing bear hug. “Rosie, this is Daniel,” he said when he finally released him. “He is a good man.”
</p>
<p>
Danny waved to the young girl, but met Sergey’s eyes with a look of deep concern. “Sergey, listen… There are cops in the building. They arrested Leo. They’ll be all over the place soon.”
</p>
<p>
Sergey’s expression darkened. “Where is Eugene? He is downstairs, yes?”
</p>
<p>
“I didn’t see him,” Danny said. “He’s not responding on his Bluetooth.”
</p>
<p>
Leading Rosie by the hand, Sergey pushed Danny aside and hurried out the doorway. “Come on, we have to find him!”
</p>
<p>
When Danny caught up, Sergey was crouching at the top of the stairs, his MAC-10 in one meaty paw, Rosie’s small hand in the other. He scanned the suite from his high vantage point. Suddenly, in a tone of horror, he screamed, “<em>Zhenya!</em>” and ran down the staircase.
</p>
<p>
Danny and Moshen exchanged puzzled glances. While Moshen stood upstairs with Rosie, Danny followed Sergey downward.
</p>
<p>
Sergey was in the sunken living room, kneeling over a body. The coffee table was smashed. The couches were torn apart. The huge television was destroyed, its cracked green circuitboards peeking out from behind the shattered screen.
</p>
<p>
Eugene was lying face-down on the floor beside the broken coffee table.
</p>
<p>
“No, no…,” Sergey gasped, and felt for his nephew’s pulse.
</p>
<p>
As Danny approached, he saw a deep dent in Eugene’s helmet. He had apparently taken a bullet to the head. The helmet had kept it from killing him, but the impact must’ve felt like a baseball bat to the skull. His hands and feet were twitching. As Danny drew nearer, he could see that Eugene was still breathing.
</p>
<p>
In fact, he was breathing quite rapidly. Too rapidly.
</p>
<p>
And then, a new smell hit Danny’s nostrils: a bitter medicinal smell, with pungent hints of acetone. The odor hung thickly in the sunken living room, growing stronger as Danny came closer. Only recently had Danny come to know that smell: cocaine.
</p>
<p>
Sergey gently turned Eugene’s head. Eugene’s cheeks and nose were encrusted with white powder. A thick heap of it lay just beneath his face. Less than a foot away, a crystal bowl lay shattered.
</p>
<p>
Eugene had fallen face-down into the pile. Unconscious and helpless, he had lain there inhaling the stimulant.
</p>
<p>
Sergey pulled the dented helmet away and pried open Eugene’s eyes. The pupils were so wide that the iris was invisible. His face was pale and damp with sweat.
</p>
<p>
Sergey propped him to his feet. Violent spasms shook his limbs. He balanced for a moment, then clutched his stomach, collapsed to his hands and knees, and began dry-heaving.
</p>
<p>
A thin, scared voice came from the stairs. “<em>Zhenya…?</em>” Rosie ran toward the living room.
</p>
<p>
Sergey grabbed her and held a hand over her eyes. “Get her out of here!” he commanded Danny. “Don’t let her see this!”
</p>
<p>
Eugene slowly climbed back onto his unsteady feet. He began vigorously brushing his arms, as though they were crawling with invisible insects.
</p>
<p>
Danny looked at Moshen. “The cops have a medical team on the way. If we can get Eugene to them…” 
</p>
<p>
Moshen gingerly put a hand on Eugene’s back. Eugene jumped and began throwing wild punches. Moshen leaned away, then gently coaxed him to follow. He moved in jerky, halting steps, babbling rapidly. The two headed toward the stairwell.
</p>
<p>
Danny approached Sergey, still holding his daughter. “We need to haul our asses to the yacht. The Claymore van is no good to us anymore &mdash; Medina’s camera system will flag it the moment it hits the streets. But we can still make it to the boat.”
</p>
<p>
Slowly, Sergey turned toward him, his face was almost crimson with fury, his eyes streaming fresh tears. He stepped away from Rosie, looked around the room, and roared something in Russian. All around him, the survivors of his rampage watched him with scared, silent faces. Sergey spun in place, meeting each of their eyes, repeating the same Russian question in steadily angrier tones. “One of you must know!”
</p>
<p>
“Know what?” Danny asked.
</p>
<p>
“Ivan! He is here somewhere! I saw him slink away like a rat! He is here, and by God I swear he will pay, once and for all!” He bowed his head, and said quietly, “Help me, Daniel. Help me to stop this man.”
</p>
<p>
“Which way did you see him go?” Danny asked.
</p>
<p>
Sergey pointed with his gun toward the antechamber.
</p>
<p>
Danny stood and pondered. “Well, he couldn’t have gone far. We control the elevator, so he must’ve taken the stairs. My team’s been watching the video feeds, and they haven’t seen him step out onto any of the floors below. The only other place where the stairs go, is <em>up</em>. To the…”
</p>
<p>
He was interrupted by a noise from outside: a distant, rapid thumping.
</p>
<p>
Sergey darted through the balcony doors and looked toward the sound. In the southwestern sky, high above the waters of Lake Washington, a dot of light drifted gently toward the Medina Gallante. A helicopter.
</p>
<p>
It was close enough for Sergey to make out its shape. It was not a SWAT helicopter, nor a news chopper, nor a medevac. It was tiny, barely larger than a car &mdash; suited solely for transporting a single high-paying chartered passenger for a trip to Sea-Tac Airport.
</p>
<p>
“<em>Son of a bitch!</em>” Sergey screamed.
</p>
<p>
He took aim with the MAC-10 and opened fire at the distant chopper, sending the sharp crack of automatic gunfire echoing out over the lake and the evergreen treetops. He kept pulling the trigger repeatedly after his bullets ran out, as though the strength of his hand could squeeze one more round out of the gun. With a grunt of mindless frustration, he hurled the gun at the helicopter, sending it arcing over the edge of the balcony and rustling the branches of the pines below.
</p>
<p>
There was a bang from overhead. A crater-like chip suddenly appeared in the balcony floor beneath Sergey’s feet.
</p>
<p>
He looked up. The roof, three stories above, was ringed with an ornate stone balustrade. Peering over that balustrade was Ivan Zheleznov.
</p>
<p>
Sergey ran to the wall and grabbed the long black nylon rope that Eugene had used to rappel from the roof. With a heaving grunt, he grabbed the rope with both immense hands, propped his booted feet up against the wall, and slowly began scaling.
</p>
<p>
Before he could ascend more than a few feet, a bullet slammed into his shoulder, mere inches from his unprotected head. The force knocked him back down to the balcony floor.
</p>
<p>
Sergey rolled quickly onto his stomach and crawled through the balcony doors back into the suite. The thrumming of the helicopter drew closer.
</p>
<p>
He tried to stand, but his legs gave out from under him. He fell to his knees and groaned, breathing heavily, clutching his chest.
</p>
<p>
“Sergey!” Danny tried to help him to his feet. The ox-like man was astonishingly heavy.
</p>
<p>
Sergey’s eyes looked glossy and unfocused. He shook his head vigorously and let out a few forced, dry, rumbling coughs.
</p>
<p>
“Jesus Christ, are you alright?” Danny asked softly.
</p>
<p>
Rosie came running toward her father. “He needs his pills!”
</p>
<p>
Sergey’s hand moved from his pants pocket to his mouth. His lips moved as he worked up enough saliva to swallow.
</p>
<p>
Outside, the tone of the chopper’s blades changed. It began a descent.
</p>
<p>
Sergey looked somberly back and forth between Danny and Rosie. He hugged his daughter tightly. “Rosie, stay with Daniel. Listen to what he says. He will protect you.” He turned his head, and his eyes met Danny’s. “Daniel. Take care of my daughter.”
</p>
<p>
And with those words, he bounded through the suite, out the cedarwood doors, and across the antechamber to the stairwell.
</p>
<p>
Danny and Rosie looked at one another awkwardly. Danny gulped. The two of them stood in tense, uncomfortable silence.
</p>
<p>
A voice chattered on Danny’s headset. “Danny! Are you there?”
</p>
<p>
“Moshen!” Danny asked. “Did you get Eugene to the cops?”
</p>
<p>
Moshen answered, “Yes, but… Danny, you’d better listen to this…”
</p>
<p>
In the background, Danny could hear shouting. “…You sent me a <em>squad car</em>!?” Danny recognized the voice of a detective he had dodged in the stairwell. “Santello and I found all the security guards &mdash; <em>all</em> of them, do you understand me? &mdash; <em>bound and gagged</em>, and you send me a goddamned <em>squad car</em>? There’s machine gun fire from the upper levels, there’s a fallen body on the ground, all phone lines are compromised… Captain, do you think this is fucking Disneyland? We’re in the middle of some kind of military operation! We need SWAT out here! We need choppers, we need snipers, we need Coast Guard! We need the wrath of God coming down on this place, and we need it <em>right fucking now!</em>”
</p>
<p>
Danny’s throat went dry. “Moshen… Come up here. Grab Rosie. Take her down to the dock. And get out of here like a bat out of Hell.” Danny turned to the girl, knelt down, and placed his hands on her shoulders. “Rosie, stay right here. My friends will get you out of here safely.” Into the headset, he said, “Jason. The whole lake is going to be swarming with Coastie boats in a matter of minutes. Get under way the second Moshen and Rosie are aboard. Set course for the Kirkland Marina. It’s only a few miles away. Sergey and I will get there on foot.”
</p>
<p>
On the deck outside, brass shell casings clinked in the downdraft of the rotor blades.
</p>
<p>
Tina said, “Danny… What’s your plan?”
</p>
<p>
Danny hoisted his HERF gun over his shoulder, turned toward the doorway, and answered, “I don’t have one.”
</p>
</div>
