<div class="chapsection">
<p>
<span class="caplead">With the watchful eyes of his team</span> and a few well-timed HERF pulses, Danny managed to stay out of sight of the throngs of police combing the Gallante. After two or three harrowing close calls, Danny was able to slip out of the building unnoticed. 
</p>
<p>
The battery in his cellphone gave out shortly after he left the hotel. In silence and moonlit darkness, Danny cut through the evergreen-fringed backyards of Medina billionaires. He carefully looked out for security cameras and motion-detecting floodlights, avoiding them where possible and zapping them where not. After slow, tentative progress across private property, he felt he had put a comfortable distance between himself and the hotel. He climbed over a retaining wall and arrived at a major road running through downtown Bellevue. The road was well-lit with streetlamps and bordered by a generous sidewalk. 
</p>
<p>
There, he pulled off the mud-crusted, blood-stained overalls, leaving himself in a t-shirt and jeans. He stuffed the overalls down a gutter grate. 
</p>
<p>
Then he figured out which direction along the road led toward the Kirkland Marina, slung his HERF gun back over his shoulder, and began walking.
</p>
<p>
And he walked.
</p>
<p>
And walked.
</p>
<p>
He had no idea how much time had passed. He wore no watch, and his dead cellphone wouldn’t tell him the hour. Cars zoomed by in both directions along the suburban road, paying him no mind. He walked past gas stations, past strip malls, past houses and apartment buildings, past busy highway overpasses and ghostly-quiet four-way intersections whose stoplight signals changed color for nobody. 
</p>
<p>
Danny heard the hum of an engine approaching from behind. He ignored it at first, as he had with the dozens of other cars that had driven past him. But when he heard the engine slowing down, he turned around.
</p>
<p>
Tina waved at him through the windows of Natalie’s borrowed car. Her eyes filled with happiness and relief.
</p>
<p>
“Danny!” she said as she pulled up beside him. “You’re going the wrong way!”
</p>
<p>
Danny climbed into the passenger seat. “My cellphone’s dead,” he said with a self-deprecating smile. He was elated to see her. “I have no GPS.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">In the cabin of Jason’s yacht,</span> Rosie and Moshen sat next to one another on the wide leather bench by the highly lacquered table. They had cleared out a space among the laptops and electronics, and filled it with markers and pencils and blank pieces of paper from Jason’s <em>Dungeons &amp; Dragons</em> kit. Moshen kept the girl distracted by flipping through the illustrated rulebooks and teaching her how to draw pictures of dragons, orcs, and fairies, of knights and priests and wizards.
</p>
<p>
The table was littered with loose pages of such images. Rosie’s pictures were stylized and cartoonish, but showed a distinct eye for movement and action. They all portrayed fierce, violent combat. Each of her scenes featured a mighty, barrel-chested knight. In one, he was single-handedly slaying an army of orcs. In another, he was rescuing a princess trapped in a tower. In a third, he was hanging from the claw of a soaring dragon. The knight wore dark armor and carried a large rectangular shield.
</p>
<p>
On the screen behind them, the conference call had stayed active. Mike and Natalie remained telepresent. 
</p>
<p>
All eyes turned towards the cabin stairs as Danny, Tina, and Jason descended from the deck.
</p>
<p>
Rosie, seeing them climbing down the steps, erupted in a joyous, expectant smile. Once the three of them descended, her smile lingered briefly, then sank into a perplexed frown.
</p>
<p>
“Where’s my Dad?” she asked nervously.
</p>
<p>
Danny’s face went pale. 
</p>
<p>
She stared into his eyes. “Where’s my Dad!?” she repeated with fierce insistence.
</p>
<p>
Silent seconds drifted by. The child’s face slowly melted into a grimace of agonized horror. “<em>Where’s my Dad?</em>” she screamed, knowing the answer.
</p>
<p>
Danny tried to say something, but only stammered. The young girl stifled tears with a wet gulp. She sprang from her seat, pushed past Danny, and bolted up the steps. Danny watched her helplessly, his mouth agape.
</p>
<p>
Jason clasped a hand on Danny’s shoulder and said, “I’ve raised children of my own,” before briskly ascending the steep cabin stairway after her.
</p>
<p>
Danny’s eyes, wide with heartbroken delirium, drifted to each of his comrades in turn. “You… You didn’t tell her…?” he asked them all.
</p>
<p>
The cabin responded with silence. On the deck above, the child’s hysterical sobs shattered the night.
</p>
<p>
“What’s going to happen to her,” Danny asked, his stomach lurching.
</p>
<p>
Several more moments of silence passed. Tina finally broke it. “She has no other family. We asked her while we were waiting for you. She has nowhere to go.”
</p>
<p>
“Sergey was adamant that she doesn’t end up in foster care,” said Danny, his head spinning. “You remember, right? In my bedroom? He said a girl her age would never…”
</p>
<p>
“I remember, Danny,” Tina replied.
</p>
<p>
“Sergey told her to listen to me. That I’d protect her,” Danny leaned heavily against the wood-paneled cabin wall. “He told me to take care of her. Those were his last words.”
</p>
<p>
Tina gently began, “Danny, you didn’t…”
</p>
<p>
He cut her off. “<em>Because of me,</em> those were his last words.”
</p>
<p>
Natalie intervened via the screen. “Danny, listen to me. It’s natural to feel guilty over something like this. Possibly even indebted. But, Danny, you couldn’t have known. What happened wasn’t your fault. Feelings of remorse are unnecessary right now.”
</p>
<p>
He listened to the child’s cries on the moonlit deck above. He replied to Natalie, “What <em>should</em> I be feeling right now, then?”
</p>
<p>
Natalie responded, “How about, proud of yourself for simply getting out alive?”
</p>
<p>
Danny emitted a hollow, humorless, sorrowful chuckle. “The things I choose to perceive as meriting pride are pretty arbitrary, don’t you think?” 
</p>
<p>
The sobbing outside began to soften. Jason’s voice could be heard offering soothing, indistinct words.
</p>
<p>
Danny looked at Tina and locked eyes with her. “Remember what we talked about back in the Rite Aid, Tina?”
</p>
<p>
Tina nodded. “Of course I do, Danny. You talked about how you believed you had an unclaimed destiny of greatness. How you’re supposed to create something amazing that would shape the whole world. Something like that, yes?”
</p>
<p>
Danny smiled warmly. “Exactly. But… my own greatness isn’t really <em>about</em> me, is it? It never has been. That’s the whole point…”
</p>
<p>
Small, light footsteps descended behind him. Rosie had broken away from Jason above. With tears still streaming down her cheeks and sobs still racking her shoulders, she ran to Danny and buried her face against his shirt. 
</p>
<p>
He instinctively reached out to hug her, and stroked her hair as her whimpers tapered to silence. “I <em>do</em> want to create something amazing,” he said as he wiped the child’s tears away on the cloth of his shirt. “I <em>do</em> want to shape the world. Maybe this is how.”
</p>

</div>
