<div class="chapsection">
<p>
<span class="caplead">Seattle’s downtown skyline glinted</span> in clear summer daylight. Tall buildings rose above the shoreline, their windows shimmering with reflections of surf and sky. They towered above parks where children and dogs played; above markets raucous with tourists and musicians; above sparkling blue waters teeming with yachts and freighters. The blue Olympic Mountains crowned the western horizon, the gray Cascades and the enormous sleeping volcano of Mount Rainier lined the east. Tucked amidst majesty of geological proportions, the man-made spires jutted upward from low-lying gray urban periphery like immense gemstones &mdash; the obsidian shard of the Columbia Center, the waterfall mesa of sandstone and sapphire at 1201 Third, the bizarre white alien stalagmite of the Space Needle. Seattle wasn’t merely adorned with jewels; she was made of them. She was the Emerald City.
</p>
<p>
“I just want to say, before we move on,” said the throaty, energetic voice of a young man freshly in his twenties, “that we both really appreciate this opportunity to present this work to you.”
</p>
<p>
On an upper floor of a soaring corporate tower, at the end of a long marble-floored lobby, there stood a pair of wide glass double doors. Frosted upon their surface were the words, “Tuttle Investment Partners.”
</p>
<p>
“We’re both techies, you know? I’m all about nanomaterials, and my partner’s a biomachinist. We’re science dudes, not money dudes. But when we talk to most venture capital people, they ask us about partnership strategies and market penetration projections. So it’s, like, great to see potential financial contributors showing a genuine interest in our engineering efforts.”
</p>
<p>
In the Tuttle office’s anteroom, beside the reception desk, stood a museum-like pedestal lined with red felt. Upon it, the ramshackle HERF gun prototype, built out of PVC and held together by Velcro and karabiners, sat inside a glass case, like some kind of curious historical relic from a bygone era. Which it was.
</p>
<p>
Video display monitors, barely thicker than paper, hung from the ceiling of the reception area. The monitors showed proud videos of Tuttle projects. One presented a focused young woman carefully measuring the electrical current flowing through an organic fractal assembly. One displayed an aging paraplegic playing the piano with a hand built of polymer and silicon. One had a Navy admiral demonstrating an aquatic robot darting through the water with a dolphin-like tail.
</p>
<p>
And another displayed a title screen announcing, “Tuttle Investment Partners is a proud sponsor of the Mukhayev Memorial Foundation.” Talking heads gave closed-captioned testimonials about overcoming drug addiction.
</p>
<p>
A woman’s voice spoke. It was an older voice, well-educated and self-assured. “It’s our pleasure to hear your ideas. We succeed financially by making informed investments, and that means understanding the science behind proposals to judge whether or not they sound promising.”
</p>
<p>
“And… Do…” The young voice stammered nervously. “Do you think we sound promising?”
</p>
<p>
The speaker stood in a small corporate conference room just beyond the reception hall. He was tall and charismatic, and brimmed with infectious excitement. His partner, a slightly older student with a heavy-set body and a shy demeanor, stood quietly at his side. Behind them, a large screen displayed a rotating protein structure with numerical readouts and a bulleted list of molecular properties. Words along the top of the diagram read, “Pluripotentiated Nanofacturing: A New Application For Cellular Multiplexing.”
</p>
<p>
The woman chuckled. “We’ll see.”
</p>
<p>
The woman was Tina. She sat at a small conference table, watching the presentation and taking notes. She wore a crisp, conservative business dress. The march of time had chiseled the contours of her face into a firm visage of competence and confidence, smart and strong and feminine. She radiated a kind of mature beauty only expressed in those who have rightfully earned it.
</p>
<p>
As the two young men fidgeted before their presentation, Tina turned to her side and said jokingly, “What do you think? Should we continue hearing these guys out, or are they a waste of our time?”
</p>
<p>
Daniel sat at the table beside her, wearing a timeless gray business suit. The color of his clothes matched the tone of his hair, which had receded high above his forehead to form a salt-and-pepper crown. The hair he had lost from the top of his head, he made up for with a neatly trimmed beard, dark and flecked with silver.
</p>
<p>
“Eh. I say cut them some slack,” he said, the creases at the corners of his mouth and eyes deepening as he smiled. “I remember giving a presentation to an investor group myself a long time ago, and it was a… stressful experience.” He gave her a wink. “Of course, back then, the term ‘cellular multiplexing’ meant something completely different.”
</p>
<p>
A device on Daniel’s wrist suddenly buzzed with a gentle vibration. Daniel glanced down at the screen. A pop-up window bore the words, “<span class="computer">Rosie: 6 unread messages (10 unread total).</span>”
</p>
<p>
One side of the pop-up was dominated by a cropped square image of Rosie’s face. She used her glamor shot for her profile picture, which meant that every time she messaged, he saw her pressing her fingers erotically against her glossy purple lips, looking sensuously upward with mascara-rimmed eyes below a mane of iridescent platinum hair. The image made him feel awfully awkward every time. He flicked the pop-up away.
</p>
<p>
“On a more serious note, I do have concerns,” Daniel said. “For starters, there’s heat buildup. You’ve got powered components placed microns apart. And your substrate is organic, which means it’s flammable. Tina, what do you think? Is there some cellular mechanism these kids could use to interweave some kind of metallic rodlike structures?”
</p>
<p>
Tina thought for a moment. “Would silica work? There’s a type of protozoan called ‘radiolaria’ that grow thin, spiny biosilicate skeletons. Maybe they could integrate part of its genome.”
</p>
<p>
Daniel nodded thoughtfully. “Silica might work. Could we infuse it with…?”
</p>
<p>
His device buzzed again. “<span class="computer">Rosie: 7 unread messages (11 unread total).</span>”
</p>
<p>
He looked up at the two young hopeful engineers. Their faces were anxious and self-conscious. “Gentlemen,” Daniel said apologetically. “I hate to be rude, but…” He turned away in his chair and focused on his device.
</p>
<p>
He maneuvered to the fresh pile of messages in his Inbox. The texts from Rosie weren’t at the top of his queue. Instead, he first had to flip through several messages that fell under a heading titled, “<span class="computer">HALF-CENTURY BIRTHDAY BLOWOUT!!11!one!</span>”
</p>
<p>
Beside each message, the device displayed familiar faces.
</p>
<p>
“<span class="computer">Dude! Your 50th birthday? We wouldn’t miss it for the world! Count us in 110%!</span>” announced one message, beside a picture of Mike and Natalie. They’d been married for almost a decade. Their youngest child had just entered pre-school. Natalie had her own clinical practice. Mike worked as a network administrator for REI’s corporate offices. In their free time, they made costumes and crafts for the Washington Midsummer Renaissance Faire. They were ridiculously happy.
</p>
<p>
“<span class="computer">Wow, 50!!!! I vaguely remember it. :) I’ve got venue, catering, and entertainment all lined up. It’ll be a gala! Get plenty of rest the night before. You’re going to need it, old man! Welcome to the other side of the hill!</span>” The message was from Jason, whom Daniel hadn’t seen much of lately. Jason’s health was faltering &mdash; no technology could stop the march of time, and his age was beginning to take its toll. Nonetheless, Jason’s spirits were quite high, and his friendship with Danny and the projects of Tuttle Investment Partners brought him fulfillment.
</p>
<p>
“<span class="computer">Daniel. It would be my pleasure to see you again, old friend,</span>” wrote Satish. “<span class="computer">My wife and daughters have not seen America yet, and it was very thoughtful of you to include them in the invitation. It’s a long flight from Mumbai, but we’ll make it happen.</span>”
</p>
<p>
“<span class="computer">Sure! See you there!</span>” Moshen replied. Moshen still made a decent living with his web design work. He was married now, and would soon probably have kids of his own. In his spare time, he penned a popular online comic. It was about kung fu.
</p>
<p>
Finally, Danny found the litany of texts from Rosie.
</p>
<p>
“<span class="computer">Dan my suit isn’t working. Can you fix it?</span>”
</p>
<p>
“<span class="computer">I'm supposed to be doing a dress rehearsal right now but my suit is broken!!! Biggest venue I've ever booked. Kinda starting to fraz here...</span>”
</p>
<p>
“<span class="computer">FUCK DAN I'M IN DEEP SHIT. The talent scouts from Epic and Columbia both watched me rehearsing and they're all like Where's your suit? And I'm like, It'll be working by showtime I PINKIE-SWEAR! DAN PLEASE PLEASE HELP!</span>”
</p>
<p>
“<span class="computer">It ons alright, but then it turds out this message "Segmentation Fault: NullPointerException in IOBuffer::integrateFrame" WTF?</span>”
</p>
<p>
“<span class="computer">Shit, I think I just made it worse...</span>”
</p>
<p>
“<span class="computer">DAN I CAN'T GO ON WITHOUT MY SUIT! WHERE ARE YOU?</span>”
</p>
<p>
“<span class="computer">Hello...?</span>”
</p>
<p>
Daniel sighed gently and put the device away. He looked back and forth at Tina and the young men. They were patiently waiting for him to finish.
</p>
<p>
“I’m so sorry,” he said. “I have to go.”
</p>
<p>
The charismatic young man said, crestfallen, “But our project…!”
</p>
<p>
He gave the two of them a warm smile. “Listen,” said Daniel as he stood up. “You kids have a lot of very, very hard work ahead of you. But Tuttle Investment Partners might be able to help you out. No promises yet. But we’ll talk more soon.”
</p>
<p>
Tina asked him, “Is everything alright?”
</p>
<p>
“Yeah,” he said. “Rosie’s just freaking out. Or ‘frazzing’ or whatever the hell the kids say today.” They exchanged a quick but warm kiss. “I’ll see you there, right?”
</p>
<p>
“Hell yeah,” Tina answered. “I already talked to the babysitter &mdash; she’ll pick the boys up from school, and we’re good ’til morning. But, Danny… Rosie’s show isn’t until eight o’clock. She wants you there right now?”
</p>
<p>
“Yeah,” Daniel replied, and headed for the door.
</p>
<p>
“What for?”
</p>
<p>
He answered over his shoulder, “Tech support.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Rosie greeted him completely naked</span> at the door to her backstage dressing room, with the arm of a very muscular young man draped around her sculpted waist.
</p>
<p>
“Dan! Thank fucking Jesus!” She turned around, pivoting in place with perfect poise. She briskly padded barefoot across the disheveled room, moving effortlessly with a dancer’s grace.
</p>
<p>
Her beefy boy-toy watched her with rapture in his eyes. Daniel knew that look. He’d seen it on every gentleman-caller Rosie had ever brought home. Whoever this fellow was, he was already hopelessly, agonizingly in love. After tonight, he’d probably never see her again.
</p>
<p>
“It’s over here!” she called from somewhere inside the cluttered chamber. Several young men and women puttered around, examining instruments and equipment. One lean geeky-looking guy sat in front of a clothing rack. Rosie looked down at him and shooed him with her hands, saying, “Ksssst! Scat!” The guy scurried out of his chair.
</p>
<p>
Daniel took a few awkward steps into the dressing room, avoiding looking in her direction. “Rosie, could you maybe put on a robe or something?”
</p>
<p>
Rosie flicked her hand manically at the clothes rack. “Just… just fix it! Please?”
</p>
<p>
The rack only held one garment: a one-piece jumpsuit custom-fitted to conform to Rosie’s flesh like a second skin. Like a scuba suit, it left only the head and hands exposed.
</p>
<p>
Unlike a scuba suit, it was completely transparent.
</p>
<p>
It was made from a material that felt to the touch like something between cellophane and polyester. A flexible column of gray opaque plates ran down the spine and across the shoulders. The plates bore jacks for data and power, as well as elaborate heatsink structures &mdash; heatsinks that would only work properly when in direct full-surface contact with naked flesh. At certain angles of light, the glint of microscopically thin metallic fibers could be seen weaving through the clear material.
</p>
<p>
Daniel pressed a power button on the spine. From neck to toe, the jumpsuit immediately turned solid black. Bars of color appeared down one thigh, indicating battery level, temperature, storage capacity, and CPU and memory utilization. Blocky gray text materialized line by line across the suit’s abdomen, distorted by the curvature of the display fabric.
</p>

<pre class="computer">
RedRaven BIOS v8.2.006
VESA Omnibulus HyperGL
Processor: Phobion LXZ-8881 512GHz 
Memory: 32T OK
INIT runlevel 4
Filesystem check........................[ OK ]
Starting system logger..................[ OK ]
Network initialization..................[ OK ]
Setting localhost.......................[ OK ]
</pre>

<p>
The waterfall of text suddenly spat out: “<span class="computer">Segmentation fault (core dumped)</span>”. The suit performed no further theatrics.
</p>
<p>
“See?” Rosie whined. She stood at a nearby closet, slipping into a bathrobe. “That’s all it does!”
</p>
<p>
Daniel raised a hand and motioned for her to calm down, and studied the reams of text on the suit’s surface. After about twenty seconds, he let out a slight chuckle. “Well, duh. Here’s your problem…”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Daniel got the suit working</span> about two hours before showtime. Rosie began pulling it on before Daniel could even complete a power cycle. “God! Thank you! You’re the best, Dan!”
</p>
<p>
“You know, Rosie, you’d be fine even without the suit,” Daniel said, facing away while she slipped into the transparent material. “You’re incredibly talented. Your performance will stand on its own merits.”
</p>
<p>
“You’d think so, wouldn’t you?” she said. “But the truth is, talent is cheap. All talent gets you is a job playing background music of an HBO miniseries. And in the meantime, there’s a thousand turdhole pop-groups that can’t hit two chords, that are booked solid for years.” She ran her hands up along her legs to squeeze out pockets of air. “Talent alone gets you nowhere. I mean, fuck, Dan. I’m almost 25. You know what the 27 Club is, right? Jimi Hendrix. Jim Morrison. Amy Winehouse. Kurt Cobain. Janis Choplin. Tricia Ferrel. A real performer is supposed to be dead at 27. I’m 24, and where am I? Everything I’ve done up to now has been coffee houses and indie festivals. If I don’t break out tonight, I’ll wind up playing bar mitzvahs and high school reunions until the day I die. Which will probably be 27 anyway, because I’d rather just shoot myself.” 
</p>
<p>
She rolled her shoulders to straighten the plates on her back. One of her lackeys zipped her up from behind.
</p>
<p>
“So I ask myself,” she continued, flexing her limbs inside the suit to smooth out any kinks and wrinkles, “what else can I do? What can I bring to the audience that nobody else in the world can give them?” She patted her sides. “This. I can give them this. Yeah, it’s just a gimmick, but fuck it. I’ll take any advantage I can get.”
</p>
<p>
The suit, now operational, responded to her movements with iridescent ripples that shimmered across her skin like waves upon an ocean of fluid energy. Flicks of her wrist and ankles sent ribbons of light spinning like whirlwinds upon her body. Shining upon her swaying form, swirls of ethereal color complemented her motions. She looked immaterial, transcendent, detached from physical reality; like a being that belonged to a different plane of existence &mdash; one purer, more celestial, more proximate to God.
</p>
<p>
She dismissed her pit crew and told her band to go prep the stage for soundcheck and last-minute rehearsal. At her command, they took their equipment and shuffled out the door. She and Daniel were alone.
</p>
<p>
At the sound of the door closing, her bossiness and bravado disappeared like an extinguished candle flame. Where once stood a brash diva, there remained only a frightened, watery-eyed little girl. “Dan…” she said with a quavering voice.
</p>
<p>
He stepped toward her and wrapped her protectively in his arms. “Shhh… It’s alright, Rosie,” he said as he gently kissed the top of her platinum-haired scalp. Her show-ready hair tasted like melted plastic. “It’s alright to be afraid. I would be too. You’re going to do great out there.”
</p>
<p>
“Thanks,” she said nervously. “Everybody’s telling me that. I’ll do my best.”
</p>
<p>
“I wasn’t saying it to be supportive,” Danny replied. “I was being sympathetic.”
</p>
<p>
She pulled a few inches away and looked up with her mascara-rimmed eyes to scrutinize his face for meaning. “I don’t follow…”
</p>
<p>
“Think about it,” he said. “If you do poorly out there, it won’t really affect anything. You’ll continue performing in obscurity, booking coffee shops and indie festivals. Your life will go on as is, and this becomes just some random night when nothing noteworthy happened, and the achievement of your dreams will forever be simply some hypothetical alternate reality.”
</p>
<p>
Her bright pink lips curled into a sly, defiant smirk. “But I <em>won’t</em> do bad. I’m going to blow them away!”
</p>
<p>
He smiled at her warmly. “Damn straight you will, Rosie! And that means everything changes. Everything. You’ll no longer be the girl struggling to make it. You’ll become the young woman that’s making it. The person you are now, ends tonight. And that’s pretty damn terrifying, isn’t it?”
</p>
<p>
She nodded briskly. With a choked voice that betrayed her efforts to look brave, she said, “So, what can I do about it?”
</p>
<p>
“What can you <em>do</em> about it?” Daniel repeated with a kind laugh. “<em>Embrace it!</em> Rosie, in a few short hours, that arena out there is going to be filled with adoring fans all dying to feel your magic. The world is waiting &mdash; craving, aching &mdash; to be shown what you’re made of. And if it consumes you in the process &mdash; if you’re burned away in the flame of your own ignition &mdash; then that’s how you know you’ve lived your destiny. Now get out there, and make it happen!”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Daniel sat beside Tina</span> in the VIP booth, above a chattering crowd of tattooed teenagers and twentysomethings slowly growing more inebriated. On the stage, Rosie’s bandmates stood tense and anxious.
</p>
<p>
Suddenly, the lights cut out, and the crowd began to howl and cheer. Delicate chords swelled from the lightless depths of the stage.
</p>
<p>
A glowing figure appeared, dancing through the darkness like an angel across the void of space. It looked not human, but something beyond humanity &mdash; an incarnation of ingenuity and sensuality, an embodiment of mind and spirit. She was a creature born of technology and biology, a unity between mankind’s origin and destination wrapped in song and motion. She was a being for whom the worlds of the natural and the designed, the human and the divine, had no boundaries. For her, the limitless reaches of imagination would be manifest in physical reality.
</p>
<p>
She floated on gossamer limbs toward the microphone, cheered on by an adoring throng of pink-haired girls and slim-hipped guys. Iridescent arms spread to embrace the spotlight. Breath drew sharply into lungs made of starstuff and nebulae. Her voice rang out, carrying her song to the audience, to the world. And from that night on, her music played.
</p>
</div>

<div class="theend">
The End
</div>