<div class="acksection">
<p>
There’s simply no way for me to comprehensively thank all the amazing people, each brilliant and talented in their own right, who helped me create the work you just read. I have no doubt that there are people who deserve to be on this page whom I have missed. But I’ll do what I can.
</p>
<p>
Christel Winkler initially suggested that I write a novel, assuring me that my knowledge was something that people might enjoy learning and that my voice was something they might enjoy hearing. This book exists because of that encouragement.
</p>
<p>
Kelly Marie Gardner and Eric Gardner kept this project alive with their invaluable advice, both on literary and technical matters. Becky Sibio and Taliesen Rose read my drafts chapter by chapter as they came off of my keyboard. Jenny Grace Makholm listened to my brainstorms and occasionally lubricated my Broca’s area with vodka to clear up writer’s blocks. Aaron Chusid and Johnny Geddes helped trim the wordcount and polish the final product, making the prose tight and compelling. All of you guys cheered me on and kept me enthusiastic to continue pursuing this mission no matter how much of a slog it got to be at times, and helped make the result of my labors the best it could be. You have my utmost gratitude.
</p>
<p>
Most of all, Marina Pogosyan deserves special mention for the sheer volume and quality of her contributions. In the time that she extended her help on this project, her dedication to it was almost as great as my own. She helped me rework sections that had been troubling me from the moment I wrote them. 
</p>
<p>
This project has taken years to complete, and I’m overjoyed to finally put it into your hands. I suppose, then, that my ultimate tribute of gratitude should go to <em>you</em>, dear reader, for buying this book and permitting some of my mind to enter into yours.
</p>
</div>