<div class="chapsection">
<p>
<span class="caplead">The applause reminded Danny</span> of this one time in an alternate universe. His band played before an adoring throng of pink-haired girls and slim-hipped guys. His electric guitar screamed in ecstasy beneath his motion-blurred fingers, gushing chords like liquid lightning into the air of the arena. The song finished, and he spread his arms to embrace the spotlight as the crowd below worshipped him with cries of adulation.
</p>
<p>
Unfortunately, that never actually happened.
</p>
<p>
<span class="think">It should be louder than this</span>, thought Danny. <span class="think">I gave a great performance. They should be whistling and howling and throwing their underwear at me.</span>
</p>
<p>
Danny looked around and decided it’s best if they didn’t.
</p>
<p>
The smattering of polite, professional applause came from two dozen 50-something men. In place of tattoos and piercings were hair plugs and dental veneers. What should have been a stadium glittering with cellphone flashes was instead a bland conference room awash in the sickly light of fluorescent bulbs. Half of the audience were wearing gray suits, like Danny. The rest were in khakis and polos, doubtlessly planning to get back to their sailboats or golf courses after the meeting.
</p>
<p>
One attendee actually <em>was</em> wearing a concert T-shirt under his suit jacket &mdash; a <em>Nine Inch Nails World Tour</em> XL tucked into pleated pants, spread over a belly that had apparently gone decades without being subjected to a sit-up. The thinning remnants of his salt-and-pepper hair were gelled upward into what would’ve been a fashionable fauxhawk on a man half his age.
</p>
<p>
There was no microphone in Danny’s hand, only a laser pointer. No spotlight, only a high-resolution projector. No hit rock song, only a PowerPoint presentation describing a 4G cellular multiplexing algorithm by Claymore Communications.
</p>
<p>
Danny’s boss, Brent Thurston, stepped deftly forward. “That’ll conclude the technical portion of this meeting. And folks, I just want to say before we move on, that Danny and I really appreciate this opportunity to present this work to you. It’s great to see Claymore’s financial contributors showing a genuine interest in the engineering efforts of the company.” 
</p>
<p>
“Oh, our pleasure!” said the man in the Nine Inch Nails T-shirt. “Danny’s presentation was amazing, but what’s even more exciting his technology. What you’ve shown here is an upcoming wireless revolution, and I’m proud to help it come to fruition!” Later that day, NIN Man would buy Claymore Communications with his personal funds, and the company would go public. Danny would cash in his stock options to buy a downtown penthouse, and spend the next several years building Claymore into the world’s premier data systems provider. He would be featured in <em>Time</em> magazine as the face of digital communication in the 21<sup>st</sup> century.
</p>
<p>
Only, that never actually happened, either.
</p>
<p>
Instead, the man in the Nine Inch Nails shirt said cheerfully, “We’re glad you set up this meeting for us! Your man Danny here really knows his stuff.”
</p>
<p>
Brent beamed. “Yes, Danny’s been a great asset to the company. He’s been Claymore’s lead engineer for… How long, Danny? Five years now?”
</p>
<p>
“Six,” Danny said.
</p>
<p>
“He ran the Naval Base Kitsap project last year,” Brent continued. “He’s personally responsible for the firmware designs you guys saw here tonight. And you should see him bust a move on <em>Dance Dance Revolution</em>!” The investors laughed on cue.
</p>
<p>
“Would it be possible,” NIN man asked, “for Danny’s slides to be available after we finish?”
</p>
<p>
Danny answered on his own behalf. “Sure thing. I can put this up on the Claymore website right now…” His hand moved inside his jacket toward his cellphone.
</p>
<p>
The room erupted in murmurs of protest and clearing of throats. The one-percenters exchanged nervous glances and inched forward in their seats. Danny stood frozen with his hand halfway to his chest pocket, as though he was caught drawing a gun. He blinked dumbly at Brent for help.
</p>
<p>
Brent returned Danny’s look with an embarrassed half-smile. “The company’s website is maybe not the best place for proprietary technical data, Danny.” To the investors, he said, “But we’ll be delighted to email this presentation to each of you as soon as we wrap up.”
</p>
<p>
“Please make sure I get a personal copy,” NIN man insisted. “You can reach me at Jason Tuttle at AOL dot com. That’s J, A, S...”
</p>
<p>
Brent quieted him down with a reassuring handwave. “You’ll get one, Jason. You’ll all get one. And I’ll send out Danny’s contact info for further technical questions.”
</p>
<p>
And just like that, Brent Thurston took the room. He launched his own set of PowerPoint slides, discussing things like potential partnership strategies and market penetration projections. Danny stood aside to let the big boys play.
</p>
<p>
In some alternate universe Danny would have gotten an MBA after finishing his master’s degree. He’d have moved to New York and quickly climbed the ladder at a multinational holding company, eventually starting a tech-heavy hedge fund. He’d date models, dine at fine restaurants, and light cigars with burning hundred-dollar bills. By night he’d don a cape and cowl and prowl the rooftops fighting crime.
</p>
<p>
In the real world, during his last trip to New York he’d dropped his cellphone onto a set of subway tracks. In reality, New York sucked.
</p>
<p>
Reality sucked.
</p>
<p>
“Reality sucks.”
</p>
<p>
<span class="think">Crap! I didn't say that out loud, did I?</span>
</p>
<p>
The words had escaped under his breath. All eyes turned to Danny. Brent’s jaw hung open.
</p>
<p>
“I… Sorry,” Danny said. “I was just… My mind was somewhere else.”
</p>
<p>
Brent stepped in diplomatically. “Danny’s been working hard to put this slideshow together for you guys. He stayed up late last night giving it a final polish. He could probably use some coffee. Right, Danny?”
</p>
<p>
Danny took the hint. As he fled the room, he heard Brent resume the presentation.
</p>
<p>
<span class="think">Reality sucks?</span>
</p>
<p>
<span class="think">No. I suck.</span>
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">The coffee pot in the company kitchen</span> held Danny in rapt attention. It glowed with a shade of red slightly deeper than the visible spectrum: infrared. Every object in the universe emitted black-body radiation based on its temperature. Danny mentally computed the hot coffee pot’s emission spectrum, a relatively easy task using Planck’s Law: the power per unit area <em>I</em> of frequency <em>v</em> from a body at temperature <em>T</em> was equal to <em>v</em> cubed times…
</p>
<p>
A vibration on his chest broke his trance. His cellphone signaled an incoming email. Judging by the time, Brent’s Q&amp;A had come to a close several minutes ago. The investors had probably cleared out by now and were already driving their Beamers and Lexi home.
</p>

<div class="computer email">
From: Jason Tuttle &lt;jason.tuttle@aol.com&gt;<br/>
CC: Dorothy Eigen &lt;eigend@corp.verizon.com&gt;<br/>
Subject: FW: RE: Claymore Communications intellectual property auction<br/>
(1 Attachment)
</div>

<p>
<span class="think">NIN Man?</span> thought Danny. <span class="think">The guy doesn’t waste any time…</span> He expanded the message. 
</p>

<div class="computer email">
Danny, could you answer Dorothy's question?<br/>
Jason<br/>
<br/>
---<br/>
From: Dorothy Eigen &lt;eigend@corp.verizon.com&gt;<br/>
To: Jason Tuttle &lt;jason.tuttle@aol.com&gt;<br/>
Subject: RE: Claymore Communications intellectual property auction<br/>
(1 Attachment)
<br/>
<br/>
Thanks for sending this, Jason. I'll study it tomorrow. One question, though. On slides 7 through 12, the diagrams show elliptical polarization, but they use different eccentricities. Is that intentional?<br/>
<br/>
Dorothy Eigen<br/>
Senior Feasibility Engineer<br/>
Department of Mergers &amp; Acquisitions<br/>
Verizon Communications
</div>

<p>
The email continued with a chain of forwards and replies by random corporate people. The attachment was the PowerPoint presentation that Danny had delivered less than half an hour ago.
</p>
<p>
“<span class="computer">Sure</span>,” Danny typed in reply. “<span class="computer">Put simply, the phase angle deltas are part of the encoding scheme. To solve the obvious physical reception problems, we’ve developed a polyradial antenna</span>…”
</p>
<p>
His fingers abruptly froze. A conundrum pestered him from the back of his mind, distracting him from NIN Man’s request. The email thread, after all, was about dynamic self-calibrating quadrature amplitude modulation protocols in the ISM-band domain. The conundrum, on the other hand, involved understanding social cues. The latter was a much more complicated matter than the former.
</p>
<p>
Danny deleted his reply-in-progress and replaced it with:
</p>

<div class="computer email">
To: Jason Tuttle &lt;jason.tuttle@aol.com&gt;<br/>
Subject: FW: RE: Claymore Communications intellectual property auction<br/>
<br/>
Wait, can you explain something to me please? You emailed my presentation to an engineer in Verizon's Mergers and Acquisitions department? I don't get it. You guys freaked out when I tried to post the presentation on the Claymore website because you didn't want it publicly available. But now you're forwarding it to technical experts at potential competitors? What am I missing?<br/>
</div>

<p>
A reply came quickly.
</p>

<div class="computer email">
From: Jason Tuttle &lt;jason.tuttle@aol.com&gt;<br/>
It's not your concern. Please answer Dorothy's question.<br/>
</div>

<p>
Danny cringed at being so unceremoniously relegated to the role of worker-gnome. He went back to Jason’s original email, hoping for clues. Bundled with the forward was a long heavily-indented list of prior emails. Danny began scrolling.
</p>

<div class="computer email">
From: Jason Tuttle &lt;jason.tuttle@aol.com&gt;<br/>
To: Dorothy Eigen &lt;eigend@corp.verizon.com&gt;<br/>
(1 Attachment)<br/>
<br/>
Dorothy,<br/>
Per your request, please find the attached presentation of Claymore's technologies. Included are schematics, flowcharts, and results of field trials. This should be sufficient for proving that our asking price is justified.<br/>
<br/>
---<br/>
To: Jason Tuttle &lt;jason.tuttle@aol.com&gt;<br/>
From: Dorothy Eigen &lt;eigend@corp.verizon.com&gt;<br/>
<br/>
Jason,<br/>
I got a green light from my director. Verizon will join the auction for the intellectual property after Claymore's dissolution. However, we'll need detailed technical data about Claymore's inventions so we know what we are bidding on. Given our mutual nondisclosure agreement, can you provide this material?<br/>
</div>

<p>
Danny stared at that email. There were more below it, with other Verizon personnel and Claymore investors. But Danny’s eyes kept reading that message over and over again, bouncing off the bottom of the screen back to the top like a program caught in an infinite loop.
</p>
<p>
Eventually, he fought through his bewilderment to write one simple question.
</p>

<div class="computer email">
To: Jason Tuttle &lt;jason.tuttle@aol.com&gt;<br/>
Subject: FW: RE: Claymore Communications intellectual property auction<br/>
<br/>
&gt; after Claymore's dissolution<br/>
Um. What?<br/>
</div>

<p>
Jason Tuttle’s answer appeared several minutes later. It came not as an email, but as a text message to Danny’s personal cellphone number.
</p>

<br/>
<div class="computer cyberchat">
  <div class="message messagein">
    Danny. This is Jason.
  </div>
  <div class="message messagein">
    You weren't supposed to see that.
  </div>
</div>
<br/>

<p>
Danny responded.
</p>

<br/>
<div class="computer cyberchat">
  <div class="message messageout">
    Yeah well. I did.
  </div>
  <div class="message messagein">
    I meant to just send you Verizon's last email.
  </div>
  <div class="message messagein">
    I didn't intend to forward the entire thread.
  </div>
  <div class="message messageout">
    I kind of got that.
  </div>
  <div class="message messagein">
    All of those communications are highly confidential. There could be serious legal and financial consequences from the divulgence of that material.
  </div>
  <div class="message messageout">
    Consequences for me? Or for you?
  </div>
  <div class="message messagein">
    Just delete the thread and pretend you didn't see it, alright?
  </div>
</div>
<br/>

<p>
For a second Danny thought about composing an explanation about why Gödel’s Incompleteness Theorem makes it technically impossible for any information-processing system, including a human mind, to operate under the premise of not having a piece of information that it does in fact have. But there was a much bigger issue to address.
</p>

<br/>
<div class="computer cyberchat">
  <div class="message messageout">
    So, um...
  </div>
  <div class="message messageout">
    "Auction?" "Dissolution?"
  </div>
  <div class="message messageout">
    What does all of this mean?
  </div>
</div>
<br/>

<p>
Even as he typed the question, he realized he was simply fighting his own denial. He knew exactly what it meant.
</p>

<br/>
<div class="computer cyberchat">
  <div class="message messagein">
    The investment board made a decision recently.
  </div>
  <div class="message messagein">
    Claymore has never turned a profit.
  </div>
</div>
<br/>

<p>
Danny swallowed hard.
</p>

<br/>
<div class="computer cyberchat">
  <div class="message messageout">
    I know.
  </div>
  <div class="message messageout">
    We've been focused on research and development.
  </div>
  <div class="message messagein">
    And that research is valuable. But you haven't managed to productize it.
  </div>
  <div class="message messageout">
    We need more time.
  </div>
  <div class="message messagein">
    You've had six years.
  </div>
  <div class="message messagein">
    You've been living off of our generosity.
  </div>
  <div class="message messagein">
    Who do you think provides the funds that your salary comes from? Benevolent gods from the ancient empire of Moneypotamia?
  </div>
  <div class="message messagein">
    We're investors, Danny. We need a RETURN on our investment. We can't wait indefinitely for some ship that never comes in. We have other projects with better potential ROI. It had to happen eventually.
  </div>
</div>
<br/>

<p>
Danny found himself wrestling with his phone’s autocorrect as his fingers trembled.
</p>

<br/>
<div class="computer cyberchat">
  <div class="message messageout">
    How long?
  </div>
  <div class="message messagein">
    One week.
  </div>
  <div class="message messagein">
    We've already pulled the plug. The operations account is frozen.
  </div>
  <div class="message messagein">
    Your next paycheck will be your last.
  </div>
  <div class="message messageout">
    That's it then.
  </div>
  <div class="message messagein">
    I'm afraid so.
  </div>
  <div class="message messageout">
    And what about all the work I've done in the past six years?
  </div>
  <div class="message messageout">
    Claymore has been MY LIFE, Jersey.
  </div>
  <div class="message messageout">
    Jason. Sorry. Autocorrect.
  </div>
  <div class="message messageout">
    I thought that this company would finally be the one that I could ride to the top. I poured everything I had into this. Doesn't any of it count for SOMETHING?
  </div>
  <div class="message messageout">
    My chip designs?
  </div>
  <div class="message messageout">
    My patents?
  </div>
  <div class="message messageout">
    My open-source driver patches?
  </div>
  <div class="message messagein">
    Sunken costs.
  </div>
</div>
<br/>

<p>
He stared at Jason’s answer. Fury and self-pity knotted together in his gut. The screen grew watery before his eyes.
</p>

<br/>
<div class="computer cyberchat">
  <div class="message messageout">
    You used me.
  </div>
  <div class="message messageout">
    You FUCKING USED ME.
  </div>
  <div class="message messagein">
    Danny, this really isn't personal.
  </div>
  <div class="message messagein">
    I know this must hurt. I really do. But it's just business.
  </div>
  <div class="message messageout">
    You had me put that presentation together just so you could lay everything I've ever done for you on the chopping block. Without that presentation, you wouldn't have been able to set up an auction for Claymore's inventions. MY inventions.
  </div>
  <div class="message messageout">
    You tricked me into being my own executioner.
  </div>
  <div class="message messageout">
    You made me render myself obsolete and useless.
  </div>
  <div class="message messageout">
    You and the rest of the investors.
  </div>
  <div class="message messageout">
    And Brent?
  </div>
  <div class="message messageout">
    Does Brent know? Does everybody know?
  </div>
</div>
<br/>

<p>
Jason’s reply was slow to come. 
</P>

<br/>
<div class="computer cyberchat">
  <div class="message messagein">
    No. Nobody's allowed to know outside the investment group. Certainly not the employees.
  </div>
  <div class="message messagein">
    Your knowing is highly problematic.
  </div>
  <div class="message messageout">
    Oh gosh. Too bad.
  </div>
  <div class="message messageout">
    So, if I was to update Claymore's website right this minute with this news...
  </div>
  <div class="message messagein">
    Jesus Christ Danny please don't do that.
  </div>
  <div class="message messageout">
    LOL what, you wouldn't like that? How about I just post it on Facebook, then?
  </div>
  <div class="message messagein">
    That's not funny.
  </div>
  <div class="message messagein">
    I could get in unbelievable trouble for letting this information slip.
  </div>
  <div class="message messagein">
    The other investors could sue me for the full value of the sale.
  </div>
</div>
<br/>

<p>
Danny let out a cold, bitter laugh.
</p>

<br/>
<div class="computer cyberchat">
  <div class="message messageout">
    Well I certainly wouldn't want THAT to happen, now would I?
  </div>
  <div class="message messageout">
    Especially not after you manipulated me into throwing away six years of my life.
  </div>
  <div class="message messagein">
    It's not throwing away! You got paid every month! You had the means to eat and pay rent. You give us your brain, we give you money. That's how it works.
  </div>
  <div class="message messageout">
    Fuck. You think this is about MONEY?
  </div>
  <div class="message messagein">
    Is it?
  </div>
  <div class="message messagein">
    Because if it is, I can be persuasive.
  </div>
  <div class="message messagein">
    I can make it profitable for you to just forget this entire conversation.
  </div>
  <div class="message messagein">
    You're obviously going to need some extra cash soon anyway, so it really would be in your best interest.
  </div>
  <div class="message messageout">
    Are you serious?
  </div>
  <div class="message messageout">
    Are you trying to BUY MY SILENCE?
  </div>
  <div class="message messageout">
    LOL! This is fucking great! I've never been bribed before!
  </div>
  <div class="message messagein">
    Please don't use that terminology.
  </div>
  <div class="message messagein">
    Do we have a deal?
  </div>
  <div class="message messageout">
    You're a fucking idiot.
  </div>
</div>
<br/>

<p>
Danny leaned against the wall and let himself sink slowly down until he sat on the floor, his head dangling limply between his knees. A silent minute passed. His cellphone vibrated again in his hand.
</p>

<br/>
<div class="computer cyberchat">
  <div class="message messagein">
    I know it's not about the money, Danny. I'm sorry for implying that that's all it was.
  </div>
  <div class="message messagein">
    Believe it or not, I've been in your shoes. I know firsthand that there are other things at stake. Deeper things.
  </div>
  <div class="message messagein">
    Dignity. Pride. A sense of accomplishment. Being valued.
  </div>
  <div class="message messagein">
    So here's what I'm thinking.
  </div>
  <div class="message messagein">
    Remember I said how all of us in the investment group each have other projects of our own?
  </div>
  <div class="message messagein">
    I personally have one very hot iron in the fire.
  </div>
  <div class="message messagein">
    It's high-priority for me, it's urgent, and it's EXTREMELY sensitive. I already have personnel selected, but none of my current picks is suitable for the role of lead engineer. The same role you've proven yourself in for the last six years. Now that I think about it, this unfortunate situation could potentially work out very well for both of us. I could really use a man of your talents.
  </div>
</div>
<br/>

<p>
Danny sat on the floor as the messages rolled in. He looked around the kitchen. The table, the coffee pot, the fridge, the OSHA notices, the community corkboard with postings from his coworkers looking for babysitters or carpool partners. In a week, it would all be gone.
</p>
<p>
It certainly wasn’t the first dot-com he’d seen die with a whimper. And, though it stabbed him through the heart to think of it, it probably wouldn’t be the last.
</p>

<br/>
<div class="computer cyberchat">
  <div class="message messageout">
    Are you offering me a job?
  </div>
  <div class="message messageout">
    You're yanking one job out from under me, and offering me another?
  </div>
  <div class="message messagein">
    Yes.
  </div>
  <div class="message messagein">
    Not so much a job in the sense of W-2s and dental benefits and all that. This is more of a one-off consulting project. With cash payment.
  </div>
  <div class="message messageout">
    Instead of a bribe? So basically you still want to shut me up with money, but this way I have to work for it.
  </div>
  <div class="message messagein">
    Basically.
  </div>
  <div class="message messageout">
    You know...
  </div>
  <div class="message messageout">
    I don't know why that should make me feel better.
  </div>
  <div class="message messageout">
    But it does.
  </div>
  <div class="message messageout">
    Give me details?
  </div>
  <div class="message messagein">
    I can't discuss it over phone or email.
  </div>
  <div class="message messagein">
    Do you know the Mercury club on Capitol Hill?
  </div>
  <div class="message messagein">
    Meet me in an hour. I'll tell you all about it.
  </div>
</div>
<br/>
</div>
