<div class="chapsection">
<p>
<span class="caplead">Krongor’s battleaxe split the orc’s skull</span> in half, spraying the cavern wall with black ichor as the creature fell lifeless at the barbarian’s feet. 
</p>
<p>
Several paces ahead, Zhan quickly chanted arcane syllables. With a hand that suddenly glowed white, the wizard grabbed a nearby orc. Arcs of lightning surged through its body as its vibrato screams echoed through the cavern. The air filled with the stench of ozone and burning hair. The monster fell, twitching but lifeless.
</p>
<p>
A veritable army of the beasts surrounded Krongor. The warrior’s axe cleaved through another orc’s torso. Yet no sooner had the foe fallen than one of its comrades advanced to fill its place.
</p>
<p>
Zhan pointed toward the barbarian and shouted another incantation &mdash; and in an instant, Krongor was engulfed in an inferno. All he could see was flame. The very air around him set alight, singeing his hair and blistering his skin.
</p>
<p>
And just as quickly as the fire had appeared, it vanished. The cavern was silent, save for the sizzling from the burnt remains of the orcs. Amidst a circle of ashen bodies, Krongor collapsed to his knees in agony. “You idiot!” he growled.
</p>
<p>
“I’m sorry!” cried Zhan. “They were all around you! It <em>did</em> kill them all, at least…”
</p>
<p>
Smoke still rose from the barbarian’s flesh. He gritted his teeth, keeping himself conscious solely through strength of will. “Stupid wizards! Just use your damn hocus-pocus to patch me up, will you?”
</p>
<p>
Zhan nodded apologetically. He sat beside Krongor in a meditative pose and began whispering prayers to Eir, Goddess of Healing. The deity’s love reached even down into these dark pits. As he prayed, Krongor’s wounds closed and vanished before his eyes.
</p>
<p>
There was some dispute over whether or not that actually happened.
</p>

<hr/>

<p>
“I don’t care what you think I said before!” insisted Satish, a short, stout Indian man. “He has no healing spells!”
</p>
<p>
Satish sat at the head of a lacquered table, on a leather bench that wrapped along the walls of a yacht’s wood-paneled cabin. Through round portholes, the water of Lake Washington glistened in the midday sun. The table held a disorganized pile of books, dice, and Cheetos. At the center, atop a plastic sheet with a hexagonal grid and dry-erase marker lines, stood two-inch painted pewter figurines &mdash; one axe-wielding barbarian, one wizard, and several orc figures lying face-down.
</p>
<p>
“This is bullshit!” Mike fired back, waving a handful of papers. He was dark-haired and tall, well-muscled but too fat and scruffy to show definition. “When we were in Salavina, I remember Zhan going to the Temple of Eir and learning a healing spell from the High Priestess.” He turned to his side. “Didn’t you?”
</p>
<p>
Jason Tuttle sat next to Mike, chugging a soda and adding up experience points on a worn character sheet. “She taught me a prayer for good health, Mike. She didn’t grant me the authority to channel the power of her god.”
</p>
<p>
“She did! She totally did! Ask Moshen!”
</p>
<p>
Moshen, a scrawny Asian kid with thick glasses, sat near Mike, his nose deep in a rulebook. “Leave me out of this, man,” he said without looking up. “I’m still back at the inn, getting drunk and hitting on wenches.”
</p>
<p>
Mike turned back to Jason. “You talked me into helping you fight through these orc-infested caverns, and you can’t even cast any healing spells!?”
</p>
<p>
“Mike, quit being such a munchkin!” Satish railed. “It doesn’t make any sense for wizards to heal! Wizards throw lightning bolts and fireballs. Priests manipulate life energies. They operate on completely incompatible principles.”
</p>
<p>
Jason shrugged. “Wizards can’t cast healing spells, dude. Everybody knows that.”
</p>
<p>
“Give me Zhan’s character sheet, Jason,” Mike demanded.
</p>
<p>
Jason put a hand over the paper. “Why…?”
</p>
<p>
Wielding an eraser with menace, Mike declared, “I’m going to change him into a barbarian.”
</p>
<p>
Jason’s face was a mask of horror. “Don’t even think about it!”
</p>
<p>
“Try and stop me!” Mike snatched at Zhan’s character sheet. Jason yanked it away and held it at arm’s length. Mike tried to reach around Jason, but he wouldn’t yield. The two grown men slapped at each other and wrestled on the cabin bench for control of the paper.
</p>
<p>
Their bickering was interrupted by footsteps above. Through the portholes they could see jeans and hiking boots. The visitor knelt down to peer inside. Danny’s face appeared in a porthole. Jason pointed to the entrance.
</p>
<p>
“Hey,” Danny said as he descended the steep stairs into the cabin. “Oh good, I got the right boat.”
</p>
<p>
Jason waved hello. “Come on in, Danny. Meet the gang.”
</p>
<p>
Danny looked around. On one end of the cabin was a large flatscreen TV. On the other end, he saw the table covered with rulebooks, figurines, and soda cans. He instantly recognized the scene. He’d walked into a <em>Dungeons & Dragons</em> campaign. 
</p>
<p>
“Aww Christ,” he muttered. He felt the revulsion and regret of a recovered heroin addict entering an opium den. Danny’s days of chasing these particular dragons were long behind him. “Jason, can I talk to you?”
</p>
<p>
Jason wiggled his way from the table and crossed the compartment. He and Danny turned away from the group and spoke in whispers.
</p>
<p>
“<em>This</em> is your hacker team?” asked Danny. “Where did you find these guys?”
</p>
<p>
“They’re my gaming group,” Jason said innocently. “We play every Thursday at the Wizards of the Coast store in Crossroads Mall.”
</p>
<p>
“You play <em>Dungeons & Dragons</em>? Aren’t you like sixty? Don’t you have a wife and kids and a life and stuff?”
</p>
<p>
Jason replied coldly, “My ex-wife is none of your business.”
</p>
<p>
“Sorry, didn’t mean to hit a sore spot. But, I mean, look at these guys. Do they have any skills? Do they even have real jobs?”
</p>
<p>
“They have my complete trust,” said Jason. “They’re smart and capable. You should see the kind of shit we pull off together. Just last month, we destroyed the stronghold of a Dark Elven necromancer.”
</p>
<p>
“Your <em>characters</em> did that. In your <em>head</em>. <em>You</em> sat around a table rolling dice and scarfing Cheetos.”
</p>
<p>
“Look, I know personnel management, alright?” Jason said. “What counts is whether you can work as a team. These guys are my comrades in arms. They’re in. Are you?”
</p>
<p>
Danny sighed, and turned to face the group. The men were poking through rulebooks or scribbling on papers. They looked up and mumbled greetings as he approached. “Guys. Good to meet you all. My name’s Danny. I’m the lead engineer at… um… Let’s just say I’ve overseen the demise of many small companies.”
</p>
<p>
He shook hands with each of them.
</p>
<p>
“Satish Srinivasan. I do whitebox testing and assembly optimization in Microsoft’s Xbox division.”
</p>
<p>
“Moshen Chen. Web designer and developer. ASP.NET, Ruby on Rails, HTML 5, Angular, Closure, I do it all. You want a kick-ass website, I’m your man.”
</p>
<p>
“Mike Braun. I work at the Safeway on Queen Anne.” Danny stopped in mid-handshake. “And I’m taking Cisco certification classes at Bellevue College. Network administration &mdash; router setup, mail servers, domain name registrars, packet monitoring, that kind of stuff.”
</p>
<p>
“And thinks wizards can cast <em>Cure Light Wounds</em>,” Satish interjected.
</p>
<p>
“Oh shut up already!” Mike insisted.
</p>
<p>
“Isn’t <em>Cure Light Wounds</em> a priest spell?” said Danny before he could stop himself.
</p>
<p>
“See!” said Satish, sticking his finger in Mike’s face.
</p>
<p>
“You play?” Jason asked Danny eagerly.
</p>
<p>
Danny shook his head. “Not since Second Edition.” That was a lie.
</p>
<p>
“You want to hop in?” offered Jason. “We have plenty of extra character sheets.”
</p>
<p>
Danny closed his eyes and sighed slowly. “Is there anything else I should know about you guys before we get started? Additional skills? Um… Attributes? Proficiencies? ”
</p>
<p>
“I play hockey!” Mike said proudly. “I can be your muscle if things get physical!”
</p>
<p>
“Yeah!” Moshen chimed in. “And I know kung fu!”
</p>
<p>
Danny eyed the men with a cocked eyebrow. “Hockey… and… kung fu…?” 
</p>
<p>
From the hexagonal grid on the table, he picked up the two-inch pewter barbarian. It was painted with loving detail. He chuckled and shook his head. “Guys, let me give you all a reality check. This is a network penetration mission. In an ideal world this’ll be done from some Internet café and take less than ten minutes. If they have a poorly maintained firewall that crumbles under a script-kiddie attack, this whole thing will be completely anticlimactic. Now clear off this table, gentlemen. Keep the pencils and notebooks. We’ve got work to do.” 
</p>
</div>
