<div class="chapsection">
<p>
<span class="caplead">The pincer arm slid along the BioTek Microplate Stacker’s</span> sleek white body, holding a clear rectangular plate. The plate’s surface was pitted with a grid of a hundred small round wells, each one filled with pale yellowish-brown fluid. The Stacker gently handed the plate off to a Synergy Microplate Reader, which drew it into a dark slot. Its payload deposited, the Stacker rose softly toward a vertical tower of identical plates, its pincers rotating to grab the next set of samples.
</p>
<p>
Tina Giordano batted a lock of her unkempt dark hair out of her eyes and focused on a computer terminal beside the Reader. Laboratory robots whirred softly around her as she studied the console. Centrifuges spun. Pipettes trickled thin streams of fluid. Gantries and belts carried plates among devices that heated the samples; cooled them; titrated them; aspirated them; sealed them beneath plastic film; and affixed them with printed labels. With their smooth plastic contours and modular mechanical assembies, the machines reminded Tina of mutant Xerox office printers.
</p>
<p>
On the far side of the laboratory, two white-coated figures, a man and a woman, stood beside a whiteboard. Both were older than Tina by at least two decades. Over the gentle humming and clicking of the machinery, she could hear them talking in somber, flustered tones.
</p>
<p>
“Passinsky is getting seriously pissed,” the man said.
</p>
<p>
“He never gets pissed. He never gets anything,” the woman replied.
</p>
<p>
“This is different. I think he’s honest-to-God scared.”
</p>
<p>
“Of what? Losing our funding?”
</p>
<p>
“I think so,” he said. “He told the Consortium that we’d have results by now. They’re coming to see for themselves.”
</p>
<p>
“Yeah. We were supposed to have results a month ago. It doesn’t make sense. The Reader logs reported expression of the full pathway in one batch several weeks back.”
</p>
<p>
“The Reader’s been spewing out a lot of false positives,” he said with a frown. “We’ve got over a week’s worth of backlog for manual testing.”
</p>
<p>
“Isn’t that what the intern’s for? Where is she, anyway?”
</p>
<p>
“You haven’t heard? Julie’s gone AWOL. Nobody’s seen her in days.”
</p>
<p>
“Well… shit,” the woman said with a sigh. “Just how high of an error rate are we dealing with here?”
</p>
<p>
“Too high,” the man replied. “Too damn high…”
</p>
<p>
They both turned to look at the machinery. The woman exclaimed, “Tina!?”
</p>
<p>
Tina jumped, and looked up apologetically from the console.
</p>
<p>
The woman stared at her with suspicion. “What are you doing at that workstation?”
</p>
<p>
Her accusatory tone almost made Tina back sheepishly away from the computer. But a final glance at the screen gave her reason to stand her ground. “Your reporter. You’re using gfp, right? Why wouldn’t you just use a selectable marker? CAT is standard for <em>E. coli</em>, isn’t it?”
</p>
<p>
The man mumbled, “The mother strain is already immune to chloramphenicol, Tina.”
</p>
<p>
Tina looked at the plastic plates being handled by the robotic arms. “I just… I have a question,” she said innocently. “If you’re using gfp as a reporter, then that means you’re testing these assays for fluorescence, right?”
</p>
<p>
The woman rolled her eyes. “Yes, Tina. That’s what <em>green fluorescence protein</em> means.”
</p>
<p>
“So this microplate reader… It shines a specific color of light on a plate of samples, and uses camera-type-things to check if each assay is, like, ‘reflecting’ some <em>different</em> color of light. Right?”
</p>
<p>
“That <em>is</em> how fluorescence reading works,” the woman replied sardonically.
</p>
<p>
“Thanks. So, then, can you explain to me…” She grabbed an empty plate off of one of the machines and waved it in front of her face, looking at the two scientists through the clear plastic. “…why the hell you guys would use <em>transparent microplates</em>?”
</p>
<p>
The man shrugged. “The clear ones are cheap. We had a huge supply of them down in the stockroom.”
</p>
<p>
“Are they cheap enough to make it worth redoing a whole month of automated runs? Because, if the plate is completely see-through, then light can shine from one well to another. Which means that, if one well is fluorescing really strongly, then the reader will pick up a little bit of light <em>in all of the wells next to it</em>, too.”
</p>
<p>
The man’s eyes widened. “Well-to-well crosstalk!”
</p>
<p>
“Exactly!” Tina nodded. “Which would lead to…”
</p>
<p>
The man facepalmed. “False positives. Tons and tons of false positives. Of course. We didn’t even think of something so basic…”
</p>
<p>
“Instead of reporting uptake in <em>one</em> sample,” said Tina, “the reader will report uptake in <em>nine</em> of them. So what you get is…”
</p>
<p>
The woman interrupted her, “What you get is way above your pay grade, Tina. You’re not even authorized to be in this lab.”
</p>
<p>
Tina’s jaw dropped. “Really?”
</p>
<p>
The man said, “Tina, this <em>is</em> a restricted area. We work with scheduled substances here, not to mention volatile chemicals and potentially dangerous microorganisms…”
</p>
<p>
Tina shot him a look. “I’m fully aware of what you work with here. I’m the one that mails out the OSHA forms, remember? And I know all your safety protocols because I’m the one that prints your memos…”
</p>
<p>
The woman sneered, “That’s great, but mailing forms and printing memos doesn’t make you a scientist.”
</p>
<p>
The man nodded. “You really should be back at the front desk.”
</p>
<p>
Tina’s gaze traveled from the two microbiologists, to the console, to the laboratory equipment, and finally to the floor. Biting her lip, she shuffled out of the room.
</p>
<p>
“Oh, and, Tina?” the man called out just as she reached the doorway. “Could you please put in a thousand-unit rush order for 96-well microplates in polystyrene carbon black? Thanks.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Tina’s desk occupied a brightly lit lobby</span> between two sets of glass doors, both frosted with a large letter “W”, the chemical symbol for the element tungsten. Her black cardigan hung draped over her armless swivel chair. Like a pithed laboratory animal, she dropped her body limply down onto the pneumatic-spring seat and got back to work.
</p>
<p>
Several new email messages greeted her in her Thunderbird inbox. Only one, however, was in the least bit significant: a rare note of validation from her boss involving the imminent babysitting of some hotshot international gazillionaire. 
</p>

<div class="computer email">
From: “Dr. Piotr Passinsky”<br/>
> > Christina, have you finalized arrangements for <br/>
> > visiting investor? Remember this man is head of the<br/>
> > consortium that funds this company. He will be coming<br/>
> > with many assistants. Spare no expense.<br/>
> <br/>
> I booked reservations with the Medina Gallante hotel,<br/>
> Dr. P. Forwarding you the confirmation email...<br/>
><br/>
> > From: “Medina Gallante Luxury Suites”<br/>
> > Thank you for choosing to stay at the Medina Gallante!<br/>
> > We are proud to offer our guests the finest upscale <br/>
> > accommodations in the Pacific Northwest.<br/>
> >   Party name: IVAN ZHELEZNOV<br/>
> >   Room assignment: PRESIDENTIAL SUITE<br/>
> > To make your travel experience as enjoyable as possible,<br/>
> > we offer the following enhanced transportation options<br/>
> > to and from our facilities.<br/>
> > * Helicopter chauffeur from Sea-Tac airport direct to<br/>
> >   our rooftop helipad<br/>
> > * Water taxi from any Lake Washington marina to our <br/>
> >   private pier<br/>
> > Please let us know if you wish to take advantage of these<br/>
> > amenities, or if there is any other way we can improve<br/>
> > your visit.<br/>
><br/>
> Will this do, Dr. P?<br/>
<br/>
Yes, Christina. This is very acceptable.<br/>
</div>

<p>
It wasn’t exactly an Employee of the Year award, but Tina knew it was the closest thing to praise that she was likely to get.
</p>
<p>
The rest of the emails were pure spam. Several solicitations from some web design company called Prismatic Creations cluttered her inbox, each with a big colorful logo plastered across the top of the message. They gave some spiel about updating Tungsten’s “corporate identity” to give the company a fresh look-and-feel to better resonate with today’s competitive blah blah blah. After reading one, she deleted them without a second thought.
</p>
<p>
With her inbox clear, she un-minimized her Facebook window. Her friend Natalie had posted some photos of a dreamcatcher that she’d woven from her own hair. Tina gave her scrollwheel a flick, and sank into a status-update-reading trance. Seconds or hours drifted mindlessly by.
</p>
<p>
When duty called again, it took the form of a FedEx man carrying a cardboard box the size of a suitcase. A small green light above the front door card-reader lit up as she buzzed him in. The package was from Newegg.com. It was addressed to Roger Tanner.
</p>
<p>
Tina cringed, and felt the taste of sour milk welling up in her throat.
</p>
<p>
She picked up her iPhone and willed her fingers to type out, “<span class="computer">Roger. Package for u. Come get.</span>” 
</p>
<p>
She spent the next several minutes staring at the box, trying to wish it away.
</p>
<p>
A raucous conversation from the hallway announced Roger’s arrival. Through the glass, she saw Roger’s tall, lean-muscled form striding toward the lobby, accompanied by two older men. Framed by his spiky hair and narrow black-framed glasses, his face wore its usual self-satisfied smirk. He opened the door with a long, sinewy arm adorned with Celtic sleeve tattoos, and sauntered in. 
</p>
<p>
“I didn’t say <em>a word</em>! That’s the whole point!” he said cheerfully.
</p>
<p>
“What, like, not even ‘Hi?’” asked one of the men. He sported a neatly-trimmed beard and a lab coat. “You just walked up to her out of the blue and, <em>bam!</em>, start making out?”
</p>
<p>
“It wasn’t out of the blue,” said Roger. “We’d been eyeing each other across the bonfire for like ten minutes. We both knew what was up.” His eyes landed on the package beside Tina’s desk. He pulled a jingling keychain out of his back pocket and squatted beside the box. “She was there at the beach with a bunch of her friends,” he continued as he carved the cardboard open with a key, “and we were all sitting around the fire. Alki Beach gets kinda cold at night, you know, and this little blonde was wearing, like, <em>nothing</em> &mdash; a bikini bottom and half of a white t-shirt, right? Anyway, some guy was playing Spanish guitar, and we were passing a joint around… I’m telling you, you guys have <em>got</em> to come out to Alki one of these nights.”
</p>
<p>
The other man, heavy-set and sloppily dressed, smiled. “We’re both married men, Roger. But it’s nice to see you kids having fun.”
</p>
<p>
With the box’s tape finally undone, Roger flipped open the top and reached inside with both hands. In a flurry of Styrofoam packing peanuts, he withdrew a dense black cube, slightly larger than a desktop computer and lined with slots, lights, and sockets. 
</p>
<p>
The man in the white coat asked, “Is that the big fancy hard drive you’ve been promising us?”
</p>
<p>
Roger nodded excitedly as he examined the equipment. “It’s a forty-terabyte RAID. Think this’ll be enough storage space for you lab monkeys?”
</p>
<p>
The trim-bearded biologist nodded. “How soon can you connect it to the network?” 
</p>
<p>
Roger stood up, cradling the device. “I’ll set up the NAS this afternoon. But whether any of your weird-ass mad scientist toys can talk to it or not… Well, that’s up to Don here.”
</p>
<p>
The heavy-set man saluted. “I’ll get my boys setting up NFS support on the robot controllers as soon as that thing’s ready.”
</p>
<p>
The biologist chuckled, “Forty terabytes. Try not to fill it up with pictures of your girlfriends, Roger, okay?”
</p>
<p>
“Oh! Speaking of…!” Roger set the RAID down on a corner of Tina’s desk, and pulled out his cellphone. He tapped its screen a few times and said, “This is the little hottie from the beach last night.”
</p>
<p>
The other two men gathered around the small screen. “She’s a knockout, alright,” said the technician. “What’s her name?”
</p>
<p>
“Oh, fuck if I know, man! Carrie? Kelly? Carley? Something like that.” He flipped through more photos.
</p>
<p>
“Check it out. She’s got that thing with her fingernails…” The tech wiggled his own nicotine-stained fingers. “What’s it called? Where just the tips are white? There’s a word for it…”
</p>
<p>
Tina’s gaze remained on her screen. While the men talked, she had shrunk progressively farther down in her chair, and now felt tiny enough to fit into a microplate well. “French manicure,” she murmured.
</p>
<p>
“Yeah, that’s it!” the tech said.
</p>
<p>
Roger glanced at her. His smirk waned slightly. “Hey, um, guys…” he said. “I’ll catch up with you later, ’kay?”
</p>
<p>
The two men said their goodbyes and left. Roger and Tina were alone.
</p>
<p>
“So…” he said, leaning awkwardly against her desk.
</p>
<p>
“Can I help you?” Tina asked flatly, her eyes glued to her computer.
</p>
<p>
“What’s got ya down, buddy?” His acerbic tone belied the friendly question.
</p>
<p>
Tina scowled. “‘Buddy,’” she echoed.
</p>
<p>
“Yeah, <em>buddy</em>,” Roger pressed. “You <em>said</em> you wanted to stay friends, right?”
</p>
<p>
Tina glared at him. “That doesn’t mean I want to listen to your stupid player conquests. I know you’re <em>real</em> proud of yourself, but you don’t have to rub it in my face.”
</p>
<p>
“Friends <em>do</em> talk about stuff like that, you know,” he said, feigning nonchalance.
</p>
<p>
Tina rolled her eyes. “Rog, you do realize it’s barely even been a week, right? Are you so inconsiderate that you can’t understand how your little pick-up tales affect me? Or do you just not care?”
</p>
<p>
Roger’s face puckered. “Not everything is about you, you know.”
</p>
<p>
“Everything? More like, <em>nothing</em> is about me!” Tina said, her voice rising. “You just kept chatting with your boy’s club over there as though I wasn’t right here the whole time. That’s how it always is with you. That’s how it was for the whole six months we were together. The only time you act like I even exist is when it’s convenient for you. Think about where I’m coming from for just one goddamned second, okay? I sit at this desk every single day, banging out endless emails, answering phones like a fucking parrot… ‘Good afternoon! Tungsten Medical Technologies! How may I help you? May I take a message?’ Ugh! I just feel so replaceable. So <em>insignificant</em>! And then you came along, and I thought we vibed, and maybe you could relate… But you end up treating me worse than anyone else here!”
</p>
<p>
Roger’s brow furrowed above his glasses. “Really, T? You’re going to use me as a dumping-ground for all your bullshit frustrations about work and life and whatever? You realize you have, like, <em>zero</em> credibility for being mad, right? <em>You</em> broke up with <em>me</em>, remember?”
</p>
<p>
“<em>I</em> broke up with <em>you</em>? <em>You</em> said you wanted to see other people!” Tina fired back. “As a matter of fact, it turned out you’d already <em>been</em> seeing other people!”
</p>
<p>
“I was just saying we should have an open relationship,” Roger said. “You’re the one that wasn’t down for it. So I really don’t see where you think you have the right to be upset.”
</p>
<p>
Tina gulped down bile. “You… ‘really don’t see…’?” she repeated incredulously. “Seriously, Rog? Even you can’t be that obtuse.”
</p>
<p>
Roger said slowly, punctuating with his hands, “I am not a mind-reader. So when I say that I have no idea where you get off being so pissed about a relationship that <em>you</em> ended, it’s <em>not</em> because I’m being ‘obtuse’. It’s because <em>you</em> aren’t making any sense. It’s because <em>you</em> are failing to <em>communicate</em>. And like you said, your <em>whole job</em> is to sit here and talk to people on the phone all day, so you’d think you’d know how to at least do <em>that</em>.”
</p>
<p>
Tina’s mind blanked with anger. She couldn’t begin to count the number of dimensions on which Roger’s comment hurt.
</p>
<p>
She grabbed her iPhone and flung it at his stupid asshole face. 
</p>
<p>
A lens of his glasses cracked on impact. She turned away from him, her arms crossed tightly over her chest. She could feel her jagged breaths pounding against her ribcage.“Roger,” she said, struggling to keep her voice steady through the lump in her throat, “take your box and get the fuck out of my lobby.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">The blinds on the windows to Dr. Passinsky’s office</span> were closed. Going to the boss’s office was never pleasant, and Roger’s presence made it that much worse. She knew he’d be there. In the email that Passinsky sent to summon her, she saw Roger’s email alias, “<span class="computer">rot13er</span>”, in the “<span class="computer">To:</span>” line alongside her own address.
</p>
<p>
Passinsky, gaunt and gray, looked at her with his unnerving expressionless gaze as she walked through the door. His pale, glassy blue eyes focused with detachment, as though the people in front of him were merely elements of some mildly interesting puzzle.
</p>
<p>
“You asked to see me, Doctor P.?”
</p>
<p>
Roger sat in one of two small, narrow chairs in front of Passinsky’s desk, still wearing the glasses with the crack down the lens. Tina closed the door behind her and took the other seat. The two of them avoided looking at each other.
</p>
<p>
Passinsky spoke with flat intonations, his English coming to him solely through practice and force of will. “I have to deal with personnel problems,” he said gruffly. “It take time away from research. Research is interesting. Personnel problems are not.”
</p>
<p>
Tina shrank in her seat, saying nothing.
</p>
<p>
“My biggest problem right now,” he continued, “is with Julie. Have you seen her come into office in a last few days?”
</p>
<p>
“No, I don’t think so. I don’t think she’s been here all week.”
</p>
<p>
“Roger, have you checked is she reading her email?” Passinsky asked.
</p>
<p>
Roger shook his head. “Her account’s had no recent activity, Dr. P.”
</p>
<p>
“Is she okay?” asked Tina. 
</p>
<p>
“I don’t know,” said Passinsky. “But it is very important for company to find her.”
</p>
<p>
Roger looked bored. “She’s an intern. How important can she be?”
</p>
<p>
“She was given very simple assignment,” said Passinsky. “Very tedious, but very critical. She ruined it. Now we need her to fix. Her timing is… very unfortunate. As Christina here can tell you, we have very important visitor coming. If this situation is not resolved, he will be very unhappy.” After a short pause, Passinsky added, “And this is not a man who you want to make unhappy.”
</p>
<p>
Tina offered, “Should I call Julie’s school and see if they’ve heard from her?”
</p>
<p>
“Yes,” said Passinsky. “And her family and friends. If you find her, tell her she must come to work tomorrow, and I take care of everything else. If you <em>don’t</em> find her, there is lots of paperwork for you to do.”
</p>
<p>
Tina looked down. “What kind of paperwork?”
</p>
<p>
“We have to end her employment,” said Passinsky. “That will mean filling out termination forms, filing payroll, writing notice to her university internship program. You will need to check what else.”
</p>
<p>
 “Alright. If I don’t hear from her by end-of-day, I’ll fill out those forms tomorrow.”
</p>
<p>
Passinsky shook his head. “No. I want them on my desk when I walk into office. I will need to sign them and send them out first thing in a morning.”
</p>
<p>
“Wait, what?” Tina said with a gulp. “But… I’ll have to stay late tonight to finish all that.”
</p>
<p>
Passinsky shrugged. “Either way, needs to be done.”
</p>
<p>
Tina turned her face away, taking a moment to quietly grumble to herself.
</p>
<p>
“I would do it myself,” Passinsky offered, “but I had to take time this afternoon to attend to another matter. Also is one I want to talk to the two of you about.”
</p>
<p>
Roger mumbled, “You mean you have us here for something besides the Julie thing?”
</p>
<p>
“I do,” said Passinsky. “Here is my issue. Neither of you is part of my research staff. So I do not expect you know these words: ‘vasopressin’ or ‘oxytocin’…”
</p>
<p>
Tina knew the terms. They were hormones. She recalled that they both had something to do with sex. She didn’t want to know where this was going.
</p>
<p>
“They are mammalian behavioral modulators for instincts of reproduction,” said Passinsky. “Oxytocin is most active in adult females. It is linked to delirium of being ‘in love’. It is released through erogenous stimulation of nipples and vaginal wall.” Hearing the old scientist use those words made Tina press her knees tighter together. “There are theories that oxytocin potentiation of dopaminergic reward pathway gives it addictive properties, and loss could trigger withdrawal symptoms.
</p>
<p>
“Vasopressin drives sexual territoriality. It is hormone responsible for feelings of jealousy. Vasopressin is subject of some ongoing research, because in humans it can act on very indirect triggers. Rats, for example, get angry by smell of another rat on their mate &mdash; this is easy to explain by pheromones. Humans, though, somehow have aggression responses wired to symbolic processing, such as sound of spoken words. This means that human being can hear someone say something, and exhibit immediate hormonal response. Observe…”
</p>
<p>
There was a computer monitor on his desk. He turned it around to face them.
</p>
<p>
The screen showed a choppy-moving overhead view of Tina and Roger arguing in the reception area earlier that day. Their fight had been captured by the lobby’s security camera.
</p>
<p>
Tina flushed. She knew the security camera was there. There were probably dozens of them in the building. She never thought anybody actually looked at the footage.
</p>
<p>
“Now, watch this part,” said Passinsky. “At this moment, Roger says something, and…” The Tina on the screen threw her iPhone at the digital Roger. “Right there! Instinctual aggression in response to comprehension of sound waves as words conveying ideas &mdash; a very non-instinctual stimulus! Fascinating, no?”
</p>
<p>
Tina leaned forward and began stammering an apology.
</p>
<p>
Roger squirmed. “What’s your point, Doctor P.?”
</p>
<p>
Passinsky replied with a sudden sharpness. “My <em>point</em>, is that I am running here a research company! Not a high school full of children who do not control their hormones!”
</p>
<p>
Tina shrank in her chair. Roger cringed.
</p>
<p>
“You know what I took this job for?” Passinsky grumbled. “To do science. You know what I do all day instead? Paperwork. All the time paperwork. Payroll, taxes, insurance, performance reviews, and nonstop American legal bullshit. Now I have to spend time covering company’s ass over stupid lover spat! Listen. I don’t know what you two have going on. I do not <em>want</em> to know. None of my business. But you bring it to my business, you <em>make</em> it my business. Understand?”
</p>
<p>
Tina and Roger looked at him sheepishly.
</p>
<p>
“So now, we have two ways to take this. We can treat this as science matter, or as paperwork matter. How do you want to handle?”
</p>
<p>
Tina gave him a tiny shrug and shook her head uncertainly.
</p>
<p>
“As paperwork matter,” he explained, “I tell you that violence has no place in work environment. Then you sign this statement…” He passed her a pen and a printed page. “…saying that I spoke with you to ensure it won’t happen again, and that your action was as private matter between you and Roger and having no involvement with company.”
</p>
<p>
Tina murmured, “Is my staying late tonight some kind of punishment?”
</p>
<p>
“I do not punish, young lady!” Passinsky fired back. “This is simple logical consequence. Forms for Julie need to be done. I could have done them this afternoon. Instead, I had to take care of this. Do I make myself clear?”
</p>
<p>
Tina sighed. “Yeah.”
</p>
<p>
Roger looked at the form in Tina’s hands with contempt. “And what if we want to handle this as a ‘science matter’?”
</p>
<p>
“Ah! As science matter, is completely different,” said Passinsky, suddenly upbeat. “As science matter, we use this as opportunity to do in-vivo study of modulating effects of oxytocin and vasopressin on axonal projections from Broca’s area to limbic system.”
</p>
<p>
“Which means…?” asked Roger.
</p>
<p>
“Which means we put Christina’s head into stabilizing vise, open top of her skull to put under high-resolution cameras, and inject voltage-sensitive dye. Then you stand nearby and say things to make her angry, and we record which neurons activate.”
</p>
<p>
He stared at them patiently.
</p>
<p>
Tina blinked. “You… want to saw my skull open?”
</p>
<p>
“Well, yes,” Passinsky replied. “How else to see electrofluorescent dye?”
</p>
<p>
“This is a joke, right?” she said.
</p>
<p>
“Y… yes. Is a joke. Of course. <em>Unless</em> if you agree…? In which case I will stay late myself, to prepare experimental apparatus. And maybe take care of Julie’s forms myself while I am here. If you understand my meaning.”
</p>
<p>
Shaking her head, Tina signed the statement and steeled herself for a late night.
</p>
<p>
“Ah! That is what you choose?” Passinsky said with disappointment. “Too bad. I like doing science. I don’t like doing paperwork.”
</p>
</div>
