<div class="chapsection">

<div class="computer cyberchat">

<div class="message messagein">
  <div class="speaker">witchdoctor82</div> 
  hey lady! Whatchya up to?
</div>  

<div class="message messageout">
  <div class="speaker">tinacious_g</div> 
  O HAI!
</div>

<div class="message messageout">
  IM IN MY LOBBY HATING MY LIFE
</div>

<div class="message messagein">
  why are u still at work? Its almost 10
</div>  

<div class="message messageout">
  Drippy gave me a bunch of shit tasks just to make my life suck.
</div>

<div class="message messagein">
  sorry t. you gonna be done soon?
</div>  

<div class="message messageout">
  No. Haven't really focused. I made a big mistake called icanhascheezburger. 
</div>
<div class="message messageout">
  And cuteoverload. 
</div>
<div class="message messageout">
  And stuffonmycat.
</div>

<div class="message messagein">
  haha did lolcats steal your brain?
</div>  

<div class="message messageout">
  Yeah. 
</div>
<div class="message messageout">
  I was like, I don't waaaaaaaant to print any more forms tonight. I know, I'll cheer myself up by looking at funny pictures on the internets. OMG KITTIES! 
</div>
<div class="message messageout">
  KITTIES KITTIES EVERYWHERE!
</div>
<div class="message messageout">
  Hours later... ZOMGZ MOAR KITTIES!
</div>

<div class="message messagein">
  did you know you get a dopamine rush just from looking at a picture of a smiling baby or a cute animal? There was a uk study about 2yrs ago that proved lolcats are actually a drug.
</div>  

<div class="message messageout">
  AW GEEZ NOT THIS SHIT AGAIN! 
</div>
<div class="message messageout">
  Drippy dragged me into his office this afternoon to lecture me about neurotransmitters. 
</div>
<div class="message messageout">
  He called me hormonal 
</div>
<div class="message messageout">
  and kindly offered to implant electrodes into my cerebral cortex.
</div>

<div class="message messagein">
  aww what a sweet man! 
</div>  

<div class="message messageout">
  It was really more about me behaving myself with Roger. Drippy disapproved of me giving Roger a close look at my iPhone at high velocity.
</div>

<div class="message messagein">
  hmm. t, you know u should never succumb to anger. Remember all energy u put out comes back to u threefold. Which is why ur stuck at work late tonight. 
</div>  
<div class="message messagein">
  but just between u and me... 
</div>
<div class="message messagein">
  nice!
</div>

<div class="message messageout">
  I'm pretty sure I'm stuck here late not because of Wiccan mysticism but because of the security cameras
</div>
<div class="message messageout">
  ohshit! Shitshitshit!
</div>
<div class="message messageout">
  I swear I just heard one move. 
</div>
<div class="message messageout">
  I think it's pointed at me. It's in a black glass dome on the ceiling but you can kinda see it when it turns.
</div>
<div class="message messageout">
  I think it's checking out my boobs.
</div>
<div class="message messageout">
  Am I losing it?
</div>

<div class="message messagein">
  yes. :)
</div>
<div class="message messagein">
  im serious about the Rule of Three, t. I know u dont believe in it, but I see it work all the time.
</div>
<div class="message messagein">
  for example. I have this one patient whos seeing me for ptsd. 
</div>
<div class="message messagein">
  his last doc had him on luvox, but it made him nauseous. So he switched to lexapro, which he didnt respond to. Then they tried klonopin, but he got suicidally depressed.
</div>
<div class="message messagein">
  so when they assigned him to me, you know what i gave him?
</div>
<div class="message messagein">
  mullein!
</div>

<div class="message messageout">
  Is that a new anti-anxiety med? 
</div>

<div class="message messagein">
  its a flower!
</div>
<div class="message messagein">
  little yellow fuzzy flower.
</div>
<div class="message messagein">
  i made him a bracelet out of them. :)
</div>

<div class="message messageout">
  Let me guess. It's a charm, right? 
</div>

<div class="message messagein">
  yes! for courage.
</div>
<div class="message messagein">
  i told him to wear the bracelet all day, and i taught him a spell to recite whenever he feels his anxiety coming back.
</div>

<div class="message messageout">
  You prescribed him a Wiccan ritual?
</div>
<div class="message messageout">
  Nat, are you actually allowed to do that? :P
</div>

<div class="message messagein">
  not really :)
</div>
<div class="message messagein">
  but it helped him a lot.
</div>

<div class="message messageout">
  "Dear Swedish Medical Center Ethics Committee. My treatment methodology involved a magical bracelet..."
</div>

<div class="message messagein">
  you think THATS the strangest thing theyve ever heard? :)
</div>
<div class="message messagein">
  anyway, the magick comes not from the bracelet, but from the mind of the wearer. the mullein is just a lens for the wearer to focus their own innate power for self-healing.
</div>
<div class="message messagein">
  think of the placebo effect. Its "imaginary" but the results are real.
</div>

<div class="message messageout">
  Better living through self-deception? :)
</div>

<div class="message messagein">
  or self-fulfilling prophecy. call it what you will.
</div>
<div class="message messagein">
  its taking something in your mind, that you imagine, and making your imagination manifest in the real world.
</div>
<div class="message messagein">
  and THAT, dear t, is magick. ;)
</div>

<div class="message messageout">
  Ok, speaking of things you imagine actually being real.
</div>
<div class="message messageout">
  That camera totally moved again.
</div>
<div class="message messageout">
  I swear I'm not seeing things!
</div>

<div class="message messagein">
  ok ok i believe u :)
</div>
<div class="message messagein">
  is it unusual? Maybe they adjust themselves at night or something.
</div>

<div class="message messageout">
  I... honestly don't know?
</div>
<div class="message messageout">
  I've worked late before but I've never really paid attention.
</div>

<div class="message messagein">
  and your paying attention to the camera now
</div>
<div class="message messagein">
  distracting yourself with some totally unimportant unrelated matter
</div>
<div class="message messagein">
  instead of dealing head-on with your real issues at work. 
</div>
<div class="message messagein">
  if you didnt hate it when i analyze you, I MIGHT call this a classic example of deflection... ;)
</div>

<div class="message messageout">
  You suck, Nat. :)
</div>
<div class="message messageout">
  So then, O Wizened Witch-Woman.
</div>
<div class="message messageout">
  What kind of magick can I use to improve this total shit-show I've got here?
</div>
<div class="message messageout">
  I mean, here's the potion for my life right now: take one part romantic failure, two parts professional failure, stir them in a crucible made of tungsten, and choke it down when it's cold and bitter.
</div>

<div class="message messagein">
  *hugs*
</div>
<div class="message messagein">
  sorry things suck for you so much right now, t
</div>

<div class="message messageout">
  Got a prescription for me, maybe?
</div>

<div class="message messagein">
  u already know what i think.
</div>
<div class="message messagein">
  hook up with one of the scientists to make roger jealous :P
</div>

<div class="message messageout">
  How about no more dating guys from the office? 
</div>
<div class="message messageout">
  They're all dipshits. Everybody here sucks. I get zero respect here. ZERO. 
</div>
<div class="message messageout">
  I try to talk shop with the lab monkeys sometimes, and they just humor me. Like, “Aww how cute! The Xerox girl is trying to use big words!”
</div>
<div class="message messageout">
  Fuck, they don't know me! They don't know that I know this shit. They don't know I was on track to be one of them back in college, before my dad got sick.
</div>
<div class="message messageout">
  They never even think to ask.
</div>
<div class="message messageout">
  And I don't know how I can convince them.
</div>
<div class="message messageout">
  It's like I'm under some sort of hex, and I don't know how to break it.
</div>
<div class="message messageout">
  Dammit Nat. Hold on. Now THIS is weird.
</div>

<div class="message messagein">
  ??
</div>

<div class="message messageout">
  brb
</div>
<div class="message messageout">
  Ok back.
</div>
<div class="message messageout">
  I'm NOT losing it. The cameras ARE fucked up.
</div>

<div class="message messagein">
  whats going on t?
</div>

<div class="message messageout">
  The camera was turning around back and forth going all crazy inside its little dome thingie.
</div>
<div class="message messageout">
  I drag my chair over and stand on it and smack the dome, and it stops.
</div>
<div class="message messageout">
  But I can see through the glass wall into the main hallway, there's a couple more cameras in the hallway, and one of them is just past the lobby doors, just a couple yards away. And while I'm standing on my chair, I can see that THAT one is doing it too.
</div>
<div class="message messageout">
  So I go into the hall and find another chair and drag it over and whack THAT camera too. BUT.
</div>
<div class="message messageout">
  While I'm dragging the chair over, I see that the camera at the OTHER end of the hall is ALSO going nuts.
</div>
<div class="message messageout">
  Nat.
</div>
<div class="message messageout">
  EVERY CAMERA IN THE BUILDING IS SPINNING AROUND.
</div>

<div class="message messagein">
  ok, that aint right.
</div>

<div class="message messageout">
  I KNOW RIGHT!?
</div>
<div class="message messageout">
  I don't know what's going on.
</div>
<div class="message messageout">
  It's kinda freaking me out.
</div>

<div class="message messagein">
  im sure its just a glitch. 
</div>

<div class="message messageout">
  All I know is, when I whack them, it seems to fix it.
</div>
<div class="message messageout">
  I better go around to the rest of the cameras and take care of it.
</div>
<div class="message messageout">
  Nat, I'll catch you later.
</div>

</div>
</div>