<div class="chapsection">
<p>
<span class="caplead">The locals called it “Pill Hill”.</span> Home to four sprawling hospitals and the state bloodbank, First Hill squeezed an entire city’s worth of medical care into a single square mile of steeply sloped one-way streets. Beneath jumbled overpasses, there sat crumbling condominiums and tiny turn-of-the-century houses, with bars on the windows and multiple deadbolts on the front doors. Within many of these homes resided the kinds of people who took comfort in living near a state-subsidized methadone dispensary or STD clinic.
</p>
<p>
A bullet-riddled Lincoln Navigator parked in an unenforced tow-away zone did not look out of place.
</p>
<p>
“Has the bleeding stopped?” Natalie Rosenbaum asked upon opening her door. She was slightly taller than Tina, but considerably more girthy. She wore a purple UW School of Medicine sweatshirt, drawstring pants, and the demeanor of a battlefield commander.
</p>
<p>
“Mostly,” said Tina. “We couldn’t keep his nose pinched because of the swelling.” Mike’s nose looked like a red bulbous prosthetic glued onto his face.
</p>
<p>
Tina led the men inside. Jason and Satish helped Mike walk in, with Moshen and Danny following. 
</p>
<p>
Natalie’s apartment was an unholy catastrophe. It was strewn with medical books and pizza cartons and candles, and smelled of cat litter and dirty socks. Notebooks and crusty paper plates littered her coffee table next to her MacBook Pro. Above her TV, on an unpainted wooden shelf nailed into the wall, sat an authentic human skull, between psychiatry textbooks on one side and racks of herbs and jewelry on the other. A small dead snake was stuffed and mounted crawling out of the skull’s right eye socket, its forked tongue sticking out inquisitively.
</p>
<p>
“Come here. Sit down,” Natalie ordered Mike. 
</p>
<p>
With an annoyed meow, a small furry gray blur scurried away as the crew of strangers entered the living room.
</p>
<p>
Natalie cleared off some space on her couch, sweeping aside a Pepsi bottle, a stuffed Grover doll, and a clump of twigs bundled in a knotted silk handkerchief. Mike sat down in a daze, the whole couch shifting under his weight. Natalie quickly took a look at the back of his head.
</p>
<p>
Back by the doorway, Moshen started sniffling and sneezing furiously. “Oh God damn it, you have a cat, don’t you?”
</p>
<p>
“There’s Benadryl in the bathroom,” Natalie said over her shoulder.
</p>
<p>
Moshen eyed the piles of laundry and beaded jewelry he’d have to cross to reach the bathroom. He didn’t dare peek inside the bathroom itself.
</p>
<p>
Jason suggested, “Why don’t you head back down to the car, Moshen? All your laptops and things are still in there.”
</p>
<p>
“And my HERF gun,” said Danny.
</p>
<p>
“Yeah, and his Nerf gun,” repeated Jason. “Go make sure someone doesn’t just reach through the busted windows and take them.”
</p>
<p>
“No way, man!” said Moshen. “This hood’s all gangbangers and drug dealers. I ain’t sitting out there by myself!”
</p>
<p>
“I thought you said you know kung fu,” Danny teased.
</p>
<p>
“Come on, dork,” said Satish condescendingly. “I’ll protect you.”
</p>
<p>
Jason tossed Satish the keys to the SUV, and the two men turned around and left the apartment. Moshen’s sneezes receded down the hallway outside.
</p>
<p>
Back at the couch, Natalie gave Mike a pair of Tylenol and a glass of water. “Here, swallow these if you can.” She lifted the glass up to his mouth. Mike managed to comply.
</p>
<p>
She sat next to him and examined his eyes, then dropped her hand down to his wrist and felt his pulse. His hands were much bigger than hers. “Has he been having seizures?” she asked Tina.
</p>
<p>
“No,” Tina replied. “But he threw up once.”
</p>
<p>
Holding his fingers, Natalie asked, “Have his hands and lips been shaking like this the whole time?”
</p>
<p>
“I… I don’t know. I didn’t notice,” replied Tina.
</p>
<p>
The doctor looked into Mike’s eyes, puffy above his swollen furry cheeks, and asked, “Do you feel cold?”
</p>
<p>
“No,” answered Mike in a stuffy nasal drawl. “I feel warm. And my face hurts.”
</p>
<p>
“Tina,” said Natalie. “You said on the phone that he was in some kind of fight, right? How bad was it? Emotionally, I mean. Is this just someone shoving him in line at a bar somewhere and it got out of hand, or was he fighting for his life?”
</p>
<p>
Tina said quietly, “It was… bad.”
</p>
<p>
Natalie said to the large man, “What’s your name? Do you know where you are?”
</p>
<p>
Mike replied, “My name is Krongor. I’m a Level 5 Barbarian Warrior. We’re in the Blade Coast city of Salavina, near the Temple of Eir.”
</p>
<p>
Natalie’s jaw dropped. She turned to Tina with a bewildered expression. “Okay, I was not expecting that.”
</p>
<p>
“He’s delirious,” Tina said.
</p>
<p>
Natalie shook her head ponderously and looked back at Mike. “We’re near the Temple of <em>what</em>?”
</p>
<p>
“Eir,” said Mike. “Handmaiden of Frigga.”
</p>
<p>
Natalie’s eyes lit up and a wide smile overtook her face. She threw her head back and let out a loud, raucous laugh.
</p>
<p>
Jason asked with worry, “What’s going on? What’s so funny?”
</p>
<p>
Natalie kept laughing. “That’s brilliant!”
</p>
<p>
“Is he going to be okay?” asked Jason. “Is he brain-damaged?”
</p>
<p>
“Eir! The Norse goddess of healing!” she said with delight. “And we’re down the street from Swedish Medical Center!”
</p>
<p>
Mike smiled.
</p>
<p>
She squeezed his arm reassuringly and said in a soft, kind tone, “Listen. My name is Doctor Natalie Rosenbaum. This is my apartment. You’re safe here. I know you’re hurt, I know you’re scared, but you’re going to be okay.”
</p>
<p>
He nodded slowly.
</p>
<p>
“Listen to me. I want you to close your eyes,” she said to him gently and methodically, “and inhale slowly through your mouth. Hold your breath in… Good… And then slowly let it out. Focus on relaxing. Focus on the feel of my hand. Breathe in… This is a safe place. Nothing bad will happen to you here. And out…”
</p>
<p>
After a few repetitions, Mike opened his eyes. They were wet.
</p>
<p>
“What’s your name?” asked Natalie.
</p>
<p>
“Mike,” he answered. “Michael Braun.”
</p>
<p>
“Can you tell me where you are, Mike?” she asked softly.
</p>
<p>
“Yes. We’re on Pill Hill by Swedish Medical,” he said quietly. “In your apartment.”
</p>
<p>
“Very good, Mike,” she said.
</p>
<p>
“It’s a mess,” he added.
</p>
<p>
Natalie smiled bashfully.
</p>
<p>
Mike looked blankly over Natalie’s shoulder and said, “I haven’t forgotten.”
</p>
<p>
“Forgotten what, Mike?” she asked.
</p>
<p>
“That I’m going to die.”
</p>
<p>
“You’re not going to die, Mike,” Natalie said reassuringly.
</p>
<p>
“Yes I am,” he said. “We all do. ‘Remember to keep death daily before one’s eyes. <em>Memento mori.</em>’”
</p>
<p>
Natalie turned her head and followed Mike’s gaze. He was looking at the shelf above her TV, at the grinning human skull with the taxidermic snake coming out of its eye socket.
</p>
<p>
“Mike…” Natalie asked with audibly piqued curiosity, “What do you do for a living?”
</p>
<p>
“I protect the People of the Lowland Plains from the armies of the Orc King.”
</p>
<p>
“And when you’re not busy doing that?”
</p>
<p>
“I stock groceries at the Safeway in Queen Anne.”
</p>
<p>
“They teach you the Rules of Saint Benedict at the Safeway?” she asked with a wry smile. “Are your coworkers monks?”
</p>
<p>
“No,” he answered. “They’re fellow peasants.”
</p>
<p>
“That quote you just recited. That’s by Saint Benedict. Where do you know it from?”
</p>
<p>
“From the Wizard’s Compendium rulebook, in the chapter on Necromancy,” he answered. “It’s the caption under an illustration of a skull with a snake in its eye.”
</p>
<p>
“Do you know anything about Saint Benedict?” she asked.
</p>
<p>
“He was a Level 20 Priest?” said Mike.
</p>
<p>
Natalie hoisted her bulky body back up to standing and navigated across her living room. “Benedict,” she said as she walked, “is the Catholic patron saint of students and scholars. He’s the one who codified the rules that all monks should live by. You’ve heard that monks take vows of celibacy, silence, and poverty, right? Do you know why?”
</p>
<p>
“To avoid sin through temptation,” answered Mike.
</p>
<p>
Natalie smiled. She took the skull from the shelf and headed back to the couch. “It’s actually deeper than that. The main purpose of the Rules of Saint Benedict is to remove the ego from the study of the divine. They’re designed to get a monk’s mind out of its own way.” She cleared off a cushion and sat down beside him.
</p>
<p>
“See, Benedict knew,” she continued, “that a mind that’s intrinsically curious and intelligent is prone to self-sabotage. It learns something incompletely, and then moves on too quickly, trying to build more knowledge on top of an incorrect and incomplete foundation. It thinks, ‘Yeah yeah, I get it, I know how this works,’ when it really doesn’t. The purpose of the Rules of Saint Benedict is to make sure that the monk is examining himself at every moment of his life, always checking his own assumptions, always seeking knowledge, never presuming to have any. Makes sense, right?”
</p>
<p>
“True knowledge begins in knowing that you know nothing,” Mike recited. “An unexamined life is not worthy of being lived by a human being.”
</p>
<p>
“You know Socrates!” Natalie said gleefully.
</p>
<p>
“Yeah,” said Mike. “I read tons of him and Plato and Aristotle when The Titans expansion pack came out for Age of Mythology.”
</p>
<p>
Natalie giggled.
</p>
<p>
There was no joy in Mike’s face or tone. Slowly, he reached toward Natalie and took the skull from her hands. He held it before his face and gazed into its eye sockets.
</p>
<p>
“I tried to kill a man tonight,” he said emptily.
</p>
<p>
The room fell silent.
</p>
<p>
“I almost succeeded.”
</p>
<p>
Danny said softly, “You saved our lives back there, man.”
</p>
<p>
Jason added, “Yeah, Mike. You did the right thing.”
</p>
<p>
Mike said nothing. In the quiet tension, Natalie scooted closer and put an arm around him. He leaned into the hug, welcoming the contact.
</p>
<p>
“Did I?” Mike finally replied. “Did I really? Because it doesn’t feel like it. I don’t feel righteous. I don’t feel like I won. Where’s my gold pieces? Where’s my experience points? Where’s that sense of accomplishment? You know… You know that feeling you get when you beat a big boss in a video game? It’s like this little burst of stuff that your brain squirts out, telling you, ‘Yay! You win! Good job! Whatever you just did, keep doing it!’ You know what I’m talking about?”
</p>
<p>
Natalie answered, “Heh, yes. That stuff is called dopamine.”
</p>
<p>
“Well, I’m not getting it,” said Mike. “I’m trying to make myself feel it, but it’s just not working. You know, I wish I really could honest-to-God convince myself that this is all just some D&amp;D campaign. Because if it’s all just fantasy then I can handle it. If it’s fantasy then it’s all fun and exciting and what I just did was epic and I should be proud of myself. But if it’s not, then…”
</p>
<p>
Natalie clapped her hand on Mike’s thigh. “Okay Mike, listen up,” she said with optimism, looking warmly into his eyes. “I’m going to take you to Swedish. They’ll take care of your nose, and they’ll give you a CT scan. I’m going to help you through this. I’ll personally make sure you’re okay. Now, I’m going to be right back &mdash; I need to go change and then we’ll head out.”
</p>
<p>
She stood up from the couch and glided cheerfully toward her bedroom door.
</p>
<p>
As she passed by, Tina heard her humming.
</p>
<p>
“Glad to see you’re happy,” Tina said with a trace of resentment.
</p>
<p>
Natalie responded in a sing-song whisper, “T, you failed to mention over the phone that this guy is <em>fucking awesooooome</em>!”
</p>
<p>
She proceeded into the bedroom and rummaged through her closet for something suitable for leaving the house. 
</p>
<p>
Tina followed her friend. From the pile of blankets and pillows on the bed, a pair of feline eyes watched her as she entered.
</p>
<p>
She closed the bedroom door behind her. 
</p>
<p>
“Did I mention I was held at gunpoint and almost kidnapped by the Russian mob tonight?”
</p>
<p>
Natalie giggled, “I’m sorry, T, I know I’ve been ignoring you. I…” She looked at Tina’s face. Her expression turned ashen. “Oh my god. You’re serious.”
</p>
<p>
“It’s been a busy night,” said Tina.
</p>
<p>
“Oh T…” Natalie said. She came up to Tina and gave her a big maternal hug. “You must be a total wreck.”
</p>
<p>
“It hasn’t really sunk in yet.” She drew away and turned around to let Natalie disrobe.
</p>
<p>
“Is <em>that</em> who this Mike guy fought off today?” Natalie asked as she pulled on a set of black Spanx. “A team of Russian hitmen? And he <em>won</em>?”
</p>
<p>
“Damn it, Nat!”
</p>
<p>
“Sorry! It’s just… that’s… pretty cool.” She hoisted herself into a large gray dress.
</p>
<p>
“You didn’t see them in action,” Tina replied.
</p>
<p>
“Oh yeah?” said Natalie. “Was it amazing? Were they all sleek black-ops ninjas?”
</p>
<p>
Tina laughed. “Anything but. They were total ass-clowns. It was like watching The Bourne Identity starring The Three Stooges. Him and the other guy. Danny. The tall thin geeky one. He’s injured too. He’s lost some blood &mdash; I think a bullet grazed his shoulder.”
</p>
<p>
“He looked a little pale, but I thought that’s just nerd-skin. I’ll check him out. He helped beat up a Russian mobster?”
</p>
<p>
“He was mostly a distraction,” said Tina. “He had this machine… He called it a ‘HERF gun.’ The thing was like something out of a really low-budget science fiction movie, all held together with Velcro and duct tape. Like he built it himself or something.” 
</p>
<p>
“Technogeeky. Sounds like your type,” said Natalie. She examined her face in the mirror of an obscenely cluttered vanity and began applying spots of foundation.
</p>
<p>
“Please. I don’t do old men,” said Tina.
</p>
<p>
“No, you don’t do <em>men</em> at all,” Natalie retorted. “You do boys. Besides, I know you. If you don’t get yourself a rebound asap, you’ll be giving Roger a drunken bootie call in twenty-four hours flat.”
</p>
<p>
“Hey, shut up! I have more willpower than that!” said Tina.
</p>
<p>
Natalie looked at her.
</p>
<p>
“Oh my god, shut up!” Tina demanded, blushing. She realized that the sleeve of her cardigan was stained with Danny’s blood. She took it off, leaving herself in her button-down shirt underneath, and threw it into Natalie’s closet. “Nat, if I didn’t know better, I’d say you were pressuring me into hooking up with the first remotely do-able guy just so you can hear me tell dirty stories about someone besides Roger for a change.”
</p>
<p>
Natalie paused for a moment to puff up and cross her arms. “Oh, we will have <em>none</em> of that, you hear? I’m the only clinical psychiatrist in the room, so I’ll be the only one doing any clinical psychiatrizing.”
</p>
<p>
“Oh, bam! I got a little truthy there, didn’t I?” Tina teased.
</p>
<p>
With a laugh and a headshake, Natalie finished adjusting her dress and makeup. “How do I look?”
</p>
<p>
“Lovely. But your new crush is potentially brain-damaged, so he probably won’t notice.”
</p>
<p>
“You’ve still got keys to this place, right?” asked Natalie. “Do you want to come with me to Swedish, or should I leave you here with your new boyfriend? There’s Jack Daniels in the pantry.”
</p>
<p>
“Oh come on, I do <em>not</em> need to get a guy drunk to have my way with him,” Tina protested. “Anyway, I think I’ll stick around. I want to see what’s all the fuss about this vial.”
</p>
<p>
Natalie reached into a drawer and pulled out a blood pressure cuff, a stethoscope, and a stopwatch. “You still remember how to use these?”
</p>
<p>
Tina nodded.
</p>
<p>
Natalie tossed the tools into Tina’s hands and shoved her out to the living room.
</p>
<p>
Jason had taken Natalie’s place beside Mike on the couch, keeping him engaged in light conversation. Danny waited quietly on a stool near the kitchen.
</p>
<p>
“Danny!” barked Natalie. “Take your clothes off.”
</p>
<p>
Danny jumped uneasily.
</p>
<p>
The girls approached him. Natalie circled him, carrying clothes and first aid, and pulled on a pair of plastic gloves. Tina stood by with the sphygmomanometer.
</p>
<p>
Hesitantly, Danny pulled off his flannel. The upper left back was caked with dried, crusted blood. There was a three-inch-long slice across the left shoulder &mdash; the material looked like it was torn with a serrated knife.
</p>
<p>
His shoulder stung as he lifted his arms to remove his black t-shirt underneath. The shirt caught on his skin as he drew it over his back, and he realized that the cotton fabric had clotted into the gash. He took a deep breath in anticipation of the sharp pain and yanked the shirt up, tearing the large scab open. Warm moisture oozed down his naked spine.
</p>
<p>
Natalie cleaned him with alcohol wipes and disinfectants, and dressed the wound in gauze and adhesive bandages.
</p>
<p>
Tina took his wrist and held his arm out so she could slide on the blood pressure cuff. “Hey,” she said to him nonchalantly. “You doing okay?”
</p>
<p>
“Me? I’m fine. I’m doing great,” he answered with an overconfident smile.
</p>
<p>
She chuckled through her nose and traced her fingers lightly along the inside of his wrist in search of his pulse. As her fingertips brushed across his skin, the rhythmic throb of his ulnar artery conveniently grew visible to her naked eye. She breathed on the end of the stethoscope to warm it up, and carefully laid it against the inside of Danny’s elbow to measure his pulse and blood pressure. They were elevated.
</p>
<p>
Danny flexed his abs upon noticing that Tina was checking out his midsection. “Am I going to live?” he asked with bravado.
</p>
<p>
“You’ll be fine,” said Natalie. “Drink some orange juice, eat some protein bars, and rest for a while.” She ruffled his floppy brown hair and said to him, “Think you can handle that?” 
</p>
<p>
“Yeah,” Danny said. “Mind if I raid your fridge?”
</p>
<p>
Natalie looked a little sheepish. “All I have in the house is liquor and frozen pot pies. But there’s a Rite Aid on Madison and Summit. Walking distance. Tina will help you get there. Right, Tina?”
</p>
<p>
Tina quickly shot her a dirty look. “Sure. No problem.”
</p>
<p>
Natalie took away his bloodied flannel, and shoved a wad of fresh clothes into his hands. “Here. You can wear this,” she said.
</p>
<p>
Danny held up the clothes in front of him. She had given him a shapeless flower-print sweatshirt. “Thanks, Doc,” he said with equal parts sincerity and sarcasm.
</p>
<p>
Natalie sashayed over to the couch. She turned to Jason and said, “Hey. You’re the one with the car, right? Can you drive us to Swedish? It’s only about three blocks away.” 
</p>
<p>
Jason nodded.
</p>
<p>
“Good,” she replied, and turned to Mike. “And now, as for <em>you</em>…” She reached out with both arms, took him by the hands, and helped him rise from the couch. “Ready to go get your head examined?” she said, looking up at him.
</p>
<p>
He didn’t answer.
</p>
<p>
“You’ll be okay, Mike,” she said to him quietly.
</p>
<p>
He nodded.
</p>
<p>
“Here, this will help,” she said. She opened a coat closet near the front door, and reached into a homemade jewelry box inside. “Normally I’d give someone sedatives to reduce anxiety, but I don’t want to take chances with your head right now. What I <em>can</em> do, though, is give you this.” 
</p>
<p>
She pulled out her large homemade woven bracelet of fuzzy leaves and small yellow flowers, and put it on his wrist.
</p>
<p>
With a fascinated expression, Mike said, “Mullein!”
</p>
<p>
Natalie was stunned. “You know what this is?”
</p>
<p>
Mike said, “I’ve never seen it in real life before.”
</p>
<p>
“Do you know what it does?” she asked.
</p>
<p>
Mike answered, “It grants the wearer a plus-four bonus on saving throws versus fear.”
</p>
<p>
Natalie hopped in place just a little bit.
</p>
<p>
Mike examined the mullein bracelet around his wrist with fascination. As he stared at it, his eyes began to well up with tears. “Natalie…” he said in a cracking voice. “I really don’t feel very brave right now. I don’t feel like a winner. I just feel like… I just…”
</p>
<p>
Natalie watched his face with sympathy. She gently reached her arms around him and pressed her head against his chest. “It’s okay, Mike,” she said to him quietly. 
</p>
<p>
He returned her embrace and bowed his head down to rest on top of hers. His chest shook several times silently. He gradually began to emit a series of coughing sobs, each one longer than the last, until they joined in a long wail. Loud, wet, gasping inhales punctuated his bawling.
</p>
<p>
“It’s okay, Mike. It’s okay,” Natalie said over and over as she held him tight. “Don’t be afraid to cry.”
</p>
</div>