<div class="chapsection">
<p>
<span class="caplead">Nothing in the world had any right</span> to look like what Danny saw happening before him. Such abominations belonged on the other side of a movie screen, projected in two dimensions and tempered by the audience’s knowledge that they were made of latex and CGI. It was a spectacle not meant to be witnessed up close, not in three dimensions, not complete with sound and smell and sensation. 
</p>
<p>
The man brought his hands up to his acid-splashed face in a desperate, frantic effort to wipe the corrosive liquid away. Holes burned instantly in the sleeves of his denim jacket. Sores and welts appeared on his fingers, resembling the scabby red wounds of chickenpox. Through the gaps between his fingers, the skin of his face could be seen oozing with frothy yellowish-white puss.
</p>
<p>
His gun clattered to the concrete floor as he rose and began running blindly. He only made it a few stumbling steps before tripping and collapsing to his knees.
</p>
<p>
He didn’t start screaming right away. He at first let out an annoyed yelp, more out of surprise than pain. But in a matter of seconds it crescendoed to howls, then cries, then a shrieking that quickly grew so loud and high-pitched that it scarcely seemed human. His sounds of agony filled the small factory, rising and falling randomly until they dissolved into moist, gurgling atonal harmonics.
</p>
<p>
Strands of long stringy blond hair fell from his head, momentarily curling and writhing on their own upon the floor. Within his eye sockets were two deformed cauldrons of bubbling white foam, leaking a clear gelatinous fluid. Greenish-yellow cauliflower-like globules of fat spilled out from areas that had once been cheeks and chin.
</p>
<p>
The smell was like vomit after a meal of putrescent meat.
</p>
<p>
And then there was an explosion of mechanical sound &mdash; a loud <em>rat-tat-tat-tat-tat</em>, like someone trying to shove a metal rod into the spokes of a spinning bicycle wheel. A hot shockwave of pressure raced through the air, carrying with it the acrid, metallic smell of gunpowder. Several smoky black blurs streaked through the air, toward the shrieking faceless thing that had been Rex. Their impacts knocked him back and down, his body convulsing forcefully with each hit. 
</p>
<p>
Only the first handful of shots made contact with him. The rest tore through the debris on the floor, or sunk into nearby laboratory machines, or shattered glassware, or scarred the walls with ricochet marks.
</p>
<p>
Julie grunted, “Ah, shit!” after the burst of gunfire stopped. It had come from her. 
</p>
<p>
She stood where Rex’s gun had fallen, holding the blocky weapon awkwardly in both of her small hands. She examined the weapon quickly and intelligently, noting its protrusions and features. The girl experimentally placed her hands on different parts, unsure of how best to grip it to maintain control of its full-automatic spray.
</p>
<p>
The wretched, faceless creature gurgled for a moment and collapsed lifeless on the factory floor. Blood flowed freely from a handful of holes in its torso. The cardboard and packing peanuts on the floor around the body turned crimson. 
</p>
<p>
Danny saw shadows watching the scene from above. In the doorway at the top of the interior stairs leading up to the small office stood two figures &mdash; the athletic, muscular, leather-clad form of Eugene Mukhayev, and the large, imposing middle-aged man that must have been Sergey. Eugene was in front, with his hand still on the knob of the pale blue door.
</p>
<p>
The mafia enforcer and his boss stared down at the scene in the factory with their breath drawn still, their jaws slack, their eyes wide with horror and disgust.
</p>
<p>
Julie followed Danny’s gaze, her head turning quickly like a bird’s, her movements twitchy and animated. She swung the blocky gun upward, pointed it at the figures in the door, and opened fire without warning or hesitation.
</p>
<p>
The two men ducked and fled back into the office room. Eugene returned fire from a small revolver, shooting haphazardly toward Julie before slamming the pale blue door shut behind him. The bang of Eugene’s pistol rang out through the factory, accompanying the <em>rat-tat-tat</em> of Julie’s machine gun with a slower syncopated tempo.
</p>
<p>
Julie bobbed and weaved to make Eugene’s angle of fire as difficult as possible. She shot in short, sporadic bursts as she dodged, unleashing two or three bullets at a time. Flakes of brick knocked loose from the walls around the top of the stairs. Her bullets flew in a wild haphazard spread as she struggled against the recoil of the weapon, mostly hitting the outside of the overhanging office room and making small angled dimples in its metal walls. The windows shattered under fire, causing shards of glass to rain into the office and onto the factory floor below. Where the bullets happened to hit the pale blue door, they ripped long gouges of splintering light brown plywood.
</p>
<p>
Spent shell casings flew wildly from her gun, pinging upon the concrete floor. One brass cylinder hit the back of Danny’s hand, still scorching hot from the exploding gunpowder it had contained only microseconds prior.
</p>
<p>
At that moment it dawned on Danny that he wasn’t merely a passive observer. The bullets from the office above, he realized, were meant for him just as much as they were meant for the coke-addled Asian girl.
</p>
<p>
He looked for somewhere to hide. Jason, for his part, had already bunkered himself under the metal table.
</p>
<p>
With his HERF gun in hand, Danny dove to shield himself from the firefight. He ducked behind the largest, most solid object nearby. 
</p>
<p>
Unfortunately, Danny noticed a moment afterward that this object happened to be a blue 55-gallon drum filled with kerosene. 
</p>
<p>
An errant bullet from Eugene’s pistol plunked into the barrel, puncturing it and making a soft sloshing noise somewhere inside. 
</p>
<p>
Danny had seen enough action movies and played enough first-person shooter video games to know what happens when a barrel of flammable liquid gets shot. <span class="think">So this is it</span>, he thought quickly, more in impressions than words. <span class="think">A pretty awesome way to die, actually. And this right here is my last thought: the realization that my last thought is my last thought. How meta. I’ve always been such an over-thinker. How fitting.</span> And the kerosene barrel exploded, ripping Danny to shreds in a blast of steel and flame.
</p>
<p>
But that didn’t actually happen.
</p>
<p>
The kerosene barrel did, however, begin leaking. The clear, pungent fluid slowly began to spill out. The impact was not dead center on the barrel, and it carved a short slice out of the metal skin before coming to rest. The fluid ran down and around the side of the drum, spilling onto Danny’s borrowed floral-print sweatshirt.
</p>
<p>
Kerosene continued to pour onto the floor, forming an iridescent puddle on the concrete. The thin liquid spread toward a pile of packing debris. Cardboard absorbed it without incident. Styrofoam packing peanuts, however, melted on contact with the kerosene, dissolving into gloppy half-formed masses like ice cream on a hot summer sidewalk.
</p>
<p>
The short bursts of <em>rat-tat-tat</em> noises from Julie’s firearm abated for a few moments. Danny risked a peek around the side of the barrel to see her bounding up the interior stairs. She made it to the top and stared at the door to the office room. The door’s pale blue finish bore long wooden scars as though it had been clawed by a wild beast.
</p>
<p>
Eugene stopped shooting, either unsure of where to aim or unable to tilt his gun to the proper angle. 
</p>
<p>
From the office room on the other side of the pale blue door came the slight sound of whispering.
</p>
<p>
In response, Julie suddenly yelled, “Oh, you’re in trouble now!” She squeezed the trigger, unleashing a tight spray of bullets upon the door.
</p>
<p>
The bullets pounded against the plywood obstacle. On Julie’s side, they punched perfectly round holes no bigger than a penny, but jagged chunks of wood the size of books burst off from the door’s opposite side. The door shuddered on its hinges as it absorbed the kinetic energy of the hollow-point projectiles. It quickly disintegrated into a patchwork of splinters and sawdust.
</p>
<p>
Through the office windows, Danny saw the office’s front door open. The two gangsters fled outside onto the landing of the exterior stairs, crouching low to avoid the girl’s gunfire. They slammed the outer door shut behind them, doubtlessly counting on its metal bulk to protect them from the onslaught.
</p>
<p>
Julie continued firing through the flimsy, flapping remains of the pale blue plywood, until finally the weapon’s bolt made an idle click and ceased moving. It left an abrupt silence in its wake.
</p>
<p>
Realizing that she was out of ammunition, Julie wasted no time. She flung open the remnants of the pulverized interior door, sprinted to the other side of the small office toward the front door on the opposite side of the room, and twisted the deadbolts shut.
</p>
<p>
 Outside, the men pounded against the front door and struggled with the locks, but they were seconds too late. They tried kicking it, bashing it, even shooting it, but the metal outer door wouldn’t yield. 
</p>
<p>
The African-American guard’s voice could be heard saying, “Don’t bother, man. We made sure nobody could bust in. Your orders, remember?”
</p>
<p>
Eugene yelled, “God fucking damn it, Deshaun! You standing in alley the whole time? What the fuck is wrong with you? You don’t hear the shooting? You don’t think to come up here and help us maybe?”
</p>
<p>
“You guys told me to stay out here,” the guard retorted. “I thought Rex had you covered if anything went down. I heard screaming, I figured you were, you know, working them over. What happened in there?”
</p>
<p>
Sergey answered, “That screaming <em>was</em> Rex.” His heavy footsteps descended the staircase outside.
</p>
<p>
“Holy fuck. Guys, are you alright?” asked the guard.
</p>
<p>
“No, I’m not alright,” Eugene grumbled. “Look what that girl did to my jacket! This is Italian custom-made lambskin leather! See here? Bullet graze. Here? Torn on glass. I swear to fucking God, that bitch is not making it out of there alive! I’ll tear that little whore’s throat out! I’ll kick her teeth in with my bare hands!”
</p>
<p>
Sergey said, “You kick with your hands, Zhenka?”
</p>
<p>
Eugene sputtered, “I… with my… Shut up!”
</p>
<p>
Inside, Julie leaned with her back against the metal door, breathing heavily. A huge grin consumed her face. She let out a deep, satisfied sigh.
</p>
<p>
Jason and Danny cautiously emerged from their hiding spots.
</p>
<p>
Jason rolled out from under the metal table. He put a hand on the tabletop and grunted as he lifted his overweight middle-aged body back to standing height. “Julie, are you okay up there?” he called out.
</p>
<p>
Julie replied, “Woooooooohooooooooo!”
</p>
<p>
Danny took a few tentative steps out from behind the barrel and surveyed the room. The rows of 55-gallon drums had served as a backstop for Eugene’s bullets. Most of them were leaking profusely from fresh bullet holes, coating the floor of the factory in a mixture of kerosene and acetone. All over the room, Styrofoam packing peanuts dissolved into thick bubbling puddles, filling the room with a soft ubiquitous hissing noise.
</p>
<p>
His sweatshirt had soaked up a great deal of kerosene by leaning against that punctured drum. It felt damp and heavy and irritating against his skin. 
</p>
<p>
The mixed stench of jet fuel and nail polish remover assaulted Danny’s nose. The very air in the room burned his lungs with every inhale. It was growing progressively harder to breathe. His eyes stung sharply and began to well up with moisture.
</p>
<p>
“Julie, we can’t stay in here,” he shouted to her.
</p>
<p>
Julie struggled with some piece of furniture in the office. Rattling sounds echoed from upstairs. “Hey, you!” she called out.
</p>
<p>
“Me?” asked Danny.
</p>
<p>
“Yeah you!” She poked her head out through the broken interior door. “Do me a favor. There’s this desk up here with a couple drawers that I want to get into. It’s locked.”
</p>
<p>
“So?” asked Danny. “What do you expect me to do about it?”
</p>
<p>
“Get the key,” she answered.
</p>
<p>
“From where?”
</p>
<p>
 Julie reached her arm out and pointed toward the center of the room. Danny followed her finger.
</p>
<p>
She was pointing at Rex’s body.
</p>
<p>
Danny’s stomach lurched. His heart palpitated in his throat and the skin on the back of his head crawled. His hearing grew distant and echoing. His vision began to dim &mdash; the world became oddly flat as though projected on a screen, and colors faded toward muted grayish tones before his eyes. He gulped for air, but the searing mix of harsh chemicals in the room served only to make him feel even sicker.
</p>
<p>
“Oh for God’s sake,” Julie scolded from above. “Grow some fucking balls!”
</p>
<p>
Danny growled loudly and shook himself just to stay conscious. <span class="think">This isn’t real</span>, he told himself. <span class="think">This is just a video game. Yes, a video game. I’m at home right now, sitting on my nice comfy leather couch, in the middle of my 7.1 surround sound setup, in front of my 60” 1080p plasma HDTV, playing a really awesome new game on my PlayStation 3. It’s very, very immersive.</span>
</p>
<p>
He maneuvered toward the body, feeling like he was detached and floating. Up close, he could tell by parallax that the acid-burned face model was rendered as a genuine triangle mesh with Bezier edge-smoothing rather than a cheaper and more conventional programmatic shading approach, and he was deeply impressed by the PS3’s ability to handle such a high polygon count. He watched his hand before his eyes as it prodded the blood-soaked pockets of the body. Danny found a keychain with several keys, a Ford car remote, and a tiny plush Kurt Cobain doll. He added the keychain to his inventory. He then hurried to the stairs, eager to get up to the office and away from the noxious fumes that were rapidly depleting his health bar.
</p>
<p>
Up in the office, Julie and Jason were both waiting for him. Julie stood by the desk, impatiently wrestling with the locked drawer. Jason sat on the floor, looking green and pale &mdash; the irritant gases were hitting his middle-aged cardiopulmonary system hardest of all.
</p>
<p>
Danny fiddled with the keychain until he found a lone brass key that was smaller than the others, suited for a desk. He moved in to unlock the drawer and began rifling through it.
</p>
<p>
“So, anything good in there?” asked Julie.
</p>
<p>
“Well,” answered Danny, “there’s this…” He withdrew a long, thin, narrow metal box &mdash; an extra magazine for Julie’s gun. Slits in the magazine allowed Danny to see the bullet cartridges, about fifty of them, stacked neatly into two columns inside.
</p>
<p>
Julie nodded approvingly and took the ammunition. She began pulling and pressing on random parts of the gun, trying to figure out how to eject the empty magazine and replace it with the full one.
</p>
<p>
“…And this,” Danny said, slapping a large, heavy key onto the desk.
</p>
<p>
“Oh, I’ve seen them use that before,” said Julie. “When they bring new equipment in. It’s for those big loading doors downstairs.” 
</p>
<p>
Danny checked on Jason, who seemed to be improving now that he was away from the spill of kerosene and acetone. The smell of the chemicals was markedly less intense in the small office. From the tiny bathroom came the whirring noise of an overhead ventilator.
</p>
<p>
Danny turned to the computer on the desk and began searching for something they might be able to use to escape. An initial click-through of the desktop folders suggested that this computer probably contained nothing but pirated movies and amateur porn. 
</p>
<p>
As he continued searching the computer, he heard the conversation of the gangsters outside in the alley below.
</p>
<p>
“Guys, we can get in just fine,” said the dreadlocked guard. “I have keys to that door up there.”
</p>
<p>
Eugene replied, “And what? Waltz right in? Do we know how much iron they have?”
</p>
<p>
“No,” answered the guard guiltily.
</p>
<p>
Sergey asked accusingly, “Fuck, Deshaun, you did not search them before they go in?”
</p>
<p>
The guard said nothing.
</p>
<p>
Sergey declared, “I’m not sending anyone in there without head-to-toe armor. Is not worth losing another man.”
</p>
<p>
The guard suggested, “We could just crack the door open a little and lob a few grenades in there.”
</p>
<p>
Sergey grumbled, “That would break the vial.”
</p>
<p>
“Riot grenades, then,” said the guard. “Fill the place up with tear gas, choke ‘em out. Or flash-bangs &mdash; stun them, then jump in and blow them away before they know what the fuck’s going on.”
</p>
<p>
Eugene scoffed, “You think we have giant stash of grenades in our trunk, Deshaun? Oh sure! Welcome to Grenade Buffet! Twelve ninety-nine, all you can throw!”
</p>
<p>
Deshaun replied, “Guys, you want grenades? I can get you grenades. Just one call to my boys. Deliver in twenty minutes or less. My phone’s right here.”
</p>
<p>
Back in the office upstairs, that last line piqued Danny’s interest. He abandoned the unfruitful computer and, with HERF gun in hand, walked quietly to the exterior wall of the office, listening intently to try to triangulate exactly where the voices were coming from.
</p>
<p>
“Put your phone away!” Eugene ordered.
</p>
<p>
“It ain’t a big deal, man” the guard said reassuringly. “I know a dude owes me a favor anyway.”
</p>
<p>
Danny’s fingers flipped a switch. Small cooling fans whirred to life.
</p>
<p>
“That’s not the point!” Eugene insisted. “Put it away now!”
</p>
<p>
“I… okay…” said Deshaun. “But I don’t…”
</p>
<p>
Inside the office, there was a soft “<em>bonk!</em>”
</p>
<p>
In the alley, there was a sudden sharp cracking sound.
</p>
<p>
“Ow!” yelled Deshaun. “What the <em>fuck</em>?”
</p>
<p>
A broken cellphone clattered to the ground.
</p>
<p>
Eugene groaned, “Fucking great. Told you so!”
</p>
<p>
Danny, in the office above, sighed approvingly. The HERF gun emitted a quiet, rapidly rising high-pitched whine as its capacitor bank recharged.
</p>
<p>
Below, Sergey started coughing and rumbling.
</p>
<p>
“Seryozha! Are you alright?” asked Eugene.
</p>
<p>
Sergey cleared his throat forcefully, sounding like the whinnying of a horse. “I’m fine. Shut up.” 
</p>
<p>
Deshaun barked, “The fuck happened to my phone, man?”
</p>
<p>
“The nerdy guy has some kind of electronics gun,” said Eugene. “It kills cellphones.”
</p>
<p>
Sergey added, “And cars. That asshole destroyed my Roadster.” 
</p>
<p>
“That’s just because it was electric, I think,” Eugene said. “It won’t work on all cars. My Beamer here should be okay.”
</p>
<p>
“Even with all its little extras?” Sergey suggested, his voice still slightly hoarse.
</p>
<p>
“What little extras?” Eugene asked defensively.
</p>
<p>
Yes, what little extras? thought Danny.
</p>
<p>
“All the options you always brag about,” Sergey said. “When you buy that thing, you come to me saying, ‘Oh, uncle, look at fancy new toy! She is with the remote ignition, she is with the satellite radio, she is with the GPS, she is with the BMW Assist plan…’ ”
</p>
<p>
<span class="think">She is with the spectrum profile of a symphony orchestra</span>, Danny thought. He checked the HERF gun’s tiny lamps. They were green again. He grinned.
</p>
<p>
Eugene mumbled, “Shit, you think it…”
</p>
<p>
There was a low “<em>bonk!</em>”, and a sharp crack from the alley below.
</p>
<p>
Eugene screamed, “Fuck, no! No, no, <em>no</em>!” 
</p>
<p>
Danny heard the sound of footsteps running, the sound of a car door being flung open, and the distinct lack of sound of an engine turning.
</p>
<p>
“My Beamer!” wailed Eugene. “My beautiful brand new 650i Beamer! Fuck, no! No no no!” Footsteps ran to the side of the alley with Jason’s Lincoln Navigator. You…” A shot rang out. “…God&mdash;” <em>Bang!</em> “&mdash;damned…” <em>Bang!</em> “…dick!” <em>Bang!</em> <em>Bang!</em> <em>Bang!</em>  
</p>
<p>
Danny giggled.
</p>
<p>
Sergey made several loud, painful-sounding grunting noises.
</p>
<p>
The African-American guard, in a nervous tone, said, “Hey… Hey, Sergey. You okay, boss-man? You don’t look so good…”
</p>
<p>
The large middle-aged Russian snapped back gruffly, “Mind your own fucking business!”
</p>
<p>
Eugene abandoned his tantrum and said a few words to Sergey in Russian. His voice was heavy with concern.
</p>
<p>
“I said I’m fine, God damn it,” Sergey rumbled defiantly. “Now let’s think of way to… to… How you would say?”
</p>
<p>
Deshaun offered, “Fuck these shitheads up?”
</p>
<p>
“Exactly.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">The <em>rat-tat-tat</em> of Julie’s gun</span> burst out suddenly. She fired a few bullets through the broken office windows toward the far factory wall, announcing to the world that she had successfully reloaded. Danny couldn’t find anything helpful on the computer, but Julie had put it to use to figure out how to operate her weapon. Between Wikipedia, YouTube, and some gun enthusiast websites, she was able to identify the firearm as a MAC-10 and determine how to properly swap the magazine and load the first round into the chamber. 
</p>
<p>
“Jason,” Danny said. “Can’t you, like, talk us out of here?”
</p>
<p>
“And how do you propose I do that?” Jason asked.
</p>
<p>
“I don’t know. Negotiate or something?”
</p>
<p>
“We’re in no position to negotiate,” Jason scoffed. “Negotiation isn’t some kind of magic spell where I open my mouth and words come out and suddenly everyone becomes lovey-dovey. Negotiating takes leverage. And we don’t have any.”
</p>
<p>
“We both still have our cellphones,” said Danny. “Is there anyone you can call?”
</p>
<p>
“The cops?” Jason offered. “But, um…” He gestured out to the room &mdash; to the cocaine on the desk, to the spent shell casings and the bullet holes in the wall, to the horribly killed corpse in the factory below. “I can make shit up, Danny, but I can’t think of any innocent way to explain what we’re doing here.”
</p>
<p>
Danny sighed. “So. Death or jail. Really? That’s our options?”
</p>
<p>
Jason looked down somberly and shrugged.
</p>
<p>
Julie, for her part, admired herself in the bathroom mirror. She postured and posed with the gun, pouting her lips and giving sultry looks, pressing it up against her body like an action movie femme fatale &mdash; the visual impression of erotic danger greatly diminished by her pajamas and bunny slippers. 
</p>
<p>
“God, you guys are such a bunch of whiners,” she said.
</p>
<p>
Jason asked, “Got any ideas, Julie?”
</p>
<p>
“Yeah, I do,” she said, trying out a <em>Charlie’s Angels</em> pose and finding that it was best done in heels and a side-slit skirt rather than borrowed sweatpants. “But you guys wouldn’t want to hear it. You’re too chickenshit.”
</p>
<p>
“Try us,” Jason insisted.
</p>
<p>
“No,” she said. “I’m sick of explaining shit to you guys. Ever since you got here, you’re all talk talk talk talk talk. Fuck that. You want to get something done, just fucking do it already.”
</p>
<p>
“Just tell us what you have in mind, Julie,” Jason coaxed.
</p>
<p>
In response, Julie marched to the desk and grabbed the large, heavy key, and said, “How about I show you instead?” As Danny stared at her nervously, she jabbed a finger at his chest. “You. When I give a signal, start banging on this door here. Just pound on it. Make some noise. You know, create a distraction. Think you can handle that?”
</p>
<p>
Danny, perplexed, merely nodded his head.
</p>
<p>
The girl skipped down the stairs, her slipper-clad feet making soft syncopated landings. Down in the factory, she made her way toward the large metal double doors at the front of the room. 
</p>
<p>
From the inside, the loading doors were held closed by a complex mechanical arrangement of steel crossbars, operated by a large lever. A heavy padlock kept the lever securely in place. Slowly and quietly, struggling against the cocaine to keep her fingers from shaking, Julie slid the key into the padlock and discreetly freed the lever. With the lock undone, she began a series of practice pantomimes on the complex latch mechanism. After a dozen or so rehearsals, the girl closed her eyes, concentrated, and took several deep, heavy breaths. Finally, she looked up at Danny and shook her fist in the air.
</p>
<p>
Danny slapped his hand hard against the locked door, sending loud metallic reverberations out through both the factory and the alley outside. He repeatedly banged on it until he was answered with a gunshot from outside, accompanied by the “<em>plink!</em>” of a bullet. 
</p>
<p>
Danny gulped and awkwardly called out, “Hey, uh, Eugene! Eugene, are you there?”
</p>
<p>
From the other side of the door, Eugene’s voice could be heard saying to his comrades, “Did you hear that? Did this fucker just call my name like he’s my buddy? You got something to say to me, dickwad?”
</p>
<p>
“I want to, uh, negotiate?” Danny shouted.
</p>
<p>
Sergey’s deep, slow voice responded, “You want to talk, you talk with me.”
</p>
<p>
Danny replied, “I.. Uh… I was just thinking, that, uh, you know, we have the vial in here… You know, the vial you want… Or at least, I assume you want… So, like, maybe if you wanted to, uh, like…”
</p>
<p>
He was interrupted by a loud metallic groan from below.
</p>
<p>
With as much strength as her small arms could muster, Julie yanked the lever that drove the mechanical latches holding the loading doors shut. The large metal double doors came unmoored from their sockets, and Julie shoved one of them narrowly open.
</p>
<p>
“Surprise, motherfuckers!” she screamed, and let loose a hail of gunfire.
</p>
<p>
The men in the alley shouted and dove for cover, Deshaun behind the exterior stairwell and the two Russians behind their BMW. Julie crouched in the doorway, using the large metal doors as a shield, steering the MAC-10 with both hands. The rattle of her gun was answered by the matching report of the black man’s identical firearm and the sporadic bangs of Eugene’s revolver.
</p>
<p>
The gap in the doors put the exterior stairwell directly in Julie’s line of fire. Her bullets made high-pitched plinks as they grazed off of the iron railing, zinging through wide gaps in the struts between the steps. The African-American guard, seeing that the stairs would offer him very little protection, aimed around the side of the railing and fired back.
</p>
<p>
Julie dropped to the ground just in time. The spray of hollow-point bullets from Deshaun’s gun had been meant for Julie’s head, but instead hit the narrowly opened door behind her. They squashed against the inside of the metal door, pushing against it and bouncing idly away as flat little mushrooms of lead that ricocheted into the factory. The door behind Julie began to swing wide open from the kinetic energy of the deadly projectiles.
</p>
<p>
On the ground, Julie kept firing. The stairwell, she noticed, didn’t quite reach all the way down to the ground. There was a gap of approximately three inches between the asphalt and the bottom-most stair, and in that gap she could see Deshaun’s shoes. She turned the MAC-10 horizontally, rested her hand on the ground, and seized the opportunity.
</p>
<p>
The burst of bullets ripped through the black man’s foot and ankle. He let out a sustained, choking grunt, and fell sideways onto the stairwell, landing on his shins and knees. He tried to use his arms and elbows to push himself off of the stairs and back into an upright position, grunting heavily through gritted teeth from the exertion. When his leg collapsed under him a second time, he looked down at his foot, and that’s when he started screaming.
</p>
<p>
Laying prone on the stairs made him a much easier target for Julie. There were plenty of gaps in the ironwork to permit a bullet to pass. She quickly picked herself up off the ground, lifted her firearm, and prepared to spray several more bullets at the black man, counting on at least one to score a killing shot.
</p>
<p>
Instead, she flew backward into the factory.
</p>
<p>
The echoes of the last bang from Eugene’s pistol resounded through the alley. The ricochet of Deshaun’s bullets had pushed the door open wide enough to afford the crew-cut Russian a clear shot at the small Asian girl.
</p>
<p>
Julie fell on her tailbone and landed face-up just inside the large loading doors. Her MAC-10 was still in her hand.
</p>
<p>
Lying on her back, she stared upward at the ceiling’s gymnasium lights with a blank, confused look on her face. She tried to rise, but her abdominal muscles wouldn’t obey her. 
</p>
<p>
On one side of her abdomen, her sweatshirt bore a small moist circular stain of blood, barely the size of a penny.
</p>
<p>
The stain quickly grew much bigger.
</p>
<p>
She managed to turn herself to the opposite side and lift herself up on an elbow. 
</p>
<p>
She coughed wetly. A thick stream of blood flowed out from her mouth.
</p>
<p>
The small Asian girl remained frozen in that position, propped on one elbow, unfocused. Her breathing became short and shallow. Her skin paled, acquiring a sickening greenish hue. Her dark, wide-pupilled eyes glazed over. She began to shiver.
</p>
<p>
Hearing the sound of movement just outside the loading doors, she slowly turned her head to look outward. A man’s shadow darkened the doorway. Julie lifted the MAC-10 in one hand and waved it at the entrance, straining against the gun’s weight. The weapon shook in her weakening hand. She squeezed the trigger to fire off a few warning rounds. The recoil knocked the firearm out of her grasp.
</p>
<p>
The muscular, leather-clad figure of Eugene wheeled into the doorway. He fired two quick shots squarely into Julie’s ribs and spun back away out of sight.
</p>
<p>
Julie collapsed onto her back. A final wet, rasping breath escaped her throat, carrying with it a red, bubbling froth. Her entire body twitched once, and fell still. 
</p>
<p>
The room was silent. Blood quietly pooled around Julie’s body.
</p>
<p>
Eugene’s athletic form again appeared in the doorway, crouching low and glancing around cautiously. He reached in through the entrance just far enough to grab a bunny-slipper-clad ankle, and dragged the small Asian girl’s lifeless body out into the alley. A streak of blood on the floor marked her exit, and she was gone.
</p>
<p>
There was the sound of rustling clothing. 
</p>
<p>
“<em>Oppah!</em>” said Eugene’s voice. “Seryozha, look what the good little girl has for us!”
</p>
<p>
“She had the vial on her?” asked Sergey.
</p>
<p>
“Yes!” Eugene said happily. He walked toward Sergey. “Here you go, Seryozha. Is present from your favorite nephew!”
</p>
<p>
Sergey responded in Russian.
</p>
<p>
“Now we go in and teach those fuckers a lesson?” asked Eugene.
</p>
<p>
“No,” said Sergey. “Now we save our soldier.”
</p>
<p>
Deshaun grunted and moaned between shallow, irregular breaths.
</p>
<p>
“Keep your feet up, Deshaun,” said Sergey’s deep, resonant voice. “You lose a lot of blood already. Foot is a bad place to get shot. Blood gushes out like from faucet. Now hold on, I tie my belt around the leg, make less blood flow, okay?”
</p>
<p>
Deshaun’s voice said through gritted teeth, “Am I gonna walk, boss?”
</p>
<p>
Sergey responded, “Let’s make sure you not to go into shock first, then we worry about you dancing ballet with Rosie someday in a future. We need get you to doctor, but we can’t start Eugene’s car. We take yours. You have keys? Is it close?”
</p>
<p>
“Yeah. It’s around the corner,” said Deshaun. Car keys jingled as they came out from the wounded African-American’s pocket.
</p>
<p>
Sergey instructed, “Zhenya, stay here with him, keep his feet up. I go get his car.”
</p>
<p>
“Bad idea, Seryozha,” said Eugene tensely. “You bring that ride here, it’ll get zapped by that fucking electric gun.”
</p>
<p>
“Alright, then help me carry him,” said Sergey.
</p>
<p>
“What? And let those two guys get away?” Eugene protested. “They’re in there right now! How about just we go in, take care of them, <em>then</em> we go fix Deshaun.”
</p>
<p>
“We <em>not</em> rushing in there, Zhenka!” Sergey insisted. “They could be armed, plotting ambush. Or they set up booby traps with bottles of chemicals. Zhenya … God forbid anything happen to you like what happen to Rex…”
</p>
<p>
The two men talked briefly in Russian, the thick Slavic syllables rolling fluently off their tongues. The discussion ended with a few grunts as Sergey helped the injured black man balance on his remaining foot. The two of them coordinated a hurried three-legged walk down the alley. Deshaun groaned out words of gratitude through gritted teeth.
</p>
<p>
As for Eugene, the silhouette of his leather-jacket-clad body, crouching with gun in hand, reappeared in the doorway downstairs. He carefully scanned the reeking slosh-covered factory room, eyeing potential hiding places amongst the packing materials and bullet-riddled equipment, and said tauntingly, “Come out, come out, wherever you are!” 
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">There was just barely enough room under the desk</span> in the office for both Danny and Jason to huddle together, terrified. They could hear the Russian slowly stalking the room below. His cautious exploration would lead him to the office in due time.
</p>
<p>
Danny eyed the front door with bitter frustration. It was only a few feet away, but there was no way to open it and get down the stairs without being seen or heard. The athletic mobster would gun them down in the alley before they could reach the SUV. Alone and in peak condition, Danny might have been able to make a dash for it, but Jason would stand no chance. And between the blood loss, the sleep deprivation, and the noxious fumes that filled the room, Danny could barely blink without passing out from exertion.
</p>
<p>
If they could just buy a few seconds to make it to the car… 
</p>
<p>
Jason pressed up next to him under the desk, a sad and empty expression on his visibly nauseous face. Jason’s hand rested on Danny’s arm and his head lay limply against his shoulder. It was an uncomfortably intimate position, and it gave Danny the same sense of unwelcome affection as when Jason had put his arm around him in the SUV parked across the street from Tungsten earlier that night. But under the circumstances, Danny didn’t begrudge the man for wanting to feel a little bit of human closeness.
</p>
<p>
As softly as he could, he whispered, “Jason, I’m sorry I can’t get us out of this.”
</p>
<p>
Jason whispered back, “I’m sorry I got you into this.” He gave Danny’s arm a squeeze through the floral-print sweatshirt. The shirt was still doused with kerosene, and the squeeze felt spongy.
</p>
<p>
Downstairs, the Russian’s footsteps squished against a sheet of cardboard soaked in the reeking slurry.
</p>
<p>
Danny’s eyes went wide. He suddenly gasped.
</p>
<p>
“Are you alright?” Jason asked in hushed tones.
</p>
<p>
“Jason! What are the chemical formulas for kerosene and acetone?”
</p>
<p>
Jason blinked at him. “How would that help?”
</p>
<p>
“I need a bond energy table. Fuck. Last time I did any chemistry was my chip fabrication class in college…”
</p>
<p>
“What are you talking about?” Jason asked.
</p>
<p>
“I’m thinking,” Danny replied, “that the floor downstairs is soaked with chemicals. And I don’t know the formulas or the principles or the math, but I do know there’s one thing those substances have in common.”
</p>
<p>
“What’s that?” asked Jason.
</p>
<p>
“They’re flammable.”
</p>
<p>
Jason stared at him nervously.
</p>
<p>
Danny reached his hand over the top of the desk and groped around blindly for a moment. “Jason, you don’t have a lighter, do you?”
</p>
<p>
Jason shook his head. “I don’t. Danny, are you nuts? If you light a fire, this place could blow to pieces &mdash; and us with it.”
</p>
<p>
“Nah. Don’t be silly,” said Danny. “Flammable doesn’t mean explosive. Those barrels down there didn’t go boom when they were shot, did they? Obviously the whole big-ball-of-fire thing you see in movies doesn’t really happen. I won’t make an explosion, just a wall of flame that the guy won’t want to run through.” He drew his hand back down from the top of the desk. “Fuck! These guys sell cocaine for a living but apparently they’re too straight-edge to smoke.”
</p>
<p>
Jason looked at him hesitantly. “It’s okay, Danny. It was a good idea. Nobody can ever say you weren’t resourceful right up until the end.”
</p>
<p>
“Fuck the end,” said Danny. “I’m not done yet.”
</p>
<p>
He looked around. There was nothing within arm’s reach but shards of broken glass. And his HERF gun.
</p>
<p>
His HERF gun, with its 3-megawatt S-band magnetron powered by pulsed electrical discharge from a 600-farad ultracapacitor bank.
</p>
<p>
Working as quietly as possible, Danny carefully unscrewed the magnetron horn. Multiple pairs of thick red and black cables protruded from the back of the megaphone-like component. He picked up a particularly sharp piece of broken glass and used it to pry the epoxy insulation away from one of the magnetron’s power cable pairs. At some point, the shard of glass painlessly sliced his palm open. He found himself leaving crimson fingerprints all over the magnetron horn.
</p>
<p>
From the factory below, the sound of rustling steadily drew closer.
</p>
<p>
He cut one pair of cables free, and put them in his mouth one at a time to strip away the insulation with his teeth. He took each exposed, frayed metal tip between his fingers and twisted it into a fine point. When he was done, he tied the two wires to the end of the PVC pipe, leaving a quarter-inch gap between the exposed silvery ends.
</p>
<p>
Danny frowned at the contraption. “What do you think?” he asked Jason.
</p>
<p>
“What’d you make?” Jason returned.
</p>
<p>
“The world’s most overpowered barbecue lighter,” Danny replied. He flipped a switch on the power supply box. Tiny lights awoke. “Assuming it works. We don’t have time to test it. It takes about thirty seconds to recharge. I don’t want to risk it. Now, help me find something to ignite…”
</p>
<p>
Jason reached his hand over the top of the desk and pulled down a loose sheet of paper, careful to keep it from making too much rustling noise.
</p>
<p>
Danny shook his head. “I need something with more heat capacity. Something that will stay burning long enough to raise the temperature to its flash point. There’s got to be something here we can use… Something that will hold a decent flame…”
</p>
<p>
Jason looked at Danny and said pointedly, “Danny…”
</p>
<p>
“Yeah?”
</p>
<p>
“Take your shirt off.”
</p>
<p>
Danny looked at him, perplexed. “What?”
</p>
<p>
“Your shirt. It’s soaking wet.”
</p>
<p>
“Yeah, it’s pretty uncomfortable,” said Danny, “but that’s the least of my… Oh!”
</p>
<p>
Danny wriggled awkwardly in the cramped space, trying to extricate himself from the oversized sweatshirt without bumping an elbow against the underside of the desk. His injured shoulder was swollen beneath its taped gauze dressing, and it hurt to move. The wrestling match with the kerosene-soaked fabric seemed interminable, but Danny ultimately prevailed over his floral-print opponent. He pulled the damp cotton slowly and silently away from his head until it came loose, and placed it down as a bundled wad on the linoleum floor.
</p>
<p>
He lifted the modified HERF gun and placed its tip, with the two exposed ends of wire, against the flammable cotton heap. After giving the circuitry one last visual inspection, he pulled the trigger.
</p>
<p>
Along the top of the PVC tube, the stegosaurus-like spine of small translucent plastic boxes clicked as the relays all closed their contact arms in unison. The eight-pack of baby blue ultracapacitors discharged, sending their stockpile of pent-up electrical energy shooting through a flyback transformer and down the cable.
</p>
<p>
The gap between the exposed wires flashed with a bright blue spark &mdash; accompanied by a cracking, zapping buzz.
</p>
<p>
Danny cursed himself for forgetting one key characteristic of pulsed-current open-air spark gaps: they’re <em>loud</em>. 
</p>
<p>
Eugene responded to the noise by firing his handgun. It was much louder. 
</p>
<p>
Bullets whizzed in through the shot-out windows, slamming into the opposite wall of the office. A few plinked against the exterior of the office itself, forming fresh dimples in the metal wall. Running footsteps filled the gaps between the shots.
</p>
<p>
The sweatshirt lit up in a bright orange flame. It burned with a disturbing ferocity in the fume-laden air.
</p>
<p>
Danny spun out from under the desk and, keeping his head down, extended an arm to help hoist Jason out behind him. The overweight man grunted and rose to his feet, crouching as low as his aging knees and spine would allow.
</p>
<p>
“Go!” Danny hissed, pushing him toward the front door. 
</p>
<p>
“He’ll follow us into the alley,” said Jason with a gulp.
</p>
<p>
“I’ll cut him off,” Danny insisted. “Now go!”
</p>
<p>
Still crouching, Jason quickly made his way to the door and reached up to click the locks open. 
</p>
<p>
More bullets zoomed through the broken windows. Jason flung the front door open, sending a rush of air inward. His heavy footsteps pounded down the iron stairs outside.
</p>
<p>
In the factory below, Eugene began to sprint toward the loading doors. Equipment crashed around him as he shoved it aside. His feet splashed in chemical puddles.
</p>
<p>
On the office floor, the sweatshirt burned fiercely, leaping to life with added vigor the moment Jason opened the door. Thin tongues of flame vaulted into the air. Glowing orange specks of burning thread wafted upward on the thermal draft, fading into ashes before floating back down to the floor.
</p>
<p>
He reached down. In one hand he grabbed his HERF gun. In the other he grabbed the fiery sweatshirt, burning his palm. Before the pain could distract him, he hurled the fireball through the broken window down into the factory, and leaped for the door. 
</p>
<p>
In three sprinting steps he reached the exterior landing, gasping to draw the clean outdoor air into lungs. He grabbed the railing and ran down the stairs without looking back. 
</p>
<p>
Danny had pointed out to Jason that the barrels of kerosene below didn’t explode when shot. He had said that “the whole big-ball-of-fire thing” only happens in movies. He had said he would only make a flaming barricade rather than an explosion.
</p>
<p>
He was wrong.
</p>

<hr/>

<p>
The entire factory was ablaze before the burning sweatshirt even touched the floor. The volatile vapors of acetone flashed first, sending an ignition wave racing out to the corners of the room. The kerosene, harder to light but burning hotter, erupted milliseconds later. The Styrofoam and cardboard followed, lifting dirty, noxious residue into the air as they combusted. In a blink, the small factory transformed into a roaring inferno.
</p>
<p>
Danny had failed to account for a key difference between the kerosene drum and the fume-filled room: the presence of oxygen.
</p>
<p>
He had just barely cleared the landing when the wave of heat blasted out from the door behind him, carrying glowing embers and ash amidst arcs of orange flame. 
</p>
<p>
Below, the loading doors swung fully open on their hinges and slammed against the side of the building, an enormous spout of fire shoving them apart in one thrust like a great demonic hand. 
</p>
<p>
And within that glowing spout of red fire was the black silhouette of Eugene.
</p>
<p>
The Russian had been mere steps from the loading doors when the room erupted. The wave of overpressure hit him in the back like a charging bull. He fell halfway out of the doorway, landing hard against the asphalt street. 
</p>
<p>
Eugene maintained enough presence of mind to keep his face down as gusts of flame billowed above him. The Russian crawled on his belly toward his BMW for cover. The small coupe was getting coated with soot.
</p>
<p>
An alarm wailed inside the building. Water gushed from sprinklers in the factory’s high ceiling. White mist poured out into the alley alongside the red flames and black smoke. Streams trickled to the street from the factory floor, drawing streaked wet lines through the trail of blood that ran to Julie’s pale, lifeless body on the asphalt outside.
</p>
<p>
Danny raced down the stairs with his butchered HERF gun. As soon as he cleared the last stair and hit the pavement, he bounded toward the SUV. He hoped to see Jason in the driver’s seat, starting the engine.
</p>
<p>
Instead, Jason stood despondently next to the Navigator, looking down. All four tires had been shot out. Jason turned to Danny with an expression combining panic and nausea.
</p>
<p>
On the ground outside the factory, on the opposite side of the parked BMW, Eugene rolled frantically to extinguish himself. The Italian lambskin material of his jacket melted off in rivulets from his sides and sleeves.
</p>
<p>
Danny scanned the alley, lit with the orange glow of the blazing factory. A handful of other cars had parked there overnight, spread far apart and separated by dumpsters and stacks of wooden pallets. 
</p>
<p>
One of the cars was a red Ford F-150. Its rear bumper and window were covered with stickers of Seattle grunge and metal bands &mdash; logos of Nirvana, Pearl Jam, Soundgarden, Queensrÿche, and Alice in Chains. 
</p>
<p>
Danny felt in his pocket, and pulled out the keychain he had lifted from Rex’s body &mdash; the one with the Ford car remote and the Kurt Cobain plushie.
</p>
<p>
He tried a button on the remote. The taillights of the red Ford blinked a greeting.
</p>
<p>
Jason and Danny wasted no time in getting to the late Rex’s pickup truck. The two men scrambled into the Ford. Force of habit drove Danny to the passenger’s side, and he passed the keys to Jason. The moment he turned the key, the sound of the ignition was momentarily drowned out by the distorted chords of a grunge guitar riff that blasted out at jarring volumes. Danny switched off the stereo while Jason hit the gas.
</p>
<p>
Eugene climbed to his feet, covered in black soot. His jeans were charred, his hair and eyebrows were singed, and his jacket was unrecognizable. In the distance, at the end of the alley, he could see the car turning to the lanes of busy fulfillment houses, the two men inside escaping to populated safety. Eugene’s roars of anger echoed behind them.
</p>
</div>