<div class="chapsection">
<p>
<span class="caplead">Eternity passed between</span> when she pressed the button and when the lights came on. She stood nervously outside the door, sweeping her hair aside. In her hands were white plastic Rite Aid bags, which she held in front of her like a flower girl with a basket of petals.
</p>
<p>
Finally, she heard shambling inside the house. She wiggled her waist for poise, and gave a sharp exhale to regain composure. She wished she’d had more time to fix her makeup, but the rush-job she had done in the rear-view mirror would have to suffice.
</p>
<p>
The doorknob turned. She was greeted by a geeky zombie in slippers and blue linen pajamas. Danny stared at her bleary-eyed. “Tina?” he said.
</p>
<p>
She looked up at him apologetically. “I totally woke you up, didn’t I? I’m so sorry… I knew you’d probably be asleep…” Her voice came out thin and weak.
</p>
<p>
Danny stared at her with utter confusion, then attempted a smile. Instead, his face winced with exhaustion. “It’s okay. Come on in.”
</p>
<p>
The soles of her black low-heel pumps tapped softly against the tile of Danny’s foyer. Tina looked around, delighted to see a civilized, ordered abode. She’d been worried that Danny’s place might look like Roger’s, a mess of laptops, laundry, and KidRobot dolls. And Natalie’s, of course, was even worse. Tina desperately needed a sense of order right now, and Danny’s house looked refreshingly sane. It was clean, uncluttered &mdash; and had a seriously sick entertainment system.
</p>
<p>
Danny wordlessly took the bags from her and carried them to the granite kitchen counter, then mindlessly began shuffling back to the bedroom. After a few short steps, he stopped, blinked a few times, turned to her and said, “So… uh… what brings you by?”
</p>
<p>
“Well, I… I know this is kind of coming out of nowhere, but could I… Would you mind if I crashed here tonight?”
</p>
<p>
Danny blinked at her uncomprehendingly, and yawned.
</p>
<p>
She looked away. “I’m sorry, I shouldn’t have come,” she said, trying to keep her voice from cracking. “It’s two thirty in the morning… I totally don’t mean to impose, I’m…” She noticed that her hands were wringing as she talked.
</p>
<p>
“Don’t worry about it,” Danny said. “Of course you can stay. But, why…?”
</p>
<p>
“Thank you. Thank you so much. I hate being any trouble. It’s just that… I’m… I’m really scared to go home…” Her lips began to tremble. She put her hands near her face to hide her mouth. She felt like a tiny, helpless creature, and she hated it. “The Russians know everything about me. They know where I live. And I just keep thinking, I’m going to walk into my place and there’s going to be someone there. In my apartment. Waiting for me…” Tina couldn’t contain her distress. She put her face in her hands and began to sob into her palms. She huddled away from Danny, feeling pathetic and ashamed.
</p>
<p>
Danny padded around the kitchen toward her. “Shhhh, it’s alright,” he said, his voice groggy but warm. “They won’t find you here. You’ll be okay.” He put a reassuring hand on her shoulder and spread his arms.
</p>
<p>
Eagerly she entered his embrace. She pressed her face and hands against his chest and cried into his pajamas like a terrified and hurt child. His arms wrapped protectively around her, and he bowed his head to rest his cheek against her hair. The pressure of his warm, dexterous hands against her back filled her with safety and peace. He was not especially muscular, but his long arms held her in a firm sanctuary. Her body melted against his. He smelled like Irish Spring and fresh linen, and felt like home.
</p>
<p>
When the last of her arrhythmic sobs shook out of her and her breathing regained its natural cadence, she gently pulled away from him. “Sorry about your PJs,” she said with an embarrassed smile as she batted at a snot-stain, her voice froggy.
</p>
<p>
He smiled at her warmly. “You want some, like, tea or anything?”
</p>
<p>
She nodded enthusiastically, and took a seat on a stool at the counter. He fished a kettle out of a cabinet filled with pots and pans, making plenty of clanking. As he filled the kettle in the sink, Tina noticed his new bandage. “What happened to your hand?” she asked.
</p>
<p>
“Fire,” he said absentmindedly. “Kerosene. Spark gap. Fumes. Boom. Everything burning. Also, I cut it on glass. Uh… oh yeah, your doctor friend isn’t gonna get her sweatshirt back.” He set the kettle on the electric stove.
</p>
<p>
Tina stared at him, at a loss for words.
</p>
<p>
He stopped his tea-making for a moment and said, “It’s been a long night.” After staring emptily at the floor for a few seconds, he asked her, “How did you get here, anyway?”
</p>
<p>
“Nat loaned me her car,” Tina replied. “Jason left her his contact info, and she texted him to get your address. He said he’d just dropped you off.”
</p>
<p>
Danny asked groggily, “Why not crash at your friend’s place?”
</p>
<p>
Tina shook her head. “I was going to, but then I realized they could find me there. I saw what you did with their phone &mdash; how you used the GPS history to figure out where they were keeping Julie. And I started thinking: they broke into my car, and my car has GPS, and have I ever GPSed my way to Nat’s house? I couldn’t remember. And the thought of them finding Nat, and thinking that my BFF could be in danger because of me…”
</p>
<p>
“It’s not because of you,” Danny reassured. “And it’s a long shot, anyway.”
</p>
<p>
“I know,” Tina said. “That’s what Nat told me, too. She said that blaming myself was just a defensive reflex of my ego trying to regain control. And that my paranoia was probably more harmful than any real danger. But I made her promise to stay at the hospital tonight regardless. She’s a doctor, so she gets to use these beds that the residents sometimes sleep on between shifts. Besides, she seemed perfectly happy to stay near Mike tonight. Those two were getting really cutesy together when I left.”
</p>
<p>
Danny smiled. “Glad <em>something</em> good can come from this night, I guess.”
</p>
<p>
“Did you find Julie?” Tina asked. 
</p>
<p>
Danny looked away. “She’s dead,” he said, just as the kettle whistled.
</p>
<p>
Danny poured cups for the two of them and joined her at the counter. There, in the calm stillness of his house in the painfully late hour, he recounted the events of the factory. He told her about what he’d learned from Julie &mdash; about the glutamine-eating cocaine-making <em>E. coli</em>. He told Tina about Julie’s acid attack, about the gunfight, about the loss of Julie and the vial, about his and Jason’s narrow escape. They sipped their tea, refilled their cups, and spoke.
</p>
<p>
And as he talked, Tina noticed him relax. While initially his muscles were tight and his speech was halting, the more he told her the more comfortable he seemed with what he was telling &mdash; the more he grew visibly at peace. As he finished his tale, he gave her a warm smile and said quietly, “Thank you for coming over tonight, Tina.”
</p>
<p>
She leaned closer to him. “I’m glad I did.”
</p>
<p>
“I think you’ll find,” he said sweetly, “that the sleeping arrangements here are quite comfy.” He hopped down from his stool and stood beside her. 
</p>
<p>
“Oh really?” she coyly replied. She looked up at him with eager, expectant eyes.
</p>
<p>
Danny reached out to touch her. She inched forward on her stool. His hand landed on her arm.
</p>
<p>
He gave her a quick pat and said, “Yeah, my guest sheets are, like, a million thread count! Here, I’ll be right back…” He rushed off to his bedroom, came out a few moments later carrying blankets and a pillow, and zoomed off to the living room to dress the couch.
</p>
<p>
He didn’t see Tina following him with her gaze, pouting with disappointment.
</p>
<p>
“Hey, Danny…” she said.
</p>
<p>
“Yah?” he called back from the living room.
</p>
<p>
“You know…” she said, “I didn’t come over here just to sleep…”
</p>
<p>
“Oh?” He trotted back to the kitchen.
</p>
<p>
She paused until he approached. Then, with a roll of her shoulders, she said in a girlish squeak, “I brought you something…”
</p>
<p>
He raised an eyebrow. “What kind of something?” 
</p>
<p>
The plastic bags lay at the end of the counter. Tina rifled through them, her teeth nibbling on her lower lip. She pulled out a latex glove. It was turned inside-out, and twisted and knotted near the base of the digits. “Do you remember,” she asked, “when we were back at the Rite Aid, when I first saw that the bacteria had formed a biofilm? Remember I scraped a bit of it out and held it with this glove?”
</p>
<p>
Danny nodded.
</p>
<p>
“Come take a look,” she said. She pinched a small segment of the inverted latex glove and stretched it against her fingers. Inside the glove, preserved in the latex, was a small crumb of yellowish crusty substance, barely a few millimeters wide.
</p>
<p>
“Holy shit…” Danny gasped.
</p>
<p>
“See?” said Tina. “I know you’re upset about losing the vial to the Russians. This should cheer you up.”
</p>
<p>
Danny nodded excitedly. “Is that one tiny flake enough to work with?”
</p>
<p>
“In theory it only takes one bacterium to grow an entire colony,” Tina answered.
</p>
<p>
“But are they still alive?” asked Danny. “And even if they are, can you wake them up from that filmy stasis mode without killing them?”
</p>
<p>
Tina flashed him an excited grin. “Let’s find out.” 
</p>
</div>
