<div class="chapsection">
<p>
<span class="caplead">
Clanging and clattering came from the cookware cabinet</span> as Danny dug around. He produced a two-gallon pot with lid.
</p>
<p>
“Here, wipe down the inside,” said Tina as she tossed him some alcohol wipes. She had arranged a row of bottles and bowls. The sleeves of her simple white button-down shirt were rolled up to her elbows, and her hands were wrapped in rubber gloves. “Fill the pot with hot water, and pre-heat the oven.”
</p>
<p>
Danny went to prepare the stove. Its clock read 2:17am.
</p>
<p>
His exhaustion felt like a lead shawl draped across his shoulders. He put the pot into the sink, leaning heavily against the counter. With unfocused vision, he watched the hot water rise against the steel. 
</p>
<p>
From behind him, Tina announced, “Incoming!” She glided in with a Pyrex bowl filled with a flour-like powder, which she poured into the pot.
</p>
<p>
She stood close enough for him to see the smudges on her face from hastily applied makeup, smell her floral perfume. He found himself subtly leaning into her. He wasn’t sure whether or not she caught him doing it; she simply kept standing there, stirring the pot as it filled, her eyes fixed downward to her task. He did notice, though, that her cheeks were rosy, and her lips were drawn up in a coquettish smile.
</p>
<p>
The water neared the brim. Tina shut off the tap, and silence abruptly filled the house. She stood motionless for a moment, her hand frozen on the water knob.
</p>
<p>
Danny looked down nervously at the pot.
</p>
<p>
Tina broke the stillness with a sharp inhale. “Okay, then.” She closed its lid, carried it to the stove, and loaded it into the oven.
</p>
<p>
With the water busy heating, Danny grabbed a seat at the counter. “So, what happens now?” he asked, resting his head limply on his hands.
</p>
<p>
“After the water boils, I’ll turn down the heat and let it simmer.” Tina came around and sat down beside him. “A real autoclave would suck out all the air and then blast it with pressurized steam for twenty minutes. But what we’re doing should be good enough.”
</p>
<p>
Danny folded his arms lazily on the countertop. He groggily said, “Cooooool,” before laying his head down and closing his eyes.
</p>
<p>
“Aww.” She reached out to touch his head. Her fingernails scratched lightly at his scalp. A contented purr escaped beneath his breath.
</p>
<p>
The oven clanked. Danny jumped alert.
</p>
<p>
Tina giggled. “It’s just the lid. The water’s starting to boil. We’ll give it another few minutes.”
</p>
<p>
“And then it’ll be sterile?”
</p>
<p>
She shook her head. “Not by a long shot. ‘Sterile’ literally means there’s nothing alive. There’s no way we’ll achieve that. The air, the water, the inside of the pot, it’s all teeming with life.”
</p>
<p>
“No, the water’s clean. It just came out of the sink.”
</p>
<p>
“Heh. Try looking at tap water under a microscope sometime,” Tina replied. “The hardest part will come afterwards. See, when we take the broth out of the oven, we’ll need to cool it down just the right amount. If we put the bacteria in when the water’s still boiling, it’ll kill them. But if we let it cool all the way down to room temperature, they won’t grow. We need to find a way to keep the broth just warm enough for incubation.”
</p>
<p>
Danny nodded. “And how warm is that?”
</p>
<p>
Tina walked over to the bags and pulled out the digital thermometer. “Body temperature. Ninety-eight point six. But keeping it there will be tricky. An electric stove’s lowest setting is around 200. We’d have to keep the pot on your range, and take shifts checking the thermometer, turning the heat on and off every few minutes. Unless you’ve got any other suggestions.”
</p>
<p>
“Build a nest and sit on it?”
</p>
<p>
Tina laughed. “That would get the job done.”
</p>
<p>
“I’ll bring you worms, and distract predators with my colorful feathers.” Danny yawned. After a moment of thought, he reached toward her and made grabby motions with his bandaged hand. “Let me see that thermometer…” He examined the small device. Through its translucent plastic shell, he could see a narrow green circuitboard behind the temperature readout screen. Danny hopped down from his stool and staggered toward his foyer.
</p>
<p>
“Ooh! You have a plan, don’t you?” Tina asked. 
</p>
<p>
He walked mechanically to the door leading out to his garage. Circuit schematics materialized in his head. In his mind’s eye appeared fine gray rectilinear diagrams of transistors, power supplies, crossovers… It was child’s play.
</p>
<p>
By the time Tina followed, he was already seated at his workbench. The thermometer was clamped into a vise beneath a table-mounted magnifying glass. He was slicing its translucent plastic shell with an X-ACTO knife.
</p>
<p>
“Can I watch?” she asked, and leaned over his shoulder.
</p>
<p>
He gently tapped the metal bulb at the tip of the thermometer with his blade. “See that? That’s the casing for a little thing called a ‘thermistor…’”
</p>
<p>
The thermometer’s shell split in half beneath his knife. The narrow end dangled by two thin orange wires, barely as thick as a hair. Working carefully under the magnifying glass, he severed the two wires, worked on their naked tips with a soldering iron, and attached them to extensions several feet long.
</p>
<p>
“Is that the temperature sensor?” asked Tina.
</p>
<p>
“Basically, yeah,” said Danny. “It’s made of temperature-sensitive ceramic. The warmer it gets, the more it impedes the flow of electricity. Thermal resistor, see? Here, hold this…”
</p>
<p>
He passed her the severed bottom of the thermometer.
</p>
<p>
When she took it delicately in her fingers, he pressed it into her palm. “No, like this…” He put his hands around hers and folded it around the sensor. “Warm it up…” 
</p>
<p>
He noticed himself lingering on her touch. Their eyes met. There was a long pause.
</p>
<p>
Tina said with a smile, “You know, it won’t reach body temperature in my hand.”
</p>
<p>
“It won’t?” Danny asked quietly.
</p>
<p>
“No chance,” she said. “It’s an oral thermometer.”
</p>
<p>
“Oh…” he murmured.
</p>
<p>
Their eyes still locked, she drew her hand away from his and turned the thermometer around in her fingers. Her lips parted. She slid it into her mouth, nestling the tip in the space beneath her tongue.
</p>
<p>
Danny found himself forgetting to breathe.
</p>
<p>
He abruptly stood up from the workbench and turned away. He stepped to a case of narrow shelves, each bearing plastic bins filled with assorted electronic components. “So anyway… It won’t need much… One transistor… A switching power supply… MOSFET… Relay… A rheostat for calibration…” He returned to the workbench with a handful of black and silver objects. He selected a breadboard, an index-card-sized rectangle of white plastic dotted with a grid of hundreds of tiny holes. Into two of the countless sockets, he inserted the loose ends of the long wires soldered to the thermistor, still hanging from Tina’s mouth as she stood there blinking. He then began drawing pieces from his pile of components and adding them to the breadboard. “There!”
</p>
<p>
Tina looked on. “Sho, umm… What’sh shish shing shupposhed to do?”
</p>
<p>
“It’s a thermostat. Watch. See this LED?” He pointed to a small glass bead. 
</p>
<p>
“Mm-hmm,” Tina replied.
</p>
<p>
“Pretend that’s a burner on my stove. Now, I’ve tuned the thermostat to your body heat. When the thermometer is at body temperature or higher, it’s turned off. But if it cools down…”
</p>
<p>
He reached toward her face. She puckered her lips. He pulled the dismantled thermometer from her mouth, possibly more slowly than necessary, and shook the moist tip through the air. The glass bead popped aglow with a bright green light.
</p>
<p>
Tina nodded. “So if you put the thermometer tip inside the pot, then it can turn the burner on and off automatically. Which will keep the broth at a steady temperature without us having to keep a vigil on it.”
</p>
<p>
“Bingo. Of course, I’ll seal the whole thing in epoxy resin to make it watertight, so the electronics won’t short out.”
</p>
<p>
Tina raised an eyebrow. “How’ll you connect this to your stove?”
</p>
<p>
“With this…!” Danny replied excitedly. He held up a blue plastic cube the size of his palm, studded with thick, stubby prongs. It looked similar to the ones on the back of the HERF gun that sat sipping power in the corner. “This is a power relay,” he explained as he attached wires between the breadboard and the cube. “It can switch ten amps of 220VAC on a two-amp 12VDC control current.”
</p>
<p>
Tina shrugged uncomprehendingly, but her eyes were gleaming. “I have to go check on the broth. Meet you in the kitchen?” He nodded, and she skipped away.
</p>
<p>
By the time Danny finished his makeshift thermostat, Tina had already taken the pot out of the oven. The kitchen sink was plugged and filled with a watery slurry of ice from the freezer. Tina held the hot vessel with oven mitts and gently rocked it in the ice bath.
</p>
<p>
Danny entered the kitchen wearing thick electrical gloves. He walked up to the stove and pulled. The stove slid out, scraping against the floor tiles, just far enough to expose the black cord that plugged it into the house’s 220VAC circuit. He pulled the plug out of the wall. The stove’s clock went dead. He then produced his X-ACTO knife and slashed open the stove’s power cable, sliding the blade slowly down the rubber insulation until he had formed a slit almost a foot long. Multicolored wires and metallic coating protruded from the gash.
</p>
<p>
“Is that safe?” Tina asked.
</p>
<p>
“Not in the slightest.” He severed and stripped one of the exposed wires, and spliced its ends with the power relay/ Gingerly, he plugged the appliance back into the wall. Much to his relief, nothing caught fire. The stove came back to life, its clock blinking 00:00.
</p>
<p>
“Not bad,” Tina said with a smirk. She lifted the two-gallon pot, and carried it to the stove.
</p>
<p>
Danny took off his electrical gloves and offered her the thermometer. “Shall we?”
</p>
<p>
She nodded, and with a deft, quick motion, she slid the lid aside just barely widely enough to accommodate Danny’s device. A warm, salty, sweet scent rose from the pot, organic yet pure. The thermometer made a soft plop as it entered the broth. Its wires protruded from the rim, preventing the lid from closing completely. Tina applied a generous coat of Saran Wrap to form an approximately airtight seal.
</p>
<p>
The power relay emitted a loud “<em>Click!</em>”, and the stove’s power cut out. Its clock showed a dead black face.
</p>
<p>
“Is it supposed to do that?” asked Tina.
</p>
<p>
“I think so,” said Danny. “The burner was on, right? So it was heating this whole time. Which means it’s supposed to turn off now to cool down a little. And then when it’s cool enough it’ll turn back on again.”
</p>
<p>
“So it’s working?” she asked.
</p>
<p>
Danny nodded.
</p>
<p>
 “So all that’s left,” said Tina, “is the…” 
</p>
<p>
They both turned their heads and stared at the white latex glove on the granite counter, inside-out, twisted and tied off.
</p>
<p>
Tina picked it up. She held one of the glove’s fingers pinched shut, and with a pair of scissors she cut the finger away. “You ready?”
</p>
<p>
Danny whispered thickly, “Let’s do it.”
</p>
<p>
Tina inhaled sharply and held her breath, her breasts stretching her white button-down shirt. 
</p>
<p>
She peeled back the plastic wrap and pushed the lid aside barely an inch, leaving a narrow crescent of broth momentarily exposed. With both gloved hands, she gently tapped the latex finger. The lone yellowish-white grain tumbled out. It alighted on the water’s surface like a flake of fish food.
</p>
<p>
Tina rapidly closed the cover and re-wrapped the plastic. She peeled off her gloves, and finally let herself exhale.
</p>
<p>
Danny stood beside her, both of them looking down at the two-gallon stainless steel pot. “What happens now?”
</p>
<p>
“Nothing,” Tina answered. 
</p>
<p>
“Nothing?”
</p>
<p>
“We wait for them to multiply,” Tina replied. She flexed her fingers, her black nail polish giving off a hint of iridescence as it caught the light. “They’ll fill the whole pot eventually.”
</p>
<p>
“How long will that take?”
</p>
<p>
Tina shrugged. “Depends on how well I prepped that broth. Maybe hours. Maybe a couple of days. Maybe weeks. It’s a big pot.”
</p>
<p>
“Hrmm. This thing could be on my stove for a couple of weeks?” 
</p>
<p>
“Yep,” she said, turning to face him with mischievous eyes. Her full, pink lips were stretched in an elfish smile. “Sucks to be you, doesn’t it?”
</p>
<p>
“Oh, in so many ways,” Danny said with a chuckle. If he wasn’t ready to pass out from exhaustion, it wouldn’t have been funny; he’d have begun mentally enumerating them all. He found, however, that being nervous or anxious required effort &mdash; the effort of visualizing failure. As the two of them stood beside the pot, Tina’s face inches from his own, he found that he could no longer expend the time and energy required to sabotage himself. Not at 00:00 in the morning.
</p>
<p>
“So…” said Tina.
</p>
<p>
“So,” said Danny, his eyes fixed on hers. “What’s left for us to do here?”
</p>
<p>
“I don’t know. You tell me.”
</p>
<p>
Beside the stove, the power relay brought the burner back to life with a loud, “<em>Click!</em>”
</p>
<p>
His hand shot toward her waist. He pulled her toward him and slid his other hand along the back of her head, his fingers running through that dark unkempt hair that he had wanted to touch since first seeing her on that hacked video feed earlier that night. His lips crashed upon hers like waves against a shore.
</p>
<p>
He didn’t think about brushing his tongue lightly against hers. He didn’t think about leading into a nibble of the lower lip. He didn’t think; he didn’t calculate or analyze or hypothesize. He simply did.
</p>
<p>
She squeezed her body against his, her breasts pressing against his ribs and her hips pushing against his pelvis. She could undoubtedly feel his desire for her. Her arms reached around him and her fingers splayed against his back, drawing him tightly to her.
</p>
<p>
The pressure of her hand hit his injured shoulder. A flash of searing pain jolted him out of the kiss. He pulled back and hissed harshly, his eyes wide and his senses suddenly heightened. The wound throbbed with his quickening pulse.
</p>
<p>
She drew her hands away and looked up at him apologetically.
</p>
<p>
His eyes gazed into hers with raw animal hunger. He grinned.
</p>
<p>
With a shove, he thrust her away from the stove with carefully guided force. Her back hit the refrigerator. 
</p>
<p>
He grabbed her dark hair and pulled her head to one side, exposing her neckline, and pressed his mouth vigorously against the side of her neck. His other hand cupped over her shirt and bra and massaged her breast.
</p>
<p>
She moaned deliciously into his ear. Her hand was in his hair, pulling his head down to increase the pressure on her neck, craving more. She raised one knee, her shoe against the refrigerator door, her thigh rubbing against his waist. Her hips ground against his.
</p>
<p>
As his mouth worked its way down from her ear to her collar, his hand began unbuttoning her white shirt. 
</p>
<p>
She ran her hand under his pajama shirt, her fingers tracing the contours of the muscles of his torso.
</p>
<p>
Her last button undone, Danny stepped back to admire the sight of this lithe young lady against his fridge, her white shirt hanging open and exposing her tan bra and toned midsection. He took a moment to consume her curving feminine form with his eyes as she remained pressed with her back against the fridge. Tina smirked libidinously for a moment, wiggling teasingly against the fridge, happy to let him enjoy the view.
</p>
<p>
She then kicked herself away from the fridge and reached out to grab him and yank him back to her by his pajama shirt, which she promptly pulled off of him. She flung it to the kitchen floor.
</p>
<p>
With both hands, he pulled her shirt off behind her, leaving the sleeves bunched at her wrists. She began to wriggle her hands to slide entirely free… but he didn’t want her to. Instead, he twisted the shirt tightly, trapping her hands behind her in its white fabric. Putting his other hand on her shoulder, he spun her around and pushed her against the fridge once more, pinning her face and chest against its door. While his one hand maintained the squeeze on the shirt bunched around her wrists to keep her hands immobile, his other deftly unhooked her bra, his agile fingers making quick work of the clasps. 
</p>
<p>
At last he released her wrists, tossing her white shirt mindlessly aside and dropping her tan bra to the floor. With his body he kept her pinned against the refrigerator door, his naked torso pressing hungrily against the warm, supple skin of her back. She pressed one of her newly freed arms against the refrigerator, the palm flat against the door. The other reached up and back, her black-painted fingers clutching his head.  
</p>
<p>
His arms wrapped around to her front. One hand climbed upward to massage and caress her naked breast, molding around its soft round form. He gently pinched her nipple between two fingers, eliciting moans of delight from her parted lips.
</p>
<p>
His other hand reached around the curve of her hip and climbed downward, past her abdomen, past her navel. He unthreaded her belt from its loops. Pulled it away from the buckle. Slid it open, letting its leather ends dangle aside. Nimbly unbuttoned her black slacks. Drew down the zipper. He took his time, enjoying hearing her gasp. 
</p>
<p>
His fingers first stroked teasingly outside her panties, indulging in the slickness of her hot, moist passion. He kept his ministrations on the outside of the thin fabric until her face contorted in agony; then he finally granted her the relief of feeling him touch her with his bare fingers. He rubbed and stroked with a steady, pulse-like rhythm, matching his motions to the pace of her breathing. He keenly watched her face, relishing her pleasure.
</p>
<p>
The subtle rocking of her hips progressively accelerated. Her panting breaths rose to gasps. Her moans began to crescendo into cries.
</p>
<p>
Finally, when she seemed to approach the threshold of exploding, she suddenly pushed him violently away with both hands. She turned to face him, topless in her black slacks and low-heel pumps, and tilted her head slightly downward to look up at him with voracious eyes. Her face was flush, glowing with carnal cravings. She leaped to him like an untamed beast, a wildcat ready to devour a helpless prey. Her hand ran claw-like down his front, leaving a long trail in his skin from his chest to his abdomen. 
</p>
<p>
He gave the kitchen a quick, determined scan. The counter looked like it was about the right height. With a sweep of his arm, groceries tumbled from the granite countertop and crashed onto the floor.
</p>
<p>
Tina hopped over to him, half-tripping, kicking off her shoes and pulling off her socks as she went. She gave him an eager kiss, then excitedly hopped up onto the counter. 
</p>
<p>
Danny pulled her slacks and panties down to her ankles, relishing the sight and sensation. 
</p>
<p>
With her butt on the countertop, in a flurry of leggy motion, she kicked the black slacks and panties away.
</p>
<p>
They landed on the kitchen floor, beside the bunched-up white shirt, beside the bra, beside the pajamas and the slippers and the shoes and socks that lay strewn across the tile. Beside the pile of groceries and improvised biotechnology equipment that now littered the floor. Beside the breadboard and the power relay and the wires that ran behind the stove and up to the stainless steel pot.
</p>
<p>
Within the broth, the microscopic <em>E. coli</em> felt the warmth and moisture around them, and slowly awoke from their slumber. Mindless and hungry, they eagerly began partaking of the bountiful feast, ready to explore the vast new frontiers of this nutrient-filled vessel. 
</p>
<p>
And on the countertop, the two lovers partook just as eagerly of one another. There was no boundary between the joys of their mutual intellectual achievement and their mutual physical pleasure. There was no separation between ecstasy of the mind, ecstasy of the body, and ecstasy of the soul. Their worlds &mdash; his of electronics and hers of biology, his of the mechanical and hers of the organic, his of the wizardly material and hers of the mystic divine &mdash; their passions, like their bodies, were made to be united. 
</p>
</div>