<div class="chapsection">
<p>
<span class="caplead">The morning sun shone</span> through Venetian blinds, casting long parallel lines of orange light upon a disheveled bed. The stripes of daylight highlighted the contours of the blanket in sharp relief, tracing out the lithe, slim bodies of sleeping lovers that lay beneath. A pillow supported the slender arm of a young woman, her French-manicured hand dangling over the edge, the crook of her elbow nestling a head that sported tussled locks of blond hair. 
</p>
<p>
On the red brick walls, the morning light drew horizontal ribbons through a <em>TRON: Legacy</em> poster, a stolen “No U Turn” sign, and a shelf filled with toys &mdash; magnetic Buckyballs, a metal Slinky, and a menagerie of vinyl dolls all bearing the bubbly round creepy-cute look of designer KidRobot figurines.
</p>
<p>
From the floor somewhere near the bed, beneath a giant tangled mess of laptops, headphones, and dirty laundry, there came a faint blue glow, accompanied by an insistent buzzing. 
</p>
<p>
The blankets shuffled. From their depths arose an annoyed groan. They parted, and a long, sinewy male arm emerged, sporting Celtic sleeve tattoos. Its hand groped the floor blindly until it found the source of the noise, a ringing cellphone. It whisked the phone up and held it before the sleep-matted face of a young man with black, spiky hair.
</p>
<p>
The screen glowed with the words, “<span class="computer">Dr. P</span>”.
</p>
<p>
Roger rolled his eyes. “Go away,” he mumbled softly, and pressed “<span class="computer">Ignore</span>”. He casually dropped the phone back to the floor.
</p>
<p>
By his side, the blonde stirred. Her petite form shifted slightly, her face lifting up out of the crook of her elbow. She was turned away from him, her small naked shoulders bearing hickeys and bite-marks. Roger followed the curve of her supple spine with his gaze, moving the blanket away from the enchanting dip of her waist where it occluded his view. Below her flowery tramp-stamp, her perfect young ass, round and tight and luscious, sported a distinct rosy hand-shaped welt. Grinning smugly, Roger slowly traced his fingers across her toned midsection and up toward her chest to fondle a pert, firm breast. 
</p>
<p>
Her face turned lazily toward him with a wide, sleepy smile on her bright pink lips. She writhed softly for a moment to uncurl herself from her sleeping position, and reached her arms high over her head in a wide, waking stretch. Her big, innocent eyes fluttered open and groggily came to focus on him. “Mmmm… Good morning.”
</p>
<p>
Roger moved his head down to flick her nipple with his tongue.
</p>
<p>
The girl’s fingers ran along his shoulder and down his chest, and she rolled to press gently against him with the full length of her feather-soft body. Roger grabbed her head in both hands and kissed her hard. She rubbed her thigh against his hip, her instep brushing against his calf. He shifted his weight, ready to climb on top of her.
</p>
<p>
The buzzing burst out once more.
</p>
<p>
“Fuuuuu<em>uuuuuck</em>!” Roger reluctantly rolled himself off the gorgeous blonde and peered over the edge of the bed, looking for his cellphone. He pressed “<span class="computer">Answer</span>”. “What’s up, Doc?” he said groggily into the phone.
</p>
<p>
The old Russian scientist’s voice rattled from the speaker.
</p>
<p>
Roger replied, “I was going to be in at 9:30, like usual. It’s barely eight o’clock. What’s going on?”
</p>
<p>
The phone mumbled something.
</p>
<p>
“Tina?” Roger asked. “No, I haven’t seen her since work yesterday. Why?”
</p>
<p>
More Russian-accented mumbling.
</p>
<p>
Roger’s entire body suddenly went tense. “What? What do you mean, ‘break-in’?” He reached for the blanket and pulled it around himself absentmindedly, quickly losing his arousal. The girl looked on uncertainly.
</p>
<p>
Passinsky’s gruff voice murmured a few sentences.
</p>
<p>
Roger bolted upright. “Whoa! Whoa, Doctor P., slow down… What happened?”
</p>
<p>
The old Russian’s voice continued. 
</p>
<p>
With his free hand, Roger fumbled around on the floor by the bed. “Hold on, Doc. Let me get you on my Bluetooth…” He found his headset scattered somewhere in the tangled mess of wires, and popped it in his ear. From the floor by the bed, he pulled out a spare pair of glasses with one hand and a laptop with the other. He wrapped himself in the blanket, sat cross-legged on the bed, and began typing.
</p>
<p>
The girl pawed at him. “Is everything okay?”
</p>
<p>
He batted her away. “Not now, Carrie.”
</p>
<p>
“My name’s Kelly!”
</p>
<p>
Staring at the screen, he said into the headset, “Okay, the DenyHosts log does say that someone was trying to hack in yesterday, but the attempt failed. The keycard server shows activity last night by… Julie? And… Fuck! The cameras!” He slapped his laptop closed, and shot up from the bed to dig through the piles of clothes on his floor. “Doctor P., I’m on my way.” A quick tap to the earpiece ended the conversation. Roger gave himself a rub of deodorant and a quick spray of Axe, and wiggled into boxers and a t-shirt.
</p>
<p>
The girl sat on the bed, putting on her bra and scanning the small studio apartment for the rest of her clothes. “What’s going on?”
</p>
<p>
“You should get going,” said Roger without looking at her. His motorcycle jacket lay slung over a chair near his helmet and boots. He began to climb into his riding gear.
</p>
<p>
“Can you give me a ride to class?”
</p>
<p>
Roger zipped up his jacket and, holding his helmet under one arm, headed back to the bed. He gave her a quick meaningless kiss, and fished his wallet out of his pants.
</p>
<p>
“Here,” he said, and slipped her a twenty.
</p>
<p>
She stared at the bill. “What the hell is this?” 
</p>
<p>
“Cab fare,” Roger answered, and headed for the door. 
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Scientists scurried through</span> the battle-scarred hallways, checking on their projects and assessing damage to their equipment. Tina’s green Volkswagon Jetta was still in the parking lot outside, its windows smashed and its glove compartment ransacked. The reception desk had been overturned, the stockroom had sustained a rampage, and bullet holes pocked the gypsum walls everywhere. A few bloody streaks on the walls and carpet had left crusty reddish-brown stains. Roger had walked through the building feeling like he was watching a documentary about Sarajevo or Fallujah. The sensation didn’t seem real.
</p>
<p>
The scientists were mostly men and women in their forties and fifties, each with multiple technical degrees. Their educated, scrutinizing faces reacted with confusion and outrage at the idea of their ivory tower of research being defiled by such real-world vulgarities as physical violence. He was surprised to see so many of the researchers at such an early hour &mdash; apparently Doctor P., usually the first to arrive in the office anyway, had spent most of the morning on the phone.
</p>
<p>
Doctor P. was still on that phone. The two of them sat alone in Passinsky’s office, where Roger had access to the DVR that recorded the camera feeds. As Roger sat in Passinsky’s chair and operated his computer, Passinsky himself remained standing, speaking rapidly into his cellphone in Russian. Finally Passinsky hung up and turned to Roger. “So what do you think?” 
</p>
<p>
“I’m still trying to wrap my brain around this, Dr. P.,” Roger replied. He played back feeds from several of the cameras, showing a large, burly man with a lug wrench being chased through the hallways by an agile gunman with a long black suppressor on his firearm. 
</p>
<p>
“Yes,” said Passinsky. “You see how the cameras move? The cameras are doing their… Their moving functions…”
</p>
<p>
“Pan, tilt, zoom,” Roger filled in.
</p>
<p>
“Yes,” said Passinsky. “They are pan-tilt-zooming to follow the two men. They stay on them the whole time. Now, this is not the automatic capability of the systems, correct?”
</p>
<p>
“No, it’s not,” Roger answered. “Somebody was controlling them.”
</p>
<p>
“So somebody hacked in and took the cameras over,” said Passinsky.
</p>
<p>
“The cameras are probably <em>how</em> they hacked in,” Roger grumbled with an edge of accusation. “I told you they’re way out of date. I told you we needed to shell out and replace them all. But you… didn’t…” He turned to look at Doctor P.’s face. The old man’s cold blue eyes looked like they were about to shoot beams of frost straight into Roger’s heart and suck out his warm blood by gaze alone. Roger gulped. “So, um, anyway… There was clearly a fight between two teams of people here. One team had the guns and the other had control of our computers.”
</p>
<p>
Passinsky watched the screen. “Different approaches, different tactics, different strengths and weaknesses. But one common objective, yes?”
</p>
<p>
“I think so. Check it out…” Roger queued up a video of Tina being held at gunpoint in the cold storage room. The footage showed her pulling a small vial out of a box from the deep-freezer and handing it to the leather-clad gunman. “See, they get this test tube from the fridge, and then later they start fighting over it in the hallway…”
</p>
<p>
“Wait, pause,” Passinsky ordered. “Enhance the image.”
</p>
<p>
“Uh, what?” said Roger.
</p>
<p>
“Make the picture more clear,” said the old scientist.
</p>
<p>
Roger paused. “You mean like in bad spy movies?”
</p>
<p>
Passinsky missed a beat. “Yes. Why? Isn’t that…”
</p>
<p>
“You know that’s not actually a thing, right?” said Roger.
</p>
<p>
“I do not know exactly how it is work,” Passinsky insisted, “but I know there is software for pixel interpolation and increase in the sharpness based on estimating focal length…”
</p>
<p>
Roger gave him a sour look.
</p>
<p>
“No?” said Passinsky.
</p>
<p>
Roger shook his head. “I can make it full-screen for you, though.”
</p>
<p>
“Fine,” said the old scientist. He squinted and leaned closer into the screen, donning a thick pair of reading glasses to help him see. When the image filled the screen, Passinsky gasped. It sounded like a wet rattle. “That man…”
</p>
<p>
“The one attacking T?” asked Roger.
</p>
<p>
“Yes…” Passinsky said, trailing off, staring at the looping video. “I think… Roger, pause. Go frame by frame. That <em>is</em> a thing, yes?”
</p>
<p>
“Yeah, <em>that</em> is,” said Roger.  
</p>
<p>
Passinsky’s eyes suddenly looked very, very tired. “Oh no…” Passinsky walked away from the desk, rubbing his temples with his fingers. “That is the Mukhayev boy…”
</p>
<p>
“Who?” Roger asked.
</p>
<p>
Passinsky shooed him into silence with a flick of his wrist. Still standing, he leaned heavily on his desk with one arm, his elderly form slack and bony. With his other hand, he dialed his phone.
</p>
<p>
“Are you finally calling the cops?” Roger asked insistently.
</p>
<p>
Passinsky shook his head. “No police. Not yet. Not until my boss gives permission.” He looked away, and spoke in Russian into the phone, his voice apologetic and obsequious. His face, which Roger had only ever seen as an icy mask, sagged with worry.
</p>
<p>
While Passinsky spoke into the phone, Roger spent the time watching the recordings on the DVR. One of the men carried an odd machine, a seemingly homemade contraption about four feet long and held together by Velcro and karabiners. Roger searched the footage to get views of the device from different angles. It looked like some kind of art project gone horribly wrong, or a science fair project gone horribly right &mdash; like Nikola Tesla had gotten high and asked Jules Verne to drive him to the nearest Home Depot.
</p>
<p>
After several minutes, the grizzly scientist hung up. “Roger,” he rasped. “Do we know <em>anything</em> about the hackers?”
</p>
<p>
“Not a thing,” Roger replied. “The security cams don’t record audio so I can’t hear anything they’re saying. The parking lot feeds show they were in a black Lincoln Navigator, but I can’t get a good shot of the license plate &mdash; I think they were intentionally keeping it out of frame. And there’s nothing in any of the system logs that would give me any clue.”
</p>
<p>
Passinsky came around to look at the screen again. It was playing a clip of the fight in the hallway outside the freezer room. On the screen, a geeky guy in an ill-fitting lab coat argued tensely with the leather-clad gunman, aiming the odd contraption at him. Tina stood by his side, and the large scruffy man lurked in the shadows. Passinsky said, “That machine he is carrying…”
</p>
<p>
Roger nodded vigorously. “I was just looking at that, Doctor P.”
</p>
<p>
“He holds it like rifle,” said the scientist. “What does it do?”
</p>
<p>
“I’m just figuring that out,” said Roger, and he queued up a video clip. “Check this out. Here he is, firing it in the middle of this fight. The guy in the leather jacket is just about to beat the shit out of this big hairy dude, when the guy holds up this doohickey, and… Bam. Guy in the leather jacket grabs his ear.”
</p>
<p>
“Did he shoot something at his head?” asked Passinsky.
</p>
<p>
“At first, I thought that too” said Roger. “I figured maybe it’s some kind of homemade gun. But then, why all the electronic parts? So I went and looked for other times he fired that thing, and I saw this…”
</p>
<p>
The screen ran a clip of the other gunman, the one with the long black suppressor on his semi-automatic pistol, trapped in the stockroom. He lifted a keycard to the reader, when suddenly it appeared to jump from his hand. After picking it up and attempting to wave it again, the card appeared to be broken and useless.
</p>
<p>
“And then I found this…”
</p>
<p>
Roger queued a video segment from the parking lot, where the gunman with the silencer talked reluctantly to the driver of the Lincoln Navigator, visible only as a silhouette in the driver’s side window. He focused on his cellphone while, behind him, the large scruffy man snuck into the building. The gunman turned his head and spotted the large one, and suddenly dropped his cellphone. Stepping frame by frame, Roger saw white sparks erupt from the phone, silent and pixilated in the digital recording.
</p>
<p>
Roger concluded, “And then I was like, ‘Holy fucking shit!’”
</p>
<p>
Passinsky shook his head. “I do not follow.”
</p>
<p>
Roger explained, “Okay, it’s like, you know how in StarCraft, the Ghost unit can shoot an EMP shockwave that knocks out Protoss shields?”
</p>
<p>
Passinsky stared at him blankly.
</p>
<p>
“And there’s this old game called System Shock 2,” Roger continued, “that has an electromagnetic pulse rifle. You shoot it at robots and cyborgs, it fries their circuitry and kills them instantly. But it doesn’t hurt humans. Only things with a microchip.”
</p>
<p>
Passinsky didn’t stir. “An electromagnetic pulse rifle?”
</p>
<p>
“Yes!” said Roger. “An EMP or Magpulse gun.”
</p>
<p>
Passinsky raised his large gray eyebrows. “For shooting robots and ‘cyborgs’ in computer game?”
</p>
<p>
“Well, yeah,” said Roger, a little sheepish but nonetheless thrilled. “I know, it sounds ridiculous, but I’m telling you, it works <em>exactly</em> like that…”
</p>
<p>
“How old is it?” Passinsky asked.
</p>
<p>
“How old is what?” asked Roger. “The EMP rifle? I have no idea. I didn’t even know it actually exists…”
</p>
<p>
“No. The computer game.”
</p>
<p>
Roger looked perplexed. “How old is System Shock 2? Hell, I don’t know. Fifteen, twenty years. It has this whole nineties cyberpunk sci-fi dystopia feel to it. All retro and awesome. Of course, I guess it wasn’t actually <em>retro</em> back then… Why do you ask?”
</p>
<p>
“You said it sounds ridiculous, to see a weapon from an old video game in your real world,” said Passinsky.
</p>
<p>
“Hey, I only know what I see on the screen.”
</p>
<p>
“It is not so ridiculous,” said the elderly scientist. “When you live for many decades, you see many things that were once only fantasy become real. Somebody built that EMP rifle you see on screen there. An engineer. And the engineers of today, fifteen or twenty years ago, were children playing video games.”
</p>
<p>
“The device is obviously homemade, or maybe a prototype that someone built by hand,” said Roger. “Here, take a look at this…” He shuffled through the footage until he found a clip of the geek dodging gunfire just outside the stockroom, then reuniting with his large scruffy friend in the adjoining hallway. “See how he’s looking over the parts of the gun to check it for damage? He’s examining all the little wires and circuits and things. It’s like he knows exactly how this thing works, down to the last transistor. And he’s so detailed and methodical about it… I’d say this thing is his baby. He made it himself. I’m sure of it.”
</p>
<p>
Passinsky’s expression turned to steel. “Do you think you can find him with it?”
</p>
<p>
“What do you mean?” asked Roger.
</p>
<p>
In a calculating tone, Passinsky said, “How many men in this city, do you think, have the capability to build something like that?”
</p>
<p>
Roger felt a flash of admiration for the gruff old scientist. The guy might’ve been ancient and a total asshole of a boss, but he was indisputably brilliant. “Probably not too many, Doctor P.,” said Roger. “And he’d probably have his skills listed on LinkedIn. And he’d be a member of local Meetup groups for electronics. And he’d know folks in the Maker community and probably post on their online forums. And there’s Ada’s Technical Books over on Broadway &mdash; I’m sure there’s somebody there who’d recognize him…”
</p>
<p>
The screen in front of Roger showed a clip of the geeky man in the hallway outside the cold storage room, just before the fight. He was wearing a stolen lab coat and pointing the pulse rifle at the leather-clad gunman. A moment later, the door to the cold storage room opened, and Tina emerged. 
</p>
<p>
Roger paused on the frame. The man on the screen had turned to look at the ajar door, and at that moment the light from the cold storage room fell upon him. Roger set the image to full-screen. It distinctly showed the face of the man with the energy gun.
</p>
<p>
“Whoever he is,” said Roger, “I bet I can find him. I know a few computer tricks.”
</p>
</div>