<div class="chapsection">
<p>
<span class="caplead">Beneath a star-filled sky, Jason’s yacht</span> rocked gently on wind-driven waves. “Can you make the boat hold still?” Danny insisted.
</p>
<p>
“It’s on water. It’s as still as it’s going to get,” Jason countered from the helm. “Can you even hit anything from all the way out here?”
</p>
<p>
“Oh yeah,” Danny replied as he braced his HERF gun against the yacht’s handrail. “I can boost the gain up to thirty decibels. Those Coast Guard radar stations along the shore? I can knock them out from half a mile away. But boosting tightens the beam, so I need to line it up just right…”
</p>
<p>
Out past the HERF gun’s nozzle, across the moonlit water, spread the steep tree-lined banks of the Medina waterfront. And over that waterfront, dwarfing the personal mansions of tech tycoons, rose the twelve-story edifice of the Medina Gallante. Its windows formed checkerboard patterns of iridescent green. Cobblestone pillars buttressed cedar balcony awnings. At the base of the hotel, a private wharf jutted out into the lake.
</p>
<p>
“This is exactly what this device is designed for,” Danny explained as he made adjustments. “I built it during Claymore’s contract with Naval Base Kitsap. I told the Navy they needed to harden their electronics against directed electromagnetic pulses. They laughed and said that EMPs are, um, ‘sci-fi hootenanny’, were their exact words. Well, I told them, ‘Give me a high-power magnetron, and I’ll show you hootenanny.’ They did, just to humor me. And when I came back and demonstrated this device to prove my point, they were surprisingly displeased…”
</p>
<p>
“So <em>that’s</em> what happened to the Kitsap contract,” Jason said. “You know, the investment board never got a straight answer from you about it.”
</p>
<p>
“Yeah, well. My point is, the Coast Guard’s radar systems are the same kind as the Navy’s. Somewhere along that shoreline, there’s an automated radar station watching this stretch of water. It’s a plastic dome, about the size of a beach ball, painted to look like a rock. It’s sweeping the area with a 5-degree beam at 2.8 gigahertz…” He pulled the trigger. “…And now it’s not.”
</p>
<p>
Jason asked, “That’s it? Just like that, the Coast Guard’s radar is down?”
</p>
<p>
Danny nodded. “Fried to a crisp. They’ll no doubt send a repair crew in the morning. But tonight, the sea is ours.”
</p>
<p>
“Alright then. I’ll take her in. Slowly. You go update the team.” Jason tapped the controls of the cherrywood console. A vibration quaked across the yacht. Water burbled behind the vessel.
</p>
<p>
Danny made his way across topside, and descended the stairs to the wood-paneled compartment where he had first met Mike and Moshen playing <em>Dungeons &amp; Dragons</em> the previous day. Upon the lacquered table sat several laptops, their screens showing floor plans, emails, and code. Freshly purchased cellphones and Bluetooth headsets lay on the leather benches.
</p>
<p>
The television on the room’s rear wall displayed the faces of Danny’s teammates in neatly tiled teleconference windows. In one corner, he could see Tina tending to glassware in his kitchen. Mike and Natalie shared a feed from the hospital room, and bantered in obnoxiously cute tones. A small icon represented Moshen, available only by voice.
</p>
<p>
“Guys,” Danny announced. “It’s happening.”
</p>
<p>
Mike responded, “I’m ready to probe their network as soon as you open a back door. Did you finish the trojan?”
</p>
<p>
Danny held up a USB thumb drive, and nodded. “Poking through the RockBox source code, I found a weakness in the integration of their billing system. It was built by a different contractor than the security system. By themselves, both billing and security are pretty solid. But their connection is sloppy. I managed to write a rootkit that exploits the flaw. As soon as this program runs on a computer that accesses the Gallante’s billing system, we take complete control.”
</p>
<p>
“But how do you plan to get that rootkit onto one of their computers in the first place?” asked Mike. “Remote access is not an option &mdash; you won’t be able to get it past their network firewall.”
</p>
<p>
“I figured as much,” said Danny. “That’s why I plan on checking out the Gallante’s fine dining establishments.”
</p>
<p>
“In person? Danny, you’ll be on your own in there at first. We can’t help you until that trojan is deployed. You’ll have to stay out of sight.”
</p>
<p>
“Don’t worry. I’ve got that covered. I went and got myself&mdash;” He held up a laundry bag. A brown shirtsleeve dangled from its open top. “&mdash;an invisibility suit.”
</p>
<p>
“Speaking of visibility,” Mike added. “I’ve taught Nat-Nat how to work the camera feeds. She’ll be your eyes and ears.”
</p>
<p>
Moshen’s voice chimed in. “‘Nat-Nat’? You call her ‘Nat-Nat’? What does she call you? ‘Snugglewumpus’?”
</p>
<p>
Natalie giggled. “Oooh, I like that one! My Snugglewumpus…”
</p>
<p>
Mike cooed back, “I’ll totally be your Snugglewumpus!” They started making out on camera.
</p>
<p>
Danny grabbed a mouse and hid their window. “Moshen,” he said, addressing the small motionless icon. “What’s your status?”
</p>
<p>
Moshen’s disembodied voice replied, “I’m parked on a side-street five miles away.”
</p>
<p>
“Great,” Danny said. “How are you feeling? Confident? Nervous?”
</p>
<p>
Moshen said, “Um…”
</p>
<p>
On a tree-lined residential road somewhere in Seattle’s eastern suburbs, a boxy gray van marked “Claymore Communications” stood on the curb. Moshen sat in the driver’s seat, his thin arms clutching the steering wheel. To his right, Sergey Mukhayev stared brooding, his hulking form breathing tensely as he gazed into the night. Behind them, Leo adjusted the suppressor on his handgun while Eugene deftly twirled a butterfly knife.
</p>
<p>
“I… can’t complain…” Moshen said.
</p>
<p>
Danny switched focus. “Tina. Status?”
</p>
<p>
She replied with a tired half-smile, “I’ve been Betty Crockering all day. I’d never eat in this house again if I were you.”
</p>
<p>
“I have a job for you,” Danny said. “It’s a job you’re best prepared for out of all of us, and it’s mission-critical.”
</p>
<p>
“As long as it gets me out of the kitchen,” she replied. “What do you need?”
</p>
<p>
“You’re not going to like it.” He hesitated, and finally said, “Communications officer.”
</p>
<p>
“What does that mean?” she asked.
</p>
<p>
“You know, like Uhura from <em>Star Trek</em>.”
</p>
<p>
“Which means…?” she repeated.
</p>
<p>
“The Gallante’s phone switch plugs into a Cisco VoIP system,” Danny explained, “And their security guards have walkie-talkies that use a trunked P25 digital radio system with an RTP cross-bridge. We can route all voice traffic to a SIP user agent on your terminal…”
</p>
<p>
“<em>Which means…?</em>”
</p>
<p>
“…You’ll be answering phones,” Danny said.
</p>
<p>
She glared at him with a gaze so cold that her image almost began frosting the screen.
</p>
<p>
“…You know, because… Your day job…” Danny stammered.
</p>
<p>
“I hate you so much right now,” she said.
</p>
<p>
The rumble of the yacht’s engines cut out.
</p>
<p>
“It’s go-time, guys,” said Danny.
</p>
<p>
Behind him, Jason descended into the cabin. “The ship’s docked. Danny, try not to get killed. Come back here when you’re ready for extraction. I’ll be waiting.”
</p>
<p>
“Actually, Jason, there’s a very important task that I need you to handle.”
</p>
<p>
“What’s that?”
</p>
<p>
“The same thing I did for you forty-eight hours ago. I need you to prepare a PowerPoint presentation.” 
</p>
</div>