<div class="chapsection">
<p>
<span class="caplead">
Hernando Mejía spoke no English,</span> and had no papers. He wasn’t stupid; he knew to keep his head down and his mouth shut. Stoically, he rubbed a Windex-coated cloth against the interior of the windows of the lower west wing of the Medina Gallante.
</p>
<p>
He saw motion outside. From the stone steps leading down to the wharf, a man’s head ascended into the light. A small Bluetooth device sat nestled in his ear, beneath a yellow safety helmet. He wore brown coveralls and a toolbelt, and carried a toolbox and a complex-looking device. He could’ve been a plumber or an electrician.
</p>
<p>
The man proceeded toward the doors. When he pulled on their handles, they wouldn’t budge. The man knocked on the glass, waved to Mejía, and said something in English. Mejía replied in Spanish, but the man simply shrugged.
</p>
<p>
Mejía weighed his options. His instincts told him to be wary. Paranoia was a virtue.
</p>
<p>
Paranoia, however, also told Mejía that, if this man was indeed simply a maintenance worker, refusal to let him in could result in being reported to management. And job loss. And ICE.
</p>
<p>
Mejía opened the door.
</p>
<p>
The man glided in, babbled something in English, and walked off into the wide wood and marble halls of the hotel. Mejía returned to work.
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Lynnette Leffert was swamped.</span> The clientele of <em>Bistro</em> was awash with cash and never thought twice about paying extravagant prices for a garden salad and garlic bread, but they always made Leffert and her staff work for their profits. She’d spent the evening enduring culinary criticism from a Parisian couple, sexual harassment from Kuwaiti bankers, and an impenetrable language barrier from Japanese technology executives. Even on the best of days, managing the premiere restaurant inside the Medina Gallante was not for the faint of heart.
</p>
<p>
She was checking the fridge inventory when Luke, the host, came to fetch her.
</p>
<p>
“Hey, um, Lynette…?” said the thin young man. “We’ve got some guy from Facilities here. He says he’s found some electrical problem…?”
</p>
<p>
“Electrical problem?” she echoed, her concentration still set on counting foil-wrapped steaks.
</p>
<p>
“He said it might have something to do with our computer? Should I bring him over, or…?”
</p>
<p>
Leffert shook her head. She closed the refrigerator door and marched out from the kitchen.
</p>
<p>
<em>Bistro</em> opened out to a wide hallway that led to the elevators and lobby. Velvet ropes swooped out from the doorway, past a black easel listing the day’s specials in handwritten multi-colored chalk.
</p>
<p>
An electrician, evident by his blue coveralls and yellow helmet, stood waiting. He was studying the host’s lectern, where a spiral-bound notepad and a glossy, crayon-marked paper chart enabled Luke to keep track of reservations and seating arrangements.
</p>
<p>
“Can I help you?” Leffert asked pointedly.
</p>
<p>
The man looked slightly disoriented. “I… was just noticing that you don’t use a computer for your, um, seating thingie…”
</p>
<p>
“No, we don’t,” Leffert said.
</p>
<p>
“But you do have a computer, yes?”
</p>
<p>
“Yeah, a Point-Of-Sale system,” Leffert answered.
</p>
<p>
The man said, “Well, see, I’m trying to isolate a ground fault somewhere along this column of the building. I need to go through all the appliances on this circuit until I can find what’s causing the issue.”
</p>
<p>
Leffert raised an eyebrow. “A ground fault?”
</p>
<p>
He nodded. “Yes, ma’am. It’s when some appliance somewhere isn’t properly insulated. It could be very dangerous. I just need to rule out your computer as a possible source…”
</p>
<p>
Leffert rubbed her temples. “How long will it take?”
</p>
<p>
“Two minutes, tops. I just need to check the computer’s power cord.”
</p>
<p>
“Fine, get to it,” Leffert replied. “Luke, take him to the POS.”
</p>
<p>
Luke escorted the electrician to the window between the kitchen and the serving area. On a shelf jutting from the wall sat the restaurant’s Point-Of-Sale computer. Its touch-sensitive screen showed multicolored blocks that waiters pressed to enter orders. The electrician nudged the computer to access its rear workings.
</p>
<p>
Leffert had scarcely gotten halfway back to the kitchen before Luke came running. “Hey, Lynette! It’s asking for your password!”
</p>
<p>
The electrician stood sheepishly next to the POS computer. “I’m so sorry! I must’ve bumped something!”
</p>
<p>
Leffert looked at the POS touch-screen. It presented a large window with a big orange warning icon and the text:
</p>
<pre class="computer">
<strong>Do you want to allow the following program from an 
unknown publisher to make changes to this computer?</strong>

Program name: <strong>MICROSOFT_WINDOWS_SYSTEM_UPDATE.EXE</strong>
Publisher: <strong>Unknown</strong>
File origin: <strong>Removable media on this computer</strong>

To continue, type an administrator password, and then click Yes.
</pre>

<p>
Leffert rolled her eyes and tapped her password. “It’s just some kind of system update crap,” Leffert said. “Probably didn’t even have anything to do with you. Did you find the issue?”
</p>
<p>
He shook his head. “No, the fault’s not here. Your system’s fine.”
</p>
<p>
“Good. You need anything else from me?” Leffert said with a tired shrug.
</p>
<p>
“Not at all,” he said, and he scampered off into the hall.
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Danny watched the old Claymore Communications van</span> roll through the gate toward a secluded corner of the hotel’s underground garage. He leaned against a concrete pillar, illuminated by jaundiced fluorescent lamps. “Did anyone see them enter?” he asked.
</p>
<p>
“Negative,” Mike replied inside his earpiece. “Our virus went from the restaurant’s sale terminal to the hotel’s billing system, and from there to the security office. We control the cameras. And the garage gate, obviously.” 
</p>
<p>
Danny watched the parking barrier’s arm drop back down after the van finished passing. “And the doors?”
</p>
<p>
“All ours,” Mike answered. “And the elevators. Still working on telephone landlines…” A moment later, he added, “PSTN secured! Routing all phone calls to Tina.”
</p>
<p>
“Yay,” Tina said with a level of enthusiasm usually reserved for dental exams.
</p>
<p>
Moshen cut the engine, hopped out, and came around to open the rear doors of the van. Danny was greeted by the familiar sight of Claymore’s field installation equipment and on-site troubleshooting tools. A spectrum analyzer, a portable power supply, and a short Yagi antenna jutted out from the heap of electronics. In the past six years, he’d taken this van to more trade shows and vendor demonstrations than he cared to remember. With Claymore now closed and its assets pending sell-off, this mission to the Medina Gallante was to be this van’s last expedition.
</p>
<p>
The van rocked gently on its suspension as Sergey stepped out. The side door slid open, and Eugene and Leo emerged. They each fiddled with Bluetooth earbuds. On his own piece, Danny overheard the chatter as Tina joined them to the conference call.
</p>
<p>
Moshen walked away to stand watch. The three Russians came around to the back of the van and dug through the piles of cables and electronics.
</p>
<p>
Buried beneath the boxes lay a mobile armory.
</p>
<p>
Sergey extracted a vest of grayish body armor, long and bulky with hard, blocky plates. He donned it over his clothes and fastened its buckles. Onto his head he pulled a heavy-looking full-faced helmet with a thick visor. He strapped a tall black rectangular shield to his left arm, large enough to cover his body from knees to face, with a wide transparent window embedded near the top to allow for vision. In his right hand he held a MAC-10, complete with suppressor, folding stock, laser sight, and extended magazine. He looked like a two-legged tank.
</p>
<p>
Leo, the gunman who’d shot Danny in the shoulder, wrapped himself in a ballistic vest and helmet like Sergey’s. Instead of the shield and MAC-10, though, Leo opted for a spiny black multi-component rifle with enough switches and levers to rival a church organ. A sophisticated scope ran along its top. A ridged hollow tube, about as big as a cardboard paper towel roll, hung beneath its barrel. The precision engineering of the many modular interlocking pieces astounded Danny; beholding it, he realized with a craftsman’s solidarity that whoever developed that firearm knew as much about alloys and ballistics as he did about computers and electronics.
</p>
<p>
“What the hell is that?” Danny couldn’t help asking.
</p>
<p>
“This?” Leo checked the intricate parts of the weapons system. “This is standard-issue M4 carbine. It has suppressor and muzzle break, M68 CCO reflex sight and an M203 grenade launcher.” He held it up proudly. “I call her Matilda.”
</p>
<p>
“A grenade launcher? Guys, that was <em>not</em> part of the plan!”
</p>
<p>
“You stay with computer stuff,” said Leo. “Leave fighting to us. You don’t tell us how to do our job, we won’t tell you how to do yours.”
</p>
<p>
“Does your job involve picking out pieces of Sergey’s daughter from piles of gibs and putting her back together with duct tape?” warned Danny.
</p>
<p>
Leo rolled his eyes and scoffed, “Idiot.” The Russian gunman reached into the van and pulled out a black rubber cylinder, rounded on one side, shaped like a bullet but the size of a pill bottle. “We use <em>this</em>.”
</p>
<p>
“What’s that?” Danny asked.
</p>
<p>
Sergey grinned. “It is how you make an entrance.”
</p>
<p>
Leo laughed lightly. “Forty-millimeter spin-stabilized flash grenade. You do not want to be looking at it when it goes off.”
</p>
<p>
Sergey smiled, shook his head, and said mirthfully, “Nooooo, you really, really don’t!” The two seemed to share an inside joke of some kind &mdash; a recollection, perhaps, of battles past.
</p>
<p>
A few feet away, Eugene practiced turning, twisting, and kicking in his gear. He opted for a thinner, lighter ballistic vest and a bowl-shaped open-faced helmet, affording him fast, easy movement.
</p>
<p>
Sergey passed him a bigger helmet, with side coverage and a faceplate like the kind he and Leo wore.
</p>
<p>
Eugene scoffed. “Uncle, that thing is useless! You wear that, you have no idea what’s happening around you. Look…!” He reached his hands out on either side of Sergey’s fully encased head, and began snapping his fingers on alternate sides. “Over here! No, over here! Over here! …See? Nothing.”
</p>
<p>
Sergey mumbled, “Over here, smartass,” and swung his MAC-10 out at Eugene’s unprotected cheekbone, quick enough to startle him but softly enough to do no harm. Eugene ducked to avoid the pistol-whipping, and reached up to seize Sergey’s elbow and wrist. Sergey found his arm trapped in a limb-lock that would’ve sent the gun clattering to the floor if Eugene applied any more force. Sergey responded with a shield-bash, smacking the black polymer bubble against Eugene’s body. Eugene stumbled several feet backwards.
</p>
<p>
The two men laughed, and spoke in Russian with warm, familial tones.
</p>
<p>
Danny’s attention was pulled away by the sound of Mike’s voice in his earpiece. “Danny, are you there?” 
</p>
<p>
Danny turned away, his face hard with concentration. “What’s up?”
</p>
<p>
“I have good news and bad news. I found several X10/IP bridges.”
</p>
<p>
“That’s <em>spectacular</em>,” said Danny. “What’s the bad news?”
</p>
<p>
“There’s a huge number of X10 controllers in the building,” said Mike. “I can’t tell which ones correspond to the penthouse. We need to go through them one by one to figure it out.”
</p>
<p>
“I’ll get you additional manpower,” said Danny. “Moshen! This X10 issue. Can you help?”
</p>
<p>
Moshen hesitated. “Uh… What’s an X10?”
</p>
<p>
“Home automation,” Danny explained. “It’s a language spoken by electrical appliances. Lights, heating, air conditioning, entertainment systems, that kind of thing.”
</p>
<p>
Moshen recoiled. “I just build websites, man…”
</p>
<p>
Danny went to the back of the van to dig out a boxy old laptop. “Wireshark,” Danny said briskly as he dusted off the computer. “tcpdump. nmap. netcat. dd.”
</p>
<p>
“Those are network probing tools, right?” asked Moshen.
</p>
<p>
“Can you use them?” he asked, booting up the laptop.
</p>
<p>
“Um…” said Moshen.
</p>
<p>
Danny shoved the laptop into his hands. “Learn. Fast.”
</p>
<p>
From around the other side of the van, Sergey’s voice rumbled. “Can we get moving yet? It is getting hot in this suit.”
</p>
<p>
“Let me check,” Danny replied. “Mike and Natalie! Have you found a path these guys can take through the building without being seen?”
</p>
<p>
Mike’s voice buzzed in the earpiece. “Yes. Up the back stairs &mdash; it connects to the hotel’s rear maintenance corridor.”
</p>
<p>
Danny grabbed his HERF gun and toolbox, and began walking toward the garage’s rear stairwell. “Guys, let’s get moving.”
</p>
<p>
Eugene called out, “Hey, hold on! Almost done here…” He knelt over a large spool of black nylon rope. He was in the process of cutting two- and three-foot lengths with a serrated blade.
</p>
<p>
Danny muttered, “Do I even want to know what that’s for?”
</p>
<p>
“Rope is for many things.” He finished the last of the cuts, then hurriedly stuffed the spool into a backpack. “But first,” he added, “it’s for making a few inconvenient people go away.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Dominga Torres was a stout, brawny woman.</span> Under her uniform, her abdomen still bore a calligraphic “Chola 4 Life” tattoo, an embarrassing reminder of her teen years in East L.A. Much of her early life was spent in and out of juvenile detention centers, cursing authority figures with vows of vengeance. But when she’d become a mother, she’d taken stock of herself and the kind of world she wanted for her babies. Her dream now was to land a position with the LAPD, and then see the expressions on her old friends’ faces when she’d come back into her old hood on the other side of the thin blue line. For now, though, she carried no gun, and her badge was simply a token brass shield printed with the words “Security Guard”, provided by the Medina Gallante.
</p>
<p>
A female voice squawked from the walkie-talkie. “Attention all Gallante security staff. If any remaining personnel have not yet received their individual briefing on tonight’s training exercises, please respond.”
</p>
<p>
The voice had been buzzing from the radio for the last half hour. The unfamiliar woman identified herself as a dispatcher from RockBox Digital Security, the company that had built the Gallante’s camera and radio systems. Torres had listened to the chatter as her fellow guards had been called up, one by one, to discuss some new procedure that RockBox wanted them to follow.
</p>
<p>
Torres took one last long drag from her cigarette before extinguishing it in the patio ashtray. “Torres to Dispatch. Just finishing a smoke break. What do you need? Over.”
</p>
<p>
“Please report to the security office,” the voice said. “Our field agent will give you an in-person outline of your role in tonight’s activities.”
</p>
<p>
“On my way,” said Torres. “Over and out.”
</p>
<p>
She reentered the building from the smoking balcony and marched through the wide posh passages of the Gallante, feeling comfortably dominant in the maze of halls and stairways that she spent every day protecting. A trip down an elevator and through a side door marked “HOTEL STAFF ONLY” placed her in a drab white corridor lit by faintly humming fluorescent bulbs.
</p>
<p>
Torres strode up to an unremarkable gray door with a black placard printed with “SECURITY” &mdash; her base of operations. She rapped her knuckles against it.
</p>
<p>
The door opened inward, apparently under its own power. Whoever had opened the door stood behind it rather than emerging to greet her.
</p>
<p>
Through the doorway, she could see the main security console. It consisted of a large desk rigged with a radio dispatch board, a computer station, a 9-1-1 hotline, and a dozen display screens showing feeds from the hotel’s security cameras. It was normally occupied by Karl or Arnie, who would’ve been sitting in the swivel chair. But the chair was empty; the security console, against protocol, was unmanned.
</p>
<p>
If there was one thing she’d learned in East L.A., it was how to spot a set-up.
</p>
<p>
She backed away and reached down to grab her radio. Goosebumps on her arms brushed electrically against the inside of her uniform.
</p>
<p>
Her back pressed against something pointed and solid. She heard a click behind her. It was a very distinctive sound: a revolver’s hammer being cocked.
</p>
<p>
“Don’t turn around,” a voice said. It had an accent. European of some kind. “And don’t scream.”
</p>
<p>
Her breathing quickened. Moving slowly, Torres spread her arms out and lifted them above her head. “What do you want?” she said quietly.
</p>
<p>
“Please step through the doorway,” said the voice.
</p>
<p>
Her spirit bucked in defiance. She suppressed her instincts and forced herself to comply.
</p>
<p>
When she was finally inside the office, she saw Karl and Arnie and the rest of the security staff. They were all gagged and bound with cords of nylon rope, tied to a water pipe that ran through the office.
</p>
<p>
And standing several feet from them, ensuring their silence, was a man with IOTV body armor, a full-faced helmet, and a highly accessorized M4 rifle.
</p>
<p>
The intruder who’d opened the door closed it behind her. He stepped into her view, and pointed a MAC-10 at her torso. He was a behemoth of a man. A black riot shield was strapped to his left arm. Through the visor of his helmet, she saw that his eyes were determined and professional.
</p>
<p>
This was not a mere robbery. This was some kind of full-scale military operation.
</p>
<p>
The Medina Gallante was frequently visited by foreign dignitaries. She had always entertained the notion that, at some point, some high-value political target would appear on its guest roster. That day must have finally come.
</p>
<p>
The voice behind her spoke. “Slowly lower your hands and put your wrists together behind your back.”
</p>
<p>
The voice’s accent clinched the conclusion in her mind. This was a Special Ops attack by a foreign power. Every man, woman, and child in the Gallante was in danger.
</p>
<p>
Her fellow guards had all been rendered helpless. Torres was the last one left.
</p>
<p>
She took a deep breath. She began to lower her arms. But as she brought them down, she simultaneously began bending her knees into a crouch.
</p>
<p>
Her babies would always know that their mommy died fighting for what’s right. For their entire lives, that knowledge would give them strength and guidance. For a gift like that to give to her children, she was willing to pay the cost.
</p>
<p>
She lunged for the security console.
</p>
<p>
On the desk was a 9-1-1 hotline &mdash; a bright yellow telephone that connected directly to the Bellevue PD automatically just by being picked up. The police department’s phone system would begin recording the call immediately, ensuring that somebody would hear her last words. She grabbed the corded handset and dove beneath the desk.
</p>
<p>
“<em>Medina Gallante hotel under foreign military attack!</em>” she screamed. “Private security incapacitated! Attackers equipped with automatic rifles and combat armor…”
</p>
<p>
Her voice trailed off. She hadn’t expected to survive long enough to say more than half a dozen words. There were no blasts of gunfire, no bullets flying.
</p>
<p>
But there was no 9-1-1 dispatcher answering the line, either.
</p>
<p>
The three soldiers stared at her in astonishment.
</p>
<p>
The goliath with the shield and the MAC-10 simply said, “Holy crap.”
</p>
<p>
The man with the M4 said, “That took some serious balls, lady.” To the rest of the captive security personnel, he said, “Did you guys see that? <em>That</em> is how you do your job!”
</p>
<p>
Torres looked back and forth at the three invaders, confused.
</p>
<p>
The man who had snuck up behind her wore a light ballistic vest and a bowl-shaped open-faced helmet, and carried a silver snubnose .44 Magnum.
</p>
<p>
“We’re not here to hurt you,” he said. “We just need you out of the way.”
</p>
<p>
The yellow handset vibrated in her hand. “Hey. Ms., um, Torres, was it?” It was a woman’s voice &mdash; matching the one on her radio. Torres looked at the handset in bewilderment. “I’m… I’m really, really sorry.”
</p>
<p>
“Who the hell are you people?” Torres hissed.
</p>
<p>
The man in the light vest gestured with his revolver. “That was incredibly heroic, what you did just now,” he said. “You should be very proud of yourself.” He reached into a backpack on the floor, and pulled out a few lengths of nylon rope. “But don’t try it again.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">The Gallante’s exercise facilities</span> comprised the entire ground floor of the hotel’s south wing. The treadmills and weight machines were populated sparsely, but the massage tables and tanning beds saw plenty of use. The Finnish saunas were always a favorite among eastern European guests. Especially Russians.
</p>
<p>
In one of the small, steamy rooms, three muscular men sat naked on white towels laid across wooden benches, talking boisterously in Russian.
</p>
<p>
“So, her husband’s still twitching on the ground, right?” one man regaled his two fellows. “And she’s, like, blank. You know how they go blank, right? And I just smile at her and go, ‘Cheer up, honey! You’re going to die tonight anyway. You might as well do it in a good mood!’”
</p>
<p>
The two other men burst out in raucous laughter. “You’re one cold bastard, man!”
</p>
<p>
“So what did she do?”
</p>
<p>
“Well, check this out,” he continued. “I had her tied up with rope, so I thought I could take my time. I’m going through the apartment, looking for the merchandise, when I hear this, ‘Click! Click-click…!’ So I come back and take a peek…”
</p>
<p>
“Was it a gun?” one man asked.
</p>
<p>
The storyteller shook his head.
</p>
<p>
“A telephone!” the other said.
</p>
<p>
“Nope.”
</p>
<p>
“So what was it?”
</p>
<p>
The storyteller pantomimed putting a cigarette in his mouth and cupping his hands to light it.
</p>
<p>
“A lighter!”
</p>
<p>
“Yes! She managed to dig it out of her pocket, and she twisted her hands around to get the flame onto the rope.”
</p>
<p>
“Daaaaamn! Clever girl!”
</p>
<p>
“I know, right? Must’ve hurt like the Devil, with the fire on her wrists, but it worked. By the time I noticed, she’d already got her hands free, and she made a run for it before I could stop her.”
</p>
<p>
He reached toward a control board mounted near the frosted glass door of the tiny room. With the press of a button, nozzles recessed in the wood-paneled walls emitted a quick hiss of steam.
</p>
<p>
“Moral of the story? When you’re tying someone up with ropes… Make sure they’re not a smoker.”
</p>
<p>
The men laughed. Moisture condensed on their bodies and beaded with their sweat. Wet droplets ran down their faces and chests.
</p>
<p>
One of them asked tentatively, “Hey, do you guys like it turned up this high?”
</p>
<p>
They looked at the control board. A small black screen reported: <span class="computer">212°F (100°C)</span>.
</p>
<p>
“Yeah, that’s a little too high,” one conceded, and pressed a down-arrow button repeatedly until the screen displayed <span class="computer">158°F (70°C)</span>.
</p>
<p>
They let a minute go by, but felt no improvement. All three began breathing a little more heavily.
</p>
<p>
“I thought you turned it down.”
</p>
<p>
“I did! Look!”
</p>
<p>
The screen again showed <span class="computer">212°F (100°C)</span>.
</p>
<p>
“Idiot doesn’t know how to work the sauna.”
</p>
<p>
“Shut up, asshole.” He punched it back down, watching the numbers descend until they again hit <span class="computer">158°F (70°C)</span>.
</p>
<p>
The moment he took his finger away, the numbers immediately jumped back up to <span class="computer">212°F (100°C)</span>.
</p>
<p>
“What the hell? Stupid piece of crap. I’ll go yell at someone about it.” He rose, wrapped his towel around his waist, and pushed on the door.
</p>
<p>
It moved about an inch, and then hit some kind of restraint. He pushed against it harder. It wouldn’t budge.
</p>
<p>
Outside, through the frosted glass, a silhouette of an athletic man appeared just beyond the door. He seemed to be wearing a small helmet and a bulky suit.
</p>
<p>
“Brothers!” said the man, in Russian. “How are you doing in there? Nice and warm?”
</p>
<p>
The men sat up shocked. One pounded on the glass. “What the hell is this? Who are you?” one yelled.
</p>
<p>
“Oh, I’m nobody! Nobody at all! But I do have a matter of pressing business with someone named Ivan Zheleznov. Perhaps you fellows have heard of him?”
</p>
<p>
One stood and body-checked the door. It proved fruitless.
</p>
<p>
“I really wouldn’t do that if I were you,” the man said mischievously. “All that physical exertion. You might work up a sweat.”
</p>
<p>
“Let us out, you vermin!” one screamed, and had to sit down to gasp for air. Each breath singed his lungs.
</p>
<p>
“Not until we chat!” the man said. “You see, brothers, it’s not really <em>my</em> interest per se, but I have some colleagues here who would like to know one slight, insignificant little piece of information. When Ivan pays you, what’s the routing number of the bank that the payments come from?”
</p>
<p>
“Are you fucking joking?” one said, fighting rage as the room boiled around him. “Who the hell memorizes bank routing numbers?”
</p>
<p>
“Then here’s what’s going to happen, buddies!” said the man. “My colleagues are going to do some exploration of Ivan’s financials, and they’re going to use <em>your</em> bank records to do it. Now, you’re each going to give me your logins and passwords to your bank accounts. And my colleagues &mdash; they’re in control of your temperature, by the way &mdash; they’re going to sift through your transaction histories until they find checks or transfers connected to Ivan. Any additional info you guys can provide to expedite that search will make the whole thing go much more quickly.”
</p>
<p>
“Go choke on a dick, asshole! We’re not going to hand our bank accounts to you!”
</p>
<p>
“I think you will,” said the man. “And I’d like to remind you that my colleagues are listening to me right now and are ready to use your login information immediately, so it’ll do you absolutely no good to lie. All it’ll do is waste your breath.”
</p>
<p>
“Rot in hell!” one screamed as he struggled, weakening, against the door.
</p>
<p>
The man chuckled. “Let me know when you guys are ready,” he said, and began whistling a cheerful tune.
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Ivan Zheleznov was freezing.</span> His hoarse voice rattled into his room’s desk phone. “You fixing right now! Understand?”
</p>
<p>
<p>
Tina’s voice politely responded, “We’re terribly sorry for the malfunction of your air conditioning, sir. We’re sending a repairman right away.”
</p>
<p>
That was Danny’s cue.
</p>
<p>
Danny stood in an undecorated emergency stairwell that ran down the full height of the building. His HERF gun was far away, stored safely in the security office where Sergey’s crew sat monitoring the captives. He picked up his toolbox, and with a deep breath that echoed off the cinderblock walls, he opened an emergency exit door.
</p>
<p>
He stepped out to a wide antechamber. One side of the room was a full plate window overlooking the nighttime skyline. The door to the penthouse elevator sat closed next to the emergency exit on one end of the passageway. On the other, a large cedarwood double door stood ominously before him.
</p>
<p>
Danny shook his head and arms limply to force himself to relax, and tapped his knuckles on the door. He stood patiently, toolbox in hand, waiting for a response.
</p>
<p>
There was shouting in Russian. After a few long moments, a lithe, aggressive man opened the door. He wordlessly bobbed his head to the side, motioning for Danny to come in.
</p>
<p>
The air in the suite was irritatingly cold. A fierce draft blew strongly enough to make hair wave and clothes billow. The balcony’s French doors had been opened in an attempt to let out the cold. On the balcony, a few leather-jacketed men and barely dressed women smoked and chatted. Inside, a small group played <em>Call of Duty</em> on an enormous wall-mounted TV in a sunken living room. On the glass coffee table, somebody had thrown a hotel towel over a large crystalline bowl. He saw no weapons out in the open, but he had no doubt they were close at hand.
</p>
<p>
No twelve-year-old girl was anywhere to be seen. He did, however, see Ivan Zheleznov.
</p>
<p>
The man descended the spiral staircase like a hawk swooping down on a field mouse. He sported a fine three-piece suit and slicked-back silver hair. Despite being the oldest and physically weakest man in the room, his presence imposed a greater sense of immediate peril than any of his bodyguards.
</p>
<p>
“You come to fixing the air, yes?” he verified in a gravelly, impatient voice.
</p>
<p>
Danny found the thermostat on the wall, walked up to it, and pretended to fiddle for a few seconds. “The thermostat looks fine. There must be a loose heating element somewhere near the sensor,” he bluffed. “I’ll need to check your ducts.”
</p>
<p>
He scanned the walls, and found an air vent near the ceiling. He marched toward it with as much bravado as he could muster, and pulled a chair over so he could stand on it for a closer look. The vent was about two feet wide and a foot tall. The frosty air blasted him in the face as he looked inside the faceplate, blowing around his helmet and across his ears. Holding his head level with the opening, he turned to check the view of the room. He could see most of the open downstairs area of the penthouse. This vent would serve him well.
</p>
<p>
With the help of a screwdriver from his toolbelt, he removed the grating. He spent several moments pretending to examine the dark interior of the air shaft.
</p>
<p>
“It, uh, looks like the ventorical airfoil router is jammed,” he said. He turned to study the expressions of the Russians. They remained emotionless.
</p>
<p>
The rest of his work would require sleight of hand.
</p>
<p>
Danny picked up his toolbox and brought it up to the vent. The opening was big enough for him to rest the toolbox partway in the air duct, obscuring his hands from the watchful eyes of Ivan and his men. Danny cracked the lid open and rummaged noisily through the box’s contents. Metallic echoes reflected back at him in the flowing air.
</p>
<p>
From inside the toolbox, he inconspicuously fished out a small black device, roughly the size and shape of a pack of cigarettes. On one edge of the object, behind a lens the size of a dime, a camera iris expanded and contracted with a soft whir as it tried to accommodate the light levels of the room. Using his body to hide his actions, Danny wadded up a ball of Sticky Tack putty and used it to affix the wireless camera inside the air vent.
</p>
<p>
Trusting the rattle of the cold, windy air to obscure his voice from the Russians, Danny murmured, “Mike, how’s the angle?”
</p>
<p>
From his Bluetooth earpiece, Mike’s voice replied in tinny tones. “Right now all we can see is you, but it should be good enough for situational awareness once you’re out of there.”
</p>
<p>
Danny said under his breath, “Every second I’m here is a second too long. Mike, prepare to cut the air in five.” He gave the Sticky Tack one last gentle tug to make sure the camera was affixed securely, and took a deep breath. In one quick motion, he pulled his toolbox out of the vent and put the faceplate back over the opening, praying that he was fast enough to keep the Russians from seeing what he had installed behind it. He screwed the grate into place. His fingers shivered as he worked, but not from the cold. He couldn’t quite get the threads on the screws to align.
</p>
<p>
As he fiddled with the cover, the air vent’s gale died, leaving a quiet stillness to the room.
</p>
<p>
Danny climbed down from the chair. “Well, it appears my work here’s done. Have a good day, gentlemen.” He gave Ivan a courteous nod. The balconyfolk began filing back inside.
</p>
<p>
He suppressed the urge to sprint from the room, policing his nerves to maintain a professional façade. Toolbox in hand, he walked calmly toward the large cedarwood doors that stood between him and the penthouse anteroom.
</p>
<p>
And he had almost reached it before he heard a sound behind him.
</p>
<p>
The sound was a metallic creak. It was followed by a clanking crash.
</p>
<p>
He turned around.
</p>
<p>
The air vent gaped exposed and uncovered in the wall, revealing a naked wad of Sticky Tack inside the shaft. On the floor beneath it, the faceplate lay upon the carpeting, beside a few loose screws. Near it was the small black wireless spycam.
</p>
<p>
For one silent second, both Danny and Ivan stared dumbly at the pile, saying nothing.
</p>
<p>
Danny bolted for the door as Ivan shouted orders to his men. Danny’s fingers reached for the handle, but before they made contact he was pulled backward by his shirt. A wiry, muscular arm curled around his neck like a python, and he felt himself getting shoved back into the room. Someone kicked him forward, toward the grey figure of Ivan Zheleznov.
</p>
<p>
The lithe man who had greeted Danny at the door earlier now stood next to Ivan. He pulled a small black semi-automatic from his pocket, and pressed it to Danny’s chest. Danny felt his heart beat against the barrel. The mercenary slowly walked Danny down the steps of the sunken living room, where Danny found himself surrounded by Ivan’s men. The video game on the large television was paused &mdash; and while the digital images of gunmen stood frozen on the screen, real ones pointed their weapons at him from all directions.
</p>
<p>
In the Bluetooth earpiece, Mike said, “Danny! What’s happening?”
</p>
<p>
Ivan hissed at him, “Do you thinking we are amateurs? A video camera bug in a air vent! Is insult to the intelligence.”
</p>
<p>
Danny squared his shoulders. He gulped hard, knowing that a convincing feint of bravado would be his only chance of survival. “I’m only here for the girl,” he said. “Hand her over and no harm will come to you.”
</p>
<p>
Ivan burst out laughing. “No harm come to me?” The mercenaries joined Ivan in laughter.
</p>
<p>
In the earpiece, Danny heard his team panicking. “Sergey! Bail him out! Bail him out right now!” said Mike. Sergey replied, “We are not anywhere nearby. Eugene is needing time to get into position. He must stall.”
</p>
<p>
With as much strength as he could conjure, Danny said, “We’re willing to negotiate.”
</p>
<p>
Still chuckling, Ivan said, “Yes, I sure you are. You working for Sergey. I know this already. It is surprising, really. This…” He gestured with the spycam. “This not style of Sergey. Sergey, he more like, ‘Rahhhh! March! Go!’ Punch, kick, boom boom boom. You understand? This, this is more thinking, more like the chess. Maybe Sergey learning something as he getting older.”
</p>
<p>
The Bluetooth headset buzzed with the voices of Danny’s cohorts. “We can’t just sit here!” Tina insisted. Mike replied, “There’s only one option! Have we finished isolating the X10 controllers?”
</p>
<p>
Danny knew what his team was trying to do. With the gun still pressed to his chest, Danny mumbled, “I didn’t intend to be in the room for this. But I guess it doesn’t matter now, does it?” He looked at Ivan defiantly and said, “So, are you ready to start making a deal?”
</p>
<p>
Ivan smirked. “<em>Deal</em>? Here making ‘deal’. We killing you soon, but not right now. First we having with you a little ‘conversation’. This man here, he is expert at having ‘conversations’ like this.” Ivan gestured to the lithe man holding the gun at Danny’s ribs. The man grunted happily. “You will telling us everything about where is Sergey and how you working with him. Then, when you done telling us, we finally letting you die. That is ‘deal’, understand?”
</p>
<p>
In the earpiece, Mike said, “X10 packet injection check, receiver firmware mod check… Let’s do it already!”
</p>
<p>
Ivan leaned toward Danny. “Ah, so quiet! You having no last words?”
</p>
<p>
A diabolical smile crept onto Danny’s face.
</p>
<p>
In a blink, the room lights died. The suite went dark, save for the glow from the plasma TV. Its image flicked to an online banking interface, logged in to a corporate account. The ledger was listed in euros, and showed a balance of seven figures. Across the top, in both Russian and English, it displayed the title, “Zheleznov Consortium Holdings”.
</p>
<p>
In the light of the television screen, with every gun in the room pointed at him, Danny looked Ivan in the eyes and grinned.“Actually, yeah. I’ve got a few things to say.”
</p>
</div>