<div class="chapsection">
<p>
<span class="caplead">
Hernando Mejía wasn’t legally allowed</span>
 to be here. He spoke no English, and he had no papers. He wasn’t stupid; he knew to keep his head down and his mouth shut.
</p>
<p>
Stoically, he rubbed a Windex-coated cloth against the interior of the windows of the lower west wing of the Medina Gallante.
</p>
<p>
He saw motion outside.
</p>
<p>
From the wide stone steps leading down to the hotel’s wharf, a man’s head ascended into the light. A small Bluetooth device sat nestled in his ear, beneath a yellow safety helmet. He wore coveralls and a toolbelt, and carried a toolbox and a large long complex-looking device. He could’ve been a plumber or an electrician.
</p>
<p>
The man climbed the steps and proceeded toward the doors. When he pulled on their handles, they wouldn’t budge. After 9:00 P.M., the doors needed a key to open from the outside. If the man had any legitimate business out on the wharf, he would’ve known that.
</p>
<p>
The man knocked on the glass, waved to Mejía, and said something in English. Mejía could hear him speaking, but he understood nothing. Mejía tried to reply in Spanish. The man simply shook his head and shrugged.
</p>
<p>
Mejía weighed his options. His instincts told him to be wary. Paranoia was a virtue.
</p>
<p>
That same sense of paranoia, however, also told Mejía that his best option was always to comply. If this man was indeed simply a locked-out maintenance worker, refusal to let him in could result in being reported to management. And job loss. And ICE.
</p>
<p>
Mejía opened the door.
</p>
<p>
The man picked up his equipment and entered the building. He babbled something in English. Mejía simply gave him a thumbs-up and a plastic smile. Eventually, the man stopped talking, and walked off into the wide wood and marble halls of the hotel.
</p>
<p>
Mejía returned to work.
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Lynnette Leffert was swamped,</span> as usual. The clientele of <em>Bistro</em> was certainly awash with cash and never thought twice about paying extravagant prices for a garden salad and garlic bread, but they always made Leffert and her staff work for their profit margins. She’d spent the evening enduring insults about her food quality from a Parisian couple, sexual harassment from a table of Kuwaiti investment bankers, and an impenetrable language barrier from a group of Japanese technology executives. Even on the best of days, the job of managing the premiere restaurant inside the Medina Gallante was not for the faint of heart.
</p>
<p>
She was checking the fridge inventory when Luke, the host, came to fetch her.
</p>
<p>
“Hey, um, Lynette…?” said the thin, effete young man. “We’ve got some guy from Facilities here. He says he’s found some kind of electrical problem…?”
</p>
<p>
“Electrical problem?” she echoed, her concentration still set on counting foil-wrapped stacks of steaks, chicken, and fish.
</p>
<p>
“He said it might have something to do with our computer?” the slight young man said hesitantly. “Should I bring him over, or…?”
</p>
<p>
Leffert shook her head. She closed the refrigerator door and marched out from the kitchen toward the front of the restaurant.
</p>
<p>
<em>Bistro</em> opened out to a wide hallway that led to the elevators and lobby. Velvet ropes swooped out from the doorway, past a black easel listing the day’s specials in handwritten multi-colored chalk.
</p>
<p>
An electrician, complete with blue coveralls and a yellow helmet, stood waiting. He was studying the host’s lectern, where a spiral-bound notepad and a glossy, crayon-marked paper chart enabled Luke to keep track of reservation times and seating arrangements.
</p>
<p>
“Can I help you?” Leffert asked pointedly.
</p>
<p>
The man looked slightly disoriented. “I… was just noticing that you don’t use a computer for your, um, seating thingie…”
</p>
<p>
“No, we don’t,” Leffert said.
</p>
<p>
“But you do have a computer, yes?” he asked.
</p>
<p>
“Yeah, a Point-Of-Sale system,” Leffert answered.
</p>
<p>
The man stood up straight, held up a bizarre plastic contraption, and said confidently, “Well, see, I’m trying to isolate an intermittent ground fault somewhere along this column of the building. I need to go through all the appliances on this circuit until I can find the one that’s causing the issue.”
</p>
<p>
Leffert raised an eyebrow. “An intermittent ground fault?”
</p>
<p>
The man nodded. “Yes, ma’am. It’s a situation in which some appliance somewhere isn’t properly insulated. It could be very dangerous. I just need to rule out your computer as a possible source…”
</p>
<p>
Leffert rubbed her temples. “How long will it take?”
</p>
<p>
“Two minutes, tops. I just need to get behind the computer and check its power cord.”
</p>
<p>
“Fine, get to it,” Leffert replied. “Luke, take him to the POS, please.”
</p>
<p>
Luke escorted the electrician to the window between the kitchen and the serving area. There, on a shelf jutting out from the wall, sat the restaurant’s Point-Of-Sale computer. Its touch-sensitive screen showed multicolored blocks that the servers could press to enter orders. The electrician nudged the computer to access its rear workings.
</p>
<p>
Leffert had scarcely gotten halfway back to the kitchen before Luke came running. “Hey, Lynette! It’s asking for your password!”
</p>
<p>
The electrician stood sheepishly next to the POS computer. “I’m so sorry! I must’ve bumped something!”
</p>
<p>
Leffert looked at the POS touch-screen. It had gone dim, and in its center sat a large window with a big orange warning icon and the text:
</p>
<pre class="computer">
<strong>Do you want to allow the following program from an 
unknown publisher to make changes to this computer?</strong>

Program name: <strong>MICROSOFT_WINDOWS_SYSTEM_UPDATE.EXE</strong>
Publisher: <strong>Unknown</strong>
File origin: <strong>Removable media on this computer</strong>

To continue, type an administrator password, and then click Yes.
</pre>

<p>
Leffert rolled her eyes and tapped in her password.
</p>
<p>
“I didn’t break anything, did I?” said the electrician. “I was just checking the electrical connection. Nothing I was doing should’ve touched the computer’s software…”
</p>
<p>
“Relax,” Leffert said. “It’s just some kind of maintenance crap. Probably didn’t even have anything to do with you. Did you find the issue?”
</p>
<p>
He shook his head. “I need to keep looking. The fault’s not here. Your system’s fine.”
</p>
<p>
“Good. You need anything else from me?” Leffert said with a tired shrug.
</p>
<p>
“Not at all,” he said, and he scampered off into the hall.
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">
Moshen Chan sat in the driver’s seat</span> of the Claymore Communications van, with a small platoon of Russian mafia thugs in the front and a cache of paramilitary armament buried beneath cellular transmission equipment in the back, wishing he could be at home writing some JavaScript code instead.
</p>
<p>
Satish’s Indian-accented voice chimed within Moshen’s earpiece. “I’ve got their billing systems under my control.”
</p>
<p>
Moshen asked, “Where’s Jason and Danny?”
</p>
<p>
Tina answered. “I’ve got them on a sidebar call. They’re discussing something about a slideshow.”
</p>
<p>
Satish announced, “Mike, I’m about to take over their security office. If they notice, they’ll probably signal for help. So I’m holding off until you take over their communications. How are you coming on that PSTN gateway?”
</p>
<p>
“I’ll tell you in a second,” Mike answered. Five silent minutes later, he said, “I think I got it. Routing phone calls to Tina…”
</p>
<p>
“Yay,” Tina said with a level of enthusiasm usually reserved for dental exams.
</p>
<p>
With his keyboard clattering in the background, Satish said, “Okay. I’m taking control of their security office.”
</p>
<p>
Mike announced, “Camera feeds coming online.” In the muffled background, he and Natalie strategized about which of them would watch which camera.
</p>
<p>
“Now, find a camera pointing at the parking entrance and watch it,” Satish instructed. “From the security controls, I should be able to open the gate to the underground garage. Can you guys see it moving?”
</p>
<p>
Natalie announced, “I see it!”
</p>
<p>
“Okay then,” said Satish. “Tina, can you get Danny and Jason for us?”
</p>
<p>
Jason’s voice arrived on the call in mid-sentence. “…where I’d get transaction counts and real-time sales figures like that.”
</p>
<p>
Danny replied to him, “Well, see, that’s just it. They don’t have to be real. Just believable. Remember, the goal is immediate psychological impact…”
</p>
<p>
Tina interrupted. “Hey Danny. I’ve patched you guys back into the main conference.”
</p>
<p>
“What’s our status?” he asked.
</p>
<p>
Satish said to him, “We own their billing systems, their security center, and their telephone lines.”
</p>
<p>
“Sweet,” Danny said slowly. “Then the next step is inserting the strike team. Moshen, you there?”
</p>
<p>
Moshen broke his silence. “Yeah.” He took a deep breath. “On our way.”
</p>
<p>
He started the ignition. The van rumbled to life, its headlights casting long cones of light down the still street. Large tires gripped the pavement as they slowly rolled out from the shoulder and onto the road. With his eyes moving in a twitchy, paranoid scanning pattern, Moshen guided the van along the quiet Bellevue streets into Medina, Washington.
</p>
<p>
If it wasn’t for the notification on the van’s GPS display, Moshen would never have known he’d just crossed into one of the wealthiest towns in the nation. Unlike the ostentatious palaces of Beverly Hills or the Hamptons, with their Corinthian columns and monogrammed wrought-iron gates, the houses of Medina were mostly simply large specimens of the kind of nondescript homes found in any upper-middle-class neighborhood. On one side of the simple suburban two-lane road, a descending slope overlooked roofs sprinkled between moonlit treetops. On the other, tall bushes obscured long driveways winding upwards beyond the greenery.
</p>
<p>
Without any warning, a pair of headlights materialized behind him.
</p>
<p>
A loud, high-pitched whooping sound broke the quiet night, and the van was suddenly lit up by the spastic red and blue flashes of a police cruiser’s lightbar. 
</p>
<p>
Moshen gulped and pulled gently onto the shoulder between the road and the foliage. The van’s tires crunched against fine gravel as it eased to a halt. He watched the police lights blink frenetically in his mirrors. Seconds felt like hours. He rolled down his window and waited.
</p>
<p>
A bright white light suddenly shone through the driver’s side window.
</p>
<p>
“Claymore Communications,” said a gravelly male voice.
</p>
<p>
“Yes, sir,” said Moshen.
</p>
<p>
The policeman waved his torch away from Moshen’s eyes, and swooped its bright circle onto Sergey in the passenger seat.
</p>
<p>
Sergey blinked, and attempted a friendly, professional smile.
</p>
<p>
“What brings you boys to the neighborhood?” the policeman said slowly. He panned his light across Eugene and Leo in the back seat. They kept stoic poker-faces.
</p>
<p>
“We’re on a troubleshooting call,” Moshen answered. “From the Medina Gallante hotel. They’re having some computer glitches.”
</p>
<p>
The policeman angled his flashlight to see into the rear of the van, past the back seat. The beam illuminated computer cables and server racks.
</p>
<p>
He turned his attention back to Moshen. “License, registration, and insurance.”
</p>
<p>
Moshen fished the paperwork out of his wallet and the van’s glove compartment. “Was I doing something wrong, Officer?”
</p>
<p>
The cop took the papers and turned around unceremoniously. “Maybe you were, maybe you weren’t.” His boots on the gravel receded beat by beat toward the squad car.
</p>
<p>
Moshen leaned back in the driver’s seat and tried to relax. Minutes passed.
</p>
<p>
He heard a ringback tone in his Bluetooth earpiece.
</p>
<p>
Tina’s chipper voice said, “You’ve reached the Medina Gallante! How may I direct your call?”
</p>
<p>
The policeman’s voice responded, “This is Lieutenant Wight, with the Bellevue PD. Can I speak to someone in charge?”
</p>
<p>
Tina replied, “I’m the night shift manager. Is everything alright, Officer?”
</p>
<p>
“I just stopped a company wagon en route to your destination. Markings ‘Claymore Communications.’ They got any legitimate business over there?”
</p>
<p>
“Absolutely!” said Tina. “We’re having serious problems with our computer systems. We need them here right away.”
</p>
<p>
“They don’t look right,” said the policeman. “The driver’s not registered to the vehicle. His tax records say he does computer work, but there’s nothing on file tying him specifically to this Claymore Communications company. Dispatch says nobody’s answering Claymore’s phone right now, so we can’t confirm with the registrant. The driver’s name is Moshen Chan. Can you vouch for him?”
</p>
<p>
“Yes,” said Tina. “Little guy, big glasses. We’ve worked with him before.”
</p>
<p>
“There are three additional persons in the vehicle,” the policeman said. “There’s something off about them. They sure as hell don’t look like computer folks. I can have Dispatch send a car out to you guys to keep an eye on these boys, just in case.”
</p>
<p>
“Oh, no, Officer. That really won’t be necessary,” Tina assured. “We wouldn’t want to upset our guests by implying there’s some kind of issue that requires police presence.”
</p>
<p>
“We’ll send plainclothes,” the cop suggested. “They’ll blend right in with the civilian population. It’d be no trouble.”
</p>
<p>
“No, really, don’t,” Tina insisted. “Please, we need those Claymore engineers here quickly. We’re losing revenue.”
</p>
<p>
“Engineers. Right.” The policeman gave a noncommittal grunt. “Over and out.”
</p>
<p>
Moshen glanced at his passengers. They looked like enormous wolves, with snarling fangs and bristling fur, wearing stickers on their chests saying, “Hello, My Name Is <span class="underlined">_Sheep_</span>!”
</p>
<p>
Outside, the policeman’s footsteps slowly approached.
</p>
<p>
“Guys!” Moshen said to the Russians. “Quick! Act like nerds!”
</p>
<p>
Sergey raised an eyebrow. “What?”
</p>
<p>
“<em>Act like nerds!</em>”
</p>
<p>
Eugene and Leo looked at one another dumbly for a moment. Then, Leo tentatively said, “I like computers…?” Eugene replied, “I <em>love</em> computers.” Leo answered, “Me too! I love computers so much!” “Computers are best! I can’t computer enough!” “Oh man, you should see this computer I computered the other night. It had the hottest circuits…”
</p>
<p>
Sergey, for his part, merely sat in the passenger seat, quietly picking his nose.
</p>
<p>
The policeman returned just long enough to hand Moshen back his cards. He muttered a perfunctory, “Drive safe,” and ambled back to his cruiser.
</p>
<p>
The Asian kid let out a deep, cathartic sigh, and slowly pulled back onto the road.
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Danny watched the van</span> roll through the gate. He leaned against a concrete pillar in the hotel’s garage level, illuminated by jaundiced fluorescent lamps. The vehicle drove to a secluded corner of the underground parking structure.
</p>
<p>
Moshen cut the engine, hopped out, and came around to open the rear doors. Danny was greeted by the familiar sight of Claymore’s field installation equipment and on-site troubleshooting tools. A spectrum analyzer, a portable power supply, and a short Yagi antenna jutted out from the disheveled pile of electronics. In the past six years, he’d taken this van to more trade shows and vendor demonstrations than he’d care to remember. With Claymore now closed and its assets pending sell-off, this mission to the Medina Gallante would be this van’s last expedition.
</p>
<p>
The van rocked gently on its suspension as Sergey stepped out. The side door slid open, and Eugene and Leo emerged.
</p>
<p>
Danny put the red toolbox on the ground.
</p>
<p>
“First, let’s get you guys on comms,” he said. He opened the box. Inside, mixed in among some decoy hammers and screwdrivers, were several fully charged cellphones and Bluetooth headsets. He handed the communication gear out to the Russians, and after a few iterations of, “Testing, testing… Can you hear me now…?”, he confirmed that they were all joined to the conference call.
</p>
<p>
Moshen walked away to stand watch. The three Russians came around to the back of the van and dug through the piles of cables and electronics.
</p>
<p>
Buried beneath the boxes lay a mobile armory.
</p>
<p>
Sergey extracted a vest of grayish-black body armor, long and bulky with hard, blocky plates. He donned it over his clothes and fastened its buckles. Onto his head he pulled a heavy-looking full-faced black helmet with a thick clear visor. He strapped a tall black rectangular shield to his left arm, large enough to cover his body from knees to face, with a wide transparent window embedded near the top to allow for vision. In his right hand he held a MAC-10, complete with suppressor, folding stock, laser sight, and extended magazine.
</p>
<p>
He looked like a tank on two legs.
</p>
<p>
Leo, the gunman who had shot Danny in the shoulder twenty-four hours ago, wrapped himself in a ballistic vest and helmet like the ones on Sergey. Instead of the shield and MAC-10, though, Leo opted for a spiny black multi-component rifle with enough switches and levers to rival a church organ. It was about as long as a man’s arm, and looked so complex that it seemed like it could suddenly unfold into a thirty-foot-tall anthropomorphic alien robot at any moment. A sophisticated scope ran along its top. A ridged hollow tube, about as big as a cardboard paper towel roll, hung beneath its barrel. The precision engineering of the many modular interlocking pieces astounded Danny; looking at the weapon, it was clear to him that the people who developed that firearm knew as much about alloys and ballistics as he knew about computers and electronics.
</p>
<p>
“What the hell is that?” Danny couldn’t help asking.
</p>
<p>
“This?” said Leo with a grin as he checked the intricate parts of the weapons system. “This is standard-issue M4 carbine. It has suppressor and muzzle break, M68 CCO reflex sight and an M203 grenade launcher.” He held it up proudly. “I call her Matilda.”
</p>
<p>
“A grenade launcher? Guys, that was not part of the plan!”
</p>
<p>
“You stay with computer stuff,” said Leo. “Leave the fighting stuff to us. You don’t tell us how to do our job, we won’t tell you how to do yours. Deal?”
</p>
<p>
“Does your job involve picking out pieces of Sergey’s daughter from piles of gibs and putting her back together with duct tape?” said Danny.
</p>
<p>
Leo rolled his eyes and scoffed, “Idiot.” The Russian gunman reached into the van and pulled out a black rubber cylinder, rounded on one side. It was shaped like a bullet, but about the size of a pill bottle. “We use this,” he said, holding the object up in front of Danny.
</p>
<p>
“What is it?” Danny asked.
</p>
<p>
Leo grinned. “It is how you make an entrance.”
</p>
<p>
Sergey laughed lightly. “It is forty-millimeter spin-stabilized flash grenade. You do not want to be looking at it when it goes off.”
</p>
<p>
Leo smiled, shook his head, and said mirthfully, “Nooooo, you really, really don’t!” The two seemed to share an inside joke of some kind &mdash; a recollection, perhaps, of battles past.
</p>
<p>
A few feet away, Eugene practiced turning, twisting, and kicking in his gear. He opted for a thinner, lighter ballistic vest and a bowl-shaped open-faced helmet, affording him fast, easy movement.
</p>
<p>
Sergey passed him a bigger helmet, with side coverage and a faceplate like the kind he and Leo wore.
</p>
<p>
Eugene scoffed at it. “Uncle, that thing is useless! You wear that, you have no idea what’s happening around you. Look…!” He walked up to Sergey, reached his hands out on either side of Sergey’s fully encased head, and began snapping his fingers on alternate sides. “Over here! No, over here! Over here! …See? Nothing.”
</p>
<p>
Sergey mumbled, “Over here, smartass,” and swung his MAC-10 out at Eugene’s unprotected cheekbone, quick enough to startle him but slow enough to not do any real harm. Eugene ducked to avoid the pistol-whipping, and reached up to seize Sergey’s elbow and wrist. Sergey found his arm trapped in a leveraged limb-lock that would’ve sent the gun clattering to the floor if Eugene applied any more force. Sergey responded with a shield-bash, smacking the black polymer bubble against Eugene’s body and sending him stumbling several feet backwards.
</p>
<p>
The two men laughed, and spoke to one another in Russian with warm, familial tones.
</p>
<p>
As they talked and checked their gear, a low rumble arose from somewhere amongst the concrete pillars of the garage. A lone headlight shone from the gate at the entrance.
</p>
<p>
Danny heard the rapid footsteps of Moshen’s sneakers. “Guys! Someone's coming!”
</p>
<p>
The Bluetooth headset in Danny’s ear chirped with Natalie’s voice. “It’s Roger. I can see him on camera.” The gate swung gently open, courtesy of a packet sent by Satish.
</p>
<p>
A yellow sportsbike rounded the bend of the garage, bearing a tall, sinewy young man. It rolled to a stop next to the van, on the opposite side from the Russians. The driver toed the kickstand to the ground and killed the throaty hum of the motorcycle’s engine. He dismounted and pulled off his helmet.
</p>
<p>
“Roger, I presume?” Danny said in a cordial tone.
</p>
<p>
Roger gave him an acknowledging grunt, and reached into one of the bike’s saddlebags. He pulled out the sealed Pyrex bowl. “Here’s your shit.”
</p>
<p>
Danny took the glass vessel. “Thanks, man,” he said earnestly. He laid his HERF gun on the ground and knelt down to stash the bowl deep inside the large toolbox.
</p>
<p>
“Hey, is that the EMP rifle?” Roger asked. “I seriously can’t believe you actually built one of those. Are those blue things on the end capacitors? What kind of range can you get on it? Can I try it?”
</p>
<p>
Danny looked up to see Roger staring at the HERF gun with eyes filled with wonder. His fingers wiggled slightly in the hope of getting to touch the device. Danny couldn’t help but smile. He picked up the gun as he stood back up. “You see,” he said to Roger, pointing proudly to a small assembly connected to the spine of relays, “the real magic is in the DC voltage amplifier circuit. It’s a tradeoff against current, but the ultracaps pump out current to spare, so…”
</p>
<p>
Roger nodded excitedly, like a child being told exactly what the tooth fairy does with all those molars. “Right! I get it,” he said. “At least, um, I think I do. I mean, I mostly just do net admin stuff. Is electrical engineering hard to learn?”
</p>
<p>
Danny beamed at him kindly. “Well…”
</p>
<p>
His attention was pulled away by the sound of Satish’s voice in his earpiece. “Danny, are you there?”
</p>
<p>
Danny turned away from Roger. His face hardened as his concentration returned. “Yeah, Satish. What’s up?”
</p>
<p>
“I have good news and bad news. Good news: I’ve been able to find several X10/IP bridges, and I can detect IP-encapsulated X10 packets all over the network.”
</p>
<p>
“That’s <em>very</em> good news,” said Danny. “What’s the bad news?”
</p>
<p>
“There’s a huge number of X10 controllers in the building,” said Satish, “and I can’t tell which ones correspond to the Presidential penthouse. Mike and I were studying it for the last few minutes, and we can’t come up with a good approach except for divide-and-conquer.”
</p>
<p>
“I’ll get you some additional manpower,” said Danny. “Moshen!”
</p>
<p>
“Yeah?” Moshen asked, still dazed.
</p>
<p>
“You’re on the conference call,” he said. “This X10 issue that Satish is talking about. Can you help?”
</p>
<p>
Moshen hesitated. “Uh… What’s an X10?”
</p>
<p>
“Home automation,” Danny explained. “It’s a language spoken by electronic appliances around the house. Lights, heating, air conditioning, entertainment systems, that kind of thing. The Gallante has its rooms wired with X10 devices, and Satish and Mike need a hand figuring out which ones are in the Presidential Suite. Can you help?”
</p>
<p>
Moshen recoiled. “I just build websites, Danny. I mean, I can try…”
</p>
<p>
Danny sighed, and went to the back of the van to dig a laptop out of the electronics. “Roger?” he asked.
</p>
<p>
“Yeah?” Roger replied uncertainly.
</p>
<p>
“Wireshark,” Danny said briskly as he dusted off the old computer. “tcpdump. nmap. netcat. dd.”
</p>
<p>
“Network probing tools,” said Roger. “What about them?”
</p>
<p>
“Can you use them?” he asked, booting up the laptop.
</p>
<p>
“Well, yeah…” said Roger. “Why? What do you…?”
</p>
<p>
Danny shoved the laptop into Roger’s hands. “Congratulations, you’ve just been drafted. Satish and Mike will get you caught up. Tina, can you link him to the voice bridge?”
</p>
<p>
Roger took the laptop with an uncertain shrug. He set it on the hood of the van and got to typing.
</p>
<p>
From around the other side of the van, the deep voice of Sergey rumbled. “Can we get moving yet? It is getting hot in this suit.”
</p>
<p>
“Let me check,” Danny replied. “Mike and Natalie! Have you found a path these guys can take through the building without being seen?”
</p>
<p>
Mike’s voice buzzed in the earpiece. “Yes. Up the back stairs &mdash; it connects to the hotel’s rear maintenance corridor.”
</p>
<p>
With an approving nod, Danny grabbed his HERF gun and his toolbox. “Then let’s get moving.”
</p>
<p>
The Russians emerged from behind the van, marching into view in their battle dressing. Roger stared slackjawed as they appeared, and instinctively backed away slowly.
</p>
<p>
Danny began to lead them to the garage’s rear stairwell.
</p>
<p>
Eugene called out, “Hey, hold on! Almost done here…” He knelt over a backpack and a large spool of black nylon rope. He was in the process of cutting two- and three-foot lengths of cord with a serrated blade and putting them into the backpack.
</p>
<p>
Roger said wide-eyed, “Do I even want to know what that’s for?”
</p>
<p>
“The rope?” said Eugene. “It’s for many things.” He finished the last of the cuts, then hurriedly stuffed the rest of the spool into the backpack and slung it over his shoulder. “But first,” he added, “it’s for making a few inconvenient people go away.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Dominga Torres was a stout, brawny woman.</span> Under her uniform, her abdomen still bore a calligraphic “Chola 4 Life” tattoo, an embarrassing reminder of her gang-fueled teen years in East L.A.. Much of her early life was spent in and out of juvenile detention centers, cursing authority figures with vows of vengeance. But when she became a mother, she took serious stock of herself and the kind of world she wanted her babies to live in. Her dream now was to land a position with the LAPD, and then see the expressions on her old friends’ faces when she’d come back into her old hood on the other side of the thin blue line. But for now, she carried no gun, and her badge was simply a token brass shield printed with the words “Security Guard”, provided to her by the Medina Gallante.
</p>
<p>
A female voice squawked from the walkie-talkie on her hip. “Attention all Gallante security staff. If any remaining personnel have not yet received their individual briefing on tonight’s training exercises, please respond.”
</p>
<p>
The voice had been buzzing from the radio for the last half hour. The unfamiliar woman identified herself as a dispatcher from RockBox Digital Security, the company that had built the Gallante’s camera and radio systems. Torres had listened to the chatter as her fellow guards had been called up, one by one, to discuss some kind of new procedure that RockBox wanted them to follow.
</p>
<p>
Torres took one last long drag from her cigarette before extinguishing it in the outdoor ashtray. She brought the walkie-talkie up to her face. “This is Dominga Torres to Dispatch, responding as requested. Just finishing a smoke break. I’ve received no notice about any training exercises scheduled for tonight. No memos, no emails, nothing on the calendar. What’s this all about? Over.”
</p>
<p>
The voice said, “RockBox sent an email outlining the new procedures last week. It appears that most Gallante personnel didn’t receive it. We think we had a glitch with our email systems, and we deeply apologize for any inconvenience.”
</p>
<p>
The woman on the radio channel didn’t say “Over”. Torres was irritated by the lack of adherence to proper voice protocol.
</p>
<p>
“So, what do you need me to do? Over,” Torres asked.
</p>
<p>
“Please report to the security office,” the voice said. “Our field agent will give you an in-person outline of your role in tonight’s activities.”
</p>
<p>
“On my way,” said Torres. “Over and out.”
</p>
<p>
She reentered the building from the smoking balcony and marched through the wide posh passages of the Gallante, feeling comfortably dominant in the maze of halls and stairways that she spent every day dutifully protecting. A trip down an elevator and through a side door marked “HOTEL STAFF ONLY” placed her in a drab white corridor lit by faintly humming fluorescent bulbs.
</p>
<p>
Torres strode up to an unremarkable gray door with a black placard printed with “SECURITY” &mdash; her base of operations. She rapped her knuckles against its drab surface.
</p>
<p>
The door opened inward, apparently under its own power. Whoever opened the door stood behind it rather than coming out to greet her.
</p>
<p>
Through the doorway, she could see the main security console. It consisted of a large desk rigged with a radio dispatch board, a computer station, a 9-1-1 hotline, and a dozen
</p>
<p>
display screens showing feeds from the hotel’s security cameras. It was normally occupied by Karl or Arnie, who would’ve been sitting in the swivel chair and glancing at the bank of screens while watching movies and eating sandwiches. But the swivel chair was empty; the security console, against protocol, was left unmanned.
</p>
<p>
If there was one thing she learned in East L.A., it was how to spot a set-up.
</p>
<p>
She backed away and reached down to grab the walkie-talkie at her belt. Goosebumps on her neck and arms brushed electrically against the inside of her uniform.
</p>
<p>
Her back pressed against something pointed and solid.
</p>
<p>
She heard a click behind her. It was a very distinctive sound: a revolver’s hammer being cocked.
</p>
<p>
“Don’t turn around,” a voice said. It had an accent. European of some kind. “And don’t scream.”
</p>
<p>
Her breathing quickened. Her mind raced with options.
</p>
<p>
Spin, duck, bump his arm upward, and go mano-a-mano.
</p>
<p>
Feign crying.
</p>
<p>
Reply in Spanish and pretend she didn’t understand the instructions.
</p>
<p>
But she couldn’t see how big he is, how old, how competent. Was he nervous? Was he angry? Was he desperate? She didn’t have enough situational awareness to decide on a viable escape plan. She had to cooperate for long enough to find out what was going on.
</p>
<p>
Moving slowly, Torres spread her arms out and lifted them above her head. “What do you want?” she said quietly.
</p>
<p>
“Please step through the doorway,” said the voice.
</p>
<p>
Her spirit bucked in defiance. She suppressed her instincts and forced herself to comply.
</p>
<p>
When she was finally inside the office, she saw Karl and Arnie and the rest of her fellow security staff. They were all gagged and bound with cords of nylon rope. Every last one of them. Their arms were tied to the hinges of interior doors, to a water pipe that ran through the office, to hooks inside their equipment lockers. They followed her with their eyes as she entered the room, each one’s face silently screaming.
</p>
<p>
And standing several feet from them, ensuring their silence, was a man with black IOTV body armor, a full-faced helmet, and a highly accessorized M4 rifle.
</p>
<p>
The intruder who had opened the door closed it behind her. He stepped into her view, and pointed a MAC-10 at her torso. He was an enormous behemoth of a man, with substantial bulk under his combat suit. A black riot shield was strapped to his left arm. Through the visor of his helmet, she saw that his eyes were determined and professional.
</p>
<p>
This was not a mere robbery. This was some kind of full-scale military operation.
</p>
<p>
The Medina Gallante was frequently visited by foreign dignitaries. She had always entertained the notion that, at some point, some high-value political target would appear on its guest roster. That day must have finally come.
</p>
<p>
The voice behind her spoke. “Slowly lower your hands and put your wrists together behind your back.”
</p>
<p>
The voice’s European accent clinched the conclusion in her mind. This was a surgical Special Ops attack by a foreign power. Every man, woman, and child in the Gallante was in extreme danger.
</p>
<p>
Her fellow guards had all been rendered helpless. The hotel kept eight security personnel on duty at a time. All seven of her colleagues were already there, captured in their own office. Torres was the last one left.
</p>
<p>
She took a deep breath. She began to lower her arms. But as she brought them down, she simultaneously began bending her knees into a crouch.
</p>
<p>
Her babies would always know that their mommy died fighting for what’s right. For their entire lives, that knowledge would give them strength and guidance in times of trouble. For a gift like that to give to her children, she was willing to pay the cost.
</p>
<p>
She lunged for the security console.
</p>
<p>
On the desk was a 9-1-1 hotline &mdash; a bright yellow telephone handset that connected directly to the Bellevue PD automatically just by being picked up. The police department’s 9-1-1 system would begin recording the call immediately, ensuring that somebody would hear her last words. She grabbed the corded handset and dove underneath the desk.
</p>
<p>
“Medina Gallante hotel under foreign military attack!” she screamed into the yellow telephone. She spoke as fast as she could, trying to squeeze out as much information as possible before getting riddled with bullets. “Private security incapacitated! Attackers equipped with automatic rifles and combat armor…”
</p>
<p>
Her voice trailed off. She hadn’t expected to survive long enough to say more than half a dozen words. There were no blasts of gunfire, no bullets flying.
</p>
<p>
But there was no 9-1-1 dispatcher answering the line, either.
</p>
<p>
The three soldiers stared at her in astonishment.
</p>
<p>
The goliath with the shield and the MAC-10 simply said, “Holy crap.”
</p>
<p>
The man with the M4 said, “That took some serious balls, lady.” To the rest of the captive security personnel, he said, “Did you guys see that? <em>That</em> is how you do your job!”
</p>
<p>
Torres looked back and forth at the three invaders, confused.
</p>
<p>
The man who had snuck up behind her wore a light ballistic vest and a bowl-shaped open-faced helmet, and carried a silver snubnose .44 Magnum.
</p>
<p>
“I have good news and bad news for you,” he said. “We’re not here to hurt you. We just need you out of the way. That is the good news. But the bad news is, that phone was cut off before we even got here.”
</p>
<p>
The yellow handset vibrated in her hand. “Hey. Ms., um, Torres, was it?” It was a woman’s voice &mdash; the same voice as the one on her radio. Torres looked at the handset in utter bewilderment. “I’m… I’m really, really sorry.”
</p>
<p>
“Who the hell are you people?” Torres hissed.
</p>
<p>
The man in the light vest gestured with his revolver. “That was incredibly heroic, what you did just now,” he said. “You should be very proud of yourself.” He reached into a backpack on the floor, and pulled out a few lengths of nylon rope. “But don’t try it again.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">The Gallante’s exercise and recreation facilities</span> comprised the entire ground floor of the hotel’s south wing. The treadmills and weight machines were populated sparsely, but the massage tables and tanning beds saw plenty of use. The Finnish saunas, complete with birch boughs, were always a favorite among eastern European guests. Especially Russians.
</p>
<p>
In one of the small, slightly steamy rooms, three muscular men sat naked on white towels laid across wooden benches, talking boisterously in Russian at volume levels much greater than necessary.
</p>
<p>
“So, her husband’s still twitching on the ground, right?” one man regaled his two fellows. “And she’s, like, blank. You know how they go completely blank, right? And I just smile at her and go, ‘Cheer up, honey! You’re going to die tonight anyway, you might as well do it in a good mood!’”
</p>
<p>
The two other men burst out in raucous laughter. “You’re one cold bastard, man!” one said as a compliment.
</p>
<p>
“So what did she do?” asked the other.
</p>
<p>
“Well, check this out,” he continued. “I had her tied up with rope, so I thought I could take my time. So I’m going through the apartment, looking for the merchandise, when I hear this, ‘Click! Click-click…!’ So I make my way back to her and take a peek…”
</p>
<p>
“Was it a gun?” one man asked.
</p>
<p>
The storyteller shook his head.
</p>
<p>
“A telephone!” the other said.
</p>
<p>
“Nope.”
</p>
<p>
“So what was it?”
</p>
<p>
The storyteller pantomimed putting a cigarette in his mouth and cupping his hands to light it.
</p>
<p>
“A lighter?”
</p>
<p>
“Yes! A cigarette lighter! She managed to dig it out of her pocket, and she sort of, like, twisted her hands around…” He mimicked. “…to get the flame right onto the rope, so it would burn right through.”
</p>
<p>
“Daaaaamn!” said one of the listeners. “Clever girl!”
</p>
<p>
“I know, right? Must’ve hurt like the Devil, with the fire on her wrists, but she figured it’s better than the alternative. She’d have gotten away with it, too, if I hadn’t heard. She actually managed to get her hands free while I watched her. She was pulling at the knots around her legs when I finally decided, ‘Okay, that’s enough.’”
</p>
<p>
The rowdy talker reached toward a sleek control board mounted near the frosted-glass door of the tiny room. With the press of a button, nozzles recessed in the wood-paneled walls emitted a quick hiss of steam. He waved an arm briskly through the puffs, relishing the sensation against his skin.
</p>
<p>
“Moral of the story,” he concluded as he basked in the heat. “When you’re tying someone up with ropes… Make sure they’re not a smoker.”
</p>
<p>
The men laughed lightly. Moisture condensed on their naked bodies and beaded with their sweat. Wet droplets ran down their faces and chests as they took deep, slow breaths.
</p>
<p>
One of them was beginning to take slightly bigger gulps of air than the others. “Hey, do you guys like it turned up this high?” he asked tentatively
</p>
<p>
The others hesitated for a moment. Finally one said, “It feels maybe a little hotter than it should.”
</p>
<p>
They looked at the control board. A small black screen reported the current temperature: <span class="computer">230°F (110°C)</span>.
</p>
<p>
“Yeah, that’s a little too high,” one conceded, and pressed a down-arrow button repeatedly until the screen displayed <span class="computer">170°F (80°C)</span>.
</p>
<p>
They let a minute go by, but felt no improvement. All three of them began breathing a little bit more heavily in the thinning air.
</p>
<p>
“I thought you turned it down,” said one.
</p>
<p>
“I did! Look!”
</p>
<p>
The screen again showed <span class="computer">230°F (110°C)</span>.
</p>
<p>
“Idiot doesn’t know how to work the sauna,” one mocked.
</p>
<p>
“Shut up, asshole,” one said, and punched it back down, watching the numbers descend until they again hit <span class="computer">170°F (80°C)</span>.
</p>
<p>
The moment he took his finger away from the control, the numbers immediately jumped back up to <span class="computer">230°F (110°C)</span>.
</p>
<p>
“What the hell?”
</p>
<p>
He pressed and held the down-arrow button until it went as low as it would go, to <span class="computer">120°F (49°C)</span>. As soon as he released it, it jumped back up to <span class="computer">230°F (110°C)</span>.
</p>
<p>
“Stupid piece of crap,” one said. “I’ll go yell at someone about it.” He rose, wrapped the white towel he was sitting on around his waist, and pushed on the frosted door.
</p>
<p>
It moved about an inch, and then hit some kind of restraint.
</p>
<p>
He pushed against it harder. It wouldn’t budge.
</p>
<p>
Outside, through the frosted glass, a silhouette of an athletic man appeared just beyond the door. He appeared to be wearing a small helmet and a very bulky suit.
</p>
<p>
“Brothers!” said the man, in Russian. “How are you doing in there? Nice and warm?”
</p>
<p>
The men sat up shocked in their seats. Their hearts began to race.
</p>
<p>
One began pounding on the glass with his fist. “What the hell is this!?”
</p>
<p>
“This?” the man outside said amicably. “This is nothing! It’s just a… a friendly conversation.”
</p>
<p>
“Who the hell are you?” one yelled.
</p>
<p>
“Oh, I’m nobody! Nobody at all! But I do have a matter of pressing business with someone named Ivan Zheleznov. Perhaps you fellows have heard of him?”
</p>
<p>
One stood and body-checked the door, his shoulder slamming hard against the glass. It proved fruitless.
</p>
<p>
“I really wouldn’t do that if I were you,” the man said mischievously. “All that physical exertion. You might work up a sweat.”
</p>
<p>
“Let us out, you vermin!” one screamed, and had to sit down to gasp for air. Each breath singed his lungs.
</p>
<p>
“Not until we talk for a little bit,” the man said.
</p>
<p>
“What the hell do you want?” one said, feeling dizzy.
</p>
<p>
“Well, brothers, you see, it’s not really my interest per se,” he said, “but I have some colleagues here who would like to know one slight, insignificant little piece of information. When Ivan pays you, what bank do the payments come from?”
</p>
<p>
“Bank?” one said, fighting rage and fear as the room boiled around him. “We get paid in cash! He gives us envelopes every week.”
</p>
<p>
“Are you saying he’s never written you a check or sent you a money transfer? Ever? Not even from one of his proxy corporations?”
</p>
<p>
The men murmured amongst one another. One said, “Maybe at some point. How the hell should we know? None of us would remember the bank it came from, anyway.”
</p>
<p>
“Well, we’re going to find out!” said the man in jovial tones. “Here’s what’s going to happen, buddies. You’re each going to tell me which banks you keep your money in, and you’ll give me your logins and passwords to your online accounts. And my colleagues &mdash; they’re in control of your temperature, by the way, and can make you as comfortable or uncomfortable as they see fit &mdash; they’re going to sift through your banking histories until they find checks or transfers from accounts connected to Ivan. Any additional info you guys can provide to expedite that search will of course make the whole thing go much more quickly.”
</p>
<p>
“Go choke on a dick, asshole!” one shouted back at him. “We’re not going to hand over our online bank accounts to you!”
</p>
<p>
“I think you will,” said the man. “And I’d like to remind you that my colleagues are listening to me right now and are ready to use your login information immediately, so it’ll do you absolutely no good to lie. All it’ll do is waste your breath.”
</p>
<p>
“Rot in hell, you filthy piece of scum!” one screamed as he struggled, weakening, against the door.
</p>
<p>
The man simply chuckled. He leaned against the glass from the outside, calmly said, “Let me know when you guys are ready,” and began whistling a cheerful, upbeat tune.
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Ivan Zheleznov was freezing.</span> His hoarse voice rattled in the mouthpiece of his room’s desk phone.
</p>
<p>
“How is problem billing?” he was saying irritably, in English or some likeness thereof. “Is not to me bill for room. Is to American company. Tungsten Medical Technologies.” He fumbled the syllables a few times.
</p>
<p>
Tina’s voice replied on the line, “Tungsten placed the reservation, yes. But they didn’t pay. They gave us an International Bank Account Number corresponding to a private investment fund in Estonia. The IBAN begins with EENN BB24, and ends with 5177. Is this account associated with you?”
</p>
<p>
“Yes, yes, yes,” Ivan mumbed, his breath hissing through his teeth. “Is payroll account for Consortium operations. How in Devil you get this bank number?”
</p>
<p>
“We attempted to bill that account, sir, but the charge wouldn’t go through.”
</p>
<p>
“Of course it not go through!” Ivan barked. “Not for you to charging me!” He stuttered, partly from his poor grasp of the language, partly from the chilly air. Ivan added, “Now hurry up and bringing someone to fixing cold! Air condition is going crazy!”
</p>
<p>
Politely, Tina said, “We’re terribly sorry for the malfunction of your air conditioning, sir. We’re sending a repairman to look at it right away.”
</p>
<p>
“You fixing right now!” said Ivan. “And you talking to the Tungsten about bill. Not me bothering with. Understand?”
</p>
<p>
“Sir, about that bank account…” Tina said carefully. “There’s a problem with it that requires your personal immediate attention.”
</p>
<p>
“My attention?” Ivan scoffed. “You know who I even? I not dealing with problems of money between banks. This for people I hire worrying about.”
</p>
<p>
“Sir,” Tina said grimly, “the charge was blocked because the account has been frozen by Interpol.”
</p>
<p>
“Frozen by Interpol?” Ivan repeated. “What this is meaning?”
</p>
<p>
“I have a message here on my screen, sir,” Tina said. “‘Fund request declined due to Interpol law enforcement investigation in progress.’”
</p>
<p>
“That is impossible!” Ivan howled.
</p>
<p>
“Would you like me to call the bank, sir? I can talk to them right now.”
</p>
<p>
“Yes!” Ivan demanded.
</p>
<p>
“Please wait while I try to reach them,” said Tina. “In the meantime, do you have a computer with you? Can you access your account online? There may be additional information available on the bank’s website.”
</p>
<p>
Beneath grumbled Russian curses, Ivan tapped on a laptop keyboard.
</p>
<p>
The Russian curses suddenly grew much louder.
</p>
<p>
“I get mistake!” Ivan barked into the phone.
</p>
<p>
“You made a mistake?” Tina asked.
</p>
<p>
“No, computer make mistake,” Ivan growled. “No website. Only big mistake. Big red mistake words.”
</p>
<p>
“You mean an error message, sir?” Tina suggested.
</p>
<p>
“Yes. Yes, Internet giving me error message. It saying, ‘The site’s security certificate is not trusted,’” he read awkwardly and haltingly, putting stresses on incorrect syllables. “‘You attempted to reach salajane.grazhdopank.ee, but the server presented a certificate
</p>
<p>
issued by an entity that is not trusted by your computer’s operating system…’ What this is? I never see before!”
</p>
<p>
“We’ve been having problems with our Internet connectivity throughout the hotel today,” Tina explained. “We’re terribly sorry for the inconvenience. At the bottom of the error message you should see a button labeled, ‘Proceed anyway’. Click that, and it will dismiss the error and allow you to connect to your bank’s website.”
</p>
<p>
“Your Internet not work, your air condition not work. This hotel is like smelling ass!”
</p>
<p>
“We greatly apologize for any inconvenience. Have you been able to log in yet?”
</p>
<p>
“Yes, I am right now log in,” said Ivan. “I see bank account as normal. No mistakes, no notes, no problems.”
</p>
<p>
“I have an English-speaking account representative from the bank on the other line,” said Tina. “Let me talk to them for a minute. Please hold…” She returned after a minute of silence. “Sorry for the delay, sir. Apparently they froze the wrong assets. There is no Interpol investigation on your account after all. The freeze alert was simply a misunderstanding.”
</p>
<p>
“Misunderstanding?” Ivan grumbled.
</p>
<p>
“Yes, sir. The bank made a mistake.”
</p>
<p>
“So is no problem?” he confirmed.
</p>
<p>
“None at all, sir,” said Tina. “And as for the room charges, we’ll discuss the matter with Tungsten at our earliest opportunity. Don’t worry, sir &mdash; we will not bill your account without further clarification.”
</p>
<p>
“Good, good. Now hurry to sending man to air condition fix!”
</p>
<p>
“He’s on his way, sir,” Tina replied. “Have a good day.”
</p>
<p>
With a soft click, she hung up.
</p>
<p>
That was Danny’s cue.
</p>
<p>
Danny stood in an undecorated emergency stairwell that ran down the full height of the building's main wing, listening silently on his Bluetooth earpiece to the dialog between Tina and the Russian kingpin. On the cellphone synced wirelessly to the headset, he typed out a soundless text-based conversation with Satish and Mike. His team was carefully rerouting a stream of SSL/TLS packets between the Gallante and a data center somewhere in Estonia, craftily injecting their own double-sided proxy into the digital traffic.
</p>
<p>
He put the cellphone away and picked up the large red toolbox on the concrete landing of the stairwell. His HERF gun was far away, stored safely in the security office where Sergey’s crew sat monitoring the captives.
</p>
<p>
With a deep breath that echoed off of the cinderblock walls, he opened an emergency exit door.
</p>
<p>
He stepped out to a wide, elegant penthouse antechamber, with sparkling metallic walls and rich red carpet. One side of the room was a full plate window looking out at the nighttime skyline, adorned with leafy green plants in the corners. The door to the penthouse elevator sat closed next to the emergency exit on one end of the hallway. On the other, a large cedarwood double door stood ominously before him.
</p>
<p>
Danny walked slowly across the room. He shook his head and arms limply to try to force himself to relax, and tapped his knuckles on the door. He stood patiently, toolbox in hand, waiting for a response.
</p>
<p>
There was shouting in Russian from inside the room. After a few long moments, a lithe, aggressive-looking man opened the door. He wordlessly bobbed his head to the side, motioning for Danny to come in.
</p>
<p>
The air in the suite was irritatingly cold. A fierce draft blew through the room, strong enough to make hair wave and clothes billow. The balcony’s French doors had been opened wide in an attempt to let out the cold.
</p>
<p>
On the balcony, a few leather-jacketed men and barely-dressed women smoked and chatted in the outdoor air. Inside, a small group played <em>Call of Duty</em> on an enormous wall-mounted plasma TV in a sunken living room. On the dirty-looking glass coffee table, somebody had suspiciously thrown a hotel towel over a large crystalline bowl to conceal its contents. Several other men merely stood around in a small kitchen area or by a wide spiral staircase, eyeing Danny suspiciously. He saw no weapons out in the open, but he had no doubt they were very close at hand.
</p>
<p>
Danny looked around. No twelve-year-old girl was anywhere to be seen.
</p>
<p>
He did, however, see Ivan Zheleznov.
</p>
<p>
The man descended the spiral staircase like a gray hawk swooping down on a field mouse. He wore a fine three-piece suit and slicked-back silver hair. Despite being the oldest and physically weakest man in the room, the force of his presence imposed a greater degree of intimidation, a greater sense of immediate peril, than any of his bodyguards.
</p>
<p>
“You come to fixing the air, yes?” he said loudly to Danny in a dry, gravelly, impatient voice.
</p>
<p>
“Yes,” said Danny. He scanned the room carefully, memorizing the topology and mentally counting the mercenaries.
</p>
<p>
He found the thermostat on the wall. Danny walked up to it and lingered for several seconds, pretending to study it and tapping at its unresponsive controls.
</p>
<p>
“The thermostat looks fine. I think there’s a loose heating element somewhere near the sensor,” Danny bluffed. “I’ll need to check your ducts.”
</p>
<p>
He scanned the walls, and found an air vent near the ceiling. He marched toward it with as much bravado as he could muster, and pulled a chair over to the wall so he could stand on it for a closer look. The vent was about two feet wide and a foot tall. The frosty air blasted him in the face as he looked inside the vent’s faceplate, blowing around his helmet and across his ears.
</p>
<p>
Holding his head level with the opening, he turned to check the view of the room. He could see most of the open downstairs area of the penthouse. This vent would serve him well.
</p>
<p>
With the help of a screwdriver from his toolbelt, he removed the grating over the opening. He spent several moments pretending to examine the dark interior of the air shaft.
</p>
<p>
“It, uh, looks like the ventorical airfoil router is jammed,” he said.
</p>
<p>
He turned to study the expressions of the Russians, trying to gauge their reactions. They remained emotionless, showing no response save for their desire for him finish his efforts.
</p>
<p>
The rest of his work would have to be done sleight-of-hand.
</p>
<p>
Danny picked up his toolbox and brought it up to the vent. The opening was big enough for him to rest the toolbox partway in the air duct, allowing him to use the red metal
</p>
<p>
container to obscure his hands from the watchful eyes of Ivan and his men. Danny cracked the lid open and dug noisily through the box’s contents. Metallic echoes of rummaging reflected back at him in the flowing air.
</p>
<p>
From inside the toolbox, he inconspicuously fished out a cellphone. It was a rather small, underpowered model, but it had what he needed: a camera. Working inside the cold, windy air duct, he covertly woke the device from sleep mode.
</p>
<p>
Using his body to hide his actions, he wadded up a ball of Sticky Tack putty and used it to affix the cellphone to the inside of the air vent, making sure to angle the device’s camera to let it see out over the entire room.
</p>
<p>
From his Bluetooth earpiece, Mike’s voice spoke in tinny tones. “I know you can’t talk right now, Danny,” Mike said. “Just wanted to let you know that we’re seeing a stream from the in-room cam. Right now all we can see is you, but once you’re out of there it should be good enough for situational awareness.”
</p>
<p>
He pulled out his toolbox, reattached the faceplate, and climbed down from the chair. The men looked at him expectantly.
</p>
<p>
“Just as I thought. There’s a jam in the central overflow valve,” he said with as much credibility as he could feign. “It’s down in the HVAC room. I can’t fix it from here.” The men said nothing. “I’ll… uh… get right on it.”
</p>
<p>
With toolbox in hand, he practically sprinted through the cedarwood doors out to the penthouse anteroom. Courtesy of Satish, the elevator was already waiting for him. Danny said nothing to his team during the brief muzak-accompanied elevator ride down to the lobby floor. He walked briskly and silently through the opulent lobby, past the bank of elevators
</p>
<p>
and through the door marked “HOTEL STAFF ONLY” into the drab white fluorescent-lit maintenance hallway. He found the plain door marked “SECURITY,” darted through it, and leaned on it heavily as he closed it behind him.
</p>
<p>
Sergey stepped away from the rope-bound captives and approached him. “Well?”
</p>
<p>
Danny let out a long, nervous breath. “Well.”
</p>
<p>
The office served as a holding cell not only for the Gallante’s security staff, but also for a trio of sweaty, pink-skinned Russians clad in nothing but white towels and fresh bruises. Danny set his toolbox down next to his HERF gun, which stood propped against the wall in a nearby corner, sipping power from an electrical socket.
</p>
<p>
“Did you see my Rosie?” Sergey asked.
</p>
<p>
“No,” Danny replied, “but I know they’re holding her on the second floor of the suite. On the main floor I counted ten soldiers. There may be more upstairs.”
</p>
<p>
Sergey looked down somberly. “Too many,” he said.
</p>
<p>
Eugene, from across the room, snorted with derision. “Against the three of us, Seryozha? It is not fair. Those poor fuckers. Almost I feel bad for them.”
</p>
<p>
Sergey shook his head. He spoke to Eugene in a tone that conveyed a complex mixture of apprehension, determination, and love. “<em>Molodoi kazyol!</em> Battles can go wrong, nephew. Risking myself is okay, I am fine with. But risking you? Risking Rosie? Risking Leo? That is only a path we take if we have no other options.”
</p>
<p>
“So what is the plan, then?” Eugene insisted.
</p>
<p>
Sergey pointed to Danny.
</p>
<p>
Danny looked down and said nothing. His head pounded sorely. He felt tired and dehydrated &mdash; almost like he was hung over.
</p>
<p>
Sergey stepped closer to him, about to say something.
</p>
<p>
Danny raised his hand to silently ask Sergey for some space and patience.
</p>
<p>
Speaking softly into the Bluetooth headset, Danny said, “Jason, are you there?”
</p>
<p>
Jason’s voice said in a businesslike tone, “I’m here, Danny.”
</p>
<p>
“How’s our little show coming?”
</p>
<p>
“It’s done,” Jason said.
</p>
<p>
“What about my hacker crew?” Danny asked. “Mike? Satish? Moshen? Hell, Roger, even? Are we ready to go?”
</p>
<p>
Satish said, “Yes, Danny. We’ve set their room temperature back to normal so it looks like repairs were a success. Next step is all yours.”
</p>
<p>
With a deep breath to bolster his confidence, Danny rose from his chair.
</p>
<p>
“Okay, then,” he said. “Here’s what’s going to happen. I’m going to come back down to the docks and join Jason in the boat. I’ll deliver the presentation from our command center there. Sergey’s crew will move into ready positions outside the Presidential Suite, and one of them will drop off our little Tupperware box just outside the door. We’ll watch the video feed from the cellphone in the air vent, and we’ll use it to gauge their reaction. If it works, they’ll turn over Sergey’s daughter peacefully, and Sergey will be there to claim her. If it doesn’t, it’ll at least give Sergey’s crew a tactical advantage.”
</p>
<p>
He picked up the toolbox and was about to hand it to Sergey with a litany of instructions.
</p>
<p>
Mike interrupted him. “Hey, um, Danny?” the large scruffy man’s voice said over the earpiece. “About that vent cam…”
</p>
<p>
“Yeah?” Danny asked. “What about it?”
</p>
<p>
“Have you tried to look at it?”
</p>
<p>
“No, Mike. I’ve been a little busy,” Danny replied.
</p>
<p>
“Maybe you should,” Mike said.
</p>
<p>
A chill ran down Danny’s spine. “Why?…” He reached for the cellphone in his pocket to access the video feed.
</p>
<p>
He got a <span class="computer">Server not found</span> error.
</p>
<p>
He gulped.
</p>
<p>
“I can’t get to it…,” Danny said slowly.
</p>
<p>
Mike said, “Neither can the rest of us.”
</p>
<p>
Danny stared dumbly at the small screen in his hands. “You’ve got to be kidding me…”
</p>
<p>
Natalie’s voice came in. “It was after you put the cover back on the vent, Danny,” she said. “Mike and I think the phone might have come loose from the Sticky Tack. A minute after you left the room, the whole image kind of turned over and went dark, and then a second later the connection died. …”
</p>
<p>
Danny cut her off. “Fuuuuuuuuck!” he groaned. “Oh fucking hell no!”
</p>
<p>
Mike said, “Relax, Danny. It’s just a slight setback…”
</p>
<p>
“Setback? Mike… Mike, this is not a ‘setback’! This is a fucking disaster! That video feed is crucial to the rest of the operation! Without any awareness of what’s going on in that room, we’re completely stuck! We can’t negotiate for the release of Sergey’s daughter, and we can’t expect Sergey’s team to launch an effective assault if negotiations fail. Everything we’ve done up to now was for the sole purpose of setting up that camera feed, and everything we do from this point forward depends on it!”
</p>
<p>
Mike said simply, “Well, Danny, we don’t have it.”
</p>
<p>
With a blank look in his eyes, Danny unclasped the helmet and pulled it off his head, mindlessly letting it fall to the ground. He walked over to a nearby wall and began gently banging his forehead against it, mumbling, “One stupid fucking piece of Sticky Tack…”
</p>
<p>
Tina’s voice chimed across the air. “Danny… Danny, hey… Are you okay?”
</p>
<p>
“Tina. No. No, I’m not okay,” he said, almost whimpering. “I’m a fucking retard. I don’t know why I ever thought I could pull this off. This whole plan is as good as done, and all of this risk was for absolutely nothing, and there’s no way we’re going to get Sergey’s daughter back, and Sergey’s going to literally &mdash; <em>literally</em> &mdash; rip my head off and probably part of my spine dangling along with it, and I fucking deserve it because I’m a goddamned fucking loser that can’t do anything right…”
</p>
<p>
Jason said, “Danny, this is a really bad time for another breakdown.”
</p>
<p>
The earpiece overheard Moshen and Roger in the parking garage below. “Does he get all emo like this a lot?” asked Roger. Moshen answered, “Second time in as many days.” Roger said sardonically, “Way to pick a winner, Tina.”
</p>
<p>
Danny tilted his head and reached one hand to his ear, intending to yank out the Bluetooth headset and throw it to the ground so that he could wallow in the misery of his defeat alone.
</p>
<p>
He was stopped by the thud of Sergey’s heavy hand on his shoulder.
</p>
<p>
Danny expected that hand to pull him away from the wall and beat him to a bloody pulp. Danny didn’t even bother to flinch.
</p>
<p>
Instead, the hand merely gave him a mild shake to get his attention. “Hey. Daniel.” Beneath the visor of his helmet, Sergey’s eyes were warm and sympathetic. Gently, he said, “I not going to rip your head off, okay?”
</p>
<p>
“You’re not?” Danny said with a very quiet, froggy voice.
</p>
<p>
“I know you could have slipped out of this many times now,” said Sergey. “I know you are helping me because you are <em>choosing</em> do to it. I am grateful. You are good man, Daniel. After everything that has happened in a last few days, you should know: you have my faith.”
</p>
<p>
Danny said meekly, “Well, what if your faith is misplaced?”
</p>
<p>
Sergey’s eyes twinkled with the hint of a smile. “You know something, Daniel? You think too much.”
</p>
<p>
Satish’s Indian-accented voice piped up on the channel. “Danny,” Satish said. “I want to tell you something. You <em>don’t</em> have my faith.”
</p>
<p>
“Thanks a whole hell of a lot, Satish.”
</p>
<p>
“I don’t mean that in a bad way,” Satish replied.
</p>
<p>
“There’s a not-bad way to mean that?”
</p>
<p>
“Danny, I never rely on faith,” said Satish. “I base my judgments on results. And I’ve seen you be a non-stop fuck-up. But you know what? You’re a <em>robust</em> fuck-up. You always find a way to recover from your failures. And I’m seeing now that that’s much more important than not having failures in the first place. I used to think that nobody should ever do anything unless they can do it perfectly &mdash; but I see now that that’s just a formula for never doing anything at all. It’s less important to have a flawless system than to have one that’s self-correcting and fault-tolerant. If a system operates in a way that allows it to adapt organically, then it’s going to be more reliable than one that operates rigidly based on a preprogrammed script.
</p>
<p>
“Several hours ago you were telling me right here in my office that you’re going to start acting like a man. A man is a dynamic system, Danny. When his plans don’t work, a man doesn’t crash like a badly written computer application. A man recovers. A man reboots, marks the faulty lines of code, and keeps going.”
</p>
<p>
Danny took a deep breath and nodded. “Adapt organically…” he echoed.
</p>
<p>
The voice that answered Danny on the headset was Tina’s. “Danny,” she said. “Do you remember what I said to you back in the Rite Aid? Biological systems always find a way to make things work. And that brain of yours is one incredibly powerful biological system. It will self-correct. It will adapt. It will persevere. That’s how the system works. That’s how <em>you</em> work. You can’t not succeed. You don’t work that way. So you don’t need Sergey’s faith or Satish’s faith or mine or anyone else’s. The faith you need is your own.”
</p>
<p>
Danny stared blankly ahead for several moments, weighing their words, analyzing them and carefully pondering their implications &mdash; until it dawned on him that doing so defeated the purpose.
</p>
<p>
“You’re right,” he said. He grabbed the toolbox from the floor. “I’ll be back in a minute,” he told Sergey’s team.
</p>
<p>
And with a Zen-like calm, he strode out the door, into the maintenance hallway.
</p>
<p>
Mike said to him over the air, “Danny, where are you going?”
</p>
<p>
Danny walked down the plain white maintenance corridor. “I’m self-correcting,” he said. He opened the door marked “HOTEL STAFF ONLY”, walked out into the luxurious lobby, and stepped into the elevator to the Presidential Suite.
</p>
<p>
“Tina was right,” he said as he stood in the rising elevator, toolbox in hand. “I’ll either come up with a way for us to not need the cellphone in the vent, or a way to put it back into position.”
</p>
<p>
“How?” Mike pressed.
</p>
<p>
Danny replied lightly, “Dunno yet. But you know what? I bet I’ll think of something.”
</p>
<p>
The elevator arrived at the penthouse. Danny walked across the lavish antechamber toward the cedarwood doors, and knocked.
</p>
<p>
After a few seconds, the large doors swung open. The same aggressive-looking man greeted Danny at the door. Ivan stood next to him.
</p>
<p>
“You come back,” Ivan said. “We thought you might.”
</p>
<p>
Danny smiled genially. “Hi folks, sorry to bother you again. We think we fixed the problem. I’d like to verify, though.”
</p>
<p>
He stepped calmly into the room. He noticed that the air in the room had returned to a civilized, pleasant temperature, with no draft blowing.
</p>
<p>
He also noticed that the mercenaries that had previously been out on the balcony had returned indoors. The women stood awkwardly in one corner, looking nervously away. The video game on the immense TV was paused, and its erstwhile players stood at attention in the sunken living room.
</p>
<p>
The men were all looking directly at Danny.
</p>
<p>
He pretended not to be unnerved by the focused attention. He walked toward the sunken living room on his way to the vent, the eyes of the hired guns following him keenly as he moved through the room. The doors closed behind him.
</p>
<p>
He saw the vent. Its faceplate had been removed. The grating lay on the floor beneath the opening.
</p>
<p>
He froze and stared at it, perplexed. Surely he had put the grating back on the vent before leaving?
</p>
<p>
From very close behind him, he heard Ivan say, “Looking for this?”
</p>
<p>
Danny turned around slowly.
</p>
<p>
Ivan stood before him, his eyes blank with a chill so deep that Danny felt frostbite in his bones. In his creasy, mottled hands, he held the small, underpowered cellphone. The wad of Sticky Tack putty was still stuck to its case.
</p>
<p>
“I…,” Danny stuttered. “No, no! I… Uh, what’s that? I’ve never seen that before…”
</p>
<p>
The lithe, aggressive-looking man stood next to Ivan. He pulled a small black semi-automatic from his pocket, and pressed it to Danny’s chest.
</p>
<p>
Danny felt his heart beat against the barrel.
</p>
<p>
In the Bluetooth earpiece, Mike said, “Danny! Danny, what’s happening?”
</p>
<p>
Danny backed up slowly, minding the steps as he descended backwards into the sunken living room. The mercenaries around the room drew their handguns in smooth, silent motions.
</p>
<p>
Ivan hissed at him, “Do you thinking we are amateurs?”
</p>
<p>
“Wh&mdash; What do you mean?” Danny squeaked.
</p>
<p>
“A video camera bug in a air vent,” Ivan scoffed. “Is insult to the intelligence.”
</p>
<p>
Danny squared his shoulders. With a sudden bravado, he said forcefully, “I’m only here for the girl. Hand her over and no harm will come to you.”
</p>
<p>
Ivan burst out laughing. “No harm come to me?” The mercenaries joined Ivan in laughter.
</p>
<p>
In the earpiece, Danny heard his team panicking. “Bail him out! Bail him out right now!” said Mike. Sergey replied, “We are not anywhere nearby. Eugene is needing time to get into position.”
</p>
<p>
Danny looked Ivan in the eye and stood his ground. “We’re willing to negotiate.”
</p>
<p>
Still chuckling, Ivan said, “Yes, I sure you are. You working for Sergey. I know this already. It is surprising, really. This…” He gestured with the cellphone. “This not style of Sergey. Sergey, he more like, ‘Rahhhh! March! Go!’ Punch, kick, boom boom boom. You understand? This, this is more thinking, more like the chess. Sergey was never man for the chess before. Not man for the poker, either. He more like man for, um, for the boxing, yes? For the wrestling. Maybe he learning something as he getting older. Is too bad having to end working together like this.”
</p>
<p>
The Bluetooth headset buzzed with the voices of Danny’s cohorts. “We can’t just sit here! They’re going to shoot him in there!” Tina insisted. Mike replied, “There’s only one thing we can do. Satish! Roger! Have we finished isolating the X10 controllers?”
</p>
<p>
With the gun still pressed to his chest, Danny said to Ivan, “So, are you ready to start making a deal?”
</p>
<p>
Ivan smirked. “<em>Deal</em>? Here making ‘deal’. We killing you soon, but not right now. First we having with you a little ‘conversation’. This man here, he is expert at having ‘conversations’ like this.” Ivan gestured to the lithe man holding the gun at Danny’s ribs. The man gave a shark-like grin and grunted happily. “You will telling us everything about where is Sergey and how you working with him. Then, when you done telling us, we finally letting you die. That is ‘deal’, understand?”
</p>
<p>
In the earpiece, Satish said, “X10 packet injection check, receiver firmware mod check…” Satish proceeded to rattle out a series of hardware address codes. Mike pressed, “Then let’s do it already!”
</p>
<p>
In the suite, Danny glared at Ivan defiantly, saying nothing.
</p>
<p>
Ivan leaned toward him. “Ah, so quiet! You having no last words before fun begin?”
</p>
<p>
Slowly, a wry, diabolical smile crept onto Danny’s face. His eyes twinkled with Machiavellian anticipation.
</p>
<p>
The lights in the room died. In a blink, the suite went dark, save for the glow from the wide screen of the plasma TV in the sunken living room, paused in the middle of the video game.
</p>
<p>
The pause screen abruptly flicked away. In its place, the television showed an image split down the middle. The left half displayed nothing but a few lines of black text in an enormous-sized font on a plain white background:
</p>

<pre class="computer">
<strong>https://salajane.grazhdopank.ee/ru/ </strong>

<strong>Имя / name:</strong> и-желез-5177
<strong>Пароль / password:</strong> 999!идинахуй
</pre>

<p>
The right half showed an online banking interface. It was logged in to a corporate account, showing weekly withdrawals of large sums of cash. The ledger was listed in euros, and showed a balance of seven figures.
</p>
<p>
In the light of the television screen, with every gun in the room pointed at him, Danny looked Ivan in the eyes and grinned.
</p>
<p>
“Actually, yeah. I’ve got a few things to say.”
</p>
</div>