<div class="chapsection">
<p>
<span class="caplead">Danny burst through a heavy gray door</span>, and was greeted by wind blasting from the helicopter’s blades. His hair swept back from his face; his clothes flapped in the gale. Gripping his energy rifle, he paused in the doorway and surveyed the roof.
</p>
<p>
The asphalt expanse was bedecked with HVAC equipment and water tanks. The helipad, a wide smooth square painted with a circled letter “H”, dominated the rooftop.
</p>
<p>
The chopper hovered forty feet above, illuminated by bright white landing lights. Inside the glass bubble of its cockpit, Ivan held his pistol trained on the terrified pilot.
</p>
<p>
Sergey Mukhayev hung from one of its landing skids. He swayed by one arm, swinging wildly as he twisted and kicked to hoist himself up, his muscles bulging and straining beneath his armor. 
</p>
<p>
Danny studied the machine. On the back of the two-seat chopper, tucked beneath its tail, he could clearly see an exhaust manifold. Superheated air streamed from the pipe, creating transparent ripples of optical distortion. The helicopter was powered by a simple four-cylinder internal combustion engine. An electromagnetic pulse would do nothing to its pistons or drive belts. But maybe… just <em>maybe</em>… its electronically regulated fuel injection system and digitally-timed spark gaps wouldn’t be so lucky.
</p>
<p>
It was worth a shot.
</p>
<p>
Danny drew his HERF gun up to his shoulder, took aim, and pulled the trigger.
</p>
<p>
Above, the cockpit went dark. From the exhaust pipe, the rippling stream of air vanished. With its rotor blades still whirling by sheer momentum, the vehicle began to sink back down toward the helipad.
</p>
<p>
And Sergey’s entire body went limp. He stopped kicking and his legs went slack. His free hand momentarily clutched his chest before dropping loosely to his hip.
</p>
<p>
Danny looked on, realizing something was horribly wrong. “Sergey…?”
</p>
<p>
He dangled from the landing skid, unpowered and inanimate, like an armor-clad rag doll.
</p>
<p>
And slowly, the fingers of his meaty hand slipped from the rail. His body plummeted through the air.
</p>
<p>
“Sergey!”
</p>
<p>
Above, the chopper sprang sideways the instant it was free of its imbalanced load. The pilot fought furiously with the controls to execute an emergency landing.
</p>
<p>
Sergey hit the concrete with a dull thud.
</p>
<p>
Danny sprinted across the helipad and knelt beside him, waving his hands frantically over Sergey’s crumpled form. Bones had surely broken in the fall, but Danny could see no bullet wounds, no head trauma, nothing that would explain Sergey’s sudden collapse.
</p>
<p>
“Come on, man! Get up! What happened?”
</p>
<p>
Danny grabbed his face in both hands, feeling the bristly skin of his cheeks, and rotated his head to face him. Sergey’s jaw was slack. Behind drooping lids, his eyes were misaligned and unfocused.
</p>
<p>
Across the helipad, the pilot managed to ground his crippled vehicle safely. Even as the chopper was still settling, the passenger door opened. Fine black shoes stepped out onto the concrete, matching the crisply-pressed pants of a three-piece suit.
</p>
<p>
As Danny drew his hands away from Sergey’s face, the white outlines of his fingers lingered on the Russian’s skin, like handprints in cement. Living flesh, with flowing blood and full capillaries, would’ve quickly regained color. Sergey’s didn’t.
</p>
<p>
Danny grabbed a wrist and felt for a pulse. There was none. He tried to locate it on his neck, but to no avail. Sergey’s heart wasn’t beating.
</p>
<p>
“God, why!?” Danny shrieked. “For fuck’s sake, why!?”
</p>
<p>
He pushed Sergey flat onto his back. His trembling hands hurriedly undid the clasps and zippers of Sergey’s armor. Danny didn’t know CPR. What he did know, however, was that the heart is just an electromechanical hydraulic pump. A machine. Surely it could be rebooted…
</p>
<p>
He pulled the armor away from Sergey’s torso, leaving him in a sweat-drenched button-down shirt. Danny curled his hand into a fist and raised it above his head, preparing to give a sharp blow to the sternum.
</p>
<p>
It was then that he saw Sergey’s wounds.
</p>
<p>
Beneath a dense mat of chest hair, the skin bore long, pale scars, running along the left pectoral. They were thick and raised and slightly striated, resembling earthworms. Thin white branches extended from each line, indicating stitching. The scars were clearly surgical.
</p>
<p>
And on the left side of his chest, below the shoulder, the flesh was raised in the outline of a smooth round disc, about two inches across, implanted beneath the skin.
</p>
<p>
A pacemaker.
</p>
<p>
Danny felt the blood rush from his face. He looked at his HERF gun. His stomach lurched.
</p>
<p>
“Oh dear God, no…”
</p>
<p>
He brought his fist down on Sergey’s chest. “<em>No!</em>” he screamed, and raised his fist again. “No no <em>no</em>!” He pounded futilely on motionless ribs. Eventually, his fist slowed and his arm weakened, and he brought it to rest softly upon Sergey’s lifeless body. His head followed, curling downward to rest his forehead upon Sergey’s chest. “I’m sorry… I’m so, so sorry…”
</p>
<p>
From somewhere nearby, Danny heard laughter. It was dry and dark. It was laughter dripping with condescension and schadenfreude, a chortling cackle of evil victory.
</p>
<p>
Kneeling over Sergey’s body, Danny looked up with red, moist eyes.
</p>
<p>
Before him stood Ivan Zheleznov, his mouth spread wide in a horrid grin. In his hand, his gun glinted in the helipad landing lights.
</p>
<p>
Danny, frozen, watched the laughing Russian kingpin raise the firearm and point it at him. Unblinking, he saw the barrel aim between his eyes.
</p>
<p>
A deafening bang resounded across the rooftop.
</p>
<p>
Ivan fell sideways.
</p>
<p>
As he dropped away, the first thing Danny saw, several yards behind him, was a small silver revolver with a short, squat barrel with an enormous opening.
</p>
<p>
It was held by Eugene Mukhayev.
</p>
<p>
The athletic man stood uneasily, halfway doubled over. His body quivered; his face was pale; his eyes darted uncontrollably. The revolver shook in his hand.
</p>
<p>
Ivan lay on the smooth concrete, bleeding from the leg. He turned to face Eugene, and fired off a few shots.
</p>
<p>
Eugene grunted as the bullets hit his armored body, but remained standing. He took aim.
</p>
<p>
Ivan tried to scramble to his feet, but succeeded only in a rapid half-crawl.
</p>
<p>
Eugene’s revolver let out another boom, then another. Fire spat forth from the large black opening. But his hand was shaking too violently to aim at a moving target. The shots chipped away concrete near Ivan, but none managed to hit him. Out of bullets, Eugene charged forward.
</p>
<p>
Ivan limped away, trying to flee. His bleeding leg left a crimson trail across the helipad’s surface.
</p>
<p>
Eugene slammed into him at full sprint, checking his shoulder into the small of the limping kingpin’s back. He knocked him forward past the edge of the helipad, toward the stone balustrade that ringed the top of the building.
</p>
<p>
As Ivan continued trying to crawl away, Eugene grabbed him by his three-piece suit and threw him against the concrete rail.
</p>
<p>
The two of them wrestled against the balusters. Eugene fought not only against the aging kingpin but also against his own body, which misinterpreted the commands of his mind into spastic, sloppy motions. His neurons misfired and short-circuited like frayed electrical wires, sending his muscles twitching and twisting against his will. His extensive martial skills failed him, as his malfunctioning brain proved incapable of translating his thoughts into coherent action.
</p>
<p>
Ivan, wounded and bleeding, pulled himself up on Eugene’s armor. He lacked Eugene’s strength and training, but the old kingpin was a twisty, writhing thing, and he resisted Eugene’s attempts to grapple him. Still wielding the glinting gun, he tried repeatedly to put it to Eugene’s head.
</p>
<p>
With Herculean exertion and mental focus, Eugene managed to overcome the waves of convulsions long enough to get an arm around Ivan’s neck, trapping him in a headlock.
</p>
<p>
The aging kingpin writhed and bucked, but couldn’t slip out of the hold. He pushed and kicked, trying to make Eugene stumble.
</p>
<p>
Eugene stabilized himself by pushing his back against the waist-high balustrade. With his arm around Ivan’s neck, he grabbed his own elbow with his opposite hand and squeezed.
</p>
<p>
Ivan, weakening, lifted his handgun over his head and pressed the muzzle against Eugene’s temple.
</p>
<p>
With Ivan’s neck still in his arms and the stone balustrade behind him, knowing that a shot from Ivan’s gun was imminent, Eugene leaned backward. Together, they tipped over the rim of the roof of the Medina Gallante.
</p>
<p>
Danny raced toward the point from where they’d fallen. He hurried past the helicopter, whose blades had slowed to a smooth, silent rotation; inside, the pilot sat low in his seat, trying desperately to call for help on his nonfunctional radio. Danny hopped down from the helipad onto the asphalt rooftop and dashed to the balustrade nearby, streaked with blood.
</p>
<p>
A dozen stories beneath him, past rows of windows and the dark green thicket of the surrounding pine canopy, Ivan Zheleznov and Eugene Mukhayev lay motionless upon the stone tiles of a wide pavilion. A dark crimson pool spread outward. Their bodies, broken and lifeless, remained locked in battle.
</p>
<p>
A crowd began forming around them &mdash; hotel guests, staff, and a growing number of police. Danny ducked away when he noticed some of them looking upward.
</p>
<p>
Thumping noises in the distance made him look around. Above the wooded suburban skyline, multiple helicopters closed in on the Medina Gallante. In the waters of Lake Washington, patrol boats approached the hotel’s wharf. From the ground, sirens and radio chatter were audible even on the rooftop.
</p>
<p>
He noticed the voices of his comrades in the Bluetooth. “Danny! Danny!” Mike hollered. “Can you hear us?”
</p>
<p>
“Yeah,” Danny replied, calmly rounding the helipad perimeter to go retrieve his energy rifle.
</p>
<p>
“The place is swarming with cops!”
</p>
<p>
“Don’t worry, Mike. I’ll be fine. They’re all talking on radios.” He checked the lights on the HERF gun. It had enough charge left for several more shots.
</p>
</div>