<div class="chapsection">
<p>
<span class="caplead">Seattle’s downtown skyline glinted</span> in the warm sunlight of a clear summer day. Tall buildings rose above the shoreline, their windows shimmering with reflections of surf and sky. They towered above parks where children and dogs played; above markets raucous with tourists and musicians; above sparkling blue waters teeming with yachts and freighters. The blue Olympic Mountains crowned the western horizon, the gray Cascades and the enormous sleeping volcano of Mount Rainier lined the east. Tucked amidst majesty of geological proportions, the man-made spires jutted upward from low-lying gray urban periphery like immense gemstones from rock &mdash; the obsidian shard of the Columbia Center, the waterfall mesa of sandstone and sapphire at 1201 Third, the bizarre white alien stalagmite of the Space Needle. Seattle wasn’t merely adorned with jewels; she was made of them. She was the Emerald City.
</p>
<p>
“I just want to say, before we move on,” said the throaty, energetic voice of a young man freshly in his twenties, “that we both really appreciate this opportunity to present this work to you.”
</p>
<p>
On an upper floor of a soaring corporate tower, at the end of a long marble-floored lobby, there stood a pair of wide glass double doors. Frosted upon their surface were the words, “Tuttle Investment Partners.”
</p>
<p>
“We’re both techies, you know? I’m all about nanomaterials, and my partner’s a biomachinist. We’re science dudes, not money dudes. But when we talk to most venture capital people, they ask us about partnership strategies and market penetration projections. So it’s, like, great to see potential financial contributors showing a genuine interest in our engineering efforts.”
</p>
<p>
In the Tuttle office’s anteroom, beside the reception desk, stood a museum-like pedestal lined with red felt. Upon it, the ramshackle HERF gun prototype, built out of PVC and held together by Velcro and karabiners, sat inside a glass case, like some kind of curious historical relic from a bygone era. Which it was.
</p>
<p>
Video display monitors, barely thicker than paper, hung from the ceiling of the reception area. The monitors showed proud videos of Tuttle projects. One presented a focused young woman carefully measuring the electrical current flowing through an organic fractal assembly. One displayed an aging paraplegic playing the piano with a hand built of polymer and silicon. One had a Navy admiral demonstrating an aquatic robot darting through the water with a dolphin-like tail.
</p>
<p>
And another displayed a title screen announcing, “Tuttle Investment Partners is a proud sponsor of the Mukhayev Memorial Foundation.” Talking heads gave closed-captioned testimonials about overcoming drug addiction.
</p>
<p>
A woman’s voice spoke. It was an older voice, well-educated and self-assured. “It’s our pleasure to hear your ideas. We succeed financially by making informed investments, and that means understanding the science behind proposals to judge whether or not they sound promising.”
</p>
<p>
“And… Do…” The young voice stammered nervously. “Do you think we sound promising?”
</p>
<p>
The speaker stood in a small corporate conference room just beyond the reception hall. He was tall and charismatic, and brimmed with infectious excitement. His partner, a slightly older student with a heavy-set body and a shy demeanor, stood quietly at his side. Behind them, a large screen displayed a rotating protein structure with numerical readouts and a bulleted list of molecular properties. Words along the top of the diagram read, “Nanotube-Modulated Pluripotentiation: A New Approach To Cellular Multiplexing.”
</p>
<p>
The woman chuckled. “We’ll see.”
</p>
<p>
The woman was Tina. She sat at a small conference table, watching the presentation and taking notes. She wore a crisp, conservative business dress. The march of time had chiseled the contours of her face into a firm visage of competence and confidence, smart and strong and feminine. She radiated a kind of mature beauty only expressed in those who have rightfully earned it.
</p>
<p>
As the two young men fidgeted before their presentation, Tina turned to her side and said jokingly, “What do you think, Dan? Should we continue hearing these guys out, or are they a waste of our time?”
</p>
<p>
Daniel sat at the table beside her, wearing a timeless gray business suit. The color of his clothes matched the tone of his hair, which had receded high above his forehead to form a salt-and-pepper crown. The hair he had lost from the top of his head, he made up for with a neatly trimmed beard, dark with flecks of silver around his chin.
</p>
<p>
“Eh. I say cut them some slack,” he said, the creases at the corners of his mouth and eyes deepening as he smiled. “I remember giving a presentation to an investor group myself a long time ago, and it went pretty terribly.”
</p>
<p>
She winked at him and said, “Hey, it wasn’t <em>all</em> bad!”
</p>
<p>
With a twinkle in his eyes, he replied, “I do suppose I made the best of it. Of course, back then, the term ‘cellular multiplexing’ meant something completely different.”
</p>
<p>
A device on Daniel’s wrist suddenly buzzed with a gentle, quiet vibration. Daniel glanced down at the screen. A pop-up window bore the words, “<span class="computer">Rosie: 6 unread messages (10 unread total).</span>”
</p>
<p>
One side of the pop-up was dominated by a cropped square image of Rosie’s face. She used her glamor shot for her profile picture, which meant that every time she called or messaged, he saw her pressing her fingers erotically against her glossy purple lips, looking sensuously upward with mascara-rimmed eyes below a mane of iridescent platinum hair. The image made him feel awfully awkward every time. He flicked the pop-up away.
</p>
<p>
“On a more serious note, guys, I do have a few concerns,” Daniel said. “For starters, then there’s the matter of heat buildup. Now, I don’t know squat about biology, but I do know that you’re working with carbon-based molecules. And you know what I do know about carbon-based molecules? They’re flammable. So, from strictly a technical standpoint, I’d advise placing a staggered…”
</p>
<p>
His device buzzed again. “<span class="computer">Rosie: 7 unread messages (11 unread total).</span>”
</p>
<p>
He looked up at the two young hopeful engineers. Their faces were anxious and self-conscious.
</p>
<p>
“Gentlemen,” Daniel said apologetically. “I hate to be rude, but…” He turned away in his chair and focused his attention on his device.
</p>
<p>
He maneuvered to the fresh pile of messages in his Inbox. The texts from Rosie weren’t at the top of his queue. Instead, he first had to flip through several messages that fell under a heading titled, “<span class="computer">HALF-CENTURY BIRTHDAY BLOWOUT!!11!one!</span>”
</p>
<p>
Beside each message, the device displayed familiar faces.
</p>
<p>
“<span class="computer">Dude! Your 50th birthday? We wouldn’t miss it for the world! Count us in 110%!</span>” announced one message, beside a picture of Mike and Natalie. They’d been married for almost a decade. Their youngest child had just entered pre-school. Natalie had her own clinical practice. Mike worked as a network administrator for REI’s corporate offices. In their free time, they made costumes and crafts for the Washington Midsummer Renaissance Faire. They were ridiculously happy.
</p>
<p>
“<span class="computer">Wow, 50!!!! I vaguely remember it. :) I’ve got venue, catering, and entertainment all lined up. It’ll be a gala! Get plenty of rest the night before. You’re going to need it, old man! Welcome to the other side of the hill!</span>” The message was from Jason, whom Daniel hadn’t seen much of lately. Jason’s health was faltering &mdash; he was fighting an aggressive case of pancreatic cancer. His oncology clinicians routinely programmed new strains of custom-built viruses to attack the cancerous cells, but the cells kept evolving new mutations to resist the virotherapy. Despite the arms race being waged within his bloodstream, Jason’s spirits were quite high, and his friendship with Danny and the projects of Tuttle Investment Partners brought him fulfillment.
</p>
<p>
“<span class="computer">Daniel. It would be my pleasure to see you again, old friend,</span>” wrote Satish. “<span class="computer">My wife and daughters have not seen America yet, and it was very kind and thoughtful of you to include them in the invitation. It’s a long flight from Mumbai, but we’ll make it happen.</span>”
</p>
<p>
“<span class="computer">Sure! See you there!</span>” Moshen replied. Moshen still made a decent living with his web design work. He couldn’t rightly be thought of as a “kid” anymore; he was married now, and would soon probably have kids of his own. In his spare time, he penned a popular online comic. It was about kung fu.
</p>
<p>
Finally, Danny found the litany of texts from Rosie.
</p>
<p>
“<span class="computer">Dan my suit isn’t working. Can you fix it?</span>”
</p>
<p>
“<span class="computer">I’m supposed to be doing a dress rehearsal right now but my suit is broken!!! I can rehearse without it but I need it tonight. Kinda starting to fraz here...</span>”
</p>
<p>
“<span class="computer">FUCK DAN I’M IN DEEP SHIT. Since Sliced Bread watched me rehearsing and she’s all like ‘Where’s your suit?’ and I’m like, ‘It’ll be working by showtime I PINKIE-SWEAR! DAN PLEASE PLEASE HELP!</span>”
</p>
<p>
“<span class="computer">It ons alright, but then it turds out this message ‘Segmentation Fault: NullPointerException in IOBuffer::integrateFrame’ WTF?</span>”
</p>
<p>
“<span class="computer">Shit, I think I just made it worse...</span>”
</p>
<p>
“<span class="computer">DAN I CAN’T GO ON WITHOUT MY SUIT! DO YOU GET? I’M OPENING FOR SINCE SLICED BREAD! WHERE ARE YOU?</span>”
</p>
<p>
“<span class="computer">Hello...?</span>”
</p>
<p>
Daniel sighed gently and put the device away. He looked back and forth at Tina and the young men. They had patiently waited for him to finish.
</p>
<p>
“I’m so sorry,” he said. “I have to go.”
</p>
<p>
Tina asked him, “Is everything alright?”
</p>
<p>
“Yeah,” he said. “Rosie’s just freaking out. Or ‘frazzing’ or whatever the hell the kids say today.”
</p>
<p>
“Her show isn’t until eight o’clock,” Tina said. “She wants you there right now?”
</p>
<p>
“Yeah,” Daniel replied.
</p>
<p>
“What for?”
</p>
<p>
“Tech support.” Daniel stood up and began walking out of the room.
</p>
<p>
The charismatic young man said, crestfallen, “Wait, so… Our project…”
</p>
<p>
He gave them a warm smile. “Listen,” said Daniel. “You kids have a lot of very, very hard work ahead of you. But Tuttle Investment Partners might be able to help you out. No promises yet. But we’ll talk more soon.”
</p>
<p>
The two young men had complex expressions on their faces, showing equal parts happiness, excitement, and fear.
</p>
<p>
Danny walked around the small conference table toward where Tina sat. “And as for you…” He leaned his head down toward hers, and the two of them exchanged a deep kiss. “I’ll see you tonight at Rosie’s concert?”
</p>
<p>
“Hell yeah,” Tina answered. “I already talked to the babysitter &mdash; she’ll pick the kids up from school, and we’re good ‘til morning.”
</p>
<p>
“Perfect,” said Daniel. “I’ll meet you in the VIP booth.”
</p>
<p>
“What’s the name of the band she’s opening for?” Tina asked.
</p>
<p>
“‘Since Sliced Bread’,” Daniel replied.
</p>
<p>
The two young engineers suddenly jumped with excitement. The older, heavier, quieter one suddenly said, “You guys have a VIP booth at the Since Sliced Bread concert?” 
</p>
<p>
Daniel shrugged. “Yeah. You two want to come?”
</p>
<p>
The young men looked like they were choking. They nodded their head so rapidly that Daniel could practically hear their brains jostling.
</p>
<p>
“Heh. I take it they’re popular?” Daniel asked.
</p>
<p>
“Since Sliced Bread?” the presenter said. “Jesus Christ! She’s, like… oh my God, she’s… she’s…”
</p>
<p>
“You mean ‘they’, right?”
</p>
<p>
“No, I mean ‘she’,” said the young man. “Since Sliced Bread is the performer. She’s a solo act.”
</p>
<p>
“‘Since Sliced Bread’ is a girl’s name now?” Daniel asked, and shook his head. “Christ, I’m getting old.”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Rosie greeted him completely naked</span> at the door to her backstage dressing room, with the arm of a very muscular young man draped around her sculpted waist.
</p>
<p>
“Dan! Thank fucking Jesus!” She turned around, pivoting in place with perfect poise. She briskly padded barefoot across the disheveled room, moving effortlessly with a dancer’s grace.
</p>
<p>
Her beefy boy-toy watched her with rapture in his eyes. Daniel knew that look. He’d seen it on every gentleman-caller Rosie had ever brought home. Whoever this fellow was, he was already hopelessly, agonizingly in love with her. After tonight, he’d never see her again.
</p>
<p>
“It’s over here!” she called from somewhere inside the cluttered chamber. Several young men and women puttered around, examining instruments and equipment. One lean geeky-looking guy sat in front of a clothing rack. Rosie looked down at him and shooed him with her hands, saying, “Ksssst! Scat!” The guy scurried out of his chair.
</p>
<p>
Daniel took a few awkward steps inward, avoiding looking in her direction. “Rosie, could you maybe put on a robe or something?”
</p>
<p>
Rosie flicked her hand manically at the clothes rack. “Just… just fix it! Please?”
</p>
<p>
The rack only held one garment. On a hanging scaffold, with arms outstretched and legs pulled straight, was Rosie’s suit. The outfit was a one-piece jumpsuit custom-fitted to conform to Rosie’s flesh like a second skin. Like a scuba suit, it left only the head and hands exposed.
</p>
<p>
Unlike a scuba suit, it was completely transparent.
</p>
<p>
It was made from a material that felt to the touch like something between cellophane and polyester. A flexible column of gray opaque plates ran down the spine and across the shoulders; the plates bore jacks for data and power, as well as elaborate heatsink structures. At certain angles of light, the glint of microscopically thin metallic fibers could be seen shimmering outward from the gray spinal column and weaving through the clear material.
</p>
<p>
With a grunt, Daniel stepped up to the jumpsuit, reached toward its spine, and pressed the power button. 
</p>
<p>
From neck to toe, the material of the suit immediately turned solid black. Bars of color appeared down one thigh, indicating battery level, temperature, storage capacity, and CPU and memory utilization. Blocky gray text materialized line by line across the suit’s breast, distorted by the curvature of the display fabric.
</p>

<pre class="computer">
RedRaven BIOS v8.2.006
VESA Omnibulus HyperGL
Processor: Phobion LXZ-8881 512GHz 
Memory: 32T OK
INIT runlevel 4
Filesystem check........................[ OK ]
Starting system logger..................[ OK ]
Network initialization..................[ OK ]
Setting localhost.......................[ OK ]
</pre>

<p>
The text cascaded in gray sheets down the surface of the suit, warping and bending along the shape of the garment. When it hit the navel, it began scrolling. After several moments, the text read: “<span class="computer">DisplaySuit diagnostic sequence. Stand by...</span>”
</p>
<p>
The text at the navel then suddenly spat out: “<span class="computer">Segmentation fault (core dumped)</span>”. The suit performed no further theatrics.
</p>
<p>
“See?” Rosie whined. She stood at a nearby closet, slipping into a bathrobe. “That’s all it does! It gets to that, and then it just stops like a little bitch…”
</p>
<p>
Daniel raised a hand and motioned for her to calm down, and studied the reams of text on the suit’s surface. After about twenty seconds, he let out a slight chuckle. “Well, duh,” he said, staring at stack trace listings and hexadecimal pointer values. “Here’s your problem…”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Daniel got the suit working</span> about two hours before showtime. Rosie began pulling it on before Daniel could even complete a power cycle. “God! Thank you, yes! You’re the best, Dan!” Daniel turned aside as she dropped her robe to the floor and began slipping her naked body into the transparent material.
</p>
<p>
“You know, Rosie, you’d be fine even without the suit,” Daniel said, facing away. “You’re incredibly talented. Your performance will stand on its own merits.”
</p>
<p>
“You’d think so, wouldn’t you?” she said. “But the truth is, talent is cheap. All talent gets you is a job playing background music of an HBO miniseries. And in the meantime, there’s a thousand turdhole pop-groups that can’t hit two chords, that are booked solid for years.” She ran her hands up along her long, firm legs to squeeze out pockets of air. “Talent alone gets you nowhere. I mean, fuck, Dan. I’m almost twenty-five. You know what the 27 Club is, right? Jimi Hendrix. Jim Morrison. Amy Winehouse. Kurt Cobain. Janis Choplin. Tricia Ferrel. A real performer is supposed to be dead at 27. I’m 24, and where am I? Everything I’ve done up to now has been coffee houses and indie festivals. If I don’t break out tonight, I’ll wind up playing bar mitzvahs and high school reunions until the day I die. Which will probably be 27 anyway, because I’d rather just shoot myself.” 
</p>
<p>
She rolled her shoulders to straighten the plates on her back. One of her lackeys zipped her up from behind.
</p>
<p>
“So, here I am,” she continued, flexing her limbs inside the suit to smooth out any kinks and wrinkles. “I’ve got talent, and I’ve got this unbelievable lucky break where Since Sliced Bread is letting me open for her tonight. So I have to ask myself, what else can I do? What can I bring to the audience that nobody else in the world can give them?” She patted her sides to gesture towards the suit. “This. I can give them this. Yeah, it’s just a gimmick, but fuck it. I’ll take any advantage I can get.”
</p>
<p>
The suit, now operational, responded to her movements with iridescent ripples that shimmered across her skin like waves upon an ocean of fluid energy. Flicks of her wrist and ankles sent ribbons of light spinning like whirlwinds upon her body.
</p>
<p>
They moved to the stage to rehearse. With her crew in place, Rosie sauntered forward and waved to an imaginary audience. Shining upon her swaying form, swirls of ethereal color complemented her motions. She looked immaterial, transcendent, detached from physical reality, like a being that belonged to a different plane of existence &mdash; one purer, more celestial, more proximate to God.
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Daniel sat beside Tina</span> in the VIP booth beside their two young guests, above a chattering crowd of tragically hip teenagers and twentysomethings slowly growing more inebriated. On the stage, Rosie’s bandmates stood at the ready, tense and anxious. It was fifteen minutes past showtime.
</p>
<p>
Daniel’s wrist buzzed with an incoming message.
</p>
<p>
“<span class="computer">Dan thank you sooooo much again for saving my ass with the suit,</span>” Rosie typed. 
</p>
<p>
“<span class="computer">No problem,</span>” he replied. “<span class="computer">Glad I could help. Everybody out here is super excited! Get out here already. :-)</span>”
</p>

<div class="computer cyberchat">

<div class="message messagein">
I feel like I'm going to hork.
</div>

<div class="message messageout">
I don't blame you. You're a natural born rock star. You'll do great tonight.
</div>

<div class="message messagein">
Everyone keeps telling me that lol. Thx, I'll do my best.
</div>

<div class="message messageout">
I wasn't saying that to be encouraging, Rosie. I was being sympathetic. You feel like you're going to hork *because* you'll do great tonight.
</div>

<div class="message messagein">
I don't follow.
</div>

<div class="message messageout">
Think about it. If you were to do poorly out here, it wouldn't really affect anything for you. You'd continue performing in obscurity, booking coffee shops and indie festivals. Your life would go on as it's been, and this becomes just some random night when nothing noteworthy happened, and a successful music career will forever be simply some hypothetical alternate reality. 
</div>

<div class="message messagein">
But I'm not going to do bad out there. I'm going to blow them away! :-)
</div>

<div class="message messageout">
Exactly. And that means everything changes. Everything. You'll no longer be the girl struggling to make it. You'll become the young woman that's making it. The person you are now, ends tonight. And that's pretty damn terrifying, isn't it?
</div>

<div class="message messagein">
You have no idea.
</div>

<div class="message messageout">
With all due respect young lady, I think I do. :-)
</div>

<div class="message messagein">
Alright, Oh Wise Ancient One. :-) So then what should I do about it?
</div>

<div class="message messageout">
What should you *do* about it??? EMBRACE IT! Rosie, you've got a house packed with adoring tattooed fans all dying to witness your magic. Get out here and make it happen!
</div>
<br/>
</div>

<p>
A minute passed with no reply. Suddenly, the lights cut out, and the crowd began to howl and cheer. The delicate chords of an intricate harmony echoed from the lightless depths of the stage.
</p>
<p>
A glowing figure appeared, dancing through the darkness like an angel across the void of space. It looked not human, but something beyond humanity &mdash; an incarnation of ingenuity and sensuality, an embodiment of mind and spirit. She was a creature born of technology and biology, a unity between mankind’s origin and destination wrapped in song and motion. She was a being for whom the worlds of the natural and the designed, the human and the divine, had no boundaries. For her, the limitless reaches of imagination would be manifest in physical reality.
</p>
<p>
She floated on gossamer limbs toward the microphone, cheered on by an adoring throng of pink-haired girls and slim-hipped guys. Iridescent arms spread to embrace the spotlight. Breath drew sharply into lungs made of starstuff and nebulae. Her voice rang out, carrying her song to the audience, to the world. And from that night on, her music played.
</p>

</div>

<div class="theend">
The End
</div>