<div class="chapsection">
<p>
<span class="caplead">The sound of applause reminded Danny</span> of this one time in an alternate universe. His band was playing their most popular set before an adoring throng of pink-haired girls and slim-hipped guys. Power chords soared above their wild screams as he pulled the microphone away from his lips and spread his arms to embrace the spotlight. His life was a hedonistic montage of groupies, hard drugs, and wealth beyond imagination.
</p>
<p>
Unfortunately, that never actually happened.
</p>
<p>
<span class="think">The applause should be louder than this</span>, thought Danny. <span class="think">I gave a great performance here. They should be whistling and screaming and throwing their underwear at me.</span>
</p>
<p>
Danny looked around and decided it’s best if they didn’t.
</p>
<p>
The applause was polite and professional. It came from about two dozen 50-something men in a small conference room. In place of tattoos and piercings were hair plugs and porcelain dental veneers. About half were wearing gray suits, like Danny. The rest were in khakis and polos, doubtlessly planning to get back to their sailboats or golf courses right after the meeting let out.
</p>
<p>
One attendee actually <em>was</em> wearing a concert T-shirt under his suit jacket &mdash; a <em>Nine Inch Nails World Tour</em> XL tucked into pleated suit-pants, spread over a belly that had apparently gone decades without being subjected to a sit-up. The thinning remnants of his salt-and-pepper hair were gelled upward into what would’ve been a hip, groovy spike ‘do on a man half his age.
</p>
<p>
There was no microphone in Danny’s hand, only a laser pointer. No spotlight, only a high-resolution projector hooked to his laptop. No hit rock song, only a PowerPoint presentation describing a 4G cellular multiplexing algorithm by Claymore Communications.
</p>
<p>
Danny’s boss, Jerry Young, was the only other person in the room without a designer watch. He moved deftly to take control. “Folks, I just want to say, before we move on, that Danny and I really appreciate this opportunity to present our technology to you. I’ve worked for a lot of dot-coms where the investors really don’t care about the tech, and it’s nice to see Claymore’s financial contributors showing a genuine interest.” 
</p>
<p>
“Oh, our pleasure!” said the man in the Nine Inch Nails T-shirt. “Danny’s presentation was amazing, but not as amazing as his technology. What you’ve shown here is an upcoming cellular revolution, and I’m proud to help it come to fruition!” Later that day, NIN Man bought Claymore Communications with his personal funds, and the company went public. Danny cashed in his stock options to buy a downtown penthouse, and spent the next several years building Claymore into the world’s premier data systems provider. He was featured in <em>Time</em> magazine as the face of digital communication in the 21<sup>st</sup> century.
</p>
<p>
That never actually happened, either.
</p>
<p>
Instead, the man in the Nine Inch Nails T-shirt said cheerfully, “We’re just glad you could set up this meeting for us! Your man Danny here really seems to know his material.”
</p>
<p>
Jerry beamed. “Yes, Danny’s been a great asset to the company. He’s been Claymore’s lead engineer for… How long, Danny? Five years now?”
</p>
<p>
“Six,” Danny said.
</p>
<p>
“Six years,” Jerry repeated. “He ran the Naval Base Kitsap project last year almost single-handedly. He’s personally responsible for most of the firmware designs you guys saw here tonight. And you should see him bust a move on <em>Dance Dance Revolution</em>!” The investors laughed on cue. From there, Jerry Young took the room. He launched his own set of PowerPoint slides, discussing things like potential partnership strategies and market penetration projections. Danny stood aside so that the big boys could play.
</p>
<p>
In some alternate universe Danny had gone to get an MBA after finishing his master’s degree. He moved to New York and quickly climbed the ladder at a multinational holding company, and eventually became a manager of a tech-heavy hedge fund. He dated models, dined at fine restaurants, and lit cigars with burning hundred-dollar bills. By night he donned a cape and cowl and prowled the rooftops fighting crime.
</p>
<p>
In the real world, during his last trip to New York he’d managed to drop his cellphone onto a set of subway tracks. In reality, New York sucked.
</p>
<p>
Reality sucked.
</p>
<p>
“Reality sucks.”
</p>
<p>
<span class="think">Crap! I didn't say that out loud, did I?</span>
</p>
<p>
The words had escaped under his breath. All eyes turned to Danny. Jerry’s jaw hung open, mortified.
</p>
<p>
“I… sorry,” Danny said. “I was just… My mind was somewhere else.”
</p>
<p>
Jerry stepped in diplomatically. “Danny’s been working hard lately to put this presentation together for you guys. He stayed up late last night giving it a final polish. He could probably use some coffee. Right, Danny?”
</p>
<p>
Danny took the hint. As he escaped the room, he heard Jerry resume the presentation.
</p>
<p>
<span class="think">Reality sucks?</span>
</p>
<p>
<span class="think">No. I suck.</span>
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">The coffee pot in the company kitchen</span> held Danny in rapt attention. Danny gazed at it, mesmerized. It glowed with a shade of red just slightly deeper than the visible spectrum. Infrared. Every object in the universe emitted black-body radiation with a brightness and color determined by its temperature. Danny stared unblinkingly as he tried to compute the hot coffee pot’s emission spectrum, a relatively easy task using Planck’s Law; the power per unit area <em>I</em> of frequency <em>v</em> from a body at temperature <em>T</em> was equal to <em>v</em> cubed times 2 times the Planck constant divided by…
</p>
<p>
“Danny…?” came a sudden voice from behind him.
</p>
<p>
Danny twitched back to awareness and turned around to greet his visitor. He found himself alone in the Claymore kitchen with the overweight investor in the Nine Inch Nails shirt. “Hi! Oh… I’m sorry, I didn’t mean to be hiding in here.”
</p>
<p>
“You look like you got distracted by something shiny,” said NIN man.
</p>
<p>
Danny smiled sheepishly. “I did. Um… Is the meeting over? I should get back to the conference room. You guys probably have technical questions for me.”
</p>
<p>
“Relax, Danny,” NIN man said collegially. “I’m glad I found you in here. I was actually hoping I could talk to you about something besides Claymore.”
</p>
<p>
“Oh. Then, uh… How can I help you, Mister… uh…?”
</p>
<p>
“Tuttle. Jason Tuttle. Call me Jason,” the investor said as they shook hands. “First off, I just wanted to tell you face-to-face that I meant what I said in there. That presentation was just excellent. You do great work.”
</p>
<p>
“Thank you,” Danny replied earnestly.
</p>
<p>
“Listen,” said NIN Man. “I’d like to run something by you. I’m putting together a small team for a project I’m working on. I could really use a man like you.”
</p>
<p>
Danny blinked in eager bewilderment. “You want to offer me a job? A… A job outside of Claymore? A job having nothing to do with 4G cellular multiplexing?” Danny noticed his voice rising. He cleared his throat. “I… Uh… I’m honored, Mister… Jason. But I can’t. I’m a Claymore employee. Are you even allowed to be asking me about other work?”
</p>
<p>
“Oh, don’t worry, Danny. You have no obligations to Claymore anymore.”
</p>
<p>
“Of course I do. We’ve got 182 Bugtraq tickets with less than four weeks left to hit ZBB before the next QA handoff…”
</p>
<p>
“You can forget about all of that, Danny. None of it will help Claymore at this point.”
</p>
<p>
“What do you mean?” Danny asked.
</p>
<p>
Jason smiled coyly. “Can you keep a secret?”
</p>
<p>
Danny nodded.
</p>
<p>
“Danny, next week there isn’t going to be any Claymore Communications. We’re pulling the plug.”
</p>
<p>
Danny blinked uncomprehendingly. He heard Jason’s words, but his brain short-circuited while trying to parse the sentence. He muttered, “Does not compute.”
</p>
<p>
Jason said matter-of-factly, “Claymore has never turned a profit, you know.”
</p>
<p>
“Well… Yes, but… We’ve been focused on research…”
</p>
<p>
Jason cocked an eyebrow. “You’ve basically been living off of our generosity.”
</p>
<p>
“That’s only temporary, until we establish a sales pipeline…” Danny insisted.
</p>
<p>
“It’s taken six years already. Who do you think’s been providing your paychecks this whole time? Benevolent gods from the ancient empire of Moneypotamia?”
</p>
<p>
Danny’s throat went dry. “Why now?”
</p>
<p>
“It had to happen eventually, Danny,” Jason said. “The investment group’s been discussing it for months amongst ourselves. We can’t keep our assets locked up in this dead-end project anymore. Enough’s enough.”
</p>
<p>
“I don’t understand…” Danny’s voice was almost a whimper. “What happens now?”
</p>
<p>
“Now we bundle up Claymore's intellectual property,” said Jason, “and sell it to the highest bidder. Someone like AT&amp;T or Verizon or Google. Or the military. It’ll be easy for us to pitch the technology now that we know how it works.” He winked.
</p>
<p>
Danny felt his stomach lurch. “My presentation…?”
</p>
<p>
“Yep. That’s why we needed you to put it together on such short notice. The other investors have the next several weeks booked solid, meeting with senior engineers and CTOs of other companies. And none of it could have happened without that show you just gave us. Really, Danny, you do excellent work.”
</p>
<p>
Danny looked away, his face pale.
</p>
<p>
“I’m sorry I couldn’t break the news a little more, er, ceremoniously,” Jason said. “Nobody outside the investment group knows about this. I’m taking a legal risk in telling you. I hope you’ll accept that fact as a token of trust. The job I need you for is a little, shall we say, sensitive.”
</p>
<p>
Danny rubbed his temples. “Wh&mdash; What about the work I’ve done in the past six years?” he said shakily. “My conference papers, my chip designs, my driver patches…”
</p>
<p>
“Sunken costs, Danny.”
</p>
<p>
He swallowed hard, and stared at Jason bitterly, saying nothing.
</p>
<p>
Jason put a hand on his shoulder. “Hey. Buddy. It’s not personal, alright? Claymore’s implosion is happening. I know it must hurt, but that’s life. At this point, all I can offer you is this new job. Are you interested?”
</p>
<p>
Danny shrugged. His head slumped down in a gesture that was a nod only by default.
</p>
<p>
“You know the bar Noc Noc near Pioneer Square?” Jason asked. “Meet me there tonight. I’ll tell you all about it.”
</p>
<p>
</div>
