<div class="chapsection">
<p>
<span class="caplead">Pain enveloped Mike like a cocoon.</span> It robbed him of all sense of time, space, or direction. He felt like he was floating in the dark womb of some alien beast. He sat propped up in his hospital bed with his wounds dressed in gauze, talking with his friends, enduring the exhaustion and the delirium, counting the hours until Natalie and the nurses would finally tell him it’s okay to sleep.
</p>
<p>
He was aware of everything. The short drive to the hospital. The wait in triage. The taking of his temperature and his blood and the lights being shined in his eyes and nose. The CT scan. The pills and the needles.
</p>
<p>
And the pain. At first he had felt it acutely in his face, in his ribs, in his foot, in the back of his head. But it diffused slowly, until eventually he simply felt it everywhere, inside and out. It sent his mind reeling, almost like a drug high. The agony was borderline euphoric.
</p>
<p>
“It’s your endorphins kicking in,” Natalie had said. “They work on your brain like morphine. That’s where the word ‘endorphin’ comes from, you know &mdash; ‘endogenous morphine.’ It’s basically heroin that your body makes naturally. Your body’s protecting itself. Making the damage a little easier to bear.”
</p>
<p>
“Natalie…,” he asked. “Why are you being so nice to me? We just met.”
</p>
<p>
“Yeah, but I… Uh… You seem pretty cool,” she said, blushing.
</p>
<p>
Natalie’s attention was taken away by a shadow on the other side of the hospital bed’s privacy curtain. 
</p>
<p>
“Doctor Rosenbaum?” said the voice of a young and harried nurse. “Can I speak to you for a minute?” 
</p>
<p>
Natalie squeezed Mike’s hand. “I’ll be right back, Mike. I have to take care of some paperwork.” She looked at his gamer buddies. Jason was in a corner talking quietly on his phone, and Satish and Moshen were oblivious to anything beyond their laptop screens. “Guys. Keep him talking, okay?”
</p>
<p>
Mike watched Natalie disappear behind the curtain. He heard her and the nurse discussing hospital business in hushed tones. Their voices slowly receded beyond a dark veil of delirium, gradually growing echoing and distant. 
</p>
<p>
“Mike! Mike, wake up!” Satish’s voice jarred him. “No sleeping!”
</p>
<p>
Mike groaned back to alertness.
</p>
<p>
Moshen poked him in the shoulder. “Miiiike’s got a giiiiiirlfriend,” he sang quietly.
</p>
<p>
Outside the privacy curtain, a few people approached, talking in distressed tones. As they got closer, he recognized one of the voices as the girl from the Tungsten building. 
</p>
<p>
It was Tina. She was sobbing.
</p>
<p>
“They know everything about me, Nat,” she was saying, her voice froggy. “They busted into my car. It was still sitting in the Tungsten parking lot. They got the registration and insurance papers and whatever else was in there. They know my address, my phone number, my Social Security Number…”
</p>
<p>
A shadow crossed the curtain and pulled it aside. Danny approached Mike’s bed, carrying plastic bags from Rite Aid. Natalie and Tina followed.
</p>
<p>
“Jason…” Danny said tensely. “I… I’m gonna need hazard pay.”
</p>
<p>
“What the hell is going on?” Jason said.
</p>
<p>
“The Russians called Tina,” Danny answered.
</p>
<p>
“Called <em>her</em>?” Jason repeated.
</p>
<p>
Tina said meekly, “They want me to help them incubate the stuff in the Eppendorf tube. They told me to meet them at my apartment in one hour, ‘or else.’”
</p>
<p>
“They think you can incubate it for them?” Jason asked with keen interest.
</p>
<p>
“Yes. Geez. It’s just <em>E. coli</em>. The incubation part is easy,” Tina said. “It’s figuring out what the hell to do with them once they’re grown that’s the hard part. You incubate them, you get a warm tub full of brown goo. Great. What do you do with <em>that</em>? I don’t know how the hell they expect me to figure that out. The only person who knows that, is Julie.”
</p>
<p>
“Julie Yen?” Jason asked.
</p>
<p>
Tina eyed him suspiciously. “How do you know Julie?”
</p>
<p>
Jason ignored the question. “Christina, is Julie working for these Russians?”
</p>
<p>
“I don’t know,” said Tina. “When that guy was holding me at gunpoint, he said some stuff that made me think she’s not exactly with them willingly.”
</p>
<p>
“And they’re trying to threaten you into ending up like her?” Jason asked.
</p>
<p>
Tina nodded meekly.
</p>
<p>
Jason rolled his eyes. “Pffft. Amateurs.”
</p>
<p>
“Come again?” Tina squeaked.
</p>
<p>
“Listen,” said Jason. “You actually hold a lot more cards than you think you do. A party only resorts to threats if they have nothing of value. If the first instinct of these Russians is to go straight for your jugular, then they’re approaching the negotiation from a position of weakness.”
</p>
<p>
Tina stared at him incredulously. “You’re saying the mob is in a ‘position of weakness’?”
</p>
<p>
“Oh, absolutely,” said Jason. “Think about it. They’re a criminal organization that’s at constant risk from both rivals and law enforcement. They have a lot to lose. I promise you, they give off the impression of being big and tough, but they’re a lot more scared of you than you are of them.”
</p>
<p>
“I highly doubt that,” said Tina.
</p>
<p>
“They’re issuing threats just to get you to the bargaining table in the first place. Their BATNA must be absolutely terrible.”
</p>
<p>
“What the hell is a BATNA?”
</p>
<p>
“A Best Alternative To a Negotiated Agreement,” Jason answered. “It’s your fallback strategy. Believe me, this stuff I know. I may be out of my league when it comes to tech, but they do teach you something in business school school, after all.”
</p>
<p>
“Christ,” Tina cried. “You’re talking business school lessons? We’re not dealing with a business here! We’re dealing with the mob!”
</p>
<p>
Jason smiled. “What do you think the mob is?” 
</p>
<p>
Tina stared at him in silence.
</p>
<p>
“Trust me,” said Jason, his tone steady. “Whatever else may be true about them, they’re rational players. They have to watch their bottom line, just like anybody else. I didn’t get rich by playing the lottery; I got rich by understanding what people want. So let’s try and understand these guys, okay? What do we know about them? What can we deduce about their needs, their risks, their motivations? Anything?”
</p>
<p>
Danny, standing nearby, smiled a wide grin. “I know a thing or two about them.” He pulled a cellphone out of his pocket and handed it to Jason.
</p>
<p>
Jason looked at the screen, perplexed. “What am I looking at here? An online bank statement? …Hmmm… It’s pretty fat… Who’s ‘Eugene Mukhayev’? And how are you seeing his… Oh… Oh! Oh holy shit!”
</p>
<p>
Danny let out a peal of maniacal laughter.
</p>
<p>
Satish and Moshen looked over excitedly. Mike craned his neck to look at the phone. Jason showed the screen to the men. Hoots and high-fives were exchanged.
</p>
<p>
“Guys, a lot of the emails are in Russian,” said Danny. “Could you guys run them through an online translator?”
</p>
<p>
Moshen took the phone. “No problem, Danny,” he said, and twirled back to his laptop.
</p>
<p>
Jason nodded approvingly. “Listen, guys, we’ve got them by the balls and they don’t even know it. We have everything they want, <em>and</em> we have leverage to make sure they play fair. Now, Christina, I can get you out of this. Do you trust me?”
</p>
<p>
“I don’t have much choice, do I?” she replied.
</p>
<p>
Jason extended a hand out to her with his palm up. “The vial, please.”
</p>
<p>
She shot him a look of suspicion so hot it could’ve ignited his gelled gray hair.
</p>
<p>
“It’s either me or the Russians.”
</p>
<p>
She grudgingly pulled the vial out of her purse and put it in his palm. Jason’s fingers curled firmly around it like the fronds of a carnivorous plant. 
</p>
<p>
He turned and said, “Moshen, can I have that phone when you’re done with it?”
</p>
<p>
“Take it,” said Moshen. “I’ve already forwarded all the emails to a disposable anonymous Yahoo account. I’ve got them all on my laptop now.”
</p>
<p>
Jason took the phone and poked at it. “Christina, is ‘Sergey’ the guy that called you?” 
</p>
<p>
Tina nodded.
</p>
<p>
“Alright, guys. I’m going to have a little chat with this Sergey fellow. And I’m going to do it on speakerphone, so I need all of you to be quiet.”
</p>
<p>
Jason stretched in his chair, cracked his knuckles, took several deep breaths, laid the phone on a counter next to Mike’s bed, and placed the call.
</p>
<p>
It rang.
</p>
<p>
A deep, resonant Russian voice rose from the cellphone. “Miss Giordano. I hope for your sake you are back in your apartment already.”
</p>
<p>
Jason leaned into the phone and said, quietly but confidently, “Sergey, I presume. You won’t be dealing with Miss Giordano anymore.” 
</p>
<p>
The voice responded slowly. “Who is this?”
</p>
<p>
Jason replied, “Listen, Sergey, I have a small vial filled with brown sludge. I’ve been told you’re interested in it. Maybe we can make a deal.” His tone was upbeat and friendly, like a salesman on a used car lot.
</p>
<p>
The voice paused. “What is your name?”
</p>
<p>
“Oh, come now, Sergey!” said Jason with good humor. “Why would you ask that?” 
</p>
<p>
“You tell Miss Giordano,” said Sergey, “that, whoever you are, she make huge mistake involving you in this.”
</p>
<p>
Tina’s eyes grew watery. She leaned against Natalie and struggled to remain silent.
</p>
<p>
Jason simply laughed. “She doesn’t know me, Sergey. She didn’t give me the vial by choice. Or this telephone, for that matter. Let’s just say I’m not a friend of hers.” As Jason talked, it became obvious why he preferred speakerphone; he gesticulated flamboyantly with his arms, making wide, dramatic gestures.
</p>
<p>
Sergey grumbled, “You tell that girl that I make it <em>her</em> problem to find out who you are. This changes nothing. I know her name and information, I can very easy to find her friends and family. She knows what will happen if I don’t get vial one way or other.”
</p>
<p>
Jason’s voice dropped. “Oh, Sergey, no. No. Come on. First of all, she has no contact with me. She has absolutely no way of giving in to your demands. Threatening her is only going to waste your time and put your manpower at unnecessary risk. And second… Look, Sergey, I know you’re not exactly in a very, shall we say, ‘wholesome’ line of work. But really? Making threats against young women, scaring them half to death? Is that how you manage your business? I’m sure you’re better than that. You’re obviously a man of power and stature. Don’t you feel like that kind of conduct is beneath you?”
</p>
<p>
Jason breathed deeply and silently through a long pause from Sergey’s end of the line. Finally, after several endless seconds, Sergey said, “Do you have a daughter?”
</p>
<p>
Jason thought before answering. “I do, as a matter of fact,” he said, his voice jovial but his face grim and calculating. “And I’ve got a son that just gave me a granddaughter.”
</p>
<p>
Jason’s friends shot him a look of horror at Jason’s willingness to reveal information about his family. Jason raised a palm reassuringly.
</p>
<p>
“You are a very blessed man,” Sergey said quietly. “I have a daughter as well. And I used to have a son.”
</p>
<p>
Jason said nothing in response. He let the line endure a few tense moments of silence.
</p>
<p>
Sergey’s slow, methodical baritone finally resumed. “If you do have the vial, then you should know that what is inside is very fragile. If you wish to do business with me, I need to have assurance that it is the vial I want, and that it still works.”
</p>
<p>
Jason said eagerly, “Makes sense to me, Sergey. Maybe if you give me instructions for processing it, I could run it through a test pass and make sure it works right for you. That sounds good, right?”
</p>
<p>
Sergey let out a cynical laugh. “I could not give you instructions even if I wanted to. This is not tiny pieces of Ikea furniture inside that vial. This is living crop. To raise it takes skill and training. You need to know what kind of food it needs, how much air and water to give it, how to protect it from getting sick. I am told that if it is not kept frozen, then it is probably sick already. You have not much time before it dies. Better for you if you just give it to me for safekeeping right away. Then we can discuss payment once vial is secure with me. Good plan, yes?”
</p>
<p>
“Oh, the vial looks perfectly fine to me,” Jason countered. He didn’t actually look at the vial, which remained engulfed within his fist. “What makes you think it’ll get sick?”
</p>
<p>
“Very simple. I have the scientist who created the… the mikrobi,” said Sergey confidently. “She is working for me. She is very familiar with crop and has made many batches with it.”
</p>
<p>
“This would be Julie Yen, I take it?” Jason said cautiously.
</p>
<p>
“You know of Miss Yen?” Sergey responded.
</p>
<p>
“Suppose I do,” Jason said.
</p>
<p>
“Well then you know,” replied Sergey, “that the vial is useless without her.”
</p>
<p>
Jason looked lost in thought for a moment. “Sergey… What kind of terms would you suggest for a, uh, rental, of sorts, of Miss Yen’s time?”
</p>
<p>
Sergey replied coldly, “That is not on the table.”
</p>
<p>
“I can be very generous…”
</p>
<p>
“Miss Yen’s expertise is not for sale,” said Sergey.
</p>
<p>
“We must be able to work something out,” Jason insisted.
</p>
<p>
“No,” Sergey spat. “No contact with Miss Yen. This is not an option. Do I make myself clear?”
</p>
<p>
“Crystal,” Jason said flatly, almost belligerently.
</p>
<p>
And with a press of a button, he abruptly ended the call.
</p>
<p>
All eyes in the room stared at Jason in stunned silence. Jason said nothing.
</p>
<p>
The phone began to ring. Jason immediately hit, “Ignore.”
</p>
<p>
Suddenly, he announced, “Moshen!” The kid snapped to attention. “What do the emails say anything about this Julie Yen girl?”
</p>
<p>
“They don’t say anything about any Julie Yen by name,” Moshen answered. “But I’ve learned about six different ways in Russian to say, ‘Oriental whore.’”
</p>
<p>
“What have you been able to learn so far?” Jason asked.
</p>
<p>
“Not a ton,” Moshen replied. “There’s as much English and Spanish as there is Russian in these emails. And my Spanish sucks, and the English is really, really bad English. It’s all ghetto slang and, like, innuendoes and shit.”
</p>
<p>
“Hmm.” Jason nodded knowingly. “Spanish, and gangbanger English… Let me take a guess. All the Russian-language emails are among a small tight group of people, and it’s mostly talking about high-level strategy and probably a bunch of family matters, right? And then everything else is in Spanish and English, and it’s all very short and specific, mostly giving orders and demanding status reports.”
</p>
<p>
Moshen nodded. “…Yeah. Yeah, I’d say that actually sums it up.”
</p>
<p>
Danny, from the side, chimed in. “So, wait, I get it. Their inner circle is all the same Russian family. But their foot soldiers are just random thugs that they hire from around the neighborhood, and it’s these, sort of, low-level employees, I guess, that do most of the day-to-day work. Right?”
</p>
<p>
Jason nodded. “Exactly. Moshen, do they say where they’re keeping her?”
</p>
<p>
“Not quite,” Moshen said. “They mentioned something about making her set up a factory in a rented warehouse space. Or set up a warehouse in a rented factory space.”
</p>
<p>
Danny suggested, “You know, that phone has GPS…”
</p>
<p>
Jason passed the gangster’s cellphone to Danny. “Can you see where he’s been?”
</p>
<p>
Danny gave the phone a few quick pokes. “AT&amp;T Navigator… Recent Places… Done.” He turned the screen back to Jason.
</p>
<p>
Jason looked at it. “Promising, but there’s over three dozen addresses in that history list. Can we narrow it down?”
</p>
<p>
“Moshen…” Danny handed him back the phone. “Hop on Google Maps and start looking up these addresses, ok? They said they’re going to make her work at a factory or warehouse, right? Use Satellite View to check which of these are in industrial zones.”
</p>
<p>
Moshen got to work.
</p>
<p>
Danny turned back to Jason. “So… Assuming you do find this Julie girl, what’s your plan? We can’t exactly just drive over there and ring the doorbell and be like, ‘Hi! We’re here to pick up the girl!’ Do warehouses even have doorbells?”
</p>
<p>
Jason nodded. “I know. It’ll be tricky. I’m hoping I might be able to find a random low-ranking worker and bribe him.”
</p>
<p>
Danny shook his head. “It’d have to be one hell of a bribe, Jason. A guy like that could end up at the bottom of Puget Sound.”
</p>
<p>
“Yeah, I’d have to make the payout big enough to be worth the risk,” Jason said sourly. “And besides, if they thought one of their own was on the take, all hell would break loose. I don’t know exactly what the Russian mafia’s disaster plan is for internal espionage, but I’ve seen what happens at companies when management thinks some employees might be secretly working for a competitor. It isn’t pretty.”
</p>
<p>
Danny looked away pensively. “What if…”
</p>
<p>
“What if what?” asked Jason.
</p>
<p>
“What if that was the point?” Danny offered.
</p>
<p>
Jason cocked his head. “Not following…”
</p>
<p>
Danny turned to his fellow computer geeks. “Guys. Listen up. Do any of you happen to have admin privileges on an SMTP server?”
</p>
<p>
Mike stirred. Slowly, feebly, he raised one hand.
</p>
<p>
Danny smiled. “Of course. From your Cisco certification classes.”
</p>
<p>
Mike nodded. “The teacher gives us a couple of servers to play with,” he said softly.
</p>
<p>
Danny replied, “Can you configure it to bypass all authentication mechanisms and function as an open mail relay?”
</p>
<p>
Mike furrowed his large brow. “Yeah, but we’re not supposed to do that. The very first thing we learn in the unit on mail servers is how to <em>prevent</em> them from running as open mail relays.”
</p>
<p>
Danny grinned. “And why exactly is that?” 
</p>
<p>
“Because open mail relays are very bad things,” Mike answered simply. “Spammers from all over the world constantly search the Internet looking for them. Open mail relays are where all those spam messages for penis enlargement pills and herbal Viagra and discount mortgages and shit come from.”
</p>
<p>
“Yep. And why do spammers need open mail relays for that?” Danny asked Socratically.
</p>
<p>
“Because open relays are completely anonymous,” Mike answered, just barely managing a shrug. “An open relay doesn’t verify the source of the message. It just forwards everything stupidly along.”
</p>
<p>
An evil grin consumed Danny’s face. “Exactly. So, if we wanted to forge a bunch of emails from the Russian mob guys to their foot-soldiers…”
</p>
<p>
Mike widened his eyes. “…We’d need an open mail relay!”
</p>
<p>
Eagerly, the large scruffy man grabbed a laptop. The computer seesawed on his lap as he punched his fingers against the keyboard.
</p>

<pre class="computer">
<strong>telnet localhost 25</strong>
</pre>

<p>
The terminal window replied:
</p>

<pre class="computer">
220-mail46.cisco.bellevuecollege.edu ESMTP Exim 4.69 #1
220-This computer system is solely for use by Bellevue 
220 College staff and students enrolled in classes for 
220 Cisco Certified Network Administration certification 
220 exams. 
220-We do not authorize the use of this system to 
220 transport unsolicited, and/or bulk e-mail.
</pre>

<p>
The empty cursor blinked alone on the blank line below the message. Mike knew that it was waiting for a few words of SMTP, the primitive language spoken by mailservers since the dawn of the Internet. He answered it in kind, and he and the computer enjoyed a short and to-the-point conversation.
</p>

<pre class="computer">
<strong>MAIL FROM:sergey@pash.ly</strong>

250 OK

<strong>RCPT TO:eugene@pash.ly</strong>

250 Accepted

<strong>DATA</strong>

354 Enter message, ending with "." on a line by itself

<strong>
To: "Eugene &lt;eugene@pash.ly&gt;"
From: "Sergey &lt;sergey@pash.ly&gt;"
Subject: This is a test
Mary had a little lamb, whose fleece was white as snow.
.
</strong>

250 OK id=1Kervv-0002Di-VE
</pre>

<p>
“What happens now?” asked Jason.
</p>
<p>
“The message has to bounce around the intertubes for a bit,” said Mike. 
</p>
<p>
“Does that take long?”
</p>
<p>
In reply, the Pantech chirped. Mike glanced at the screen and proudly held it up to Danny. Danny took the phone from Mike with a look of exquisite approval. 
</p>
<p>
Satish eyed Danny reproachfully. “What kind of plan is this, Danny? So, you can forge their emails. So what? How do you think that helps you?”
</p>
<p>
Danny replied, “Two words for you, Satish.”
</p>
<p>
“And those would be…?” 
</p>
<p>
“Byzantine General.” 
</p>
<p>
Everyone except for Danny and Satish exchanged quizzical glances.
</p>
<p>
“What about it?” Satish asked defiantly.
</p>
<p>
“You know how to break a Byzantine army, right?” Danny goaded.
</p>
<p>
“Sure. Yeah,” Satish countered. “What’s your point?”
</p>
<p>
“Now that we can forge their emails, we can induce a Byzantine failure mode,” Danny replied.
</p>
<p>
“In what?” said Satish. “In their mailserver?”
</p>
<p>
“No,” Danny said, beaming wickedly. “In their foot-soldiers.”
</p>
<p>
Satish shook his head, aghast. “You’re insane.”
</p>
<p>
“Yep!” Danny said proudly. Turning, he asked, “Moshen, do you have a street address for us?”
</p>
<p>
“I think so, Danny.” Moshen turned his laptop around. A satellite image took up the entire screen, showing an overhead view of Seattle’s long southward stretch of shipping yards lining the silty gray runoff-thickened waters of the Duwamish River. “I’d say that looks like an industrial zone, right?”
</p>
<p>
 “Danny,” Jason asked, “what the hell is this Byzantine General thing?”
</p>
<p>
“So glad you asked!” said Danny. “Grab your car keys. I’ll explain on the way.”
</p>
</div>