<div class="chapsection">
<p>
<span class="caplead">Eternity seemed to pass</span> between when she pressed the button and when she saw the lights come on. She stood nervously outside the door, self-consciously sweeping her hair aside. In her hands were white plastic Rite Aid bags, which she held in front of her like a flower girl with a basket of petals.
</p>
<p>
Finally, she heard a soft shambling inside the house. She wiggled her waist for poise, and gave a sharp exhale to regain composure. She wished she’d had more time to fix her makeup, but the rush-job she had done in the rear-view mirror would have to suffice.
</p>
<p>
The doorknob turned. She was greeted by a geeky zombie in slippers and blue linen pajamas.
</p>
<p>
Danny stared at her bleary-eyed. 
</p>
<p>
“Tina?” he said.
</p>
<p>
She looked up at him apologetically. “I totally woke you up, didn’t I? I’m so sorry… I knew you’d probably be asleep…” Her voice came out thin and weak.
</p>
<p>
Danny stared at her with utter confusion.
</p>
<p>
“I asked Nat to text Jason for your contact info,” Tina explained. “He said he’d just dropped you off…”
</p>
<p>
Danny tried to give her a friendly smile. Instead, his face winced with exhaustion. The corners of his eyes crinkled heavily, and for a moment he looked every bit of his almost forty years of age. “It’s okay. Come on in.”
</p>
<p>
The soles of her black low-heel pumps tapped softly against the tile of Danny’s foyer. Tina looked around, delighted and relieved to see a civilized, ordered abode. She’d been worried that Danny’s place might look like Roger’s, a giant tangled mess of laptops, laundry, and KidRobot dolls. And Natalie’s living conditions, of course, were even more chaotic. Tina desperately needed a sense of order at the moment, and Danny’s house looked refreshingly sane. It was clean, sensible, uncluttered &mdash; and had a seriously sick entertainment system.
</p>
<p>
Danny wordlessly took the plastic Rite Aid bags from her and carried them to the granite kitchen counter, then mindlessly began shuffling back to the bedroom. After a few short steps, he stopped, blinked a few times, turned to her and said, “So… uh… what brings you by?”
</p>
<p>
“Well, I… I know this is kind of coming out of nowhere, but could I… Would you mind if I crashed here tonight?”
</p>
<p>
Danny blinked at her uncomprehendingly, and yawned.
</p>
<p>
She looked away. “I’m sorry, I shouldn’t have come,” she said, trying to keep her voice from cracking. “It’s almost three o’clock in the morning… I totally don’t mean to impose, I’m…” She noticed that her hands were wringing as she talked.
</p>
<p>
“Don’t worry about it,” Danny said. “Of course you can stay. But, why…?”
</p>
<p>
“Thank you. Thank you so much. I hate being any trouble. It’s just that… I’m… I’m really scared to go home…” Her lips began to tremble. She put her hands near her face to hide her mouth. She felt like a tiny, helpless creature, and she hated it. “The Russians know everything about me. They know where I live. And I just keep thinking, I’m going to walk into my place and there’s going to be someone there &mdash; in my apartment &mdash; waiting for me…”
</p>
<p>
Tina couldn’t contain her distress anymore. She put her face in her hands and, shoulders hunched, began to sob into her palms. She huddled her body away from Danny, feeling pathetic and ashamed.
</p>
<p>
Danny padded around the kitchen’s granite peninsula toward her. “Shhhh, it’s alright,” he said, his voice groggy but warm. “They won’t find you here. They don’t know me. You’ll be okay.” He put a reassuring hand on her shoulder, and spread his arms to offer a hug.
</p>
<p>
Eagerly she entered his embrace, setting aside her self-consciousness to partake in the comfort. She pressed her face and hands against his chest and cried into his pajamas like a terrified and hurt child. His arms wrapped protectively around her, and he bowed his head to rest his cheek against her hair. The pressure of his warm, dexterous hands against her back filled her with a sense of safety and peace. He was not especially muscular, but he was toned and lean, and his long arms held her in a firm sanctuary. Her body melted against his. He smelled like Irish Spring and fresh linen, and felt like home.
</p>
<p>
When the last of her arrhythmic sobs shook out of her and her breathing regained its natural cadence, she gently pulled away from him. “Sorry about your PJs,” she said with an embarrassed smile as she batted at a tiny tear-stain, her voice froggy.
</p>
<p>
He smiled at her warmly. “You want some, like, tea or anything?”
</p>
<p>
She nodded enthusiastically, and took a seat on a stool at the counter.
</p>
<p>
He fished a kettle out of a cabinet filled with pots and pans, making plenty of clanking in the process. As he filled the kettle in the sink, Tina noticed his new bandage.
</p>
<p>
“What happened to your hand?”
</p>
<p>
“Fire,” he said absentmindedly. “Kerosene. Spark gap. Fumes. Boom. Everything burning. Also, I cut it on glass. Uh… oh yeah, your doctor friend isn’t gonna get her sweatshirt back.” He set the kettle on the electric stove.
</p>
<p>
Tina stared at him, at a loss for words.
</p>
<p>
He stopped his tea-making for a moment and said, “It’s been a long night.”
</p>
<p>
Tina shook her head in wonder. “Did you find Julie?” 
</p>
<p>
Danny looked away. “She’s dead.” 
</p>
<p>
“Oh my God…”
</p>
<p>
“The Russians killed her. I watched it happen.”
</p>
<p>
Tina’s skin crawled. “God… I didn’t like her, but I never…”
</p>
<p>
“And they got the vial. After everything that’s happened tonight, in the end the Russians got the vial. Figures, right?” He stared at the floor blankly. “Just fucking figures…”
</p>
<p>
The kettle whistled.
</p>
<p>
Danny poured cups for the two of them and joined her at the counter. “But it wasn’t a total failure. We learned what the stuff in the vial does. Want to take a guess?”
</p>
<p>
“Biological warfare agent?” Tina tried.
</p>
<p>
“Nuh-uh. Turns out it’s a cocaine-making biomachine. It takes some stuff called ‘glutine’ or ‘glumine’ or something like that…”
</p>
<p>
“Glutamine?”
</p>
<p>
“Yeah, that’s it,” said Danny as he sipped. “You feed it that stuff and it turns it into cocaine. Crazy, right?”
</p>
<p>
Tina held her cup of tea in both hands and gave a slight shrug, smiling.
</p>
<p>
“You don’t seem too shocked,” said Danny.
</p>
<p>
“Eh. I was the one that filed Tungsten’s paperwork for all their FDA and DEA authorizations. I’ve seen stuff about cocaine cross my desk a lot. It’s kind of surprising, but kind of not. And it actually works? The <em>E. coli</em> in that vial actually runs the entire metabolic pathway for cocaine biosynthesis?”
</p>
<p>
“Apparently,” Danny said with a nod. With a warm chuckle he added, “Heh. Listen to you! ‘Metabolic pathway for biosynthesis.’ That’s the kind of stuff that intern girl was saying. Do all you bio people talk like that?”
</p>
<p>
Tina looked away bashfully. “I’m not really a bio person, you know. I’m just their office admin.”
</p>
<p>
“Oh come on,” he said. “You can obviously hold your own. I bet the only thing keeping you from being a real bio person is just the fact that you don’t see yourself as one.”
</p>
<p>
Tina looked at him with eyes wide and hopeful. “You really think so?”
</p>
<p>
“Sure,” Danny said, mumbling through exhaustion. “But, I mean, don’t ask me. Look at your friend, for example. That doctor girl. She obviously knows what she’s doing, right? And I know that smart people tend to gravitate toward other smart people, so…”
</p>
<p>
At the mention of Natalie, Tina’s expression soured. She looked away sadly.
</p>
<p>
“What’s wrong?” Danny asked.
</p>
<p>
Tina’s face bore a distant frown. “Natalie and I had a kinda-sorta fight.”
</p>
<p>
Danny blinked uncomprehendingly. “A fight?”
</p>
<p>
“Yeah. It’s kind of why I’m here tonight.”
</p>
<p>
Danny seemed to think really hard before coming up with his most earnest facsimile of sympathy. “I’m… sorry?”
</p>
<p>
“Don’t get me wrong, we’re totally still BFFs,” Tina amended. “I mean, she let me borrow her car here and everything. But… some pretty heavy stuff came out.”
</p>
<p>
“What kind of heavy stuff?” Danny asked.
</p>
<p>
“Well…”
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Natalie had stayed with Mike</span> for as long as she could. She watched with delight as he and his two dorky friends forged emails from the Russians. The whole sequence had barely taken more than an hour, and Natalie looked on like a teenage girl watching her all-star dream-boy playing hockey from the end of the rink.
</p>
<p>
Afterward, she and Mike flirted openly, casting coy glances and saying clever, adorable things to each other.
</p>
<p>
“You guys!” Moshen said. “Get a room already, will you?”
</p>
<p>
“We have one,” Mike replied from his hospital bed. “You’re in it.”
</p>
<p>
Tina spent most of the time standing in the corner, irritated.
</p>
<p>
Eventually, the trauma ward staff pulled rank on Natalie and shooed the visitors away. Reluctantly, Natalie bid Mike farewell.
</p>
<p>
“Here, let me give you something to help you stay awake,” she said slyly, and leaned down over him. Beneath his smashed nose, his mouth was mostly uninjured. 
</p>
<p>
She put a hand against Mike’s hairy face and planted a deep, firm kiss. 
</p>
<p>
He reciprocated, leaning into her lips as much as he could. He lifted a hand to put behind her head, his large fingers weaving through her frizzy hair. His heart monitor registered an increase in his pulse.
</p>
<p>
Natalie slowly drew away, glowing. “I’m writing you a prescription for those,” she said with a smirk. “Expect more of them.” 
</p>
<p>
When the two young women returned to Natalie’s apartment, her face was still glowing. She looked at Tina speechlessly with an excited conspiratorial grin, able only to squeeze out a high-pitched, “Eeeee!” as commentary on her night’s experience.
</p>
<p>
Tina’s mood wasn’t anywhere near as jovial.
</p>
<p>
“God, what am I going to do about work tomorrow, Nat?” Tina fretted as she planted herself on the dilapidated couch. She lifted her knees up to her chest and wrapped her arms around her legs. “The whole office is smashed up. There’s bullet holes in the walls.”
</p>
<p>
Natalie replied, “Just call the cops…” Her voice was light and breezy. After a pause, she added, “No, wait. Don’t. You could get Mike and his friends in trouble.” Natalie noticed her cat rubbing against her leg. She greeted the little gray fuzzball enthusiastically with a cartoonish voice, and scooped him up to pet him with long, loving strokes.
</p>
<p>
“Well, the cops have to get involved at some point,” Tina figured. “God, and my car is still there! Shit! Nat, I’m going to need to borrow yours. Is that alright? If I even go into work tomorrow. You think I should? Or maybe I should just lay low for a day or two.”
</p>
<p>
“That’s fine,” said Natalie absentmindedly as she nuzzled her face against her cat’s fur. “I usually just walk to work anyway.” She carried her furry gray friend into her kitchen and managed to find a bag of cat treats somewhere amidst the soup cans and potato chips. After dispensing a few crunchy bits onto the floor and letting her cat jump down to enjoy them, she looked around her biohazard of a kitchen. She put her hands on her hips and pursed her lips off to one side, scanning the area with thoughtful displeasure.
</p>
<p>
“So you <em>do</em> think I should go to work tomorrow?” Tina asked tensely. “But that means I’ll show up and Drippy will be like, ‘What the hell happened here?’ and what am I supposed to say? ‘Yeah, I was here but I didn’t get a chance to call you or the cops, because I… uh…’ I mean, it’s not like I can just play dumb, right? Should I just, like, hide until Drippy calls me, or what?”
</p>
<p>
“Yeah, that’s probably a good idea,” said Natalie. Her gaze landed resolutely on the kitchen sink, barely visible under the dirty dishes and silverware. She marched up to it, cleared some room around the tap, and set the hot water to full blast. The sponge next to the sink smelled of mildew, but a thick slathering of lemon-scented dish soap exorcised the odor quickly. Natalie pulled on a pair of rubber gloves and got to work.
</p>
<p>
Tina glared in Natalie’s direction. “God damn it, Nat! Are you even listening?”
</p>
<p>
Natalie shut off the tap. “I’m sorry, hon. I couldn’t really hear you with the water running. What’s up?”
</p>
<p>
“‘What’s up’?” Tina snapped. “What’s up is that I’m scared for my life here! I don’t know what to do, and I need your help, and you’re over there doing some… Wait a minute… You’re…?” Her expression shifted from anger to shocked confusion. “…Cleaning? Holy shit! Nat, are you <em>cleaning</em>?”
</p>
<p>
Natalie stopped the dishwashing immediately, and her face sank in embarrassment. She peeled off the gloves and came around to join her friend on the couch in the living room. The cushions shifted under Tina as her heavy friend sat down. “God, you’re absolutely right. T, I’m so sorry! I’ve totally been ignoring you, haven’t I? I guess I’m just a little… distracted…” She smiled self-deprecatingly.
</p>
<p>
Tina inched away from her friend on the off chance that she might be demonically possessed. “I’ve known you since we were teenagers, and not once have I ever seen you do the dishes.”
</p>
<p>
Natalie shrugged, “Yeah, well. I just looked around and thought to myself, ‘You know, I should make this place look a little nicer.’ ”
</p>
<p>
“What’s gotten into you, Nat? I’ve never seen you so…”
</p>
<p>
“So what? So giddy?” 
</p>
<p>
“Yeah. About a <em>guy</em>,” said Tina.
</p>
<p>
Natalie looked away mischievously. “I know! Isn’t it great?”
</p>
<p>
Tina shook her head. “That’s just really not like you.”
</p>
<p>
“What, I’m not allowed to be into a guy?” Natalie said with a giggle. “That’s against the rules?”
</p>
<p>
Tina nodded. “Kind of, yeah.”
</p>
<p>
“What do you mean?” Natalie chuckled.
</p>
<p>
“I just thought that you were above that,” Tina shrugged.
</p>
<p>
There was a subtle shift in Natalie’s face. She still smiled, but her brow furrowed and her eyes set on Tina with a hint of irritation. “Above what?”
</p>
<p>
“You know. Men. Dating. Relationships. I just thought you weren’t into it.”
</p>
<p>
The glow of bliss began to fade from Natalie’s face. “Why on Goddess’s green Earth would you think that?”
</p>
<p>
“Because, you’ve always been all about your studies,” Tina said, growing a bit defensive. “Your wicca stuff, your school stuff, your work stuff. You know. Important things.”
</p>
<p>
Natalie blinked at her in bewilderment. “‘Important things’? You think <em>those</em> are important things?”
</p>
<p>
“Well, aren’t they?” Tina said.
</p>
<p>
Natalie reached down to the floor next to the couch. “Let me show you something.” From a pile of random junk that she had moved off of the couch earlier that night, Natalie produced a knotted silk handkerchief wrapped around a clump of twigs. “Do you remember what this is?”
</p>
<p>
“Yeah,” said Tina. “It’s a love charm.”
</p>
<p>
“It’s the material component of a love summoning spell,” Natalie corrected. “It’s supposed to draw your soulmate to you.”
</p>
<p>
Tina nodded with a nostalgic smile. “Ah, right! I remember you and me used to cast those back in high school.”
</p>
<p>
Natalie held it up in front of herself and said, “I’ve cast one every month for the last ten years.”
</p>
<p>
Tina looked back and forth between the bundle and her friend. “I… I don’t get it, Nat,” she stammered. “You’ve always been so confident and comfortable in your own skin… You’ve never needed to have a guy in order to feel complete. Since when have you been desperate to be with someone?”
</p>
<p>
“Since always,” Natalie replied.
</p>
<p>
Tina shook her head. “I’ve always been the one that’s obsessed with boys. You’ve always been the one that’s got her life together.”
</p>
<p>
Natalie swept her arms out to gesture at the apartment. “Does it <em>look</em> like I’ve got my life together?”
</p>
<p>
Tina rolled her eyes. “Yes, your apartment’s messy. But so what? Big fucking deal. Nat, in the grand scheme of things you’re a success…”
</p>
<p>
“No, T. I’m a wreck,” Natalie replied. “A crazy, unattractive, workaholic wreck that men won’t touch with a ten-foot pole.”
</p>
<p>
“Nat, you’re not…” Tina started.
</p>
<p>
“And frankly,” Natalie interrupted, “I’ve never understood why you’ve always failed to see that.”
</p>
<p>
“Because it’s not true, Nat,” Tina protested. “I don’t understand where all of this is coming from.”
</p>
<p>
Slowly and somberly, Natalie said, “Yes, you do, T.” She looked down and gestured at her body. The side of the couch on which she sat see-sawed considerably lower than Tina’s. “Yes, you do.”
</p>
<p>
Tina sighed softly. “Nat, come on. Don’t be silly,” she said with forced gentleness. “You’ve always been, you know, big-boned. I’ve never seen it get you down. When has your weight ever been a problem?”
</p>
<p>
“When has it ever not been a problem?” Natalie threw back. “You haven’t seen it get me down because you’ve never looked.”
</p>
<p>
“What are you talking about?” Tina protested. “I’ve seen you having fun with guys! What about our last trip to Alki Beach? Or any of the thousands of times you and I have gone out on the town together? Boys see us hanging out, and they’re always like, ‘Hey! Who are those hot girls?’ They come over, chat us up, buy us drinks, try desperately to get into our pants. Hilarity always ensues.”
</p>
<p>
Natalie looked at her darkly. “T… That’s not how it ever plays out from <em>my</em> point of view.”
</p>
<p>
“What do you mean?”
</p>
<p>
“They don’t hit <em>us</em>, T,” Natalie said bitterly. “They hit on <em>you</em>. I’m an obstacle. I’m a cock-block. I’m a grenade that one guy in the group agrees to jump on. They always have some designated schmuck who comes and distracts me so his buddies can mack on you.”
</p>
<p>
“What?” Tina sputtered. “Nat, where are you getting this…?”
</p>
<p>
“From paying attention!” said Natalie, struggling against her agitation. “Look, T, you don’t see it for what it is, because the unspoken social dynamic always plays out in your favor. But the fact is, whenever it comes to guys, it’s always been all about you. You’ve always been the prize. I’ve always been just the fat, weird best friend.”
</p>
<p>
Tina shook her head in bewilderment. “Nat, there have been guys that are into you…,” she said uncertainly.
</p>
<p>
“No, there really haven’t,” Natalie replied grimly.
</p>
<p>
“You’ve had boyfriends, Nat...”
</p>
<p>
Natalie challenged, “Name one.”
</p>
<p>
Tina opened her mouth to speak, but nothing came out. Her eyes drifted upward as she scrolled through memories of high school, of college, of their early adult lives together, searching for images and vignettes of short-lived romances both silly and sordid. The only misadventures that came to her mind were her own.
</p>
<p>
Natalie interrupted her silent scouring with a hand on Tina’s shoulder. “Look, it’s not that big of a deal,” she said with tense calmness. “I don’t mind playing to type. I’ve learned to kind of enjoy the awkward social situations that result from it. And every now and then I meet some genuinely interesting guys with you and enjoy some decent conversation. But T, let’s face it: I’ve never really had a love life of my own. You’ve always been the one to whom relationship stuff happens. I’ve always felt… ancillary. Like a note in the margin.”
</p>
<p>
Tina stared at her friend dumbfounded. “Nat, you…? You see <em>yourself</em> as marginal? Compared to <em>me</em>?”
</p>
<p>
Natalie looked away bashfully. “I kind of always have.”
</p>
<p>
“Nat, that’s… that’s absurd!” Tina said with laughter that bordered on tears.
</p>
<p>
With a warm but pained smile, Natalie asked, “Why should it be absurd?”
</p>
<p>
“Because…” Tina stammered. “Because that’s what <em>I’ve</em> always… Because that’s what I always thought <em>I</em>… Nat, you’ve always been my rock… I always thought I’m the one whose life is a giant mess and you’re the one who’s got all the answers…”
</p>
<p>
With her eyes red and puffy, Natalie let out a somber, bittersweet laugh. “T, I don’t know anything more about how this whole ‘life’ thing works than you do.”
</p>
<p>
The two women wrapped their arms around each other and shared a long, tight hug. It was cathartic, and apologetic, and forgiving, and thankful, and restorative. They didn’t cry, they didn’t speak. They didn’t need to. 
</p>
<p>
They pulled away and smiled at one another. Natalie’s face began to regain its happy glow.
</p>
<p>
“So…” Tina said, her voice soft but chipper. “You’ve got a new boyfriend, then.”
</p>
<p>
Natalie’s gaze floated off to the ceiling. She grinned widely. “Yeah. Yeah, I do. He <em>likes</em> me, T. He likes <em>me</em>! I can see the way he looks at me and talks to me. He actually seems to think I’m cool. Me! A guy thinks I’m cool!”
</p>
<p>
Tina replied brightly, “And don’t forget brilliant and awesome!” 
</p>
<p>
“And he likes me for that!” Natalie agreed, beaming. “He doesn’t see it as some kind of threat or liability or something, like a lot of guys do. And <em>he’s</em> brilliant. And <em>he’s</em> awesome! He’s strong, and he’s brave, and he’s funny. And he’s so humble about it all…”
</p>
<p>
Tina giggled lightly. “He does seem like a really great guy. I’m happy for you, Nat. I really am. And listen… When it comes to relationships and handling yourself with guys, I’ve been through one or two or thirty myself. So, I might know a thing or two about how they go. And I know you’re a psychiatrist and you’re incredibly smart and you can figure out just about everything on your own. But, Nat, I want you to know… If you ever feel like you’re out of your element, or in over your head, or you just want some help…”
</p>
<p>
With a smirk, Natalie said, “Actually, I could use a hand with the dishes…” 
</p>
</div>

<div class="chapsection">
<p>
<span class="caplead">Tina took a final sip</span> from her tea. “I felt like that was a good note to leave on,” she told Danny. “Housework aside, I felt like I needed some space. To digest the conversation, you know? Besides… I really hate sleeping on that couch of hers.”
</p>
<p>
Danny smiled. “Well, as it so happens, Tina,” he said sweetly, “the sleeping arrangements here are quite comfy.” He hopped down from his stool and stood beside her. 
</p>
<p>
“Oh really?” she coyly replied. She found the act of telling him about her night’s experiences with Natalie cleansing and cathartic. Tina felt unburdened, at ease. She looked up at him with eager, expectant eyes.
</p>
<p>
Danny reached out to touch her. She inched forward on her stool. His hand landed on her arm.
</p>
<p>
He gave her a quick pat and said, “Let me go get you some sheets.” He rushed off to his bedroom, came out a few moments later carrying blankets and a pillow, and zoomed off to the living room to dress the couch.
</p>
<p>
He didn’t see Tina following him with her gaze, pouting with a tinge of disappointment.
</p>
<p>
“Hey, Danny…” she said.
</p>
<p>
“Yah?” he called back from the living room.
</p>
<p>
“You know…” she said, “Finding a safe place to sleep isn’t the only reason I came over here tonight.”
</p>
<p>
“It’s not?” He trotted back to the kitchen.
</p>
<p>
She paused until he approached. “I brought you something…”
</p>
<p>
He raised an eyebrow, Spock-like. “What kind of something?” 
</p>
<p>
The white plastic Rite Aid bags lay at the end of the counter. Tina rifled through them for a moment, their plastic crinkling sounds filling the still house. She pulled out a white latex glove. It was turned inside-out, and twisted and knotted near the base of the digits.
</p>
<p>
Danny looked at it quizzically.
</p>
<p>
“Do you remember,” Tina asked him, “when we were back at the Rite Aid, when I first saw that the bacteria had formed a biofilm? Remember I scraped out a little bit of it from the Eppendorf vial and held it in my fingers with this glove?”
</p>
<p>
Danny nodded.
</p>
<p>
“Come take a look,” she said. She pinched a small segment of the inverted latex glove and stretched it tight against her fingers. Danny leaned in to see.
</p>
<p>
Inside the glove, preserved in the latex, was a small crumb of yellowish brown crusty substance, barely a few millimeters wide.
</p>
<p>
“Holy shit…” Danny gasped.
</p>
<p>
“See?” said Tina. “You were beating yourself up about losing the vial. I figure this should cheer you up.”
</p>
<p>
Danny nodded excitedly. “Is that one tiny little flake enough to work with?”
</p>
<p>
“In theory it only takes one bacterium to grow an entire colony,” Tina answered.
</p>
<p>
“But are they still alive?” asked Danny. “And even if they are, can you wake them up out of that filmy stasis panic mode thing without killing them?”
</p>
<p>
Tina flashed him an excited grin. “There’s only one way to find out.” 
</p>
</div>
